(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function l(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var w=aa(this);function x(a,b){if(b)a:{var c=w;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}
x("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(g||"")+"_"+f++,g)}function c(g,d){this.h=g;q(this,"description",{configurable:!0,writable:!0,value:d})}if(a)return a;c.prototype.toString=function(){return this.h};var e="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0;return b});
x("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=w[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&q(e.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(l(this))}})}return a});function ba(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ca(a){return a.raw=a}function y(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:l(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function da(a,b){a instanceof String&&(a+="");var c=0,e=!1,f={next:function(){if(!e&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}e=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}
x("Array.prototype.keys",function(a){return a?a:function(){return da(this,function(b){return b})}});var A=this||self;function B(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.B=function(e,f,g){for(var d=Array(arguments.length-2),h=2;h<arguments.length;h++)d[h-2]=arguments[h];return b.prototype[f].apply(e,d)}}function C(a){return a};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}B(D,Error);D.prototype.name="CustomError";function E(a,b){a=a.split("%s");for(var c="",e=a.length-1,f=0;f<e;f++)c+=a[f]+(f<b.length?b[f]:"%s");D.call(this,c+a[e])}B(E,D);E.prototype.name="AssertionError";var ea={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var F;function G(){if(void 0===F){var a=null,b=A.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:C,createScript:C,createScriptURL:C})}catch(c){A.console&&A.console.error(c.message)}F=a}else F=a}return F};function H(a,b){this.g=a===I&&b||"";this.u=J}H.prototype.i=!0;H.prototype.h=function(){return this.g};function K(a){return a instanceof H&&a.constructor===H&&a.u===J?a.g:"type_error:Const"}var J={},I={};function L(a){this.g=a;this.i=!0}L.prototype.toString=function(){return this.g.toString()};L.prototype.h=function(){return this.g.toString()};function M(a){this.g=a}M.prototype.toString=function(){return this.g+""};M.prototype.i=!0;M.prototype.h=function(){return this.g.toString()};function N(a){return a instanceof M&&a.constructor===M?a.g:"type_error:TrustedResourceUrl"}
function fa(a){var b=K(new H(I,"https://cse.google.com/cse.js?cx=%{cx}"));if(!ha.test(b))throw Error("Invalid TrustedResourceUrl format: "+b);var c=b.replace(ia,function(e,f){if(!Object.prototype.hasOwnProperty.call(a,f))throw Error('Found marker, "'+f+'", in format string, "'+b+'", but no valid label mapping found in args: '+JSON.stringify(a));e=a[f];return e instanceof H?K(e):encodeURIComponent(String(e))});return ja(c)}
var ia=/%{(\w+)}/g,ha=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),ka={};function ja(a){var b=G();a=b?b.createScriptURL(a):a;return new M(a,ka)};function O(a){if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ra,"&#0;"));return a}var ma=/&/g,na=/</g,oa=/>/g,pa=/"/g,qa=/'/g,ra=/\x00/g,la=/[\x00&<>"']/;function P(a){this.g=a}P.prototype.toString=function(){return this.g.toString()};P.prototype.i=!0;P.prototype.h=function(){return this.g.toString()};function Q(a){return a instanceof P&&a.constructor===P?a.g:"type_error:SafeUrl"}var sa=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,ta=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;
function ua(a){if(a instanceof P)return a;a="object"==typeof a&&a.i?a.h():String(a);ta.test(a)?a=new P(a,R):(a=String(a).replace(/(%0A|%0D)/g,""),a=a.match(sa)?new P(a,R):null);return a}var R={},va=new P("about:invalid#zClosurez",R);var wa={};function S(a){this.g=a;this.i=!0}S.prototype.h=function(){return this.g};S.prototype.toString=function(){return this.g.toString()};var xa=new S("",wa);
function ya(a){if(a instanceof P)return'url("'+Q(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof H)a=K(a);else{a=String(a);var b=a.replace(za,"$1").replace(za,"$1").replace(Aa,"url");if(Ba.test(b)){if(b=!Ca.test(a)){for(var c=b=!0,e=0;e<a.length;e++){var f=a.charAt(e);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c&&Da(a)}a=b?Ea(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new E("Value does not allow [{;}], got: %s.",[a]);return a}
function Da(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,e=0;e<a.length;e++){var f=a.charAt(e);if("]"==f){if(b)return!1;b=!0}else if("["==f){if(!b)return!1;b=!1}else if(!b&&!c.test(f))return!1}return b}
var Ba=RegExp("^[-+,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$"),Aa=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g"),za=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|steps|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g"),Ca=/\/\*/;
function Ea(a){return a.replace(Aa,function(b,c,e,f){var g="";e=e.replace(/^(['"])(.*)\1$/,function(d,h,k){g=h;return k});b=(ua(e)||va).h();return c+g+b+g+f})};var Fa={};function T(a){this.g=a;this.i=!0}T.prototype.h=function(){return this.g.toString()};T.prototype.toString=function(){return this.g.toString()};function U(a){return a instanceof T&&a.constructor===T?a.g:"type_error:SafeHtml"}function Ga(a){return a instanceof T?a:V(O("object"==typeof a&&a.i?a.h():String(a)))}function Ha(a){function b(f){Array.isArray(f)?f.forEach(b):(f=Ga(f),e.push(U(f).toString()))}var c=Ga(Ia),e=[];a.forEach(b);return V(e.join(U(c).toString()))}
function Ja(a){return Ha(Array.prototype.slice.call(arguments))}function V(a){var b=G();a=b?b.createHTML(a):a;return new T(a,Fa)}var Ka=/^[a-zA-Z0-9-]+$/,La={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Ia=new T(A.trustedTypes&&A.trustedTypes.emptyHTML||"",Fa);/*

 SPDX-License-Identifier: Apache-2.0
*/
var W;try{new URL("s://g"),W=!0}catch(a){W=!1}var Ma=W;function X(a){var b=void 0===b?{}:b;if(a instanceof T)return a;a=Y(a);b.D&&(a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;"));b.C&&(a=a.replace(/(\r\n|\n|\r)/g,"<br>"));b.F&&(a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>'));return V(a)}function Y(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}function Na(a){return V(a.map(function(b){return U(X(b))}).join(""))}
var Oa=/^[a-z][a-z\d-]*$/i,Pa="APPLET BASE EMBED IFRAME LINK MATH META OBJECT SCRIPT STYLE SVG TEMPLATE".split(" "),Qa="AREA BR COL COMMAND HR IMG INPUT KEYGEN PARAM SOURCE TRACK WBR".split(" "),Ra=["action","formaction","href"];function Sa(a){if(!Oa.test(a))throw Error("");if(-1!==Pa.indexOf(a.toUpperCase()))throw Error("");}
function Ta(a,b,c){Sa(a);var e="<"+a;b&&(e+=Ua(b));Array.isArray(c)||(c=void 0===c?[]:[c]);-1!==Qa.indexOf(a.toUpperCase())?e+=">":(b=Na(c.map(function(f){return f instanceof T?f:X(String(f))})),e+=">"+b.toString()+"</"+a+">");return V(e)}
function Ua(a){for(var b="",c=Object.keys(a),e=0;e<c.length;e++){var f=c[e],g=a[f];if(!Oa.test(f))throw Error("");if(void 0!==g&&null!==g){if(/^on/i.test(f))throw Error("");if(-1!==Ra.indexOf(f.toLowerCase()))if(g instanceof P)g=g.toString();else{g=String(g);b:{var d=void 0;var h=g;if(Ma){try{d=new URL(h)}catch(k){h="https:";break b}h=d.protocol}else c:{d=document.createElement("a");try{d.href=h}catch(k){h=void 0;break c}h=d.protocol;h=":"===h||""===h?"https:":h}}g="javascript:"!==h?g:void 0;g=g||
"about:invalid#zClosurez"}f=f+'="'+X(String(g))+'"';b+=" "+f}}return b};function Va(a){a=a.tagName;if("SCRIPT"===a||"STYLE"===a)throw Error("");};var Wa=ca(["var iFrame = window.frameElement;\n          if (iFrame != null) {\n            var div = document.getElementById('inner-sbox');\n            var query = div.getAttribute('data-query');\n            function doQuery() {\n              var doSearch = setInterval(function() {\n                  if ('google' in window) {\n                    var element = window.google.search.cse.element.getElement('iSbox');\n                    element.execute(query);\n                    clearInterval(doSearch);\n                  } else {\n                    console.log('google not found yet');\n                  }\n                }, 10);\n            }\n            if (query) doQuery();\n\n            // Add JavaScript to scroll the window to the top when a navigation\n            // link or any link which reloads the iframe is clicked.\n            if (iFrame.attachEvent) {\n              iFrame.attachEvent('onload', function(ev) {\n                window.scrollTo(0, 0);\n              });\n            } else {\n              iFrame.addEventListener('load', function() {\n                  window.scrollTo(0, 0);\n                }, false);\n            }\n\n            // Resize iframe\n            setInterval(function() {\n              if (document.location.hash && document.location.hash != '#') {\n                const height = document.location.hash.substring(1) + 'px';\n                if (iFrame.height !== height && height != '0px') {\n                  iFrame.height = height;\n                }\n              }\n            }, 10);\n          }"]),
Z,Xa=Wa[0],Ya=G(),Za=Ya?Ya.createScript(Xa):Xa;Z=new L(Za,{});function $a(a,b,c,e){var f={};a=y(a.split(c));for(c=a.next();!c.done;c=a.next()){c=c.value;var g=c.split(b);if(2!==g.length){A.console.log("Dictionary entries (from URL) must contain a name and a value separated by "+(b+". "+c+" does not fit that pattern"));break}g=y(g);c=g.next().value;g=g.next().value;f[e?c.toUpperCase():c.toLowerCase()]=g}return f}
function ab(a){var b=document.location.search;if(1>b.length)return{};b=decodeURIComponent(b.substring(1,b.length));b=$a(b,"=","&",!1);"q"!==a&&b[a]&&(b.q=b[a],delete b[a]);return b}function bb(a){if("cof"in a&&(a=$a(decodeURIComponent(a.cof),":",";",!0).FORID))switch(parseInt(a,10)){case 9:return 795;case 10:return 795}return 500}function cb(){var a=A.googleSearchIframeName||null;return a&&document.getElementById(a)}
function db(){function a(g,d){"number"!==typeof g?e.push("googleSearch"+d+" must be a number. It is "+g):0>g&&e.push("googleSearch"+d+" must be >= 0. It is "+g)}function b(g,d,h){"string"!==typeof g?e.push("googleSearch"+d+" must be a string. It is "+g):/^[\s\xa0]*$/.test(g)?e.push("googleSearch"+d+' must not be empty. It is "'+g+'"'):h.test(g)||e.push("googleSearch"+d+" contains an invalid character. The field's value is \""+g+'"')}var c={frameWidth:A.googleSearchFrameWidth||0,frameHeight:A.googleSearchFrameHeight||
0,frameBorder:A.googleSearchFrameborder||0,j:A.googleSearchQueryString||"q",v:"cse.google.com",A:"/cse.js",l:A.googleAdtest||"",o:A.googleSearchResizeIframe||!0,m:Math.min(A.googleNumSearchResults||10,20),s:A.googleSearchFormName||"googleSearchForm"},e=[];a(c.frameWidth,"FrameWidth");a(c.frameHeight,"FrameHeight");a(c.frameBorder,"FrameBorder");b(c.j,"QueryString",/^[a-zA-Z1-9.\-_~]+$/);b(c.v,"SearchDomain",/^[a-zA-Z1-9.\-]+$/);b(c.A,"SearchPath",/^\/[a-zA-Z1-9.\-]+$/);"string"!==typeof c.l&&e.push("googleAdtest must be a string. It is a "+
typeof c.l+" with value {$params.adTest}");"boolean"!==typeof c.o&&e.push("googleSearchResizeIframe must be a boolean. It is "+c.o);if(0<e.length){c=y(e);for(var f=c.next();!f.done;f=c.next())A.console.log(f.value);return null}return c}A.console.log("show_afs_search.js is deprecated.  Please update this page to use the search element directly, see https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox");
(function(){function a(d,h,k){h={name:"googleSearchFrame",width:k,height:h,frameBorder:b.frameBorder,marginWidth:"0",marginHeight:"0",hspace:"0",vspace:"0",allowTransparency:"true",scrolling:"no",sandbox:"allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-top-navigation"};d={l:b.l,j:b.j,m:b.m,cx:d.cx,q:d.q||d[b.j]};var n=void 0===d?{}:d;d=n.m;var t=n.q;k=n.l;var r=!!t;t=r?t:"";n=fa({cx:n.cx});var m=void 0===m?{}:m;n='<script src="'+Y(N(n).toString())+'"';m.async&&(n+=
" async");m.nonce&&(n+=' nonce="'+Y(m.nonce)+'"');m=V(n+">\x3c/script>");d=Ta("div",{"class":r?"gcse-searchresults-only":"gcse-search",id:"inner-sbox","data-adTest":k||"","data-enableHistory":"false","data-enableAutoComplete":"false","data-gname":"iSbox","data-personalizedAds":"false","data-query":t,"data-webSearchResultSetSize":""+d});k={defer:!0};k=void 0===k?{}:k;r=(Z instanceof L&&Z.constructor===L?Z.g:"type_error:SafeScript").toString();t="<script";k.id&&(t+=' id="'+Y(k.id)+'"');k.nonce&&(t+=
' nonce="'+Y(k.nonce)+'"');k.type&&(t+=' type="'+Y(k.type)+'"');k.defer&&(t+=" defer");k=V(t+(">"+r+"\x3c/script>"));m=Ta("body",{},[m,d,k]);d={src:null};d.srcdoc=m&&U(m).toString();k={sandbox:""};m={};for(var u in d)Object.prototype.hasOwnProperty.call(d,u)&&(m[u]=d[u]);for(var v in k)Object.prototype.hasOwnProperty.call(k,v)&&(m[v]=k[v]);if(h)for(var p in h)if(Object.prototype.hasOwnProperty.call(h,p)){u=p.toLowerCase();if(u in d)throw Error("");u in k&&delete m[u];m[p]=h[p]}p=void 0;u="";if(m)for(z in m)if(Object.prototype.hasOwnProperty.call(m,
z)){if(!Ka.test(z))throw Error("");h=m[z];if(null!=h){v=z;d=h;if(d instanceof H)d=K(d);else if("style"==v.toLowerCase()){h=void 0;k=typeof d;if(("object"!=k||null==d)&&"function"!=k)throw Error("");if(!(d instanceof S)){k="";for(h in d)if(Object.prototype.hasOwnProperty.call(d,h)){if(!/^[-_a-zA-Z0-9]+$/.test(h))throw Error("Name allows only [-_a-zA-Z0-9], got: "+h);r=d[h];null!=r&&(r=Array.isArray(r)?r.map(ya).join(" "):ya(r),k+=h+":"+r+";")}d=k?new S(k,wa):xa}d=d instanceof S&&d.constructor===S?
d.g:"type_error:SafeStyle"}else{if(/^on/i.test(v))throw Error("");if(v.toLowerCase()in La)if(d instanceof M)d=N(d).toString();else if(d instanceof P)d=Q(d);else if("string"===typeof d)d=(ua(d)||va).h();else throw Error("");}d.i&&(d=d.h());v=v+'="'+O(String(d))+'"';u+=" "+v}}var z="<iframe"+u;null==p?p=[]:Array.isArray(p)||(p=[p]);!0===ea.iframe?z+=">":(p=Ja(p),z+=">"+U(p).toString()+"</iframe>");return V(z)}var b=db();if(null==b)A.console.log("Invalid global parameters.");else{var c=ab(b.j),e=cb();
if(null==e)A.googleSearchIframeName?A.console.log("HTML element with id of "+A.googleSearchIframeName+" not found"):A.console.log("googleSearchIframeName not specified in global memory");else if(function(d){function h(n){n.checked=null==c.sitesearch&&""===n.value?!0:n.value===c.sitesearch}if(d=document.getElementById(d))if(!(d.elements.q&&"q"in c)||"ie"in c&&"utf-8"!==c.ie.toLowerCase()||(d.elements.q.value=decodeURIComponent(c.q.replace(/\+/g," "))),d.sitesearch)if(d=d.elements.sitesearch,d instanceof
RadioNodeList){d=y(d);for(var k=d.next();!k.done;k=d.next())h(k.value)}else d instanceof Element&&h(d)}(b.s),b.j in c&&c[b.j]||null==document.getElementById(b.s)){var f=Math.max(b.frameHeight,660+120*b.m),g=Math.max(bb(c),b.frameWidth);f=a(c,f,g);1===e.nodeType&&Va(e);e.innerHTML=U(f);A.googleSearchIframeName=null;A.googleSearchFormName=null;A.googleSearchResizeIframe=null;A.googleSearchQueryString=null;A.googleSearchDomain=null;A.googleSearchPath=null;A.googleSearchFrameborder=null;A.googleSearchFrameWidth=
null;A.googleSearchFrameHeight=null;A.googleSearchNumAds=null;A.googleNumSearchResults=null;A.googleAdtest=null}}})();}).call(this);
