<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>AppArmor</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="security.html" title="Bezpečnosť">Bezpečnosť</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="firewall.html" title="Firewall">Predchádzajúca</a><a class="nextlinks-next" href="certificates-and-security.html" title="Certifikáty">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">AppArmor</h1></div>
<div class="region">
<div class="contents">
<p class="para"><span class="app application">AppArmor</span> je implementácia bezpečnostného modulu Linuxu (Linux Security Module) riadenia prístupu na základe mandátov založených na menách. AppArmor zabraňuje jednotlivým programom meniť súbory, ktoré sú definované v zozname dokumentu posix 1003.1e.</p>
<p class="para"><span class="app application">AppArmor</span> sa nainštaluje spolu so systémom a hneď sa aj aktivuje. Používa <span class="em emphasis">profily</span> aplikácií, aby určil, ktoré súbory a s akými právami daná aplikácia vyžaduje. Niektoré balíky nainštalujú svoje vlastné profily a niektoré ďalšie dodatočné profily sa nachádzajú v balíku <span class="app application">apparmor-profiles</span>.</p>
<p class="para">Ak chceme nainštalovať balík <span class="app application">apparmor-profiles</span>, do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install apparmor-profiles</span>
</pre></div>
<p class="para">Profily AppArmor majú dva módy spustenia:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	      <p class="para">Upozorňovací/Učiaci: umožňuje porušiť pravidlá v profile, porušenia sú však zaznamenané. Toto je užitočné pri testovaní a tvorbe nových profilov.</p>
	    </li>
<li class="list itemizedlist">
	      <p class="para">Prinucovací/Zákazový: striktne presadzuje politiku profilu a pokus o jej porušenie zaznamená.</p>
	    </li>
</ul></div>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="apparmor.html#apparmor-usage" title="Použitie AppArmor">Použitie AppArmor</a></li>
<li class="links"><a class="xref" href="apparmor.html#apparmor-profiles" title="Profily">Profily</a></li>
<li class="links"><a class="xref" href="apparmor.html#apparmor-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="apparmor-usage"><div class="inner">
<div class="hgroup"><h2 class="title">Použitie AppArmor</h2></div>
<div class="region"><div class="contents">
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
   		  <p class="para">
   		  This section is plagued by a bug (<a href="https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1304134" class="ulink" title="https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1304134">LP #1304134</a>) 
		  and instructions will not work as advertised.
   		  </p>
	       </div></div></div></div>
<p class="para">Balík <span class="app application">apparmor-utils</span> obsahuje nástroje pre príkazový riadok, ktorými môžeme pre <span class="app application">AppArmor</span> zmeniť mód spustenia, nájsť stav profilu, vytvoriť nové profily, atď.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	    	<p class="para"><span class="app application">apparmor_status</span> sa používa na zobrazenie aktuálneho stavu profilov AppArmor.</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apparmor_status</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="app application">aa-complain</span> prepne profil do <span class="em emphasis">upozorňovacieho</span> módu.</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-complain /cesta/k/programu</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="app application">aa-enforce</span> prepne profil do <span class="em emphasis">prinucovacieho</span> módu.</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-enforce /cesta/k/programu</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	    	<p class="para">Profily AppArmor sa nachádzajú v priečinku <span class="file filename">/etc/apparmor.d</span>. Tento priečinok môžeme použiť na zmenu <span class="em emphasis">módu<span class="em emphasis"> všetkých profilov naraz.</span></span></p>
	    	<p class="para">Ak chceme všetky profily naraz prepnúť do upozorňovacieho módu, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-complain /etc/apparmor.d/*</span>
</pre></div>
	    <p class="para">Keby sme ich chceli prepnúť do prinucovacieho módu, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-enforce /etc/apparmor.d/*</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="app application">apparmor_parser</span> sa používa na načítanie profilu do jadra. Môžeme ho použiť aj na obnovenie už načítaných profilov použitím prepínača <span class="em emphasis">-r</span>. Profil načítame takto:</p>
<div class="screen"><pre class="contents "><span class="cmd command">cat /etc/apparmor.d/profile.name | sudo apparmor_parser -a</span>
</pre></div>
		<p class="para">Obnovenie profilu urobíme takto:</p>
<div class="screen"><pre class="contents "><span class="cmd command">cat /etc/apparmor.d/profile.name | sudo apparmor_parser -r</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	   	<p class="para">
	   	<span class="file filename">service apparmor</span> can be used to <span class="em emphasis">reload</span> all profiles:
	   	</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo service apparmor reload</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	    	<p class="para">Priečinok <span class="file filename">/etc/apparmor.d/disable</span> môže byť použitý pomocou príkazu <span class="app application">apparmor_parser -R</span> na <span class="em emphasis">vypnutie</span> profilu.</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo ln -s /etc/apparmor.d/profile.name /etc/apparmor.d/disable/</span>
<span class="cmd command">sudo apparmor_parser -R /etc/apparmor.d/profile.name</span>
</pre></div>
	        <p class="para">Ak chceme <span class="em emphasis">znova zapnúť</span> vypnutý profil, odstránime symbolické prepojenie na profil v <span class="file filename">/etc/apparmor.d/disable/</span>. Potom načítame profil spolu s prepínačom <span class="em emphasis">-a</span>.</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo rm /etc/apparmor.d/disable/profile.name</span>
<span class="cmd command">cat /etc/apparmor.d/profile.name | sudo apparmor_parser -a</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	    	<p class="para"><span class="app application">AppArmor</span> môžeme vypnúť a zrušiť aj načítanie modulu jadra zadaním príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo service apparmor stop</span>
<span class="cmd command">sudo update-rc.d -f apparmor remove</span>
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para">Ak chceme znova obnoviť <span class="app application">AppArmor</span>, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo service apparmor start</span>
<span class="cmd command">sudo update-rc.d apparmor defaults</span>
</pre></div>
	      </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	      <p class="para">Spojenie <span class="em emphasis">meno.profilu</span> nahraďte menom profilu, s ktorým chcete manipulovať. Nahraďte tiež cestu <span class="file filename">/cesta/k/programu/</span> aktuálnou cestou spustiteľného súboru. Napríklad príkaz <span class="app application">ping</span> má cestu <span class="file filename">/bin/ping</span></p>
	    </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="apparmor-profiles"><div class="inner">
<div class="hgroup"><h2 class="title">Profily</h2></div>
<div class="region">
<div class="contents">
<p class="para">Profily <span class="app application">AppArmor</span> sú jednoduché textové súbory umiestnené v priečinku <span class="file filename">/etc/apparmor.d/</span>. Súbory sú nazvané podľa celej cesty k spustiteľnému súboru pričom znak "/" je nahradený znakom ".". Napríklad <span class="file filename">/etc/apparmor.d/bin.ping</span> je AppArmor profil pre príkaz <span class="file filename">/bin/ping</span>.</p>
<p class="para">Existujú dva hlavné typy pravidiel použitých v profiloch:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	        <p class="para">
	        <span class="em emphasis">Path entries:</span> detail which files an application can access in the file system.
	        </p>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="em emphasis">Capability entries:</span> určujú, aké právomoci budú môcť použiť neoprávnené procesy.</p>
	      </li>
</ul></div>
<p class="para">
	    As an example, take a look at <span class="file filename">/etc/apparmor.d/bin.ping</span>:
	    </p>
<div class="code"><pre class="contents ">#include &lt;tunables/global&gt;
/bin/ping flags=(complain) {
  #include &lt;abstractions/base&gt;
  #include &lt;abstractions/consoles&gt;
  #include &lt;abstractions/nameservice&gt;

  capability net_raw,
  capability setuid,
  network inet raw,
  
  /bin/ping mixr,
  /etc/modules.conf r,
}
</pre></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	        <p class="para"><span class="em emphasis">#include &lt;tunables/global&gt;:</span> príkaz include znamená začleniť z iných súborov. Tento umožňuje nastaviť chovanie viacerých aplikácií, ktoré nastavíme v spoločnom súbore.</p>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="em emphasis">/bin/ping flags=(complain):</span> cesta k profilovanému programu a nastavenie <span class="em emphasis">upozorňovacieho</span> módu.</p>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="em emphasis">capability net_raw,:</span> umožňuje aplikáciám pristupovať k funkcionalite CAP_NET_RAW Posix.1e.</p>
	      </li>
<li class="list itemizedlist">
	        <p class="para"><span class="em emphasis">/bin/ping mixr,:</span> umožňuje aplikáciám čítať a spúšťať súbor.</p>
	      </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	      <p class="para">Ak upravíte profil, musíte ho znova načítať. Viac informácii sa dozviete v časti <a class="xref" href="apparmor.html#apparmor-usage" title="Použitie AppArmor">Použitie AppArmor</a>.</p>
	    </div></div></div></div>
</div>
<div class="sect3 sect" id="apparmor-profiles-new"><div class="inner">
<div class="hgroup"><h3 class="title">Vytvorenie profilu</h3></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	          <p class="para"><span class="em emphasis">Návrh testovacieho plánu:</span> Skúsme porozmýšlať, ako by aplikácia mala byť spúšťaná. Testovací plán si rozdelíme na malé testovacie prípady. Každý testovací prípad by mal mať krátky opis a zoznam krokov podobných týmto.</p>
		  <p class="para">Niektoré štandardné testovacie prípady sú:</p>
	          <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">		
		      <p class="para">Štartovanie programu.</p>
		    </li>
<li class="list itemizedlist">		
		      <p class="para">Vypínanie programu.</p>
		    </li>
<li class="list itemizedlist">		
		      <p class="para">Obnovenie programu.</p>
		    </li>
<li class="list itemizedlist">		
		      <p class="para">#  #  Testovanie všetkých príkazov, ktoré podporuje init skript.</p>
		    </li>
</ul></div>
		</li>
<li class="list itemizedlist">
	          <p class="para"><span class="em emphasis">Generovanie nového profilu:</span> Na vygenerovanie nového profilu použijem nástroj <span class="app application">aa-genprof</span>. Do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-genprof executable</span>
</pre></div>
		    <p class="para">Napríklad:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-genprof slapd</span>
</pre></div>
		</li>
<li class="list itemizedlist">
		  <p class="para">Ak chceme náš nový profil začleniť do balíka <span class="app application">apparmor-profiles</span>, súbor odošleme ako chybové hlásenie k balíku <a href="https://bugs.launchpad.net/ubuntu/+source/apparmor/+filebug" class="ulink" title="https://bugs.launchpad.net/ubuntu/+source/apparmor/+filebug">AppArmor</a> do systému <span class="em emphasis">Launchpad</span>:</p>
		  <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
		      <p class="para">Napíšeme testovací plán a testovacie prípady.</p>
		    </li>
<li class="list itemizedlist">
		      <p class="para">Pripojíme nový profil k hláseniu o chybe.</p>
		    </li>
</ul></div>
		</li>
</ul></div></div></div>
</div></div>
<div class="sect3 sect" id="apparmor-profiles-update"><div class="inner">
<div class="hgroup"><h3 class="title">Aktualizácia profilov</h3></div>
<div class="region"><div class="contents">
<p class="para">Keď sa program nespráva tak ako by sa mal, odošle sa správa do log súborov. Na hľadanie v súboroch so záznamami <span class="app application">AppArmor</span> môžeme použiť nástroj <span class="app application">aa-logprof</span>, prezrieť si ich a aktualizovať profily. Do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo aa-logprof</span>
</pre></div>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="apparmor-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<div class="list itemizedlist"><ul class="list itemizedlist"><li class="list itemizedlist">
	        <p class="para">Popis ďalších konfiguračných možností je na stránke <a href="http://www.novell.com/documentation/apparmor/apparmor201_sp10_admin/index.html?page=/documentation/apparmor/apparmor201_sp10_admin/data/book_apparmor_admin.html" class="ulink" title="http://www.novell.com/documentation/apparmor/apparmor201_sp10_admin/index.html?page=/documentation/apparmor/apparmor201_sp10_admin/data/book_apparmor_admin.html">AppArmor Administration Guide</a>.</p>
	      </li></ul></div>
<div class="list itemizedlist"><ul class="list itemizedlist"><li class="list itemizedlist">
	        <p class="para">Detaily o používaní AppArmor s ostatnými vydaniami Ubuntu sa nachádzajú na stránke  <a href="https://help.ubuntu.com/community/AppArmor" class="ulink" title="https://help.ubuntu.com/community/AppArmor"> AppArmor Community Wiki</a>.</p>
	      </li></ul></div>
<div class="list itemizedlist"><ul class="list itemizedlist"><li class="list itemizedlist">
	        <p class="para">
		The <a href="http://en.opensuse.org/SDB:AppArmor_geeks" class="ulink" title="http://en.opensuse.org/SDB:AppArmor_geeks">OpenSUSE AppArmor</a> page is another introduction to AppArmor.
  	        </p>
	      </li></ul></div>
<div class="list itemizedlist"><ul class="list itemizedlist"><li class="list itemizedlist">
	  	<p class="para">Skvelým miestom, kde môžete získať pomoc ku <span class="app application">AppArmor</span> a spojiť sa s ostatnými členmi komunity Ubuntu Servera, je na IRC kanále <span class="em emphasis">#ubuntu-server</span> na <a href="http://freenode.net" class="ulink" title="http://freenode.net">freenode</a>.</p>
	      </li></ul></div>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="firewall.html" title="Firewall">Predchádzajúca</a><a class="nextlinks-next" href="certificates-and-security.html" title="Certifikáty">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
