<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bazaar</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="version-control-system.html" title="Systém správy verzií">Systém správy verzií</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="version-control-system.html" title="Systém správy verzií">Predchádzajúca</a><a class="nextlinks-next" href="git.html" title="Git">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Bazaar</h1></div>
<div class="region">
<div class="contents"><p class="para">Bazaar je nový systém na kontrolu verzií sponzorovaný spoločnosťou Canonical, čo je spoločnosť, ktorá vyvíja Ubuntu. Na rozdiel od systémov Subversion a CVS, ktoré podporujú iba centrálny model úložiska, Bazaar podporuje aj <span class="em emphasis">distribuované riadenie verzii</span>, čo ľuďom umožňuje efektívnejšie spolupracovať. Bazaar bol vyvinutý na maximalizovanie úrovne spolupatričnosti komunity na otvorených projektoch.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="bazaar.html#bzr-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="bazaar.html#bzr-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="bazaar.html#bzr-learning" title="Používanie systému Bazaar">Používanie systému Bazaar</a></li>
<li class="links"><a class="xref" href="bazaar.html#bzr-lp-integration" title="Prepojenie so systémom Launchpad">Prepojenie so systémom Launchpad</a></li>
</ul></div>
<div class="sect2 sect" id="bzr-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents"><p class="para">Do príkazového riadka zadáme nasledujúci príkaz: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install bzr</span>
</pre></div></p></div></div>
</div></div>
<div class="sect2 sect" id="bzr-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents"><p class="para">Aby sme uviedli samého seba do <span class="app application">bzr</span>, použijeme príkaz <span class="em emphasis">whoami</span>: <div class="screen"><pre class="contents "><span class="cmd command">$ bzr whoami 'Jozef Mrkva &lt;jozef.mrkva@gmail.com&gt;'</span>
</pre></div></p></div></div>
</div></div>
<div class="sect2 sect" id="bzr-learning"><div class="inner">
<div class="hgroup"><h2 class="title">Používanie systému Bazaar</h2></div>
<div class="region"><div class="contents">
<p class="para">Súčasťou systému Bazaar je i dokumentácia, ktorá sa nachádza v priečinku <span class="app application">/usr/share/doc/bzr/html</span>. Tento návod je vhodný pre začiatočníkov. Príkaz <span class="app application">bzr</span> má tiež vstavaného pomocníka: <div class="screen"><pre class="contents "><span class="cmd command">$ bzr help</span>
</pre></div></p>
<p class="para">Ak sa chceme dozvedieť viac, napríklad o príkaze <span class="em emphasis">foo</span>, zadáme: <div class="screen"><pre class="contents "><span class="cmd command">$ bzr help foo</span>
</pre></div></p>
</div></div>
</div></div>
<div class="sect2 sect" id="bzr-lp-integration"><div class="inner">
<div class="hgroup"><h2 class="title">Prepojenie so systémom Launchpad</h2></div>
<div class="region"><div class="contents"><p class="para">Aj keď je Bazaar veľmi užitočný ako samostatný systém, poskytuje aj možnosť prepojenia so systémom <a href="https://launchpad.net/" class="ulink" title="https://launchpad.net/">Launchpad</a>, čo je systém určený na spoluprácu pri vývoji, ktorý používa spoločnosť Canonical a rozsiahla komunita na správu a rozširovanie samotného Ubuntu. Informácie o tom, ako sa dá Bazaar použiť so systémom Launchpad na spoluprácu na otvorených projektoch, sa nachádzajú na stránke <a href="http://bazaar-vcs.org/LaunchpadIntegration/" class="ulink" title="http://bazaar-vcs.org/LaunchpadIntegration/"> http://bazaar-vcs.org/LaunchpadIntegration</a>.</p></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="version-control-system.html" title="Systém správy verzií">Predchádzajúca</a><a class="nextlinks-next" href="git.html" title="Git">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
