<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Byobu</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="other-useful-applications.html" title="Ďalšie užitočné aplikácie">Ďalšie užitočné aplikácie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="etckeeper.html" title="etckeeper">Predchádzajúca</a><a class="nextlinks-next" href="serverguide-appendix.html" title="Príloha">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Byobu</h1></div>
<div class="region">
<div class="contents">
<p class="para">
	    One of the most useful applications for any system administrator is an xterm multiplexor such as <span class="app application">screen</span> or
	    <span class="app application">tmux</span>.  It allows for the execution of multiple shells in one terminal. To make some of the advanced multiplexor
	    features more user-friendly and provide some useful information about the system, the <span class="app application">byobu</span> package was created.
	    It acts as a wrapper to these programs.  By default Byobu uses tmux (if installed) but this can be changed by the user.  
    </p>
<p class="para">
	    Invoke it simply with:
    </p>
<div class="screen"><pre class="contents "><span class="cmd command">byobu</span>
</pre></div>
<p class="para">
	Now bring up the configuration menu.  By default this is done by pressing the <span class="em emphasis">F9</span> key.  This will allow you to:
    </p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist"><p class="para">Zobraziť ponuku Pomocníka - View the Help menu</p></li>
<li class="list itemizedlist"><p class="para">Zmeniť farbu pozadia - Change Byobu's background color</p></li>
<li class="list itemizedlist"><p class="para">Zmeniť farbu popredia - Change Byobu's foreground color</p></li>
<li class="list itemizedlist"><p class="para">Prepnúť oznamovanie stavov -Toggle status notifications</p></li>
<li class="list itemizedlist"><p class="para">Nastaviť klávesové skratky - Change the key binding set</p></li>
<li class="list itemizedlist"><p class="para">Zmeniť nastavenie únikovej klávesovej skratky - Change the escape sequence</p></li>
<li class="list itemizedlist"><p class="para">Vytvoriť nové screen okno - Create new windows</p></li>
<li class="list itemizedlist"><p class="para">Spravovať predvolené okná - Manage the default windows</p></li>
<li class="list itemizedlist"><p class="para">Zapnúť byobu hneď pro prihlásení - Byobu currently does not launch at login (toggle on)</p></li>
</ul></div>
<p class="para">V nastaveniach <span class="em emphasis">klávesových skratiek</span> môžeme definovať tzv. únikovú klávesovú skratku, skratku pre nové okno, zmenu okna, atď. Existujú dve sady klávesových skratiek, z ktorých si môžete vybrať <span class="em emphasis">f-keys</span> a <span class="em emphasis">screen-escape-keys</span>. Ak chceme použiť pôvodné nastavenie kláves, vyberieme si sadu <span class="em emphasis">none</span>.</p>
<p class="para">Balík byobu poskytuje menu, ktoré zobrazuje názov vydania Ubuntu, informácie o procesore, informácie o voľnej pamäti a čas s dátumom. Efekt je podobný ako v grafickom rozhraní.</p>
<p class="para">Pomocou voľby <span class="em emphasis">"Byobu currently does not launch at login (toggle on)"</span> nastavíme, aby sa nástroj <span class="app application">byobu</span> spustil zakaždým, keď sa prihlásime do terminálu. Nastavenia systému byobu sú pre každého používateľa iné. Zmeny, ktoré vykoná jeden používateľ neovplyvnia výzor systému druhého používateľa.</p>
<p class="para">Jeden rozdiel je pri použití tzv. <span class="em emphasis">scrollback</span> režimu. Ak používame jeden z Ubuntu profilov stlačením <span class="em emphasis">F7</span> sa prepneme do scrollback režimu. Režim scrollback umožňuje prechádzanie výstupu pomocou príkazov podobných editoru <span class="em emphasis">vi</span>. Tu je stručný zoznam príkazov:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist"><p class="para"><span class="em emphasis">h</span> - Posun kurzora o jeden znak doľava</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">j</span> - Posun kurzora o jeden riadok dole</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">k</span> - Posun kurzora o jeden riadok hore</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">l</span> - Posun kurzora o jeden znak doprava</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">0</span> - Presun na začiatok aktuálneho riadka</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">$</span> - Presun na koniec aktuálneho riadka</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">G</span> - Presun na určený riadok (v predvolenom stave na koniec práve načítaného textu)</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">/</span> - Hľadať za</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">?</span> - Hľadať pred</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">n</span> - Moves to the next match, either forward or backward</p></li>
</ul></div>
</div>
<div class="links sectionlinks" role="navigation"><ul><li class="links"><a class="xref" href="byobu.html#byobu-resources" title="Zdroje">Zdroje</a></li></ul></div>
<div class="sect2 sect" id="byobu-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
        <p class="para">Viac informácií o nástroji <span class="app application">screen</span> sa nachádza na stránke <a href="http://www.gnu.org/software/screen/" class="ulink" title="http://www.gnu.org/software/screen/">screen web site</a>.</p>
      </li>
<li class="list itemizedlist">
        <p class="para">Aj na stránke <a href="https://help.ubuntu.com/community/Screen" class="ulink" title="https://help.ubuntu.com/community/Screen">Ubuntu Wiki screen</a>.</p>
      </li>
<li class="list itemizedlist">
        <p class="para">Viac informácií o <span class="app application">byobu</span> je na stránke <a href="https://launchpad.net/byobu" class="ulink" title="https://launchpad.net/byobu">project page</a>.</p>
      </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="etckeeper.html" title="etckeeper">Predchádzajúca</a><a class="nextlinks-next" href="serverguide-appendix.html" title="Príloha">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
