<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Riešenie problémov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="dns.html" title="Služba prekladu doménových mien (DNS)">Služba prekladu doménových mien (DNS)</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="dns-configuration.html" title="Konfigurácia">Predchádzajúca</a><a class="nextlinks-next" href="dns-references.html" title="Zdroje">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Riešenie problémov</h1></div>
<div class="region">
<div class="contents"><p class="para">Táto časť hovorí o spôsoboch, akými môžeme zistiť príčiny vzniknutých problémov s DNS a <span class="app application">BIND9</span>.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="dns-troubleshooting.html#dns-testing" title="Testovanie">Testovanie</a></li>
<li class="links"><a class="xref" href="dns-troubleshooting.html#dns-logging" title="Záznamy">Záznamy</a></li>
</ul></div>
<div class="sect2 sect" id="dns-testing"><div class="inner">
<div class="hgroup"><h2 class="title">Testovanie</h2></div>
<div class="region">
<div class="contents"></div>
<div class="sect3 sect" id="dns-resolv.conf"><div class="inner">
<div class="hgroup"><h3 class="title">resolv.conf</h3></div>
<div class="region"><div class="contents">
<p class="para">
	    The first step in testing <span class="app application">BIND9</span> is to add the nameserver's IP Address to a hosts resolver.
	    The Primary nameserver should be configured as well as another host to double check things.
	    Refer to <a class="xref" href="network-configuration.html#dns-client-configuration" title="Konfigurácia DNS klienta">Konfigurácia DNS klienta</a> for details on adding nameserver addresses to your network clients, and afterwards check
	    that the file <span class="file filename">/etc/resolv.conf</span> contains (for this example):
	    </p>
<div class="code"><pre class="contents ">nameserver	192.168.1.10
nameserver	192.168.1.11
</pre></div>
<p class="para">
            Nameservers that listen at 127.* are responsible for adding their own IP addresses to resolv.conf (using resolvconf).
            This is done via the file <span class="file filename">/etc/default/bind9</span> by changing the line RESOLVCONF=no to RESOLVCONF=yes.
            </p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	      <p class="para">Môžete tiež pridať IP adresu sekundárneho servera pre prípad, že primárny nebude fungovať.</p>
	    </div></div></div></div>
</div></div>
</div></div>
<div class="sect3 sect" id="dns-testing-dig"><div class="inner">
<div class="hgroup"><h3 class="title">dig</h3></div>
<div class="region"><div class="contents">
<p class="para">Ak máme nainštalovaný balík <span class="app application">dnsutils</span>, môžeme otestovať nastavenie DNS pomocou nástroja <span class="app application">dig</span>:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	        <p class="para">Po nainštalovaní <span class="app application">BIND9</span> použijeme <span class="app application">dig</span> ako rozhranie so spätnou väzbou, aby sme sa uistili, či server načúva na porte 53. V príkazovom riadku zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">dig -x 127.0.0.1</span>
</pre></div>
	        <p class="para">Mali by sme uvidieť riadky podobné týmto:</p>
<div class="code"><pre class="contents ">;; Query time: 1 msec
;; SERVER: 192.168.1.10#53(192.168.1.10)
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para">Ak máme <span class="app application">BIND9</span> nastavený ako menný server s <span class="em emphasis">dočasnou pamäťou</span>, môžeme príkaz "dig" použiť na otestovanie rýchlosti odpovede na požiadavku:</p>
<div class="screen"><pre class="contents "><span class="cmd command">dig ubuntu.com</span>
</pre></div>
	        <p class="para">Všimneme si čas požiadavky na konci výstupu:</p>
<div class="code"><pre class="contents ">;; Query time: 49 msec
</pre></div>
	        <p class="para">Po opätovnom zadaní tej istej požiadavky by sme mali dostať oveľa kratší čas:</p>
<div class="code"><pre class="contents ">;; Query time: 1 msec
</pre></div>
	      </li>
</ul></div>
</div></div>
</div></div>
<div class="sect3 sect" id="dns-testing-ping"><div class="inner">
<div class="hgroup"><h3 class="title">ping</h3></div>
<div class="region"><div class="contents">
<p class="para">Teraz si ukážeme, ako môžeme otestovať DNS, či správne prekladá mená staníc. Použijeme na to nástroj <span class="app application">ping</span>, ktorý odošle ICMP echo požiadavku. Do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">ping nieco.sk</span>
</pre></div>
<p class="para">V prípade, že menný server bude vedieť preložiť adresu <span class="em emphasis">ns.nieco.sk</span> na IP adresu, mal by výstup vyzerať takto:</p>
<div class="code"><pre class="contents ">PING ns.nieco.sk (192.168.1.10) 56(84) bytes of data.
64 bytes from 192.168.1.10: icmp_seq=1 ttl=64 time=0.800 ms
64 bytes from 192.168.1.10: icmp_seq=2 ttl=64 time=0.813 ms
</pre></div>
</div></div>
</div></div>
<div class="sect3 sect" id="dns-testing-configuration"><div class="inner">
<div class="hgroup"><h3 class="title">named-checkzone</h3></div>
<div class="region"><div class="contents">
<p class="para">Výborný spôsob, akým sa dajú otestovať zónové súbory, je použitie nástroja <span class="app application">named-checkzone</span>, ktorý sa nainštaloval pri inštalácii balíka <span class="app application">bind9</span>. Tento nástroj umožňuje zistiť, či je konfigurácia pred reštartovaním <span class="app application">BIND9</span>správna a umožňuje robiť zmeny za behu.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	        <p class="para">Ak chceme otestovať náš priamy zónový súbor, zadáme toto:</p>
<div class="screen"><pre class="contents "><span class="cmd command">named-checkzone nieco.sk /etc/bind/db.nieco.sk</span>
</pre></div>
	        <p class="para">Ak je všetko nastavené správne, mal by výstup vyzerať takto:</p>
<div class="code"><pre class="contents ">zone nieco.sk/IN: loaded serial 6
OK
</pre></div>
	      </li>
<li class="list itemizedlist">
	        <p class="para">Podobne môžeme otestovať aj reverzný zónový súbor:</p>
<div class="screen"><pre class="contents "><span class="cmd command">named-checkzone 1.168.192.in-addr.arpa /etc/bind/db.192</span>
</pre></div>
	        <p class="para">Výstup by mal vyzerať takto:</p>
<div class="code"><pre class="contents ">zone 1.168.192.in-addr.arpa/IN: loaded serial 3
OK
</pre></div>
	      </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	     <p class="para">Čísla <span class="em emphasis">Serial</span> sa budú vo Vašom prípade pravdepodobne odlišovať.</p>
	    </div></div></div></div>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="dns-logging"><div class="inner">
<div class="hgroup"><h2 class="title">Záznamy</h2></div>
<div class="region"><div class="contents">
<p class="para"><span class="app application">BIND9</span> má veľa rôznych nastavení týkajúcich sa zaznamenávania. Hlavné nastavenia sú dve. Nastavenie <span class="em emphasis">channel</span> (kanál) hovorí o tom, kam pôjdu záznamy a nastavenie <span class="em emphasis">category</span> (kategória) určuje, aké informácie budú zaznamenávané.</p>
<p class="para">Ak nie sú nakonfigurované žiadne nastavenia, použije sa predvolené nastavenie:</p>
<div class="code"><pre class="contents ">logging {
     category default { default_syslog; default_debug; };
     category unmatched { null; };
};
</pre></div>
<p class="para">Táto časť hovorí o tom, ako nakonfigurovať <span class="app application">BIND9</span> tak, aby odosielal <span class="em emphasis">debug</span> (ladiace) správy súvisiace s DNS požiadavkami do samostatného súboru.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	      <p class="para">Najskôr nastavíme kanál tak, aby systém vedel kam má správy odosielať. Otvoríme súbor <span class="file filename">/etc/bind/named.conf.local</span>  a pridáme nasledujúce riadky:</p>
<div class="code"><pre class="contents ">logging {
    channel query.log {      
        file "/var/log/query.log";
        severity debug 3; 
    }; 
};
</pre></div>	    
	    </li>
<li class="list itemizedlist">
	      <p class="para">Potom nastavím kategóriu, aby systém odosielal všetky DNS požiadavky do súboru query.log:</p>
<div class="code"><pre class="contents ">logging {
    channel query.log {      
        file "/var/log/query.log"; 
        severity debug 3; 
    }; 
    <span class="em emphasis">category queries { query.log; };</span> 
};
</pre></div>	    
	    </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	    <p class="para">Poznámka: nastavenie <span class="em emphasis">debug</span> môžete meniť v rozsahu 1 až 3. Ak ho nezadáte, použije sa úroveň 1.</p>
	  </div></div></div></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	      <p class="para">Pretože démon <span class="em emphasis">named daemon</span> je spustený pod používateľom <span class="em emphasis">bind</span> po vytvorení súboru <span class="file filename">/var/log/query.log</span>  musíme zmeniť jeho vlastníctvo:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo touch /var/log/query.log</span>
<span class="cmd command">sudo chown bind /var/log/query.log</span>
</pre></div>
	    </li>
<li class="list itemizedlist">
	      <p class="para">Pred tým, ako bude môcť démon <span class="app application">named</span> zapisovať do nového log súboru, musíme aktualizovať profil <span class="app application">AppArmor</span>. Najskôr otvoríme súbor <span class="file filename">/etc/apparmor.d/usr.sbin.named</span> a pridáme:</p>
<div class="code"><pre class="contents ">/var/log/query.log w,
</pre></div>
	      <p class="para">Potom nanovo načítame profil:</p>
<div class="screen"><pre class="contents "><span class="cmd command">cat /etc/apparmor.d/usr.sbin.named | sudo apparmor_parser -r</span>
</pre></div>
	      <p class="para">Viac informácii o <span class="app application">AppArmor</span> sa nachádza v časti <a class="xref" href="apparmor.html" title="AppArmor">AppArmor</a></p>
	    </li>
<li class="list itemizedlist">
	      <p class="para">Teraz reštartujeme <span class="app application">BIND9</span> aby sa zmeny prejavili:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo service bind9 restart</span>
</pre></div>
	    </li>
</ul></div>
<p class="para">Teraz by sme mali vidieť v súbore <span class="file filename">/var/log/query.log</span> informácie o požiadavkách. Toto je len veľmi jednoduchá ukážka toho, ako sa konfigurujú nastavenia zaznamenávania systému <span class="app application">BIND9</span>. Podrobnejšie informácie sa dozviete v časti <a class="xref" href="dns-references.html#dns-more-info" title="Ďalšie informácie">Ďalšie informácie</a>.</p>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="dns-configuration.html" title="Konfigurácia">Predchádzajúca</a><a class="nextlinks-next" href="dns-references.html" title="Zdroje">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
