<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>DRBD</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="clustering.html" title="Klastrovanie">Klastrovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="clustering.html" title="Klastrovanie">Predchádzajúca</a><a class="nextlinks-next" href="vpn.html" title="VPN">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">DRBD</h1></div>
<div class="region">
<div class="contents">
<p class="para">Distributed Replicated Block Device (DRBD) – disrribuované zariadenie s replikovanými blokmi je zariadenie, ktoré zrkadlí svoje bloky navzájom medzi viacerými stanicami. Replikácia je pritom neviditeľná pre ostatné aplikácie v systéme. Zrkadlený môže byť ktorýkoľvek blok pevných diskov, diskových oddielov, diskových polí RAID, logických zväzkov, atď.</p>
<p class="para">Ak chceme systém <span class="app application">drbd</span> začať používať, najskôr musíme nainštalovať potrebné balíky. Do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install drbd8-utils</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
      <p class="para">Ak používate virtuálne jadro <span class="em emphasis">virtual kernel</span> ako súčasť virtuálneho počítača, je potrebné modul <span class="app application">drbd</span> ručne skompilovať. Jednoduchší spôsob je nainštalovanie balíka <span class="app application">linux-server</span> do virtuálneho počítača.</p>
    </div></div></div></div>
<p class="para">V tejto časti si povieme ako <span class="app application">drbd</span> nastaviť tak, aby medzi dvoma stanicami replikoval samostatný diskový oddiel so súborovým systémom <span class="app application">ext3</span> pripojený k <span class="file filename">/srv</span>. Veľkosť diskového oddielu nie je podstatná, ale na oboch počítačoch musí byť rovnaká.</p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="drbd.html#drbd-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="drbd.html#drbd-testing" title="Testovanie">Testovanie</a></li>
<li class="links"><a class="xref" href="drbd.html#drbd-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="drbd-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Dve stanice sa v našom príklade budú volať <span class="em emphasis">drbd01</span> a <span class="em emphasis">drbd02</span>. Je potrebné, aby bol nastavený preklad adries prostredníctvom DNS alebo na oboch staniciach prostredníctvom súboru <span class="file filename">/etc/hosts</span>. Viac informácií sa nachádza v kapitole <a class="xref" href="dns.html" title="Služba prekladu doménových mien (DNS)">Služba prekladu doménových mien (DNS)</a>.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Systém <span class="app application">drbd</span> najskôr nastavíme na prvej stanici úpravou súboru <span class="file filename">/etc/drbd.conf</span>:</p>

<div class="code"><pre class="contents ">global { usage-count no; }
common { syncer { rate 100M; } }
resource r0 {
        protocol C;
        startup {
                wfc-timeout  15;
                degr-wfc-timeout 60;
        }
        net {
                cram-hmac-alg sha1;
                shared-secret "secret";
        }
        on drbd01 {
                device /dev/drbd0;
                disk /dev/sdb1;
                address 192.168.0.1:7788;
                meta-disk internal;
        }
        on drbd02 {
                device /dev/drbd0;
                disk /dev/sdb1;
                address 192.168.0.2:7788;
                meta-disk internal;
        }
} 
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Súbor <span class="file filename">/etc/drbd.conf</span> umožňuje nastaviť oveľa viac možností, ale pre náš prípad nám vyhovujú predvolené hodnoty.</p>
          </div></div></div></div>
        </li>
<li class="list itemizedlist">
   
          <p class="para">Teraz skopírujeme súbor <span class="file filename">/etc/drbd.conf</span> na druhú stanicu:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">scp /etc/drbd.conf drbd02:~</span>
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">Na stanici <span class="em emphasis">drbd02</span> súbor premiestnime do priečinka <span class="file filename">/etc</span>:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo mv drbd.conf /etc/</span>
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">Potom použijeme nástroj <span class="app application">drbdadm</span>, ktorým inicializujeme metaúložisko. Na každej stanici spustíme:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo drbdadm create-md r0</span>
</pre></div>
          
        </li>
<li class="list itemizedlist">

          <p class="para">Teraz na oboch staniciach spustíme <span class="app application">drbd</span> démon:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo service drbd start</span>
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">Na stanici <span class="em emphasis">drbd01</span> alebo na tej, ktorá má byť hlavá, zadáme:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo drbdadm -- --overwrite-data-of-peer primary all</span>
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">
          After executing the above command, the data will start syncing with the secondary host.  To watch the progress, on
          <span class="em emphasis">drbd02</span> enter the following:
          </p> 

<div class="screen"><pre class="contents "><span class="cmd command">watch -n1 cat /proc/drbd</span>
</pre></div>

          <p class="para">Výpis prerušíme stlačením kombinácie kláves <span class="em emphasis">Ctrl+c</span>.</p>

        </li>
<li class="list itemizedlist">

      <p class="para">Nakoniec vytvoríme súborový systém na <span class="file filename">/dev/drbd0</span> a pripojíme ho:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo mkfs.ext3 /dev/drbd0</span>
<span class="cmd command">sudo mount /dev/drbd0 /srv</span>
</pre></div>

        </li>
</ul></div>
</div></div>
</div></div>
<div class="sect2 sect" id="drbd-testing"><div class="inner">
<div class="hgroup"><h2 class="title">Testovanie</h2></div>
<div class="region"><div class="contents">
<p class="para">Ak chceme zistiť, či sa dáta synchronizujú medzi dvoma stanicami, na stanici <span class="em emphasis">drbd01</span> skopírujeme nejaké súbory do priečinka <span class="file filename">/srv</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo cp -r /etc/default /srv</span>
</pre></div>
<p class="para">Potom odpojíme priečinok <span class="file filename">/srv</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo umount /srv</span>
</pre></div>
<p class="para">Nastavíme <span class="em emphasis">primárny</span> server do úlohy <span class="em emphasis">sekundárneho</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo drbdadm secondary r0</span>
</pre></div>
<p class="para">Teraz <span class="em emphasis">sekundárny</span> server povýšime do úlohy <span class="em emphasis">primárneho</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo drbdadm primary r0</span>
</pre></div>
<p class="para">Nakoniec pripojíme diskový oddiel:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo mount /dev/drbd0 /srv</span>
</pre></div>
<p class="para">Po použití príkazu <span class="em emphasis">ls</span> uvidíme súbor <span class="file filename">/srv/default</span>, ktorý sme nakopírovali na <span class="em emphasis">primary</span> (predtým bol <span class="em emphasis">primárny</span>).</p>
</div></div>
</div></div>
<div class="sect2 sect" id="drbd-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Viac informácií o <span class="app application">DRBD</span> sa nachádza na stránke <a href="http://www.drbd.org/" class="ulink" title="http://www.drbd.org/">DRBD web site</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">
          The <a href="http://manpages.ubuntu.com/manpages/trusty/en/man5/drbd.conf.5.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/en/man5/drbd.conf.5.html">drbd.conf man page</a> contains
          details on the options not covered in this guide.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para">
          Also, see the <a href="http://manpages.ubuntu.com/manpages/trusty/en/man8/drbdadm.8.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/en/man8/drbdadm.8.html">drbdadm man page</a>.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para">Viac informácií sa dá nájsť aj na stránke <a href="https://help.ubuntu.com/community/DRBD" class="ulink" title="https://help.ubuntu.com/community/DRBD">DRBD Ubuntu Wiki</a>.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="clustering.html" title="Klastrovanie">Predchádzajúca</a><a class="nextlinks-next" href="vpn.html" title="VPN">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
