<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>IRC server</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="chat-servers.html" title="Aplikácie na chatovanie">Aplikácie na chatovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="chat-overview.html" title="Prehľad">Predchádzajúca</a><a class="nextlinks-next" href="jabberd2-server.html" title="Jabber server">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">IRC server</h1></div>
<div class="region">
<div class="contents"><p class="para">Úložiská softvéru Ubuntu obsahujú mnoho Internet Relay Chat serverov. Táto časť sa zameria na to, ako nainštalovať a nastaviť IRC server <span class="app application">ircd-irc2</span>.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="irc-server.html#irc-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="irc-server.html#irc-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="irc-server.html#irc-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="irc-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Ak chceme nainštalovať <span class="app application">ircd-irc2</span>, spustíme nasledujúci príkaz v príkazovom riadku:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install ircd-irc2</span>
</pre></div>
<p class="para">Konfiguračné súbory sú uložené v priečinku <span class="file filename">/etc/ircd</span>. Dokumentácia je dostupná zasa v priečinku <span class="file filename">/usr/share/doc/ircd-irc2</span>.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="irc-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">IRC nastavenia môžeme zmeniť v konfiguračnom súbore <span class="file filename">/etc/ircd/ircd.conf</span>. V tomto súbore môžeme nastaviť názov IRC stanice zmenou nasledujúceho riadka (miesto irc.localhost):</p>
<div class="code"><pre class="contents ">M:irc.localhost::Debian ircd default configuration::000A
</pre></div>
<p class="para">Uistite sa, že alias tohto meno stanice je definovaný aj v DNS. Napríklad, ak nastavíme ako meno IRC stanice irc.nieco.sk, uistíme sa, či DNS server vráti pre mennú adresu irc.nieco.sk číselnú IP adresu. Názov IRC stanice by nemal byť rovnaký, ako názov samotnej stanice (počítača).</p>
<p class="para">
      The IRC admin details can be configured by editing the following
      line:
      </p>
<div class="code"><pre class="contents ">A:Organization, IRC dept.:Daemon &lt;ircd@example.irc.org&gt;:Client Server::IRCnet:
</pre></div>
<p class="para">Môžeme pridať ďalšie riadky, ktorými nastavíme IRC porty, na ktorých má server načúvať, prihlasovacie údaje operátora, spôsob autentifikácie klientov atď. Viac informácií sa nachádza vo vzorovom konfiguračnom súbore <span class="file filename">/usr/share/doc/ircd-irc2/ircd.conf.example.gz</span>.</p>
<p class="para">Úvodná správa, ktorá sa má zobraziť v IRC klientovi po pripojení k serveru, sa dá nastaviť v súbore <span class="file filename">/etc/ircd/ircd.motd</span>.</p>
<p class="para">Po vykonaní všetkých potrebných zmien reštartujeme IRC server použitím nasledujúceho príkazu:</p>
<div class="code"><pre class="contents ">sudo service ircd-irc2 restart
</pre></div>
</div></div>
</div></div>
<div class="sect2 sect" id="irc-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<p class="para">Úložiská Ubuntu obsahujú aj ďalšie IRC servery, napríklad <span class="app application">ircd-ircu</span> and <span class="app application">ircd-hybrid</span>.</p>
<div class="list itemizedlist"><ul class="list itemizedlist"><li class="list itemizedlist">
        <p class="para">Viac informácií o IRC serveroch sa dozviete na stránke <a href="http://www.irc.org/tech_docs/ircnet/faq.html" class="ulink" title="http://www.irc.org/tech_docs/ircnet/faq.html">IRCD FAQ</a>.</p>
      </li></ul></div>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="chat-overview.html" title="Prehľad">Predchádzajúca</a><a class="nextlinks-next" href="jabberd2-server.html" title="Jabber server">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
