<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kerberos</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="network-authentication.html" title="Sieťová autentifikácia">Sieťová autentifikácia</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-ldap.html" title="Samba a LDAP">Predchádzajúca</a><a class="nextlinks-next" href="kerberos-ldap.html" title="Kerberos a LDAP">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Kerberos</h1></div>
<div class="region">
<div class="contents">
<p class="para"><span class="app application">Kerberos</span> je sieťový autentifikačný systém založený na princípe dôveryhodnej tretej strany. Na zvyšných dvoch stranách sa nachádza používateľ a služba, kvôli ktorej sa chce používateľ autentifikovať. Nie všetky služby a aplikácie môžu použiť Kerberos, ale pre tie, ktoré môžu, Kerberos ponúkne sieťové rozhranie, ktoré je o jeden krok bližšie k tzv. Single Sign On (SSO) – jeden podpis na všetko.</p>
<p class="para">Táto časť hovorí o inštalácii a konfigurácii Kerberos servera a uvádza i niekoľko príkladov konfigurácie klienta.</p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="kerberos.html#kerberos-overview" title="Prehľad">Prehľad</a></li>
<li class="links"><a class="xref" href="kerberos.html#kerberos-server" title="Server Kerberos">Server Kerberos</a></li>
<li class="links"><a class="xref" href="kerberos.html#kerberos-secondary-kdc" title="Sekundárny KDC">Sekundárny KDC</a></li>
<li class="links"><a class="xref" href="kerberos.html#kerberos-linux-client" title="Linuxový klient systému Kerberos">Linuxový klient systému Kerberos</a></li>
<li class="links"><a class="xref" href="kerberos.html#kerberos-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="kerberos-overview"><div class="inner">
<div class="hgroup"><h2 class="title">Prehľad</h2></div>
<div class="region"><div class="contents">
<p class="para">Ak ešte Kerberos nepoznáme, bude dobré sa najskôr oboznámiť s niektorými dôležitými pojmami skôr, ako začneme nastavovať server Kerberos. Väčšina pojmov je odvodená od vecí, ktoré sú podobné v iných rozhraniach:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Principal (splnomocniteľ):</span> všetci používatelia, počítače a služby poskytované servermi musia byť zadefinované ako splnomocnitelia systému Kerberos.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Instances (rozhrania):</span> používajú sa na obsluhu splnomocniteľov a pre špeciálnych administratívnych splnomocniteľov.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">
          <span class="em emphasis">Realms:</span> the unique realm of control provided by the Kerberos installation.  
	  Think of it as the domain or group your hosts and users belong to.
	  Convention dictates the realm should be in uppercase.
	  By default, ubuntu will use the DNS domain converted to 
          uppercase (EXAMPLE.COM) as the realm.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Key Distribution Center (distribučné centrum kľúčov):</span> (KDC) sa skladá z troch častí, databázy všetkých splnomocniteľov, autentifikačného servera a servera poskytujúceho vstupenky. Pre každé pôsobisko musí existovať aspoň jedno KDC.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Ticket Granting Ticket (vstupenka poskytujúca vstupenku):</span> je poskytovaný Autentifikačným serverom (AS). Ticket Granting Ticket (TGT) je zašifrované heslo používateľa, ktoré je známe iba používateľovi a KDC.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Ticket Granting Server (server poskytujúci vstupenku):</span> (TGS) služba poskytujúca vstupenky klientom, ktorí o ne žiadajú.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Tickets (vstupenky):</span> potvrdzujú identitu dvoch splnomocniteľov. Prvým splnomocniteľom – používateľom a druhým splnomocniteľom – službou, ktorú používateľ chce použiť. Vstupenky vytvoria šifrovací kľúč, ktorý bude použitý počas autentifikovaného pripojenia.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Keytab Files (súbory tabuliek kľúčov):</span> sú súbory extrahované KDC databázy splnomocniteľov a obsahujú zašifrované kľúče pre služby a stanice.</p>
        </li>
</ul></div>
<p class="para">
      To put the pieces together, a Realm has at least one KDC, preferably more for redundancy, which contains a database of Principals.  When a 
      user principal logs into a workstation that is configured for Kerberos authentication, the KDC issues a Ticket Granting Ticket (TGT).  If the user
      supplied credentials match, the user is authenticated and can then request tickets for Kerberized services from the Ticket Granting Server
      (TGS).  The service tickets allow the user to authenticate to the service without entering another username and password.
      </p>
</div></div>
</div></div>
<div class="sect2 sect" id="kerberos-server"><div class="inner">
<div class="hgroup"><h2 class="title">Server Kerberos</h2></div>
<div class="region">
<div class="contents"></div>
<div class="sect3 sect" id="kerberos-server-installation"><div class="inner">
<div class="hgroup"><h3 class="title">Inštalácia</h3></div>
<div class="region"><div class="contents">
<p class="para">
	For this discussion, we will create a MIT Kerberos domain with the 
	following features (edit them to fit your needs):
        </p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">Realm:</span> EXAMPLE.COM 
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">Primary KDC:</span> kdc01.example.com (192.168.0.1)
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">Secondary KDC:</span> kdc02.example.com (192.168.0.2)
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">User principal:</span> steve 
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">Admin principal:</span> steve/admin 
            </p>
          </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"> 
          <p class="para">
          It is <span class="em emphasis">strongly</span> recommended that your
	  network-authenticated users have their uid in a different range 
	  (say, starting at 5000) than that of your local users. 
          </p>
        </div></div></div></div>
<p class="para"> 
        Before installing the Kerberos server a properly configured DNS server is needed for your domain.  Since the Kerberos Realm by 
        convention matches the domain name, this section uses the <span class="em emphasis">EXAMPLE.COM</span> domain configured in 
        <a class="xref" href="dns-configuration.html#dns-primarymaster-configuration" title="Primárny hlavný menný server">Primárny hlavný menný server</a> of the DNS documentation.  
        </p>
<p class="para">
        Also, Kerberos is a time sensitive protocol.  So if the local system time between a client machine and the server differs by
        more than five minutes (by default), the workstation will not be able to authenticate.  To correct the problem all hosts 
        should have their time synchronized using the same
	<span class="em emphasis">Network Time Protocol (NTP)</span> server.  For details
        on setting up NTP see <a class="xref" href="NTP.html" title="Synchronizácia času pomocou NTP">Synchronizácia času pomocou NTP</a>.
        </p>
<p class="para">
        The first step in creating a Kerberos Realm is to install the <span class="app application">krb5-kdc</span>  and 
        <span class="app application">krb5-admin-server</span> packages.  From a terminal enter:
        </p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install krb5-kdc krb5-admin-server</span>
</pre></div>
<p class="para">
        You will be asked at the end of the install to supply the hostname 
	for the Kerberos and Admin servers, which may or may not be the 
        same server, for the realm.
        </p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
          <p class="para">
          By default the realm is created from the KDC's domain name.
          </p>
        </div></div></div></div>
<p class="para">Ako ďalšie vytvoríme nové pôsobisko pomocou nástroja <span class="app application">kdb5_newrealm</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo krb5_newrealm</span>
</pre></div>
</div></div>
</div></div>
<div class="sect3 sect" id="kerberos-server-configuration"><div class="inner">
<div class="hgroup"><h3 class="title">Konfigurácia</h3></div>
<div class="region"><div class="contents">
<p class="para">
        The questions asked during installation are used to configure the <span class="file filename">/etc/krb5.conf</span> file.  If you need to adjust 
        the Key Distribution Center (KDC) settings simply edit the file and restart the <span class="app application">krb5-kdc</span> daemon.
	If you need to reconfigure Kerberos from scratch, perhaps to change the realm name, you can do so by typing
        </p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo dpkg-reconfigure krb5-kdc</span>
</pre></div>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">

            <p class="para">
            Once the KDC is properly running, an admin user -- the
	    <span class="em emphasis">admin principal</span> -- is needed.  
	    It is recommended to use a different username from your everyday username.  
            Using the <span class="app application">kadmin.local</span> utility in a terminal prompt enter:
            </p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kadmin.local</span>
<span class="output computeroutput">Authenticating as principal root/admin@NIECO.SK with password.
kadmin.local:</span><span class="input userinput"> addprinc stefan/admin</span>
<span class="output computeroutput">WARNING: no policy specified for stefan/admin@NIECO.SK; defaulting to no policy
Enter password for principal "stefan/admin@NIECO.SK": 
Re-enter password for principal "stefan/admin@NIECO.SK": 
Principal "stefan/admin@NIECO.SK" created.
kadmin.local:</span><span class="input userinput"> quit</span>
</pre></div>

            <p class="para">
            In the above example <span class="em emphasis">steve</span> is the <span class="em emphasis">Principal</span>, 
            <span class="em emphasis">/admin</span> is an <span class="em emphasis">Instance</span>, and 
            <span class="em emphasis">@EXAMPLE.COM</span> signifies the realm.  The <span class="em emphasis">"every day"</span>
            Principal, 
	    a.k.a. the <span class="em emphasis">user principal</span>,
	    would be <span class="em emphasis">steve@EXAMPLE.COM</span>, and should have only normal user rights.            
            </p>

            <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
              <p class="para">Nahraďte <span class="em emphasis">NIECO.SK</span> a <span class="em emphasis">stefan</span>, pôsobiskom a menom používateľa, ktoré chcete použiť.</p>
            </div></div></div></div>

          </li>
<li class="steps">
 
            <p class="para">Teraz novému používateľovi pridelíme práva (ACL). Práva sú nastavené v súbore <span class="file filename">/etc/krb5kdc/kadm5.acl</span>:</p>

<div class="code"><pre class="contents ">stefan/admin@NIECO.SK        *
</pre></div>

            <p class="para">
            This entry grants <span class="em emphasis">steve/admin</span> the ability to perform any operation on all principals in the realm.
	    You can configure principals with more restrictive privileges,
	    which is convenient if you need an admin principal that junior 
	    staff can use
	    in Kerberos clients. Please see the 
	    <span class="em emphasis">kadm5.acl</span> man page for details.
            </p>

          </li>
<li class="steps">

            <p class="para">Aby sa nové ACL oprávnenia prejavili, je potrebné reštartovať <span class="app application">krb5-admin-server</span> :</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo service krb5-admin-server restart</span>
</pre></div>

          </li>
<li class="steps">

            <p class="para">Novovytvoreného splnomocniteľa môžeme otestovať pomocou nástroja <span class="app application">kinit utility</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">kinit stefan/admin</span>
<span class="output computeroutput">stefan/admin@NIECO.SK's Password:</span>
</pre></div>          

            <p class="para">Po zadaní hesla, použijeme nástroj  <span class="app application">klist</span>, ktorý zobrazí informácie o TGT:</p>

<div class="screen"><pre class="contents "><span class="cmd command">klist</span>
<span class="output computeroutput">Credentials cache: FILE:/tmp/krb5cc_1000
        Principal: stefan/admin@NIECO.SK

  Issued           Expires          Principal
Jul 13 17:53:34  Jul 14 03:53:34  krbtgt/NIECO.SK@NIECO.SK</span>
</pre></div>

            <p class="para">
	    Where the cache filename <span class="file filename">krb5cc_1000</span> is 
	    composed of the prefix <span class="file filename">krb5cc_</span> and the user
	    id (uid), which in this case is <span class="file filename">1000</span>.
            You may need to add an entry into the 
	    <span class="file filename">/etc/hosts</span> for the KDC so the client can
	    find the KDC.  For example:
            </p>
            
<div class="code"><pre class="contents ">192.168.0.1   kdc01.nieco.sk      kdc01
</pre></div>

            <p class="para">
            Replacing <span class="em emphasis">192.168.0.1</span> with the IP address of your KDC.  
	    This usually happens when you have a Kerberos realm encompassing 
	    different networks separated by routers.
            </p>

          </li>
<li class="steps">
          
            <p class="para">
	    The best way to allow clients to automatically
            determine the KDC for the Realm is using DNS SRV records.  Add the following to 
            <span class="file filename">/etc/named/db.example.com</span>:
            </p>

<div class="code"><pre class="contents ">_kerberos._udp.NIECO.SK.     IN SRV 1  0 88  kdc01.nieco.sk.
_kerberos._tcp.NIECO.SK.     IN SRV 1  0 88  kdc01.nieco.sk.
_kerberos._udp.NIECO.SK.     IN SRV 10 0 88  kdc02.nieco.sk. 
_kerberos._tcp.NIECO.SK.     IN SRV 10 0 88  kdc02.nieco.sk. 
_kerberos-adm._tcp.NIECO.SK. IN SRV 1  0 749 kdc01.nieco.sk.
_kpasswd._udp.NIECO.SK.      IN SRV 1  0 464 kdc01.nieco.sk.
</pre></div>

            <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
              <p class="para">Nahraďte <span class="em emphasis">NIECO.SK</span>, <span class="em emphasis">kdc01</span> a <span class="em emphasis">kdc02</span> názvom domény a názvami primárneho a sekundárneho KDC.</p>
            </div></div></div></div>

            <p class="para">Podrobné inštrukcie o nastavovaní DNS nájdete v kapitole <a class="xref" href="dns.html" title="Služba prekladu doménových mien (DNS)">Služba prekladu doménových mien (DNS)</a>.</p>

          </li>
</ol></div></div>
<p class="para">Nové pôsobisko systému Kerberos je teraz pripravené na autetifikovanie klientov.</p>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="kerberos-secondary-kdc"><div class="inner">
<div class="hgroup"><h2 class="title">Sekundárny KDC</h2></div>
<div class="region"><div class="contents">
<p class="para">
      Once you have one Key Distribution Center (KDC) on your network, it is good practice to have a Secondary KDC in case the
      primary becomes unavailable. 
      Also, if you have Kerberos clients that are in different networks 
      (possibly separated by routers using NAT), it is wise to place a 
      secondary KDC in each of those networks.
      </p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
        
        <p class="para">Najskôr nainštalujeme balíky. Pri otázke inštalátora na Kerberos server a Admin server zadáme meno primárneho KDC:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install krb5-kdc krb5-admin-server</span>
</pre></div>

        </li>
<li class="steps">

        <p class="para">Po nainštalovaní balíkov vytvoríme splnomocniteľa pre hostiteľa (host) sekundárneho KDC. V príkazovom riadku zadáme:</p>

<div class="screen"><pre class="contents "><span class="cmd command">kadmin -q "addprinc -randkey host/kdc02.nieco.sk"</span>
</pre></div>
    
        <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
          <p class="para">Vždy po zadaní príkazu <span class="app application">kadmin</span> bude potrebné zadať heslo pre <span class="em emphasis">pouzivatel/admin@NIECO.SK</span>.</p>
        </div></div></div></div>
      
        </li>
<li class="steps">

          <p class="para">Extrahujeme súbor <span class="em emphasis">tabuľky kľúčov</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">kadmin -q "ktadd -norandkey -k keytab.kdc02 host/kdc02.example.com"</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Teraz by v priečinku kde sa nachádzame mal pribudnúť súbor <span class="file filename">keytab.kdc02</span>. Presunieme ho do priečinka <span class="file filename">/etc/krb5.keytab</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo mv keytab.kdc02 /etc/krb5.keytab</span>
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Ak ste použili inú cestu k súboru <span class="file filename">keytab.kdc02</span>, použite tú.</p>
          </div></div></div></div>

          <p class="para">Z tabuľky kľúčov sa pomocou nástroja <span class="app application">klist</span> dá vypísať aj zoznam splnomocniteľov, čo môže byť užitočné pri riešení problémov:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo klist -k /etc/krb5.keytab</span>
</pre></div>

            <p class="para">
            The <span class="app application">-k</span> option indicates the file is a keytab file.
            </p>

        </li>
<li class="steps">

          <p class="para">Ako ďalšie je potrebné vytvoriť súbor <span class="file filename">kpropd.acl</span>, ktorý bude obsahovať zoznam všetkých KDC v pôsobisku. Na oboch serveroch – primárnom aj sekundárnom, vytvoríme súbor <span class="file filename">/etc/krb5kdc/kpropd.acl</span> s takýmto obsahom:</p>

<div class="code"><pre class="contents ">host/kdc01.nieco.sk@NIECO.SK
host/kdc02.example.com@NIECO.SK
</pre></div>

        </li>
<li class="steps">

          <p class="para">Vytvoríme databázu na <span class="em emphasis">sekundárnom KDC</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kdb5_util -s create</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Teraz spustíme démona <span class="app application">kpropd</span>, ktorý bude načúvať pripojeniam nástroja <span class="app application">kpropd</span>. Nástroj <span class="app application">kpropd</span> sa používa na prenos vyexportovaných súborov:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kpropd -S</span>
</pre></div>
      
        </li>
<li class="steps">

          <p class="para">V príkazovom riadku <span class="em emphasis">primárneho KDC</span>, vyexportujeme súbor so splnomocniteľmi:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kdb5_util dump /var/lib/krb5kdc/dump</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Vyextrahujeme súbor <span class="em emphasis">tabuľky kľúčov</span> primárneho KDC a skopírujeme ho do <span class="file filename">/etc/krb5.keytab</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">kadmin -q "ktadd -k keytab.kdc01 host/kdc01.nieco.sk"</span>
<span class="cmd command">sudo mv keytab.kdc01 /etc/krb5.keytab</span>
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Pred extrahovaním tabuľky kľúčov sa uistite, či existuje <span class="em emphasis">host</span> pre <span class="em emphasis">kdc01.nieco.sk</span>.</p>
          </div></div></div></div>

        </li>
<li class="steps">

          <p class="para">Nástroj <span class="app application">kprop</span> vloží databázu do sekundárneho KDC:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kprop -r NIECO.SK -f /var/lib/krb5kdc/dump kdc02.nieco.sk</span>
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Ak operácia prebehne správne, program vypíše <span class="em emphasis">SUCCEEDED</span>. Ak nastane chyba, viac informácii sa dozviete v súbore <span class="file filename">/var/log/syslog</span> na sekundárnom KDC.</p>
          </div></div></div></div>
      
          <p class="para">
          You may also want to create a <span class="app application">cron</span> job to periodically update the database on the Secondary KDC.  For 
          example, the following will push the database every hour (note the long line has been split to fit the format of this document):
          </p>

<div class="code"><pre class="contents "># m h  dom mon dow   command
0 * * * * /usr/sbin/kdb5_util dump /var/lib/krb5kdc/dump &amp;&amp; 
/usr/sbin/kprop -r EXAMPLE.COM -f /var/lib/krb5kdc/dump kdc02.example.com
</pre></div>
  
        </li>
<li class="steps">

          <p class="para">Vrátime sa na <span class="em emphasis">sekundárne KDC</span>, kde vytvoríme súbor <span class="em emphasis">stash</span>, ktorý bude obsahovať hlavný kľúč systému Kerberos:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo kdb5_util stash</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Nakoniec spustíme démon <span class="app application">krb5-kdc</span> na sekundárnom KDC:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo service krb5-kdc start</span>
</pre></div>

        </li>
</ol></div></div>
<p class="para">
      The <span class="em emphasis">Secondary KDC</span> should now be able to issue tickets for the Realm.  You can test this by stopping 
      the <span class="app application">krb5-kdc</span> daemon on the Primary KDC, then 
      by using <span class="app application">kinit</span> to request a ticket.
      If all goes well you should receive a ticket from the Secondary KDC.
      Otherwise, check <span class="file filename">/var/log/syslog</span> and
      <span class="file filename">/var/log/auth.log</span> in the Secondary KDC.
      </p>
</div></div>
</div></div>
<div class="sect2 sect" id="kerberos-linux-client"><div class="inner">
<div class="hgroup"><h2 class="title">Linuxový klient systému Kerberos</h2></div>
<div class="region">
<div class="contents"><p class="para">V tejto časti si povieme, ako nastaviť operačný systém Linux tak, aby bol klientom systému <span class="app application">Kerberos</span>. To umožní používateľovi, ktorý sa úspešne do systému prihlási, prístup ku všetkým kerberizovaným službám bez toho, aby musel zakaždým zadať heslo.</p></div>
<div class="sect3 sect" id="kerberos-client-installation"><div class="inner">
<div class="hgroup"><h3 class="title">Inštalácia</h3></div>
<div class="region"><div class="contents">
<p class="para">Aby bolo možné prihlásiť sa do pôsobiska systému Kerberos, sú potrebné balíky <span class="app application">krb5-user</span> a <span class="app application">libpam-krb5</span> spolu s ďalšími, ktoré síce nie sú nutné, ale uľahčia nám prácu. Ak chceme tieto balíky nainštalovať, do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install krb5-user libpam-krb5 libpam-ccreds auth-client-config</span>
</pre></div>
<p class="para">Balík <span class="app application">auth-client-config</span> umožňuje jednoduchú konfiguráciu PAM pre autentifikáciu z viacerých zdrojov a <span class="app application">libpam-ccreds</span> dočasne uchováva údaje o prihlásení, ktoré nám umožnia prihlásiť sa, aj keď je distribučné centrum kľúčov (KDC) nedostupné. Tento balík je tiež užitočný pre notebooky, ktoré sa musia vedieť prihlásiť do firemnej siete pomocou systému Kerberos, ale musia používateľovi umožniť prístup aj vtedy, ak nie sú pripojené do siete.</p>
</div></div>
</div></div>
<div class="sect3 sect" id="kerberos-client-configuration"><div class="inner">
<div class="hgroup"><h3 class="title">Konfigurácia</h3></div>
<div class="region"><div class="contents">
<p class="para">Ak chceme nastaviť klienta, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo dpkg-reconfigure krb5-config</span>
</pre></div>
<p class="para">Pri konfigurácii bude potrebné zadať meno pôsobiska systému Kerberos a ak nemáte nastavené v DNS Kerberos <span class="em emphasis">SRV</span> záznamy, bude potrebné zadať i adresu distribučného centra kľúčov (KDC) a adresu Admin servera pôsobiska.</p>
<p class="para">Nástroj <span class="app application">dpkg-reconfigure</span> tieto zadané údaje o pôsobisku uloží do súboru <span class="file filename">/etc/krb5.conf</span>. Záznamy v súbore budú vyzerať asi takto:</p>
<div class="code"><pre class="contents ">[libdefaults]
        default_realm = EXAMPLE.COM
...
[realms]
        EXAMPLE.COM = {
                kdc = 192.168.0.1
                admin_server = 192.168.0.1
        }
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	  <p class="para">
	  If you set the uid of each of your network-authenticated users to 
	  start at 5000, as suggested in 
	  <a class="xref" href="kerberos.html#kerberos-server-installation" title="Inštalácia">Inštalácia</a>, you 
	  can then tell pam to only try to authenticate using Kerberos 
	  users with uid &gt; 5000:
	  </p>
<div class="screen"><pre class="contents "><span class="cmd command"># Kerberos should only be applied to ldap/kerberos users, not local ones.
for i in common-auth common-session common-account common-password; do
 sudo sed -i -r \ 
 -e 's/pam_krb5.so minimum_uid=1000/pam_krb5.so minimum_uid=5000/' \ 
 /etc/pam.d/$i 
done </span>
</pre></div>
	  <p class="para">
	  This will avoid being asked for the (non-existent) Kerberos 
	  password of a locally authenticated user when changing its 
	  password using <span class="cmd command">passwd</span>.
	  </p>
	</div></div></div></div>
<p class="para">Nastavenie môžeme otestovať požiadaním o vstupenku pomocou nástroja <span class="app application">kinit</span>. Napríklad takto:</p>
<div class="screen"><pre class="contents "><span class="cmd command">kinit stefan@NIECO.SK</span>
<span class="output computeroutput">Password for stefan@NIECO.SK:</span>
</pre></div>
<p class="para">Ak nám bude vstupenka poskytnutá, detail môžeme zobraziť pomocou <span class="app application">klist</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">klist</span>
<span class="output computeroutput">Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: stefan@NIECO.SK

Valid starting     Expires            Service principal
07/24/08 05:18:56  07/24/08 15:18:56  krbtgt/NIECO.SK@NIECO.SK
        renew until 07/25/08 05:18:57


Kerberos 4 ticket cache: /tmp/tkt1000
klist: You have no tickets cached</span>
</pre></div>
<p class="para">Potom použijeme nástroj <span class="app application">auth-client-config</span>, ktorým nastavíme modul <span class="app application">libpam-krb5</span>, aby žiadal o vstupenku pri prihlasovaní:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo auth-client-config -a -p kerberos_example</span>
</pre></div>
<p class="para">Teraz by sme po úspešnom prihlásení mali obdržať vstupenku.</p>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="kerberos-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">
          For more information on MIT's version of Kerberos, see the <a href="http://web.mit.edu/Kerberos/" class="ulink" title="http://web.mit.edu/Kerberos/">MIT Kerberos</a> site.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para">Viac podrobností sa nachádza na stránke <a href="https://help.ubuntu.com/community/Kerberos" class="ulink" title="https://help.ubuntu.com/community/Kerberos">Ubuntu Wiki Kerberos</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Dobrou príručkou o nastavovaní systému Kerberos je O'Reillyho <a href="http://oreilly.com/catalog/9780596004033/" class="ulink" title="http://oreilly.com/catalog/9780596004033/">Kerberos: The Definitive Guide</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">
          Also, feel free to stop by the <span class="em emphasis">#ubuntu-server</span> 
	  and <span class="em emphasis">#kerberos</span>
	  IRC channels on <a href="http://freenode.net/" class="ulink" title="http://freenode.net/">Freenode</a>  
          if you have Kerberos questions.
          </p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-ldap.html" title="Samba a LDAP">Predchádzajúca</a><a class="nextlinks-next" href="kerberos-ldap.html" title="Kerberos a LDAP">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
