<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>libvirt</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="virtualization.html" title="Virtualizácia">Virtualizácia</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="virtualization.html" title="Virtualizácia">Predchádzajúca</a><a class="nextlinks-next" href="cloud-images-and-uvtool.html" title="Cloud images and uvtool">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">libvirt</h1></div>
<div class="region">
<div class="contents">
<p class="para">Knižnica <span class="app application">libvirt</span> sa používa ako rozhranie pre rôzne virtualizačné technológie. Pred tým, ako začneme používať <span class="app application">libvirt</span>, je dobré uistiť sa, či máme hardvérovú podporu potrebnú pre <span class="app application">KVM</span>. V príkazovom riadku zadáme nasledujúci príkaz:</p>
<div class="screen"><pre class="contents "><span class="cmd command">kvm-ok</span>
</pre></div>
<p class="para">Zobrazí sa správa, ktorá hovorí či náš procesor hardvérovo <span class="em emphasis">podporuje</span> alebo <span class="em emphasis">nepodporuje</span> virtualizáciu.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
      <p class="para">On many computers with processors supporting hardware assisted
      virtualization, it is necessary to activate an option in the BIOS to
      enable it.</p>
    </div></div></div></div>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="libvirt.html#virtual-networking" title="Virtuálna sieť">Virtuálna sieť</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-virt-install" title="virt-install">virt-install</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-virt-clone" title="virt-clone">virt-clone</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-management" title="Správa virtuálnych počítačov">Správa virtuálnych počítačov</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-virt-viewer" title="Prehliadač virtuálnych počítačov">Prehliadač virtuálnych počítačov</a></li>
<li class="links"><a class="xref" href="libvirt.html#libvirt-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="virtual-networking"><div class="inner">
<div class="hgroup"><h2 class="title">Virtuálna sieť</h2></div>
<div class="region"><div class="contents">
<p class="para">There are a few different ways to allow a virtual machine access
      to the external network. The default virtual network configuration
      includes <span class="em emphasis">bridging</span> and <span class="em emphasis">iptables</span>
      rules implementing <span class="em emphasis">usermode</span> networking, which uses
      the SLIRP protocol. Traffic is NATed through the host interface to the
      outside network.</p>
<p class="para">To enable external hosts to directly access services on virtual
      machines a different type of <span class="em emphasis">bridge</span> than the
      default needs to be configured. This allows the virtual interfaces to
      connect to the outside network through the physical interface, making
      them appear as normal hosts to the rest of the network.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="libvirt-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Ak chceme nainštalovať potrebné balíčky, v príkazovom riadku zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install qemu-kvm libvirt-bin</span>
</pre></div>
<p class="para">Po nainštalovaní <span class="app application">libvirt-bin</span>, je potrebné pridať aspoň jedného používateľa do skupiny <span class="em emphasis">libvirtd</span>. Používatelia v tejto skupine môžu spravovať virtuálne počítače. Títo používatelia budú mať tiež právo meniť pokročilé sieťové nastavenia.</p>
<p class="para">V príkazovom riadku zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo adduser $USER libvirtd</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Ak bol zvolený aktuálny používateľ, pod ktorým ste práve prihlásený, je potrebné sa odhlásiť a znovu prihlásiť aby sa zmena prejavila.</p>
      </div></div></div></div>
<p class="para">Teraz môžeme začať inštalovať <span class="em emphasis">hosťujúci</span> operačný systém. Inštalácia systému na virtuálny počítač sa ničím nelíši od inštalácie na fyzický počítač. Buď treba nájsť spôsob, ako inštaláciu zautomatizovať alebo je potrebné pripojiť k fyzickému počítaču monitor a klávesnicu.</p>
<p class="para">V prípade virtuálnych počítačov s grafickým rozhraním (GUI), je použitie klávesnice a myši rovnaké. Miesto inštalovania grafického systému však môžeme použiť aj aplikáciu <span class="app application">virt-viewer</span>, pomocou ktorej sa môžeme pripojiť na vzdialený virtuálny počítač cez <span class="app application">VNC</span>. Viac informácií sa nachádza v časti <a class="xref" href="libvirt.html#libvirt-virt-viewer" title="Prehliadač virtuálnych počítačov">Prehliadač virtuálnych počítačov</a>.</p>
<p class="para">There are several ways to automate the Ubuntu installation
      process, for example using preseeds, kickstart, etc. Refer to the <a href="https://help.ubuntu.com/14.04/installation-guide/" class="ulink" title="https://help.ubuntu.com/14.04/installation-guide/">Ubuntu
      Installation Guide</a> for details.</p>
<p class="para">Yet another way to install an Ubuntu virtual machine is to use
      <span class="app application">uvtool</span>.
      This application, available as of 14.04, allows you to set up
      specific VM options, execute custom post-install scripts, etc. For
      details see <a class="xref" href="cloud-images-and-uvtool.html" title="Cloud images and uvtool">Cloud images and uvtool</a>.</p>
<p class="para">Libvirt can also be configured work with
      <span class="app application">Xen</span>. For details, see the Xen Ubuntu
      community page referenced below.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="libvirt-virt-install"><div class="inner">
<div class="hgroup"><h2 class="title">virt-install</h2></div>
<div class="region"><div class="contents">
<p class="para"><span class="app application">virt-install</span> is part of the
      <span class="app application">virtinst</span> package. To install it, from a
      terminal prompt enter:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install virtinst</span>
</pre></div>
<p class="para">Spolu s príkazom <span class="app application">virt-install</span> je možné použiť aj niekoľko parametrov. Napríklad:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo virt-install -n web_devel -r 256 \
--disk path=/var/lib/libvirt/images/web_devel.img,bus=virtio,size=4 -c \
ubuntu-14.04-server-i386.iso --network network=default,model=virtio \
--graphics vnc,listen=0.0.0.0 --noautoconsole -v</span>
</pre></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-n web_vyvoj:</span> meno virtuálneho počítača v tomto príklade bude <span class="em emphasis">web_vyvoj</span> .</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-r 256:</span> specifies the amount of memory
          the virtual machine will use in megabytes.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">--disk
          path=/var/lib/libvirt/images/web_devel.img,size=4:</span>
          indicates the path to the virtual disk which can be a file,
          partition, or logical volume. In this example a file named
          <span class="file filename">web_devel.img</span> in the /var/lib/libvirt/images/
          directory, with a size of 4 gigabytes, and using
          <span class="em emphasis">virtio</span> for the disk bus.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-c ubuntu-14.04-server-i386.iso:</span> file to be used as a virtual
          CDROM. The file can be either an ISO file or the path to the host's
          CDROM device.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">--network</span> provides details related to the
          VM's network interface. Here the <span class="em emphasis">default</span>
          network is used, and the interface model is configured for
          <span class="em emphasis">virtio</span>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">--graphics vnc,listen=0.0.0.0:</span> exports
          the guest's virtual console using VNC and on all host interfaces.
          Typically servers have no GUI, so another GUI based computer on the
          Local Area Network (LAN) can connect via VNC to complete the
          installation.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">--noautoconsole:</span> nepripojí sa automaticky ku konzole virtuálneho počítača.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-v:</span> vytvorí plne virtualizovaný hosťovaný systém.</p>
        </li>
</ul></div>
<p class="para">After launching <span class="app application">virt-install</span> you can
      connect to the virtual machine's console either locally using a GUI (if
      your server has a GUI), or via a remote VNC client from a GUI-based
      computer.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="libvirt-virt-clone"><div class="inner">
<div class="hgroup"><h2 class="title">virt-clone</h2></div>
<div class="region"><div class="contents">
<p class="para">Aplikácia <span class="app application">virt-clone</span> sa používa na vytváranie kópie jedného virtuálneho počítača na druhý. Napríklad:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo virt-clone -o web_devel -n database_devel -f /path/to/database_devel.img \
--connect=qemu:///system</span> 
</pre></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-o:</span> originálny virtuálny počítač</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-n:</span> meno nového virtuálneho počítača.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">-f:</span> cesta k súboru, logickému zväzku alebo diskovému oddielu, ktorý bude používať nový virtuálny počítač.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">--connect:</span> určuje, ku ktorému hypervízoru (virtualizátoru) sa má pripojiť.</p>
        </li>
</ul></div>
<p class="para">Tiež môžete použiť<span class="em emphasis">-d</span> alebo <span class="em emphasis">--debug</span> ak chcete získať podrobný výpis pri riešení problémov s <span class="app application">virt-clone</span>.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Mená <span class="em emphasis">web_vyvoj</span> a <span class="em emphasis">databaz_vyvoj</span> nahraďte menami svojich virtuálnych počítačov.</p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="libvirt-management"><div class="inner">
<div class="hgroup"><h2 class="title">Správa virtuálnych počítačov</h2></div>
<div class="region">
<div class="contents"></div>
<div class="sect3 sect" id="virsh"><div class="inner">
<div class="hgroup"><h3 class="title">virsh</h3></div>
<div class="region"><div class="contents">
<p class="para">Existuje niekoľko nástrojov na správu virtuálnych počítačov a <span class="app application">libvirt</span>. Nástroj <span class="app application">virsh</span> sa dá používať z príkazového riadka. Niekoľko príkladov:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
            <p class="para">Vypísanie zoznamu spustených virtuálnych počítačov:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system list</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Spustenie virtuálneho počítača:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system start web_vyvoj</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Spustenie virtuálneho počítača pri zavádzaní systému</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system autostart web_vyvoj</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Reštart virtuálneho počítača:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system reboot web_vyvoj</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Aktuálny <span class="em emphasis">stav</span> virtuálneho počítača sa dá uložiť do súboru a neskôr sa dá obnoviť. Nasledujúci príkaz uloží stav virtuálneho počítača do súboru, ktorý má v mene aktuálny dátum:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system save web_vyvoj web_vyvoj-022708.state</span>
</pre></div>

            <p class="para">Po uložení virtuálny počítač zostane vypnutý.</p>
          </li>
<li class="list itemizedlist">
            <p class="para">Obnovenie uloženého stavu:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system restore web_vyvoj-022708.state</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Vypnutie virtuálneho počítača:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system shutdown web_vyvoj</span>
</pre></div>
          </li>
<li class="list itemizedlist">
            <p class="para">Pripojenie CDROMu do virtuálneho počítača:</p>

            <div class="screen"><pre class="contents "><span class="cmd command">virsh -c qemu:///system attach-disk web_vyvoj /dev/cdrom /media/cdrom</span>
</pre></div>
          </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
          <p class="para">V predchádzajúcich príkladoch nahraďte <span class="em emphasis">web_vyvoj</span> názvom vášho virtuálneho počítača a <span class="file filename">web_vyvoj-270208.state</span> nahraďte popisnejším názvom súboru.</p>
        </div></div></div></div>
</div></div>
</div></div>
<div class="sect3 sect" id="virt-manager"><div class="inner">
<div class="hgroup"><h3 class="title">Správca virtuálnych počítačov</h3></div>
<div class="region"><div class="contents">
<p class="para">Balík <span class="app application">virt-manager</span> obsahuje grafický nástroj na správu lokálnych a vzdialených virtuálnych počítačov. Nástroj virt-manager nainštalujeme pomocou príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install virt-manager</span>
</pre></div>
<p class="para">Kvôli tomu, že <span class="app application">virt-manager</span> vyžaduje grafické rozhranie (GUI), odporúčame ho nainštalovať na pracovnú stanicu a nie na server v ostrej prevádzke. Ak sa chceme pripojiť k lokálnej službe <span class="app application">libvirt</span> zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">virt-manager -c qemu:///system</span>
</pre></div>
<p class="para">Môžeme sa však pripojiť aj k službe <span class="app application">libvirt</span>, ktorá je spustená na inej stanici, zadaním nasledujúceho príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">virt-manager -c qemu+ssh://virtnode1.nieco.sk/system</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
          <p class="para">V predchádzajúcom príklade predpokladáme, že sa medzi počítačmi dá nadviazať spojenie cez <span class="app application">SSH</span>, a že počítač virtnode1.nieco.sk už bol nakonfigurovaný a používa na autentifikáciu SSH kľúče. SSH <span class="em emphasis">kľúče</span> sú nevyhnutné, pretože <span class="app application">libvirt</span> posiela výzvu na zadanie hesla do iného procesu. Viac informácii o konfigurovaní <span class="app application">SSH</span> sa nachádza v časti <a class="xref" href="openssh-server.html" title="OpenSSH Server">OpenSSH Server</a>.</p>
        </div></div></div></div>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="libvirt-virt-viewer"><div class="inner">
<div class="hgroup"><h2 class="title">Prehliadač virtuálnych počítačov</h2></div>
<div class="region"><div class="contents">
<p class="para">Aplikácia <span class="app application">virt-viewer</span> umožňuje pripojenie ku konzole virtuálneho počítača. Nástroj <span class="app application">virt-viewer</span> vyžaduje grafické rozhranie (GUI) aby sa vedel spojiť s virtuálnym počítačom.</p>
<p class="para">Nástroj <span class="app application">virt-viewer</span> nainštalujeme zadaním:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install virt-viewer</span>
</pre></div>
<p class="para">Ak je virtuálny počítač už nainštalovaný a spustený, môžeme sa ku nemu pripojiť zadaním nasledujúceho príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">virt-viewer -c qemu:///system web_vyvoj</span>
</pre></div>
<p class="para">Podobne ako <span class="app application">virt-manager</span>, aj <span class="app application">virt-viewer</span> sa vie pripojiť k vzdialenej stanici pomocou <span class="em emphasis">SSH</span> s autentifikáciou pomocou kľúčov:</p>
<div class="screen"><pre class="contents "><span class="cmd command">virt-viewer -c qemu+ssh://virtnode1.nieco.sk/system web_vyvoj</span>
</pre></div>
<p class="para">Názov <span class="em emphasis">web_vývoj</span> nahradíme názvom nášho virtuálneho počítača.</p>
<p class="para">If configured to use a <span class="em emphasis">bridged</span> network
      interface you can also setup <span class="app application">SSH</span> access to
      the virtual machine.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="libvirt-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">See the <a href="http://www.linux-kvm.org/" class="ulink" title="http://www.linux-kvm.org/">KVM</a>
          home page for more details.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Viac informácií o <span class="app application">libvirt</span> sa dozviete na <a href="http://libvirt.org/" class="ulink" title="http://libvirt.org/">libvirt home page</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">The <a href="http://virt-manager.org/" class="ulink" title="http://virt-manager.org/">Virtual
          Machine Manager</a> site has more information on
          <span class="app application">virt-manager</span> development.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">O virtualizačnej technológii v Ubuntu sa môžete dozvedieť viac aj v diskusnom kanále IRC <span class="em emphasis">#ubuntu-virt</span> na <a href="http://freenode.net/" class="ulink" title="http://freenode.net/">freenode</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Ďalším dobrým zdrojom je stránka <a href="https://help.ubuntu.com/community/KVM" class="ulink" title="https://help.ubuntu.com/community/KVM">Ubuntu Wiki KVM</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">For information on Xen, including using Xen with libvirt,
          please see the <a href="https://help.ubuntu.com/community/Xen" class="ulink" title="https://help.ubuntu.com/community/Xen">Ubuntu Wiki Xen</a>
          page.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="virtualization.html" title="Virtualizácia">Predchádzajúca</a><a class="nextlinks-next" href="cloud-images-and-uvtool.html" title="Cloud images and uvtool">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
