<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Sieťový súborový systém (NFS)</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="file-servers.html" title="Súborové servery">Súborové servery</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="ftp-server.html" title="FTP Server">Predchádzajúca</a><a class="nextlinks-next" href="iscsi-initiator.html" title="iSCSI Initiator">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Sieťový súborový systém (NFS)</h1></div>
<div class="region">
<div class="contents">
<p class="para">NFS umožňuje zdieľanie priečinkov a súborov s ostatnými systémami v sieti. Pri použití NFS používatelia a programy môžu pristupovať k súborom, ako keby pristupovali k súborom na lokálnom počítači.</p>
<p class="para">Medzi najväčšie výhody, ktoré NFS poskytuje patrí toto:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
      <p class="para">Lokálne stanice môžu použiť menej diskového priestoru, pretože spoločne využívané dáta môžu byť uložené na jednom počítači a všetkým dostupné cez sieť.</p>
          </li>
<li class="list itemizedlist">
      <p class="para">Nie je potrebné každému používateľovi vytvoriť vlastný domovský priečinok na každej stanici. Domovské priečinky sa môžu nachádzať na NFS serveri a môžu byť dostupné cez sieť.</p>
          </li>
<li class="list itemizedlist">

      <p class="para">Rôzne zariadenia ako disketové mechaniky, CDROM mechaniky a USB mechaniky môžu byť používané aj ostatnými počítačmi v sieti, čo môže znížiť počet potrebných mechaník pre prenosné média.</p>
          </li>
</ul></div>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="network-file-system.html#nfs-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="network-file-system.html#nfs-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="network-file-system.html#nfs-client-configuration" title="Konfigurácia NFS Clienta">Konfigurácia NFS Clienta</a></li>
<li class="links"><a class="xref" href="network-file-system.html#nfs-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="nfs-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">NFS server nainštalujeme tak, že do príkazového riadka zadáme nasledujúci príkaz:</p>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install nfs-kernel-server</span>
</pre></div>
          </p>
</div></div>
</div></div>
<div class="sect2 sect" id="nfs-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Priečinky, ktoré majú byť zdieľané môžeme, pridať do súboru <span class="file filename">/etc/exports</span>. Napríklad:</p>
<p class="para">
<div class="screen"><pre class="contents ">/ubuntu  *(ro,sync,no_root_squash)
/home    *(rw,sync,no_root_squash)
</pre></div>
          </p>
<p class="para">Znak * môžeme nahradiť maskou názvu staníc. Deklaráciu názvu staníc urobme tak konkrétnu, ako sa len dá, aby neoprávnené systémy nemohli pristupovať k zdieľaným NFS priečinkom.</p>
<p class="para">Po dokončení spustíme NFS server zadaním nasledujúceho príkazu:</p>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo service nfs-kernel-server start</span>
</pre></div>
          </p>
</div></div>
</div></div>
<div class="sect2 sect" id="nfs-client-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia NFS Clienta</h2></div>
<div class="region"><div class="contents">
<p class="para">Zdieľaný NFS priečinok z inej stanice pripojíme pomocou príkazu <span class="app application">mount</span>, zadaním príkazu, ktorý bude podobný ako tento:</p>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo mount menopc.nieco.sk:/ubuntu /local/ubuntu</span>
</pre></div>
</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
      <p class="para">Cieľový priečinok <span class="file filename">/local/ubuntu</span> musí existovať. Nemali by v ňom byť žiadne súbory ani podpriečinky.</p>
      </div></div></div></div>
<p class="para">Iný spôsob, akým sa dajú pripojiť zdieľané NFS priečinky z iných staníc, je pridanie záznamu do súboru <span class="file filename">/etc/fstab</span>. Riadok musí obsahovať meno stanice NFS servera, zdieľaný priečinok a priečinok na lokálnej stanici, do ktorého sa zdieľaný priečinok má pripojiť.</p>
<p class="para">Všeobecná syntax riadka v súbore <span class="file filename">/etc/fstab</span> je takáto:</p>
<div class="code"><pre class="contents ">menopc.nieco.sk:/ubuntu /local/ubuntu nfs rsize=8192,wsize=8192,timeo=14,intr
</pre></div>
<p class="para">Ak sa nám nedarí zdieľaný NFS priečinok pripojiť, uistíme sa, či je na klientskom počítači nainštalovaný balík <span class="app application">nfs-common</span>. Balik <span class="app application">nfs-common</span> nainštalujeme zadaním nasledujúceho príkazu do príkazového riadka: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install nfs-common</span>
</pre></div></p>
</div></div>
</div></div>
<div class="sect2 sect" id="nfs-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<p class="para"><a href="http://nfs.sourceforge.net/" class="ulink" title="http://nfs.sourceforge.net/">Linux NFS faq</a></p>
<p class="para">
                <a href="https://help.ubuntu.com/community/NFSv4Howto" class="ulink" title="https://help.ubuntu.com/community/NFSv4Howto">Ubuntu Wiki NFS Howto</a>
                </p>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="ftp-server.html" title="FTP Server">Predchádzajúca</a><a class="nextlinks-next" href="iscsi-initiator.html" title="iSCSI Initiator">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
