<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>PHP5 - Skriptovací jazyk</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="web-servers.html" title="Webové servery">Webové servery</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="httpd.html" title="HTTPD - Apache2 Web Server">Predchádzajúca</a><a class="nextlinks-next" href="squid.html" title="Squid - Sprostredkovateľský (proxy) server">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">PHP5 - Skriptovací jazyk</h1></div>
<div class="region">
<div class="contents">
<p class="para">PHP je všeobecný skriptovací jazyk zameraný na vytváranie webových aplikácií. PHP skript sa dá začleniť do HTML. Táto časť vysvetľuje, ako nainštalovať a nakonfigurovať PHP5 v systéme Ubuntu so systémami Apache2 a MySQL.</p>
<p class="para">Táto časť predpokladá, že už máme nainštalovaný a nakonfigurovaný webový server Apache 2 a databázový server MySQL. Návod, ako tieto systémy nainštalovať a nakonfigurovať, nájdeme v častiach Apache2 a MySQL tejto príručky.</p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="php5.html#php5-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="php5.html#php5-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="php5.html#php5-testing" title="Testovanie">Testovanie</a></li>
<li class="links"><a class="xref" href="php5.html#php5-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="php5-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">The PHP5 is available in Ubuntu Linux. Unlike python and
      perl, which are installed in the base system, PHP must be added.
      </p>
<div class="steps"><div class="inner"><ul class="steps"><li class="steps">
<p class="para">Ak chceme nainštalovať PHP5, môžeme zadať nasledujúci príkaz do príkazového riadka: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install php5 libapache2-mod-php5</span>
</pre></div></p>

      <p class="para">PHP5 skripty môžeme spustiť aj v príkazovom riedku. Aby sme mohli spúšťať PHP5 skripty v príkazovom riadku, je potrebné nainštalovať balík <span class="app application">php5-cli</span>. Balík <span class="app application">php5-cli</span> nainštalujeme pomocou nasledujúceho príkazu: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install php5-cli</span>
</pre></div></p>
      <p class="para">PHP5 skripty môžeme spúšťať aj bez nainštalovaného modulu PHP5 pre  Apache. Aby to bolo možné, je potrebné nainštalovať balík <span class="app application">php5-cgi</span>. Balík <span class="app application">php5-cgi</span> nainštalujeme nasledujúcim príkazom: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install php5-cgi</span>
</pre></div></p>
      <p class="para">Aby bolo možné prepojiť databázu <span class="app application">MySQL</span> s PHP5, je potrebné nainštalovať balík <span class="app application">php5-mysql</span>. Balík <span class="app application">php5-mysql</span> môžeme nainštalovať zadaním tohto príkazu: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install php5-mysql</span>
</pre></div></p>
      <p class="para">Rovnako môžeme prepojiť databázu <span class="app application">PostgreSQL</span> s PHP5 tak, že nainštalujeme balík <span class="app application">php5-pgsql</span>. Balík <span class="app application">php5-pgsql</span> nainštalujeme zadaním príkazu: <div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install php5-pgsql</span>
</pre></div></p>
			</li></ul></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="php5-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Po nainštalovaní PHP5 môžeme spúšťať PHP5 skripty z webového prehliadača. Ak sme nainštalovali balík <span class="app application">php5-cli</span>, môžeme PHP5 skripty spúšťať aj v príkazovom riadku.</p>
<p class="para">V predvolenom stave je webový server Apache 2 nakonfigurovaný tak, aby spúšťal PHP5 skripty. Inak povedané, modul PHP5 sa vo webovom serveri Apache2 automaticky zapne po nainštalovaní modulu. Stačí overiť, či existujú súbory <span class="file filename">/etc/apache2/mods-enabled/php5.conf</span> a <span class="file filename">/etc/apache2/mods-enabled/php5.load</span>. Ak neexistujú, môžeme modul zapnúť pomocou príkazu <span class="cmd command">a2enmod</span>.</p>
<p class="para">Once you install PHP5 related packages and enabled PHP5
          Apache 2 module, you should restart Apache2 Web server to run
          PHP5 scripts. You can run the following command at a terminal
          prompt to restart your web server:
<div class="screen"><pre class="contents "><span class="cmd command">sudo service apache2 restart</span> </pre></div>
          </p>
</div></div>
</div></div>
<div class="sect2 sect" id="php5-testing"><div class="inner">
<div class="hgroup"><h2 class="title">Testovanie</h2></div>
<div class="region"><div class="contents">
<p class="para">Aby sme overili funkčnosť inštalácie, môžeme spustiť PHP5 skript s funkciou phpinfo:</p>
<div class="code"><pre class="contents ">&lt;?php
  phpinfo();
?&gt;
</pre></div>
<p class="para">Tento text uložíme do súboru <span class="file filename">phpinfo.php</span> a umiestnime do priečinka <span class="cmd command">DocumentRoot</span> (hlavný priečinok webu) webového servera Apache2. Ak do prehliadača zadáme adresu <span class="file filename">http://nazovstanice/phpinfo.php</span>, mali by sa zobraziť hodnoty rôznych konfiguračných nastavení PHP5.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="php5-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
            <p class="para">Viac detailnejších informácií sa nachádza v dokumentácii na stránke <a href="http://www.php.net/docs.php" class="ulink" title="http://www.php.net/docs.php">php.net</a>.</p> 
          </li>
<li class="list itemizedlist">
            <p class="para">Existuje nespočetné množstvo kníh o PHP. Dve veľmi dobré knihy od O'Reillyho sú <a href="http://oreilly.com/catalog/9780596005603/" class="ulink" title="http://oreilly.com/catalog/9780596005603/">Learning PHP 5</a> a <a href="http://oreilly.com/catalog/9781565926813/" class="ulink" title="http://oreilly.com/catalog/9781565926813/">PHP Cook Book</a>.</p> 
          </li>
<li class="list itemizedlist">
            <p class="para">Viac informácií sa môžeme dozvedieť aj na stránke <a href="https://help.ubuntu.com/community/ApacheMySQLPHP" class="ulink" title="https://help.ubuntu.com/community/ApacheMySQLPHP">Apache MySQL PHP Ubuntu Wiki</a>.</p> 
          </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="httpd.html" title="HTTPD - Apache2 Web Server">Predchádzajúca</a><a class="nextlinks-next" href="squid.html" title="Squid - Sprostredkovateľský (proxy) server">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
