<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>As a Domain Controller</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="samba.html" title="Samba">Samba</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-fileprint-security.html" title="Securing File and Print Server">Predchádzajúca</a><a class="nextlinks-next" href="samba-ad-integration.html" title="Active Directory Integration">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">As a Domain Controller</h1></div>
<div class="region">
<div class="contents"><p class="para">Aj keď sa samba nedá použiť ako primárny radič domény v Active Directory – Active Directory Primary Domain Controller (PDC), Samba server môže byť nakonfigurovaná tak, aby sa tváril ako radič domény systému Windows NT4. Hlavná výhoda takejto konfigurácie je schopnosť centrálne spravovať prihlasovacie údaje všetkých používateľov a počítačov. Samba dokáže na uchovávanie informácií o používateľoch použiť viacero systémov.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="samba-dc.html#samba-pdc-smbpasswd" title="Primárny radič domény">Primárny radič domény</a></li>
<li class="links"><a class="xref" href="samba-dc.html#samba-bdc-smbpasswd" title="Záložný radič domény">Záložný radič domény</a></li>
<li class="links"><a class="xref" href="samba-dc.html#samba-dc-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="samba-pdc-smbpasswd"><div class="inner">
<div class="hgroup"><h2 class="title">Primárny radič domény</h2></div>
<div class="region"><div class="contents">
<p class="para">Táto časť hovorí o nastavení systému Samba tak, aby sa tváril ako primárny radič domény (PDC), pričom na uchovávanie informácií o používateľoch použijeme predvolený systém smbpasswd.</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">

          <p class="para">Najskôr nainštalujeme systém Samba a balík <span class="app application">libpam-smbpass</span>, ktorý slúži na synchronizáciu používateľov. Do príkazového riadka zadáme:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install samba libpam-smbpass</span>
</pre></div>
        
        </li>
<li class="steps">

          <p class="para">Ďalej otvoríme konfiguračný súbor systému Samba <span class="file filename">/etc/samba/smb.conf</span>. Bezpečnostný režim <span class="em emphasis">security</span> nastavíme na hodnotu <span class="em emphasis">user</span> a pracovnú skupinu <span class="em emphasis">workgroup</span> nastavíme podľa názvu našej organizácie:</p>

<div class="code"><pre class="contents ">   workgroup = NIECO
   ...
   security = user
</pre></div>

        </li>
<li class="steps">

          <p class="para">
          In the commented <span class="quote">„Domains“</span> section add or uncomment the following (the last line has been split to fit the format of this document):
          </p>

<div class="code"><pre class="contents ">   domain logons = yes
   logon path = \\%N\%U\profile
   logon drive = H:
   logon home = \\%N\%U
   logon script = logon.cmd
   add machine script = sudo /usr/sbin/useradd -N -g machines -c Machine -d
         /var/lib/samba -s /bin/false %u
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Ak nechcete použiť tzv. <span class="em emphasis">cestovné profily (Roaming Profiles)</span>, ponechajte možnosti <span class="em emphasis">logon home</span>  a <span class="em emphasis">logon path</span> zapoznámkované.</p>
          </div></div></div></div>
 
          <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">domain logons:</span> spôsobí, že sa Samba bude pri prihlasovaní tváriť ako radič domény.</p>
            </li>
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">logon path:</span> umiestnenie domovského priečinka z pohľadu používateľa Windows. Tu je však potrebné odkomentovať aj nastavenie zdieľania v časti <span class="em emphasis">[profiles]</span>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">logon drive:</span> určuje jednotku, pod akou používateľ uvidí svoj priečinok.</p>
            </li>
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">logon home:</span> určuje umiestnenie domovského priečinka.</p>
            </li>
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">logon script:</span> určuje skript, ktorý sa spustí na lokálnej stanici po prihlásení používateľa. Skript je potrebné umiestniť do zdieľaného priečinka <span class="em emphasis">[netlogon]</span>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para"><span class="em emphasis">add machine script:</span> skript, ktorý automaticky vytvorí tzv. <span class="em emphasis">dôveryhodné konto stanice - Machine Trust Account</span> potrebné na to, aby sa počítač mohol pripojiť do domény.</p>
              <p class="para">V tomto príklade tiež bude potrebné vytvoriť skupinu s názvom <span class="em emphasis">machines</span> pomocou nástroja <span class="app application">addgroup</span>. Viac informácií sa nachádza v časti  <a class="xref" href="user-management.html#adding-deleting-users" title="Pridávanie a odstraňovanie používateľov">Pridávanie a odstraňovanie používateľov</a>.</p>

            </li>
</ul></div>

        </li>
<li class="steps">
     
          <p class="para">Odpoznámkujeme zdieľanie priečinka <span class="em emphasis">[homes]</span>, aby bolo možné pripojiť <span class="em emphasis">domovské priečinky</span>:</p>

<div class="code"><pre class="contents ">[homes]
   comment = Home Directories
   browseable = no
   read only = no
   create mask = 0700
   directory mask = 0700
   valid users = %S
</pre></div>

        </li>
<li class="steps">

          <p class="para">Ak chceme server použiť ako radič domény, je potrebné nakonfigurovať aj zdieľanie priečinka <span class="em emphasis">[netlogon]</span>. Stačí odkomentovať nasledujúce riadky:</p>

<div class="code"><pre class="contents ">[netlogon]
   comment = Network Logon Service
   path = /srv/samba/netlogon
   guest ok = yes
   read only = yes
   share modes = no
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Originálny priečinok <span class="em emphasis">netlogon</span> je umiestnený na ceste <span class="file filename">/home/samba/netlogon</span>, ale podľa štandardu Filesystem Hierarchy Standard (FHS) je na tento účel správnejšie použiť priečinok <a href="http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM" class="ulink" title="http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM">/srv</a>.</p>
          </div></div></div></div>

        </li>
<li class="steps">

          <p class="para">Teraz vytvoríme priečinok <span class="file filename">netlogon</span> a (zatiaľ) prázdny súbor s prihlasovacím skriptom <span class="file filename">logon.cmd</span>:</p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo mkdir -p /srv/samba/netlogon</span>
<span class="cmd command">sudo touch /srv/samba/netlogon/logon.cmd</span>
</pre></div>
 
          <p class="para">Do tohto súboru <span class="file filename">logon.cmdm</span></p>

        </li>
<li class="steps">

          <p class="para">
          Restart Samba to enable the new domain controller:
          </p> 

<div class="screen"><pre class="contents "><span class="cmd command">sudo restart smbd</span>
<span class="cmd command">sudo restart nmbd</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">
          Lastly, there are a few additional commands needed to setup the appropriate rights.
          </p>

          <p class="para">Keďže používateľ <span class="em emphasis">root</span> je z bezpečnostných dôvodov zablokovaný, je potrebné priradiť niektorú zo systémových skupín ku Windows skupine s názvom <span class="em emphasis">Domain Admins</span>, inak sa nebudú dať pracovné stanice pripojiť do domény. Urobíme to pomocou nástroja <span class="app application">net</span>, ktorý takýmto spôsobom zapíšeme do príkazového riadka:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo net groupmap add ntgroup="Domain Admins" unixgroup=sysadmin rid=512 type=d</span>
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Skupinu <span class="em emphasis">sysadmin</span>, ktorú sme my použili, zmeňte na takú, akú používate. Používatelia, ktorí sú členmi skupiny <span class="em emphasis">sysadmin</span>, by mali byť členmi aj systémovej skupiny <span class="em emphasis">admin</span>. Skupina <span class="em emphasis">admin</span> umožňuje použitie príkazu <span class="app application">sudo</span>.</p>
            <p class="para">
            If the user does not have Samba credentials yet, you can add them with
            the <span class="app application">smbpasswd</span> utility, change the <span class="em emphasis">sysadmin</span> username appropriately:

<div class="screen"><pre class="contents "><span class="cmd command">sudo smbpasswd -a sysadmin</span>
</pre></div>
            </p>
          </div></div></div></div>

          <p class="para">Aby add machine script (a ostatné správcovské funkcie) fungovali, je potrebné, aby sme to explicitne povolili skupine Domain Admins. To dosiahneme príkazom:</p>
<div class="screen"><pre class="contents "><span class="cmd command">net rpc rights grant -U sysadmin "EXAMPLE\Domain Admins" SeMachineAccountPrivilege \
SePrintOperatorPrivilege SeAddUsersPrivilege SeDiskOperatorPrivilege \
SeRemoteShutdownPrivilege</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Odteraz bude možné klientské počítače so systémom Windows pripojiť do domény tak, ako keby sa pripájali do domény na serveri Windows NT4.</p>

        </li>
</ol></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="samba-bdc-smbpasswd"><div class="inner">
<div class="hgroup"><h2 class="title">Záložný radič domény</h2></div>
<div class="region"><div class="contents">
<p class="para">Spolu s primárnym radičom domény (PDC) je vhodné mať na sieti aj záložný radič domény Backup Domain Controller (BDC). Tento umožňuje autentifikáciu klientov v prípade, ak nastane výpadok PDC.</p>
<p class="para">Keď chceme systém Samba použiť ako BDC, potrebujeme nejakým spôsobom zosynchronizovať informácie o používateľských účtoch s PDC. Túto úlohu je možné vykonať niekoľkými spôsobmi. Napríklad môžeme použiť nástroje <span class="app application">scp</span>, <span class="app application">rsync</span> alebo môžeme použiť miesto predvolenej databázy na uchovávanie autentifikačných údajov (<span class="em emphasis">passdb backend</span>) databázu <span class="app application">LDAP</span>.</p>
<p class="para">Použitie systému LDAP je veľmi výhodný spôsob na synchronizáciu informácii o kontách, pretože oba doménové radiče môžu v rovnakom čase použiť tie isté informácie. Avšak nastavenie LDAP servera môže byť príliš komplikované a neoplatí sa, ak máme v sieti iba malý počet počítačov a používateľov. Viac informácií sa nachádza v časti xref linkend="samba-ldap"/&gt;.</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
   
          <p class="para">Najskôr nainštalujeme balíky <span class="app application">samba</span> a <span class="app application">libpam-smbpass</span>. V príkazovom riadku zadáme:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install samba libpam-smbpass</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Otvoríme súbor <span class="file filename">/etc/samba/smb.conf</span> a zmeníme nasledujúce riadky v časti <span class="em emphasis">[global]</span>:</p>

<div class="code"><pre class="contents ">   workgroup = NIECO
   ...
   security = user
</pre></div>

        </li>
<li class="steps">

        <p class="para">V časti <span class="em emphasis">Domains</span> odkomentujeme riadky:</p>

<div class="code"><pre class="contents ">   domain logons = yes
   domain master = no
</pre></div>
        
        </li>
<li class="steps">

          <p class="para">Uistíme sa, že používateľ má právo čítať súbory v priečinku <span class="file filename">/var/lib/samba</span>. Napríklad ak chceme používateľom v skupine <span class="em emphasis">admin</span> povoliť použitie nástroja <span class="app application">scp</span> zadáme:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo chgrp -R admin /var/lib/samba</span>
</pre></div>

        </li>
<li class="steps">

          <p class="para">Teraz synchronizujeme kontá pomocou nástroja <span class="app application">scp</span>, ktorým ich skopírujeme z priečinka <span class="file filename">/var/lib/samba</span> z PDC:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo scp -r menopouzivatela@pdc:/var/lib/samba /var/lib</span>
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Miesto <span class="em emphasis">menopouzivatela</span> zadajte používateľa a miesto <span class="em emphasis">pdc</span> zadajte názov stanice alebo IP adresu počítača, ktorý je PDC.</p>
          </div></div></div></div>

        </li>
<li class="steps">
          
          <p class="para">Nakoniec reštartujeme systém <span class="app application">samba</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo restart smbd</span>
<span class="cmd command">sudo restart nmbd</span>
</pre></div>

        </li>
</ol></div></div>
<p class="para">Záložný radič domény môžeme otestovať tak, že zastavíme démona systému Samba na PDC a potom sa skúsime prihlásiť na niektorej Windows stanici, ktorá je súčasťou domény.</p>
<p class="para">Ďalšia vec, ktorú je potrebné mať na pamäti, čo s priečinkami definovaným ako <span class="em emphasis">logon home</span> na PDC, ak sa PDC stane nedostupný. V takom prípade nebudú dostupné ani domovské priečinky používateľov. Kvôli tomuto je výhodné nastaviť <span class="em emphasis">logon home</span> na iný súborový server, ktorý nie je súčasťou PDC ani BDC.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="samba-dc-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Podrobnejšie informácie o nastavení systému Samba sa nachádzajú na stránke <a href="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/" class="ulink" title="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/">Samba HOWTO Collection</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Príručka je dostupná aj vo verzii <a href="http://www.amazon.com/exec/obidos/tg/detail/-/0131882228" class="ulink" title="http://www.amazon.com/exec/obidos/tg/detail/-/0131882228">pre tlač</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Ďalším dobrým zdrojom je O'Reillyho <a href="http://www.oreilly.com/catalog/9780596007690/" class="ulink" title="http://www.oreilly.com/catalog/9780596007690/">Using Samba</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><a href="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/samba-pdc.html" class="ulink" title="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/samba-pdc.html">Kapitola 4</a> zo Samba HOWTO Collection je zameraná na primárny radič domény.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><a href="http://us3.samba.org/samba/docs/man/Samba-HOWTO-Collection/samba-bdc.html" class="ulink" title="http://us3.samba.org/samba/docs/man/Samba-HOWTO-Collection/samba-bdc.html">Kapitola 5</a> zo Samba HOWTO Collection je zameraná na záložný radič domény.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Tiež stránka <a href="https://help.ubuntu.com/community/Samba" class="ulink" title="https://help.ubuntu.com/community/Samba">Ubuntu Wiki Samba </a>.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-fileprint-security.html" title="Securing File and Print Server">Predchádzajúca</a><a class="nextlinks-next" href="samba-ad-integration.html" title="Active Directory Integration">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
