<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Active Directory Integration</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="samba.html" title="Samba">Samba</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-dc.html" title="As a Domain Controller">Predchádzajúca</a><a class="nextlinks-next" href="backups.html" title="Zálohovanie">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Active Directory Integration</h1></div>
<div class="region">
<div class="contents"></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="samba-ad-integration.html#ad-integration-samba-share" title="Prístup k zdieľaným prostriedkom systému Samba">Prístup k zdieľaným prostriedkom systému Samba</a></li>
<li class="links"><a class="xref" href="samba-ad-integration.html#ad-integration-windows-share" title="Prístup k zdieľaným prostriedkom systému Windows">Prístup k zdieľaným prostriedkom systému Windows</a></li>
<li class="links"><a class="xref" href="samba-ad-integration.html#ad-integration-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="ad-integration-samba-share"><div class="inner">
<div class="hgroup"><h2 class="title">Prístup k zdieľaným prostriedkom systému Samba</h2></div>
<div class="region"><div class="contents">
<p class="para">Iný spôsob použitia systému Samba je jeho integrovanie do existujúcej siete Windows. Jednou z funkcií systému Samba je aj to, že môže slúžiť ako súborový a tlačový server pre používateľov AD.</p>
<p class="para">
      The simplest way to join an AD domain is to use <span class="app application">Likewise-open</span>.  For detailed instructions
      see the <a href="http://www.beyondtrust.com/Technical-Support/Downloads/files/pbiso/Manuals/ubuntu-active-directory.html" class="ulink" title="http://www.beyondtrust.com/Technical-Support/Downloads/files/pbiso/Manuals/ubuntu-active-directory.html"> 
      Likewise Open documentation</a>.
      </p>
<p class="para">
      Once part of the Active Directory domain, enter the following command in the terminal prompt:
      </p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt-get install samba smbfs smbclient</span>
</pre></div>
<p class="para">Teraz otvoríme súbor <span class="file filename">/etc/samba/smb.conf</span> a zmeníme:</p>
<div class="code"><pre class="contents ">   workgroup = NIECO
   ...
   security = ads
   realm = NIECO.SK
   ...
   idmap backend = lwopen
   idmap uid = 50-9999999999
   idmap gid = 50-9999999999
</pre></div>
<p class="para">Reštartujeme systém <span class="app application">samba</span> aby sa nové nastavenia prejavili:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo restart smbd</span>
<span class="cmd command">sudo restart nmbd</span>
</pre></div>
<p class="para">Odteraz by sa malo dať pristupovať k zdieľaným prostriedkom systému <span class="app application">Samba</span> zo staníc so systémom Windows. Je však potrebné sa uistiť či používatelia a skupiny AD majú právo pristupovať k zdieľaným priečinkom. Viac informácií sa nachádza v časti <a class="xref" href="samba-fileprint-security.html" title="Securing File and Print Server">Securing File and Print Server</a>.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="ad-integration-windows-share"><div class="inner">
<div class="hgroup"><h2 class="title">Prístup k zdieľaným prostriedkom systému Windows</h2></div>
<div class="region"><div class="contents">
<p class="para">Teraz keď je Samba server súčasťou domény Active Directory, môžeme pristupovať k zdieľaným prostriedkom systémov Windows:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">

          <p class="para">Ak chceme pripojiť priečinok zdieľaný systémom Windows zadáme nasledujúci príkaz:</p>
<div class="screen"><pre class="contents "><span class="cmd command">mount.cifs //fs01.nieco.sk/zdielanie bod_pripojenia</span>
</pre></div>

          <p class="para">Je tiež možné pristupovať k zdieľaným prostriedkom, ktoré ni sú súčasťou domény AD, ale v tom prípade bude potrebné zadať používateľské meno a heslo.</p>

        </li>
<li class="list itemizedlist">

          <p class="para">Ak chceme pripojiť priečinok už pri zavádzaní systému, pridáme záznam do súboru <span class="file filename">/etc/fstab</span>. Záznam môže vyzerať napríklad takto:</p>

<div class="code"><pre class="contents ">//192.168.0.5/zdielanie /mnt/windows cifs auto,username=stefan,password=tajne,rw 0        0
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">Iný spôsob akým môžeme skopírovať súbory zo systému Windows je použitie nástroja <span class="app application">smbclient</span>. Zoznam súborov v zdieľanom priečinku systému Windows získame po zadaní:</p>

<div class="screen"><pre class="contents "><span class="cmd command">smbclient //fs01.nieco.sk/zdielanie -k -c "ls"</span>
</pre></div>

        </li>
<li class="list itemizedlist">

          <p class="para">Kópiu súboru získame po zadaní:</p>

<div class="screen"><pre class="contents "><span class="cmd command">smbclient //fs01.nieco.sk/zdielanie -k -c "get subor.txt"</span>
</pre></div>

          <p class="para">Tento príkaz skopíruje súbor s názvom <span class="file filename">subor.txtdo aktu</span></p>

        </li>
<li class="list itemizedlist">

          <p class="para">Kópiu lokálneho súboru odošleme do zdielaného priečinka zadaním:</p>

<div class="screen"><pre class="contents "><span class="cmd command">smbclient //fs01.nieco.sk/zdielanie -k -c "put /etc/hosts hosts"</span>
</pre></div>

          <p class="para">Tento príkaz skopíruje súbor <span class="file filename">/etc/hosts</span> to do <span class="file filename">//fs01.nieco.sk/zdielanie/hosts</span>.</p>

        </li>
<li class="list itemizedlist">

          <p class="para">Voľba <span class="em emphasis">-c</span>, ktorú sme použili, umožňuje spustiť pomocou nástroja <span class="app application">smbclient</span> zadaný príkaz. Tento spôsob spúšťania je užitočný pri vytváraní skriptov. Ak chceme vstúpiť do príkazového riadka <span class="em emphasis">smb: \&gt;</span>, ktorý je podobný príkazovému riadku FTP, v ktorom môžeme normálne spúšťať príkazy, zadáme len:</p>

<div class="screen"><pre class="contents "><span class="cmd command">smbclient //fs01.nieco.sk/zdielanie -k</span>
</pre></div>

        </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Vo všetkých uvedených príkladoch zmeňte <span class="em emphasis">fs01.nieco.sk/zdielanie</span>, <span class="em emphasis">//192.168.0.5/zdielanie</span>, <span class="em emphasis">username=stefan, password=tajne</span> a <span class="em emphasis">subor.txt</span> na IP adresu vášho servera, názov stanice, názov zdielaného priečinka, názov súboru, prihlasovacie meno a heslo aktuálneho používateľa na údaje zodpovedajúce zdieľanému prostriedku.</p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="ad-integration-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<p class="para">
      For more <span class="app application">smbclient</span> options see the man page: <span class="cmd command">man smbclient</span>, also available
      <a href="http://manpages.ubuntu.com/manpages/trusty/en/man1/smbclient.1.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/en/man1/smbclient.1.html">online</a>.
      </p>
<p class="para">
      The <span class="app application">mount.cifs</span> 
      <a href="http://manpages.ubuntu.com/manpages/trusty/en/man8/mount.cifs.8.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/en/man8/mount.cifs.8.html">man page</a> is also useful for 
      more detailed information.
      </p>
<p class="para">Tiež stránka <a href="https://help.ubuntu.com/community/Samba" class="ulink" title="https://help.ubuntu.com/community/Samba">Ubuntu Wiki Samba </a>.</p>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-dc.html" title="As a Domain Controller">Predchádzajúca</a><a class="nextlinks-next" href="backups.html" title="Zálohovanie">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
