<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>TCP/IP</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="networking.html" title="Sieť">Sieť</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="network-configuration.html" title="Konfigurácia siete">Predchádzajúca</a><a class="nextlinks-next" href="dhcp.html" title="Protokol dynamického nastavenia hostiteľov (DHCP)">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">TCP/IP</h1></div>
<div class="region">
<div class="contents"><p class="para">Transmission Control Protocol and Internet Protocol (TCP/IP) je štandardná sada protokolov (dohovorov o komunikácii), ktorá bola vyvinutá koncom sedemdesiatych rokov armádnou agentúrou Defense Advanced Research Projects Agency (DARPA) ako prostriedok na komunikáciu medzi rôznymi typmi počítačov a počítačových sietí. TCP / IP je hnacou silou Internetu, a preto je najpopulárnejším súborom sieťových protokolov na Zemi.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="tcpip.html#tcpip-introduction" title="Úvod do TCP/IP">Úvod do TCP/IP</a></li>
<li class="links"><a class="xref" href="tcpip.html#tcpip-configuration" title="Konfigurácia TCP/IP">Konfigurácia TCP/IP</a></li>
<li class="links"><a class="xref" href="tcpip.html#ip-routing" title="IP smerovanie">IP smerovanie</a></li>
<li class="links"><a class="xref" href="tcpip.html#tcp-and-udp" title="TCP a UDP">TCP a UDP</a></li>
<li class="links"><a class="xref" href="tcpip.html#icmp" title="ICMP">ICMP</a></li>
<li class="links"><a class="xref" href="tcpip.html#daemons" title="Démoni">Démoni</a></li>
<li class="links"><a class="xref" href="tcpip.html#tcpip-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="tcpip-introduction"><div class="inner">
<div class="hgroup"><h2 class="title">Úvod do TCP/IP</h2></div>
<div class="region"><div class="contents"><p class="para">Dve súčasti protokolu TCP/IP sa zaoberajú rôznymi aspektami počítačových sietí. <span class="em emphasis">Internet Protocol</span> -"IP" je protokol, ktorý sa nezaoberá pripojením, ale iba smerovaním sieťových paketov pomocou IP Datagramov a packety považuje za základnú jednotkou sieťovej informácie. <span class="em emphasis">IP Datagram</span> obsahuje hlavičku, za ktorou nasleduje správa. <span class="em emphasis">Transmission Control Protocol</span> - "TCP" umožňuje sieťovým hostiteľom (zariadeniam v sieti, ktoré majú svoju sieťovú adresu) nadviazať spojenie, ktoré sa použije na výmenu dát. TCP tiež zaručuje, že dáta budú doručené, a že do cieľa prídu v rovnakom tvare, v akom boli odoslané.</p></div></div>
</div></div>
<div class="sect2 sect" id="tcpip-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia TCP/IP</h2></div>
<div class="region"><div class="contents">
<p class="para">Konfigurácia TCP/IP protokolu pozostáva z niekoľkých prvkov, ktoré sa nastavujú v príslušných konfiguračných súboroch alebo nasadením riešenia, akým je napríklad DHCP server (protokol na dynamickú konfiguráciu staníc), ktorý môže byť nakonfigurovaný tak, aby správnu konfiguráciu TCP/IP poskytoval sieťovým klientom automaticky. Tieto konfiguračné hodnoty musia byť správne nastavené, aby systém Ubuntu mohol vykonávať sieťové operácie.</p>
<p class="para">Bežnými konfiguračnými prvkami TCP/IP sú tieto: <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">IP adresa</span> IP adresa je jedinečný identifikačný reťazec vyjadrený štyrmi dekadickými číslami v rozsahu 0 až 255 oddelených bodkami, z ktorých každé číslo reprezentuje 8 bitov adresy s celkovou dĺžkou 32 bitov. Tento formát sa nazýva <span class="em emphasis">dotted quad notation</span>.</p>
               </li>
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">Sieťová maska</span> Maska podsiete (alebo jednoducho sieťová maska) je lokálna bitová maska určujúca, ktorá časť IP adresy prislúcha sieti a ktorá časť IP adresy patrí <span class="em emphasis">podsieti</span>. Napríklad sieť triedy C má štandardnú sieťovú masku 255.255.255.0, ktorá zamaskuje prvé tri bajty (24 bitov) IP adresy a zostávajúci bajt (8 bitov) IP adresy umožňuje prideliť klientom v podsieti.</p>
               </li>
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">Adresa siete</span> Adresa siete je reprezentovaná bajtami IP adresy, ktoré prislúchajú sieti. Napríklad stanica 12.128.1.2 v sieti triedy A používa adresu siete 12.0.0.0, pričom číslo 12 reprezentované prvým bajtom IP adresy prislúcha sieti a nuly reprezentované zvyšnými troma bajtami prislúchajú hodnotám potenciálnych staníc. Klient inej siete používajúci privátnu IP adresu 192.168.1.100 používa sieťovú adresu 192.168.1.0, ktorá je určená prvými troma bajtami 192.168.1, pretože ide o sieť tried C a nulu pre potencionálnych staníc siete.</p>
               </li>
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">Broadcast adresa</span> Broadcast adresa je IP adresa, ktorá umožňuje poslať dáta naraz všetkým klientom siete v danej podsieti. Štandardná všeobecná broadcast adresa pre IP siete je 255.255.255.255, táto broadcast adresa sa však samozrejme nedá použiť na odoslanie broadcast správy každému klientovi v sieti Internet, pretože to smerovač nedovolí. Vhodnejšia broadcast adresa je nastavená tak, aby zodpovedala konkrétnej podsieti. Napríklad v privátnej sieti triedy C s adresou 192.168.1.0 bude brodacat adresa 192.168.1.255. Broadcast správy sú väčšinou vytvárané sieťovými protokolmi ako napríklad Address Resolution Protocol (ARP) a Routing Information Protocol (RIP).</p>
               </li>
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">Adresa brány</span> Adresa brány je IP adresa, cez ktorú sa dá pripojiť do určitej siete alebo ku klientovi siete. Ak jedna stanica chce komunikovať s inou stanicou, ktorá nie je umiestnená v rovnakej sieti, potom je potrebné použiť <span class="em emphasis">bránu</span>. V mnohých prípadoch je adresa brány zároveň adresou smerovača, ktorý prepúšťa komunikáciu do iných sietí - napríklad do Internetu. Adresa brány musí byť nastavená správne, inak sa váš systém nebude schopný pripojiť na žiadne stanice okrem tých, ktoré sú v rovnakej sieti.</p>
               </li>
<li class="list itemizedlist">
                  <p class="para"><span class="em em-bold emphasis">DNS adresa</span> DNS adresy predstavújú IP adresy systémov Domain Name Service (DNS), ktoré prekladajú menné adresy staníc na IP adresy. Existujú tri úrovne DNS adries, ktoré môžu byť zadané v tomto poradí: <span class="em emphasis">primárny</span> DNS server, <span class="em emphasis">sekundárny</span> DNS server a <span class="em emphasis">terciárny</span> DNS server. Aby bol váš systém schopný získavať IP adresy prislúchajúce menným adresám staníc, musíte zadať správne adresy DNS serverov, ktoré ste oprávnený používať vo Vašom nastavení TCP/IP. V mnohých prípadoch vám tieto adresy poskytne Váš dodávateľ sieťových služieb, ale existujú tiež verejne prístupné DNS servery, ako napríklad servery Level3 (Verizon) IP adresami od 4.2.2.1 po 4.2.2.6.</p>
                     <div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents">
                        <p class="para">
                        The IP address, Netmask, Network Address, Broadcast Address, Gateway Address, and Nameserver
                        Addresses are typically specified via the appropriate directives in the file
                        <span class="file filename">/etc/network/interfaces</span>. For more information, view the system manual
                        page for <span class="file filename">interfaces</span>, with the following command typed at a terminal prompt:
                        </p>
                     </div></div></div></div>
                    <p class="para">Pre zobrazenie systémového manuálu pre <span class="file filename">interfaces</span> použijeme nasledujúci príkaz:</p>
                    <p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">man interfaces</span>
</pre></div>
                    </p>
               </li>
</ul></div></p>
</div></div>
</div></div>
<div class="sect2 sect" id="ip-routing"><div class="inner">
<div class="hgroup"><h2 class="title">IP smerovanie</h2></div>
<div class="region"><div class="contents">
<p class="para">IP smerovanie alebo tiež IP routing predstavuje spôsob určenia alebo nájdenia cesty v sieti TCP/IP, po ktorej sa budú posielať dáta. Smerovanie používa na posielanie dátových paketov od odosielateľa k príjemcovi <span class="em emphasis">smerovacie tabuľky</span>. Odoslanie pritom často prebieha cez mnoho medzičlánkov, ktorým hovoríme <span class="em emphasis">smerovače</span> alebo tiež <span class="em emphasis">routre</span>. Existujú dva hlavné spôsoby smerovania: <span class="em emphasis">statické smerovanie</span> a <span class="em emphasis">dynamické smerovanie</span>.</p>
<p class="para">Statické smerovanie spočíva v manuálnom pridávaní IP trás do smerovacej tabuľky. Najčastejšie sa to vykonáva pomocou príkazu <span class="app application">route</span>. Statické smerovanie má oproti dynamickému smerovaniu mnoho výhod, ako napríklad jednoduchú implementáciu v malých sieťach, predvídateľnosť (smerovacia tabuľka sa určí vopred a preto je cesta rovnaká pri každom jej použití) a nízka záťaž ostatných smerovačov a sieťových prepojení vďaka tomu, že sa nepoužíva protokol dynamického smerovania. Statické smerovanie má však aj svoje nevýhody. Statické smerovanie je obmedzené na malé siete a nie je dobre prispôsobiteľné. Statické smerovanie sa tiež nedokáže prispôsobiť výpadkom pripojení kvôli nemennej povahe smerovania.</p>
<p class="para">Dynamické smerovanie sa používa vo veľkých sieťach s viacerými možnými spôsobmi pripojenia od zdroja k cieľu, pričom využíva špeciálne protokoly smerovania, ako napríklad Router Information Protocol (RIP), ktorý automatický robí zmeny v smerovacej tabuľke, aby umožnil dynamické smerovanie. Dynamické smerovanie má niekoľko výhod oproti statickému smerovaniu, akými sú napríklad vynikajúca prispôsobiteľnosť a schopnosť prispôsobiť sa výpadkom pripojenia v sieti. Taktiež nevyžaduje toľko ručného nastavovania smerovacích tabuliek, pretože smerovače sa navzájom informujú o svojej prítomnosti a dostupných trasách. Táto vlastnosť tiež vylučuje chyby spôsobené ľudským faktorom. Dynamické smerovanie nie je dokonalé, pretože má aj určité nevýhody akými sú vyššia zložitosť a záťaž pri komunikácii smerovačov, čo následne pocítia koncoví používatelia zníženou šírkou prenosového pásma.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="tcp-and-udp"><div class="inner">
<div class="hgroup"><h2 class="title">TCP a UDP</h2></div>
<div class="region"><div class="contents">
<p class="para">TCP je protokol, poskytujúci korekciu chýb a garanciu doručenia dát, čo je známe ako riadenie toku alebo <span class="em emphasis">flow control</span>. Riadenie toku určuje, kedy je potrebné prerušiť tok dát a vyžiadať o znovuzaslanie dátových paketov kvôli problémom, akými sú napríklad tzv. kolízie, a tak zabezpečiť správne doručenie údajov. TCP sa využíva najmä na výmenu dôležitých informácii, akými sú napríklad databázové transakcie.</p>
<p class="para">UDP protokol (User Datagram Protocol) je naopak protokolom, ktorý sa len zrieka zaoberá prenosom dôležitých dát, pretože nepoužíva riadenie toku ani žiadnu ďalšiu metódu, aby zabezpečil spoľahlivý prenos dát. UDP sa najčastejšie používa všade tam, kde strata zopár paketov nie je žiadna katastrofa, ako napríklad pri tzv. audio a video streamingu, pri ktorom je neporovnateľne rýchlejší ako TCP, pretože sa nezaoberá opravou chýb a riadením toku.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="icmp"><div class="inner">
<div class="hgroup"><h2 class="title">ICMP</h2></div>
<div class="region"><div class="contents"><p class="para">ICMP protokol  (Internet Control Messaging Protocol) je rozšírením IP protokolu podľa definície Request For Comments (RFC) číslo 792 a umožňuje riadenie obsahu paketov, chýbových a informačných správ. Prokol ICMP je využívaný takými sieťovými aplikáciami, akou je napríklad nástroj <span class="app application">ping</span>, ktrorý vie overiť dostupnosť stanice. Príkladmi niektorých chybových hlásení užitočných pre obe komunikujúce strany, ktoré posiela ICMP, sú hlásenia <span class="em emphasis">Destination Unreachable</span> (cieľ nedostupný) a <span class="em emphasis">Time Exceeded</span> (vypršal čas na spojenie).</p></div></div>
</div></div>
<div class="sect2 sect" id="daemons"><div class="inner">
<div class="hgroup"><h2 class="title">Démoni</h2></div>
<div class="region"><div class="contents"><p class="para">Daemons alebo démoni sú špeciálne systémové aplikácie, ktoré sú zvyčajne spustené v pozadí a čakajú na požiadavky o služby, ktoré poskytujú z iných aplikácií. Mnoho démonov je sieťovo zameraných. Aj v Ubuntu je na pozadí spustených veľa démonov, ktoré poskytujú sieťovo zamerané služby. Medzi nich patria aj démoni: <span class="em emphasis">Hyper Text Transport Protocol Daemon</span> (httpd), ktorý poskytuje služby webového servera, <span class="em emphasis">Secure SHell Daemon</span> (sshd), ktorý poskytuje rozhranie pre vzialenú správu a funkcie na prenos súborov a <span class="em emphasis">Internet Message Access Protocol Daemon</span> (imapd), ktorý poskytuje e-mailové služby.</p></div></div>
</div></div>
<div class="sect2 sect" id="tcpip-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para">
              There are man pages for <a href="http://manpages.ubuntu.com/manpages/trusty/en/man7/tcp.7.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/en/man7/tcp.7.html">TCP</a> and
              <a href="http://manpages.ubuntu.com/manpages/trusty/man7/ip.7.html" class="ulink" title="http://manpages.ubuntu.com/manpages/trusty/man7/ip.7.html">IP</a> that contain more useful information.
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">Preštudujte si tiež <a href="http://www.redbooks.ibm.com/abstracts/gg243376.html" class="ulink" title="http://www.redbooks.ibm.com/abstracts/gg243376.html">TCP/IP Tutorial and Technical Overview</a> IBM Redbook.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Ďalší zdroj je O'Reillyho <a href="http://oreilly.com/catalog/9780596002978/" class="ulink" title="http://oreilly.com/catalog/9780596002978/">TCP/IP Network Administration</a>.</p>
            </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="network-configuration.html" title="Konfigurácia siete">Predchádzajúca</a><a class="nextlinks-next" href="dhcp.html" title="Protokol dynamického nastavenia hostiteľov (DHCP)">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
