<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Jabber server</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><script>
      function englishPageVersion() {
        var href = window.location.href;
        if (href.slice(-1) == "/") {
                window.location = "index.html.en";
        } else {
                window.location = href.replace(/\.html.*/, ".html.en");
        }
         return false;
      }
      function browserPreferredLanguage() {
        var href = window.location.href;
        if (href.slice(-1) == "/") {
                window.location = href;
        } else {
                window.location = href.replace(/\.html.*/, ".html");
        }
        return false;
      }
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../18.04" class="trail">Ubuntu 18.04</a> » <a class="trail" href="index.html.sk" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="chat-servers.html.sk" title="Aplikácie na chatovanie">Aplikácie na chatovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="irc-server.html.sk" title="IRC server">Predchádzajúca</a><a class="nextlinks-next" href="version-control-system.html.sk" title="Systém správy verzií">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Jabber server</h1></div>
<div class="region">
<div class="contents"><p class="para"><span class="em emphasis">Jabber</span> je populárny protokol na odosielanie okamžitých správ (instant message) založený na otvorenom štandarde XMPP, ktorý používa mnoho populárnych aplikácií. Táto časť hovorí o tom, ako nastaviť <span class="em emphasis">Jabberd 2</span> v lokálnej sieti LAN. Toto nastavenie sa však dá prispôsobiť aj tak, aby poskytovaná služba fungovala aj cez Internet.</p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="jabberd2-server.html.sk#jabberd2-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="jabberd2-server.html.sk#jabberd2-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="jabberd2-server.html.sk#jabberd2-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="jabberd2-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Server <span class="app application">jabberd2</span> nainštalujeme zadaní príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install jabberd2</span>
</pre></div>
</div></div>
</div></div>
<div class="sect2 sect" id="jabberd2-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">
    A couple of XML configuration files will be used to configure <span class="app application">jabberd2</span> for 
    <span class="em emphasis">Berkeley DB</span> user authentication.  This is a very simple form of authentication.  However,
    <span class="app application">jabberd2</span> can be configured to use LDAP, MySQL, PostgreSQL, etc for 
    for user authentication.
    </p>
<p class="para">Najskôr otvoríme súbor <span class="file filename">/etc/jabberd2/sm.xml</span> a zmeníme riadok:</p>
<div class="code"><pre class="contents ">  &lt;id&gt;jabber.nieco.sk&lt;/id&gt;
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
      <p class="para">Miesto adresy <span class="em emphasis">jabber.nieco.sk</span> zadajte mennú alebo číselnú adresu vášho servera.</p>
    </div></div></div></div>
<p class="para">Teraz v časti &lt;storage&gt; zmeníme hodnotu &lt;driver&gt; na:</p>
<div class="code"><pre class="contents ">   &lt;driver&gt;db&lt;/driver&gt;
</pre></div>
<p class="para">Potom otvoríme súbor <span class="file filename">/etc/jabberd2/c2s.xml</span> a v časti <span class="em emphasis">&lt;local&gt;</span> zmeníme hodnotu:</p>
<div class="code"><pre class="contents ">    &lt;id&gt;jabber.nieco.sk&lt;/id&gt;
</pre></div>
<p class="para">a v časti &lt;authreg&gt; upravíme hodnotu &lt;module&gt; na:</p>
<div class="code"><pre class="contents ">    &lt;module&gt;db&lt;/module&gt;
</pre></div>
<p class="para">Nakoniec reštartujeme <span class="app application">jabberd2</span> aby sa prejavili nové nastavenia:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart jabberd2.service</span>
</pre></div>
<p class="para">Teraz by sa malo dať pripojiť na server pomocou Jabber klienta ako napríklad <span class="app application">Pidgin</span>.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
    <p class="para">Výhoda použitia Berkeley DB pre dáta používateľov je tá, že po nastavení nie je potrebná žiadna ďalšia údržba. Ak potrebujete mať väčšiu kontrolu nad kontami používateľov, odporúčame použiť iný spôsob autentifikácie.</p>
  </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="jabberd2-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
        <p class="para">Viac informácií o konfigurácii servera <span class="app application">Jabberd2</span> sa nachádza na stránke <a href="http://codex.xiaoka.com/wiki/jabberd2:start" class="ulink" title="http://codex.xiaoka.com/wiki/jabberd2:start">Jabberd2 Web Site</a>.</p>
      </li>
<li class="list itemizedlist">
        <p class="para">
        For more authentication options see the <a href="http://www.jabberdoc.org/" class="ulink" title="http://www.jabberdoc.org/">Jabberd2 Install Guide</a>.
        </p>
      </li>
<li class="list itemizedlist">
        <p class="para">Viac informácií sa nachádza aj na stránke <a href="https://help.ubuntu.com/community/SettingUpJabberServer" class="ulink" title="https://help.ubuntu.com/community/SettingUpJabberServer">Setting Up Jabber Server Ubuntu Wiki</a>.</p>
      </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="irc-server.html.sk" title="IRC server">Predchádzajúca</a><a class="nextlinks-next" href="version-control-system.html.sk" title="Systém správy verzií">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer">
<p style="padding-bottom: 0.4em">You can choose the <b>displayed language</b> by adding a language suffix to the web address
          so it ends with e.g. <tt>.html.en</tt> or <tt>.html.de</tt>.<br>
          If the web address has no language suffix, the preferred language specified in your web browser's settings is used. For your convenience:<br>
          [ <a title="English page version" href="#" onClick="englishPageVersion();">Change to English Language</a> | 
          <a title="Language selected by browser" href="#" onClick="browserPreferredLanguage()">Change to Browser's Preferred Language</a> ]</p>
<p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p>
</div>
</div>
</body>
</html>
