<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Úvod</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><script>
      function englishPageVersion() {
        var href = window.location.href;
        if (href.slice(-1) == "/") {
                window.location = "index.html.en";
        } else {
                window.location = href.replace(/\.html.*/, ".html.en");
        }
         return false;
      }
      function browserPreferredLanguage() {
        var href = window.location.href;
        if (href.slice(-1) == "/") {
                window.location = href;
        } else {
                window.location = href.replace(/\.html.*/, ".html");
        }
        return false;
      }
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../18.04" class="trail">Ubuntu 18.04</a> » <a class="trail" href="index.html.sk" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="samba.html.sk" title="Samba">Samba</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba.html.sk" title="Samba">Predchádzajúca</a><a class="nextlinks-next" href="samba-fileserver.html.sk" title="File Server">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Úvod</h1></div>
<div class="region"><div class="contents">
<p class="para">Pre úspešné prepojenie s klientami Windows, Ubuntu zahrňuje poskytovanie a integrovanie služieb, ktoré sú spoločné s rozhraním Windows. Služby na zdieľanie dát a informácií o počítačoch a používateľoch pripojených do siete môžeme rozdeliť do troch hlavných kategórií podľa funkcionality:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
        <p class="para"><span class="em em-bold emphasis">Súborové a tlačové služby</span>. Tieto služby využívajú protokol Server Message Block (SMB) na zdieľanie súborov, priečinkov, diskových zväzkov a tlačiarní v sieti.</p>
      </li>
<li class="list itemizedlist">
        <p class="para"><span class="em em-bold emphasis">Adresárové služby</span>. Zdieľanie dôležitých informácii o počítačoch a používateľoch siete umožňujú technológie Lightweight Directory Access Protocol (LDAP) a <span class="trademark">Microsoft Active Directory®</span>.</p>
      </li>
<li class="list itemizedlist">
        <p class="para"><span class="em em-bold emphasis">Autentifikácia a prístup</span>. Stanovenie identity počítača a používateľov v sieti a určenie, či je počítač alebo používateľ autorizovaný, sa používajú také princípy a technológie, akými sú práva súborového systému, skupinová politika a autentifikačná služba Kerberos.</p>
      </li>
</ul></div>
<p class="para">Našťastie systém Ubuntu môže všetky tieto služby poskytnúť klientom so systémom Windows a zdielať s nimi sieťové zdroje. Jednou z hlavných častí softvéru, ktorý poskytuje systém Ubuntu pre sieť Windows, je systém Samba - balík serverových aplikácií SMB a nástrojov.</p>
<p class="para">Táto časť príručky systému <span class="phrase">Ubuntu</span> Server hovorí o niektorých najčastejších spôsoboch využitia systému Samba, o inštalácii a konfigurácii potrebných balíkov. Podrobnejšiu dokumentáciu a informácie o systéme Samba nájdeme na stránke <a href="http://www.samba.org" class="ulink" title="http://www.samba.org">Samba website</a>.</p>
</div></div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba.html.sk" title="Samba">Predchádzajúca</a><a class="nextlinks-next" href="samba-fileserver.html.sk" title="File Server">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer">
<p style="padding-bottom: 0.4em">You can choose the <b>displayed language</b> by adding a language suffix to the web address
          so it ends with e.g. <tt>.html.en</tt> or <tt>.html.de</tt>.<br>
          If the web address has no language suffix, the preferred language specified in your web browser's settings is used. For your convenience:<br>
          [ <a title="English page version" href="#" onClick="englishPageVersion();">Change to English Language</a> | 
          <a title="Language selected by browser" href="#" onClick="browserPreferredLanguage()">Change to Browser's Preferred Language</a> ]</p>
<p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p>
</div>
</div>
</body>
</html>
