<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bezbariérový prístup</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Bezbariérový prístup</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Pracovné prostredie Unity obsahuje asistenčné technológie podporujúce používateľov s rôznymi poruchami a s osobitnými potrebami, a na komunikáciu s bežnými asistenčnými zariadeniami. Mnohé funkcie zjednodušenia ovládania sú prístupné z časti <span class="gui">Univerzálny prístup</span> v <span class="gui">Nastaveniach systému</span>.</p></div>
<div id="vision" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Zrakové postihnutie</span></h2></div>
<div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Slepota</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="a11y-braille.html" title="Prepis obrazovky do Braiilovho písma">Prepis obrazovky do Braiilovho písma</a><span class="desc"> — Použitie programu <span class="app">Orca</span> s obnoviteľným displejom pre Braillove písmo.</span>
</li>
<li class="links ">
<a href="a11y-screen-reader.html" title="Čítanie obrazovky hlasom">Čítanie obrazovky hlasom</a><span class="desc"> — Použitie programu <span class="app">Orca</span> na prečítanie používateľského rozhrania.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Slabozrakosť</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard-cursor-blink.html" title="Blikanie kurzora klávesnice">Blikanie kurzora klávesnice</a><span class="desc"> — Nastavenie rýchlosti blikania kurzora klávesnice.</span>
</li>
<li class="links ">
<a href="a11y-font-size.html" title="Zmena veľkosti textu na obrazovke">Zmena veľkosti textu na obrazovke</a><span class="desc"> — Použitie väčších písiem, aby sa dal text ľahšie čítať.</span>
</li>
<li class="links ">
<a href="a11y-contrast.html" title="Úprava kontrastu">Úprava kontrastu</a><span class="desc"> — Zvýraznenie okien a tlačidiel, aby boli lepšie vidieť.</span>
</li>
</ul></div>
</div></div>
</div></div>
</div></div>
<div id="sound" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Sluchové postihnutie</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><ul><li class="links ">
<a href="a11y-visualalert.html" title="Bilikanie obrazovky pri výstražných zvukoch">Bilikanie obrazovky pri výstražných zvukoch</a><span class="desc"> — Povolenie doplnenia prehrávania výstražných zvukov vizuálnou výstrahou formou blikania obrazovky alebo okna.</span>
</li></ul></div></div></div></div></div>
</div></div>
<div id="mobility" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pohybové postihnutie</span></h2></div>
<div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Pohyb myši</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse-mousekeys.html" title="Click and move mouse pointer using the keypad">Click and move mouse pointer using the keypad</a><span class="desc"> — Enable mouse keys to control the mouse with the keypad.</span>
</li>
<li class="links ">
<a href="mouse-sensitivity.html" title="Rýchlosť pohybu myši a touchpadu">Rýchlosť pohybu myši a touchpadu</a><span class="desc"> — Natavenie rýchlosti pohybu kurzora myši pri pohybe myši alebo touchpadu.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Klikanie a ťahanie</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse-doubleclick.html" title="Rýchlosť dvojitého kliknutia">Rýchlosť dvojitého kliknutia</a><span class="desc"> — Nastavenie tolerovanej prestávky medzi dvoma kliknutiami pri dvojitom kliknutí.</span>
</li>
<li class="links ">
<a href="a11y-right-click.html" title="Simulovanie kliknutia pravým tlačidlom">Simulovanie kliknutia pravým tlačidlom</a><span class="desc"> — Zapnutie simulovania kliknutia pravým tlačidlom podržaním ľavého tlačidla.</span>
</li>
<li class="links ">
<a href="a11y-dwellclick.html" title="Simulovanie kliknutia zotrvaním">Simulovanie kliknutia zotrvaním</a><span class="desc"> — Funkcia kliknutie zotrvaním umožňuje kliknúť podržaním kurzora myši na rovnakom mieste.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Používanie klávesnice</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard-nav.html" title="Keyboard navigation">Keyboard navigation</a><span class="desc"> — Use applications and the desktop without a mouse.</span>
</li>
<li class="links ">
<a href="keyboard-repeat-keys.html" title="Nastavenie opakovania klávesy pri jej držaní">Nastavenie opakovania klávesy pri jej držaní</a><span class="desc"> — Vypnutie opakovania písmen pri podržaní klávesu, alebo zmena prestávky a rýchlosti opakovania.</span>
</li>
<li class="links ">
<a href="keyboard-osk.html" title="Use a screen keyboard">Use a screen keyboard</a><span class="desc"> — 
     Use an on-screen keyboard to enter text by clicking buttons with the mouse.
    </span>
</li>
<li class="links ">
<a href="a11y-stickykeys.html" title="Zapnutie lepkavých kláves">Zapnutie lepkavých kláves</a><span class="desc"> — Nastavenie písania klávesových skratiek po jednej klávese namiesto súčasného držania viacerých kláves naraz.</span>
</li>
<li class="links ">
<a href="a11y-slowkeys.html" title="Zapnutie pomalých kláves">Zapnutie pomalých kláves</a><span class="desc"> — Nastavenie prestávky medzi držaním klávesu a jeho zobrazením na obrazovke.</span>
</li>
<li class="links ">
<a href="a11y-bouncekeys.html" title="Zapnutie poskakujúcich kláves">Zapnutie poskakujúcich kláves</a><span class="desc"> — Ignorovanie rýchlo opakujúcich sa stlačení rovnakého klávesu.</span>
</li>
</ul></div>
</div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Príručka pre Ubuntu desktop">Príručka pre Ubuntu desktop</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
