<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>O ovom vodiču</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="more-help.html" title="Još pomoći">Još pomoći</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">O ovom vodiču</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ovaj vodić vam omogućava razgledanje Ubuntu značajki radne površine, odgovara na vaša pitanja koja su vezana za računare i daje vam savjete kako da koristite vaš računar efikasnije.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Vodič je podijeljen na manje teme, orijentisane ka izvršavanju zadataka, a ne na poglavlja. Ovo znači da ne morate tražiti odgovor na vaše pitanje po cijelom priručniku.</p></li>
<li class="list"><p class="p">Srodni predmeti su povezani zajedno. "Pogledaj takođe" linkove na dnu nekih stranica da vas odvedu do srodnih tema.</p></li>
<li class="list"><p class="p">Kutija za unos teksta na vrhu ovog vodiča se ponaša kao <span class="em">pretraživačka traka</span>, i relevantni rezultati će se pojaviti ispod nje čim počnete s kucanjem. Lijevi klik na bilo koji rezultat otvara njegovu stranicu.</p></li>
<li class="list"><p class="p">Vodič se konstantno upotpunjava. Iako se trudimo da vam obezbijedimo široku kolekciju korisnih informacija, znamo da ne možemo odgovoriti na sva vaša pitanja ovdje. Ali, ipak ćemo dodavati još informacija da bi vodič bio od veće pomoći.</p></li>
</ul></div></div></div>
<p class="p">Hvala vam na vremenu koje ste odvojili da pročitate <span class="em"> Ubuntu Desktop Vodič</span>.</p>
<p class="p">-- Ubuntu tim za dokumentaciju</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="more-help.html" title="Još pomoći">Još pomoći</a><span class="desc"> — <span class="link"><a href="about-this-guide.html" title="O ovom vodiču">Savjeti za korištenje ovog priručnika</a></span>, <span class="link"><a href="get-involved.html" title="Učestvujte u poboljšanju ovog uputstva">pomozite da poboljšamo ovaj priručnik </a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="unity-introduction.html" title="Dobrodošli u Ubuntu">Dobrodošli u Ubuntu</a><span class="desc"> — Vizualni uvod u Unity desktop.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
