<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>
		Remove an account
	</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="accounts.html" title="Online účty">Online účty</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">
		Remove an account
	</span></h1></div>
<div class="region">
<div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikneme na ikonu v tvare vypínača vpravo na <span class="gui">hornej lište</span> a zvolíme <span class="gui">Nastavenia systému</span>.</p></li>
<li class="steps"><p class="p">Select <span class="gui">Online Accounts</span>.
			</p></li>
<li class="steps"><p class="p">
        From the left windowpane, select the account you wish to remove.
      </p></li>
<li class="steps">
<p class="p">
        Click the <span class="gui">Remove Account</span> button in the lower-right portion of 
        the window.
			</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">
      Removing the selection from <span class="app">Online Accounts</span> in no way affects
			the account from your service provider.
    </p></div></div></div></div>
</li>
<li class="steps"><p class="p">Klikneme na <span class="gui">Odstrániť</span>.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">
      Instead of deleting the account completely, you can <span class="link"><a href="accounts-disable-service.html" title="Disable account services">restrict the service</a></span> from being
			accessed by your desktop.
    </p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="accounts.html" title="Online účty">Online účty</a><span class="desc"> — 
	    <span class="link"><a href="accounts-add.html" title="Pridať účet">Add accounts, </a></span>
	    <span class="link"><a href="accounts-remove.html" title="Remove an account">Remove accounts, </a></span>
	    <span class="link"><a href="accounts-disable-service.html" title="Disable account services">Disable services</a></span>
		</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="accounts-disable-service.html" title="Disable account services">
    Disable account services
  </a><span class="desc"> — 
      Some online accounts allow you to use multiple services (like calendar
			and email). You can control which of these services can be used by
			local applications.
    </span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
