<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dodaj korisnički nalog</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="accounts.html" title="Online računi">Online računi</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dodaj korisnički nalog</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Dodavanje korisničkog računa će vam pomoći da povežete korisničke račune s interneta s vašom Ubuntu radnom površinom. Dakle, vaša pošta, aplikacije za dopisivanje i slične aplikacije će biti podešene za vas.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Izaberi <span class="gui">Internet Računi</span>.</p></li>
<li class="steps">
<p class="p">Izaberi <span class="gui">Tip Računa</span> sa desne strane prozora.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako želite uspostaviti više korisničkih računa, možete ponoviti ovaj proces kasnije.</p></div></div></div></div>
</li>
<li class="steps"><p class="p">Otvoriti će vam se mali mrežni korisnički interfejs gdje možete unijeti podatke vašeg internet računa. Na primjer, ako podešavate Google račun, unesite vaše Google korisničko ime, lozinku i prijavite se.</p></li>
<li class="steps"><p class="p">Ako ste unijeli vaše podatke tačno, bit će zatraženo od vas da prihvatite uslove. Izaberite <span class="gui">Prihvatam</span> da nastavite. Nakon što ste prihvatili, Ubuntu treba dozvolu da pristupi vašem računu. Da dozvolite pristup, kliknite na <span class="gui">Dozvoli prisput</span> opciju. Kada bude zatrazeno, unesite lozinku za trenutni korisnički račun.</p></li>
<li class="steps"><p class="p">Sada možete odabrati aplikacije koje želite povezati sa vašim korisničkim računom. Na primjer, ako želite koristiti korisnički račun s interneta za chat, ali ne za kalendar, isključite opciju za <span class="gui">kalendar</span></p></li>
</ol></div></div></div>
<p class="p">Nakon što ste dodali korisničke račune, svaka aplikacija koju ste odabrali će automatski koristiti te postavke kada se povežete na svoj račun.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Iz sigurnosnih razloga, Ubuntu neće pohraniti vaš password na računar. Umjesto toga, pohranjuje znak koji pružaju internetske usluge. Ako želite upotpunsti ukinuti vezu između vašeg desktopa i online servisa, <span class="link"><a href="accounts-remove.html" title="Izbrišite račun">ukinite ga</a></span></p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="accounts.html" title="Online računi">Online računi</a><span class="desc"> — <span class="link"><a href="accounts-add.html" title="Dodaj korisnički nalog">Dodaj račune, </a></span> <span class="link"><a href="accounts-remove.html" title="Izbrišite račun">Ukloni račune, </a></span> <span class="link"><a href="accounts-disable-service.html" title="Isključi korisničke usluge">Isključi servise</a></span></span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
