<!DOCTYPE html>
<!DOCTYPE html>
<html lang=kk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>
    Use Synaptic for more advanced software management
  </title>
<link rel="stylesheet" type="text/css" href="kk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Guide"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Help"></span></span> Ubuntu Desktop Guide</a> » <a class="trail" href="addremove.html" title="Add &amp; remove software">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">
    Use Synaptic for more advanced software management
  </span></h1></div>
<div class="region">
<div class="contents">
<p class="p">
    <span class="app">Synaptic Package Manager</span> is more powerful and can do some 
    software management tasks which <span class="app">Ubuntu Software</span> can't. 
    Synaptic's interface is more complicated and doesn't support newer
    <span class="app">Ubuntu Software</span> features like ratings and reviews and therefore
    isn't recommended for use by those new to Ubuntu.
  </p>
<p class="p">
    Synaptic isn't installed by default, but you can <span class="link"><a href="https://apps.ubuntu.com/cat/applications/synaptic" title="https://apps.ubuntu.com/cat/applications/synaptic">install</a></span> it from the Ubuntu package archive.
  </p>
</div>
<div id="install-software-with-synaptic" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">
      Install software with Synaptic
    </span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">
          Open Synaptic from the <span class="gui">Dash</span> or the <span class="gui">Launcher</span>. You 
          will need to enter your password in the <span class="gui">Authenticate</span> window.
        </p></li>
<li class="steps"><p class="p">
          Click <span class="gui">Search</span> to search for an application, or click 
          <span class="gui">Sections</span> and look through the categories to find one.
        </p></li>
<li class="steps"><p class="p">
          Right-click the application that you want to install and select 
          <span class="gui">Mark for Installation</span>.
        </p></li>
<li class="steps"><p class="p">
          If you are asked to mark additional changes, click <span class="gui">Mark</span>.
        </p></li>
<li class="steps"><p class="p">
          Select any other applications that you would like to install.
        </p></li>
<li class="steps"><p class="p">
          Click <span class="gui">Apply</span>, and then click <span class="gui">Apply</span> in the window 
          that appears. The applications that you chose will be downloaded and 
          installed.
        </p></li>
</ol></div></div></div>
<p class="p">
      For more information about using <span class="app">Synaptic</span>, consult the <span class="link"><a href="https://help.ubuntu.com/community/SynapticHowto" title="https://help.ubuntu.com/community/SynapticHowto">Synaptic How To</a></span>.
    </p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Add &amp; remove software">Add &amp; remove software</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Install additional software">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Remove an application">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Add additional software repositories">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove-install.html" title="Install additional software">
    Install additional software
  </a><span class="desc"> — 
      Use <span class="app">Ubuntu Software</span> to add programs and make Ubuntu more 
      useful.
    </span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
