<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Inštalácia ďalšieho softvéru</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Inštalácia ďalšieho softvéru</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Vývojový tím systému Ubuntu vybral základnú sadu aplikácií, ktoré považovali za veľmi užitočné pre najbežnejšie úlohy. My si však môžeme nainštalovať aj ďalšie aplikácie, ktoré potrebujeme.</p>
<p class="p">Keď chceme nainštalovať ďalší softvér, budeme postupovať takto:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Pripojíme sa na internet pomocou <span class="link"><a href="net-wireless-connect.html" title="Pripojenie k bezdrôtovej sieti">bezdrôtového</a></span> alebo <span class="link"><a href="net-wired-connect.html" title="Pripojenie k drôtovej (Ethernet) sieti">drôtového pripojenia</a></span>.</p></li>
<li class="steps"><p class="p">
        Click the <span class="app">Ubuntu Software</span> icon in the <span class="gui">Launcher</span>, or search
        for <span class="input">Software</span> in the search bar of the <span class="gui">Dash</span>.
      </p></li>
<li class="steps"><p class="p">
        When <span class="app">Ubuntu Software</span> launches, search for an application, or select 
        a category and find an application from the list.
      </p></li>
<li class="steps"><p class="p">Vyberieme aplikáciu, ktorú chceme a klikneme na tlačidlo <span class="gui">Nainštalovať</span>.</p></li>
<li class="steps"><p class="p">Systém nás vyzve aby sme zadali heslo. Po jeho zadaní sa spustí inštalácia.</p></li>
<li class="steps"><p class="p">Inštalácia zvyčajne skončí rýchlo, no môže trvať dlhšie, ak máme pomalé pripojenie do internetu.</p></li>
<li class="steps"><p class="p">
        A shortcut to your new app will be added to the Launcher. To disable 
        this feature, uncheck <span class="guiseq"><span class="gui">View</span> ▸ <span class="gui">New Applications in 
        Launcher</span></span>.
      </p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Pridávanie a odstraňovanie softvéru</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Odstránenie aplikácie">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="prefs-language-install.html" title="Install languages">Install languages</a><span class="desc"> — Install more translations and related language support packages.</span>
</li>
<li class="links ">
<a href="addremove-remove.html" title="Odstránenie aplikácie">Odstránenie aplikácie</a><span class="desc"> — Odstránenie softvéru, ktorý už nepoužívame.</span>
</li>
<li class="links ">
<a href="addremove-install-synaptic.html" title="Používanie programu Synaptic na pokročilejšiu správu softvéru">Používanie programu Synaptic na pokročilejšiu správu softvéru</a><span class="desc"> — 
      Synaptic is a powerful but complicated software management alternative to 
      <span class="app">Ubuntu Software</span>.
    </span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
