<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pridanie osobného úložiska (PPA)</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pridanie osobného úložiska (PPA)</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="em">Osobné archívy balíkov (PPA)</span> sú zdroje softvéru navrhnuté pre používateľov Ubuntu a dajú sa jednoduchšie nainštalovať ako iné zdroje softvéru.</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
<p class="p">Pridávať je vhodné iba tie zdroje, ktorým dôverujeme!</p>
<p class="p">Bezpečnosť zdrojov softvéru od tretích strán nie je preverená vývojármi softvéru ani komunitou a použitie takýchto zdrojov môže byť pre počítač škodlivé.</p>
</div></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Inštalácia zdroja PPA</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Na stránke s prehľadom PPA nájdeme nadpis <span class="gui">Adding this PPA to your system</span>. Pod ním sa nachádza informácia o umiestnení PPA, ktorá má nasledujúci tvar: <span class="code">ppa:mozillateam/firefox-next</span>.</p></li>
<li class="steps"><p class="p">
        Click the <span class="app">Ubuntu Software</span> icon in the <span class="gui">Launcher</span>, or search
        for <span class="input">Software</span> in the search bar of the <span class="gui">Dash</span>.
      </p></li>
<li class="steps"><p class="p">
        When <span class="app">Ubuntu Software</span> launches, click <span class="gui">Software &amp; Updates</span>
      </p></li>
<li class="steps"><p class="p">Prepneme sa na kartu <span class="gui">Ďalší softvér</span>.</p></li>
<li class="steps"><p class="p">Klikneme na tlačidlo <span class="gui">Pridať</span> a do poľa Riadok APT zadáme adresu v tvare <span class="code">ppa: adresa</span></p></li>
<li class="steps"><p class="p">Klikneme na tlačidlo <span class="gui">Pridať zdroj</span>. Do okna Overenie totožnosti zadáme svoje heslo.</p></li>
<li class="steps"><p class="p">
        Close the <span class="app">Software &amp; Updates</span> window. <span class="app">Ubuntu Software</span> will then 
        check your software sources for new software.
      </p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Pridávanie a odstraňovanie softvéru</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Odstránenie aplikácie">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">Pridanie ďalších zdrojov softvéru</a><span class="desc"> — Pridanie ďalších zdrojov softvéru, ktoré je možné použiť na inštaláciu a aktualizáciu Ubuntu.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
