<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Gdje spremati Vaše sigurnosne kopije</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#backup" title="Rezervne kopije">Rezervne kopije</a> » <a class="trail" href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka">Sigurnosne kopije</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Gdje spremati Vaše sigurnosne kopije</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Trebate pohraniti sigurnosne kopije datoteka negdje odvojeno od računara - na vanjski tvrdi disk, na primjer. Na taj način, ako se računar pokvari, sigurnosna kopija će i dalje biti netaknuta. Za maksimalnu sigurnost, ne bi trebali držati sigurnosne kopije u istoj zgradi kao i vaš računar. Ako dođe do požara ili krađe, obje kopije podataka mogle bi biti izgubljene ako se drže zajedno.</p>
<p class="p">Bitno je da izaberete prikladan <span class="em">backup medij</span> takođe. Trebate da smjestite vaše sigurnosne kopije na uređaj koji ima dovoljan kapacitet da za sve vaše fajlove.</p>
<div class="list"><div class="inner">
<div class="title title-list"><h2><span class="title">Lokalna i udaljena pohrana opcija</span></h2></div>
<div class="region"><ul class="list compact">
<li class="list"><p class="p">USB memorije (mali kapacitet)</p></li>
<li class="list"><p class="p">CD ili DVD za pisanje (niski / srednji kapacitet)</p></li>
<li class="list"><p class="p">Vanjski tvrdi disk (obično visok kapacitet)</p></li>
<li class="list"><p class="p">Unutarnji disk (veliki kapacitet)</p></li>
<li class="list"><p class="p">Mrežno povezani disk (veliki kapacitet)</p></li>
<li class="list"><p class="p">Datoteka / rezervni server (veliki kapacitet)</p></li>
<li class="list"><p class="p">Internet servis za sigurnosne kopije (<span class="link"><a href="http://aws.amazon.com/s3/" title="http://aws.amazon.com/s3/">Amazon S3</a></span>, na primjer; kapacitet zavisi od cijene)</p></li>
</ul></div>
</div></div>
<p class="p">Neke opcije imaju dovoljan kapacitet da dozvole sigurnosnu kopiju svakog fajla na vašem sistemu, koja je poznata kao <span class="em">sigurnosna kopija cjelokupnog sistema</span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka">Napravite sigurnosne kopije važnih datoteka</a><span class="desc"> — Zašto, kako, gdje i na koji način do sigurnosnih kopija.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
