<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Gdje mogu pronaći podatke koje želim sigurnosno kopirati ?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#backup" title="Rezervne kopije">Rezervne kopije</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Gdje mogu pronaći podatke koje želim sigurnosno kopirati ?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ispod su navedene najčešće lokacije bitnih dokumenata i postavki za koje biste željeli kreirati backup.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">Lične datoteke (dokumenti, muzika, fotografije i video)</p>
<p class="p">Obično su smješteni u vašem home folderu (<span class="file">/home/your_name</span>). Mogu biti u podfolderima kao što su Desktop, Dokumenti, SLike, Muzika, i Video.</p>
<p class="p">Ako vaš backup medij ima dovoljno prostora (ako je u pitanju eksterni hard disk, na primjer), razmislite da napravite backup cijelog Početnog foldera. Možete saznati koliko prostora zauzima Početni folder pomoću <span class="app">Disk Usage Analyzer</span>.</p>
</li>
<li class="list">
<p class="p">Skrivene datoteke</p>
<p class="p">Bilo koja datoteka ili mapa čije ime počinje sa intervalom (.) je sakrivena prema zadanim postavkama. Da biste vidjeli sakrivene datoteke, kliknite <span class="guiseq"><span class="gui">Pregled</span> ▸ <span class="gui">Prikaži Sakrivene Datoteke</span></span> ili pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>H</kbd></span></span>. Možete ih kopirati na backup lokaciju kao i bilo koju drugu datoteku.</p>
</li>
<li class="list">
<p class="p">Lične postavke (desktop postavke, teme, i postavke programa)</p>
<p class="p">Većina aplikacija sprema svoje postavke u skriveni folder u Vašem Home folderu (vidite iznad za informacije o skrivenim datotekama)</p>
<p class="p">Većina postavki vaših programa će biti pohranjena u skrivene foldere <span class="file">.config</span>, <span class="file">.gconf</span>, <span class="file">.gnome2</span>, i <span class="file">.local</span> u vašem Home folderu.</p>
</li>
<li class="list">
<p class="p">Postavke cijelog sistema</p>
<p class="p">Postavke za važnih dijelova sistema ne pohranjuju se u vaša početna mapu. Postoji nekoliko mjesta gdje bi mogli biti pohranjeni, ali većina su pohranjeni u <span class="file"> /etc</span> mape. U principu, nećete morati kopije tih datoteka na kućnom računalu. Ako radite server, međutim, trebali biste sigurnosnu kopiju datoteke za usluge koje se izvode.</p>
</li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#backup" title="Rezervne kopije">Rezervne kopije</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
