<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pošalji datoteku Bluetooth uređaju</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="bluetooth.html" title="Bluetooth">Bluetooth</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="sharing.html" title="Dijeljenje">Dijeljenje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pošalji datoteku Bluetooth uređaju</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete slati datoteke povezanim Bluetooth uređajima, kao što su mobilni telefoni ili drugi računari. Neke vrste uređaja ne dozvoljavaju prenos datoteka ili određenih vrsta datoteka. Možete slati datoteke na jedan od tri načina:k oristeći Bluetooth ikonu na meni traci, iz prozora Bluetooth postavki, ili direktno iz menadžera datoteka.</p>
<p class="p">Za slanje datoteka direktno iz upravitelja datoteka, vidi <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Dijeli i prebaci datoteke</a></span>.</p>
<div class="note note-important" title="Važna"><div class="inner"><div class="region"><div class="contents"><p class="p">Prije nego što počnete, budite sigurni da je Bluetooth omogućen na vašem računaru. Vidi <span class="link"><a href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite">Uključite Bluetooth ili isključite</a></span>.</p></div></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Pošaljite datoteke koristeći Bluetooth ikonu</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na Bluetooth ikonu u menu traci i odaberite <span class="gui">Pošalji datoteke na uređaj</span>.</p></li>
<li class="steps">
<p class="p">Odaberite datoteku koju želite poslati i kliknite <span class="gui"> Odaberi </span>.</p>
<p class="p">Da biste poslali više od jednog fajla u folderu, zadržite <span class="key"><kbd>Ctrl</kbd></span> kao što odaberete svaki fajl.</p>
</li>
<li class="steps">
<p class="p">Odaberite uređaj na koji želite poslati datoteke i kliknite <span class="gui">Pošalji</span>.</p>
<p class="p">Lista uređaja će pokazati i<span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">uređaje na koje ste već spojeni</a></span> as well as <span class="link"><a href="bluetooth-visibility.html" title="Šta je vidljivost Bluetooth-a?">i vidljive uređaje</a></span> unutar dometa. Ukoliko se već niste spajali sa odabranim uređajem, tražit će da se spojite sa uređajem nakon što kliknete <span class="gui">Pošalji</span>. To će vjerovatno zahtjevati potvrdu na drugom urađaju.</p>
<p class="p">Ako ima mnogo uređaja, možete ograničiti listu samo na određene tipove uređaja koristeći <span class="gui">Tip uređaja</span> padajući meni.</p>
</li>
<li class="steps"><p class="p">Vlasnik uređaja koji prima signal obično mora pritisnuti dugme za prihvaćanje datoteke. Nakon što vlasnik prihvati ili odbije, rezultat prijenosa datoteke bit će prikazan na ekranu.</p></li>
</ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Pošalji datoteke iz Bloetooth postavki</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na Bluetooth ikonu na  izborniku i odaberite  <span class="gui">Postavke Bluetooth-a</span>.</p></li>
<li class="steps"><p class="p">Odaberite uređaj da pošaljete datoteku sa liste na lijevoj strani. Na listi su samo prikazani uređaji sa kojima ste već bili spojeni. Vidi <span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">Povežite vaš računar sa Bluetooth uređajem</a></span>.</p></li>
<li class="steps"><p class="p">U informacijama o uređaju na desnoj strani, kliknite <span class="gui">Pošalji Datoteke</span>.</p></li>
<li class="steps">
<p class="p">Odaberite datoteku koju želite poslati i kliknite <span class="gui"> Odaberi </span>.</p>
<p class="p">Da biste poslali više od jednog fajla u folderu, zadržite <span class="key"><kbd>Ctrl</kbd></span> kao što odaberete svaki fajl.</p>
</li>
<li class="steps"><p class="p">Vlasnik uređaja koji prima signal obično mora pritisnuti dugme za prihvaćanje datoteke. Nakon što vlasnik prihvati ili odbije, rezultat prijenosa datoteke bit će prikazan na ekranu.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="bluetooth.html" title="Bluetooth">Bluetooth</a><span class="desc"> — <span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">Spojiti</a></span>, <span class="link"><a href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju"> slanje datoteka</a></span>, <span class="link"><a href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite"> uključivanje i isključivanje</a></span>…</span>
</li>
<li class="links ">
<a href="sharing.html" title="Dijeljenje">Dijeljenje</a><span class="desc"> — 
      <span class="link"><a href="sharing-desktop.html" title="Dijelite vaš desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Share files</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files-share.html" title="Dijeli i prebaci datoteke">Dijeli i prebaci datoteke</a><span class="desc"> — Prebacite datoteke svojim email kontaktima iz uređivača datoteka.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
