<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>I can't connect my Bluetooth device</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="bluetooth.html#problems" title="Problémy">Bluetooth problems</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">I can't connect my Bluetooth device</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">There are a number of reasons why you may not be able to connect to a 
Bluetooth device, such as a phone or headset.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">Zablokované alebo nedôveryhodné pripojenie</dt>
<dd class="terms"><p class="p">Some Bluetooth devices block connections by default, or require you to 
    change a setting to allow connections to be made. Make sure that your device 
    is set up to allow connections.</p></dd>
<dt class="terms">Nebol rozpoznaný Bluetooth hardvér</dt>
<dd class="terms"><p class="p">Your Bluetooth adapter/dongle may not have been recognized by the 
    computer. This could be because <span class="link"><a href="hardware-driver.html" title="Čo je to ovládač?">drivers</a></span> 
    for the adapter aren't installed. Some Bluetooth adapters aren't supported 
    on Linux, so you may not be able to get the right drivers for them. In this 
    case, you will probably have to get a different Bluetooth adapter.</p></dd>
<dt class="terms">Adaptér nie je zapnutý</dt>
<dd class="terms"><p class="p">Make sure that your Bluetooth adapter is switched on. Click the 
          Bluetooth icon in the <span class="gui">menu bar</span> and check that it's not 
          <span class="link"><a href="bluetooth-turn-on-off.html" title="Zapnutie alebo vypnutie bluetooth">disabled</a></span>.</p></dd>
<dt class="terms">Bluetooth zariadenie je vypnuté</dt>
<dd class="terms"><p class="p">Check that Bluetooth is turned on on the device you're trying to connect 
  to. For example, if you're trying to connect to a phone, make sure that it's 
  not in airplane mode.</p></dd>
<dt class="terms">Bluetooth adaptér nie je v počítači</dt>
<dd class="terms"><p class="p">Mnoho počítačov neobsahuje bluetooth adaptér. Ak chceme bluetooth používať, je potrebné si adaptér zakúpiť.</p></dd>
</dl></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="bluetooth.html#problems" title="Problémy">Bluetooth problems</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware-driver.html" title="Čo je to ovládač?">Čo je to ovládač?</a><span class="desc"> — Ovládač zariadenia je niečo, čo umožňuje počítaču používať zariadenie, ktoré k nemu pripojíme.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
