<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Upravljanje bojama</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Upravljanje bojama</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="color-assignprofiles.html" title="Kako dodijeliti profile na uređaje?"><span class="title">Kako dodijeliti profile na uređaje?</span><span class="linkdiv-dash"> — </span><span class="desc">Pogledajte u <span class="guiseq"><span class="gui"> Postavke sistema </span> ▸ <span class="gui"> Boja </span></span> za mogućnost da se to promijeni.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-whyimportant.html" title="Zašto je upravljanje bojama važno?"><span class="title">Zašto je upravljanje bojama važno?</span><span class="linkdiv-dash"> — </span><span class="desc">Upravljanje bojama je važno za dizajnera, fotografa i umjetnika.</span></a></div>
</div></div></div></div>
<div id="profiles" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Profili boja</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-gettingprofiles.html" title="Gdje mogu dobiti profile boja?"><span class="title">Gdje mogu dobiti profile boja?</span><span class="linkdiv-dash"> — </span><span class="desc">Profili boja osiguravaju dobavljači od prodavača i možete ih generirati.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-howtoimport.html" title="Kako uvesti profile boja?"><span class="title">Kako uvesti profile boja?</span><span class="linkdiv-dash"> — </span><span class="desc">Profili boja mogu biti uvezeni njihovim otvaranjem.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-whatisspace.html" title="Šta je prostor boja?"><span class="title">Šta je prostor boja?</span><span class="linkdiv-dash"> — </span><span class="desc">Prostor boja je definiran raspon boja.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-whatisprofile.html" title="Što je profil boja?"><span class="title">Što je profil boja?</span><span class="linkdiv-dash"> — </span><span class="desc">Profil boja je jednostavna datoteka koja izražava prostor boja ili  odgovor uređaja.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-virtualdevice.html" title="Što je virtuelni upravljan bojama uređaj?"><span class="title">Što je virtuelni upravljan bojama uređaj?</span><span class="linkdiv-dash"> — </span><span class="desc">Virtuelni uređaj je uređaj upravljanja boja koji nije povezan sa računarom.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="calibration" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kalibracija</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-screen.html" title="Kako kalibrirati ekran?"><span class="title">Kako kalibrirati ekran?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibriranje ekrana je važno za prikaz tačne boje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-camera.html" title="Kako kalibrirati moj aparat?"><span class="title">Kako kalibrirati moj aparat?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibriranje vaše kamere je važno za hvatanje tačne boje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-printer.html" title="Kako kalibrirati moj printer?"><span class="title">Kako kalibrirati moj printer?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibriranje vašeg printera je važno za ispis tačne boje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-scanner.html" title="Kako kalibrirati moj skener?"><span class="title">Kako kalibrirati moj skener?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibriranje vašeg skenera je važno za hvatanje tačne boje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrationcharacterization.html" title="Koja je razlika između kalibracije i karakterizacije?"><span class="title">Koja je razlika između kalibracije i karakterizacije?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibracija i karakterizacija su potpuno različite stvari.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-calibrationdevices.html" title="Koji instrumenti za mjerenje boja su podržani?"><span class="title">Koji instrumenti za mjerenje boja su podržani?</span><span class="linkdiv-dash"> — </span><span class="desc">Mi podržavamo veliki broj kalibracijskih uređaja.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrationtargets.html" title="Koji odredišni tipovi su podržani?"><span class="title">Koji odredišni tipovi su podržani?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibracijski objekti su potrebni za rad  profiliranja skenera i kamere.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-canshareprofiles.html" title="Mogu li dijeliti moje profile boja?"><span class="title">Mogu li dijeliti moje profile boja?</span><span class="linkdiv-dash"> — </span><span class="desc">Dijeljenje boje profila nikada nije dobra ideja kao promjene hardware-a vremenom.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-why-calibrate.html" title="Zašto moram kalibraciju uraditi ja sama?"><span class="title">Zašto moram kalibraciju uraditi ja sama?</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibriranje je važno ako vam je stalo do boja koje ćete prikazati ili ispisati.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problemi</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-testing.html" title="Kako da testiram da li menadžment boja radi ispravno?"><span class="title">Kako da testiram da li menadžment boja radi ispravno?</span><span class="linkdiv-dash"> — </span><span class="desc">Testiranje menadžmenta boja nije teško, čak i obezbjeđujemo neke testne profile.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-notifications.html" title="Mogu li biti obaviješten kada mi je profil za boje netačan?"><span class="title">Mogu li biti obaviješten kada mi je profil za boje netačan?</span><span class="linkdiv-dash"> — </span><span class="desc">Možete biti obaviješteni ukoliko je vaš profil za boje star i netačan.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-missingvcgt.html" title="Nedostaje informacija za korekciju cijelih ekrana u boji?"><span class="title">Nedostaje informacija za korekciju cijelih ekrana u boji?</span><span class="linkdiv-dash"> — </span><span class="desc">Korekcija cijelih ekrana u boji mijenja sve boje ekrana na svim prozorima.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-notspecifiededid.html" title="Zašto zadanim monitor profilima ne ističe kalibracija?"><span class="title">Zašto zadanim monitor profilima ne ističe kalibracija?</span><span class="linkdiv-dash"> — </span><span class="desc">Zadani profili za monitor nemaju datum kalibracije.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a><span class="desc"> — <span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span>
</li>
<li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
