<!DOCTYPE html>
<!DOCTYPE html>
<html lang=tl>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Link and unlink contacts</title>
<link rel="stylesheet" type="text/css" href="tl.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Guide"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Help"></span></span> Ubuntu Desktop Guide</a> » <a class="trail" href="net.html" title="Networking, web, email &amp; chat">Networking, web, email &amp; chat</a> » <a class="trail" href="contacts.html" title="Contacts">Contacts</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Link and unlink contacts</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="link-contacts" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Link contacts</span></h2></div>
<div class="region"><div class="contents">
<p class="p">You can combine duplicate contacts from your local address book and online
  accounts into one <span class="app">Contacts</span> entry. This feature helps you keep your
  address book organized, with all details about one contact in one place.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Enable <span class="em">selection mode</span> by pressing the tick button above the
      contact list.</p></li>
<li class="steps"><p class="p">A checkbox will appear next to each contact. Tick the checkboxes next
      to the contacts that you want to merge.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Link</span> to link the selected
      contacts.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="unlink-contacts" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Unlink contacts</span></h2></div>
<div class="region"><div class="contents">
<p class="p">You may want to unlink contacts if you accidentally linked contacts which
  should not be linked.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Select the contact you wish to unlink from your list of contact.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Edit</span> in the top-right corner of
      <span class="app">Contacts</span>.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Linked Contacts</span>.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Remove</span> to unlink the entry from the
      contact.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Close</span> once you have finished unlinking
      the entries.</p></li>
<li class="steps"><p class="p">Press <span class="gui">Done</span> to finish editing the
      contact.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="contacts.html" title="Contacts">Contacts</a><span class="desc"> — Access your contacts.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
