<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Provjerite vaš tvrdi disk na probleme</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Provjerite vaš tvrdi disk na probleme</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="disk-status" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjeravam tvrdi disk</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Tvrdi diskovi imaju ugrađen alat za provjeravanje zdravlja zvan <span class="app"> SMART </span> (Self-Monitoring, Analysis, i Reporting Technology), koji stalno provjerava disk za potencijalne probleme. SMART vas, također, upozorava ako je disk na izmaku, pomažući vam da izbjegnete gubitak važnih podataka.</p>
<p class="p">Iako SMART pokreće automatski, također možete provjeriti zdravlje vašeg diska pokretanjem <span class="app"> Diskovi </span> aplikacije:</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h3><span class="title">Provjerite stanje vašeg diska koristeći aplikaciju Diskovi</span></h3></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite program <span class="app">Diskovi</span> iz crtice  <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">From the list to the left, select the disk whose information and status
  you want to check.</p></li>
<li class="steps"><p class="p"><span class="gui">Assessment</span> should say "Disk is OK".</p></li>
<li class="steps"><p class="p">Open the menu at the top right and select <span class="gui">SMART Data &amp;
  Self-Tests</span> to view more drive information, or to run a self-test.</p></li>
</ol></div>
</div></div>
</div></div>
</div></div>
<div id="disk-not-healthy" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Šta ako disk nije zdrav?</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Čak i ako <span class="gui"> SMART status </span> pokazuje da disk <span class="em"> nije </span> zdrav, ne mora postojati uzrok za uzbunu. Međutim, bolje biti pripremljen s <span class="link"><a href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka"> sigurnosnom kopijom </a></span> da biste spriječili gubitak podataka.</p>
<p class="p">Ako status kaže: "Pred neuspjeh", disk je još uvijek prilično zdrav ali znakovi trošenja su otkriveni, što znači da će možda propasti u skoroj budućnosti. Ako je vaš hard disk (ili računar) star nekoliko godina, vjerojatno ćete vidjeti ovu poruku na barem nekim zdravstenim pregledima. Trebate <span class="link"><a href="backup-how.html" title="Kako izvršiti sigurnosno kopiranje"> praviti sigurnosne kopije važnih datoteka redovito </a></span> i provjeriti stanje diska povremeno da vidite ako se pogorša.</p>
<p class="p">Ako se pogorša, trebali bi odnijeti računar / tvrdi disk stručnjaku za daljnju dijagnozu ili popravku.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a><span class="desc"> — <span class="link"><a href="disk-capacity.html" title="Provjerite koliko je slobodnog prostora u diksu ostalo">Kapacitet Diska</a></span>, <span class="link"><a href="disk-benchmark.html" title="Testirajte performanse vašeg tvrdog diska">performance</a></span>, <span class="link"><a href="disk-check.html" title="Provjerite vaš tvrdi disk na probleme">problemi</a></span>, <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama">količine i particije</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
