<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Obrišite sve s odstranjivog diska</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Obrišite sve s odstranjivog diska</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako imate odstranjivi disk, kao USB memorijski stik ili vanjski tvrdi disk, ponekad ćete poželjeti u potpunosti ukloniti sve svoje datoteke i foldere. To možete učiniti tako da <span class="em"> formatirate </span> disk - to briše sve datoteke na disku i ostavlja ga praznim.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Formatirajte odstranjivi disk</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite program <span class="app">Diskovi</span> iz crtice  <span class="gui">Dash</span>.</p></li>
<li class="steps">
<p class="p">Odaberite disk koji želite izbrisati iz <span class="gui">Uređaji za pohranivanje</span> popisa.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Provjerite jeste li odabrali odgovarajući disk! Ako odaberete krivi disk, sve datoteke na drugom disku će biti izbrisane!</p></div></div></div></div>
</li>
<li class="steps"><p class="p">U sekciji Volumen, kliknite <span class="gui"> Demontirajte Volumen </span>. Zatim kliknite <span class="gui"> Formatiraj Volumen </span>.</p></li>
<li class="steps">
<p class="p">Iz prozora koji iskoči, izaberite datotečni sistem <span class="gui"> Vrsta</span> za disk.</p>
<p class="p">Ako koristite disk na Windows i Mac OS računaru uz linux računare, odaberite <span class="gui"> FAT </span>. Ako ga samo koristite na Windows-u, <span class="gui"> NTFS </span> može biti bolji izbor. Kratak opis <span class="gui"> datotečnog tipa sistema </span> predstavit će se kao oznaka.</p>
</li>
<li class="steps"><p class="p">Dajte disku ime i kliknite <span class="gui"> Formatiranje </span> za početak brisanja diska.</p></li>
<li class="steps"><p class="p">Nakon što je formatiranje završeno, <span class="gui"> sigurno uklonite </span> disk. Sada bi trebao biti prazan i spreman za ponovno korištenje.</p></li>
</ol></div>
</div></div>
<div class="note note-warning" title="Upozoranje"><div class="inner">
<div class="title title-note"><h2><span class="title">Formatiranje diska ne briše skroz datoteke</span></h2></div>
<div class="region"><div class="contents"><p class="p">Formatiranje diska nije potpuno siguran način brisanja svih svojih podataka. Formatiran disk neće izgledati kao da ima datoteke na njemu, ali moguće je da posebni softver za povrat koji vraćs datoteke. Ako trebate sigurno izbrisati datoteke, morat ćete koristiti uslužni program iskoristivosti, kao što je<span class="app"> shred </span>.</p></div></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a><span class="desc"> — <span class="link"><a href="disk-capacity.html" title="Provjerite koliko je slobodnog prostora u diksu ostalo">Kapacitet Diska</a></span>, <span class="link"><a href="disk-benchmark.html" title="Testirajte performanse vašeg tvrdog diska">performance</a></span>, <span class="link"><a href="disk-check.html" title="Provjerite vaš tvrdi disk na probleme">problemi</a></span>, <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama">količine i particije</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
