<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kontrola zostávajúceho voľného miesta</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="disk.html" title="Disky a úložiská">Disky a úložiská</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kontrola zostávajúceho voľného miesta</span></h1></div>
<div class="region">
<div class="contents"><p class="p">You can check how much disk space is left with <span class="app">Disk Usage Analyzer</span>
 or <span class="app">System Monitor</span>.</p></div>
<div id="disk-usage-analyzer" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kontrola pomocou nástroja Analyzátor využitia disku</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Keď chceme skontrolovať voľné miesto a používanú kapacitu diskov, použijeme <span class="app">Analyzátor využitia disku</span>:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Open the <span class="app">Disk Usage Analyzer</span> application from the
 <span class="gui">Dash</span>. The window will display the <span class="gui">Total file system capacity</span>
  and <span class="gui">Total file system usage</span>.</p></li>
<li class="list"><p class="p">Click one of the toolbar buttons to choose to <span class="gui">Scan Home</span>,
   <span class="gui">Scan filesystem</span>, <span class="gui">Scan a folder</span>, or <span class="gui">Scan a remote
   folder</span>.</p></li>
</ul></div></div></div>
<p class="p">The information is displayed according to <span class="gui">Folder</span>, <span class="gui">Usage</span>,
  <span class="gui">Size</span> and <span class="gui">Contents</span>. See more details in
  <span class="link"><a href="https://help.gnome.org/users/baobab/stable/" title="https://help.gnome.org/users/baobab/stable/"><span class="app">Disk Usage Analyzer</span></a></span>.</p>
</div></div>
</div></div>
<div id="system-monitor" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kontrola pomocou nástroja Monitor systému</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Voľný diskový priestor  a využitie disku je možné skontrolovať aj pomocou nástroja <span class="app">Monitor systému</span>:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvoríme <span class="app">Monitor systému</span> pomocou <span class="gui">Prehľadnej ponuky</span>.</p></li>
<li class="steps"><p class="p">Select the <span class="gui">File Systems</span> tab to view the system's partitions and
  disk space usage.  The information is displayed according to <span class="gui">Total</span>,
  <span class="gui">Free</span>, <span class="gui">Available</span> and <span class="gui">Used</span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="disk-full" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Čo robiť keď jed disk plný</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ak je disk príliš plný mali by sme:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Odstrániť súbory, ktoré nie sú dôležité alebo tie, ktoré už nepotrebujeme.</p></li>
<li class="list"><p class="p">Vytvoriť si <span class="link"><a href="backup-why.html" title="Zálohovanie dôležitých súborov">zálohu</a></span> dôležitých súborov, ktoré momentálne nepotrebujeme a odstrániť ich z disku.</p></li>
</ul></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Disky a úložiská">Disky a úložiská</a><span class="desc"> — 
    <span class="link"><a href="disk-capacity.html" title="Kontrola zostávajúceho voľného miesta">Disk space</a></span>,
    <span class="link"><a href="disk-benchmark.html" title="Testovanie výkonu pevného disku">performance</a></span>,
    <span class="link"><a href="disk-check.html" title="Skontrolovanie chýb na disku">problems</a></span>,
    <span class="link"><a href="disk-partitions.html" title="Správa zväzkov a oddielov">volumes and partitions</a></span>…
  </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
