<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Vymazanie odpojiteľného disku</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="disk.html" title="Disky a úložiská">Disky a úložiská</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Vymazanie odpojiteľného disku</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ak máme odpojiteľný disk, USB kľúč alebo externý pevný disk, niekedy je potrebné vymazať na ňom všetky súbory a priečinky. Toto môžeme urobiť <span class="em">formátovaním</span> disku - táto operácia vymaže všetky súbory na disku a disk zanechá prázdny.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Otvoríme aplikáciu Diskové nástroje pomocou Prehľadnej ponuky.</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Open the <span class="app">Disks</span> application from the <span class="gui">Dash</span>.</p></li>
<li class="steps">
<p class="p">V zozname <span class="gui">Úložné zariadenia</span> zvolíme disk, ktorý chceme vymazať .</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents"><p class="p">Uistíme sa, či máme správny disk! Ak si zvolíme nesprávny disky, všetky súbory sa na ňom vymažú!</p></div></div></div></div>
</li>
<li class="steps"><p class="p">V časti Zväzky klikneme na <span class="gui">Odpojiť zväzok</span>, a potom na <span class="gui">Naformátovať zväzok</span>.</p></li>
<li class="steps">
<p class="p">In the window that pops up, choose a filesystem <span class="gui">Type</span> for the
   disk.</p>
<p class="p">Ak disk používame nie len na počítačoch Linux, ale aj na počítačoch so systémami Windows a Mac OS, zvolíme <span class="gui">FAT</span>. Ak ho používame iba na Windows, voľba <span class="gui">NTFS</span> môže byť lepšia. Stručný popis <span class="gui">súborového systému</span> sa zobrazí pod poľom.</p>
</li>
<li class="steps"><p class="p">Zadáme názov disku a kliknutím na tlačidlo <span class="gui">Formátovať</span> spustíme čistenie disku.</p></li>
<li class="steps"><p class="p">Po skončení formátovania disk klikneme na tlačidlo <span class="gui">Bezpečne odobrať</span>. Teraz by disk mal byť čistý a pripravený na ďalšie použitie.</p></li>
</ol></div>
</div></div>
<div class="note note-warning" title="Upozornenie"><div class="inner">
<div class="title title-note"><h2><span class="title">Formátovanie disku nezmaže súbory bezpečne</span></h2></div>
<div class="region"><div class="contents"><p class="p">Formátovanie disku nie je úplne bezpečný spôsob ako zmazať všetky údaje. Naformátovaný disk sa zdá byť prázdny, no napriek tomu nejaký špeciálny softvér môže súbory obnoviť. Ak potrebujeme údaje zmazať bezpečne, je potrebné použiť nástroj pre príkazový riadok ako napríklad <span class="app">shred</span>.</p></div></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Disky a úložiská">Disky a úložiská</a><span class="desc"> — 
    <span class="link"><a href="disk-capacity.html" title="Kontrola zostávajúceho voľného miesta">Disk space</a></span>,
    <span class="link"><a href="disk-benchmark.html" title="Testovanie výkonu pevného disku">performance</a></span>,
    <span class="link"><a href="disk-check.html" title="Skontrolovanie chýb na disku">problems</a></span>,
    <span class="link"><a href="disk-partitions.html" title="Správa zväzkov a oddielov">volumes and partitions</a></span>…
  </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
