<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nastavenie jasu obrazovky</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="power.html#problems" title="Problémy">Power problems</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="prefs-display.html" title="Vzhľad displeja; obrazovka">Vzhľad displeja; obrazovka</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nastavenie jasu obrazovky</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can change the brightness of your screen to save power or to make the
  screen more readable in bright light. You can also have the screen dim
  automatically when on battery power and have it turn off automatically when
  not in use.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Nastavenie jasu</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikneme na ikonu v tvare vypínača vpravo na <span class="gui">hornej lište</span> a zvolíme <span class="gui">Nastavenia systému</span>.</p></li>
<li class="steps"><p class="p">Select <span class="gui">Brightness &amp; Lock</span>.</p></li>
<li class="steps"><p class="p">Pomocou posuvníka <span class="gui">Jas</span> nastavíme prijateľnú hodnotu.</p></li>
</ol></div>
</div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Many laptop keyboards have special keys to adjust the brightness. These
    have a picture that looks like the sun and are located on the function
    keys at the top. Hold down the <span class="key"><kbd class="key-Fn">Fn</kbd></span> key to use these keys.</p></div></div></div></div>
<p class="p">Ak chceme aby sa jas automaticky znížil pri napájaní z batérie, zaškrtneme pole <span class="gui">Na úsporu energie znížiť jas</span>. Podsvietenie obrazovky môže vyžadovať veľa energie a jeho zníženie môže významne predĺžiť čas výdrže batérie.</p>
<p class="p">The screen will automatically turn off after you haven't used it for a
  while. This only affects the display, and doesn't turn off your computer.
  You can adjust how long you have to be inactive with the <span class="gui">Turn screen off
  when inactive for</span> option.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="power.html#problems" title="Problémy">Power problems</a><span class="desc"> — Troubleshoot problems with power and batteries.</span>
</li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a><span class="desc"> — Riešenie problémov s obrazom a grafikou.</span>
</li>
<li class="links ">
<a href="prefs-display.html" title="Vzhľad displeja; obrazovka">Vzhľad displeja; obrazovka</a><span class="desc"> — 
      <span class="link"><a href="look-background.html" title="Zmena pozadia pracovnej plochy">Background</a></span>,
      <span class="link"><a href="look-resolution.html" title="Change the size or rotation of the screen">size and rotation</a></span>,
      <span class="link"><a href="display-dimscreen.html" title="Nastavenie jasu obrazovky">brightness</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="display-lock.html" title="Automatické uzamknutie obrazovky">Automatické uzamknutie obrazovky</a><span class="desc"> — Zabránenie iným ľuďom v práci na našom počítači počas našej neprítomnosti.</span>
</li>
<li class="links ">
<a href="power-whydim.html" title="Prečo mi obrazovka stmavne po nejakej dobe?">Prečo mi obrazovka stmavne po nejakej dobe?</a><span class="desc"> — Keď je váš notebook napájaný z batérie alebo akonáhle je počítač nečinný tak sa displej stlmí z dôvodu úspory energie.</span>
</li>
<li class="links ">
<a href="a11y-contrast.html" title="Úprava kontrastu">Úprava kontrastu</a><span class="desc"> — Zvýraznenie okien a tlačidiel, aby boli lepšie vidieť.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
