<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nađite informacije o dokumentima</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#documents" title="Dokumenti">Dokumenti</a> » <a class="trail" href="documents.html" title="Dokumenti">Dokumenti</a> › <a class="trail" href="documents.html#view" title="Pregledaj, Sortiraj i Pretraga">Pregledaj, Sortiraj i Pretraga</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nađite informacije o dokumentima</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada je dokument kreiran, dolazi sa <span class="em">metapodatcima</span>. <span class="app">Documents</span> prikazuje sljedeće metapodatke za svaki dokument:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Naslov: ime dokumenta, koje se može mijenjati;</p></li>
<li class="list"><p class="p">Izvor: put do foldera koji sadrži dokument;</p></li>
<li class="list"><p class="p">Datum izmjene;</p></li>
<li class="list"><p class="p">Tip: <span class="link"><a href="documents-formats.html" title="Podržani formati">file format</a></span> dokumenta.</p></li>
</ul></div></div></div>
<p class="p">Da biste vidjeli svojstva dokumenta:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na dugme <span class="gui">Označi</span> da biste se prebacili na opciju za selektovanje.</p></li>
<li class="steps"><p class="p">Odaberite dokument.</p></li>
<li class="steps"><p class="p">Kliknite na <span class="gui">Svojstva</span> dugme na desnom kraju menija s dugmićima.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents">
<p class="p">Neki tipovi dokumenata (npr. PDF fajlovi) mogu biti zaštićeni lozinkim, sprečavajući pristup svom sadržaju.</p>
<p class="p"><span class="app">Files</span> trenutno ne podržava mehanizam za dodavanje privatnosti na dokumente. Možda možete to učiniti preko aplikacije koju ste koristili za kreiranje tog dokumenta (npr. <span class="app">LibreOffice</span> ili <span class="app">Adobe Acrobat </span>).</p>
</div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="documents.html#view" title="Pregledaj, Sortiraj i Pretraga">Pregledaj, Sortiraj i Pretraga</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
