<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dijeli i prebaci datoteke</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="sharing.html" title="Dijeljenje">Dijeljenje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dijeli i prebaci datoteke</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete dijeliti vaše datoteke sa vašim kontaktima ili ih poslati na eksterne uređaje kao ili <span class="link"><a href="nautilus-connect.html" title="Pregled datoteka na serveru ili na mreži">network shares</a></span> direktno iz fajl menadžera.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite <span class="link"><a href="files-browse.html" title="Pregledavanje datoteka i mapa.">menadžer datoteke</a></span>.</p></li>
<li class="steps"><p class="p">Pronađite datoteku koju želite prenijeti.</p></li>
<li class="steps"><p class="p">Desnom tipkom miša kliknite na datoteku i odaberite <span class="gui"> Pošalji u </span>.</p></li>
<li class="steps"><p class="p"><span class="gui"> Pošalji na </span> prozor će se pojaviti. Odaberite gdje želite poslati datoteku i kliknite <span class="gui"> Pošalji </span>. Pogledajte popis odredišta ispod, za više informacija.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Možete poslati više datoteka odjednom. Odaberite više datoteka držeći <span class="key"><kbd>Ctrl</kbd></span>, zatim desnim klikom miša odaberete bilo koju datoteku. Možete automatski kompresovati datoteke u zip ili tar arhivi.</p></div></div></div></div>
<div class="list"><div class="inner">
<div class="title title-list"><h2><span class="title">Odredišta</span></h2></div>
<div class="region"><ul class="list">
<li class="list"><p class="p">Za slanje datoteke e-mailom , odaberite <span class="gui"> Email </span> i unesite adresu primaoca e-maila.</p></li>
<li class="list"><p class="p">Da biste poslali datoteku na instant poruke kontaktu, odaberite <span class="gui"> Instant poruka </span>, a zatim odaberite kontakt iz padajućeg popisa. Vaša aplikacija za zahtjev  instant poruke će možda trebati biti pokrenuta da bi radila.</p></li>
<li class="list"><p class="p">Za pisanje datoteka na CD ili DVD, odaberite <span class="gui"> CD / DVD Creator </span>. Vidi <span class="link"><a href="files-disc-write.html" title="Pisanje datoteka na CD ili DVD.">Pisanje datoteka na CD ili DVD.</a></span> da biste saznali više.</p></li>
<li class="list"><p class="p">Za prenos datoteke na Bluetooth uređaj, odaberite <span class="gui">Bluetooth (OBEX Push)</span> i odaberite uređaj na koji želite poslati datoteku. Vidjet ćete samo uređaje sa kojima ste već bili upareni. Pogledajte<span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span> za više informacija.</p></li>
<li class="list"><p class="p">Da kopirate datoteku na spoljni uređaj poput USB flash drive-a, ili za prenos na server na koji ste već spojeni, odaberite <span class="gui">Prenosivi diskovi i dijeljenja</span>, a zatim odaberite uređaj ili sever na koji želite kopirati datoteku.</p></li>
</ul></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Traži datoteke">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li>
<li class="links ">
<a href="sharing.html" title="Dijeljenje">Dijeljenje</a><span class="desc"> — 
      <span class="link"><a href="sharing-desktop.html" title="Dijelite vaš desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Share files</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju">Pošalji datoteku Bluetooth uređaju</a><span class="desc"> — Dijelite datoteke sa Bluetooth uređajima kao što je vaš telefon.</span>
</li>
<li class="links ">
<a href="nautilus-connect.html" title="Pregled datoteka na serveru ili na mreži">Pregled datoteka na serveru ili na mreži</a><span class="desc"> — Pogledajte i uređujte datoteke na drugom računaru preko FTP, SSH, Windows dijeljenja, ili WebDAV.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
