<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Vyhľadávanie súborov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Vyhľadávanie súborov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Súbory môžeme vyhľadávať podľa ich názvu alebo typu priamo v správcovi súborov. Často používané hľadania si tiež môžeme uložiť. Zobrazia sa ako špeciálne priečinky v domovskom priečinku.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Search</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p"><span class="link"><a href="files-browse.html" title="Navigácia medzi priečinkami">Otvoríme správcu súborov</a></span></p></li>
<li class="steps"><p class="p">Ak vieme, že súbor, ktorý chceme sa nachádza v konkrétnom priečinku, prejdeme do toho priečinka.</p></li>
<li class="steps"><p class="p">Click the magnifying glass in the toolbar, or press
    <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>F</kbd></span></span>.</p></li>
<li class="steps"><p class="p">Type a word or words that you know appear in the file name. For
    example, if you name all your invoices with the word "Invoice", type
    <span class="input">invoice</span>. Press <span class="key"><kbd>Enter</kbd></span>. Words are matched regardless
    of case.</p></li>
<li class="steps">
<p class="p">You can narrow your results by location and file type.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Click <span class="gui">Home</span> to restrict the search results to your
      <span class="file">Home</span> folder, or <span class="gui">All Files</span> to search
      everywhere.</p></li>
<li class="list"><p class="p">Click <span class="key"><kbd>+</kbd></span> and pick a <span class="gui">File Type</span> from the
      drop-down list to narrow the search results based on file type. Click the
      <span class="key"><kbd>x</kbd></span> button to remove this option and widen the search
      results.</p></li>
</ul></div></div></div>
</li>
<li class="steps"><p class="p">Vyhľadané súbory môžeme otvoriť, skopírovať, zmazať alebo s nimi vykonať akúkoľvek inú operáciu ako keby boli v bežnom priečinku.</p></li>
<li class="steps"><p class="p">Click the magnifying glass in the toolbar again to exit the search
    and return to the folder.</p></li>
</ol></div>
</div></div>
<p class="p">Ak niektoré vyhľadávanie vykonávame často, môžeme si ho uložiť, aby sme ku nemu mali rýchly prístup.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Uloženie vyhľadávania</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Spustíme vyhľadávanie podľa predchádzajúceho postupu.</p></li>
<li class="steps"><p class="p">When you're happy with the search parameters, click <span class="gui">File</span>
    in the menu bar and select <span class="gui">Save Search As...</span>.</p></li>
<li class="steps"><p class="p">Zadáme pre vyhľadávanie názov a klikneme na tlačidlo <span class="gui">Uložiť</span>. Ak chceme, môžeme vybrať iný priečinok, do ktorého sa vyhľadávanie uloží. Ak vojdeme do daného priečinka, uložené vyhľadávanie uvidíme ako priečinok s obrázkom lupy.</p></li>
</ol></div>
</div></div>
<p class="p">To remove the search file when you are done with it, simply
  <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete</a></span> the search as you would any other
  file. When you delete a saved search, it does not delete the files that the
  search matched.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Vyhľadávanie súborov">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
