<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Datoteke, folderi &amp; pretraživanje</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Datoteke, folderi &amp; pretraživanje</span></h1></div>
<div class="region">
<div class="contents">
<div class="media media-image floatend if-if if__not-target-mobile"><div class="inner"><img src="figures/nautilus.png" class="media media-block" alt=" Nautilus  upravljač datotekama"></div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h2><span class="title">Uobičajeni zadaci</span></h2></div>
<div class="region"><ul>
<li class="links "><a class="bold" href="files-browse.html" title="Pregledavanje datoteka i mapa.">Pregledavanje datoteka i mapa.</a></li>
<li class="links "><a class="bold" href="files-copy.html" title="Kopirajte ili premjestite datoteke i foldere">Kopirajte ili premjestite datoteke i foldere</a></li>
<li class="links "><a class="bold" href="files-delete.html" title="Obrišite datoteke i direktorije.">Obrišite datoteke i  direktorije.</a></li>
<li class="links "><a class="bold" href="files-rename.html" title="Preimenujte datoteku ili folder">Preimenujte datoteku ili folder</a></li>
<li class="links "><a class="bold" href="files-preview.html" title="Prikažite primjere datoteka i mapa">Prikažite primjere datoteka i mapa</a></li>
<li class="links "><a class="bold" href="files-sort.html" title="Sortiraj datoteke i direktorije">Sortiraj datoteke i direktorije</a></li>
<li class="links "><a class="bold" href="files-search.html" title="Traži datoteke">Traži datoteke</a></li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h2><span class="title">Više tema.</span></h2></div>
<div class="region"><ul>
<li class="links "><a class="bold" href="files-share.html" title="Dijeli i prebaci datoteke">Dijeli i prebaci datoteke</a></li>
<li class="links "><a class="bold" href="files-lost.html" title="Nađi izgubljenu datoteku">Nađi izgubljenu datoteku</a></li>
<li class="links "><a class="bold" href="files-recover.html" title="Obnova datoteke iz smeća.">Obnova datoteke iz smeća.</a></li>
<li class="links "><a class="bold" href="files-open.html" title="Otvorite datoteke sa drugim aplikacijama">Otvorite datoteke sa drugim aplikacijama</a></li>
<li class="links "><a class="bold" href="files-disc-write.html" title="Pisanje datoteka na CD ili DVD.">Pisanje datoteka na CD ili DVD.</a></li>
<li class="links "><a class="bold" href="nautilus-connect.html" title="Pregled datoteka na serveru ili na mreži">Pregled datoteka na serveru ili na mreži</a></li>
<li class="links "><a class="bold" href="nautilus-file-properties-basic.html" title="Svojstva datoteke">Svojstva datoteke</a></li>
<li class="links "><a class="bold" href="nautilus-prefs.html" title="Postavke programa za upravljanje datotekama">Postavke programa za upravljanje datotekama</a></li>
</ul></div>
</div></div>
</div>
<div id="removable" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Prijenosni diskovi i vanjski diskovi.</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Otvorite aplikacije za uređaje ili diskove"><span class="title">Otvorite aplikacije za uređaje ili diskove</span><span class="linkdiv-dash"> — </span><span class="desc">Automatsko pokretanje aplikacija za CD i DVD, kamere, audio plejere i drugih uređaja i medija.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-removedrive.html" title="Sigurno ukloniti vanjski disk"><span class="title">Sigurno ukloniti vanjski disk</span><span class="linkdiv-dash"> — </span><span class="desc">Izbaciti ili demontirati USB memorijski pogon , CD, DVD ili neki drugi uređaj.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="backup" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Rezervne kopije</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="backup-thinkabout.html" title="Gdje mogu pronaći podatke koje želim sigurnosno kopirati ?"><span class="title">Gdje mogu pronaći podatke koje želim sigurnosno kopirati ?</span><span class="linkdiv-dash"> — </span><span class="desc">Lista mapa gdje možete naći dokumente,podatke i postvke koje možda želite sigurnosno kopirati.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka"><span class="title">Napravite sigurnosne kopije važnih datoteka</span><span class="linkdiv-dash"> — </span><span class="desc">Zašto, kako, gdje i na koji način do sigurnosnih kopija.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-check.html" title="Provjerite Vaše sigurnosne kopije"><span class="title">Provjerite Vaše sigurnosne kopije</span><span class="linkdiv-dash"> — </span><span class="desc">Provjerite da li je vaše sigurnosno kopiranje bilo uspješno</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="backup-frequency.html" title="Učestalost sigurnosnih kopija"><span class="title">Učestalost sigurnosnih kopija</span><span class="linkdiv-dash"> — </span><span class="desc">Naučite koliko često bi trebali raditi backup Vaših važnih datoteka da budete uvjereni da su sigurne.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-restore.html" title="Vratite sigurnosnu kopiju"><span class="title">Vratite sigurnosnu kopiju</span><span class="linkdiv-dash"> — </span><span class="desc">Vratite svoje podatke  iz sigurnosne kopije</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="documents" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Dokumenti</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="documents.html" title="Dokumenti"><span class="title">Dokumenti</span><span class="linkdiv-dash"> — </span><span class="desc">Organizujte lokalne dokumente sa vašeg računara ili dokumente kreirane na internetu.</span></a></div></div>
<div class="links-twocolumn"></div>
</div></div></div></div></div>
</div></div>
<div id="faq" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Savjeti i pitanja</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="files-select.html" title="Odaberite datoteke po uzorku"><span class="title">Odaberite datoteke po uzorku</span><span class="linkdiv-dash"> — </span><span class="desc">Pritisnite <span class="keyseq"><span class="key"><kbd> Ctrl </kbd></span>+<span class="key"><kbd> S </kbd></span></span> kako biste odabrali više datoteka koje imaju slične nazive.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="nautilus-file-properties-permissions.html" title="Postavite dozvole za datoteku"><span class="title">Postavite dozvole za datoteku</span><span class="linkdiv-dash"> — </span><span class="desc">Kontrolišite ko može vidjeti i izmjeniti vaše datoteke i foldere.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-hidden.html" title="Sakrij datoteku."><span class="title">Sakrij datoteku.</span><span class="linkdiv-dash"> — </span><span class="desc">Napravite datoteku nevidljivom, tako da je ne možete vidjeti  u upravljanjem datotekama.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="nautilus-bookmarks-edit.html" title="Uređujte oznake u folderu"><span class="title">Uređujte oznake u folderu</span><span class="linkdiv-dash"> — </span><span class="desc">Dodajte, obrišite ili preimenujte oznake u programu za upravljanje datotekama.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-tilde.html" title='Što je datoteka sa "~" na kraju svog imena?'><span class="title">Što je datoteka sa "~" na kraju svog imena?</span><span class="linkdiv-dash"> — </span><span class="desc">To su sigurnosne kopije datoteka. One su skrivene po postavci.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-templates.html" title="šabloni za najčešće korištne vrste dokumenata."><span class="title">šabloni  za najčešće korištne vrste dokumenata.</span><span class="linkdiv-dash"> — </span><span class="desc">Brzo napravite  nove dokumente poručene  za datoteku šablona.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
