<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Problemi ekrana.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Problemi ekrana.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Većina problema sa ekranom su uzrokovane problemima grafičkog upravljačkog pogona ili konfiguracije. Koji od tema u nastavku najbolje opisuje problem koji susrecete?</p>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="display-dimscreen.html" title="Postavite osvjetljenje ekrana"><span class="title">Postavite osvjetljenje ekrana</span><span class="linkdiv-dash"> — </span><span class="desc">Zamaglite ekran radi očuvanja energije ili povećajte svjetlinu da bi ga učinili čitljivim na jakom svjetlu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="look-resolution.html" title="Promijenite veličinu rotacije ekrana"><span class="title">Promijenite veličinu rotacije ekrana</span><span class="linkdiv-dash"> — </span><span class="desc">Promijenite rezoluciju ekrana i njegovu orijentaciju (rotaciju).</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="session-screenlocks.html" title="Zaslon se prebrzo sam zaključava"><span class="title">Zaslon se prebrzo sam zaključava</span><span class="linkdiv-dash"> — </span><span class="desc">Izmijenite nakon kog vremena će se zaključati ekran u podešavanjima <span class="gui">Osvjetljenost i zaključavanje</span>.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-suspendfail.html" title="Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??"><span class="title">Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??</span><span class="linkdiv-dash"> — </span><span class="desc">Hardver nekih računara stvara problem sa obustavljanjem ili hibernacijom</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?"><span class="title">Zašto se moj ekran zamagli nakon nekog vremena?</span><span class="linkdiv-dash"> — </span><span class="desc">Ako vaš računar radi na bateriju, ekran će se zatamniti kada računar miruje kako bi uštedio snagu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="look-display-fuzzy.html" title="Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?"><span class="title">Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?</span><span class="linkdiv-dash"> — </span><span class="desc">Rezolucija zaslona može se postaviti na pogrešan način.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-willnotturnon.html" title="Moj računar ne moe da se upali"><span class="title">Moj računar ne moe da se upali</span><span class="linkdiv-dash"> — </span><span class="desc">Labavi kablovi i hardverski problemi su mogući razlozi.</span></a></div>
</div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
