<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zvuk, video a obrázky</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zvuk, video a obrázky</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="sound" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Zvuk</span></h2></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="sound-broken.html" title="Sound problems"><span class="title">Sound problems</span><span class="linkdiv-dash"> — </span><span class="desc">Troubleshoot problems like having no sound or having poor sound quality.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-alert.html" title="Choose or disable the alert sound"><span class="title">Choose or disable the alert sound</span><span class="linkdiv-dash"> — </span><span class="desc">Choose the sound to play for messages, set the alert
    volume, or disable alert sounds.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-usespeakers.html" title="Používanie rôznych reproduktorov alebo slúchadiel"><span class="title">Používanie rôznych reproduktorov alebo slúchadiel</span><span class="linkdiv-dash"> — </span><span class="desc">Pripojte reproduktory alebo slúchadlá a vyberte predvolené zariadenie pre výstup zvuku.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="sound-usemic.html" title="Use a different microphone"><span class="title">Use a different microphone</span><span class="linkdiv-dash"> — </span><span class="desc">Use an analog or USB microphone and select a default input device.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-volume.html" title="Zmena hlasitosti"><span class="title">Zmena hlasitosti</span><span class="linkdiv-dash"> — </span><span class="desc">Set the sound volume for the computer and control the
    loudness of each application.</span></a></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h3><span class="title">Viac informácií</span></h3></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Užívateľské a systémové nastavenia">Užívateľské a systémové nastavenia</a><span class="desc"> — 
      <span class="link"><a href="keyboard.html" title="Klávesnica">Keyboard</a></span>,
      <span class="link"><a href="mouse.html" title="Myš">mouse</a></span>,
      <span class="link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">display</a></span>,
      <span class="link"><a href="prefs-language.html" title="Region &amp; Language">languages</a></span>,
      <span class="link"><a href="user-accounts.html" title="Užívateľský účet">user accounts</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div id="music" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Hudba a prenosné prehrávače</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="music-player-newipod.html" title="Nový iPod nefunguje"><span class="title">Nový iPod nefunguje</span><span class="linkdiv-dash"> — </span><span class="desc">Novozakúpené iPody je potrebné pred použitím nastaviť pomocou softvéru iTunes.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Open applications for devices or discs"><span class="title">Open applications for devices or discs</span><span class="linkdiv-dash"> — </span><span class="desc">Automatické spustenie aplikácie pre CD a DVD disky, fotoaparáty, prehrávače zvuku a ďalšie zariadenia a nosiče.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="music-player-notrecognized.html" title="Prečo systém nerozpozná prehrávač po pripojení?"><span class="title">Prečo systém nerozpozná prehrávač po pripojení?</span><span class="linkdiv-dash"> — </span><span class="desc">Pridanie súboru <span class="input">.is_audio_player</span>, aby počítač vedel, že ide o prehrávač hudby.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="music-player-ipodtransfer.html" title="Skladby sa po skopírovaní do iPodu nezobrazujú"><span class="title">Skladby sa po skopírovaní do iPodu nezobrazujú</span><span class="linkdiv-dash"> — </span><span class="desc">Použitie prehrávača hudby na kopírovanie a bezpečné odstránenie skladieb z iPodu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="music-cantplay-drm.html" title="Skladby zakúpené z internetového obchodu sa nedajú prehrať"><span class="title">Skladby zakúpené z internetového obchodu sa nedajú prehrať</span><span class="linkdiv-dash"> — </span><span class="desc">Podpora formátov, ktoré nemôžu byť nainštalované a prehrávanie skladieb, ktoré sú "chránené proti kopírovaniu".</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="photos" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Fotografie a digitálne fotoaparáty</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Open applications for devices or discs"><span class="title">Open applications for devices or discs</span><span class="linkdiv-dash"> — </span><span class="desc">Automatické spustenie aplikácie pre CD a DVD disky, fotoaparáty, prehrávače zvuku a ďalšie zariadenia a nosiče.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="hardware-cardreader.html" title="Problémy s čítačkou kariet"><span class="title">Problémy s čítačkou kariet</span><span class="linkdiv-dash"> — </span><span class="desc">Riešenie problémov s čítačkou kariet</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="videos" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Videá a videokamery</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="video-sending.html" title="Nemožno prehrať video"><span class="title">Nemožno prehrať video</span><span class="linkdiv-dash"> — </span><span class="desc">Skontrolujte, či máte nainštalované správne video kodeky.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Open applications for devices or discs"><span class="title">Open applications for devices or discs</span><span class="linkdiv-dash"> — </span><span class="desc">Automatické spustenie aplikácie pre CD a DVD disky, fotoaparáty, prehrávače zvuku a ďalšie zariadenia a nosiče.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="video-dvd.html" title="Prečo neprehráva DVD?"><span class="title">Prečo neprehráva DVD?</span><span class="linkdiv-dash"> — </span><span class="desc">Nemáte nainštalované správne kodeky alebo pre DVD máte nastavený zlý región.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="app-cheese.html" title="Vytváranie zábavých fotografií a videí pomocou webovej kamery"><span class="title">Vytváranie zábavých fotografií a videí pomocou webovej kamery</span><span class="linkdiv-dash"> — </span><span class="desc">Vytváranie osobných fotografií v štýle fotobúdky.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="video-dvd-restricted.html" title="Ako povoliť obmedzené kodeky na prehrávanie DVD?"><span class="title">Ako povoliť obmedzené kodeky na prehrávanie DVD?</span><span class="linkdiv-dash"> — </span><span class="desc">Väčšina komerčných DVD je kódovaná a nepôjdu prehrať bez dekódovacieho softvéru.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Príručka pre Ubuntu desktop">Príručka pre Ubuntu desktop</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
