<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zvuk, video &amp; slike</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zvuk, video &amp; slike</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="sound" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Osnovni zvuk</span></h2></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="sound-broken.html" title="Problemi sa zvukom"><span class="title">Problemi sa zvukom</span><span class="linkdiv-dash"> — </span><span class="desc">Uklonite probleme poput onih da nemate zvuka ili je kvalitet zvula loš.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-alert.html" title="Izaberite ili onemogućite zvuk upozorenja"><span class="title">Izaberite ili onemogućite zvuk upozorenja</span><span class="linkdiv-dash"> — </span><span class="desc">Odaberite zvuk koji se reproducira za poruku, postavite glasnoću upozorenja, ili onemogućite zvukove upozorenja.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-usemic.html" title="Koristite drugi mikrofon"><span class="title">Koristite drugi mikrofon</span><span class="linkdiv-dash"> — </span><span class="desc">Koristite analogni ili USB mikrofon i odaberite zadani ulazni uređaj.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice."><span class="title">Koristite različite zvučnike i slušalice.</span><span class="linkdiv-dash"> — </span><span class="desc">Spojite zvučnike ili slušalice i odaberite zadani izlazni audio uređaj.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sound-volume.html" title="Promjenite jačinu zvuka"><span class="title">Promjenite jačinu zvuka</span><span class="linkdiv-dash"> — </span><span class="desc">Postavite jačinu zvuka na vašem računaru i kontrolišite glasnoću za svaki program.</span></a></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h3><span class="title">Više informacija</span></h3></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div id="music" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Muzika i prenosivi plejeri</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="music-player-newipod.html" title="Moj noviiPod neće da radi"><span class="title">Moj noviiPod neće da radi</span><span class="linkdiv-dash"> — </span><span class="desc">Posve novi iPod moraju biti postavljeni koristeći iTunes softver prije nego što možete ih koristiti.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="music-cantplay-drm.html" title="Ne mogu slušati pjesmu koju sam kupio na online muzičkoj prodavnici"><span class="title">Ne mogu slušati pjesmu koju sam kupio na online muzičkoj prodavnici</span><span class="linkdiv-dash"> — </span><span class="desc">Podrška za tu vrstu datoteke možda nije instalirana ili pjesme mogu biti "zaštićene od kopiranja".</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Otvorite aplikacije za uređaje ili diskove"><span class="title">Otvorite aplikacije za uređaje ili diskove</span><span class="linkdiv-dash"> — </span><span class="desc">Automatsko pokretanje aplikacija za CD i DVD, kamere, audio plejere i drugih uređaja i medija.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="music-player-ipodtransfer.html" title="Pjesme se ne pojavljuju na mom iPod-u kada ih kopiram na njega."><span class="title">Pjesme se ne pojavljuju na mom iPod-u kada ih kopiram na njega.</span><span class="linkdiv-dash"> — </span><span class="desc">Koristite media player za kopiranje pjesama i sigurno uklanjanje iPod-a poslije.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="music-player-notrecognized.html" title="Zašto moj audio player ne prepoznaju kada ga spojim?"><span class="title">Zašto moj audio player ne prepoznaju kada ga spojim?</span><span class="linkdiv-dash"> — </span><span class="desc">Dodaj <span class="input">.is_audio_player</span> datoteku da kažete vašem računaru da je to audio player.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="photos" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Slike i digitalni aparati</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Otvorite aplikacije za uređaje ili diskove"><span class="title">Otvorite aplikacije za uređaje ili diskove</span><span class="linkdiv-dash"> — </span><span class="desc">Automatsko pokretanje aplikacija za CD i DVD, kamere, audio plejere i drugih uređaja i medija.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="hardware-cardreader.html" title="Problemi sa čitačem kartica."><span class="title">Problemi sa čitačem kartica.</span><span class="linkdiv-dash"> — </span><span class="desc">Rješavanje problema s čitatčima medijskih kartica.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="videos" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Video i video kamere</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="video-sending.html" title="Drugi ljudi ne mogu pokrenuti video koji sam ja napravio."><span class="title">Drugi ljudi ne mogu pokrenuti video koji sam ja napravio.</span><span class="linkdiv-dash"> — </span><span class="desc">Provjerite da imate instalirane ispravne video kodeke.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="app-cheese.html" title="Napravite zanimljive fotografije i videozapise vašom webkamerom"><span class="title">Napravite zanimljive fotografije i videozapise vašom webkamerom</span><span class="linkdiv-dash"> — </span><span class="desc">Ovo izgleda kao Vaša vlastita FotoGalerija</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Otvorite aplikacije za uređaje ili diskove"><span class="title">Otvorite aplikacije za uređaje ili diskove</span><span class="linkdiv-dash"> — </span><span class="desc">Automatsko pokretanje aplikacija za CD i DVD, kamere, audio plejere i drugih uređaja i medija.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="video-dvd.html" title="Zašto DVD ne radi?"><span class="title">Zašto DVD ne radi?</span><span class="linkdiv-dash"> — </span><span class="desc">Možda nemate instalirane odgovarajuće kodeke, ili je DVD iz pogrešnog regiona.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="video-dvd-restricted.html" title="Kako da omogućim ograničene kodeke da pokrenu DVD-ve?"><span class="title">Kako da omogućim ograničene kodeke da pokrenu DVD-ve?</span><span class="linkdiv-dash"> — </span><span class="desc">Mnogi komercijalni DVD-vi su kodirani i neće raditi bez softvera za dešifrovanje.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
