<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pokazivač miša se ne kreće</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> › <a class="trail" href="mouse.html#problems" title="Uobičajeni problemi">Uobičajeni problemi</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> › <a class="trail" href="mouse.html#problems" title="Uobičajeni problemi">Uobičajeni problemi</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pokazivač miša se ne kreće</span></h1></div>
<div class="region">
<div class="contents"><div role="navigation" class="links sectionlinks"><div class="inner"><div class="region"><ul>
<li class="links "><a href="mouse-problem-notmoving.html#plugged-in" title="Provjeri da je miš priključen">Provjeri da je miš priključen</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#connected" title="Provjera da je računar prepoznao miša">Provjera da je računar prepoznao miša</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#broken" title="Provjerite da miš stvarno radi">Provjerite da miš stvarno radi</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#wireless-mice" title="Provjera bežičnih miševa">Provjera bežičnih miševa</a></li>
</ul></div></div></div></div>
<div id="plugged-in" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjeri da je miš priključen</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako imate miš sa kabelom, provjerite da je čvrsto spojen na računar.</p>
<p class="p">Ako je USB miš( sa pravougaonim konektorom) pokušajte spajanjem na drugi port. A ako je PS/2 miš( sa malim okruklim konektorom sa 6 pinova) pobrinite se da je spojen u zeleni port za miš a ne u ljubičasti za tastaturu. Možda čete morati restartovati računar ako nije bio spojen.</p>
</div></div>
</div></div>
<div id="connected" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjera da je računar prepoznao miša</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Ukucajte <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>T</kbd></span></span> da biste otvorili <span class="app">Terminal</span>.</p></li>
<li class="steps"><p class="p">U terminal prozoru, ukucajte <span class="cmd">xsetpointer -l | grep Pointer</span>, tačno kako se pojavljuje ovdje, i pritisnite <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps"><p class="p">Pojaviće se kratka lista miš uređaja. Provjerite bar jednu stavku pored koje stoji <span class="sys">[XExtensionPointer]</span>, i jednu <span class="sys">[XExtensionPointer]</span> stavku koja ima naziv miša pored nje lijevo.</p></li>
<li class="steps"><p class="p">Ako nema imena miša praćenog sa <span class="sys">[XExtensionPointer]</span>,onda miš nije prepoznat od strane računara. Ako unos postoji miš je prpoznat. U ovom slučaju trebate pogledati <span class="link"><a href="mouse-problem-notmoving.html#plugged-in" title="Provjeri da je miš priključen">plugged in</a></span> i  <span class="link"><a href="mouse-problem-notmoving.html#broken" title="Provjerite da miš stvarno radi">working condition</a></span>.</p></li>
</ol></div></div></div>
<p class="p">Ako vaš miš ima serijski (RS-232) konektor, možda ćete morati odraditi neke dodatne korake da bi proradio. Sve ovisi o modelu miša</p>
<p class="p">Može biti komplicirano da riješite probleme sa prepoznavanjem miša. Pitajte za podršku vašeg distributera ili prodavača ako mislite da vaš miš nije ispravno prepoznat.</p>
</div></div>
</div></div>
<div id="broken" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite da miš stvarno radi</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Spojite miš na drugi računar da provjerite da radi.</p>
<p class="p">Ako je miš optički, svjetlo bi trebali da izlazi na dnu miša ako je ukljulen. Ako nema svjetla, provjerite da li je uključen. A ako jeste i dalje nema svjetla, moguće da je pokvaren</p>
</div></div>
</div></div>
<div id="wireless-mice" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjera bežičnih miševa</span></h2></div>
<div class="region"><div class="contents">
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Budite sigurni da je vaš miš uključen. Često se na dnu miša nalazi prekidač da isključite miš upotpunosti, tako da ga možete pomjerati sa mjesta na mjesto bez konstantnog buđenja.</p></li>
<li class="list"><p class="p">Ako koristite Bluetooth miš, budite sigurni da je spojen na vaš računar. Vidi <span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">Povežite vaš računar sa Bluetooth uređajem</a></span>.</p></li>
<li class="list"><p class="p">Kliknite tipku i vidi ako se pokazivač miša sada pomjera. Neki bežični miševi spavaju da uštede energiju, pa ne odgovaraju dok ne kliknete tipku. Vidi <span class="link"><a href="mouse-wakeup.html" title="Miš reaguje sa zakašnjenjem prije nego počne raditi.">Miš reaguje sa zakašnjenjem prije nego počne raditi.</a></span>.</p></li>
<li class="list"><p class="p">Provjerite da je napunjena baterija u mišu.</p></li>
<li class="list"><p class="p">Budite sigurni da je prijemnik (dongle) čvrsto spojen na računar.</p></li>
<li class="list"><p class="p">Ako miš i prijemnik mogu raditi na različitim radio kanalima, budite sigurni da su postavljni na isti kanal.</p></li>
<li class="list"><p class="p">Možda morate pritisnutu tipku na mišu, prijemniku ili i jednom i drugom da uspostavite vezu. Upute za upotrebu miša trebale bi imati više detalja ako je to slučaj.</p></li>
</ul></div></div></div>
<p class="p">Većina RF(radio) bežičnih miševa bi trebala raditi automatski kad ih spojite na računar. Ako imate Bluetooth ili IR(infracrveni) bežični miš, moguče je da trebate poduzeti dodatne korake da proradi. Sve ovisi o modelu miša.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="mouse.html#problems" title="Uobičajeni problemi">Uobičajeni problemi s mišem</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
