<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Klikajte, povucite, ili skrolajte pomoću touchpad-a.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Klikajte, povucite, ili skrolajte pomoću touchpad-a.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete kliknuti, napraviti dupli klik, povući i listati koristeći samo dodirnu površinu, bez razdvojenih hardverskih dugmadi.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Miš i dodirna ploča</span>.</p></li>
<li class="steps">
<p class="p">U <span class="gui">Touchpad</span> sekciji, čekirajte <span class="gui">Tap to click</span>.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Sekcija <span class="gui">Touchpad</span> se pojavljuje samo ako vaš sistem ima tačped.</p></div></div></div></div>
</li>
</ol></div></div></div>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Za klik, dodirnite dodirnu površinu.</p></li>
<li class="list"><p class="p">Da dva puta kliknete tapnite dva puta.</p></li>
<li class="list"><p class="p">Za povlačenje stavke, dupli dodir ali ne dižite prst nakon drugog dodira. Povucite stavku gdje želite, a zadtim dignite prst da je spustite.</p></li>
<li class="list"><p class="p">Ako vaš touchpad podržava više-prtsni dodir, desni klik dodir dva prsta odjednom. Inače morate koristiti dugmad da uradite desni klik: pogledajte <span class="link"><a href="a11y-right-click.html" title="Simulacija klika desnom tipkom miša">Simulacija klika desnom tipkom miša</a></span> za način desnog klika bez drugog dugmeta miša</p></li>
<li class="list"><p class="p">Ako vaš touchpad podržava više-prtsni dodir, <span class="link"><a href="mouse-middleclick.html" title="Srednji klik">middle-click</a></span> pritiskom sa tri prsta odjednom.</p></li>
</ul></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Kada pritišćete ili vučete sa više prstiju razdvojite vaše prste dovoljno. Ako su prsti previše blizu računar može pomisliti da je jedan prst.</p></div></div></div></div>
</div>
<div id="twofingerscroll" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Skrolanje pomoću dva prsta</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete skrolati pomoću touchpada koristeći dva prsta.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Miš i dodirna ploča</span>.</p></li>
<li class="steps"><p class="p">U  <span class="gui">Touchpad</span> sekciji, čekirajte <span class="gui">Two finger scroll</span>.</p></li>
</ol></div></div></div>
<p class="p">When this is selected, tapping and dragging with one finger will work as
normal, but if you drag two fingers across any part of the touchpad, it will
scroll instead. If you also select <span class="gui">Enable horizontal scrolling</span>, you
can move your fingers left and right to scroll horizontally. Be careful to space
your fingers a bit apart. If your fingers are too close together, they just look
like one big finger to your touchpad.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Listanje sa dva prsta možda neće raditi na svim dodirnim površinama.</p></div></div></div></div>
</div></div>
</div></div>
<div id="contentsticks" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Sadržaj će biti zaljepljen za prste</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Pomoću touchpad-a možete povlačiti sadržaje kako biste povlačili komad papira.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Miš i dodirna ploča</span>.</p></li>
<li class="steps"><p class="p">U  <span class="gui">Dodirna ploča</span> sekciji, čekirajte  <span class="gui">Sadržaj se hvata za prste</span>.</p></li>
</ol></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Ta mogućnost se imenuje i <span class="em">Prirodno klizanje</span> ili <span class="em">Obratno klizanje</span>.</p></div></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="mouse.html" title="Miš">Miš</a><span class="desc"> — <span class="link"><a href="mouse-lefthanded.html" title="Miš za ljevoruke">Ljevak</a></span>, <span class="link"><a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">brzina i osjetljivost</a></span>, <span class="link"><a href="mouse-touchpad-click.html" title="Klikajte, povucite, ili skrolajte pomoću touchpad-a.">dodirna površina, klik i listanje</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="unity-scrollbars-intro.html" title="Šta su okvirni trake za pomicanje?">Šta su okvirni trake za pomicanje?</a><span class="desc"> — Preklopne klizne trake su tanki narandžasti odsječci na dugim dokumentima.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
