<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Myš</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Myš</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="mouse-mousekeys.html" title="Click and move mouse pointer using the keypad"><span class="title">Click and move mouse pointer using the keypad</span><span class="linkdiv-dash"> — </span><span class="desc">Enable mouse keys to control the mouse with the keypad.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad"><span class="title">Click, drag, or scroll with the touchpad</span><span class="linkdiv-dash"> — </span><span class="desc">Click, drag, or scroll using taps and gestures on your touchpad.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="mouse-lefthanded.html" title="Myš pre ľavákov"><span class="title">Myš pre ľavákov</span><span class="linkdiv-dash"> — </span><span class="desc">Zámena ľavého a pravého tlačidla myši.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="mouse-doubleclick.html" title="Rýchlosť dvojitého kliknutia"><span class="title">Rýchlosť dvojitého kliknutia</span><span class="linkdiv-dash"> — </span><span class="desc">Nastavenie tolerovanej prestávky medzi dvoma kliknutiami pri dvojitom kliknutí.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="mouse-sensitivity.html" title="Rýchlosť pohybu myši a touchpadu"><span class="title">Rýchlosť pohybu myši a touchpadu</span><span class="linkdiv-dash"> — </span><span class="desc">Natavenie rýchlosti pohybu kurzora myši pri pohybe myši alebo touchpadu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="a11y-right-click.html" title="Simulovanie kliknutia pravým tlačidlom"><span class="title">Simulovanie kliknutia pravým tlačidlom</span><span class="linkdiv-dash"> — </span><span class="desc">Zapnutie simulovania kliknutia pravým tlačidlom podržaním ľavého tlačidla.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="a11y-dwellclick.html" title="Simulovanie kliknutia zotrvaním"><span class="title">Simulovanie kliknutia zotrvaním</span><span class="linkdiv-dash"> — </span><span class="desc">Funkcia kliknutie zotrvaním umožňuje kliknúť podržaním kurzora myši na rovnakom mieste.</span></a></div>
</div>
</div></div></div></div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Časté problémy</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="mouse-problem-notmoving.html" title="Mouse pointer is not moving"><span class="title">Mouse pointer is not moving</span><span class="linkdiv-dash"> — </span><span class="desc">Ako skontrolovať myš, keď nefunguje.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="mouse-wakeup.html" title="Mouse reacts with delay before it starts working"><span class="title">Mouse reacts with delay before it starts working</span><span class="linkdiv-dash"> — </span><span class="desc">Myš začne reagovať až po kliknutí alebo pohýbaní.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="tips" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Tipy</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="mouse-middleclick.html" title="Stredné tlačidlo myši"><span class="title">Stredné tlačidlo myši</span><span class="linkdiv-dash"> — </span><span class="desc">Používanie prostredného tlačidla myši na vkladanie textu alebo otváranie kariet.</span></a></div></div>
<div class="links-twocolumn"></div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware.html" title="Hardvér a ovládače">Hardvér a ovládače</a><span class="desc"> — 
      <span class="link"><a href="hardware.html#problems" title="Časté problémy">Hardware problems</a></span>,
      <span class="link"><a href="printing.html" title="Tlačiť">printers</a></span>,
      <span class="link"><a href="power.html" title="Power &amp; battery">power settings</a></span>,
      <span class="link"><a href="color.html" title="Správa farieb">color management</a></span>,
      <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>,
      <span class="link"><a href="disk.html" title="Disky a úložiská">disks</a></span>…
    </span>
</li>
<li class="links ">
<a href="prefs.html" title="Užívateľské a systémové nastavenia">Užívateľské a systémové nastavenia</a><span class="desc"> — 
      <span class="link"><a href="keyboard.html" title="Klávesnica">Keyboard</a></span>,
      <span class="link"><a href="mouse.html" title="Myš">mouse</a></span>,
      <span class="link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">display</a></span>,
      <span class="link"><a href="prefs-language.html" title="Region &amp; Language">languages</a></span>,
      <span class="link"><a href="user-accounts.html" title="Užívateľský účet">user accounts</a></span>…
    </span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
