<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Mouse pointer is not moving</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> › <a class="trail" href="mouse.html#problems" title="Časté problémy">Časté problémy</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> › <a class="trail" href="mouse.html#problems" title="Časté problémy">Časté problémy</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Mouse pointer is not moving</span></h1></div>
<div class="region">
<div class="contents"><div role="navigation" class="links sectionlinks"><div class="inner"><div class="region"><ul>
<li class="links "><a href="mouse-problem-notmoving.html#plugged-in" title="Skontrolujte, či je myš pripojená">Skontrolujte, či je myš pripojená</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#connected" title="Skontrolujte, či počítač rozpoznal myš">Skontrolujte, či počítač rozpoznal myš</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#broken" title="Skontrolujte, či myš nie je pokazená">Skontrolujte, či myš nie je pokazená</a></li>
<li class="links "><a href="mouse-problem-notmoving.html#wireless-mice" title="Skontrolujte bezdrôtovú myš">Skontrolujte bezdrôtovú myš</a></li>
</ul></div></div></div></div>
<div id="plugged-in" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Skontrolujte, či je myš pripojená</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ak máme myš s káblom, skontrolujeme, či je správne pripojená k počítaču.</p>
<p class="p">Ak je to USB myš (s obdĺžnikovým konektorom), skúsime ju pripojiť od iného USB portu. Ak je to myš PS/2 (s malým okrúhlym konektorom so šiestimi kolíkmi), uistíme sa, či je pripojená do zeleného portu pre myš a nie do fialového portu pre klávesnicu. Po pripojení bude potrebné reštartovať počítač.</p>
</div></div>
</div></div>
<div id="connected" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Skontrolujte, či počítač rozpoznal myš</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Type <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>T</kbd></span></span> to open the <span class="app">Terminal</span>.</p></li>
<li class="steps"><p class="p">
   In the terminal window, type <span class="cmd">xsetpointer -l | grep Pointer</span>,
    exactly as it appears here,
   and press <span class="key"><kbd>Enter</kbd></span>.
   </p></li>
<li class="steps"><p class="p">Zobrazí sa krátky zoznam zariadení ovládajúcich kurzor myši. Skontrolujeme, či má aspoň jedno zariadenie pri sebe napísané  <span class="sys">[XExtensionPointer]</span>, a či je vľavo od <span class="sys">[XExtensionPointer]</span> názov nášho zariadenia.</p></li>
<li class="steps"><p class="p">If there is no entry that has the name of the mouse followed by
   <span class="sys">[XExtensionPointer]</span>, then the mouse was not recognized by your
   computer. If the entry exists, your mouse was recognized by your computer.
   In this case you should check that the mouse is
   <span class="link"><a href="mouse-problem-notmoving.html#plugged-in" title="Skontrolujte, či je myš pripojená">plugged in</a></span> and in
   <span class="link"><a href="mouse-problem-notmoving.html#broken" title="Skontrolujte, či myš nie je pokazená">working condition</a></span>.</p></li>
</ol></div></div></div>
<p class="p">Ak máme sériovú myš (s konektorom RS-232), môže byť potrebné vykonať niekoľko dodatočný krokov aby myš pracovala. Tieto kroky závisia od modelu myši, ktorý používame.</p>
<p class="p">Opraviť problém s rozpoznaním myši môže byť komplikované. Skúsime kontaktovať podporu svojej distribúcie alebo výrobcu zariadenia, že zariadenie nebolo správne rozpoznané.</p>
</div></div>
</div></div>
<div id="broken" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Skontrolujte, či myš nie je pokazená</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Pripojíme myš k inému počítaču a skontrolujeme, či funguje.</p>
<p class="p">Ak je myš optická alebo laserová, mala by na spodnej strane svietiť. Ak na spodnej strane nevidíme svetlo, skontrolujeme, či je myš zapnutá. Ak je, a napriek tomu nesvieti, tak je pokazená.</p>
</div></div>
</div></div>
<div id="wireless-mice" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Skontrolujte bezdrôtovú myš</span></h2></div>
<div class="region"><div class="contents">
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Make sure the mouse is turned on. There is often a switch on the
   bottom of the mouse to turn the mouse off completely, so you can move it
   from place to place without it constantly waking up.</p></li>
<li class="list"><p class="p">If you are using a Bluetooth mouse, make sure you have actually paired the
   mouse with your computer. See <span class="link"><a href="bluetooth-connect-device.html" title="Connect your computer to a Bluetooth device">Connect your computer to a Bluetooth device</a></span>.</p></li>
<li class="list"><p class="p">
   Click a button and see if the mouse pointer moves now. Some wireless mice go
   to sleep to save power, so might not respond until you click a button.
   See <span class="link"><a href="mouse-wakeup.html" title="Mouse reacts with delay before it starts working">Mouse reacts with delay before it starts working</a></span>.
   </p></li>
<li class="list"><p class="p">Skontrolujeme stav nabitia batérie.</p></li>
<li class="list"><p class="p">Skontrolujeme, či je prijímač správne pripojený k počítaču.</p></li>
<li class="list"><p class="p">Ak myš a prijímač môžu fungovať na rôznych rádiových kanáloch, uistíme sa, že sú obe zariadenia nastavené na rovnaký kanál.</p></li>
<li class="list"><p class="p">Môže byť potrebné stlačiť tlačidlo na myši, na prijímači alebo na oboch zariadeniach súčasne, aby sa medzi nimi nadviazalo spojenie. Viac informácií by sa malo nachádzať v príručke k zariadeniu.</p></li>
</ul></div></div></div>
<p class="p">Väčšina RF (rádiových) bezdrôtových myší by malo fungovať automaticky po pripojení k počítaču. Ak máme Bluetooth alebo IR (infračervenú) bezdrôtovú myš, môže byť potrebné vykonať niekoľko dodatočných krokov aby začali pracovať. Tieto kroky závisia od modelu myši, ktorú používame.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="mouse.html#problems" title="Časté problémy">Časté problém s myšou</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
