<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Stredné tlačidlo myši</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> › <a class="trail" href="mouse.html#tips" title="Tipy">Tipy</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> › <a class="trail" href="mouse.html#tips" title="Tipy">Tipy</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="tips.html" title="Tips &amp; tricks">Tips &amp; tricks</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Stredné tlačidlo myši</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Many mice and some touchpads have a middle mouse button. On a mouse
with a scroll wheel, you can usually press directly down on the scroll
wheel to middle-click. If you don't have a middle mouse button, you
can press the left and right mouse buttons at the same time to
middle-click. If you find you are unable to middle-click this way you 
can try following <span class="link"><a href="https://wiki.ubuntu.com/X/Quirks#A2-button_Mice" title="https://wiki.ubuntu.com/X/Quirks#A2-button_Mice">
these instructions</a></span>.</p>
<p class="p">Na touchpadoch ktoré sú citlivé na dotyk viacerých prstov, môžeme kliknutie prostredným tlačidlom vyvolať ťuknutím troma prstami naraz. Aby to fungovalo, je potrebné <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">povoliť kliknutia pomocou touchpadu</a></span>.</p>
<p class="p">Mnoho aplikácií reaguje na kliknutie stredným tlačidlom.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">Najčastejšia reakcia je vloženie označeného textu. Označíme text, ktorý chceme vložiť niekam inam, presunieme sa na cieľové miesto a stlačíme prostredné tlačidlo myši. Označený text sa vloží na miesto, na ktorom sa nachádza kurzor myši.</p>
<p class="p">Vloženie textu pomocou prostredného tlačidla je úplne nezávislé od schránky. Označený text sa nekopíruje do schránky. Tento rýchly spôsob funguje iba pomocou stredného tlačidla.</p>
</li>
<li class="list"><p class="p">On scrollbars and sliders, a regular click in the empty space moves
  by a set amount (such as one page) in the direction you clicked. You can also
  middle-click in the empty space to move to exactly the location you
  clicked.</p></li>
<li class="list"><p class="p">You can quickly open a new
  window for an application with
 middle-click. Simply
  middle-click on the application's icon, either in
 the <span class="gui">Launcher</span> on the left, or in
  the <span class="gui">Dash</span>.</p></li>
<li class="list"><p class="p">Väčšina webových prehliadačov umožňuje rýchle otváranie odkazov na kartách pomocou stredného tlačidla myši. Stačí kliknúť na odkaz prostredným tlačidlom, a stránka sa otvorí na novej karte. Pri klikaní na odkazy v prehliadači <span class="app">Firefox</span> je potrebné dať si pozor.. Ak v prehliadači <span class="app">Firefox</span> klikneme vedľa odkazu, pokúsi sa načítať označený text ako URL adresu, ako keby sme vložili adresu do poľa Adresa a stlačili kláves <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="list"><p class="p">V správcovi súborov má stredné tlačidlo dve úlohy. Ak klikneme stredným tlačidlom na priečinok, otvorí sa na novej karte - podobne ako pri odkazoch vo webovom prehliadači. Ak klikneme stredným tlačidlom na súbor, súbor sa otvorí - ako keby sme nad ním urobili dvojité kliknutie.</p></li>
</ul></div></div></div>
<p class="p">Niektoré špeciálne aplikácie umožňujú použiť stredné tlačidlo na iné účely. Viac informácií o využití stredného tlačidla, je potrebné hľadať v príručke konkrétnej aplikácie.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="mouse.html#tips" title="Tipy">Mouse tips</a></li>
<li class="links ">
<a href="tips.html" title="Tips &amp; tricks">Tips &amp; tricks</a><span class="desc"> — <span class="link"><a href="tips-specialchars.html" title="Zadanie špeciálnych znakov">Special characters</a></span>, <span class="link"><a href="mouse-middleclick.html" title="Stredné tlačidlo myši">middle click shortcuts</a></span>…</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
