<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Srednji klik</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> › <a class="trail" href="mouse.html#tips" title="Savjeti">Savjeti</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> › <a class="trail" href="mouse.html#tips" title="Savjeti">Savjeti</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="tips.html" title="Savjeti &amp; trikovi">Savjeti &amp;  trikovi</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Srednji klik</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Many mice and some touchpads have a middle mouse button. On a mouse
with a scroll wheel, you can usually press directly down on the scroll
wheel to middle-click. If you don't have a middle mouse button, you
can press the left and right mouse buttons at the same time to
middle-click. If you find you are unable to middle-click this way you 
can try following <span class="link"><a href="https://wiki.ubuntu.com/X/Quirks#A2-button_Mice" title="https://wiki.ubuntu.com/X/Quirks#A2-button_Mice">
these instructions</a></span>.</p>
<p class="p">On touchpads that support multi-finger taps, you can tap with three
fingers at once to middle-click. You have to
<span class="link"><a href="mouse-touchpad-click.html" title="Klikajte, povucite, ili skrolajte pomoću touchpad-a.">enable tap clicking</a></span> in the
touchpad settings for this to work.</p>
<p class="p">Neke aplikacije koriste srednji klik kao napredne prečice.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">Jedna obična kratica je da se zalijepi izabrani tekst. (ovo se nekad naziva obično lijepljenje teksta). izaberete tekst koji želite da zalijepite, zatim oddete gdje želite da zalijepite i pritisnete srednj-klik. Tekst je zalijepljen na poziciji misa.</p>
<p class="p">Ljepljenje teksta sa srednjom tipkom miša je potpuno odvojeno od normalnog međuspremnika. Odabiranjem teksta isti se ne kopira u međuspremnik.  Ovaj brzi način ljepljenja radi samo sa srednjom tipkom miša.</p>
</li>
<li class="list"><p class="p">Na pokretnim trakama i klizačima. obilni klik na preznom prostoru pomjera za određeni iznos (npr jedna strana) u smjeru u kojem ste kliknuli. Možete takođe srednjim-klikom u praznom prostoru doći na lokaciju koju ste kliknuli.</p></li>
<li class="list"><p class="p">Možete brzo otvoriti novi prozor za aplikaciju pomoću srednjeg klika. Jednostavno srednje-klikate na ikonu aplikacije, ili u <span class="gui">Launcher</span>-u ili u <span class="gui">Dash</span></p></li>
<li class="list"><p class="p">Većina web pretraživača dozvoljava da otvarate linkove u tabovima brzo korištenjem srednjeg dugmeta na mišu. kliknite bilo koji link i on će se otvoriti u novom tabu.budite oprezzni klikanjem na <span class="app">Firefox</span> web pretraživaču, U <span class="app">Firefox</span> , ako kliknete srednjim klikom negdje pored linka pokusat će da učita izabraani tekst kao URL, kao da ste koristili srednji klik da zalijepite tekst u adresnu traku i pritusnuli <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="list"><p class="p">U menadžeru datoteka, srednji-klik ima dvije uloge. Ako srednjim klikom kliknete na folder, otvorit ce je u novom prozoru.Ovo oponaša popularne web pretraživače. Ko srednjim klikom kliknete na fajl, otvorit ce fajl kao da ste uradili dvostruki klik na njega.</p></li>
</ul></div></div></div>
<p class="p">Neke specijalne aplikacije dopuštaju da koristite srednju tipku miša za druge funkcije. Traži pomoć u aplikaciji za <span class="em">srednji-klik</span> ili <span class="em">srednja tipka miša</span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="tips.html" title="Savjeti &amp; trikovi">Savjeti &amp;  trikovi</a><span class="desc"> — <span class="link"><a href="tips-specialchars.html" title="Unesite posebne znakove">Specijalni znakovi</a></span>, <span class="link"><a href="mouse-middleclick.html" title="Srednji klik">kratice srednjim klikom</a></span>…</span>
</li>
<li class="links "><a href="mouse.html#tips" title="Savjeti">Savjeti miša</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
