<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Vlastnosti súboru</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Vlastnosti súboru</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">To view information about a file or folder, right-click it and select
  <span class="gui">Properties</span>. You can also select the file and press
  <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Enter</kbd></span></span>.</p>
<p class="p">The file properties window shows you information like the type of file,
  the size of the file, and when you last modified it. If you need this
  information often, you
  can have it displayed in <span class="link"><a href="nautilus-list.html" title="Nastavenia stĺpcov v zozname správcu súborov">list view columns</a></span>
  or <span class="link"><a href="nautilus-display.html#icon-captions" title="Nápisy pri ikonách">icon captions</a></span>.</p>
<p class="p">Informácie, ktoré sa nachádzajú na karte <span class="gui">Základné</span>, sú vysvetlené nižšie. Okrem tejto karty sa v okne nachádzajú aj karty <span class="gui"><span class="link"><a href="nautilus-file-properties-permissions.html" title="Nastavenie oprávnení k súborom">Oprávnenia</a></span></span> a <span class="gui"><span class="link"><a href="files-open.html#default" title="Zmena predvolenej aplikácie">Otvoriť pomocou</a></span></span>. Pri niektorých typoch súborov, ako sú napríklad obrázky a videá, sa v okne môžu nachádzať ďalšie karty, poskytujúce informácie o rozmeroch, trvaní a použitých kodekoch.</p>
</div>
<div id="basic" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Základné vlastnosti</span></h2></div>
<div class="region"><div class="contents"><div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Názov</span></dt>
<dd class="terms"><p class="p">Súbor môžeme premenovať zmenou názvu v tomto poli. Súbor sa dá premenovať aj mimo okna Vlastnosti. Viď <span class="link"><a href="files-rename.html" title="Premenovanie súborov a priečinkov">Premenovanie súborov a priečinkov</a></span>.</p></dd>
<dt class="terms"><span class="gui">Typ</span></dt>
<dd class="terms">
<p class="p">Tento typ pomáha identifikovať typ súboru ako napríklad PDF dokument, OpenDocument Text, alebo obrázok JPEG. Typ súboru (a ďalšie veci) určuje aplikácie, ktoré súbor môže otvoriť. Viac informácií sa nachádza v časti <span class="link"><a href="files-open.html" title="Otvorenie aplikácie inou aplikáciou">Otvorenie aplikácie inou aplikáciou</a></span>.</p>
<p class="p"><span class="em">Typ MIME</span> súboru je zobrazený v zátvorkách. Ide o štandardný spôsob, ktorý počítač používa na odkazovanie na typ súboru.</p>
</dd>
<dt class="terms">Obsah</dt>
<dd class="terms"><p class="p">Toto pole sa zobrazuje keď sa pozeráme na vlastnosti priečinka. Zobrazuje počet položiek v priečinku. Ak priečinok obsahuje iné priečinky, každý vnútorný priečinok sa zaráta ako jedna položka, aj napriek tomu že obsahuje ďalšie položky. Každý súbor sa zaráta ako jedna položka. Ak je priečinok prázdny pole nezobrazí <span class="gui">nič</span>.</p></dd>
<dt class="terms">Veľkosť</dt>
<dd class="terms">
<p class="p">Toto pole sa zobrazuje ak sa pozeráme na inú položku ako je priečinok. Veľkosť udáva, koľko priestoru na disku súbor zaberá. Pomocou tohto údaju tiež vieme, ako dlho sa bude súbor sťahovať alebo odosielať pri posielaní napríklad cez e-mail (posielanie a prijímanie veľkých súborov trvá dlhšie).</p>
<p class="p">Veľkosť môže byť udávaná v jednotkách KB, MB alebo GB. Okrem tejto hodnoty sa v zátvorke nachádza hodnota uvedená v bajtoch. Pričom platí, že 1 KB je 1024 bajtov, 1 MB je 1024 KB atď.</p>
</dd>
<dt class="terms">Umiestnenie</dt>
<dd class="terms"><p class="p">Umiestnenie každého súboru je dané jeho <span class="em">absolútnou cestou</span>. Ide o jedinečnú "adresu" v počítači, zostavenú zo zoznamu priečinkov, do ktorých je potrebné vojsť, ak sa chceme dostať k súboru. Napríklad ak má Juraj súbor s názvom <span class="file">Príbeh.pdf</span> vo svojom domovskom priečinku, jeho umiestnenie bude <span class="file">/home/juraj/Príbeh.pdf</span>.</p></dd>
<dt class="terms">Disk</dt>
<dd class="terms"><p class="p">Súborový systém alebo zariadenie, na ktorom je súbor uložený. Toto zobrazuje médium, na ktorom je súbor ako napríklad pevný disk, optický disk, <span class="link"><a href="nautilus-connect.html" title="Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku">sieťový disk alebo súborový server</a></span>. Pevné disky sa dajú rozdeliť na niekoľko <span class="link"><a href="disk-partitions.html" title="Správa zväzkov a oddielov">diskových oddielov</a></span>, ktoré sa niekedy označujú slovom „zväzok“, pre jednoduchosť je však vo vlastnostiach správcu súborov uvádzané slovo „Disk“.</p></dd>
<dt class="terms">Voľné miesto</dt>
<dd class="terms"><p class="p">Pri priečinkoch sa zobrazuje veľkosť voľného miesta, ktoré zostáva na ukladanie nových súborov na tom disku, na ktorom sa priečinok nachádza. Takto si môžeme overiť, či nie je pevný disk už plný.</p></dd>
<dt class="terms">Použitý</dt>
<dd class="terms"><p class="p">Dátum a čas posledného otvorenia súboru.</p></dd>
<dt class="terms">Zmenený</dt>
<dd class="terms"><p class="p">Dátum a čas poslednej zmeny a uloženia súboru.</p></dd>
</dl></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Vyhľadávanie súborov">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="nautilus-file-properties-permissions.html" title="Nastavenie oprávnení k súborom">Nastavenie oprávnení k súborom</a><span class="desc"> — Nastavenie práv určujúcich kto môže zobraziť a upravovať súbory a priečinky.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
