<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Svojstva datoteke</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Svojstva datoteke</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Za pregled informacija o datoteci ili mapi, desni klik i odaberite <span class="gui">Svojstva</span>. Možete također odabrati datoteku i pritisnuti <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Enter</kbd></span></span>.</p>
<p class="p">Prozor datoteka svojstva pokazuje informacije kao vrsti datoteke, veličina datoteke, a kada to trajati izmjena. Ako vam je potrebna ova informacija često, možete ga prikazati u <span class="link"><a href="nautilus-list.html" title="Postavke listi kolona menadžera datoteka"> prikazu popisa stupaca </a></span> ili <span class="link"><a href="nautilus-display.html#icon-captions" title="Naslovi ikona"> ikona naslove </a></span>.</p>
<p class="p">Podaci dati u kartici <span class="gui">Osnovno</span> su objašnjeni ispod. Pored njega imate takođe i jezičke <span class="gui"><span class="link"><a href="nautilus-file-properties-permissions.html" title="Postavite dozvole za datoteku">Ovlašćenja</a></span></span> i <span class="gui"><span class="link"><a href="files-open.html#default" title="Promjena zadanog programa.">Otvori pomoću</a></span></span>. Za određene vrste datoteka, kao što su slike i snimci, biće prikazana dodatna kartica koja će obezbjeđivati podatke o veličini, trajanju, i kodeku.</p>
</div>
<div id="basic" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Osnovna svojstva</span></h2></div>
<div class="region"><div class="contents"><div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Naziv</span></dt>
<dd class="terms"><p class="p">Možete promijeniti ime datoteke mijenjanjem ovog polja. Možete također promijeniti ime izvan prozora svojstva. Vidi <span class="link"><a href="files-rename.html" title="Preimenujte datoteku ili folder">Preimenujte datoteku ili folder</a></span>.</p></dd>
<dt class="terms"><span class="gui">Vrsta</span></dt>
<dd class="terms">
<p class="p">To vam pomaže identificirati vrstu datoteke, kao što su PDF dokument, OpenDocument Text, ili JPEG slike.Vrsta datoteke određuje koje aplikacije mogu otvoriti datoteku, između ostalog. Na primjer, ne možete otvoriti sliku s glazbenim playerom. Vidi <span class="link"><a href="files-open.html" title="Otvorite datoteke sa drugim aplikacijama">Otvorite datoteke sa drugim aplikacijama</a></span> za više informacija o tome.</p>
<p class="p"><span class="em">MIME vrsta</span> datoteke se pojavljuje u zagradama; MIME vrsta je standardni način koji računar koristi da uputi na vrstu datoteke.</p>
</dd>
<dt class="terms">Sadržaji</dt>
<dd class="terms"><p class="p">Ovo polje prikazuje se ako ste u potrazi na svojstva mape nego u datoteku. To vam pomaže vidjeti broj stavki u mapi. Ako mapa uključuje i druge mape, svaka unutarnja mapa računa se kao jedan predmet, čak i ako ona sadrži daljnje stavke. Svaka datoteka također se računa kao jedan predmet. Ako mapa je prazna, sadržaj će se prikazati <span class="gui"> ništa </span>.</p></dd>
<dt class="terms">Veličina</dt>
<dd class="terms">
<p class="p">Ovo polje prikazuje se ako ste u potrazi na datoteku (ne mapa).Veličina datoteke vam govori koliko prostora na disku zauzima. To je ujedno i pokazatelj koliko dugo će trajati za preuzimanje datoteke ili ga poslati u e-mail (velike datoteke potrajati duže za slanje / primanje).</p>
<p class="p">Veličina može biti u bajtima, KB, MB; ako je slučaj da je nešto od posljednja tri, veličina u bajtima je također data u zagradi. Tehnički, 1 KB je 1024 bajta, 1 MB je 1024 KB itd.</p>
</dd>
<dt class="terms">Lokacija</dt>
<dd class="terms"><p class="p">The location of each file on your computer is given by its <span class="em">absolute path</span>. This is a unique "address" of the file on your computer, made up of a list of the folders that you would need to go into to find the file. For example, if Jim had a file called <span class="file">Resume.pdf</span> in his Home folder, its location would be <span class="file">/home/jim/Resume.pdf</span>.</p></dd>
<dt class="terms">Sadržaj</dt>
<dd class="terms"><p class="p">Datotečni sustav ili uređaj na koji je datoteka pohranjena. To vam pokazuje gdje je datoteka fizički  pohranjena, na primjer, ako je na tvrdi disk ili na CD-u, ili <span class="link"><a href="nautilus-connect.html" title="Pregled datoteka na serveru ili na mreži"> mreže udjela ili poslužitelja </a></span>. Tvrdi disk može se podijeliti u nekoliko <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama"> particije </a></span>, particija će biti prikazana pod <span class="gui"> Volume </span> previše.</p></dd>
<dt class="terms">Slobodan prostor</dt>
<dd class="terms"><p class="p">Ovo je jedino prikazano za mape. Daje iznos prostora na disku koji je dostupan na disku na kojem je mapa. Ovo je korisno za provjeru da li je tvrdi disk pun.</p></dd>
<dt class="terms">Pristupljeno</dt>
<dd class="terms"><p class="p">Datum i vrijeme kada je datoteka posljednji put otvorena.</p></dd>
<dt class="terms">Promijenjeno</dt>
<dd class="terms"><p class="p">Datum i vrijeme kada je datoteka posljednji put izmjenjena i snimljena.</p></dd>
</dl></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Traži datoteke">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="nautilus-file-properties-permissions.html" title="Postavite dozvole za datoteku">Postavite dozvole za datoteku</a><span class="desc"> — Kontrolišite ko može vidjeti i izmjeniti vaše datoteke i foldere.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
