<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pregled datoteka na serveru ili na mreži</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="sharing.html" title="Dijeljenje">Dijeljenje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pregled datoteka na serveru ili na mreži</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete se povezati s poslužiteljem ili mrežnim dijeljenjima za pregledavanje i pregled datoteka na tom poslužitelju, baš kao da su na vašem računaru. To je zgodan način za preuzimanje ili prijenos datoteka na internetu, ili za dijeljenje datoteka s drugim ljudima na lokalnoj mreži.</p>
<p class="p">To browse files over the network, open the <span class="app">Files</span>
application from the <span class="gui">Dash</span>, and click
<span class="gui">Browse Network</span> in the sidebar. The file manager
will find any computers on your local area network that advertise
their ability to serve files. If you want to connect to a server
on the internet, or if you do not see the computer you're looking
for, you can manually connect to a server by typing in its
internet/network address.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Povezivanje sa serverom datoteka</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">U fajl menadžeru, kliknite  <span class="gui">Files</span> u traci menija i izaberite <span class="gui">Connect to Server</span> iz menija aplikacije.</p></li>
<li class="steps">
<p class="p">Unesite adresu servera, u obliku  <span class="link"><a href="#urls" title="Pisanje URL-ova">URL</a></span>. Detalji o podržanim URL-ovima se nalaze na <span class="link"><a href="#types" title="Vrste poslužitelja">listed below</a></span>.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako ste se ranije spajali na server, možete kliknuti na njega na listi <span class="gui">Nedavno korišteni serveri</span></p></div></div></div></div>
</li>
<li class="steps"><p class="p">Click <span class="gui">Connect</span>. A new window will open showing you the
  files on the server. You can browse the files just as you would for those on
  your own computer. The server will also be added to the sidebar so you can
  access it quickly in the future</p></li>
</ol></div>
</div></div>
</div>
<div id="urls" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pisanje URL-ova</span></h2></div>
<div class="region"><div class="contents">
<p class="p"><span class="em">URL</span>, ili <span class="em">uniformni lokator resursa</span>, je oblik adrese koji se odnosi na lokaciju ili datoteku u nekoj mreži. Adresa je ovog formata:</p>
<div class="example"><p class="p"><span class="sys">scheme://imeservera.primjer.com/mapa</span></p></div>
<p class="p"><span class="em">scheme</span> specificira protokol ili tip servera. <span class="em">primjer.com</span> dio adrese se zove <span class="em">ime domene</span>. Ako je potrebno korisničko ime, ubacuje se prije imena servera:</p>
<div class="example"><p class="p"><span class="sys">scheme://korisničkoime@imeservera.primjer.com/mapa</span></p></div>
<p class="p">Neke sheme zahtijevaju da se navede broj porta. Unesite ga nakon imena domene:</p>
<div class="example"><p class="p"><span class="sys">scheme://imeservera.primjer.com:port/mapa</span></p></div>
<p class="p">Ispod su specifični primjeri za razne tipove servera koji su podržani.</p>
</div></div>
</div></div>
<div id="types" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Vrste poslužitelja</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete se povezati na različite tipove servera. Neki serveri su javni, na njih se svako može povezati. Neki drugi serveri zahtijevaju prijavu preko korisničkog imena i lozinke.</p>
<p class="p">Možda nemate dozvole za obavljanje određene radnje o datotekama na serveru. Na primjer, na javnim FTP mjestima, vjerojatno neće moći izbrisati datoteke.</p>
<p class="p">URL koji unesete zavisi od protokola koji server koristi da izveze svoje datoteke.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">SSH</dt>
<dd class="terms">
<p class="p">If you have a <span class="em">secure shell</span> account on a server, you
  can connect using this method. Many web hosts provide SSH accounts
  to members so they can securely upload files. SSH servers always
  require you to log in.</p>
<p class="p">Tipičan SSH URL izgleda ovako:</p>
<div class="example"><p class="p"><span class="sys">ssh://username@servername.example.com/folder</span></p></div>
<p class="p">Kada koristite SSH, svi podaci koje šaljete (uključujući i vašu lozinku) su šifrirani i ostali korisnici na mreži ih ne mogu vidjeti.</p>
</dd>
<dt class="terms">FTP (uz prijavu)</dt>
<dd class="terms">
<p class="p">FTP je popularan način za razmjenu datoteka na internetu. Budući da podaci nisu kriptirani preko FTP, mnogi poslužitelji sada pružaju pristup internetu putem SSH. Neki će poslužitelji, međutim, još uvijek dopustiti ili zahtijevati da koristite FTP za upload ili preuzimanje datoteka. FTP mjesta s prijavama obično će vam omogućiti brisanje i upload datoteka.</p>
<p class="p">Tipičan FTP URL izgleda ovako:</p>
<div class="example"><p class="p"><span class="sys">ftp://korisničkoime@ftp.primjer.com/put/</span></p></div>
</dd>
<dt class="terms">Javni FTP</dt>
<dd class="terms">
<p class="p">Stranice koje vam dozvoljavaju skidanje datoteka će nekada obezbjeđivati javni ili anonimni pristup za FTP.  Ovi serveri ne zahtijevaju korisničko ime i lozinku, i uglavnom vam neće dopustiti da brišete ili postavljate datoteke.</p>
<p class="p">Tipičan anonimni FTP URL izgleda ovako:</p>
<div class="example"><p class="p"><span class="sys">ftp://ftp.primjer.com/put/</span></p></div>
<p class="p">Some anonymous FTP sites require you to log in with a
  public username and password, or with a public username using
  your email address as the password. For these servers, use the
  <span class="gui">FTP (with login)</span> method, and use the credentials
  specified by the FTP site.</p>
</dd>
<dt class="terms">Dijeljeni windows direktoriji</dt>
<dd class="terms">
<p class="p">Windows računari koriste  vlastiti protokol za razmjenu datoteka preko lokalne mreže. Računari na Windows mreži ponekad su grupirani u <span class="em"> domene </span> za organizaciju i za bolju kontrolu pristupa. Ako imate pravo dozvole na udaljenom računalu, možete spojiti na Windows dionici iz file manageru.</p>
<p class="p">Tipičan Windows URL za dijeljenje izgleda ovako:</p>
<div class="example"><p class="p"><span class="sys">smb://imeservera/Share</span></p></div>
</dd>
<dt class="terms">WebDAV i Sigurni WebDAV</dt>
<dd class="terms">
<p class="p">Na temelju HTTP protokola koji se koristi na webu, WebDAV ponekad se koristi za razmjenu datoteka u lokalnoj mreži i spremanje datoteka na internetu. Ako poslužitelj ste povezivanja podržava sigurne veze, trebali biste odabrati ovu opciju. Sigurna WebDAV koristi snažnu SSL enkripcije, kako bi drugi korisnici ne mogu vidjeti svoju lozinku ..</p>
<p class="p">Tipičan WebDAV URL izgleda ovako:</p>
<div class="example"><p class="p"><span class="sys">http://example.hostname.com/path</span></p></div>
</dd>
</dl></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Traži datoteke">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li>
<li class="links ">
<a href="sharing.html" title="Dijeljenje">Dijeljenje</a><span class="desc"> — 
      <span class="link"><a href="sharing-desktop.html" title="Dijelite vaš desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Share files</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files-share.html" title="Dijeli i prebaci datoteke">Dijeli i prebaci datoteke</a><span class="desc"> — Prebacite datoteke svojim email kontaktima iz uređivača datoteka.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
