<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nastavenia stĺpcov v zozname správcu súborov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » <a class="trail" href="nautilus-prefs.html" title="Nastavenia správcu súborov">Nastavenia správcu súborov</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nastavenia stĺpcov v zozname správcu súborov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">There are nine columns of information that you can display in the file manager's list view. Click <span class="gui">Files</span> in the menu bar, pick <span class="gui">Preferences</span> and choose the <span class="gui">List Columns</span> tab to select which columns will be visible.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Pomocou tlačidiel <span class="gui">Presunúť hore</span> a <span class="gui">Presunúť dole</span> môžeme nastaviť poradie, v akom sa označené stĺpce objavia.</p></div></div></div></div>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Názov</span></dt>
<dd class="terms"><p class="p">Názov priečinkov a súborov v priečinku, do ktorého sa pozeráme.</p></dd>
<dt class="terms"><span class="gui">Veľkosť</span></dt>
<dd class="terms"><p class="p">Veľkosť priečinka je udávaná v počte položiek, ktoré sa v ňom nachádzajú. Veľkosť súborov je udávaná v bajtoch, KB alebo MB.</p></dd>
<dt class="terms"><span class="gui">Typ</span></dt>
<dd class="terms"><p class="p">Zobrazuje buď slovo Zložka alebo typ súboru ako napríklad Dokument PDF, Obrázok JPEG, Zvuk MP3 a podobne.</p></dd>
<dt class="terms"><span class="gui">Zmenený</span></dt>
<dd class="terms"><p class="p">Shows when the file was last modified.</p></dd>
<dt class="terms"><span class="gui">Vlastník</span></dt>
<dd class="terms"><p class="p">Meno používateľa, ktorý vlastní priečinok alebo súbor.</p></dd>
<dt class="terms"><span class="gui">Skupina</span></dt>
<dd class="terms"><p class="p">Skupina, ktorá vlastní súbor. Na domácich počítačoch má každý používateľ svoj vlastnú skupinu. V podnikovom prostredí však môžu byť používatelia priradený do skupín podľa oddelení alebo projektov.</p></dd>
<dt class="terms"><span class="gui">Oprávnenia</span></dt>
<dd class="terms">
<p class="p">Zobrazuje oprávnenia k súboru vo formáte <span class="gui">drwxrw-r--</span></p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Prvý znak <span class="gui">d</span> je typ súboru. <span class="gui">-</span> znamená bežný súbor a <span class="gui">d</span> znamená adresár (priečinok).</p></li>
<li class="list"><p class="p">Ďalšie tri znaky <span class="gui">rwx</span> určujú oprávnenia pre používateľa, ktorý vlastní súbor.</p></li>
<li class="list"><p class="p">Ďalšie tri znaky <span class="gui">rw-</span> určujú oprávnenia pre všetkých členov skupiny, ktorá súbor vlastní.</p></li>
<li class="list"><p class="p">Posledné tri znaky v stĺpci <span class="gui">r--</span> určujú oprávnenia pre všetkých ostatných používateľov v systéme.</p></li>
</ul></div></div></div>
<p class="p">Znaky majú nasledujúci význam:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">r : Oprávnenie na čítanie.</p></li>
<li class="list"><p class="p">w : Oprávnenie na zápis.</p></li>
<li class="list"><p class="p">x : Oprávnenie na spustenie súboru alebo na vstup do adresára.</p></li>
<li class="list"><p class="p">- : Bez oprávnenia.</p></li>
</ul></div></div></div>
</dd>
<dt class="terms"><span class="gui">Typ MIME</span></dt>
<dd class="terms"><p class="p">Zobrazuje typ MIME položky.</p></dd>
<dt class="terms"><span class="gui">Umiestnenie</span></dt>
<dd class="terms"><p class="p">Cesta k miestu, kde sa súbor nachádza.</p></dd>
</dl></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="nautilus-prefs.html" title="Nastavenia správcu súborov">Nastavenia správcu súborov</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
