<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Postavke listi kolona menadžera datoteka</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » <a class="trail" href="nautilus-prefs.html" title="Postavke programa za upravljanje datotekama">Postavke programa za upravljanje datotekama</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Postavke listi kolona menadžera datoteka</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">There are nine columns of information that you can display in the file manager's list view. Click <span class="gui">Files</span> in the menu bar, pick <span class="gui">Preferences</span> and choose the <span class="gui">List Columns</span> tab to select which columns will be visible.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Koristite <span class="gui">Pomjeri Gore</span> i <span class="gui">Pomjeri Dolje</span> tipke da izaberete redoslijed kojim će se odabrane kolone pojavljivati.</p></div></div></div></div>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Naziv</span></dt>
<dd class="terms"><p class="p">Prikazuju se imena foldera i datoteka u folderu.</p></dd>
<dt class="terms"><span class="gui">Veličina</span></dt>
<dd class="terms"><p class="p">Veličina mape je data kao broj predmeta sadržanih u mapi. Veličina datoteke je data u bajtima, KB, ili MB.</p></dd>
<dt class="terms"><span class="gui">Vrsta</span></dt>
<dd class="terms"><p class="p">Prikaži kao mapu, ili datoteku kao što je PDF dokument, JPEG slika, MP3 audio, i više.</p></dd>
<dt class="terms"><span class="gui">Promijenjeno</span></dt>
<dd class="terms"><p class="p">Shows when the file was last modified.</p></dd>
<dt class="terms"><span class="gui">Vlasnik</span></dt>
<dd class="terms"><p class="p">Ime korisnika u čijem je vlasništvu datoteka ili folder.</p></dd>
<dt class="terms"><span class="gui">Grupi</span></dt>
<dd class="terms"><p class="p">Skupina datoteka u vlasništvu. Na mojim kućnim računalima, svaki korisnik u svojoj grupi. Grupe ponekad se koristi u korporativnim okruženjima, gdje korisnici mogu biti u skupinama prema odjelu ili projektu.</p></dd>
<dt class="terms"><span class="gui">Dozvole</span></dt>
<dd class="terms">
<p class="p">Prikaži pravo pristupa datoteci, na primjer <span class="gui">drwxrw-r--</span></p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Prvi znak <span class="gui">-</span> označava vrstu datoteke.  <span class="gui">-</span> označava pravilnu datoteku, a <span class="gui">d</span> označava direktorij (folder).</p></li>
<li class="list"><p class="p">Naredna tri znaka <span class="gui">rwx</span> određuju dozvole za korisnika koji posjeduje datoteku.</p></li>
<li class="list"><p class="p">Naredna tri znaka <span class="gui">rw-</span> određuju dozvole za sve članove grupe koja posjeduje datoteku.</p></li>
<li class="list"><p class="p">Posljednja tri znaka u koloni  <span class="gui">r--</span> određuju dozvole za sve korisnike sistema.</p></li>
</ul></div></div></div>
<p class="p">Svaki znak ima sljedeće značenje:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">r : Pravo čitanja.</p></li>
<li class="list"><p class="p">w : Pravo pisanja.</p></li>
<li class="list"><p class="p">x : Pravo izvršenja</p></li>
<li class="list"><p class="p">- : Bez dozvole</p></li>
</ul></div></div></div>
</dd>
<dt class="terms"><span class="gui">MIME tip</span></dt>
<dd class="terms"><p class="p">Prikaži MIME vrstu stavke.</p></dd>
<dt class="terms"><span class="gui">Lokacija</span></dt>
<dd class="terms"><p class="p">Put do lokacije datoteke.</p></dd>
</dl></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="nautilus-prefs.html" title="Postavke programa za upravljanje datotekama">Postavke programa za upravljanje datotekama</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
