<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nastavenie oprávnení k súborom</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> › <a class="trail" href="files.html#faq" title="Tipy a otázky">Tipy a otázky</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nastavenie oprávnení k súborom</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can use file permissions to control who can view and edit files that
  you own. To view and set the permissions for a file, right click it and
  select <span class="gui">Properties</span>, then select the <span class="gui">Permissions</span> tab.</p>
<p class="p">Viac podrobností typoch práv, ktoré je možné nastaviť, sa nachádza nižšie v častiach <span class="link"><a href="#files" title="Súbory">Súbory</a></span> a <span class="link"><a href="#folders" title="Priečinky">Priečinky</a></span>.</p>
</div>
<div id="files" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Súbory</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Oprávnenia je možné nastavovať pre vlastníka súboru, vlastniacu skupinu a všetkých ostatných používateľov systému. Pre naše vlastné súbory sme my ich vlastníkom, a môžeme sami sebe nastaviť právo iba na čítanie alebo na čítanie aj zápis. Ak nechceme aby sme súbor omylom mohli zmeniť, nastavíme si oprávnenie iba na čítanie.</p>
<p class="p">Každý používateľ na našom počítači patrí do nejakej skupiny používateľov. Na domácich počítačoch je bežné, že každý používateľ má svoju vlastnú skupinu a oprávnenia pre skupinu sa často nevyužívajú. V podnikovom prostredí sa skupiny niekedy využívajú pre jednotlivé oddelenia alebo projekty. V takom prípade každý súbor vlastní nejaká skupina a my môžeme pomocou oprávnení skupiny nastaviť, aké oprávnenia budú mať všetci používatelia patriaci do skupiny. Môžeme však meniť iba oprávnenia pre skupinu, do ktorej sami patríme.</p>
<p class="p">Pre ostatných používateľov, ktorí nie sú vlastníkmi súboru a nepatria do našej skupiny môžeme nastaviť oprávnenia tiež.</p>
<p class="p">Ak je súbor program ako napríklad skript, je potrebné zaškrtnúť voľbu <span class="gui">Povoliť spustenie súboru ako programu</span>, aby súbor bolo možné spustiť. Aj napriek tejto voľbe však správca súborov môže súbor otvárať v predvolenej aplikácii alebo sa spýta čo má urobiť. Viac informácií sa nachádza v časti <span class="link"><a href="nautilus-behavior.html#executable" title="Spustiteľné textové súbory">Spustiteľné textové súbory</a></span>.</p>
</div></div>
</div></div>
<div id="folders" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Priečinky</span></h2></div>
<div class="region"><div class="contents">
<p class="p">K priečinkom je možné nastaviť oprávnenia pre vlastníka, skupinu a ostatných používateľov. Informácie o tom, čo je vlastník, skupina a ostatní používatelia sa nachádza v časti o oprávneniach k súborom.</p>
<p class="p">Oprávnenia, ktoré sa dajú nastaviť pri priečinkoch, sú iné ako oprávnenia k súborom.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Žiadne</span></dt>
<dd class="terms"><p class="p">Používateľ nebude mať možnosť vidieť aké súbory sú v priečinku.</p></dd>
<dt class="terms"><span class="gui">Iba zobrazenie súborov</span></dt>
<dd class="terms"><p class="p">Používateľ bude môcť vidieť súbory, ktoré sú v priečinku, no nebude ich môcť otvoriť, vytvárať ani odstraňovať.</p></dd>
<dt class="terms"><span class="gui">Prístup k súborom</span></dt>
<dd class="terms"><p class="p">Používateľ bude môcť otvoriť súbory v priečinku (za predpokladu, že mu to umožňuje oprávnenie k danému súboru), no nebude môcť vytvárať nové súbory ani odstraňovať súbory.</p></dd>
<dt class="terms"><span class="gui">Vytváranie a odstraňovanie súborov</span></dt>
<dd class="terms"><p class="p">The user will have full access to the folder, including
        opening, creating, and deleting files.</p></dd>
</dl></div></div></div>
<p class="p">You can also quickly set the file permissions for all the files
    in the folder by clicking <span class="gui">Change Permissions for Enclosed Files</span>.
    Use the drop-down lists to adjust the permissions of contained files or
    folders, and click <span class="gui">Change</span>. Permissions are applied to files and
    folders in subfolders as well, to any depth.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Tipy a otázky">Tipy a otázky</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="nautilus-file-properties-basic.html" title="Vlastnosti súboru">Vlastnosti súboru</a><span class="desc"> — Zobrazenie základných informácií o súbore, nastavenie oprávnení a voľba predvolenej aplikácie.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
