<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Internet izgleda sporo.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Internet izgleda sporo.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako koristite internet i on izgleda sporo,postoji nekoliko stvari koje bi mogle biti razlog usporenja.</p>
<p class="p">Pokušajte zatvoriti web pretraživač i ponovo ga pokrenuti,i diskonektovati i ponovo se konektovati. ( Pri tome mnoge druge stvari mogu biti uzrok usporenja interneta. )</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p"><span class="em-bold em">Zauzeto doba dana</span></p>
<p class="p">Internet davatelji usluga obično postavljanje internetske veze, tako da oni dijele između nekoliko domaćinstava. Iako se povežete odvojeno, kroz svoju telefonsku liniju ili kabelsku vezu, veza s ostatkom interneta na telefonskoj centrali zapravo može biti zajednička. Ako je to slučaj i puno svojih susjeda koriste internet u isto vrijeme kao i vi, možda ćete primijetiti usporavanje. Vi ste vjerojatno da doživite to u vrijeme kada vaši susjedi su vjerojatno na internetu (u večernjim satima, na primjer).</p>
</li>
<li class="list">
<p class="p"><span class="em-bold em">Preuzimanje više stvari odjednom</span></p>
<p class="p">Ako Vi ili neko drugi putem Vaše internet veze preuzima nekoliko datoteka odjednom, ili gledate video, internet veza možda neće biti dovoljno brza kako bi išla ukorak s potražnjom. U ovom slučaju, osjetit ćete usporenje.</p>
</li>
<li class="list">
<p class="p"><span class="em-bold em">Nepouzdana konekcija</span></p>
<p class="p">Neke internet veze,su nepouzdane, naročito one privremene ili one u velikim područjima potražnje. Ako ste u prometnom kafiću ili konferencijskom centru, internetska veza može biti previše zauzeta ili jednostavno nepouzdana.</p>
</li>
<li class="list">
<p class="p"><span class="em-bold em">Slab signal bežične konekcije</span></p>
<p class="p">Ako ste spojeni na internet preko wireless-a (wifi),  provjerite postavke mreže na traci izbornika da vidite da li imate dobar wireless signal. Internet može biti spor jer nemate veoma jak signal.</p>
</li>
<li class="list">
<p class="p"><span class="em-bold em">Korištenje sporije mobilne internet konekcije</span></p>
<p class="p">Ako imate mobilnu internet vezu i uočite da je spora, možda ste se  preselili u područje gdje je prijem loš. Kada se to dogodi, internet veza će se automatski prebaciti sa brze "mobilne širokopojasne" veze kao što je 3G u više pouzdanu, ali sporiju, kao što su GPRS veza.</p>
</li>
<li class="list">
<p class="p"><span class="em-bold em">Web pretraživač ima problem</span></p>
<p class="p">Ponekad web preglednici naiđu na problem koji ih čini sporim. To bi mogao biti bilo koji broj razloga - mogli ste posjetili web stranice koje preglednik borili za učitavanje, ili ste možda imali preglednik otvoren za dugo vremena, na primjer. Pokušajte zatvoriti sve prozore preglednika, a zatim otvaranjem preglednik opet vidjeti ako se to čini razliku.</p>
</li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Troubleshooting wireless connections</a></span>,
      <span class="link"><a href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi.">finding your wifi network</a></span>…
        </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
