<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Šta je MAC adresa?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Šta je MAC adresa?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">A <span class="em">MAC address</span> is the unique identifier that is assigned by the manufacturer to a piece of network hardware (like a wireless card or an Ethernet card). MAC stands for <span class="em">Media Access Control</span>, and each identifier is intended to be unique to a particular device.</p>
<p class="p">MAC adresa se ​​sastoji od šest kompleta od dva znaka, odvojenih dvotočkom. <span class="code"> 00:01 B: 44:11:3: B7 </span> je primjer MAC adrese.</p>
<p class="p">Da biste identificirali MAC adresu Vašeg mreženog hardvera :</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui">mreža meni</span> na traci menija.</p></li>
<li class="steps"><p class="p">Izaberite <span class="gui">Informacije o konekciji</span>.</p></li>
<li class="steps"><p class="p">Vaša MAC adresa će biti prikazana kao <span class="gui">Hardverska adresa</span>.</p></li>
</ol></div></div></div>
<p class="p">In practice, you may need to <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">modify or "spoof" a MAC address</a></span>. For example, some internet service providers may require that a specific MAC address be used to access their service. If the network card stops working, and you need to swap a new card in, the service won't work anymore. In such cases, you would need to spoof the MAC address.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a><span class="desc"> — <span class="link"><a href="net-findip.html" title="Nađite Vašu IP adresu">Pronađite vašu IP adresu</a></span>, <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">WEP &amp; WPA sigurnost</a></span>, <span class="link"><a href="net-macaddress.html" title="Šta je MAC adresa?">MAC adrese</a></span>, <span class="link"><a href="net-proxy.html" title="Definišite postavke ovlaštenja">proxies</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
