<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ako môžem používať Skype v Ubuntu?</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="net.html" title="Networking, web, email &amp; chat">Networking, web, email &amp; chat</a> » <a class="trail" href="net-chat.html" title="Chat &amp; Social Networking">Chat &amp; Social Networking</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ako môžem používať Skype v Ubuntu?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="app">Skype</span> je autorizovaný softvér ktorý umožnuje volať cez internet pomocou vášho počítača.</p>
<p class="p">Skype využíva decentralizovanú peer-to-peer technológiu, takže hovory neprechádzajú centrálnym serverom, ale prostredníctvom distribuovaných serverov a ďalších užívateľov.</p>
<p class="p">Skype softvér je zadarmo ale nie je to slobodný softvér; zdrojový kód je proprietárny a nie je k dispozícii pre úpravy.</p>
<p class="p">Skype nie je nainštalovaný v predvolenom nastavení Ubuntu. <span class="link"><a href="https://apps.ubuntu.com/cat/applications/skype" title="https://apps.ubuntu.com/cat/applications/skype">Inštalácia <span class="em">skype</span> balíčkov</a></span> k aplikácii.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">
    You need to <span class="link"><a href="addremove-sources.html#canonical-partner" title="Aktivácia úložiska partnerov spoločnosti Canonical">activate
    the Canonical Partner Repository</a></span> to install <span class="app">Skype</span>
  </p></div></div></div></div>
<div class="list"><div class="inner">
<div class="title title-list"><h2><span class="title">Daľšie zdroje na pomoc so <span class="app">Skype</span></span></h2></div>
<div class="region"><ul class="list">
<li class="list"><p class="p">
      <span class="link"><a href="https://help.ubuntu.com/community/SkypeRecordingHowto" title="https://help.ubuntu.com/community/SkypeRecordingHowto">
      How to record Skype conversations
      </a></span>
    </p></li>
<li class="list"><p class="p">
      <span class="link"><a href="https://wiki.ubuntu.com/SkypeWebCams" title="https://wiki.ubuntu.com/SkypeWebCams">
      A list of webcams which are compatible with Skype
      </a></span>
    </p></li>
<li class="list"><p class="p">
      <span class="link"><a href="https://help.ubuntu.com/community/SkypeTroubleshooting" title="https://help.ubuntu.com/community/SkypeTroubleshooting">
      Troubleshooting Skype - for advanced users
      </a></span>
    </p></li>
</ul></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-chat.html" title="Chat &amp; Social Networking">Chat &amp; Social Networking</a><span class="desc"> — 
      <span class="link"><a href="net-chat-empathy.html" title="Okamžité zasielanie správ v Ubuntu">Chat on any network using <span class="app">Empathy</span></a></span>,
      <span class="link"><a href="net-chat-video.html" title="Video hovory">make video calls</a></span>,
      <span class="link"><a href="net-chat-skype.html" title="Ako môžem používať Skype v Ubuntu?">install skype</a></span>,
      <span class="link"><a href="net-chat-social.html" title="Sociálne siete na pracovnej ploche">social networking apps</a></span>
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-chat-video.html" title="Video hovory">Video hovory</a><span class="desc"> — Aké aplikácie môžem použiť pre video hovory?</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
