<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Rješavanje problema bežične konekcije</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » <a class="trail" href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="net-wireless-troubleshooting-hardware-info.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Prethodni</a><a class="nextlinks-next" href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Sljedeći</a>
</div>
<div class="hgroup">
<h1 class="title"><span class="title">Rješavanje problema bežične konekcije</span></h1>
<h2 class="subtitle"><span class="subtitle">Provjerite da li je bežični adapter prepozat</span></h2>
</div>
<div class="region">
<div class="contents">
<p class="p">Iako je bezicni adapter spojen na racunar, mozda nije prepoznat kao mrezni uredjaj. U ovom koraku ce te provjeriti da li je uredjaj prepoznat ispravno.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite Terminal prozor, unesite <span class="cmd">sudo lshw -C network</span> i pritisnite <span class="key"><kbd>Enter</kbd></span>. Ako ovo daje poruku upozorenja, trebate instalirati <span class="app">lshw</span> program na vašem računaru ako ukucate <span class="cmd">sudo apt-get install lshw</span>  u terminal.</p></li>
<li class="steps">
<p class="p">Pogledaj informaciju koja se pojavila i pronadji  <span class="em">Wireless interface</span> dio. Ako je bezicni adapter pronadjen ispravno, trebali bi vidjeti nesto slicno( ne isto) ovome:</p>
<div class="code"><pre class="contents ">*-mreža
       description: Wireless interface
       proizvod: PRO/Wireless 3945ABG [Golan] Network Connection
       proizvođač: Intel Corporation</pre></div>
</li>
<li class="steps">
<p class="p">Ako je bezicni uredjaj na listi, nastavite na  <span class="link"><a href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Device Drivers step</a></span>.</p>
<p class="p">Ako bezicni uredjaj  <span class="em">nije</span> ucitan, slijedeci koraci koje poduzmete ovise o tipu uredjaja koji koristite.Pogledajte koje tipove bezicnih uredjaja vas racunar posjeduje (<span class="link"><a href="#pci" title="PCI (interni) bežični adapter">internal PCI</a></span>, <span class="link"><a href="#usb" title="USB bežični adapter">USB</a></span>, or <span class="link"><a href="#pcmcia" title="Provjera PCMCIA uređaja">PCMCIA</a></span>).</p>
</li>
</ol></div></div></div>
</div>
<div id="pci" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">PCI (interni) bežični adapter</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Interni PCI adapteri su najcesci, nalaze se u vecini laptopa napravljenih do unazad par godina.Da provjerite da li je vas PSI adapter prepoznat:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite Terminal, ukucajte  <span class="cmd">lspci</span> i pritisnite <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps">
<p class="p">Pogledajte na listi uredjaja da li cete pronaci neke koji su oznaceni kao <span class="code">Network controller</span> ili <span class="code">Ethernet controller</span>. Nekoliko uredjaja moze biti oznaceno na ovaj nacinu, onaj koji bi mogao odgovarati vasem bezicnom adapteru mozda ukljucuje rijeci tipa <span class="code">wireless</span>, <span class="code">WLAN</span>, <span class="code">wifi</span> ili <span class="code">802.11</span>. Ovdje je primjer kako bi to moglo izgledati:</p>
<div class="code"><pre class="contents ">Kontrolor mreže: Intel Corporation PRO/Wireless 3945ABG [Golan] Mrežna Konekcija</pre></div>
</li>
<li class="steps"><p class="p">Ako ste pronasli vas bezicni adapter na listi, nastavite na <span class="link"><a href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Device Drivers step</a></span>. Ako niste pronasli nista vezano za vas bezicni adapter pogledajte <span class="link"><a href="#not-recognized" title="Bežični adapter nije prepoznat">the instructions below</a></span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="usb" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">USB bežični adapter</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Bezicni adapteri koji se spajaju preko USB porta su rijedi. Oni se mogu spojiti direktno na USB port, ili se mogu spojiti preko USB kabla. 3G/mobilni adapteri izgledaju slicno kao bezicni (wifi) adapteri, tako mislite da imate USB bezicni adapter, provjerite da to nije 3G adapter. Da provjerite da li je vas USB adapter prepoznat:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite Terminal, ukucajte <span class="cmd">lsusb</span> i pritisnite <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps">
<p class="p">Pogledajte prikazanu listu uredjaja da nadjete neki koji izgleda kao bezicni ili mrezni uredjaj. Onaj koji odgovara vasem bezicnom adapteru moze sadrzavati rijeci poput <span class="code">wireless</span>, <span class="code">WLAN</span>, <span class="code">wifi</span> or <span class="code">802.11</span>. ovdje je primjer kako moze unos izgledati.</p>
<div class="code"><pre class="contents ">Bus 005 Device 009: ID 12d1:140b Huawei Technologies Co., Ltd. EC1260 Wireless Data Modem HSD USB Card</pre></div>
</li>
<li class="steps"><p class="p">Ako ste pronasli vas bezicni adapter na listi, nastavite na <span class="link"><a href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Device Drivers step</a></span>. Ako niste pronasli nista vezano za vas bezicni adapter pogledajte <span class="link"><a href="#not-recognized" title="Bežični adapter nije prepoznat">the instructions below</a></span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="pcmcia" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjera PCMCIA uređaja</span></h2></div>
<div class="region"><div class="contents">
<p class="p">PCMCIA bezicni adapteri su tipcno pravougaone kartice koje se stavljaju u vas laptop sa strane. Cesce se pronalaze na starim racunarima. Da provjerite da li je vas PCMCIA adapter prepoznat:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Pokrente svoj računar <span class="em">bez</span> uključivanja bežičnog adaptera</p></li>
<li class="steps">
<p class="p">Otvorite Terminal i ukucajte sljedeće, zatim pritisnite <span class="key"><kbd>Enter</kbd></span>:</p>
<div class="code"><pre class="contents ">tail -f /var/log/dmesg</pre></div>
<p class="p">Ovo će prikazati spisak poruka povezanih sa vašim računarskim hardverom, i automatski obnoviti ako se nešto promijenilo sa vašim hardverom.</p>
</li>
<li class="steps"><p class="p">Umetnite vas bezicni adapter u vas PCMCIA slot i pogledajte sta se je promijenilo u prozoru. Promjene bi trebale ukljuciti informacije o vasem bezicnom adapteru. Pogledajte da vidite mozete li prepoznati .</p></li>
<li class="steps"><p class="p">Da zaustavite pokrenutu komandu u Terminalu, pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>C</kbd></span></span>. Nakon što to uradite, možete zatvoriti Terminal, ako želite.</p></li>
<li class="steps"><p class="p">Ako pronadjete bilo kakvu informaciju o vasem bezicnom adapteru, nastavite na <span class="link"><a href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Device Drivers step</a></span>. a ako ne pronadjete nista pogledajte <span class="link"><a href="#not-recognized" title="Bežični adapter nije prepoznat"> instrukcije ispod </a></span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="not-recognized" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Bežični adapter nije prepoznat</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako vaš bežični adapter nije prepoznat, možda on ne radi ispravno ili za njega nisu instalirani odgovarajući drajveri.</p>
<p class="p">Da dobijete pomoc, pogledajte opcije podrske na web stranici distributera. Ovo moze ukljucivati liste mailova i razgovora gdje mozete postavljati pitanja vezana za vas bezicni adapter.</p>
</div></div>
</div></div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="net-wireless-troubleshooting-hardware-info.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Prethodni</a><a class="nextlinks-next" href="net-wireless-troubleshooting-device-drivers.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Sljedeći</a>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a><span class="desc"> — Identifikujte i riješite probleme sa bežičnim povezivanjima</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
