<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Omogućite ili blokirajte pristup protupožarnom zidu</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Omogućite ili blokirajte pristup protupožarnom zidu</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ubuntu dolazi opremljen s <span class="app"> Uncomplicated Firewal</span> (<span class="app"> ufw </span>), ali taj firewall (zaštitna barijera) nije omogućen u standardnoj postavci. Budući da Ubuntu nema otvorene mrežne usluge (osim za osnovne mrežne infrastrukture) u zadanoj instalaciji, firewall nije potreban da bi blokirao pokušaj dolaska zlonamjerne veze.</p>
<p class="p">Za više informacija o tome kako koristiti utw,vidite <span class="link"><a href="https://wiki.ubuntu.com/UncomplicatedFirewall" title="https://wiki.ubuntu.com/UncomplicatedFirewall">dokumentaciju na mreži</a></span>.</p>
</div>
<div id="ufw-enable" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Uključiti ili isključiti firewall</span></h2></div>
<div class="region"><div class="contents"><p class="p">Da biste uključili firewall ukucajte <span class="cmd">sudo ufw enable</span> u terminalu.Da biste isključili ufw,ukucajte <span class="cmd">sudo ufw disable</span>.</p></div></div>
</div></div>
<div id="ufw-filter" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Dopustite ili blokirajte specifične mrežne aktivnosti</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Mnogi programi su napravljeni da bi ponuditi usluge mreže. Na primjer, možete dijeliti sadržaj, ili pustiti da neko vidi Vaš desktop na daljinu. Ovisno o tome koje dodatne programa instalirate, možda ćete morati prilagoditi firewall kako bi se omogućilo tim uslugama da rade onako kako smo zamislili. UfW dolazi s nekoliko pravila već pre-konfiguriran. Na primjer, kako bi se omogućilo <span class="app"> SSH </span> veze, unesite <span class="cmd"> sudo ufw allow ssh </span> u terminal. Da biste blokirali ssh, unesite <span class="cmd"> sudo ufw block ssh </span>.</p>
<p class="p">Svaki program koji podrćava servise koristi određeni <span class="em">mrežni port</span>.Da biste omogućili pristup toj usluzi programa, možda ćete morati dopustiti pristup svom dodjeljenom portu na firewallu.</p>
<p class="p">Da biste provjerili trenutni status ufw-a,ukucajte <span class="cmd">sudo ufw status</span> u terminalu</p>
</div></div>
</div></div>
<div id="gufw" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Koristite ufw bez terminala</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Također možete instalirati <span class="app">gufw</span> ako preferirate korištenje firewall bez korištenja terminala.Da instalirate,kliknite <span class="link"><a href="https://apps.ubuntu.com/cat/applications/gufw" title="https://apps.ubuntu.com/cat/applications/gufw">this link</a></span>.</p>
<p class="p">Možete pokrenuti ovaj program traženjem  <span class="app">Konfiguracija firewalla</span> u <span class="gui">Dash</span>. Program ne mora biti otvoren dok firewall radi</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a><span class="desc"> — <span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Antivirus softver</a></span>, <span class="link"><a href="net-firewall-on-off.html" title="Omogućite ili blokirajte pristup protupožarnom zidu">osnovni protupožarni zidovi</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-firewall-ports.html" title="Često korišteni mrežni portovi">Često korišteni mrežni portovi</a><span class="desc"> — Morate navesti ispravan mrežni port koji želite omogućiti / onemogućiti pristup mreži za program s Vašeg firewall-a</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
