<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Povežite se na bežičnu mrežu.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Povežite se na bežičnu mrežu.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako Vaš računar podržava bežično povezivanje, možete se povezati na bežičnu mrežu koja je unutar raspona kako biste dobili pristup internetu, pogledali zajedničke datoteke na mreži, i tako dalje.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Ako imate bežični uređaj priključen na računar,provjerite da li je uključen.</p></li>
<li class="steps">
<p class="p">Kliknite <span class="gui">mreža meni</span> u <span class="gui">traci menija</span>, i kliknite ime mreže na koju se želite povezati.</p>
<p class="p">Ako ime mreze nije na listi, izaberite  <span class="gui">More Networks</span> da vidite da li je mreza nize na listi. Ako i dalje ne vidite mrezu mozda ste izvan dometa mreze <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu"> mozda je sakrivena </a></span>.</p>
</li>
<li class="steps">
<p class="p">Ako je mreža osigurana šifrom ( <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">ključ za šifriranje</a></span>),ukucajte šifru kada se bude tražilo i kliknite <span class="gui">Poveži</span>.</p>
<p class="p">Ako ne znate ključ, može biti napisan na donjoj strani bežičnog usmjerivača ili na baznoj stanici, u njihovom uputstvu za uptrebu, ili možda morate pitati osobu koja upravlja bežičnom mrežom.</p>
</li>
<li class="steps"><p class="p">Mrežna ikona će promijeniti svoj izgled dok se računar pokušava povezati na internet.</p></li>
<li class="steps"><p class="p">Ako je povezivanje uspješno, ikona će se promijeniti na tačku s nekoliko barova iznad nje. Više barova pokazuje jaču vezu s mrežom. Ako nema mnogo barova, veza je slaba i ne može biti vrlo pouzdana.</p></li>
</ol></div></div></div>
<p class="p">If the connection is not successful, you <span class="link"><a href="net-wireless-noconnection.html" title="Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati">may be asked for your password again</a></span> or it might just tell you that the connection has been disconnected. There are a number of things that could have caused this to happen. You could have entered the wrong password, the wireless signal could be too weak, or your computer's wireless card might have a problem, for example. See <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a></span> for more help.</p>
<p class="p">Jače povezivanje s bežičnom mrežom ne znači da ćete imati bržu internet vezu, ili da ćete moći brže skidati podatke.Bežično povezivanje povezuje računare na uređaj koji pruža <span class="em"> internet priključak </span> (kao usmjerivač ili modem), ali dvije veze su zapravo različite, i tako će se izvoditi na različitim brzinama.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to wifi</a></span>, <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>, <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">Edit connection settings</a></span>, <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a><span class="desc"> — Identifikujte i riješite probleme sa bežičnim povezivanjima</span>
</li>
<li class="links ">
<a href="net-wireless-noconnection.html" title="Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati">Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati</a><span class="desc"> — Dobro provjerite lozinku, pokušajte koristiti brojčanu lozinku umjesto lozinke, isključite pa uključite bežičnu karticu...</span>
</li>
<li class="links ">
<a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Zašto je moja bežična mreža odspojena?</a><span class="desc"> — Možete imati slab signal,ili Vam mreža ne dozvoljava da se povežete ispravno.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
