<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako ste sigurn ida ste ukucali  <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">bežičnu lozinku</a></span> ali se i dalje ne možete uspješno konektovati na bežičnu mrežu,pokušajte nešto od sljedećeg :</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">Dva puta provjerite da imate ispravnu šifru</p>
<p class="p">Šifre su osjetljive na velika i mala slova (važno je da li šifra sadrži mala ili velika slova),dakle provjerite da li ste ukucali pogrešno neko slovo</p>
</li>
<li class="list">
<p class="p">Pokušajte heksadecimalnu ili ASCII šifru</p>
<p class="p">Lozinka koju ste unijli može takođe biti predstavljena na drugačiji način — kao niska heksadecimalnih znakova (brojevi 0-9 i slova a-f) zvanih propusni ključ. Svaka lozinka ima odgovarajući propusni ključ. Ako imate pristup propusnom ključu kao i lozinci/propusnoj reči, pokušajte umesto toga da upišete propusni ključ. Uverite se da ste izabrali tačnu opciju <span class="gui">bežične bezbednosti</span> kada vam bude zatražena vaša lozinka (na primjer, izaberite <span class="gui">VEP 40/128-bitni ključ</span> ako upisujete 40 znakova propusnog ključa za VEP-šifrovanu vezu).</p>
</li>
<li class="list">
<p class="p">Pokušajte sa uključivanjem i isključivanjem Vaše bežične karte.</p>
<p class="p">Ponekad bežične kartice mogu zaglaviti ili doživjeti manji problem što znači da se neće spojiti. Pokušajte isključiti i ponovi uključiti karticu - vidite <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a></span> za više informacija.</p>
</li>
<li class="list">
<p class="p">Provjerite da li koristite ispravan tip bežične sigurnosti.</p>
<p class="p">Kada se pojavi upit za bežičnu sigurnosnu šifru, možete odabrati koji tip bežične sigurnosti koristiti. Provjerite jeste li odabrali onu koja se koristi u usmjerivač ili bežične bazne stanice. Ovo bi trebalo biti odabrano prema zadanim postavkama, ali ponekad to neće biti iz nekog razloga. Ako ne znate koja je to, koristite pokušaj i pogrešaku za prolaz kroz različite opcije.</p>
</li>
<li class="list">
<p class="p">Provjerite da li je Vaša bežična karta regularno podržana</p>
<p class="p">Neke bežične karte nisu podržane najbolje. Pojavljuju se kao bežične konekcije,ali  se one ne mogu konektovati na mrežu jer njhovi drajveri imaju nedostatak sposobnosti za konekciju. Vidite da li možete dobiti alternativni bežični drajver, ili da li trebate uraditi neko ekstra podešavanje ( kao sto je instaliranje različitog <span class="em">firmware</span> ). Vidite <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a></span> za više informacija.</p>
</li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to wifi</a></span>, <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>, <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">Edit connection settings</a></span>, <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Povežite se na bežičnu mrežu.</a><span class="desc"> — Uđite na internet-bežično.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
