<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Da li mi treba anti-virusni softver?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Da li mi treba anti-virusni softver?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako koristite Windows ili Mac OS, vjerovatno morate imati pokrenut anti-virus cijelo vrijeme. Anti-virus je pokrenut u pozadini, konstantno provjeravajući kompjuterske viruse koji možda mogu pronaći put do vašeg računara i izazvati probleme.</p>
<p class="p">Anti-virus postoji i za Linux, ali vjerovatno ga nećete morati koristit. Virusi koji napadaju Linux su veoma rijetki. Neki tvrde da je to zato što se Linux ne koristi široko kao drugi operativni sistemi, dakle niko ne piše viruse za Linux. Drugi argumenti su da je Linux istinski sigurniji, i sigurnosni problemi koje virusi mogu napraviti se veoma brzo ispravljaju.</p>
<p class="p">Sta god da je razlog,Linux virusi su jako rijetki tako da stvarn one trebate sada brinuti o njima.</p>
<p class="p">If you want to be extra-safe, or if you want to check for viruses in files that you are passing between yourself
and people using Windows and Mac OS, you can still install anti-virus software. Check in <span class="app">Ubuntu Software</span>
where a number of applications are available.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a><span class="desc"> — <span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Antivirus softver</a></span>, <span class="link"><a href="net-firewall-on-off.html" title="Omogućite ili blokirajte pristup protupožarnom zidu">osnovni protupožarni zidovi</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-email-virus.html" title="Da li trebam skenirati svoje mailove od virusa?">Da li trebam skenirati svoje mailove od virusa?</a><span class="desc"> — Virusi vjerovatno neće zaraziti vaš računar, ali bi mogli zaraziti računare ljudi kojima šaljete e-mail.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
