<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ručno postavljanje mrežnih postavki</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ručno postavljanje mrežnih postavki</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako vaša mreža ne dodjeljuje postavke vašem računaru automatski, vjerovatno ćete ih morati unijeti sami. Ova tema pretpostavlja da već znate ispravne postavke za korištenje. Ako ne znate, morat ćete pitati administratora mreže ili pogledati postavke rutera ili mrežnog preklopnika.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Za ručno postavljanje mrežnih postavki:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na <span class="gui">mreža meni</span> na traci menija i kliknite <span class="gui">Uređuj konekcije</span>.</p></li>
<li class="steps"><p class="p">Odaberite mrežnu konekciju koju želite postaviti ručno. Na primjer, ako ste priključeni na mrežu sa kablom, pogledajte <span class="gui">Žičani</span> tab.</p></li>
<li class="steps"><p class="p">Kliknite na vezu koju želite urediti i izaberite je, onda kliknite na <span class="gui">Izmijeni</span>.</p></li>
<li class="steps"><p class="p">Idite na <span class="gui">IPv4 postavke</span> katricu i promijenite <span class="gui">Metod</span> u <span class="gui">Ručni</span>.</p></li>
<li class="steps">
<p class="p">Kliknite <span class="gui">Dodaj</span> i unesite <span class="em">IP adresu </span> ,<span class="em"> masku mreže</span> i <span class="em"> zadanu gateway IP adresu</span> u odgovarajuću kolonu u <span class="gui">Adrese</span> listi. Pritisnite <span class="key"><kbd>Enter</kbd></span> ili <span class="key"><kbd>Tab</kbd></span> nakon unosa svake adrese.</p>
<p class="p">Ove tri adrese moraju biti IP adrese. To jest,  moraju biti četiri broja odvojena tačkama (npr. 123.45.6.78).</p>
</li>
<li class="steps"><p class="p">Ukucajte IP adrese DNS servera koje želite koristiti,razdvojite ih zarezima.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Spasi</span>. Ako niste spojeni na mrežu, kliknite na ikonu mreže u traci izbornika i spojite se. Testirajte postavke mreže pokušavajući otići na web stranicu ili pogledajte dijeljene datoteke na mreži, na primjer.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to wifi</a></span>, <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>, <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">Edit connection settings</a></span>, <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…</span>
</li>
<li class="links ">
<a href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">Žičana internet konekcija</a></span>, <span class="link"><a href="net-fixed-ip-address.html" title="Napravite konekciju sa fiksiranom IP adesom">Stalne IP adrese</a></span>…</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
