<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Poveži se na VPN</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Poveži se na VPN</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">VPN (ili <span class="em"> Virtual Private Network </span>) je način spajanja na lokalnu mrežu preko interneta. Na primjer, recimo da želite spojiti na lokalnu mrežu na radnom mjestu, dok ste na poslovnom putu. Trebate negdje naći internet vezu ( npr. u hotelu),i povezati se na VPN radnog mjesta. To bi bilo kao da ste bili direktno povezani sa Vašom radnom mrežom,ali stvarna internet veza je hotelska internet veza. VPN mreže su obično <span class="em">šifrirane</span> kako bi spriječile ljude da pristupaju lokalnoj mreži na koju se povezujete bez prijave.</p>
<p class="p">There are a number of different types of VPN. You may have to install some extra software depending on what type of VPN
you're connecting to. Find out the connection details from whoever is in charge of the VPN and see which <span class="em">VPN client</span>
you need to use. Then, open <span class="app">Ubuntu Software</span> and search for the <span class="app">network-manager</span> package which works
with your VPN (if there is one) and install it.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako nemate paketa MrežniMenadžer za Vaš tip VPN-a,vjerovatno ćete morati skinuti i instalirati neke softvere za klijente od kompaije koja daje taj VPN softver. Vjerovatno ćete morati slijediti različite instrukcije da biste učinili da veza radi.</p></div></div></div></div>
<p class="p">Nakon što to učinite, možete postaviti VPN vezu :</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na <span class="gui">izbornik mreže</span> na traci izbornika, ispod <span class="gui">VPN Spajanje</span>, odaberite <span class="gui"> Postavi VPN</span>.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Dodaj</span> i izaberite koju vrstu VPN veze imate.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Kreiraj</span> i slijedite instrukcije na ekranu, ukucavanjem podataka kao što su korisničko ime i šifra</p></li>
<li class="steps"><p class="p">Kada završite s postavljanjem-up VPN, kliknite <span class="gui"> mrežni izbornik </span> na traci izbornika, idite na <span class="gui"> VPN veze </span> i kliknite na vezu koju ste upravo stvorili. To će pokušati uspostaviti VPN vezu - mreža ikona će se promijeniti kao što se pokušava spojiti.</p></li>
<li class="steps"><p class="p">Nadamo se da ćete se uspješno povezati sa VPN-om.Ako ne,možda ćete trebati dva puta provjeriti VPN postavke koje ste unijeli.To možete učiniti klikom na meni mreže, odabirom <span class="gui"> Uredi Veze </span> i <span class="gui"> VPN </span> kartice.</p></li>
<li class="steps"><p class="p">Da biste se odspojili s VPN-a, kliknite izbornik mreže i odaberite <span class="gui"> Odspoji</span> ispod imena vaše VPN veze.</p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to wifi</a></span>, <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>, <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">Edit connection settings</a></span>, <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…</span>
</li>
<li class="links ">
<a href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">Žičana internet konekcija</a></span>, <span class="link"><a href="net-fixed-ip-address.html" title="Napravite konekciju sa fiksiranom IP adesom">Stalne IP adrese</a></span>…</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
