<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nađite Vašu IP adresu</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nađite Vašu IP adresu</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Znajući IP adresu može vam pomoći otkloniti problema s internetskom vezom. Vi svibanj biti iznenađen kako bi saznali da imate <span class="em"> dva </span> IP adrese: IP adresa za vaše računalo na internoj mreži i IP adresa za vaše računalo na internetu.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Nađite vašu internu (mrežnu) IP adresu</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Network</span> i odaberite <span class="gui">Wired</span>  ili <span class="gui">Wireless</span> sa spiska lijevo, u zavisnosti od koje mreže želite da saznate IP.</p></li>
<li class="steps"><p class="p">Vaša interna IP adresa će biti prikazana na listi sa informacijama.</p></li>
</ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Nađite vašu vanjsku (internet) IP adresu</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Posjetite <span class="link"><a href="http://whatismyipaddress.com/" title="http://whatismyipaddress.com/">whatismyipaddress.com</a></span>.</p></li>
<li class="steps"><p class="p">Stranica će prikazati vašu vanjsku IP adresu za vas.</p></li>
</ol></div>
</div></div>
<p class="p">Zavisno od toga kako se vaš računar konektuje na internet, ove adrese mogu biti iste.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a><span class="desc"> — <span class="link"><a href="net-findip.html" title="Nađite Vašu IP adresu">Pronađite vašu IP adresu</a></span>, <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">WEP &amp; WPA sigurnost</a></span>, <span class="link"><a href="net-macaddress.html" title="Šta je MAC adresa?">MAC adrese</a></span>, <span class="link"><a href="net-proxy.html" title="Definišite postavke ovlaštenja">proxies</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-fixed-ip-address.html" title="Napravite konekciju sa fiksiranom IP adesom">Napravite konekciju sa fiksiranom IP adesom</a><span class="desc"> — Korištenje statičke IP adrese može lakše dati neke mrežne usluge sa vašeg računara.</span>
</li>
<li class="links ">
<a href="net-what-is-ip-address.html" title="Šta je IP adresa?">Šta je IP adresa?</a><span class="desc"> — IP adresa je kao telefonski broj za Vaš računar.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
