<!DOCTYPE html>
<!DOCTYPE html>
<html lang=tl>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Create a connection with a fixed IP address</title>
<link rel="stylesheet" type="text/css" href="tl.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Guide"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Help"></span></span> Ubuntu Desktop Guide</a> » <a class="trail" href="net.html" title="Networking, web, email &amp; chat">Networking, web, email &amp; chat</a> » <a class="trail" href="net-wired.html" title="Wired Networking">Wired Networking</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Create a connection with a fixed IP address</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Most networks will automatically assign an <span class="link"><a href="net-what-is-ip-address.html" title="What is an IP address?">IP address</a></span> and other details to your computer when you connect to the network. These details can change periodically, but you might want to have a fixed IP address for the computer so you always know what its address is (for example, if it is a file server).</p>
<p class="p">To give your computer a fixed (static) IP address:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="gui">network menu</span> on the menu bar and select <span class="gui">Edit Connections</span>.</p></li>
<li class="steps"><p class="p">Select the <span class="gui">Wired connection</span> on the <span class="gui">Wired</span> tab or your WiFi network on the <span class="gui">Wireless</span> tab and click <span class="gui">Edit</span>.</p></li>
<li class="steps"><p class="p">Click on the <span class="gui">IPv4 Settings</span> tab and change the <span class="gui">Method</span> to <span class="em">Manual</span>.</p></li>
<li class="steps"><p class="p">If no connection information is listed in the <span class="gui">Addresses</span> list, or if you want to set up a new connection, click <span class="gui">Add</span>.</p></li>
<li class="steps"><p class="p">Enter the <span class="em">IP Address</span>, <span class="em">Netmask</span>, and <span class="em">Gateway</span> information into the appropriate boxes. How you choose these will depend on your network setup; there are specific rules governing which IP addresses and netmasks are valid for a given network.</p></li>
<li class="steps"><p class="p">If necessary, enter a <span class="em">Domain Name Server</span> address into the <span class="gui">DNS servers</span> box. This is the IP address of a server which looks up domain names; most corporate networks and internet providers have dedicated DNS servers.</p></li>
<li class="steps"><p class="p">Click <span class="gui">Save</span>. The network connection should now have a fixed IP address.</p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wired.html" title="Wired Networking">Wired Networking</a><span class="desc"> — 
      <span class="link"><a href="net-wired-connect.html" title="Connect to a wired (Ethernet) network">Wired internet connections</a></span>,
      <span class="link"><a href="net-fixed-ip-address.html" title="Create a connection with a fixed IP address">Fixed IP addresses</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-findip.html" title="Find your IP address">Find your IP address</a><span class="desc"> — Knowing your IP address can help you troubleshoot network problems.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
