<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zašto se moj računar gasi/obustavlja kada baterija dođe do 10%?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> › <a class="trail" href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> › <a class="trail" href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zašto se moj računar gasi/obustavlja kada baterija dođe do 10%?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada nivo punjenja baterije znacajno opadne, vas racunar ce automatski <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">suspend</a></span>. To radi da bi bio siguran da se baterija nece isprazniti do kraja, posto je to stetno za bateriju. Ako vam se baterija potrosi racunar nece imati vremena da se ugasi ispravno.</p>
<p class="p">You can change what happens when the battery level gets too low. First, click the 
<span class="gui">battery menu</span> in the <span class="gui">menu bar</span> and select <span class="gui">Power Settings</span>. At the <span class="gui">'When
power is critically low'</span> setting, you can choose for the computer to
suspend, <span class="link"><a href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?">hibernate</a></span>, or shut down. If you choose shut down, your applications and
documents <span class="em">will not</span> be saved when the computer turns off.</p>
<p class="p">Some computers have problems suspending, and may not be able to recover the
applications and documents you had open when you turn on the computer again. In
this case, it is possible that you could lose some of your work if you didn't
save it before the computer suspended. You may be able to <span class="link"><a href="power-suspendfail.html" title="Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??">fix problems with suspend</a></span> though.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
