<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Will my computer work with a power supply in another country?</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="power.html#problems" title="Problémy">Power problems</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Will my computer work with a power supply in another country?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Different countries use power supplies at different voltages (usually 110V
or 220-240V) and AC frequencies (usually 50 Hz or 60 Hz). Your computer should
work with a power supply in a different country as long as you have
an appropriate power adapter. You may also need to flip a switch.</p>
<p class="p">If you have a laptop, all you should need to do is get the right plug for
your power adapter. Some laptops come packaged with more than one plug for
their adapter, so you may already have the right one. If not, plugging your
existing one into a standard travel adapter will suffice.</p>
<p class="p">Ak máte stolný počítač, môžete použiť kábel s inou zástrčkou alebo použite cestovný adaptér. V tomto prípade však môže byť nutné zmeniť spínacie napätie zdroja počítača do elektrickej siete, ak existuje. Mnoho počítačov nemá vypínač ako je tento a budú pracovať s akýmkoľvek napätím. Pozrite sa na zadnej strane počítača a nájdite zásuvku kde sa zapája napájací kábel do zástrčky. Niekde v blízkosti môže sa jednať o malý prepínač označený (napríklad) "110V" alebo "230V". Ak potrebujete tak prepnite.</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents"><p class="p">Buďte opatrný pri zmene napájacích káblov alebo použitím cestovného adaptéra. Vypnite všetko ak môžete.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power.html#problems" title="Problémy">Power problems</a><span class="desc"> — Troubleshoot problems with power and batteries.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
