<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Procjenjeno trajanje baterije je pogrešno</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> › <a class="trail" href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> › <a class="trail" href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Procjenjeno trajanje baterije je pogrešno</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada provjerite preostalo vrijeme baterije, mozete primijetiti da je to vrijeme drugcije od onog koliko baterija stvarno traje. Ovo se desava zato sto se vrijeme trajanja baterije procijenjuje. Naravno, procjene se popravljaju vremenom.</p>
<p class="p">Da bi se procijenilo preostalo radno vrijeme baterije, veliki broj činilaca treba uzeti u obzir. Jedan od njih je iznos napajanja koje trenutno koristi računar: potrošnja napajanja se mijenja u zavisnosti od toga koliko programa ste otvorili, koji uređaji su priključeni, i da li ste pokrenuli neki zahtevan zadatak (kao što je gledanje DVD-a ili pretvaranje muzičke datoteke, na primer). Ovo se menja iz trenutka u trenutak i teško je za predviđanje.</p>
<p class="p">Jos jedan faktor je akkao se baterija prazni. Neke baterije gube naboj brze i postaju praznije. Bez preciznog saznanja kako se baterija prazni, samo gruba procjena o trajanju baterije moze biti napravljena.</p>
<p class="p">Kako se baterija bude praznila, upravitelj snagom će računati osobine pražnjenja i naučiti kako da poboljša procjene trajanje baterije. One, ipak, nikada neće biti potpuno tačne.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents">
<p class="p">Ako je procjena trajanja baterije smiješna (recimo, stotine dana), programu za upravljanje snagom vjerovatno nedostaju neke informacije da bi napravio razumnu procjenu.</p>
<p class="p">Ako iskljucite laptop sa napajanja i koristite napajanje baterije. i onda ga ponovo ukljucite i pustite da se napuni, menadzer energije ce biti u stanju da prikupi potrebne informacije.</p>
</div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="power.html#battery" title="Podešavanja baterije">Podešavanja baterije</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power-batterywindows.html" title="Zašto imam manje baterije nego kada radim sa Windows/Mac OS?">Zašto imam manje baterije nego kada radim sa Windows/Mac OS?</a><span class="desc"> — Ugadjanja od proizvodjaca i procjena zivota baterije mogu prouzrokovati ovaj problem.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
