<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Počítač sa nezapne</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="power.html#problems" title="Problémy">Power problems</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Počítač sa nezapne</span></h1></div>
<div class="region">
<div class="contents"><p class="p">There are a number of reasons why your computer will not turn on. This topic
gives a brief overview of some of the possible reasons.</p></div>
<div id="nopower" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Počítač nie je pripojený, vybité batérie, alebo voľné káble</span></h2></div>
<div class="region"><div class="contents"><p class="p">Make sure that the power cables of the computer are firmly plugged in and
  the power outlets are switched on. Make sure that the monitor is plugged in
  and switched on too. If you have a laptop, connect the charging cable (in
  case it has run out of battery). You may also want to check that the battery
  is correctly fitted in place (check the underside of the laptop) if it's
  removable.</p></div></div>
</div></div>
<div id="hardwareproblem" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problém s počítačovým hardvérom</span></h2></div>
<div class="region"><div class="contents"><p class="p">Súčasť vášho počítača môže byť poškodená alebo nepracuje správne. Ak je to tento prípad, budete musieť váš počítač opraviť. Časté poruchy sú rozbitý napájací zdroj, chybne namontované komponenty (napr. pamäť/RAM) a chybná základná doska.</p></div></div>
</div></div>
<div id="beeps" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Počítač pípa a potom sa vypne</span></h2></div>
<div class="region"><div class="contents"><p class="p">Ak počítač pípa niekoľkokrát po zapnutí a potom sa vypne (alebo sa nespustí), pravdepodobne sa vyskytol problém. Tieto zvuky sú niekedy označované ako <span class="em">Zvukové signály</span> a vzor pípania má napovedať v čom je problém s počítačom. Rôzni výrobcovia používajú rôzne zvukové signály, takže budete musieť pozrieť do manuálu k základnej doske počítača alebo si počítač dať do opravy.</p></div></div>
</div></div>
<div id="fans" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Ventilátor počítača sa točí ale nič sa nezobrazí</span></h2></div>
<div class="region"><div class="contents">
<p class="p">The first thing to check is that your monitor is plugged in and turned
  on.</p>
<p class="p">Tento problém by mohol byť kvôli zlyhaniu hardvéru. Keď stlačíte tlačidlo napájania ventilátor sa zapne ale ďalšie dôležité časti počítača zlyhajú pri zapnutí. V takomto prípade vezmite váš počítač do opravy.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="power.html#problems" title="Problémy">Power problems</a><span class="desc"> — Troubleshoot problems with power and batteries.</span>
</li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a><span class="desc"> — Riešenie problémov s obrazom a grafikou.</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
