<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Užívateľské a systémové nastavenia</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Užívateľské a systémové nastavenia</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="clock.html" title="Dátum a čas">Dátum a čas</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="clock-set.html" title="Change the date and time">Set time and date</a></span>,
      <span class="link"><a href="clock-timezone.html" title="Zobrazenie času v iných mestách">timezone</a></span>,
      <span class="link"><a href="clock-calendar.html" title="Calendar appointments">calendar and appointments</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="keyboard.html" title="Klávesnica">Klávesnica</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">Input sources</a></span>,
      <span class="link"><a href="keyboard-cursor-blink.html" title="Blikanie kurzora klávesnice">cursor blinking</a></span>,
      <span class="link"><a href="windows-key.html" title='What is the "Super" key?'>super key</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Pohybové postihnutie">keyboard accessibility</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="mouse.html" title="Myš">Myš</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="mouse-lefthanded.html" title="Myš pre ľavákov">Left-handed</a></span>,
      <span class="link"><a href="mouse-sensitivity.html" title="Rýchlosť pohybu myši a touchpadu">speed and sensitivity</a></span>,
      <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">touchpad clicking and scrolling</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="accounts.html" title="Online účty">Online účty</a></div>
<div class="desc"><span class="desc">
	    <span class="link"><a href="accounts-add.html" title="Pridať účet">Add accounts, </a></span>
	    <span class="link"><a href="accounts-remove.html" title="Remove an account">Remove accounts, </a></span>
	    <span class="link"><a href="accounts-disable-service.html" title="Disable account services">Disable services</a></span>
		</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="power.html" title="Power &amp; battery">Power &amp; battery</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="power-suspend.html" title="What happens when I suspend my computer?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Use less power and improve battery life">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Power off or restart">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Prečo mi obrazovka stmavne po nejakej dobe?">screen dimming</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs-language.html" title="Region &amp; Language">Region &amp; Language</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="prefs-language-install.html" title="Install languages">Install languages</a></span>,
      <span class="link"><a href="session-language.html" title="Change which language you use">change language</a></span>,
      <span class="link"><a href="session-formats.html" title="Change date and measurement formats">region and formats</a></span>,
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">input sources</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="color.html" title="Správa farieb">Správa farieb</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="color-whyimportant.html" title="Prečo je správa farieb dôležitá">Why is this important</a></span>,
      <span class="link"><a href="color.html#profiles" title="Profily farieb">Color profiles</a></span>,
      <span class="link"><a href="color.html#calibration" title="Kalibrácia">How to calibrate a device</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="startup-applications.html" title="Startup Applications">Startup Applications</a></div>
<div class="desc"><span class="desc">Choose what applications to start when you log in.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="user-accounts.html" title="Užívateľský účet">Užívateľský účet</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="user-add.html" title="Pridať nový užívateľský účet">Add user</a></span> or
      <span class="link"><a href="shell-guest-session.html" title="Spustenie a obmedzenie hosťovania">guest user</a></span>,
      <span class="link"><a href="user-changepassword.html" title="Zmeniť heslo">change password</a></span>,
      <span class="link"><a href="user-admin-change.html" title="Zmena ktorá oprávňuje správcu">administrators</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">Vzhľad displeja; obrazovka</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="look-background.html" title="Zmena pozadia pracovnej plochy">Background</a></span>,
      <span class="link"><a href="look-resolution.html" title="Change the size or rotation of the screen">size and rotation</a></span>,
      <span class="link"><a href="display-dimscreen.html" title="Nastavenie jasu obrazovky">brightness</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="wacom.html" title="Wacom Graphics Tablet">Wacom Graphics Tablet</a></div>
<div class="desc"><span class="desc">Adjust the settings of your Wacom tablet.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="media.html#sound" title="Zvuk">Zvuk</a></div>
<div class="desc"><span class="desc">
     <span class="link"><a href="sound-volume.html" title="Zmena hlasitosti">Volume</a></span>,
     <span class="link"><a href="sound-usespeakers.html" title="Používanie rôznych reproduktorov alebo slúchadiel">speakers and headphones</a></span>,
     <span class="link"><a href="sound-usemic.html" title="Use a different microphone">microphones</a></span>…
   </span></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Príručka pre Ubuntu desktop">Príručka pre Ubuntu desktop</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
