<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Promjenite formate za datum i mjerenje</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-language.html" title="Regija i jezik">Regija i jezik</a> › <a class="trail" href="prefs-language.html#langsupport" title="Jezička podrška">Jezička podrška</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Promjenite formate za datum i mjerenje</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete kontrolisati formate koji su korišteni za datum, vrijeme, brojeve, valutu i mjerenja kako bi se slagali sa lokalnim običajima vaše regije.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Podrška za jezike</span> i odaberite <span class="gui">Regionalni formati</span> tab.</p></li>
<li class="steps"><p class="p">Odaberire regiju koja se najpribližnije slaže sa formatima koje želite koristiti. Predefinisano, lista prikazuje samo regije koje koriste jezik postavljen u <span class="gui">Jezik</span> tabu.</p></li>
<li class="steps"><p class="p">Morate se odjaviti i vratiti nazad da bi promjene imale efekta. Kliknite ikonu koja se nalazi sasvim desno na traci menija i odaberite <span class="gui">Odjavi se</span>  da se odjavite.</p></li>
</ol></div></div></div>
<p class="p">Nakon sto ste izabrali regiju, prostor ispod pokazuje vise primjera kako se prikazuju datumi i ostale vrijednosti. Iako nije prikazano moguce je podesiti i pocetni dan u kalendarima.</p>
</div>
<div id="system" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Promijenite sistemske formate</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Kada promijenite vašu regiju za formate, samo je mijenjate za vaš račun na kom ste prijavljeni. Možete, također, promijeniti <span class="em">sistemske formate</span>, formate korištene na mjestima poput zaslona za prijavu.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Promijenite vaše formate, kako je opisano iznad.</p></li>
<li class="steps"><p class="p">Kliknite  <span class="gui">Primijeni Ssitem-Široko</span>.</p></li>
<li class="steps"><p class="p">Potrebne su <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?">Privilegije administratora</a></span>. Unesite vašu šifru, ili šifru za traženi administratorski račun.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="prefs-language.html#langsupport" title="Jezička podrška">Jezička podrška</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="session-language.html" title="Promjenite jezik koji koristite">Promjenite jezik koji koristite</a><span class="desc"> — Prebacite na drugi jezika za korisničko sučelje i tekst pomoći.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
