<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zamjena između prozora</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="shell-overview.html" title="Desktop, programi &amp; prozori">Radna površina</a> › <a class="trail" href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="shell-overview.html" title="Desktop, programi &amp; prozori">Radna površina</a> › <a class="trail" href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a> » <a class="trail" href="shell-windows.html" title="Prozori i radni prostori.">Prozori i radni prostori.</a> › <a class="trail" href="shell-windows.html#working-with-windows" title="Rad s prozorima">Prozori</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zamjena između prozora</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="launcher" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Sa pokretača</span></h2></div>
<div class="region"><div class="contents"><div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">
Show the <span class="gui">Launcher</span> by moving your mouse to the top left corner of your screen.
    </p></li>
<li class="steps"><p class="p">Pokrenute aplikacije  imaju malu bijeli triangl strijelu na lijevo. Kliknite na ikonu pokrenute aplikacije da biste prebacili na nju.</p></li>
<li class="steps"><p class="p">Ako pokrenuta aplikacija ima više otvorenih prozora,bit će i više bijelih strelica u lijevo. Kliknite na ikonu aplikacije još jednom da prokaze sve otvorene prozore odzumirane. Kliknite na prozor na koji se želite prebaciti.</p></li>
</ol></div></div></div></div></div>
</div></div>
<div id="keyboard" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">S tastature.</span></h2></div>
<div class="region"><div class="contents">
<div class="list"><div class="inner"><div class="region"><ul class="list"><li class="list">
<p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> da podignete <span class="gui">window switcher</span>.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Pustite <span class="key"><kbd>Alt</kbd></span> da izaberete sledeci( oznaceni) prozor.</p></li>
<li class="list">
<p class="p">U protivnom. cuvanje tipke <span class="key"><kbd>Alt</kbd></span>, pritiskom na <span class="key"><kbd>Tab</kbd></span> mozete kruziti po listi otvorenih prozora, ili <span class="keyseq"><span class="key"><kbd>Shift</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> da idete unazad.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Prozori u u izuborniku prozora su grupisani po aplikacijama. Pregled aplikacija sa vise iskacucih prozora kako idete kroz njega.</p></div></div></div></div>
</li>
<li class="list"><p class="p">Mozete takodjer da se pomjerate po ikonama aplikacija sa tipkama <span class="key"><kbd>→</kbd></span> or <span class="key"><kbd>←</kbd></span>, ili da izaberete neku klikom misa.</p></li>
<li class="list">
<p class="p">Pregledi aplikacija sa jednom prozorom mogu biti prikazane tipkom <span class="key"><kbd>↓</kbd></span></p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Samo prozori sa trenutne <span class="link"><a href="shell-workspaces.html" title="Šta je radna površina, i kako će mi pomoći?">radne površine</a></span> će biti prikazani. Da bi bili prikazane prozori sa svih radnih površina, držite pritisnutim <span class="key"><kbd>Ctrl</kbd></span> i <span class="key"><kbd>Alt</kbd></span> tipke i pritisnite <span class="key"><kbd>Tab</kbd></span> ili <span class="keyseq"><span class="key"><kbd>Shift</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span>.</p></div></div></div></div>
</li>
</ul></div></div></div>
</li></ul></div></div></div>
<div class="list"><div class="inner"><div class="region"><ul class="list"><li class="list">
<p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd><span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>Super</a></span></kbd></span>+<span class="key"><kbd>W</kbd></span></span> da prikazete sve otvorene prozore koji nisu u fokusu</p>
<div class="list"><div class="inner"><div class="region"><ul class="list"><li class="list"><p class="p">Kliknite prozor na koji se želite prebaciti.</p></li></ul></div></div></div>
</li></ul></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a></li>
<li class="links "><a href="shell-windows.html#working-with-windows" title="Rad s prozorima">Rad s prozorima</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
