<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prozori i radni prostori.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="shell-overview.html" title="Desktop, programi &amp; prozori">Radna površina</a> › <a class="trail" href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Prozori i radni prostori.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Like other desktops, Unity uses windows to display your running applications. Using both the <span class="gui">Dash</span> and the <span class="gui">Launcher</span>, you can launch new applications and control which window is active.</p>
<p class="p">U dodatku sa prozorom, također možete grupisati Vaše aplikacije zajedno unutar radnih prostora. Posjetite pomoćne teme o prozorima i radnim prostorima ispod,da biste naučili kako bolje koristiti ove značajke.</p>
</div>
<div id="working-with-windows" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Rad s prozorima</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="shell-windows-maximize.html" title="Maksimizirajte i smanjite prozor."><span class="title">Maksimizirajte i smanjite prozor.</span><span class="linkdiv-dash"> — </span><span class="desc">Dva puta kliknite ili povucite titlebar da bi ste maksimizirali ili opravili prozor.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="shell-windows-tiled.html" title="Poredaj prozore."><span class="title">Poredaj prozore.</span><span class="linkdiv-dash"> — </span><span class="desc">Maksimizirajte dva prozora jedan pored drugog.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="shell-windows-states.html" title="Prozor operacije"><span class="title">Prozor operacije</span><span class="linkdiv-dash"> — </span><span class="desc">Vraćanje,mijenjanje veličine, uređivanje i sakrivanje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="shell-windows-switching.html" title="Zamjena između prozora"><span class="title">Zamjena između prozora</span><span class="linkdiv-dash"> — </span><span class="desc">Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span>.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="working-with-workspaces" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Rad sa radnim prostorima.</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="shell-workspaces.html" title="Šta je radna površina, i kako će mi pomoći?"><span class="title">Šta je radna površina, i kako će mi pomoći?</span><span class="linkdiv-dash"> — </span><span class="desc">Radne površne su način grupisanja prozora na vašem desktopu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="shell-workspaces-movewindow.html" title="Pomjerite prozor na drugu radnu površinu"><span class="title">Pomjerite prozor na drugu radnu površinu</span><span class="linkdiv-dash"> — </span><span class="desc">Otvorite mjenjača radne površine i privucite prozor drugoj radnoj površini.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="shell-workspaces-switch.html" title="Sljedeća radna površina"><span class="title">Sljedeća radna površina</span><span class="linkdiv-dash"> — </span><span class="desc">Otvorite switcher radne površine i dvaput kliknite na jednu od radnih površina.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
