<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Odjavti se, isključiti, zamijeniti korisnika</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Odjavti se, isključiti, zamijeniti korisnika</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Kada ste završili sa korištenjem vašeg računara, možete ga ugasiti, obustaviti ( da sačuvate snagu), ili ostaviti upaljenog i odjaviti se.</p></div>
<div id="logout" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Odjaviti se ili zamijeniti korisnika</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Da dozvolite drugima da koriste vas racunar mozete se izlogovati, ili ostaviti sebe logovanim a prebaciti korisnika. Ako mijenjate korisnika, sve vase aplikacije ce se nastaviti izvrsavati, i sve ce biti kako ste i ostavili kad se ulogujete ponovo.</p>
<p class="p">Da se izlogujete ili da zamijenite korisnika kliknite <span class="link"><a href="unity-menubar-intro.html" title="Upravljajte aplikacijama i postavkama pomoću trake s menijem">system menu</a></span> skroz desno na meni traci i izaberite odgovarajucu opciju.</p>
</div></div>
</div></div>
<div id="lock-screen" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Zaključaj ekran</span></h2></div>
<div class="region">
<div class="contents">
<p class="p">Ako napustate vas racunar nakratko trebali bi zakljucati ekran da spijecite druge ljude da pristupaju vasim fajlovima i pokrecu aplikacije. Kada se vratite jednotavno unesete sifru. Ako vi ne zakljucate ekran, on ce se sam zakljucati nakon izvjesnog vremena.</p>
<p class="p">Da zaključate ekran kliknite <span class="gui">sistemski meni</span> na traci menija i odaberite <span class="gui">Zaključaj ekran</span>.</p>
<p class="p">Kada vam je ekran zakljucan, drugi korisnici se mogu spojiti na svoje racune klikanjem <span class="gui">Switch User</span>. Mozwte vratiti vas ekran kada oni zavrse.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links seealsolinks"><div class="inner">
<div class="title"><h3><span class="title">Vidite i</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="display-lock.html" title="Automatski zaključajte vaš ekran">Automatski zaključajte vaš ekran</a><span class="desc"> — Spriječite druge osobe da koriste radnu površinu kada odete dalje od računara.</span>
</li>
<li class="links ">
<a href="session-screenlocks.html" title="Zaslon se prebrzo sam zaključava">Zaslon se prebrzo sam zaključava</a><span class="desc"> — Izmijenite nakon kog vremena će se zaključati ekran u podešavanjima <span class="gui">Osvjetljenost i zaključavanje</span>.</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div id="suspend" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Suspenduj</span></h2></div>
<div class="region">
<div class="contents">
<p class="p">Da bi stedjeli energiju, suspendujte vas racunar kada ga ne koristite. Ako koristite laptop, Ubuntu suspenduje vas racunar cimga preklopite. OVo spasava vase stanje na racunaru i gasi vecinu funkcija. Veoma mala kolicina energije se trosi kad je racunar suspendovan.</p>
<p class="p">Da ručno obustavite vaš računar, kliknite <span class="gui">sistemski meni</span> na traci menija i odaberite <span class="gui">Obustavi</span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links seealsolinks"><div class="inner">
<div class="title"><h3><span class="title">Vidite i</span></h3></div>
<div class="region"><ul><li class="links ">
<a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Šta se dešava kada obustavim moj računar?</a><span class="desc"> — Suspendiranje salje vas racunar na spavanje ztako da koristi manje energije.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div id="shutdown" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Isključiti ili restartovati</span></h2></div>
<div class="region">
<div class="contents">
<p class="p">Ako želite potpuno da ugasite Vaš računar, ili da uradite potpuni restart, kliknite <span class="gui">system menu</span> i izaberite <span class="gui">Shut Down</span>.</p>
<p class="p">Ako su i drugi korisnici ulogovani, nećete moći da ugasite ili da restartujete računar, jer će te okončati i njihove sesije. Ako se administrativni korisnik, onda ćete biti pitani za lozinku da bi ste ugasili računar.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links seealsolinks"><div class="inner">
<div class="title"><h3><span class="title">Vidite i</span></h3></div>
<div class="region"><ul><li class="links ">
<a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">Koristite manje snage i unaprijedite trajanje baterije</a><span class="desc"> — Savjeti za manju potrošnju struje vašeg računara.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="shell-overview.html#desktop" title="Radna površina">Radna površina</a></li>
<li class="links ">
<a href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a><span class="desc"> — 
      <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">screen dimming</a></span>…
    </span>
</li>
<li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?">Kako vršim hibernaciju mog računara?</a><span class="desc"> — Hibernacija je normalno onemogućena jer nije potpuno podržana.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
