<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Promjenite jačinu zvuka</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="media.html#sound" title="Osnovni zvuk">Zvuk</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Promjenite jačinu zvuka</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Da promijenite jacinu zvuka kliknite  <span class="gui">sound menu</span> na <span class="gui">menu bar</span> i pomjerite klizac lijevo ili desno. Mozete skroz ugasiti zvuk pritiskom na <span class="gui">Mute</span>.</p>
<p class="p">Neke tastature imaju tastere koji vam omogućavaju da upravljate jačinom zvuka. Ovi tasteri obično izgledaju kao zvučnici iz kojih izlaze zvučni talasi. Često se nalaze blizu tastera „F“ na vrhu. Na tastaturama prenosnih računara, obično se nalaze na „F“ tasterima. Držite pritisnutim taster <span class="key"><kbd class="key-Fn">Fn</kbd></span> na tastaturi da ih koristite.</p>
<p class="p">Naravno, ako imate eksterne zvucnike, mozete promijeniti jacinu zvuka na njima samim. Neke slusalice takodjer imaju podesavanje jacine zvuka na sebi.</p>
</div>
<div id="apps" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Mijenjanje jačine zvuka za zasebne programe</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete da izmenite jačinu zvuka jednog programa, ali da ostavite neizmenjenom jačinu zvuka drugih programa. Ovo je korisno ako slušate muziku i razgledate veb, na primer. Možete da isključite jačinu zvuka u veb pregledniku tako da zvuci saweb sajtova ne ometaju muziku.</p>
<p class="p">Neke aplikacije imaju kontrolu glasnoće u svojim glavnim prozorima. Ako vaša aplikacija ima jedan od tih, koristiti da biste promijenili glasnoću. Inače, kliknite <span class="gui">sound menu</span> na <span class="gui">menu bar</span> i kliknite <span class="gui">Sound Settings</span>.  Idite na <span class="gui">Applications</span> i promijenite jacinu zvuka aplikacije tu.</p>
<p class="p">Samo programi koji trenutno puštaju zvuk će biti na spisku. Ako neki program koji trenutno pušta zvuk nije na spisku, možda ne podržava funkciju koja vam dopušta da upravljate jačinom zvuka na ovaj način. U tom slučaju, nećete moći da promenite njegovu jačinu zvuka.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="media.html#sound" title="Osnovni zvuk">Osnovni zvuk</a><span class="desc"> — <span class="link"><a href="sound-volume.html" title="Promjenite jačinu zvuka">Jačina</a></span>, <span class="link"><a href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice.">zvučnici i slušaliceheadphones</a></span>, <span class="link"><a href="sound-usemic.html" title="Koristite drugi mikrofon">mikrofoni</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
