<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Upravljajte aplikacijama i postavkama pomoću trake s menijem</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Upravljajte aplikacijama i postavkama pomoću trake s menijem</span></h1></div>
<div class="region">
<div class="contents"><p class="p">The <span class="gui">menu bar</span> is the dark strip on the top of your screen.
    It contains the window management buttons, the app menus, and the status menus.</p></div>
<div id="window-management" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Dugmad za upravljanje prozorom</span></h2></div>
<div class="region">
<div class="contents"><p class="p">The <span class="gui">window management buttons</span> are on the top left corner of windows. When
    maximized, the buttons are in the top left of the screen. Click the buttons to
    close, minimize, maximize or restore windows.</p></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links seealsolinks"><div class="inner">
<div class="title"><h3><span class="title">Vidite i</span></h3></div>
<div class="region"><ul><li class="links ">
<a href="shell-windows-states.html" title="Prozor operacije">Prozor operacije</a><span class="desc"> — Vraćanje,mijenjanje veličine, uređivanje i sakrivanje.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div id="app-menus" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Aplikacijski meniji</span></h2></div>
<div class="region"><div class="contents">
<p class="p">The <span class="gui">app menus</span> are by default located to the right of the window management buttons.
    Unity hides the app menus and the window management buttons unless you move your
    mouse pointer to the top left of the screen or press <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F10</kbd></span></span>.
    This feature enables you to see more of your content at once, which is
    especially valuable on small screens like netbooks.
  </p>
<p class="p">If you want, you can change the default behavior to having your menus attached
    to the window title bar of respective application instead of the menu bar, and setting the visibility to always displayed instead of only displayed on mouse hovering. </p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="gui">system menu</span> at the very right of the <span class="gui">menu bar</span> and select
        <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">U Ličnoj sekciji, odaberite <span class="gui">Izgled</span> i odaberite <span class="gui">Ponašanje</span> tab.</p></li>
<li class="steps"><p class="p">Ispod <span class="gui">Prikaži menije za prozor</span>, odaberite <span class="gui">U naslovnoj traci prozora</span>.</p></li>
<li class="steps"><p class="p">Ispod <span class="gui">Vidljivost menija</span>, odaberite <span class="gui">Uvijek prikazano</span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="status-menus" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Statusni meniji</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ubuntu posjeduje nekoliko različitih <span class="gui">statusnih menija</span> (ponekad se odnosi na <span class="gui">indikatori</span>) na desnoj strani meni trake. Statusni meniji su pogodno mjesto gdje mozete provjeriti status vašeg računara i aplikacija.</p>
<div class="list ui-expander">
<div class="yelp-data yelp-data-ui-expander" dir="ltr" data-yelp-expanded="false"></div>
<div class="inner">
<div class="title title-list"><h3><span class="title">Lista statusnih menija i šta oni rade</span></h3></div>
<div class="region"><ul class="list">
<li class="list">
<p class="p"><span class="em">Mrežni meni</span> <span class="media"><span class="media media-image"><img src="figures/network-offline.svg" class="media media-inline" alt="Van mreže ikona"></span></span></p>
<p class="p">Poveži se na <span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">žično</a></span>, <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">bežično</a></span>, <span class="link"><a href="net-mobile.html" title="Povezivanje na mobilni širokopojasni pristup.">mobile</a></span>, and <span class="link"><a href="net-vpn-connect.html" title="Poveži se na VPN">VPN</a></span> mreže.</p>
</li>
<li class="list">
<p class="p"><span class="em">Input source meni</span> <span class="media"><span class="media media-image"><img src="figures/indicator-keyboard-En.svg" class="media media-inline" alt="Input source ikona"></span></span></p>
<p class="p">Odaberite izgled tastature/izvor unosa, <span class="link"><a href="keyboard-layouts.html" title="Koristite alternativne izvore unosa">konfigurišite izvore unosa</a></span></p>
</li>
<li class="list">
<p class="p"><span class="em">Bluetooth meni</span> <span class="media"><span class="media media-image"><img src="figures/bluetooth-active.svg" class="media media-inline" alt="Bluetooth ikona"></span></span></p>
<p class="p">Šaljite ili primajte datoteke preko <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>-a. Ovaj meni je sakriven ako podržani Bluetooth uređaj nije otkriven.</p>
</li>
<li class="list">
<p class="p"><span class="em">Meni poruka</span> <span class="media"><span class="media media-image"><img src="figures/indicator-messages.svg" class="media media-inline" alt="Meni ikona"></span></span></p>
<p class="p">Lako pokrenite i primajte dolazeće notifikacije od aplikacija za dopisivanje uključujući email, društvene mreže i internet chat.</p>
</li>
<li class="list">
<p class="p"><span class="em">Meni baterije</span> <span class="media"><span class="media media-image"><img src="figures/battery-100.svg" class="media media-inline" alt="Ikona baterije"></span></span></p>
<p class="p">Provjera statusa punjenja vaše baterije od laptopa. Ovaj meni je sakriven ako baterija nije detektovana.</p>
</li>
<li class="list">
<p class="p"><span class="em">Meni zvuka</span> <span class="media"><span class="media media-image"><img src="figures/audio-volume-high-panel.svg" class="media media-inline" alt="Ikona jačine zvuka"></span></span></p>
<p class="p">Postavite <span class="link"><a href="sound-volume.html" title="Promjenite jačinu zvuka">jačinu</a></span>, konfigurišite zvuk <span class="link"><a href="media.html" title="Zvuk, video &amp; slike">settings</a></span>, i kontrolišite izvođače medija kao što je <span class="app">Rhythmbox</span>.</p>
</li>
<li class="list">
<p class="p"><span class="em">Sat</span></p>
<p class="p">Pristupite trenutnom datumu i vremenu. Isti iz bulit-in <span class="link"><a href="clock-calendar.html" title="Kalendarski sastanci">Kalendar</a></span> mogu također da se pojave ovdje.</p>
</li>
<li class="list">
<p class="p"><span class="em">Sistemski meni</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Ikona"></span></span></p>
<p class="p">Pristupite detaljima o vašem računaru, vodiču i <span class="link"><a href="prefs.html" title="Korisničke &amp; sistemske postavke">sistemskim postavkama</a></span>. Promjenite korisnika, zaključajte ekran, odjavite se, suspendujte ili ugasite računar.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Neke od ikona koje se koriste kao pokazatelji menija mijenjaju se prema statusu aplikacije.</p></div></div></div></div>
<p class="p">Drugi programi poput <span class="app">Tomboy</span> ili <span class="app">Transmission</span> takodje mogu dodati indikatorski meni na panel</p>
</li>
</ul></div>
</div>
</div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="shell-overview.html#desktop" title="Radna površina">Radna površina</a></li>
<li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
