<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Šta su okvirni trake za pomicanje?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="shell-overview.html" title="Desktop, programi &amp; prozori">Radna površina</a> › <a class="trail" href="shell-overview.html#desktop" title="Radna površina">Radna površina</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Šta su okvirni trake za pomicanje?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ubuntu uključuje i <span class="em">overlay scrollbars</span> koji zauzimaju manje prostora na ekranu od uobičajenih scrollbars, davajući vam više prostora za vaš sadržaj. Inspirisani mobitelima gdje uobičajeni scrollbars nisu potrebni, Ubuntovi overlay scrollbars su dizajniraji da rade jednako dobro sa mišem.</p>
<p class="p">Neki programi poput FireFox-a i LibreOffice-a ne podržavaju nove klizače još uvijek.</p>
</div>
<div id="using" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Koristite klizače</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Prekriveni klizač se pojavljuje kao tanka narandžasta traka na ivici skrolajućeg prostora. Pozicija klizača odgovara sa pozicijom vašeg ekrana. Dužina trake odgovara dužini sadržaja; Kraća traka znači duži sadržaj.</p>
<p class="p">Pomaknite vaš pokazivač miša preko bilo koje tačke na ivici sadržaja da vam se prikaže <span class="gui"> palac klizač </span>.</p>
<div class="list"><div class="inner">
<div class="title title-list"><h3><span class="title">Načini korištenja klizača</span></h3></div>
<div class="region"><ul class="list">
<li class="list"><p class="p">Dovucite <span class="gui">palac klizač</span> gore ili dolje da pomjerite poziciju ekerana tačno gdje želite.</p></li>
<li class="list"><p class="p">Kliknite na klizač-traku da pomjerite poziciju ekrana tačno gdje želite.</p></li>
</ul></div>
</div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="shell-overview.html#desktop" title="Radna površina">Radna površina</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="mouse-touchpad-click.html" title="Klikajte, povucite, ili skrolajte pomoću touchpad-a.">Klikajte, povucite, ili skrolajte pomoću touchpad-a.</a><span class="desc"> — Kliknite, povucite ili skrolajte pomoću dodira i gestu na touchpadu.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
