<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Korisnički nalozi</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Korisnički nalozi</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Svaka osoba koja koristi ralunar bi trebala imati drugi korisnički nalog. Ovo će vam omogućiti da čuvate vaše datoteke odvojene od tudjih i da birate vlastite postavke. Takođe je sigurnije. Možete pristupiti drugom korisničkom racunu samo ako znate šifru.</p></div>
<div id="manage" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Upravljanje korisničkim nalozima</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-add.html" title="Dodaj novi korisnički račun."><span class="title">Dodaj novi korisnički račun.</span><span class="linkdiv-dash"> — </span><span class="desc">Dodajte nove korisnike kako bi i drugi ljudi mogli pristupiti vasem računaru.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-delete.html" title="Obrišite korisnički račun"><span class="title">Obrišite korisnički račun</span><span class="linkdiv-dash"> — </span><span class="desc">Uklonite korisnike koji više ne koriste Vas računar.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="shell-guest-session.html" title="Pokrenite ograničenu gost sesiju"><span class="title">Pokrenite ograničenu gost sesiju</span><span class="linkdiv-dash"> — </span><span class="desc">Dopustite na siguran način prijatelju ili kolegi da posudi vaš računar.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-changepicture.html" title="Promijenite Vašu sliku na ulaznom ekranu"><span class="title">Promijenite Vašu sliku na ulaznom ekranu</span><span class="linkdiv-dash"> — </span><span class="desc">Dodajte vašu fotografiju na prijavu i korisničke zaslone</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="passwords" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Šifre</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-goodpassword.html" title="Odaberite sigurne šifre."><span class="title">Odaberite sigurne šifre.</span><span class="linkdiv-dash"> — </span><span class="desc">Koristite duže, komplikovanije šifre.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-changepassword.html" title="Promijenite(mijenjajte) Vašu šifru."><span class="title">Promijenite(mijenjajte) Vašu šifru.</span><span class="linkdiv-dash"> — </span><span class="desc">Čuvajte Vas racun sigurnim čestim mijenjanjem sifre u vašim računskim postavkama.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="user-forgottenpassword.html" title="Zaboravio sam šifru!"><span class="title">Zaboravio sam šifru!</span><span class="linkdiv-dash"> — </span><span class="desc">Napredne tehnike za resetovanje Vaše šifre</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="privileges" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Korisničke privilegije.</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?"><span class="title">Kako funkcionišu administrativne privilegije?</span><span class="linkdiv-dash"> — </span><span class="desc">Potrebne su Vam administratorske privilegije da biste mogli mijenjati vazne dijelove vaseg sistema.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-admin-change.html" title="Mijenjajte(promijenite) ko ima administrativne privilegije"><span class="title">Mijenjajte(promijenite) ko ima administrativne privilegije</span><span class="linkdiv-dash"> — </span><span class="desc">Možete mijenjati koji korisnici mogu praviti promjene na vašem sistemu dajući administrativne privilegije.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="user-admin-problems.html" title="Problemi prouzrokovani administrativnim zabranama."><span class="title">Problemi prouzrokovani administrativnim zabranama.</span><span class="linkdiv-dash"> — </span><span class="desc">Možete raditi samo odredjene stvari,kao sto je instaliranje aplikacija,ako imate administratorske privilegije.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
