<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dodaj novi korisnički račun.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#manage" title="Upravljanje korisničkim nalozima">Korisnički nalozi</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dodaj novi korisnički račun.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete dodati brojne korisnicke račune vasem računaru. Dodjelite jedan nalog svakoj osobi u domaćinstvu ili firmi. Svaki korisnik ima vlastiti home folder,dokumente i postavke.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikom na ikonu na desnoj strani <span class="gui">menu trake</span> i odabirom <span class="gui">Sistemske Postavke</span>.</p></li>
<li class="steps"><p class="p">Otvorite  <span class="gui">Korisnički račun</span>.</p></li>
<li class="steps"><p class="p">Trebaju vam <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?">privilegije administratora</a></span> da dodate korisnički račun. Kliknite <span class="gui">Otključaj</span> u gornjem desnom uglu i ukucajte vašu lozinku.</p></li>
<li class="steps"><p class="p">U listi računa na lijevoj strani, kliknite dugme <span class="key"><kbd>+</kbd></span> da dodate novi račun.</p></li>
<li class="steps"><p class="p">Ako želite da novi korisnik ima <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?">administratorski pristup</a></span> računaru, izaberite <span class="gui">Administrator</span> za vrstu naloga. Administratori mogu da dodaju i da brišu korisnike, instaliraju programe i upravljačke programe, i da izmijene datum i vrijeme.</p></li>
<li class="steps"><p class="p">Unesite puno ime novog korisnika. Ovo korisničko ime ce biti popunjeno automatski na osnovu punog imena. Podrazumijevano je vjerovatno u redu, ali vi ga mozete promijeniti ako želite.</p></li>
<li class="steps"><p class="p">Kliknite  <span class="gui">Kreiraj</span></p></li>
<li class="steps">
<p class="p">Nalog je na početku isključen sve dok ne odlučite šta ćete sa korisničkom lozinkom. Pod <span class="gui">Opcije prijavljivanja</span> kliknite na <span class="gui">Nalog je isključen</span> pored <span class="gui">Lozinke</span>. Izaberite <span class="gui">Postavi lozinku sada</span> iz padajućeg spiska <span class="gui">Radnja</span>, i dajte korisniku da upiše svoju lozinku u poljima <span class="gui">Nova lozinka</span> i <span class="gui">Potvrdi lozinku</span>. Pogledajte <span class="link"><a href="user-goodpassword.html" title="Odaberite sigurne šifre.">Odaberite sigurne šifre.</a></span>.</p>
<p class="p">Takodje mozete kliknuti dugme sljedeće do <span class="gui">Nova šifra</span> polja da izaberete slucajno odabranu sigurnu šifru. Ove šifre su teške za druge da pogote,ali mogu biti teške i za zapamtiti, pa pripazite.</p>
</li>
<li class="steps"><p class="p">Kliknite<span class="gui">Promijeni</span>.</p></li>
</ol></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">U prozoru <span class="gui">Korisnički nalozi</span> možete da kliknete na sliku pored imena korisnika da podesite sliku za nalog. Ova slika će biti prikazana u prozoru prijavljivanja. Gnome obezbjeđuje neke slike koje možete da koristite, ili možete da izaberete neku vašu ili d anapravite sliku vašom veb kamericom.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#manage" title="Upravljanje korisničkim nalozima">Upravljanje korisničkim nalozima</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="shell-guest-session.html" title="Pokrenite ograničenu gost sesiju">Pokrenite ograničenu gost sesiju</a><span class="desc"> — Dopustite na siguran način prijatelju ili kolegi da posudi vaš računar.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
