<!DOCTYPE html>
<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Užívateľský účet</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Užívateľský účet</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Each person that uses the computer should have a different user account.
 This allows them to keep their files separate from yours and to choose their
 own settings. It's also more secure. You can only access a different user
 account if you know the password.</p></div>
<div id="manage" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Správa užívateľského účtu</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-add.html" title="Pridať nový užívateľský účet"><span class="title">Pridať nový užívateľský účet</span><span class="linkdiv-dash"> — </span><span class="desc">Add new users so that other people can log in to the computer.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-delete.html" title="Odstránenie používateľského konta"><span class="title">Odstránenie používateľského konta</span><span class="linkdiv-dash"> — </span><span class="desc">Odstrániť používateľa ktorý používa váš počítač.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="shell-guest-session.html" title="Spustenie a obmedzenie hosťovania"><span class="title">Spustenie a obmedzenie hosťovania</span><span class="linkdiv-dash"> — </span><span class="desc">Požičajte priateľom a kolegom počítač bezpečným spôsobom.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-changepicture.html" title="Zmena obrázku vašej prihlasovacej obrazovky"><span class="title">Zmena obrázku vašej prihlasovacej obrazovky</span><span class="linkdiv-dash"> — </span><span class="desc">Add your photo to the login and user screens.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="passwords" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Heslá</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-forgottenpassword.html" title="Zabudol som heslo!"><span class="title">Zabudol som heslo!</span><span class="linkdiv-dash"> — </span><span class="desc">Pokročilé techniky pre resetovanie vášho hesla</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-changepassword.html" title="Zmeniť heslo"><span class="title">Zmeniť heslo</span><span class="linkdiv-dash"> — </span><span class="desc">Udržujte si svoj účet zabezpečený častou zmenou vášho hesla v nastaveniach účtu.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="user-goodpassword.html" title="Zvoľte si bezpečné heslo"><span class="title">Zvoľte si bezpečné heslo</span><span class="linkdiv-dash"> — </span><span class="desc">Používajte dlhšie, viac zložitejšie heslá.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="privileges" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Užívatelia práva</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="user-admin-explain.html" title="Aké sú oprávnenia správcu?"><span class="title">Aké sú oprávnenia správcu?</span><span class="linkdiv-dash"> — </span><span class="desc">Potrebujete práva admina pre zmenu dôležitých častí vášho systému.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="user-admin-problems.html" title="Problémy v administratívnych obmedzeniach"><span class="title">Problémy v administratívnych obmedzeniach</span><span class="linkdiv-dash"> — </span><span class="desc">Môžete robiť len niektoré veci, ako je inštalácia aplikácií, ak máte práva ako administrátor.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="user-admin-change.html" title="Zmena ktorá oprávňuje správcu"><span class="title">Zmena ktorá oprávňuje správcu</span><span class="linkdiv-dash"> — </span><span class="desc">You can change which users are allowed to make changes to the system
 by giving them administrative privileges.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Užívateľské a systémové nastavenia">Užívateľské a systémové nastavenia</a><span class="desc"> — 
      <span class="link"><a href="keyboard.html" title="Klávesnica">Keyboard</a></span>,
      <span class="link"><a href="mouse.html" title="Myš">mouse</a></span>,
      <span class="link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">display</a></span>,
      <span class="link"><a href="prefs-language.html" title="Region &amp; Language">languages</a></span>,
      <span class="link"><a href="user-accounts.html" title="Užívateľský účet">user accounts</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
