<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Odaberite sigurne šifre.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#passwords" title="Šifre">Šifre</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Odaberite sigurne šifre.</span></h1></div>
<div class="region">
<div class="contents">
<div class="note note-important" title="Važna"><div class="inner"><div class="region"><div class="contents"><p class="p">Neka Vaše šifre budu dovoljno lake da ih zapamtite, ali veoma teške za druge (uključujući računarske programe) da pogode.</p></div></div></div></div>
<p class="p">Odabiranje dobrih šiifri ce Vam pomoći da Vas  računar bude siguran. Ako su vaše sifre lagane za pogoditi, neko je možze odgonetnuti i dobiti pristup Vašim ličnim informacijama.</p>
<p class="p">Ljudi mogu čak koristiti racunare da sistematski pokušaju odgonetnuti Vasu sifru, pa čak i ako je tečko za čovjeka da pogodi Vasu sifru,ipak za računarski program to može biti ekstremno lahko. Ovo su neki savjeti za odabir dobre šifre:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">Koristite kombinacije velikih i malih slova, brojeva, simbola i razmaka u lozinci. Na taj način postaje teža za pogoditi. Možete odabrati više različitih simbola, tako da bi se više mogućih lozinki moralo provjeriti kada bi neko pokušao pogoditi vašu.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Dobar način da izaberete lozinku je da uzmete prvo slovo svake riječi neke fraze koju možete zapamtiti. Fraza može biti ime nekog filma, knjige, pjesme ili albuma. Na primjer, "The Lord of the Rings: The Two Towers" će biti TLotRTTT ili tlotrttt ili tlotr:ttt.</p></div></div></div></div>
</li>
<li class="list"><p class="p">Neka Vaša šifra bude sto je moguce duža. Sto više znakova posjeduje, potrebno je više vremena osobi ili računaru da je pogodi.</p></li>
<li class="list"><p class="p">Ne koristite nijednu riječ koja se nalazi u rečnicima ili u nekom jeziku. Lozinkolomci će prvo njih isprobati. Najčešća lozinka je „password“ —— ovakvu lozinku će svako za čas da pogodi!</p></li>
<li class="list"><p class="p">Nemojte koristiti lične informacije poput datuma, broja registarskih tablica, ili ime bilo kojeg člana porodice.</p></li>
<li class="list"><p class="p">Ne koristite imenice.</p></li>
<li class="list">
<p class="p">Odaberite lozinku koju možete otkucati brzo, da biste smanjili šanse da neko ko vas je gledao zaključi šta ste otkucali.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Nikada ne zapisujte lozinke. Mogu biti pronađene!</p></div></div></div></div>
</li>
<li class="list"><p class="p">Koristite različite šifre za različite stvari.</p></li>
<li class="list">
<p class="p">Koristite različite šifre za različite korisničke naloge.</p>
<p class="p">Ako koristite iste šifre za sve vaše naloge, bilo tko ko pogodi, bit će u mogućnosti da pristupi svim Vašim nalozima.</p>
<p class="p">Može biti teško zapamtiti mnogo lozinki. Iako nije sigurno kao korištenje različitih lozinki za sve, može biti lakše koristiti istu lozinku za nebitne stvari (kao što su web stranice), i različite za bitne stvari (kao što su online bankarski računi i Vaš email).</p>
</li>
<li class="list"><p class="p">Mijenjajte Vašu šifru redovno.</p></li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#passwords" title="Šifre">Šifre</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="user-changepassword.html" title="Promijenite(mijenjajte) Vašu šifru.">Promijenite(mijenjajte) Vašu šifru.</a><span class="desc"> — Čuvajte Vas racun sigurnim čestim mijenjanjem sifre u vašim računskim postavkama.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
