<!DOCTYPE html>
<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zašto DVD ne radi?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 16.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#videos" title="Video i video kamere">Video</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zašto DVD ne radi?</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Ako ubacite DVD u vaš računar i ne započne sa puštanjem, možda nemate instalirane potrebne DVD <span class="em">kodeke</span>, ili je možda DVD iz drugog <span class="em">regiona</span>.</p></div>
<div id="codecs" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Instaliranje ispravnih kodeka iz DVD reprodukcije.</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Da bi mogli puštati DVD-ijeve, morate imati prave  <span class="em">kodeke</span> instalirane. Kodek je mali program koji omogućava aplikacijama da čitaju video ili audio formate. Ako pokušate pokrenuti DVD i nemate prave kodeke instalirane, Movie Player će vas informisati o tome i ponuditi da ih instalira za vas.</p>
<p class="p">DVD-ijevi su takođe <span class="em">copy-protected</span> pomoću sistema nazvanog CSS. Spriječava vam kopiranje DVD-ijeva, ali takođe spriječava korištenje istih osim ako nemate <span class="link"><a href="video-dvd-restricted.html" title="Kako da omogućim ograničene kodeke da pokrenu DVD-ve?">dodatni program</a></span> da skinete zaštitu.</p>
</div></div>
</div></div>
<div id="region" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjeravanje DVD regije.</span></h2></div>
<div class="region"><div class="contents">
<p class="p">DVD diskovi imaju <span class="em">kod regiona</span>, koji vam govori u kom regionu sveta je dopušteno njihovo puštanje. Ako region vašeg DVD uređaja na računaru ne odgovara regionu DVD diska koji pokušavate da pustite, nećete biti u mogućnosti da pustite DVD. Na primjer, ako je vaš DVD uređaj iz regiona 1, moći ćete da puštate DVD diskove samo iz Sjeverne Amerike.</p>
<p class="p">Često je moguće promjeniti regiju koju koristi vaš DVD čitač, ali to se može učiniti samo par puta prije nego se konačno zaključa. Da promjenite DVD regiju vašeg DVD čitača, koristite <span class="link"><a href="https://apps.ubuntu.com/cat/applications/regionset" title="https://apps.ubuntu.com/cat/applications/regionset">podesi regiju</a></span>.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#videos" title="Video i video kamere">Video</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="video-dvd-restricted.html" title="Kako da omogućim ograničene kodeke da pokrenu DVD-ve?">Kako da omogućim ograničene kodeke da pokrenu DVD-ve?</a><span class="desc"> — Mnogi komercijalni DVD-vi su kodirani i neće raditi bez softvera za dešifrovanje.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
