<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pokročilá inštalácia</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="installation.html" title="Inštalácia">Inštalácia</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="installing-upgrading.html" title="Prechod na novú verziu">Predchádzajúca</a><a class="nextlinks-next" href="kernel-crash-dump.html" title="Kernel Crash Dump">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Pokročilá inštalácia</h1></div>
<div class="region">
<div class="contents"></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="advanced-installation.html#software-raid" title="Softvérový RAID">Softvérový RAID</a></li>
<li class="links"><a class="xref" href="advanced-installation.html#lvm" title="Správca logických zväzkov (LVM)">Správca logických zväzkov (LVM)</a></li>
<li class="links"><a class="xref" href="advanced-installation.html#iscsi" title="iSCSI">iSCSI</a></li>
</ul></div>
<div class="sect2 sect" id="software-raid"><div class="inner">
<div class="hgroup"><h2 class="title">Softvérový RAID</h2></div>
<div class="region">
<div class="contents">
<p class="para">
        Redundant Array of Independent Disks "RAID" is a method of using multiple disks to provide different balances of
        increasing data reliability and/or increasing input/output performance, depending on the RAID level being used.
        RAID is implemented in either software 
        (where the operating system knows about both drives and actively maintains both of them) or hardware 
        (where a special controller makes the OS think there's only one drive and maintains the drives 'invisibly').
        </p>
<p class="para">Softvérový RAID zahrnutý v aktuálnych verziách Linuxu (a Ubuntu) je založený na ovládači <span class="app application">'mdadm'</span>  a pracuje veľmi dobre, lepšie ako niektoré takzvané 'hardverové' RAID radiče. Táto časť vás prevedie inštaláciou vydania Ubuntu Server s použitím dvoch diskových oddielov RAID1 na dvoch fyzických diskoch, jedného oddielu pre <span class="em emphasis">/</span> a druhého pre <span class="em emphasis">swap</span>.</p>
</div>
<div class="sect3 sect" id="raid-partitioning"><div class="inner">
<div class="hgroup"><h3 class="title">Rozdelenie disku na oddiely</h3></div>
<div class="region"><div class="contents">
<p class="para">Budeme nasledovať inštalačné kroky, až kým sa nedostanete ku kroku <span class="em emphasis">Rozdelenie diskov</span>. Potom:</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
 
              <p class="para">Vyberieme <span class="em emphasis">manuálny</span> spôsob rozdelenia diskových oddielov.</p>

            </li>
<li class="steps">
 
              <p class="para">Vyberieme prvý disk a odsúhlasíme otázku <span class="em emphasis">"Vytvoriť na tomto zariadení novú prázdnu tabuľku oblastí?"</span>.</p>

              <p class="para">Tento krok zopakujeme na každom disku, ktorý chceme zaradiť do poľa RAID.</p>

            </li>
<li class="steps">
 
              <p class="para">Označíme <span class="em emphasis">"VOĽNÉ MIESTO"</span> na prvom disku a potom zvolíme <span class="em emphasis">"Vytvoriť novú oblasť"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Následne zvolíme <span class="em emphasis">veľkosť</span> oblasti. Táto oblasť bude swap a vo všeobecnosti platí, že veľkosť <span class="em emphasis">swap</span> je dvojnásobok RAM. Zadáme veľkosť, zvolíme <span class="em emphasis">Primárna</span>  a potom <span class="em emphasis">Začiatok</span>.</p>

              <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
                <p class="para">
                A swap partition size of twice the available RAM capacity may not always be desirable, especially on systems with large amounts of RAM.
                Calculating the swap partition size for servers is highly dependent on how the system is going to be used.
                </p>
              </div></div></div></div>

            </li>
<li class="steps">
 
              <p class="para">Vyberieme <span class="em emphasis">"Použiť ako:"</span> v hornom riadku a zmeňíme predvolenú hodnotu <span class="em emphasis">"žurnálovací súborový systém Ext4"</span>, na <span class="em emphasis">"fyzický zväzok pre RAID"</span>, a potom zvolíme <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Pre partíciu <span class="em emphasis">/</span> znova vyberieme <span class="em emphasis">"Voľné miesto"</span> na prvom disku a potom vyberieme <span class="em emphasis">"Vytvoriť novú oblasť"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Použijeme zvyšok voľného miesta na disku a zvolíme <span class="em emphasis">Pokračovať</span>, a potom <span class="em emphasis">Primárna</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Tak, ako pri oblasti swap, vyberieme <span class="em emphasis">"Použiť ako:"</span> v hornom riadku, zmeníme voľbu na <span class="em emphasis">"fyzický zväzok pre RAID"</span>, a potom zvolíme  <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Zopakujeme kroky tri až osem pre ostatné disky a oblasti.</p>

            </li>
</ol></div></div>
</div></div>
</div></div>
<div class="sect3 sect" id="raid-configuration"><div class="inner">
<div class="hgroup"><h3 class="title">Nastavenie poľa RAID</h3></div>
<div class="region"><div class="contents">
<p class="para">Vďaka nastaveniu oblastí teraz môžme nastaviť diskové pole:</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
 
              <p class="para">Vrátime sa späť na "Rozdelenie diskov" a vyberieme <span class="em emphasis">"Nastaviť softvérový RAID"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Vyberieme <span class="em emphasis">"áno"</span>, aby sa zmeny zapísali na disk.</p>

            </li>
<li class="steps">
 
              <p class="para">Zvolíme <span class="em emphasis">"Vytvoriť MD zariadenie"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">V našom prípade vyberieme <span class="em emphasis">"RAID1"</span>, ale ak by sme chceli iné nastavenie, môžeme zvoliť jemu prislúchajúci typ (RAID0 RAID1 RAID5).</p>

              <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
                <p class="para">Ak chcete použiť <span class="em emphasis">RAID5</span>, potrebujete najmenej <span class="em emphasis">tri</span> disky. Použitie RAID0 alebo RAID1, vyžaduje iba <span class="em emphasis">dva</span> disky.</p>
              </div></div></div></div>

            </li>
<li class="steps">
 
              <p class="para">Zadáme počet aktívnych zariadení <span class="em emphasis">"2"</span>, alebo iný počet pevných diskov, ktoré máme pre pole k dispozícii. Potom zvolíme <span class="em emphasis">"Pokračovať"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Ďalej zadáme počet náhradných zariadení <span class="em emphasis">"0"</span> a zvolíme <span class="em emphasis">"Pokračovať"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Označíme, ktoré oblasti chceme použiť. Najčastejšie to bývajú oblasti sda1, sdb1, sdc1, atď. Čísla sa väčšinou zhodujú, písmená sa odlišujú a prislúchajú rozdielnym pevným diskom.</p>

              <p class="para">Pre oblasť <span class="em emphasis">swap</span> vyberieme <span class="em emphasis">sda1</span> a <span class="em emphasis">sdb1</span> a prejdeme na ďalší krok voľbou <span class="em emphasis">"Pokračovať"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Kroky <span class="em emphasis">tri</span> až <span class="em emphasis">sedem</span> zopakujeme pre oblasť <span class="em emphasis">/</span>, pričom vyberieme <span class="em emphasis">sda2</span> a <span class="em emphasis">sdb2</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Ak sme skončili, zvolíme <span class="em emphasis">"Dokončiť"</span>.</p>

            </li>
</ol></div></div>
</div></div>
</div></div>
<div class="sect3 sect" id="raid-formatting"><div class="inner">
<div class="hgroup"><h3 class="title">Formátovanie</h3></div>
<div class="region"><div class="contents">
<p class="para">Teraz by sme mali vidieť zoznam diskov a RAID zariadení. Ďalším krokom je formátovanie a nastavenie ich bodu pripojenia. Zariadenie RAID budeme považovať za bežný lokálny disk, ktorý môžeme rovnako naformátovať a pripojiť.</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
 
              <p class="para">Vyberieme <span class="em emphasis">"č. 1"</span> oblasť <span class="em emphasis">"RAID1 zariadenie č. 0"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Zvolíme <span class="em emphasis">""Použiť ako:"</span>. Potom vyberieme <span class="em emphasis">"odkladací swap priestor"</span>, a následne <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para"># Potom vyberieme <span class="em emphasis">"č. 1"</span> oblasť <span class="em emphasis">"RAID1 zariadenie č. 1"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Zvolíme <span class="em emphasis">"Použiť ako:"</span>. Potom vyberieme <span class="em emphasis">"žurnálovací súborový systém Ext4"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Teraz zvolíme <span class="em emphasis">"Bod pripojenia"</span> a vyberieme <span class="em emphasis">"/ - koreňový súborový systém"</span>. Zmeníme ostatné nastavenia podľa potreby a vyberieme <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Nakoniec vyberieme <span class="em emphasis">"Ukončiť rozdeľovanie a zapísať zmeny na disk"</span>.</p>

            </li>
</ol></div></div>
<p class="para">Ak nastavíme, že koreňová oblasť má byť v poli RAID, inštalátor sa nás opýta, či chceme systém zavádzať v <span class="em emphasis">degradovanom stave</span>. Podrobnosti sa nachádzajú v časti <a class="xref" href="advanced-installation.html#raid-degraded" title="Degradované pole RAID">Degradované pole RAID</a>.</p>
<p class="para">Inštalačný proces bude potom normálne pokračovať.</p>
</div></div>
</div></div>
<div class="sect3 sect" id="raid-degraded"><div class="inner">
<div class="hgroup"><h3 class="title">Degradované pole RAID</h3></div>
<div class="region"><div class="contents">
<p class="para">Počas dlhej prevádzky počítača môže nastať porucha disku. Ak je takýto disk súčasťou softvérového poľa RAID, operačný systém prepne pole do tzv. <span class="em emphasis">degradovaného</span> stavu.</p>
<p class="para">Ak pole prejde do degradovaného stavu kvôli možnosti poškodenia dát, Ubuntu Server sa po 30 sekundách reštartuje do tzv. <span class="em emphasis">initramfs</span> režimu. Keď je initramfs zavedený, objaví sa na pätnásť sekúnd výzva umožňujúca opustiť tento režim a zaviesť systém alebo sa pokúsiť o ručnú opravu. Naštartovanie do initramfs môže ale aj nemusí byť želaným správaním, najmä ak ide o vzdialený počítač. Zavedenie systému do degradovaného poľa môže byť nastavené rôznymi spôsobmi:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">

              <p class="para">Nástroj <span class="app application">dpkg-reconfigure</span> môže byť použitý na nakonfigurovanie základného správania. Počas tohto procesu budeme môcť zadať dodatočné nastavenia týkajúce sa poľa. Napríklad monitorovanie, upozorňovanie emailom, atď. Ak chceme zmeniť nastavenie <span class="app application">mdadm</span> zadáme príkaz:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo dpkg-reconfigure mdadm</span>
</pre></div>

             </li>
<li class="list itemizedlist">

              <p class="para">Proces <span class="cmd command">dpkg-reconfigure mdadm</span> mdadm zmení konfiguračný súbor <span class="file filename">/etc/initramfs-tools/conf.d/mdadm</span>. Tento súbor má tú výhodu, že pomocou neho dokážeme predkonfigurovať správanie systému a môžeme ho ručne upravovať:</p>

<div class="code"><pre class="contents ">BOOT_DEGRADED=true
</pre></div>

          <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Nastavenie v súbore môže byť prevážené parametrom jadra Kernel.</p>
          </div></div></div></div>          

            </li>
<li class="list itemizedlist">
    
              <p class="para">Pomocou parametra jadra Kernel sa systém tiež dá zaviesť do degradovaného poľa:</p>

              <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
                  <p class="para">Keď sa server začína zavádzať, stlačíme <span class="key keycap"><kbd>Shift</kbd></span>, čím otvoríme ponuku zavádzacieho systému Grub.</p>
                </li>
<li class="list itemizedlist">
                  <p class="para">Stlačením <span class="key keycap"><kbd>e</kbd></span> zvolíme možnosť úpravy parametrov jadra Kernel.</p>
                </li>
<li class="list itemizedlist">
                  <p class="para">Stlačíme šípku <span class="key keycap"><kbd>DOLE</kbd></span>, aby sa označil riadok s Kernelom.</p>
                </li>
<li class="list itemizedlist">
                  <p class="para">Na koniec riadka dopíšeme "bootdegraded=true" (bez úvodzoviek).</p>
                </li>
<li class="list itemizedlist">
                  <p class="para">Nakoniec stlačíme kombináciu kláves <span class="keyseq keycombo"><span class="key keycap"><kbd>Ctrl</kbd></span>+<span class="key keycap"><kbd>x</kbd></span></span>, aby sa systém zaviedol.</p>
                </li>
</ul></div>

            </li>
</ul></div>
<p class="para">Po zavedení systému môžeme pole buď opraviť, ako sa hovorí v časti <a class="xref" href="advanced-installation.html#raid-maintenance" title="Údržba poľa RAID">Údržba poľa RAID</a>, alebo skopírovať dôležité dáta na iný počítač kvôli neopraviteľnému zlyhaniu hardvéru.</p>
</div></div>
</div></div>
<div class="sect3 sect" id="raid-maintenance"><div class="inner">
<div class="hgroup"><h3 class="title">Údržba poľa RAID</h3></div>
<div class="region"><div class="contents">
<p class="para">Nástroj <span class="app application">mdadm</span> sa dá použitý na zobrazenie stavu poľa, pridanie diskov do poľa, odobranie diskov, atď:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para">Ak chceme zobraziť stav poľa, do príkazového riadka zadáme príkaz:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo mdadm -D /dev/md0</span>
</pre></div>
            
              <p class="para">Voľba <span class="em emphasis">-D</span> hovorí <span class="app application">mdadm</span>, aby zobrazil detailné informácie o zariadení <span class="file filename">/dev/md0</span>. Cestu <span class="file filename">/dev/md0</span> nahradíme prislúchajúcou cestou zariadenia RAID.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Ak chceme vidieť stav disku v poli, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo mdadm -E /dev/sda1</span>
</pre></div>
              <p class="para">Výstup bude veľmi podobný príkazu <span class="cmd command">mdadm -D</span>. Ak chceme iný disk, zmeníme <span class="file filename">/dev/sda1</span>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Ak disk zlyhá a je ho potrebné odobrať z poľa, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo mdadm --remove /dev/md0 /dev/sda1</span>
</pre></div>
              <p class="para">Cesty <span class="file filename">/dev/md0</span> a <span class="file filename">/dev/sda1</span> zmeníme na prislúchjúce cesty k zariadeniu RAID a disku.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Podobne pridáme nový disk:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo mdadm --add /dev/md0 /dev/sda1</span>
</pre></div>
            </li>
</ul></div>
<p class="para">Niekedy disk prejde do <span class="em emphasis">chybného</span> stavu, aj keď nie je fyzicky poškodený. Takýto disk zvyčajne stačí z poľa odstrániť a znova ho pridať. Pole sa potom znova zosynchronizuje. Ak sa disk nezosynchronizuje s poľom, znamená to, že je asi chybný.</p>
<p class="para">Súbor <span class="file filename">/proc/mdstat</span> tiež obsahuje užitočné informácie o systémových zariadeniach RAID:</p>
<div class="screen"><pre class="contents "><span class="cmd command">cat /proc/mdstat</span>
<span class="output computeroutput">Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md0 : active raid1 sda1[0] sdb1[1]
      10016384 blocks [2/2] [UU]
      
unused devices: &lt;none&gt;</span>
</pre></div>
<p class="para">Nasledujúci príkaz je výborný na sledovanie stavu synchronizácie diskov:</p>
<div class="screen"><pre class="contents "><span class="cmd command">watch -n1 cat /proc/mdstat</span>
</pre></div>
<p class="para">Ak chceme sledovanie pomocou nástroja <span class="app application">watch</span> prerušiť, stlačíme <span class="em emphasis">Ctrl+c</span>.</p>
<p class="para">Ak bolo potrebné vymeniť disk kvôli chybe, po výmene a zosynchronizovaní disku je ešte potrebné nainštalovať <span class="app application">grub</span>. Ak chceme <span class="app application">grub</span> nainštalovať na nový disk, zadáme príkaz:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo grub-install /dev/md0</span>
</pre></div>
<p class="para">Cestu <span class="file filename">/dev/md0</span> nahradíme prislúchajúcou cestou k poľu RAID.</p>
</div></div>
</div></div>
<div class="sect3 sect" id="raid-resources"><div class="inner">
<div class="hgroup"><h3 class="title">Zdroje</h3></div>
<div class="region"><div class="contents">
<p class="para">Problematika diskových polí RAID je vďaka množstvu spôsobov, akým môžu byť nastavené, veľmi rozsiahla. Viac informácií sa nachádza v anglickom jazyku na nasledujúcich stránkach:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para"><a href="https://help.ubuntu.com/community/Installation#raid" class="ulink" title="https://help.ubuntu.com/community/Installation#raid">Ubuntu Wiki Articles on RAID</a>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <a href="http://www.faqs.org/docs/Linux-HOWTO/Software-RAID-HOWTO.html" class="ulink" title="http://www.faqs.org/docs/Linux-HOWTO/Software-RAID-HOWTO.html">Software RAID HOWTO</a>
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <a href="http://oreilly.com/catalog/9781565927308/" class="ulink" title="http://oreilly.com/catalog/9781565927308/">Managing RAID on Linux</a>
              </p>
            </li>
</ul></div>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="lvm"><div class="inner">
<div class="hgroup"><h2 class="title">Správca logických zväzkov (LVM)</h2></div>
<div class="region">
<div class="contents"><p class="para">Správca logických zväzkov (<span class="em emphasis">LVM</span>) umožňuje správcom vytvoriť <span class="em emphasis">logické</span> zväzky z jedného alebo viacerých fyzických diskov. LVM zväzky môžeme vytvoriť na štandardných oddieloch vytvorených na fyzických diskoch, ale aj na oddieloch diskového poľa RAID. Zväzky môžu byť aj rozšírené, čo systémom poskytuje väčšiu flexibilitu, keď potrebujeme niečo zmeniť.</p></div>
<div class="sect3 sect" id="lvm-overview"><div class="inner">
<div class="hgroup"><h3 class="title">Prehľad</h3></div>
<div class="region"><div class="contents">
<p class="para">Vedľajším efektom sily a flexibility LVM je jeho väčšia komplikovanosť. Pred tým, ako sa pustíme do inštalácie LVM, bude lepšie, ak sa oboznámime s niektorými termínmi.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para">
              <span class="em emphasis">Physical Volume (PV):</span> physical hard disk, disk partition or software RAID partition
              formatted as LVM PV.
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <span class="em emphasis">Volume Group (VG):</span> is made from one or more physical volumes. A VG can can be
              extended by adding more PVs. A VG is like a virtual disk drive, from which one or more logical volumes are carved.
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <span class="em emphasis">Logical Volume (LV):</span> is similar to a partition in a non-LVM system. A LV is formatted
              with the desired file system (EXT3, XFS, JFS, etc), it is then available for mounting and data storage.
              </p>
            </li>
</ul></div>
</div></div>
</div></div>
<div class="sect3 sect" id="lvm-installation"><div class="inner">
<div class="hgroup"><h3 class="title">Inštalácia</h3></div>
<div class="region"><div class="contents">
<p class="para">Použitie LVM si ukážeme na na príklade, v ktorom  pripojíme priečinok /srv k zväzku LVM. Počas počiatočnej inštalácie použijeme iba jeden fyzický zväzok (PV), ktorý bude časťou skupiny zväzkov (VG). Ďalší PV pridáme po skončení inštalácie, aby sme demonštrovali, ako sa dá VG rozšíriť.</p>
<p class="para">Pri inštalácii systému máte k dispozícii niekoľko možností, ktoré nastavia LVM. Možnosť <span class="em emphasis">"Sprievodca - použiť celý disk a nastaviť LVM"</span>, ktorá Vám umožní použiť časti voľného priestoru pre LVM, <span class="em emphasis">"Sprievodca - použiť celý disk a nastaviť šifrované LVM"</span>, alebo <span class="em emphasis">Manuálne</span> nastaviť oddiely a nastaviť LVM. Ak chceme nastaviť systém tak, aby súčasne používal LVM aj štandardné diskové oddiely, musíme vybrať manuálny spôsob.</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">

              <p class="para">Budeme nasledovať inštalačné kroky, až kým sa nedostanete ku kroku <span class="em emphasis">Rozdelenie diskov</span>. Potom:</p>

            </li>
<li class="steps">
 
              <p class="para">Na obrazovke <span class="em emphasis">Rozdelenie diskov</span> zvolíme <span class="em emphasis">"Manuálne"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Vyberieme disk a výberom "áno" odsúhlasíme otázku <span class="em emphasis">"Vytvoriť na tomto zariadení novú prázdnu tabuľku oblastí?"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Potom vytvoríme bežné oddiely pre priečinky<span class="em emphasis">/boot</span>, <span class="em emphasis">swap</span> a <span class="em emphasis">/</span> so súborovým systémom aký nám vyhovuje.</p>

            </li>
<li class="steps">
 
              <p class="para">Pre LVM  priečinok <span class="em emphasis">/srv</span>, vytvoríme novú logickú oblasť. Potom zmeníme <span class="em emphasis">"Použiť ako"</span> na <span class="em emphasis">"fyzický zväzok pre LVM"</span> a zvolíme <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Teraz vyberieme <span class="em emphasis">"Nastavenie správcu logických zväzkov (LVM)"</span> v hornej časti ponuky a výberom <span class="em emphasis">"Áno"</span> potvrdíme zápis zmien na disk.</p>

            </li>
<li class="steps">
 
              <p class="para">V časti <span class="em emphasis">"Krok nastavenia LVM"</span> na ďalšej obrazovke zvolíme <span class="em emphasis">"Vytvoriť skupinu zväzkov"</span>. Ako názov skupiny zväzkov zadáme napríklad <span class="em emphasis">vg01</span> alebo niečo viacvravnejšie. Po zadaní mena označíme oddiel, ktorý sme nastavili pre LVM a zvolíme <span class="em emphasis">"Pokračovať"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Na obrazovke s ponukou <span class="em emphasis">"Krok nastavenia LVM"</span> vyberieme <span class="em emphasis">"Vytvoriť logický zväzok"</span>. Vyberieme novovytvorenú skupinu zväzkov a zadáme názov nového logického zväzku, napríklad srv podľa miesta, kam ho chceme pripojiť. Potom zvolíme veľkosť, ktorá môže pokojne obsiahnuť celé dostupné miesto, pretože sa dá neskôr rozšíriť. Zvolíme <span class="em emphasis">"Ukončiť"</span>, čím sa vrátime späť na hlavnú obrazovku <span class="em emphasis">"Rozdelenie diskov"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Teraz priradíme súborový systém novému LVM. Vyberieme oddiel <span class="em emphasis">"LVM VG vg01, LV srv"</span> (resp. s menami, aké sme použili) a potom zmeníme <span class="em emphasis">Použiť ako</span>. Nastavíme súborový systém a vyberieme /srv ako bod pripojenia. Po skončení zvolíme <span class="em emphasis">"Nastavenie oblasti ukončené"</span>.</p>

            </li>
<li class="steps">
 
              <p class="para">Nakoniec vyberieme <span class="em emphasis">"Ukončiť rozdeľovanie a zapísať zmeny na disk"</span>. Potvríme zmeny a dokončíme inštaláciu systému.</p>

            </li>
</ol></div></div>
<p class="para">Existuje niekoľko užitočných nástrojov, ktoré zobrazujú informácie o LVM:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist"><p class="para"><span class="em emphasis">pvdisplay:</span> shows information about Physical Volumes.</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">vgdisplay:</span> zobrazí informácie o zviazaných zväzkoch.</p></li>
<li class="list itemizedlist"><p class="para"><span class="em emphasis">lvdisplay:</span> shows information about Logical Volumes.</p></li>
</ul></div>
</div></div>
</div></div>
<div class="sect3 sect" id="lvm-extending"><div class="inner">
<div class="hgroup"><h3 class="title">Rozširovanie skupiny zväzkov</h3></div>
<div class="region"><div class="contents">
<p class="para">
          Continuing with <span class="em emphasis">srv</span> as an LVM volume example, this section covers adding a second hard disk, creating
          a Physical Volume (PV), adding it to the volume group (VG), extending the logical volume <span class="file filename">srv</span>
          and finally extending the filesystem. This example assumes a second hard disk has been added to the system. In
          this example, this hard disk will be named <span class="file filename">/dev/sdb</span> and we will use the entire disk as a physical volume 
          (you could choose to create partitions and use them as different physical volumes)
          </p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
          <p class="para">
              Make sure you don't already have an existing <span class="file filename">/dev/sdb</span> before issuing the commands below. You could lose some data if you issue those commands on a non-empty disk. 
          </p>
        </div></div></div></div>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
 
              <p class="para">Najskôr vytvoríme fyzický zväzok zadaním príkazu:</p>

                <div class="screen"><pre class="contents "><span class="cmd command">sudo pvcreate /dev/sdb</span>
                </pre></div>

            </li>
<li class="steps">

              <p class="para">Teraz rozšírime skupinu zväzkov:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo vgextend vg01 /dev/sdb</span>
</pre></div>

            </li>
<li class="steps">

              <p class="para">Použijeme príkaz <span class="app application">vgdisplay</span> na zistenie počtu voľných tzv. physical extents (PE), ktoré predstavujú počet voľných alokovateľných blokov. Dostaneme napríklad veľkosť 511 PE (čo zodpovedá 2GB, kde každý PE bude mať veľkosť 4MB) a použijeme celé dostupné voľné miesto. Vy môžete použiť vlastný počet PE.</p>

              <p class="para">Teraz sa dá logický zväzok rôznymi spôsobmi rozšíriť. My si ukážeme, ako sa to dá pomocou PE:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo lvextend /dev/vg01/srv -l +511</span>
</pre></div>

              <p class="para">Voľba <span class="em emphasis">-l</span> umožní rozšíriť logický zväzok pomocou PE. Voľba <span class="em emphasis">-L</span> umožňuje logický zväzok rozšíriť pomocou jednotiek Mega, Giga, Tera bajty.</p>

            </li>
<li class="steps">
 
              <p class="para">
              Even though you are supposed to be able to <span class="em emphasis">expand</span> an ext3 or ext4 filesystem without unmounting it first, 
              it may be a good practice to unmount it anyway and check the filesystem, so that you don't mess up the day you want to reduce
              a logical volume (in that case unmounting first is compulsory).
              </p>

              <p class="para">Nasledujúce príkazy sú určené iba pre súborové systémy EXT3 alebo EXT4. Ak používate iný súborový systém, môžete použiť niektoré iné dostupné nástroje.</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo umount /srv</span>
<span class="cmd command">sudo e2fsck -f /dev/vg01/srv</span>
</pre></div>

              <p class="para">Voľba <span class="em emphasis">-f</span> nástroja <span class="app application">e2fsck</span> skontroluje disk aj napriek tomu, že vyzerá byť prázdny.</p>

            </li>
<li class="steps">
 
              <p class="para">Zväčšíme súborový systém:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo resize2fs /dev/vg01/srv</span>
</pre></div>

            </li>
<li class="steps">
 
              <p class="para">A nakoniec oddiel pripojíme a skontrolujeme jeho veľkosť.</p>

<div class="screen"><pre class="contents "><span class="cmd command">mount /dev/vg01/srv /srv &amp;&amp; df -h /srv</span>
</pre></div>

            </li>
</ol></div></div>
</div></div>
</div></div>
<div class="sect3 sect" id="lvm-resources"><div class="inner">
<div class="hgroup"><h3 class="title">Zdroje</h3></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para">Za pozretie stojí stránka <a href="https://help.ubuntu.com/community/Installation#lvm" class="ulink" title="https://help.ubuntu.com/community/Installation#lvm">Ubuntu Wiki LVM Articles</a>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Viac informácií sa dozviete na stránke <a href="http://tldp.org/HOWTO/LVM-HOWTO/index.html" class="ulink" title="http://tldp.org/HOWTO/LVM-HOWTO/index.html">LVM HOWTO</a>.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">Iný dobrý článok je <a href="http://www.linuxdevcenter.com/pub/a/linux/2006/04/27/managing-disk-space-with-lvm.html" class="ulink" title="http://www.linuxdevcenter.com/pub/a/linux/2006/04/27/managing-disk-space-with-lvm.html">Managing Disk Space with LVM</a> na O'Reillyho stránke linuxdevcenter.com.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              For more information on <span class="app application">fdisk</span> see the
              <a href="http://manpages.ubuntu.com/manpages/xenial/en/man8/fdisk.8.html" class="ulink" title="http://manpages.ubuntu.com/manpages/xenial/en/man8/fdisk.8.html">fdisk man page</a>.
              </p>
            </li>
</ul></div></div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="iscsi"><div class="inner">
<div class="hgroup"><h2 class="title">iSCSI</h2></div>
<div class="region">
<div class="contents"><p class="para">The iSCSI protocol can be used to install Ubuntu on systems with
        or without hard disks attached.</p></div>
<div class="sect3 sect"><div class="inner">
<div class="hgroup"><h3 class="title">Installation on a diskless system</h3></div>
<div class="region"><div class="contents">
<p class="para">The first steps of a diskless iSCSI installation are identical
          to the <a class="xref" href="installing-from-cd.html" title="Inštalácia">Inštalácia</a> section up to "Hard drive
          layout".</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
              <p class="para">The installer will display a warning with the following
              message:</p>

              <div class="screen"><pre class="contents ">No disk drive was detected. If you know the name of the driver needed by your disk drive, you can select it from the list.</pre></div>
            </li>
<li class="steps">
              <p class="para">Select the item in the list titled <span class="em emphasis">login to iSCSI
              targets.</span></p>
            </li>
<li class="steps">
              <p class="para">You will be prompted to Enter an IP address to scan for
              iSCSI targets with a description of the format for the address.
              Enter the IP address for the location of your iSCSI target and
              navigate to <span class="em emphasis">&lt;continue&gt;</span> then hit
              <span class="key keycap"><kbd>ENTER</kbd></span></p>
            </li>
<li class="steps">
              <p class="para">If authentication is required in order to access the iSCSI
              device, provide the <span class="em emphasis">username</span> in the next
              field. Otherwise leave it blank.</p>
            </li>
<li class="steps">
              <p class="para">If your system is able to connect to the iSCSI provider, you
              should see a list of available iSCSI targets where the operating
              system can be installed. The list should be similar to the
              following :</p>

              <div class="screen"><pre class="contents ">Select the iSCSI targets you wish to use.

iSCSI targets on 192.168.1.29:3260:

[ ] iqn.2016-03.TrustyS-iscsitarget:storage.sys0

&lt;Go Back&gt;                          &lt;Continue&gt;

</pre></div>
            </li>
<li class="steps">
              <p class="para">Select the iSCSI target that you want to use with the space
              bar. Use the arrow keys to navigate to the target that you want to
              select.</p>
            </li>
<li class="steps">
              <p class="para">Navigate to <span class="em emphasis">&lt;Continue&gt;</span> and hit
              <span class="key keycap"><kbd>ENTER</kbd></span>.</p>
            </li>
</ol></div></div>
<p class="para">If the connection to the iSCSI target is successful, you will be
          prompted with the <span class="em emphasis">[!!] Partition disks</span>
          installation menu. The rest of the procedure is identical to any
          normal installation on attached disks. Once the installation is
          completed, you will be asked to reboot.</p>
</div></div>
</div></div>
<div class="sect3 sect"><div class="inner">
<div class="hgroup"><h3 class="title">Installation on a system with disk attached</h3></div>
<div class="region"><div class="contents">
<p class="para">Again, the iSCSI installation on a normal server with one or
          many disks attached is identical to the <a class="xref" href="installing-from-cd.html" title="Inštalácia">Inštalácia</a> section until we reach the disk
          partitioning menu. Instead of using any of the Guided selection, we
          need to perform the following steps :</p>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
              <p class="para">Navigate to the Manual menu entry</p>
            </li>
<li class="steps">
              <p class="para">Select the Configure iSCSI Volumes menu entry</p>
            </li>
<li class="steps">
              <p class="para">Choose the Log into iSCSI targets</p>
            </li>
<li class="steps">
              <p class="para">You will be prompted to Enter an IP address to scan for
              iSCSI targets. with a description of the format for the address.
              Enter the IP address and navigate to
              <span class="em emphasis">&lt;continue&gt;</span> then hit <span class="key keycap"><kbd>ENTER</kbd></span></p>
            </li>
<li class="steps">
              <p class="para">If authentication is required in order to access the iSCSI
              device, provide the <span class="em emphasis">username</span> in the next
              field or leave it blank.</p>
            </li>
<li class="steps">
              <p class="para">If your system is able to connect to the iSCSI provider, you
              should see a list of available iSCSI targets where the operating
              system can be installed. The list should be similar to the
              following :</p>

            <div class="screen"><pre class="contents ">Select the iSCSI targets you wish to use.

iSCSI targets on 192.168.1.29:3260:

[ ] iqn.2016-03.TrustyS-iscsitarget:storage.sys0

&lt;Go Back&gt;                          &lt;Continue&gt;
</pre></div>
            </li>
<li class="steps">
              <p class="para">Select the iSCSI target that you want to use with the space
              bar. Use the arrow keys to navigate to the target that you want to
              select</p>
            </li>
<li class="steps">
              <p class="para">Navigate to &lt;Continue&gt; and hit <span class="key keycap"><kbd>ENTER</kbd></span>.</p>
            </li>
<li class="steps">
              <p class="para">If successful, you will come back to the menu asking you to
              Log into iSCSI targets. Navigate to Finish and hit <span class="key keycap"><kbd>ENTER</kbd></span></p>
            </li>
</ol></div></div>
<p class="para">The newly connected iSCSI disk will appear in the overview
          section as a device prefixed with SCSI. This is the disk that you
          should select as your installation disk. Once identified, you can
          choose any of the partitioning methods.</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
            <p class="para">Depending on your system configuration, there may be other
            SCSI disks attached to the system. Be very careful to identify the
            proper device before proceeding with the installation. Otherwise,
            irreversible data loss may result from performing an installation on
            the wrong disk.</p>
          </div></div></div></div>
</div></div>
</div></div>
<div class="sect3 sect"><div class="inner">
<div class="hgroup"><h3 class="title">Rebooting to an iSCSI target</h3></div>
<div class="region"><div class="contents">
<p class="para">The procedure is specific to your hardware platform. As an
          example, here is how to reboot to your iSCSI target using iPXE</p>
<div class="screen"><pre class="contents ">iPXE&gt; dhcp

Configuring (net0 52:54:00:a4:f2:a9)....... ok

iPXE&gt; sanboot iscsi:192.168.1.29::::iqn.2016-03.TrustyS-iscsitarget:storage.sys0
</pre></div>
<p class="para">If the procedure is successful, you should see the Grub menu
          appear on the screen.</p>
</div></div>
</div></div>
</div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="installing-upgrading.html" title="Prechod na novú verziu">Predchádzajúca</a><a class="nextlinks-next" href="kernel-crash-dump.html" title="Kernel Crash Dump">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
