<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Shell skripty</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="backups.html" title="Zálohovanie">Zálohovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="backups.html" title="Zálohovanie">Predchádzajúca</a><a class="nextlinks-next" href="backups-shellscripts-rotation.html" title="Rotácia archívov">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Shell skripty</h1></div>
<div class="region">
<div class="contents">
<p class="para">
    One of the simplest ways to backup a system is using a <span class="em emphasis">shell script</span>.  For example, a script can be used to configure 
    which directories to backup, and pass those directories as arguments to the <span class="app application">tar</span> utility, which creates
    an archive file. The archive file can then be moved or copied to another location.  The archive can also be created on a remote 
    file system such as an <span class="em emphasis">NFS</span> mount.
    </p>
<p class="para">
    The <span class="app application">tar</span> utility creates one archive file out of many files or directories.  <span class="app application">tar</span> 
    can also filter the files through compression utilities, thus reducing the size of the archive file.  
    </p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="backup-shellscripts.html#backup-shellscript" title="Jednoduchý skript">Jednoduchý skript</a></li>
<li class="links"><a class="xref" href="backup-shellscripts.html#backup-executing-shellscript" title="Spustenie skriptu">Spustenie skriptu</a></li>
<li class="links"><a class="xref" href="backup-shellscripts.html#backup-shellscript-archive-testing" title="Obnovenie údajov z archívu">Obnovenie údajov z archívu</a></li>
<li class="links"><a class="xref" href="backup-shellscripts.html#backup-shellscript-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="backup-shellscript"><div class="inner">
<div class="hgroup"><h2 class="title">Jednoduchý skript</h2></div>
<div class="region"><div class="contents">
<p class="para">Nasledujúci skript použije nástroj <span class="app application">tar</span> na vytvorenie archívu na vzdialenom súborovom systéme, ktorý je pripojený pomocou systému NFS. Meno súboru s archívom sa odvodí od dátumu a názvu počítača.</p>
<div class="code"><pre class="contents ">#!/bin/bash
####################################
#
# Backup to NFS mount script.
#
####################################

# What to backup. 
backup_files="/home /var/spool/mail /etc /root /boot /opt"

# Where to backup to.
dest="/mnt/backup"

# Create archive filename.
day=$(date +%A)
hostname=$(hostname -s)
archive_file="$hostname-$day.tgz"

# Print start status message.
echo "Backing up $backup_files to $dest/$archive_file"
date
echo

# Backup the files using tar.
tar czf $dest/$archive_file $backup_files

# Print end status message.
echo
echo "Backup finished"
date

# Long listing of files in $dest to check file sizes.
ls -lh $dest
</pre></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">$backup_files:</span> premenná, ktorá obsahuje zoznam priečinkov, ktoré sa majú zálohovať. Tento zoznam si môžeme upraviť podľa našich potrieb.</p>
        </li>
<li class="list itemizedlist">           
          <p class="para">
     	  <span class="em emphasis">$day:</span> a variable holding the day of the week (Monday, Tuesday, Wednesday, etc).  This is used to create 
          an archive file for each day of the week, giving a backup history of seven days.  There are other ways to accomplish
          this including using the <span class="app application">date</span> utility. 
          </p>
        </li>
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">$hostname:</span> premenná, ktorá obsahuje <span class="em emphasis">krátky</span> názov stanice. Vďaka tomuto menu rozoznáme, z ktorého počítača záloha pochádza, v prípade, že na rovnaké miesto ukladáme zálohy z viacerých počítačov.</p>
        </li>
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">$archive_file:</span> celé meno súboru s archívom.</p>
        </li>
<li class="list itemizedlist">           
          <p class="para">
   	  <span class="em emphasis">$dest:</span> destination of the archive file.  The directory needs to be created and in this case 
          <span class="em emphasis">mounted</span> before executing the backup script.  See <a class="xref" href="network-file-system.html" title="Sieťový súborový systém (NFS)">Sieťový súborový systém (NFS)</a> for details of
          using <span class="em emphasis">NFS</span>.
          </p>
        </li>
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">stavové správy:</span> toto sú voliteľné správy, ktoré sa vypíšu pomocou nástroja <span class="app application">echo</span> na počítači, aby používateľ vedel, čo sa na počítači deje.</p>
        </li>
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">tar czf $dest/$archive_file $backup_files:</span> príkaz <span class="app application">tar</span> sa využíva na vytvorenie archívu.</p>
  	  <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">           
              <p class="para"><span class="em emphasis">c:</span> vytvorí archív.</p>
            </li>
<li class="list itemizedlist">           
              <p class="para"><span class="em emphasis">z:</span> použije kompresiu <span class="app application">gzip</span>.</p>
            </li>
<li class="list itemizedlist">           
              <p class="para">
      	      <span class="em emphasis">f:</span> output to an archive file.  Otherwise the <span class="app application">tar</span> output will be sent to STDOUT.
              </p>
            </li>
</ul></div>
        </li>
<li class="list itemizedlist">           
          <p class="para"><span class="em emphasis">ls -lh $dest:</span> voliteľný príkaz ktorý zobrazí <span class="em emphasis">-l</span> dlhý výpis cieľového priečinka <span class="em emphasis">-h</span> v tvare zrozumiteľnom pre človeka. Tento príkaz je užitočný, ak sa chceme uistiť, že bol súbor vytvorený a aká je jeho veľkosť.</p>
        </li>
</ul></div>
<p class="para">
      This is a simple example of a backup shell script; however there are many options that can be included in such a script.
      See <a class="xref" href="backup-shellscripts.html#backup-shellscript-references" title="Zdroje">Zdroje</a> for links to resources providing more in-depth shell scripting information.
      </p>
</div></div>
</div></div>
<div class="sect2 sect" id="backup-executing-shellscript"><div class="inner">
<div class="hgroup"><h2 class="title">Spustenie skriptu</h2></div>
<div class="region">
<div class="contents"></div>
<div class="sect3 sect" id="backup-script-execute-shell"><div class="inner">
<div class="hgroup"><h3 class="title">Spustenie z príkazového riadka</h3></div>
<div class="region"><div class="contents">
<p class="para">
        The simplest way of executing the above backup script is to copy and paste the contents into a file.  <span class="file filename">backup.sh</span> 
        for example. The file must be made executable:
	</p>
<div class="screen"><pre class="contents "><span class="cmd command">chmod u+x backup.sh</span>
</pre></div>
<p class="para">
	Then from a terminal prompt:  
        </p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo ./backup.sh</span>
</pre></div>
<p class="para">Tento spôsob môžeme využiť, ak chceme otestovať správnu funkčnosť skriptu.</p>
</div></div>
</div></div>
<div class="sect3 sect" id="backup-script-execute-cron"><div class="inner">
<div class="hgroup"><h3 class="title">Spustenie pomocou plánovacieho nástroja cron</h3></div>
<div class="region"><div class="contents">
<p class="para">Nástroj <span class="app application">cron</span> môžeme využiť na automatické spúšťanie skriptu. Démon <span class="app application">cron</span> umožňuje spúšťanie skriptov alebo príkazov v stanovený čas.</p>
<p class="para"><span class="app application">cron</span> môžeme nastaviť prostredníctvom záznamov v súbore <span class="file filename">crontab</span>. Syntax riadkov súboru <span class="file filename">crontab</span> je nasledovná:</p>
<div class="code"><pre class="contents "># m h dom mon dow   command
</pre></div>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">m:</span> minute the command executes on, between 0 and 59.
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">h:</span> hour the command executes on, between 0 and 23.
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para"><span class="em emphasis">dom:</span> deň v mesiaci, kedy sa má príkaz spustiť.</p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">mon:</span> the month the command executes on, between 1 and 12.
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para">
            <span class="em emphasis">dow:</span> the day of the week the command executes on, between 0 and 7. Sunday may be specified by using 0 or 7, both values are valid.
            </p>
          </li>
<li class="list itemizedlist">
            <p class="para"><span class="em emphasis">command:</span> príkaz, ktorý sa má vykonať.</p>
          </li>
</ul></div>
<p class="para">Ak chceme pridať záznam do súboru <span class="file filename">crontab</span>, použijeme príkaz <span class="app application">crontab -e</span>. Obsah súboru <span class="file filename">crontab</span> si môžeme pozrieť pomocou príkazu <span class="app application">crontab -l</span>.</p>
<p class="para">Ak chceme nastaviť spúšťanie skriptu <span class="app application">zaloha.sh</span> pomocou nástroja <span class="app application">cron</span>, najskôr zadáme príkaz:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo crontab -e</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
	  <p class="para">Ak použijeme <span class="app application">sudo</span> spolu s príkazom <span class="app application">crontab -e</span>, budeme upravovať crontab používateľa <span class="em emphasis">root</span>. To je nevyhnutné, ak chceme zálohovať systémové priečinky, pretože iba používateľ root ku nim má prístup.</p>
        </div></div></div></div>
<p class="para">Pridáme nasledujúci záznam do súboru <span class="file filename">crontab</span>:</p>
<div class="code"><pre class="contents "># m h dom mon dow   command
0 0 * * * bash /usr/local/bin/zaloha.sh
</pre></div>
<p class="para">Pri použití tohto nastavenia sa bude skript <span class="app application">zaloha.sh</span> spúšťať každý deň o polnoci.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
          <p class="para">
          The <span class="app application">backup.sh</span> script will need to be copied to the <span class="file filename">/usr/local/bin/</span> directory in order for 
          this entry to execute properly.  The script can reside anywhere on the file system, simply change the script path appropriately.
          </p>
        </div></div></div></div>
<p class="para">
        For more in-depth <span class="app application">crontab</span> options see <a class="xref" href="backup-shellscripts.html#backup-shellscript-references" title="Zdroje">Zdroje</a>.
        </p>
</div></div>
</div></div>
</div>
</div></div>
<div class="sect2 sect" id="backup-shellscript-archive-testing"><div class="inner">
<div class="hgroup"><h2 class="title">Obnovenie údajov z archívu</h2></div>
<div class="region"><div class="contents">
<p class="para">Potom ako vytvoríme archív, je dôležité ho otestovať. Môžeme to urobiť tak, že si necháme vypísať súbory, ktoré obsahuje. Najlepší test ale je, ak súbory z archívu <span class="em emphasis">obnovíme</span>.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">
          To see a listing of the archive contents.  From a terminal prompt type:
          </p>
<div class="screen"><pre class="contents "><span class="cmd command">tar -tzvf /mnt/backup/nazovpc-Pondelok.tgz</span>
</pre></div>
        </li>
<li class="list itemizedlist">
          <p class="para">Ak chceme obnoviť súbor z archívu do iného priečinka, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">tar -xzvf /mnt/backup/nazovpc-Pondelok.tgz -C /tmp etc/hosts</span>
</pre></div>
          <p class="para">Prepínač <span class="em emphasis">-C</span> povie nástroju <span class="app application">tar</span>, aby presmeroval obnovovaný súbor do zadaného priečinka. Predchádzajúci príkaz obnoví súbor <span class="file filename">/etc/hosts</span> do priečinka <span class="file filename">/tmp/etc/hosts</span>. Nástroj <span class="app application">tar</span> obnoví súbor aj s celou jeho cestou a chýbajúce priečinky automaticky vytvorí.</p>
          <p class="para">Z tohto dôvodu na začiatku cesty, ktorá sa má obnoviť, nie je zapísané <span class="em emphasis">"/"</span>.</p>  
        </li>
<li class="list itemizedlist">
          <p class="para">Ak chceme obnoviť súbory z archívu, zadáme nasledujúce príkazy:</p>
<div class="screen"><pre class="contents "><span class="cmd command">cd /</span>
<span class="cmd command">sudo tar -xzvf /mnt/backup/nazovpc-Pondelok.tgz</span>
</pre></div>
        </li>
</ul></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Týmto prepíšeme aktuálne súbory v súborovom systéme.</p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="backup-shellscript-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Viac informácií o vytváraní skriptov sa dozviete na stránke <a href="http://tldp.org/LDP/abs/html/" class="ulink" title="http://tldp.org/LDP/abs/html/">Advanced Bash-Scripting Guide</a></p>
        </li>
<li class="list itemizedlist">
          <p class="para">Vynikajúcou online knihou o vytváraní skriptov je <a href="http://safari.samspublishing.com/0672323583" class="ulink" title="http://safari.samspublishing.com/0672323583">Teach Yourself Shell Programming in 24 Hours</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">O ďalších možnostiach nástroja cron sa môžeme dozvedieť na stránke CronHowto Wiki Page.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Viac o nástroji <span class="app application">tar</span> sa dozvieme na stránke <a href="http://www.gnu.org/software/tar/manual/index.html" class="ulink" title="http://www.gnu.org/software/tar/manual/index.html">GNU tar Manual</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">O iných stratégiách pre vytváraní záloh sa dozvieme na stránke Wikipédie s názvom <a href="http://en.wikipedia.org/wiki/Backup_rotation_scheme" class="ulink" title="http://en.wikipedia.org/wiki/Backup_rotation_scheme">Backup Rotation Scheme</a>.</p>
        </li>
<li class="list itemizedlist">
        <p class="para">V našom skripte sme použili na vytvorenie zálohy nástroj <span class="app application">tar</span>, no existuje mnoho ďalších nástrojov, ktoré sa dajú na tento účel použiť. Sú to napríklad:</p>
          <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
              <p class="para"><a href="http://www.gnu.org/software/cpio/" class="ulink" title="http://www.gnu.org/software/cpio/">cpio</a>: používa sa na vytváranie kópií do a z archívov.</p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <a href="http://www.gnu.org/software/coreutils/" class="ulink" title="http://www.gnu.org/software/coreutils/">dd</a>: part of the <span class="app application">coreutils</span> 
              package.  A low level utility that can copy data from one format to another.
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <a href="http://www.rsnapshot.org/" class="ulink" title="http://www.rsnapshot.org/">rsnapshot</a>: a file system snapshot utility used to create 
              copies of an entire file system. 
              </p>
            </li>
<li class="list itemizedlist">
              <p class="para">
              <a href="http://www.samba.org/ftp/rsync/rsync.html" class="ulink" title="http://www.samba.org/ftp/rsync/rsync.html">rsync</a>:
              a flexible utility used to create incremental copies of files.
              </p>
            </li>
</ul></div>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="backups.html" title="Zálohovanie">Predchádzajúca</a><a class="nextlinks-next" href="backups-shellscripts-rotation.html" title="Rotácia archívov">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
