<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bacula</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="backups.html" title="Zálohovanie">Zálohovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="backups-shellscripts-rotation.html" title="Rotácia archívov">Predchádzajúca</a><a class="nextlinks-next" href="virtualization.html" title="Virtualizácia">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Bacula</h1></div>
<div class="region">
<div class="contents"><p class="para">
    <span class="app application">Bacula</span> is a backup program enabling you to backup, restore, and verify data across your network. There are Bacula 
    clients for Linux, Windows, and Mac OS X - making it a cross-platform network wide solution.
    </p></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="bacula.html#bacula-overview" title="Prehľad">Prehľad</a></li>
<li class="links"><a class="xref" href="bacula.html#bacula-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="bacula.html#bacula-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="bacula.html#bacula-localhost-backup" title="Záloha na lokálnom počítači">Záloha na lokálnom počítači</a></li>
<li class="links"><a class="xref" href="bacula.html#bacula-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="bacula-overview"><div class="inner">
<div class="hgroup"><h2 class="title">Prehľad</h2></div>
<div class="region"><div class="contents">
<p class="para">
      <span class="app application">Bacula</span> is made up of several components and services used to manage which files to backup and backup locations:
      </p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula Director:</span> služba, ktorá riadi celé zálohovanie, obnovu, overovanie a operácie s tým spojené.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula Console:</span> aplikácia umožňujúca komunikáciu so službou Director. Existujú tri verzie konzoly:</p>
	  <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist"><p class="para">Textovo založený príkazový riadok.</p></li>
<li class="list itemizedlist"><p class="para">Grafické rozhranie pre prostredie Gnome založené na GTK+.</p></li>
<li class="list itemizedlist"><p class="para">Grafické rozhranie založené na wxWidgets.</p></li>
</ul></div>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula File:</span> známy tiež ako <span class="app application">Bacula Client</span> program. Táto aplikácia je nainštalovaná na počítačoch, ktoré chceme zálohovať, a ktorý poskytuje údaje žiadané programom Director.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula Storage:</span> program, ktorý ukladá a číta údaje z fyzického média.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula Catalog:</span> je zodpovedný za správu zoznamu súborov a databázu zväzov so všetkými zálohovanými súbormi. Umožňuje rýchle vyhľadanie a obnovenie archivovaných súborov. Program Catalog podporuje tri rôzne databázy MySQL, PostgreSQL a SQLite.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="app application">Bacula Monitor:</span> umožňuje monitorovanie programov Director, File a Storage. Momentálne je tento program dostupný iba v aplikácii s grafickým rozhraním GTK+.</p>
        </li>
</ul></div>
<p class="para">Tieto služby a aplikácie môžu byť súčasne spustené na viacerých serveroch a klientoch alebo môžu byť všetky nainštalované na jednom počítači, ak zálohujeme jeden disk alebo zväzok.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="bacula-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">
        If using MySQL or PostgreSQL as your database, you should already have the services available.
        <span class="app application">Bacula</span> will not install them for you.
        </p>
      </div></div></div></div>
<p class="para">Komponenty systému <span class="app application">Bacula</span> sú rozložené do viacerých balíkoch. Ak chceme nainštalovať systém Bacula, do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install bacula</span>
</pre></div>
<p class="para">V predvolenom stave po nainštalovaní balíka <span class="app application">bacula</span> bude pre program Catalog použitá databáza <span class="app application">MySQL</span>. Ak chceme pre program Catalog použiť SQLite alebo PostgreSQL, nainštalujeme balík <span class="app application">bacula-director-sqlite3</span> alebo <span class="app application">bacula-director-pgsql</span>.</p>
<p class="para">Počas inštalácie bude potrebné zadať prihlasovacie údaje pre konto <span class="em emphasis">správcu</span> databázy a </p>
</div></div>
</div></div>
<div class="sect2 sect" id="bacula-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Konfiguračné súbory systému <span class="app application">Bacula</span> sú formátované na základe <span class="em emphasis">zdrojov</span> pozostávajúcich z direktív uzatvorených do zložených zátvoriek <span class="quote">„{}“</span>. Každý komponent systému Bacula má svoj vlastný konfiguračný súbor v priečinku <span class="file filename">/etc/bacula</span>.</p>
<p class="para">Rôzne časti systému <span class="app application">Bacula</span> sa musia navzájom autorizovať. Toto je zabezpečené pomocou direktívy <span class="em emphasis">password</span>. Napríklad heslo zdroja Storage v súbore <span class="file filename">/etc/bacula/bacula-dir.conf</span> sa musí zhodovať s heslom zdroja <span class="em emphasis">Director</span> v súbore <span class="file filename">/etc/bacula/bacula-sd.conf</span>.</p>
<p class="para">V predvolenom stave je vytvorená úloha s názvom <span class="em emphasis">Client1</span>, ktorá archivuje údaje prostredníctvom programu Catalog systému <span class="app application">Bacula</span>. Ak máme v pláne použiť server na archivovanie údajov z viacerých klientov, zmeníme meno tejto úlohy na niečo viac popisné. Meno zmeníme v súbore <span class="file filename">/etc/bacula/bacula-dir.conf</span>:</p>
<div class="code"><pre class="contents ">#
# Define the main nightly save backup job
#   By default, this job will back up to disk in 
Job {
  Name = "BackupServer"
  JobDefs = "DefaultJob"
  Write Bootstrap = "/var/lib/bacula/Client1.bsr"
}
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">V predchádzajúcom príklade sme ako názov úlohy použili názov stanice <span class="em emphasis">BackupServer</span>. Nahraďte  <span class="quote">„BackupServer“</span> názvom vašej stanice alebo iným popisným menom.</p>
      </div></div></div></div>
<p class="para">Program <span class="em emphasis">Console</span> si môže vyžiadať od programu <span class="em emphasis">Director</span> úlohy, ale aby mohli program Console použiť aj používatelia, ktorí <span class="em emphasis">nemajú</span> právo root, musia byť členmi skupiny <span class="em emphasis">bacula</span>. Používateľa do skupiny bacula pridáme napísaním nasledujúceho príkazu do príkazového riadka:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo adduser $username bacula</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Nahraďte <span class="em emphasis">$username</span> skutočným menom aktuálneho používateľa. Po pridaní používateľa do skupiny sa musíte odhlásiť a znova prihlásiť, aby sa zmena prejavila.</p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="bacula-localhost-backup"><div class="inner">
<div class="hgroup"><h2 class="title">Záloha na lokálnom počítači</h2></div>
<div class="region"><div class="contents">
<p class="para">Táto časť vysvetľuje spôsob, ako nastaviť zálohovanie určitých priečinkov na jednom počítači na lokálne pripojenú páskovú mechaniku.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Najskôr nastavíme parametre zariadenia pre program <span class="em emphasis">Storage</span>. Otvoríme súbor <span class="file filename">/etc/bacula/bacula-sd.conf</span> a pridáme:</p>
<div class="code"><pre class="contents ">Device {
  Name = "Tape Drive"
  Device Type = tape
  Media Type = DDS-4
  Archive Device = /dev/st0
  Hardware end of medium = No;
  AutomaticMount = yes;               # when device opened, read it
  AlwaysOpen = Yes;
  RemovableMedia = yes;
  RandomAccess = no;
  Alert Command = "sh -c 'tapeinfo -f %c | grep TapeAlert'"
}
</pre></div>
          <p class="para">
          The example is for a <span class="em emphasis">DDS-4</span> tape drive.  Adjust the <span class="quote">„Media Type“</span> and <span class="quote">„Archive Device“</span> to match your hardware.
          </p>
          <p class="para">Miesto tohto nastavenia by sme tiež mohli odpoznámkovať jeden z ďalších súborov s príkladmi.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Po dokončení úprav súboru <span class="file filename">/etc/bacula/bacula-sd.conf</span> je potrebné reštartovať démon programu <span class="app application">Storage</span>:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart bacula-sd.service</span>
</pre></div>
        </li>
<li class="list itemizedlist">
          <p class="para">Teraz pridáme zdroj <span class="em emphasis">Storage</span> do súboru <span class="file filename">/etc/bacula/bacula-dir.conf</span> aby použil nové zariadenie :</p>
<div class="code"><pre class="contents "># Definition of "Tape Drive" storage device
Storage {
  Name = TapeDrive
  # Do not use "localhost" here    
  Address = backupserver               # N.B. Use a fully qualified name here
  SDPort = 9103
  Password = "Cv70F6pf1t6pBopT4vQOnigDrR0v3LT3Cgkiyjc"
  Device = "Tape Drive"
  Media Type = tape
}
</pre></div>
          <p class="para">Do direktívy <span class="em emphasis">Address</span> je potrebné zapísať úplné doménové meno (FQDN) servera. Zmeníme <span class="em emphasis">backupserver</span> na mennú adresu našej stanice.</p>
          <p class="para">Tiež sa uistíme, či sa direktíva <span class="em emphasis">Password</span> zhoduje s heslom definovaným v súbore <span class="file filename">/etc/bacula/bacula-sd.conf</span>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Vytvoríme novú sadu súborov <span class="em emphasis">FileSet</span>, ktorá bude určovať, ktoré priečinky sa majú archivovať:</p>
<div class="code"><pre class="contents "># LocalhostBacup FileSet.
FileSet {
  Name = "LocalhostFiles"
  Include {
    Options {
      signature = MD5
      compression=GZIP
    }
    File = /etc
    File = /home
  }
}
</pre></div>
          <p class="para">
          This <span class="em emphasis">FileSet</span> will backup the <span class="file filename">/etc</span> and 
          <span class="file filename">/home</span> directories.  The <span class="em emphasis">Options</span> resource directives 
          configure the FileSet to create an MD5 signature for each file backed up, and to compress the files using GZIP.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para">Teraz vytvoríme nový plán <span class="em emphasis">Schedule</span> pre zálohovanie:</p>
<div class="code"><pre class="contents "># LocalhostBackup Schedule -- Daily.
Schedule {
  Name = "LocalhostDaily"
  Run = Full daily at 00:01
}
</pre></div>
          <p class="para">Tento plán hovorí, že úloha sa má spustiť každý deň o 00:01. Samozrejme je k dispozícii omnoho viac volieb, ktoré sa dajú použiť.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Nakoniec vytvoríme úlohu <span class="em emphasis">Job</span>:</p>
<div class="code"><pre class="contents "># Localhost backup.
Job {
  Name = "LocalhostBackup"
  JobDefs = "DefaultJob"
  Enabled = yes
  Level = Full
  FileSet = "LocalhostFiles"
  Schedule = "LocalhostDaily"
  Storage = TapeDrive
  Write Bootstrap = "/var/lib/bacula/LocalhostBackup.bsr"
}  
</pre></div>
          <p class="para">Úloha bude každý deň vykonávať úplnú <span class="em emphasis">Full</span> zálohu na páskovú mechaniku.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Každá páska, ktorú použijeme, musí mať označenie - <span class="em emphasis">Label</span> Ak aktuálna páska nemá označenie, systém <span class="app application">Bacula</span> vám odošle email, aby ste o tom vedeli. Ak chceme priradiť páske označenie pomocou programu <span class="app application">Console</span>, spustíme ho pomocou príkazu:</p>
<div class="screen"><pre class="contents "><span class="cmd command">bconsole</span>
</pre></div>
        </li>
<li class="list itemizedlist">
          <p class="para">a v príkazovom riadku konzoly Bacula zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">label</span>
</pre></div>
        </li>
<li class="list itemizedlist">
          <p class="para">Po zadaní príkazu bude potrebné zadať zdroj <span class="em emphasis">Storage</span>:</p>
<div class="screen"><pre class="contents "><span class="output computeroutput">
Automatically selected Catalog: MyCatalog
Using Catalog "MyCatalog"
The defined Storage resources are:
     1: File
     2: TapeDrive
Select Storage resource (1-2):<span class="input userinput">2</span>
</span>
</pre></div>
        </li>
<li class="list itemizedlist">
          <p class="para">Teraz zadáme nový názov <span class="em emphasis">zväzku</span> - Volume name:</p>
<div class="screen"><pre class="contents "><span class="output computeroutput">
Enter new Volume name: <span class="input userinput">Nedeľa</span>
Defined Pools:
     1: Default
     2: Scratch</span>
</pre></div>
          <p class="para">Miesto slova <span class="em emphasis">Nedela</span> môžeme použiť iný popisnejší názov.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Teraz vyberieme <span class="em emphasis">Pool</span>:</p>
<div class="screen"><pre class="contents "><span class="output computeroutput">
Select the Pool (1-2): <span class="input userinput">1</span>
Connecting to Storage daemon TapeDrive at backupserver:9103 ...
Sending label command for Volume "Sunday" Slot 0 ...
</span>
</pre></div>
        </li>
</ul></div>
<p class="para">Odteraz by mal systém <span class="em emphasis">Bacula</span> zálohovať údaje z lokálnej stanice na pripojené páskové zariadenie.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="bacula-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">
	  For more <span class="em emphasis">Bacula</span> configuration options, refer to 
          <a href="http://blog.bacula.org/documentation/documentation/" class="ulink" title="http://blog.bacula.org/documentation/documentation/">Bacula's
          Documentation</a>.
          </p>
        </li>
<li class="list itemizedlist">
          <p class="para">Na domovskej stránke <a href="http://www.bacula.org/" class="ulink" title="http://www.bacula.org/">Bacula Home Page</a> sa zasa nachádzajú informácie o najnovšej verzii systému Bacula a o jeho vývoji.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Stránka <a href="https://help.ubuntu.com/community/Bacula" class="ulink" title="https://help.ubuntu.com/community/Bacula">Bacula Ubuntu Wiki</a> tiež stojí za pozretie.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="backups-shellscripts-rotation.html" title="Rotácia archívov">Predchádzajúca</a><a class="nextlinks-next" href="virtualization.html" title="Virtualizácia">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
