<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>CUPS - Tlačový server</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="file-servers.html" title="Súborové servery">Súborové servery</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="iscsi-initiator.html" title="iSCSI Initiator">Predchádzajúca</a><a class="nextlinks-next" href="email-services.html" title="Emailové služby">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">CUPS - Tlačový server</h1></div>
<div class="region">
<div class="contents">
<p class="para">Hlavný mechanizmus pre tlač a tlačové služby v Ubuntu zabezpečuje emphasis role="bold"&gt;Common UNIX Printing System</p>
<p class="para">CUPS spravuje tlačové úlohy a požiadavky a umožňuje sieťovú tlač prostredníctvom štandardného protokolu Internet Printing Protocol (IPP) a ponúka podporu pre široký rozsah tlačiarní od ihličkových až po laserové. CUPS tiež podporuje PostScript Printer Description (PPD), automatickú detekciu sieťových tlačiarní a funkcie pre jednoduchú konfiguráciu cez webové administračné rozhranie.</p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="cups.html#cups-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="cups.html#cups-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="cups.html#cups-web" title="Webové rozhranie">Webové rozhranie</a></li>
<li class="links"><a class="xref" href="cups.html#cups-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="cups-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">
            To install CUPS on your Ubuntu computer, simply use <span class="app application">sudo</span> with the <span class="app application">apt</span> command and give the packages to install as the first parameter. A complete CUPS install has many package dependencies, but they may all be specified on the same command line.  Enter the following at a terminal prompt to install CUPS:
          </p>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install cups</span>
</pre></div>
          </p>
<p class="para">Po autentifikácii heslom používateľa sa balíky stiahnu a nainštalujú. Po skončení inštalácie by sa mal server CUPS automaticky naštartovať.</p>
<p class="para">Ak nastanú problémy, chybové hlásenia servera CUPS si môžeme pozrieť v súbore: <span class="file filename">/var/log/cups/error_log</span>. Ak súbor záznamov neposkytuje dostatočné informácie pre vyriešenie problému, môžeme zvýšiť podrobnosť záznamov systému CUPS pomocou direktívy <span class="em em-bold emphasis">LogLevel</span> v konfiguračnom súbore (viď nižšie) z predvolenej hodnoty "info" na "debug" alebo dokonca "debug2", pri ktorom sa bude zaznamenávať všetko. Po vyriešení problému by sme nemali zabudnúť vrátiť pôvodné nastavenie, aby sa súbor so záznamom nestal príliš veľký.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="cups-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Správanie servera CUPS sa konfiguruje prostredníctvom direktív v súbore <span class="file filename">/etc/cups/cupsd.conf</span>. Konfiguračný súbor systému CUPS má rovnakú sysntax ako hlavný konfiguračný súbory servera Apache, preto používateľom, ktorí poznajú konfiguračný súbor servera Apache, nebude robiť problém ani konfiguračný súbor systému CUPS. Teraz si ukážeme niekoľko základných konfiguračných možností.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents">
               <p class="para">Pred úpravou akéhokoľvek konfiguračného súboru by ste si mali vytvoriť kópiu originálneho súboru a nastaviť ho iba na čítanie, aby ste mohli nastavenia porovnať s pôvodnými hodnotami a v prípade potreby ich vrátiť späť.</p>
               <p class="para">Vytvorte kópiu súboru <span class="file filename">/etc/cups/cupsd.conf</span> a nastavte ju iba na čítanie zadaním nasledujúcich príkazov:</p>
               </div></div></div></div>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo cp /etc/cups/cupsd.conf /etc/cups/cupsd.conf.original</span>
<span class="cmd command">sudo chmod a-w /etc/cups/cupsd.conf.original</span>
</pre></div>
               </p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
                <p class="para">Copy text   	
<span class="em em-bold emphasis">ServerAdmin</span>: Ak chceme zmeniť emailovú adresu administrátora servera CUPS, jednoducho v obľúbenom textovom editore upravíme riadok <span class="em emphasis">ServerAdmin</span> v súbore <span class="file filename">/etc/cups/cupsd.conf</span> na príslušnú hodnotu. Napríklad, ak sme administrátorom servera CUPS a naša emailova adresa je 'jhrasko@nieco.sk', zmeníme riadok ServerAdmin takto:</p>
                <p class="para">
<div class="screen"><pre class="contents ">ServerAdmin jhrasko@nieco.sk
</pre></div>
                </p>
                </li>
<li class="list itemizedlist">
                <p class="para">Copy text   	
<span class="em em-bold emphasis">Listen</span>: V predvolenom stave v Ubuntu po inštalácii server CUPS načúva iba na rozhraní spätnej väzby s IP adresou <span class="em emphasis">127.0.0.1</span>. Ak chceme aby server CUPS načúval na IP adrese adaptéra pripojeného k sieti, musíme zadať ku nemu priradené meno stanice alebo IP adresu, alebo voliteľne pár IP adresa/port ako ďalšiu direktívu Listen. Napríklad, ak je server CUPS v lokálnej sieti na počítači s IP adresou <span class="em emphasis">192.168.10.250</span> a chceme, aby bol prístupný aj pre ostatné počítače v sieti, otvoríme súbor <span class="file filename">/etc/cups/cupsd.conf</span> a pridáme nasledujúcu Listen direktívu:</p>
                <p class="para">
<div class="screen"><pre class="contents ">Listen 127.0.0.1:631           # existujúce nastavenie pre spätnú väzbu
Listen /var/run/cups/cups.sock # existujúce nastavenie pre socket
Listen 192.168.10.250:631      # nové nastavenie pre LAN rozhranie a port 631 (IPP)
</pre></div>
                </p>
                <p class="para">V predchádzajúcom príklade môžeme zapoznámkovať alebo vymazať nastavenie pre spätnú väzbu (127.0.0.1), ak nechceme, aby <span class="app application">cupsd</span> načúval na tomto rozhraní, ale chceme, aby načúval iba na Ethernetovom rozhraní lokálnej siete (LAN). Ak chceme aby načúval na všetkých rozhraniach, ktoré sú na danom počítači, vrátanie zariadenia spätnej väzby Loopback, môžeme vytvoriť záznam Listen s názvom stanice - napríklad <span class="em emphasis">socrates</span>:</p>
                <p class="para">
<div class="screen"><pre class="contents ">Listen socrates:631  # nastavenie pre všetky rozhrania na stanici s názvom 'socrates'
</pre></div>
                </p> 
				<p class="para">alebo použitím direktívy <span class="em emphasis">Port</span> miesto direktívy Listen:</p>
<p class="para">
<div class="screen"><pre class="contents ">Port 631  # Načúva na porte 631 na všetkých rozhraniach
</pre></div>
</p>
                </li>
</ul></div>
<p class="para">Viac informácií o direktívach konfiguračného súboru servera CUPS si môžeme pozrieť na manuálových stránkach zadaním nasledujúceho príkazu do príkazového riadka:</p>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">man cupsd.conf</span>
</pre></div>
               </p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
                <p class="para">Vždy, keď urobíte zmeny v konfiguračnom súbore <span class="file filename">/etc/cups/cupsd.conf</span>, je potrebné reštartovať server CUPS zadaním nasledujúceho príkazu:</p>
                </div></div></div></div>
<p class="para">
<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart cups.service</span>
</pre></div>
                </p>
</div></div>
</div></div>
<div class="sect2 sect" id="cups-web"><div class="inner">
<div class="hgroup"><h2 class="title">Webové rozhranie</h2></div>
<div class="region"><div class="contents">
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents">
	    <p class="para">CUPS sa dá konfigurovať a monitorovať cez webové rozhranie, ktoré je dostupné na adrese <span class="em emphasis">http://nazovstanice:631/admin</span>. Webové rozhranie sa dá použiť na vykonanie všetkých správcovských úloh týkajúcich sa tlačiarní.</p>
	  </div></div></div></div>
<p class="para">Aby sme mohli vykonávať správcovské úlohy cez webové rozhranie, musíme mať buď povolené konto používateľa root na serveri alebo sa prihlásiť ako používateľ patriaci do skupiny <span class="em emphasis">lpadmin</span>. Kvôli bezpečnosti CUPS odmieta autentifikovať používateľov bez hesla.</p>
<p class="para">Keď chceme pridať používateľa do skupiny <span class="em emphasis">lpadmin</span>, spustíme nasledujúci príkaz: <div class="screen"><pre class="contents "><span class="cmd command">sudo usermod -aG lpadmin username</span>
</pre></div></p>
<p class="para">Ďalšia dokumentácia je dostupná z webového rozhranie na karte <span class="em emphasis">Documentation/Help</span>.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="cups-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<p class="para">
        <a href="http://www.cups.org/" class="ulink" title="http://www.cups.org/">CUPS Website</a>
        </p>
<p class="para">
        <a href="http://wiki.debian.org/SAN/iSCSI/open-iscsi" class="ulink" title="http://wiki.debian.org/SAN/iSCSI/open-iscsi">Debian Open-iSCSI page</a>
        </p>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="iscsi-initiator.html" title="iSCSI Initiator">Predchádzajúca</a><a class="nextlinks-next" href="email-services.html" title="Emailové služby">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
