<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prehľad</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="monitoring.html" title="Monitorovanie">Monitorovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="monitoring.html" title="Monitorovanie">Predchádzajúca</a><a class="nextlinks-next" href="nagios.html" title="Nagios">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Prehľad</h1></div>
<div class="region"><div class="contents">
<p class="para">Monitorovanie jednotlivých serverov a služieb je dôležitou súčasťou administrácie systému. Väčšina sieťových služieb sa monitoruje kvôli zisteniu výkonu, zisteniu dostupnosti, alebo kvôli zisteniu oboch týchto parametrov. Táto časť hovorí o inštalácii a konfigurácii systému <span class="app application">Nagios</span>, ktorý monitoruje dostupnosť a systému <span class="app application">Munin</span>, ktorý monitoruje výkon.</p>
<p class="para">Príklady v teto časti používajú dve stanice s mennými adresami <span class="em emphasis">server01</span> a <span class="em emphasis">server02</span>. <span class="em emphasis">Server01</span> nakonfigurujeme tak, aby pomocou systému <span class="app application">Nagios</span> monitoroval sám seba a <span class="em emphasis">server02</span>. Na server01 nainštalujeme aj <span class="app application">munin</span>, ktorý bude získavať informácie zo siete. Pomocou balíka <span class="app application">munin-node</span>, nastavíme <span class="em emphasis">server02</span>  tak, aby posielal informácie na <span class="em emphasis">server01</span>.</p>
<p class="para">Dúfame, že vám tieto jednoduché príklady poslúžia ako návod pre monitorovanie ďalších staníc a služieb vo vašej sieti.</p>
</div></div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="monitoring.html" title="Monitorovanie">Predchádzajúca</a><a class="nextlinks-next" href="nagios.html" title="Nagios">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
