<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nagios</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="monitoring.html" title="Monitorovanie">Monitorovanie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="monitoring-overview.html" title="Prehľad">Predchádzajúca</a><a class="nextlinks-next" href="munin.html" title="Munin">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">Nagios</h1></div>
<div class="region">
<div class="contents"></div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="nagios.html#nagios-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="nagios.html#nagios-configuration-overview" title="Prehľad konfiguračných súborov">Prehľad konfiguračných súborov</a></li>
<li class="links"><a class="xref" href="nagios.html#nagios-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="nagios.html#nagios-references" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="nagios-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Najskor na počítači s názvom <span class="em emphasis">server01</span> nainštalujeme balík <span class="app application">nagios</span>. Do príkazového riadka zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install nagios3 nagios-nrpe-plugin</span>
</pre></div>
<p class="para">Po zadaní príkazu zadáme heslo pre správcu – používateľa <span class="em emphasis">nagiosadmin</span>. Prihlasovacie údaje používateľov sa uložia do súboru <span class="file filename">/etc/nagios3/htpasswd.users</span>. Ak budeme chcieť zmeniť heslo používateľa <span class="em emphasis">nagiosadmin</span> alebo pridať ďalších používateľov do Nagios CGI skriptov, použijeme nástroj <span class="app application">htpasswd</span>, ktorý je súčasťou balíka <span class="app application">apache2-utils</span>.</p>
<p class="para">Ak chceme napríklad zmeniť heslo používateľa <span class="em emphasis">nagiosadmin</span> zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo htpasswd /etc/nagios3/htpasswd.users nagiosadmin</span>
</pre></div>
<p class="para">Ak chceme pridať nového používateľa, zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo htpasswd /etc/nagios3/htpasswd.users stefan</span>
</pre></div>
<p class="para">Teraz nainštalujeme na stanicu s názvom <span class="em emphasis">server02</span> balík <span class="app application">nagios-nrpe-server</span>. Do príkazového riadka na počítači server02 zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install nagios-nrpe-server</span>
</pre></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para"><span class="app application">NRPE</span> umožňuje spúšťať lokálne kontroly na vzdialených staniciach. Existujú aj iné rozšírenia systému Nagios, pomocou ktorých sa dajú kontroly spustiť vzdialene. Rovnako existujú iné spôsoby kontroly.</p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="nagios-configuration-overview"><div class="inner">
<div class="hgroup"><h2 class="title">Prehľad konfiguračných súborov</h2></div>
<div class="region"><div class="contents">
<p class="para">Existuje niekoľko priečinkov, ktoré obsahujú konfiguráciu systému <span class="app application">Nagios</span> a kontrolné súbory.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="file filename">/etc/nagios3</span>: obsahuje konfiguračné súbory, ktoré riadia správanie démona <span class="app application">nagios</span>, CGI súborov, zoznamu staníc – hosts, atď.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="file filename">/etc/nagios-plugins</span>: obsahuje konfiguračné súbory pre kontrolu služieb.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="file filename">/etc/nagios</span>: na vzdialenej stanica obsahuje konfiguračné súbory pre <span class="app application">nagios-nrpe-server</span>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="file filename">/usr/lib/nagios/plugins/</span>: tu sú uložené spustiteľné kontrolné nástroje. Ak chceme zobraziť možnosti nástroja, použijeme prepínač <span class="em emphasis">-h</span>.</p>
          
          <p class="para">Napríklad: <span class="cmd command">/usr/lib/nagios/plugins/check_dhcp -h</span></p>
        </li>
</ul></div>
<p class="para">Existuje veľké množstvo najrôznejších kontrol pomocou systému Nagios, ktoré môžeme spustiť na zadanom vzdialenom počítači. V tomto príklade Nagios nastavíme tak, aby skontroloval voľné miesto na disku, DNS a  MySQL hostgroup. Kontrolu DNS vykonáme na počítači <span class="em emphasis">server02</span> a kontrolu MySQL hostgroup vykonáme na oboch počítačoch <span class="em emphasis">server01</span> aj <span class="em emphasis">server02</span>.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Pozrite si časť <a class="xref" href="httpd.html" title="HTTPD - Apache2 Web Server">HTTPD - Apache2 Web Server</a> hovoriacu o nastavení systému Apache, časť <a class="xref" href="dns.html" title="Služba prekladu doménových mien (DNS)">Služba prekladu doménových mien (DNS)</a> o DNS a časť <a class="xref" href="mysql.html" title="MySQL">MySQL</a> o MySQL.</p>
      </div></div></div></div>
<p class="para">Pred tým, ako budeme pokračovať, si vysvetlíme ešte niekoľko termínov, ktoré nám umožnia ľahšie porozumieť konfigurácii systému Nagios:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Host</span>: server, pracovná stanica, sieťové zariadenie, atď., ktoré bude monitorované.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Host Group</span>: zoskupenie podobných staníc. Napríklad môžeme zoskupiť webové servery, súborové servery.atď.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Service</span>: služba, ktorá bude monitorovaná na danej stanici. Napríklad HTTP, DNS, NFS, atď.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Service Group</span>: umožňuje zoskupiť viacero služieb. Je to užitočné napríklad pri viacerých HTTP službách.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">Contact</span>: osoba, ktorej má byť oznámené, že nastala sledovaná udalosť. Nagios môže poslať email, SMS správu, atď.</p>
        </li>
</ul></div>
<p class="para">V predvolenom stave je Nagios nastavený tak, aby sledoval HTTP miesto na disku, SSH, aktuálnych používateľov, procesy a zaťaženie na stanici <span class="em emphasis">localhost</span> (stanica, na ktorej je spustený). Nagios tiež pomocou nástroja <span class="app application">ping</span> preverí dostupnosť sieťovej <span class="em emphasis">brány</span> (gateway).</p>
<p class="para">Rozsiahlu inštaláciu systému Nagios môže byť ťažké nakonfigurovať . Preto je najlepšie začať malou inštaláciou – s jedným alebo dvoma počítačmi, nastaviť ich tak, aby monitorovanie fungovalo a potom Nagios nainštalovať na ďalšie stanice.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="nagios-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">

          <div class="steps"><div class="inner"><ol class="steps">
<li class="steps">
              <p class="para">
              First, create a <span class="em emphasis">host</span> configuration file for <span class="em emphasis">server02</span>.
              Unless otherwise specified, run all these commands on <span class="em emphasis">server01</span>.
              In a terminal enter:
             </p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo cp /etc/nagios3/conf.d/localhost_nagios2.cfg \
/etc/nagios3/conf.d/server02.cfg</span>
</pre></div>

             <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
               <p class="para">V predchádzajúcich a nasledujúcich krokoch zmeňte <span class="em emphasis">"server01"</span>, <span class="em emphasis">"server02"</span><span class="em emphasis">172.18.100.100</span> a <span class="em emphasis">172.18.100.101</span> za menné a číselné IP adresy vašich staníc.</p>
             </div></div></div></div>
             
           </li>
<li class="steps">
             <p class="para">Potom upravíme súbor <span class="file filename">/etc/nagios3/conf.d/server02.cfg</span>:</p>

<div class="code"><pre class="contents ">define host{
        use                     generic-host  ; Name of host template to use
        host_name               server02
        alias                   Server 02
        address                 172.18.100.101
}

# check DNS service.
define service {
        use                             generic-service
        host_name                       server02
        service_description             DNS
        check_command                   check_dns!172.18.100.101
}
</pre></div>

           </li>
<li class="steps">

             <p class="para">Reštartujeme démon systému <span class="app application">nagios</span>, aby sa konfigurácia prejavila:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart nagio3.service</span>
</pre></div>
           
           </li>
</ol></div></div>
       </li>
<li class="list itemizedlist">
         <div class="steps"><div class="inner"><ol class="steps">
<li class="steps">

             <p class="para">Teraz pridáme definíciu pre kontrolu služby MySQL pridaním nasledujúcich riadkov do súboru <span class="file filename">/etc/nagios3/conf.d/services_nagios2.cfg</span>:</p>

<div class="code"><pre class="contents "># check MySQL servers.
define service {
        hostgroup_name        mysql-servers
        service_description   MySQL
        check_command         check_mysql_cmdlinecred!nagios!secret!$HOSTADDRESS
        use                   generic-service
        notification_interval 0 ; set &gt; 0 if you want to be renotified
}
</pre></div>

           </li>
<li class="steps">

             <p class="para">
             A <span class="em emphasis">mysql-servers</span> hostgroup now needs to be defined.  Edit 
             <span class="file filename">/etc/nagios3/conf.d/hostgroups_nagios2.cfg</span> adding:
             </p>

<div class="code"><pre class="contents "># MySQL hostgroup.
define hostgroup {
        hostgroup_name  mysql-servers
                alias           MySQL servers
                members         localhost, server02
        }
</pre></div>

           </li>
<li class="steps">

             <p class="para">Kontrola systému Nagios sa musí vedieť prihlásiť do MySQL. Pridáme používateľa <span class="em emphasis">nagios</span> do systému MySQL:</p>

<div class="screen"><pre class="contents "><span class="cmd command">mysql -u root -p -e "create user nagios identified by 'secret';"</span>
</pre></div>

             <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
               <p class="para">Používateľa <span class="em emphasis">nagios</span> je potrebné pridať na všetkých staniciach, ktoré sú definované v skupine <span class="em emphasis">mysql-servers</span> hostgroup.</p>
             </div></div></div></div>

           </li>
<li class="steps">

             <p class="para">Reštartovaním systému <span class="app application">nagios</span> sa zapne kontrolovanie MySQL serverov.</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart nagios3.service</span>
</pre></div>

           </li>
</ol></div></div>
       </li>
<li class="list itemizedlist">
         <div class="steps"><div class="inner"><ol class="steps">
<li class="steps">  

             <p class="para">Nakoniec nastavíme NRPE aby kontroloval voľné miesto na disku na stanici <span class="em emphasis">server02</span>.</p>
 
             <p class="para">Na stanici <span class="em emphasis">server01</span> pridáme nastavenie kontroly služby do súboru <span class="file filename">/etc/nagios3/conf.d/server02.cfg</span>:</p>

<div class="code"><pre class="contents "># NRPE disk check.
define service {
        use                     generic-service
        host_name               server02
        service_description     nrpe-disk
        check_command           check_nrpe_1arg!check_all_disks!172.18.100.101
}
</pre></div>

           </li>
<li class="steps">

             <p class="para">Teraz na stanici <span class="em emphasis">server02</span> otvoríme súbor <span class="file filename">/etc/nagios/nrpe.cfg</span> a zmeníme:</p>

<div class="code"><pre class="contents ">allowed_hosts=172.18.100.100
</pre></div>

             <p class="para">a nižšie do časti command pridáme:</p>

<div class="code"><pre class="contents ">command[check_all_disks]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -e
</pre></div>

           </li>
<li class="steps">

             <p class="para">Nakoniec reštartujeme <span class="app application">nagios-nrpe-server</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart nagios-nrpe-server.service</span>
</pre></div>

           </li>
<li class="steps">

             <p class="para">A tiež na stanici <span class="em emphasis">server01</span> reštartujeme <span class="app application">nagios</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart nagios3.service</span>
</pre></div>

           </li>
</ol></div></div>
       </li>
</ul></div>
<p class="para">Teraz by sme mali vidieť kontrolované stanice a služby v Nagios CGI súboroch. Dostaneme sa ku nim pomocou prehliadača, zadaním adresy http://server01/nagios3. Po načítaní stránky bude potrebné zadať <span class="em emphasis">nagiosadmin</span> ako meno používateľa a heslo, ktoré sme mu nastavili pri inštalácii.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="nagios-references"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents">
<p class="para">Táto časť obsahuje iba základné predstavenie funkcií systému Nagios. Rozšírenia <span class="app application">nagios-plugins-extra</span> a  <span class="app application">nagios-snmp-plugins</span> obsahujú omnoho viac nástrojov na kontrolu služieb.</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Viac informácii sa nachádza na domovskej stránke systému <a href="http://www.nagios.org/" class="ulink" title="http://www.nagios.org/">Nagios</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Najmä stránka <a href="http://nagios.sourceforge.net/docs/3_0/" class="ulink" title="http://nagios.sourceforge.net/docs/3_0/">Online Documentation</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Existuje tiež zoznam <a href="http://www.nagios.org/propaganda/books/" class="ulink" title="http://www.nagios.org/propaganda/books/">kníh</a> súvisiacich so systémom Nagios a monitorovaním siete:</p>
        </li>
<li class="list itemizedlist">
          <p class="para">
          The <a href="https://help.ubuntu.com/community/Nagios3" class="ulink" title="https://help.ubuntu.com/community/Nagios3">Nagios Ubuntu Wiki</a> page also has more details.
          </p>
        </li>
</ul></div>
</div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="monitoring-overview.html" title="Prehľad">Predchádzajúca</a><a class="nextlinks-next" href="munin.html" title="Munin">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
