<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>pam_motd</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="other-useful-applications.html" title="Ďalšie užitočné aplikácie">Ďalšie užitočné aplikácie</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="other-useful-applications.html" title="Ďalšie užitočné aplikácie">Predchádzajúca</a><a class="nextlinks-next" href="etckeeper.html" title="etckeeper">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">pam_motd</h1></div>
<div class="region">
<div class="contents">
<p class="para">Pri prihlasovaní k serveru Ubuntu, sa nám môže zobraziť informatívna správa dňa – Message Of The Day (MOTD). Táto informácia sa nachádza a zobrazuje vďaka niekoľkým balíkom:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
        <p class="para">
        <span class="em emphasis">landscape-common:</span> provides the core libraries of <span class="app application">landscape-client</span>,
	which is needed to manage systems with <a href="http://landscape.canonical.com/" class="ulink" title="http://landscape.canonical.com/">Landscape</a> (proprietary).  Yet the package also includes
        the <span class="app application">landscape-sysinfo</span> utility which is responsible for displaying core system data involving cpu, memory, disk space, etc.  For instance:
        </p>

<div class="screen"><pre class="contents "><span class="output computeroutput">
	  System load:  0.0               Processes:           76
	  Usage of /:   30.2% of 3.11GB   Users logged in:     1
	  Memory usage: 20%               IP address for eth0: 10.153.107.115
	  Swap usage:   0%

	  Graph this data and manage this system at https://landscape.canonical.com/
</span>
</pre></div>

        <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
                <p class="para">
                You can run landscape-sysinfo manually at any time.
                </p>
        </div></div></div></div>

      </li>
<li class="list itemizedlist">
        <p class="para">
        <span class="em emphasis">update-notifier-common:</span> provides information on available package updates, impending filesystem checks (fsck), and required reboots (e.g.: after a kernel upgrade).
        </p>
      </li>
</ul></div>
<p class="para"><span class="app application">pam_motd</span> spustí skripty v priečinku <span class="file filename">/etc/update-motd.d</span> v poradí podľa čísel, ktoré sú pripísané na začiatok názvu skriptu. Výstup skriptov sa zapíše do <span class="file filename">/var/run/motd</span>, pričom sa zachová číselné poradie, ktoré sa prevedie na text pomocou <span class="file filename">/etc/motd.tail</span>.</p>
<p class="para">Do správy dňa môžeme pridať vlastné dynamické informácie. Napríklad lokálne informácie o počasí:</p>
<div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
        <p class="para">Najskôr nainštalujeme balík <span class="app application">weather-util</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install weather-util</span>
</pre></div>

      </li>
<li class="list itemizedlist">
        <p class="para">Nástroj <span class="app application">weather</span> požije tzv. METAR dáta z National Oceanic a Atmospheric Administration a prdpoveď z <a href="http://www.weather.gov/tg/siteloc.shtml" class="ulink" title="http://www.weather.gov/tg/siteloc.shtml">National Weather Service</a>. Aby lokálne informácie systém vedel nájsť, bude potrebné zadať 4 miestny ICAO indikátor umiestnenia. Tento indikátor je možné zistiť na stránke National Weather Service (Bratislava Ivanka – LZIB, Dolný Hričov – LZZI, Kamenica Nad Cirochou – LZKC, Košice – LKKZ, Košice letisko – LZKZ, Lučenec  LZLU, Nitra – LZNI, Piešťany – LZPP, Poprad / Tatry – LZTT, Prievidza – LZPE, Sliač – LZSL).</p>

        <p class="para">Aj napriek tomu, že National Weather Service je vládnou agentúrou Spojených štátov Amerických, poskytuje informácie z meteorologických staníc z celého Sveta. Lokálne informácie zo staníc mimo USA však nemusia byť vždy dostupné.</p>
      </li>
<li class="list itemizedlist">
        <p class="para">Vytvoríme jednoduchý skript <span class="file filename">/usr/local/bin/local-weather</span>, ktorý použije <span class="app application">weather</span> s lokálnym ICAO indikátorom:</p>

<div class="code"><pre class="contents ">#!/bin/sh
##########################################################################
#
# Vypíše lokálne informácie o počasí do /var/run/update-motd/60-local-weather  
# pre update-motd.
#
##########################################################################

# Nahraďte LZIB kódom najbližšej stanice.
# Zoznam staníc môžete nájsť na adrese: http://www.weather.gov/tg/siteloc.shtml

echo
weather -i LZIB 
echo

</pre></div>
      </li>
<li class="list itemizedlist">
        <p class="para">Urobíme skript spustiteľným:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo chmod 755 /usr/local/bin/local-weather</span>
</pre></div>
      </li>
<li class="list itemizedlist">
        <p class="para">Potom vytvoríme symbolické prepojenie na <span class="file filename">/etc/update-motd.d/98-local-weather</span>:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo ln -s /usr/local/bin/local-weather /etc/update-motd.d/98-local-weather</span>
</pre></div>
      </li>
<li class="list itemizedlist">
        <p class="para">Nakoniec sa odhlásim a znova prihlásime aby sme videli novú správu dňa.</p>
      </li>
</ul></div>
<p class="para">Teraz by nás po prihlásení mala privítať správa o počasí. Dúfame, že sa nám na príklade s <span class="app application">local-weather</span> podarilo demonštrovať flexibilitu aplikácie <span class="app application">pam_motd</span>.</p>
</div>
<div class="links sectionlinks" role="navigation"><ul><li class="links"><a class="xref" href="pam_motd.html#pam_motd-resources" title="Zdroje">Zdroje</a></li></ul></div>
<div class="sect2 sect" id="pam_motd-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
	<p class="para">
        See the <a href="http://manpages.ubuntu.com/manpages/xenial/en/man5/update-motd.5.html" class="ulink" title="http://manpages.ubuntu.com/manpages/xenial/en/man5/update-motd.5.html">update-motd man page</a> for
        more options available to <span class="app application">update-motd</span>.
	</p>
	</li>
<li class="list itemizedlist">
        <p class="para">V článku na stránke The Debian Package of the Day s názvom <a href="http://debaday.debian.net/2007/10/04/weather-check-weather-conditions-and-forecasts-on-the-command-line/" class="ulink" title="http://debaday.debian.net/2007/10/04/weather-check-weather-conditions-and-forecasts-on-the-command-line/">weather</a> sa nachádza viac informácií o nástroji <span class="app application">weather</span>.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="other-useful-applications.html" title="Ďalšie užitočné aplikácie">Predchádzajúca</a><a class="nextlinks-next" href="etckeeper.html" title="etckeeper">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
