<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>File Server</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="https://partners.ubuntu.com">Partners</a></li>
<li><a href="https://www.ubuntu.com/support/community-support">Support</a></li>
<li><a href="https://community.ubuntu.com">Community</a></li>
<li><a href="https://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="https://community.ubuntu.com/t/contribute/26">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails"><div class="trail">
<a href="../../16.04" class="trail">Ubuntu 16.04</a> » <a class="trail" href="index.html" title="Príručka k správe Ubuntu servera">Príručka k správe Ubuntu servera</a> » <a class="trail" href="samba.html" title="Samba">Samba</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-introduction.html" title="Úvod">Predchádzajúca</a><a class="nextlinks-next" href="samba-printserver.html" title="Tlačový server">Nasledujúca</a>
</div>
<div class="hgroup"><h1 class="title">File Server</h1></div>
<div class="region">
<div class="contents">
<p class="para">Jeden z najčastejších spôsobov, ako spolu zapojiť počítače so systémami Ubuntu a Windows do jednej siete, je nastaviť systém Samba ako súborový server. Táto časť hovorí o spôsobe, akým sa <span class="app application">Samba</span> server nastaví tak, aby zdieľal súbory so stanicami so systémom Windows.</p>
<p class="para">
    The server will be configured to share files with any client on the network without prompting for a password.  If
    your environment requires stricter Access Controls see <a class="xref" href="samba-fileprint-security.html" title="Securing File and Print Server">Securing File and Print Server</a>.
    </p>
</div>
<div class="links sectionlinks" role="navigation"><ul>
<li class="links"><a class="xref" href="samba-fileserver.html#samba-fileserver-installation" title="Inštalácia">Inštalácia</a></li>
<li class="links"><a class="xref" href="samba-fileserver.html#samba-fileserver-configuration" title="Konfigurácia">Konfigurácia</a></li>
<li class="links"><a class="xref" href="samba-fileserver.html#samba-fileserver-resources" title="Zdroje">Zdroje</a></li>
</ul></div>
<div class="sect2 sect" id="samba-fileserver-installation"><div class="inner">
<div class="hgroup"><h2 class="title">Inštalácia</h2></div>
<div class="region"><div class="contents">
<p class="para">Najskôr nainštalujeme balík <span class="app application">samba</span>. V príkazovom riadku zadáme:</p>
<div class="screen"><pre class="contents "><span class="cmd command">sudo apt install samba</span>
</pre></div>
<p class="para">To je všetko, čo budeme potrebovať. Teraz môžeme nastaviť systém Samba tak, aby zdieľal súbory.</p>
</div></div>
</div></div>
<div class="sect2 sect" id="samba-fileserver-configuration"><div class="inner">
<div class="hgroup"><h2 class="title">Konfigurácia</h2></div>
<div class="region"><div class="contents">
<p class="para">
      The main Samba configuration file is located in <span class="file filename">/etc/samba/smb.conf</span>.  The default configuration file
      has a significant number of comments in order to document various configuration directives.  
      </p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">V predvolenom konfiguračnom súbore sa nenachádzajú všetky nastavenia, ktoré je možné použiť. Viac sa dozviete na <span class="app application">man</span> stránkach <span class="file filename">smb.conf</span> alebo na stránke <a href="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/" class="ulink" title="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/">Samba HOWTO Collection</a>.</p>
      </div></div></div></div>
<div class="steps"><div class="inner"><ol class="steps">
<li class="steps">

        <p class="para">Najskôr nastavíme nasledujúce hodnoty nastavení v časti <span class="em emphasis">[global]</span> súboru <span class="file filename">/etc/samba/smb.conf</span>:</p>

<div class="code"><pre class="contents ">   workgroup = NIECO
   ...
   security = user
</pre></div>

        <p class="para">Parameter <span class="em emphasis">security</span> je takmer na konci časti [global] a je v predvolenom stave zapoznámkovaný, preto ho odpoznámkujeme. Nastavenie pracovnej skupiny <span class="em emphasis">EXAMPLE</span> prispôsobíme nášmu prostrediu.</p>

        </li>
<li class="steps">
  
        <p class="para">Vytvoríme novú časť na konci súboru alebo odkomentujeme jeden z existujúcich príkladov zdieľaného priečinka:</p>

<div class="code"><pre class="contents ">[share]
    comment = Zdieľanie súborového servera v Ubuntu
    path = /srv/samba/zdielanie
    browsable = yes
    guest ok = yes
    read only = no
    create mask = 0755
</pre></div>

      <div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">comment::</span> krátky popis zdieľania. Zmeňte ho podľa potrieb.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">path:</span> cesta k priečinku, ktorý chceme zdielať.</p>
          <p class="para">V tomto príklade sme použili cestu v tvare <span class="file filename">/srv/samba/zdielany_priecinok</span>, pretože podľa štandardu <span class="em emphasis">Filesystem Hierarchy Standard (FHS)</span> je priečinok <a href="http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM" class="ulink" title="http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM">/srv</a> určený práve na takýto typ dát. Technicky môže byť priečinok, ktorý chceme pomocou Samby zdieľať, kdekoľvek v súborovom systéme za predpokladu, že sú správne nastavené práva, ale odporúča sa dodržiavanie štandardov.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">browsable:</span> povolí klientom Windows prehliadať obsah zdielaného priečinka pomocou programu <span class="app application">Windows Explorer</span>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">guest ok:</span> umožňuje klientom pripojiť sa bez zadania hesla.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">read only:</span> určuje či je zdieľanie iba na čítanie alebo či sa do neho dá aj zapisovať. Právo na zápis je povolené, iba ak je nastavená hodnota <span class="em emphasis">no</span>, tak ako je to v našom príklade. Ak je hodnota <span class="em emphasis">yes</span>, potom je zdieľanie určené iba na čítanie.</p>
        </li>
<li class="list itemizedlist">
          <p class="para"><span class="em emphasis">create mask:</span> určuje práva na nové súbory, ktoré sa nastavia pri ich vytvorení.</p>
        </li>
</ul></div>

      </li>
<li class="steps">
        
        <p class="para">Teraz, keď je systém <span class="app application">Samba</span> nastavený, je potrebné vytvoriť priečinok a nastaviť práva. V príkazovom riadku zadáme:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo mkdir -p /srv/samba/zdielanie</span>
<span class="cmd command">sudo chown nobody:nogroup /srv/samba/share/</span>
</pre></div>

      <div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">
        The <span class="em emphasis">-p</span> switch tells mkdir to create the entire directory tree if it doesn't exist.
        </p>
      </div></div></div></div>

      </li>
<li class="steps">
     
      <p class="para">Nakoniec reštartujeme službu <span class="app application">samba</span>, aby sa prejavila nová konfigurácia:</p>

<div class="screen"><pre class="contents "><span class="cmd command">sudo systemctl restart smbd.service nmbd.service</span>
</pre></div>

      </li>
</ol></div></div>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
        <p class="para">Znova pripomíname, že predchádzajúca konfigurácia umožňuje prístup všetkým klientom z lokálnej siete. Bezpečnejšiu konfiguráciu nájdete v časti <a class="xref" href="samba-fileprint-security.html" title="Securing File and Print Server">Securing File and Print Server</a>.</p>
      </div></div></div></div>
<p class="para">
      From a Windows client you should now be able to browse to the Ubuntu file server and see the shared directory. If your client doesn't show your share automatically, try to access your server by its IP address, e.g. \\192.168.1.1, in a Windows Explorer window. To check that everything is working try creating a directory from Windows. 
      </p>
<p class="para">Ak chceme vytvoriť ďalšie zdieľania, vytvoríme novú časť <span class="em emphasis">[priečinok]</span> v súbore<span class="file filename">/etc/samba/smb.conf</span> a reštartujeme systém <span class="em emphasis">Samba</span>. Nesmieme tiež zabudnúť vytvoriť priečinok a nastaviť mu správne práva.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
        <p class="para">
        The file share named <span class="em emphasis">"[share]"</span> and the path <span class="file filename">/srv/samba/share</span> are just examples.
        Adjust the share and path names to fit your environment.  It is a good idea to name a share after a directory on the 
        file system.  Another example would be a share name of <span class="em emphasis">[qa]</span> with a path of <span class="file filename">/srv/samba/qa</span>.
        </p>
      </div></div></div></div>
</div></div>
</div></div>
<div class="sect2 sect" id="samba-fileserver-resources"><div class="inner">
<div class="hgroup"><h2 class="title">Zdroje</h2></div>
<div class="region"><div class="contents"><div class="list itemizedlist"><ul class="list itemizedlist">
<li class="list itemizedlist">
          <p class="para">Podrobnejšie informácie o nastavení systému Samba sa nachádzajú na stránke <a href="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/" class="ulink" title="http://samba.org/samba/docs/man/Samba-HOWTO-Collection/">Samba HOWTO Collection</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Príručka je dostupná aj vo verzii <a href="http://www.amazon.com/exec/obidos/tg/detail/-/0131882228" class="ulink" title="http://www.amazon.com/exec/obidos/tg/detail/-/0131882228">pre tlač</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Ďalším dobrým zdrojom je O'Reillyho <a href="http://www.oreilly.com/catalog/9780596007690/" class="ulink" title="http://www.oreilly.com/catalog/9780596007690/">Using Samba</a>.</p>
        </li>
<li class="list itemizedlist">
          <p class="para">Tiež stránka <a href="https://help.ubuntu.com/community/Samba" class="ulink" title="https://help.ubuntu.com/community/Samba">Ubuntu Wiki Samba </a>.</p>
        </li>
</ul></div></div></div>
</div></div>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="samba-introduction.html" title="Úvod">Predchádzajúca</a><a class="nextlinks-next" href="samba-printserver.html" title="Tlačový server">Nasledujúca</a>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this serverguide documentation, <a href="https://bugs.launchpad.net/serverguide">file a bug report</a>.</p></div>
</div>
</body>
</html>
