<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Uključite naglašene tipke.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="a11y.html" title="Opšti pristup">Opšti pristup</a> › <a class="trail" href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Uključite naglašene tipke.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="em">Ljepljive tipke</span> dopuštaju vam da koristite jednu tipku sa tastature kao prečicu umjesto da koristite sve tipke odjednom.  Na primjer, <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> prečica daje mogućnost promjene prozora. Sa neaktiviranim ljepljivim tipkama, trebali bi ste pritisnuti obje tipke u isto vrijeme; a sa aktiviranim ljepljivim tipkama, pritisnuli bi ste <span class="key"><kbd>Alt</kbd></span> i onda <span class="key"><kbd>Tab</kbd></span> da uradite isto.</p>
<p class="p">Možda biste željeli uključiti ljepljive tipke, ako vam je teško da držite nekoliko tipki odjednom.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Univerzalni Pristup</span> i odaberite <span class="gui">Tipkanje</span> tab.</p></li>
<li class="steps"><p class="p">Uključite <span class="gui"> Ljepljive tipke </span>.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner">
<div class="title title-note"><h2><span class="title">Brzo uključite i isključite ljepljive tipke</span></h2></div>
<div class="region"><div class="contents"><p class="p">
      Under <span class="gui">Enable by Keyboard</span>, select <span class="gui">Turn on accessibility 
      features from the keyboard</span> to turn sticky keys on and off from the 
      keyboard. When this option is selected, you can press <span class="key"><kbd>Shift</kbd></span> 
      five times in a row to enable or disable sticky keys.
    </p></div></div>
</div></div>
<p class="p">Ako pritisnete dvije tipke odjednom, možete isključiti ljepljive tipke istovremeno da ukucate prečicu sa tastature na normalan način.</p>
<p class="p">Na primjer, ako imate uključene ljepljive tipke, ali pritisnite <span class="key"><kbd> Alt </kbd></span> i <span class="key"><kbd> Tab </kbd></span> istovremeno, ljepljive tipke neće čekati da pritisnete drugu tipku ako je ova opcija uključena. Ali <span class="em"> bi </span> čekalo ako samo pritisnete jednu tipku. To je korisno ako ste u mogućnosti da pritisnete neke prečice na tastaturi istovremeno (primjerice, tipke koje su u neposrednoj blizini zajedno), ali ne i druge.</p>
<p class="p">Odaberite <span class="gui"> Isključi ako su dva tastera pritisnuta istovremeno </span> kako biste omogućili ovo.</p>
<p class="p">Možete napraviti da računar prozvodi  "Beep" zvuk kada počnete tipkati prečicu sa tastature sa ljepljivim tipkama uključenim. Ovo je korisno ako želite da znate da ljepljive tipke očekuju da se otkuca prečica sa tastature, tako da će se sljedeći pritisak na tipku tumačiti kao dio prečice. Odaberite <span class="gui"> Svirni pri pritisku na modifikator. </span> kako biste omogućili ovo.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a></li>
<li class="links ">
<a href="keyboard.html" title="Tastatura">Tastatura</a><span class="desc"> — 
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">Input sources</a></span>,
      <span class="link"><a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">cursor blinking</a></span>,
      <span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>super key</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">keyboard accessibility</a></span>…
    </span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
