<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Simulacija klika lebdeći</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="a11y.html" title="Opšti pristup">Opšti pristup</a> › <a class="trail" href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Simulacija klika lebdeći</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete kliknuti ili povući jednostavno postavljajući miša iznad kontrole ili objekta na zaslonu.</p>
<p class="p">Kad je lebdeći klik omogućen, možete pomicati pokazivač miša preko kontrole, otpustiti tipku miša, i onda sačekati dok gumb bude kliknut za vas.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Opšti pristup </span> i odaberite <span class="gui"> Pokazivanje i klikanje </span> karticu.</p></li>
<li class="steps"><p class="p">Uključite <span class="gui">Klik nadlijetanjem</span> upaljen.</p></li>
</ol></div></div></div>
<p class="p">Prozor <span class="gui">Klik nadlijetanjem</span> će se otvoriti i ostati iznad svih ostalih prozora. Možete ga koristiti da odaberete koja vrsta klika će se desiti kada nadlijećete. Na primjer, ako odaberete <span class="gui">Sekundarni klik</span>, obavit ćtete desni klik kada nadlijećete. Nakon što dva puta kliknete, obavite desni klik ili prevučete. automatski ćete se vratiti na klikanje.</p>
<p class="p">Kada lebdite sa svojim pokazivačem miša iznad dugmeta i ne pomjerate ga, postepeno će mijenjati boju. Kada potpuno promijeni boju, dugme će biti kliknuto.</p>
<p class="p">Podesite <span class="gui"> Odgodu </span> postavljanjem da promijeni koliko dugo morate držati pokazivač miša mirno prije nego što kliknete.</p>
<p class="p">Ne morate savršeno mirno držati miš dok koristite lebdeći klik. Pokazivaču je dozvoljeno malo pomjeranje i kliknut će nakon nekog vremena. Ali, ako se previše pomjera, neće kliknuti.</p>
<p class="p">Prilagodite postavku<span class="gui">Prag kretanja</span> da odredite koiko se pokazivač miša može pomjeriti, a da se to još uvijek smatra nadlijetanjem.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse.html" title="Miš">Miš</a><span class="desc"> — <span class="link"><a href="mouse-lefthanded.html" title="Miš za ljevoruke">Ljevak</a></span>, <span class="link"><a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">brzina i osjetljivost</a></span>, <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">dodirna površina, klik i listanje</a></span>…</span>
</li>
<li class="links "><a href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
