<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Opšti pristup</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Opšti pristup</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Jedinstveni desktop uključuje pomoćne tehnologije za podršku korisnicima sa raznim oštećenjima i posebnim potrebama, za interakciju sa zajedničkim pomagalima. Mnogim značajkama pristupačnosti možete pristupiti sa <span class="gui"> Univerzalni pristup </span> odabirom <span class="gui"> Postavke sistema </span>.</p></div>
<div id="vision" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Oštećenje vida</span></h2></div>
<div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Sljepilo</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="a11y-screen-reader.html" title="Pročitajte naglas ekran">Pročitajte naglas ekran</a><span class="desc"> — Koristite <span class="app"> Orca </span> čitač ekrana da izgovori korisnički interfejs.</span>
</li>
<li class="links ">
<a href="a11y-braille.html" title="Čitanje ekrana na Brajevom pismu.">Čitanje ekrana na Brajevom pismu.</a><span class="desc"> — Koristite <span class="app">Orca</span> čitač ekrana sa osvježavajućim Brajevim (Braille) displejom.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Slabi vid</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">Napravite da kursor tastature treperi.</a><span class="desc"> — Napravite treptaj tačke unosa i kontrolirajte kako brzo treperi.</span>
</li>
<li class="links ">
<a href="a11y-contrast.html" title="Podesite kontrast">Podesite kontrast</a><span class="desc"> — Napravite prozore i tipke na ekranu više (ili manje) živopisne, tako da se lakše vide.</span>
</li>
<li class="links ">
<a href="a11y-font-size.html" title="Promjenite veličinu teksta na ekranu.">Promjenite veličinu teksta na ekranu.</a><span class="desc"> — Koristite veće fontove da bise  tekst lakše čitali.</span>
</li>
</ul></div>
</div></div>
</div></div>
</div></div>
<div id="sound" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Oštećenje sluha</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><ul><li class="links ">
<a href="a11y-visualalert.html" title="Bljesak ekrana za upozorenje zvukom">Bljesak ekrana za upozorenje zvukom</a><span class="desc"> — Omogući vizualna upozorenja, bljesak ekrana ili prozora kad je zvuk upozorenja oglašen.</span>
</li></ul></div></div></div></div></div>
</div></div>
<div id="mobility" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Oštećenje mobilnosti</span></h2></div>
<div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Kretanje miša</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse-mousekeys.html" title="Click and move mouse pointer using the keypad">Click and move mouse pointer using the keypad</a><span class="desc"> — Omogićite tipkama miša da kontrolišete miš pomoću tastature.</span>
</li>
<li class="links ">
<a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">Promijenite brzinu miša ili dodirne površine</a><span class="desc"> — Promijenite koliko se brzo pomjera pokazivač miša kada koristite miš ili dodirnu površinu.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Klikanje i povlačenje</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse-doubleclick.html" title="Podesite brzinu duplog klika">Podesite brzinu duplog klika</a><span class="desc"> — Kontrolirajte koliko brzo morate pritisnuti tipku miša drugi put za dupli klik.</span>
</li>
<li class="links ">
<a href="a11y-right-click.html" title="Simulacija klika desnom tipkom miša">Simulacija klika desnom tipkom miša</a><span class="desc"> — Pritisnite i držite lijevu tipku miša desnom tipkom miša.</span>
</li>
<li class="links ">
<a href="a11y-dwellclick.html" title="Simulacija klika lebdeći">Simulacija klika lebdeći</a><span class="desc"> — Lebdeći klik omogućava vam da kliknete ne pomjerajući miša.</span>
</li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h3><span class="title">Korištenje tastature</span></h3></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard-repeat-keys.html" title="Isključite ponavljanje pritiskanja na tipke">Isključite ponavljanje pritiskanja na tipke</a><span class="desc"> — Provjerite da tastatura ne ponovi slova kada držite pritisnutu  tipku, ili promijenite  kašnjenje i brzinu ponovljenih tipki.</span>
</li>
<li class="links ">
<a href="keyboard-osk.html" title="Koristi raspored na ekranu">Koristi raspored na ekranu</a><span class="desc"> — Koristite tastaturu na ekranu za unos teksta pomoću miša.</span>
</li>
<li class="links ">
<a href="a11y-slowkeys.html" title="Uključi spore tastere">Uključi spore tastere</a><span class="desc"> — Imati kašnjenje između pritisnutih tipki i pojavljivanja slova na ekranu.</span>
</li>
<li class="links ">
<a href="a11y-stickykeys.html" title="Uključite naglašene tipke.">Uključite naglašene tipke.</a><span class="desc"> — Upišite prečice na tastaturi kao tipku po tipku umjesto da držite sve tipke odjednom.</span>
</li>
<li class="links ">
<a href="keyboard-nav.html" title="Upravljanje tastaturom">Upravljanje tastaturom</a><span class="desc"> — Koristite aplikacije i desktop bez miša</span>
</li>
<li class="links ">
<a href="a11y-bouncekeys.html" title="uključi bounce dugmad">uključi bounce dugmad</a><span class="desc"> — Ignoriši brzo-ponovljenja tipkanja iste tipke.</span>
</li>
</ul></div>
</div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
