<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dodajte Arhive ličnih paketa (PPA)</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="addremove.html" title="Dodaj &amp;ukloni softver/program">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dodajte Arhive ličnih paketa (PPA)</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="em">Arhive ličnih paketa(PPA)</span> su programska spremišta dizajnirana za Ubuntu korisnike i koji su lakši za instalaciju od drugih spremišta</p>
<div class="note note-warning" title="Warning"><div class="inner"><div class="region"><div class="contents">
<p class="p">Softverske repozitorije dodajite samo iz izvora kojima vjerujete.</p>
<p class="p">Third-party softver repozitoriji nisu provjereni za sigurnost i pouzdanost od strane Ubuntu članova, i mogu sadržavati softver koji je štetan za vaš računar.</p>
</div></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Instalirajte PPa</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Na PPA pregledu stranice, tražite naslov <span class="gui">Dodajte ovaj PPA na vaš sistem</span>. Napravite bilješku PPA lokacije, koja bi trebala izgledati slično kao: <span class="code">ppa:mozillateam/firefox-next</span>.</p></li>
<li class="steps"><p class="p">Kliknite ikonu <span class="app">Ubuntu Softverkog Centra</span> u <span class="gui">Pokretaču</span>, ili tražite <span class="input">Softverski centar</span> u <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">
        When the Software Center launches, click <span class="guiseq"><span class="gui">Edit</span> ▸ <span class="gui">Software Sources</span></span>
      </p></li>
<li class="steps"><p class="p">Prebacite se na karticu <span class="gui">Ostali softver</span> tab.</p></li>
<li class="steps"><p class="p">Kliknite na <span class="gui">Dodaj</span>  i unesite  lokaciju <span class="code">ppa:</span></p></li>
<li class="steps"><p class="p">Kliknite<span class="gui">Dodaj izvor</span>. Unesite lozinku u prozoru za prijavu.</p></li>
<li class="steps"><p class="p">Zatvorite prozor Softver Izvori. Ubuntu Softver Centar će tada provjeriti vaše softver izvore za novi softver.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Dodaj &amp;ukloni softver/program">Dodaj &amp;ukloni softver/program</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Instalacija dodatnog softvera">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Uklonite aplikaciju">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Dodajte dodatna programske repozitorije">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove-sources.html" title="Dodajte dodatna programske repozitorije">Dodajte dodatna programske repozitorije</a><span class="desc"> — Dodajte druga spremišta za proširenje programskog izvora koji Ubuntu koristi za instalaciju i nadogradnje.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
