<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Používanie programu Synaptic na pokročilejšiu správu softvéru</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Používanie programu Synaptic na pokročilejšiu správu softvéru</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="app">Správca balíkov Synaptic</span> je mocnejší a dokáže robiť niektoré úlohy, ktoré <span class="app">Centrum softvéru Ubuntu</span> urobiť nevie. Rozhranie programu Synaptic je komplikovanejšie a nepodporuje novšie funkcie Centra softvéru, akými sú napríklad hodnotenie aplikácií a náhľady a preto sa jeho používanie neodporúča novým používateľom Ubuntu.</p>
<p class="p">Správca balíkov Synaptic nie je štandardne nainštalovaný, no je ho možné <span class="link"><a href="https://apps.ubuntu.com/cat/applications/synaptic" title="https://apps.ubuntu.com/cat/applications/synaptic">nainštalovať</a></span> pomocou Centra softvéru.</p>
</div>
<div id="install-software-with-synaptic" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Inštalácia softvéru pomocou Správcu balíkov Synaptic</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">
          Open Synaptic from the <span class="gui">Dash</span> or the <span class="gui">Launcher</span>. You 
          will need to enter your password in the <span class="gui">Authenticate</span> window.
        </p></li>
<li class="steps"><p class="p">Kliknutím na <span class="gui">Hľadať</span> vyhľadáme aplikáciu alebo klikneme na <span class="gui">Oblasti</span> a vyhľadáme ju podľa kategórie.</p></li>
<li class="steps"><p class="p">Pravým tlačidlom myši klikneme na aplikáciu, ktorú chceme nainštalovať, a zvolíme<span class="gui"> Označiť na inštaláciu</span>.</p></li>
<li class="steps"><p class="p">
          If you are asked to mark additional changes, click <span class="gui">Mark</span>.
        </p></li>
<li class="steps"><p class="p">Vyberieme aj ďalšie aplikácie, ktoré chceme nainštalovať.</p></li>
<li class="steps"><p class="p">Klikneme na <span class="gui">Použiť</span>, a potom v okne, ktoré sa otvorí, klikneme znova na <span class="gui">Použiť</span>. Aplikácie, ktoré sme si zvolili sa stiahnu a nainštalujú.</p></li>
</ol></div></div></div>
<p class="p">
      For more information about using <span class="app">Synaptic</span>, consult the <span class="link"><a href="https://help.ubuntu.com/community/SynapticHowto" title="https://help.ubuntu.com/community/SynapticHowto">Synaptic How To</a></span>.
    </p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Pridávanie a odstraňovanie softvéru</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Odstránenie aplikácie">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Inštalácia ďalšieho softvéru</a><span class="desc"> — Použitie Centra softvéru Ubuntu na pridanie programov aby sa Ubuntu stalo užitočnejším.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
