<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Instalacija dodatnog softvera</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="addremove.html" title="Dodaj &amp;ukloni softver/program">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Instalacija dodatnog softvera</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Tim Ubuntu razvoj je izabrao zadani skup aplikacija koje smatramo da čini Ubuntu vrlo korisno za većinu svakodnevnih zadataka.Ali svakako ćete željeti instalirati jos programa kako biste napravili Ubuntu još korisnijim za sebe</p>
<p class="p">Da biste instalirali  dodatni program,izvršite sljedeće korake:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Povežite se na Internet koristeći <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">bežičnu</a></span> ili <span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">žičanu konekciju</a></span>.</p></li>
<li class="steps"><p class="p">Kliknite ikonu <span class="app">Ubuntu Softverkog Centra</span> u <span class="gui">Pokretaču</span>, ili tražite <span class="input">Softverski centar</span> u <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">Kada se Software Center pokrene,tražite aplikaciju,ili izaberite kategoriju i nađite aplikaciju u listi</p></li>
<li class="steps"><p class="p">Izaberite program za koji ste zainteresovani i klikinite na <span class="gui">Instaliraj</span>.</p></li>
<li class="steps"><p class="p">Bit ćete pitani da ukucate šifru. Nakon sto ukucate,instalacija će početi</p></li>
<li class="steps"><p class="p">Instalacija uobičajeno završi brzo, ali može potrajati ukoliko imate sporu Internet konekciju.</p></li>
<li class="steps"><p class="p">Kratica za vaš novi program se dodaje u pokretač. Da isključite ovu mogućnost deaktivirajte<span class="guiseq"><span class="gui">Pogled</span> ▸ <span class="gui">Nove aplikacije u pokretaču</span></span>.</p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Dodaj &amp;ukloni softver/program">Dodaj &amp;ukloni softver/program</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Instalacija dodatnog softvera">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Uklonite aplikaciju">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Dodajte dodatna programske repozitorije">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="prefs-language-install.html" title="Install languages">Install languages</a><span class="desc"> — Install more translations and related language support packages.</span>
</li>
<li class="links ">
<a href="addremove-install-synaptic.html" title="Koristite Synaptic za naprednije upravljanje paketima">Koristite Synaptic za naprednije upravljanje paketima</a><span class="desc"> — Syinaptic je moćna ali komplikovana softverska alternativa za Ubuntu Software Centar</span>
</li>
<li class="links ">
<a href="addremove-remove.html" title="Uklonite aplikaciju">Uklonite aplikaciju</a><span class="desc"> — Uklonite program koji dugo ne koristite</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
