<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pridanie ďalších zdrojov softvéru</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Add/remove software</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pridanie ďalších zdrojov softvéru</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Softvér je okrem softvérových zdrojov Ubuntu dostupný aj z ďalších zdrojov. Ak chceme inštalovať softvér z úložiska iných dodávateľov, musíme si toto úložisko pridať do zoznam zdrojov softvéru.</p>
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents">
<p class="p">Pridávať je vhodné iba tie zdroje, ktorým dôverujeme!</p>
<p class="p">Bezpečnosť zdrojov softvéru od tretích strán nie je preverená vývojármi softvéru ani komunitou a použitie takýchto zdrojov môže byť pre počítač škodlivé.</p>
</div></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Inštalácia ďalších zdrojov</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikneme na ikonu <span class="app">Centrum softvéru Ubuntu</span> na spúšťači alebo vyhľadáme Centrum softvéru v <span class="app">Prehľadnej ponuke</span>.</p></li>
<li class="steps"><p class="p">
        When the Software Center launches, click <span class="guiseq"><span class="gui">Edit</span> ▸ <span class="gui">Software Sources</span></span>
      </p></li>
<li class="steps"><p class="p">Systém si vyžiada naše heslo. Po jeho zadaní sa prepneme na kartu <span class="gui">Ďalší softvér</span>.</p></li>
<li class="steps">
<p class="p">Klikneme na tlačidlo <span class="gui">Pridať</span> a do poľa Riadok APT zadáme adresu úložiska. Táto adresa sa nachádza na webovej stránke výrobcu softvéru a má nasledujúci tvar:</p>
<p class="p">
        <span class="code">deb http://archive.ubuntu.com/ubuntu/ trusty main</span>
      </p>
</li>
<li class="steps"><p class="p">Klikneme na tlačidlo <span class="gui">Pridať zdroj</span>, a potom okno Zdroje softvéru zatvoríme. Centrum softvéru Ubuntu skontroluje nové aktualizácie v zdrojoch softvéru.</p></li>
</ol></div>
</div></div>
</div>
<div id="canonical-partner" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Aktivácia úložiska partnerov spoločnosti Canonical</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Úložisko Partneri Canonicalu poskytuje niekoľko neslobodných aplikácií, ktoré sú zadarmo ale majú utajený zdrojový kód. Obsahuje softvér ako napríklad <span class="app">Skype</span>, <span class="app">Adobe Reader</span> a <span class="app">Adobe Flash Plugin</span>. Softvér z tohto úložiska sa zobrazuje v Centre softvéru Ubuntu no nedá sa nainštalovať, pokým nie je úložisko povolené.</p>
<p class="p">Keď chceme úložisko povoliť, budeme postupovať podľa predchádzajúceho postupu až po prepnutie sa na kartu <span class="gui">Ďalší softvér</span>. Ak úložisko Partneri Canonicalu vidíme v zozname, zaškrtneme ho a zatvoríme okno <span class="app">Zdroje softvéru</span>. Ak ho nevidíme, klikneme na tlačidlo <span class="gui">Pridať</span> a zadáme:</p>
<p class="p">
      <span class="code">deb http://archive.canonical.com/ubuntu trusty partner</span>
    </p>
<p class="p">Klikneme na <span class="gui">Pridať zdroj</span>, a potom zatvoríme okno Zdroje softvéru. Chvíľu počkáme, pokým Centrum softvéru Ubuntu nestiahne informácie o úložiskách.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Pridávanie a odstraňovanie softvéru</a><span class="desc"> — 
      <span class="link"><a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Odstránenie aplikácie">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">extra repositories</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="addremove-ppa.html" title="Pridanie osobného úložiska (PPA)">Pridanie osobného úložiska (PPA)</a><span class="desc"> — Pridanie osobného úložiska kvôli otestovaniu ešte nevydaného alebo špeciálneho softvéru.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
