<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bluetooth</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Bluetooth</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Bluetooth je bežični protokol koji omogućuje povezivanje mnogo različitih vrsta uređaja s računalom. Bluetooth se obično koristi za slušalice i ulaznih uređaja kao što su miševi i tipkovnice. Također možete koristiti Bluetooth za <span class="link"><a href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju"> poslati datoteke između uređaja </a></span>, kao što je iz računala na vaš mobilni telefon.</p>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite"><span class="title">Uključite Bluetooth ili isključite</span><span class="linkdiv-dash"> — </span><span class="desc">Omogućite ili onemogućite Bluetooth uređaj na vašem računaru.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="sharing-bluetooth.html" title="Control sharing over Bluetooth"><span class="title">Control sharing over Bluetooth</span><span class="linkdiv-dash"> — </span><span class="desc">Bluetooth file sharing and receiving options.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem"><span class="title">Povežite vaš računar sa Bluetooth uređajem</span><span class="linkdiv-dash"> — </span><span class="desc">Par Bluetooth uređaja.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju"><span class="title">Pošalji datoteku Bluetooth uređaju</span><span class="linkdiv-dash"> — </span><span class="desc">Dijelite datoteke sa Bluetooth uređajima kao što je vaš telefon.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="bluetooth-remove-connection.html" title="Uklonite vezu između Bluetooth uređaja"><span class="title">Uklonite vezu između Bluetooth uređaja</span><span class="linkdiv-dash"> — </span><span class="desc">Uklonite uređaj s popisa Bluetooth uređaja.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="bluetooth-visibility.html" title="Šta je vidljivost Bluetooth-a?"><span class="title">Šta je vidljivost Bluetooth-a?</span><span class="linkdiv-dash"> — </span><span class="desc">Da li će ili ne  drugi uređaji moći otkriti vaš računar.</span></a></div>
</div></div></div>
</div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problemi</span></h2></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><div class="linkdiv "><a class="linkdiv" href="bluetooth-problem-connecting.html" title="Ne mogu se povezati na moj Bluetooth uređaj"><span class="title">Ne mogu se povezati na moj Bluetooth uređaj</span><span class="linkdiv-dash"> — </span><span class="desc">Adapter može biti isključen ili ne imati drajvere,  ili Bluetooth može biti onemogućen ili blokiran.</span></a></div></div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h3><span class="title">More Information</span></h3></div>
<div class="region"><ul><li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a><span class="desc"> — <span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
