<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prikaži druge vremenske zone</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="clock.html" title="Vrijeme &amp; datum">Vrijeme &amp; datum</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Prikaži druge vremenske zone</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako želite znati koje je to vrijeme u različitim gradovima diljem svijeta, možete dodati dodatne vremenske zone na menij sata. Ovi dodatni gradovi će se pojaviti ispod kalendara kada kliknete na sat.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click on the clock and select <span class="gui">Date &amp; Time Settings</span>.</p></li>
<li class="steps"><p class="p">Prebaci se na <span class="gui"> sat </span> karticu i odaberite <span class="gui"> Vrijeme na drugim mjestima </span>.</p></li>
<li class="steps"><p class="p">Kliknite na <span class="gui">Odaberite lokacije</span>.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">+</span> da dodate lokaciju.</p></li>
<li class="steps"><p class="p">Ispunite Prazno mjesto sa imenom grada koje želite dodati. Pričekajte trenutak za popis mogućih gradova da se prikažu u padajućem popisu.</p></li>
<li class="steps"><p class="p">Odaberite grad koji želite i trenutno vrijeme u tom mjestu će se ispuniti automatski.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui"> - </span> da izbrišete grad sa popisa.</p></li>
<li class="steps"><p class="p">Također možete povući i ispustiti gradove u ovom <span class="gui"> Lokacije </span> prozoru za promjenu redoslijeda u kojem će se prikazati u meniju sata.</p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="clock.html" title="Vrijeme &amp; datum">Vrijeme &amp; datum</a><span class="desc"> — 
      <span class="link"><a href="clock-set.html" title="Change the date and time">Set time and date</a></span>,
      <span class="link"><a href="clock-timezone.html" title="Prikaži druge vremenske zone">timezone</a></span>,
      <span class="link"><a href="clock-calendar.html" title="Calendar appointments">calendar and appointments</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="clock-set.html" title="Change the date and time">Change the date and time</a><span class="desc"> — Ažuriraj vrijeme / datum prikazan na vrhu ekrana.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
