<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako kalibrirati moj aparat?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#calibration" title="Kalibracija">Kalibracija</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#calibration" title="Kalibracija">Kalibracija</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako kalibrirati moj aparat?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kamere su kalibrirane uzimajući fotografiju cilja pod željenim svjetlosnim uvjetima. Pretvaranjem RAW datoteka u TIFF datoteku,  može se koristiti za kalibriranje kamere na ploči kontrole za boje.</p>
<p class="p">Morat ćete obrezati TIFF datotekekako bi samo ciljna vidljiva. Provjerite je li bijeli ili crni granice su još uvijek vidljive. Kalibracija neće raditi ako je slika naopako ili je iskrivljena od strane velikog iznosa.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">rezultantni profil vrijedi samo pod uvjetom da rasvjete ste nabavili originalnu sliku iz. To znači da ćete morati profilirati nekoliko puta za <span class="em"> studiju </span>, <span class="em"> svijetle suncu </span> i <span class="em"> oblačno </span> svjetlosnim uvjetima.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#calibration" title="Kalibracija">Kalibracija</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="color-calibrate-screen.html" title="Kako kalibrirati ekran?">Kako kalibrirati ekran?</a><span class="desc"> — Kalibriranje ekrana je važno za prikaz tačne boje.</span>
</li>
<li class="links ">
<a href="color-calibrate-printer.html" title="Kako kalibrirati moj printer?">Kako kalibrirati moj printer?</a><span class="desc"> — Kalibriranje vašeg printera je važno za ispis tačne boje.</span>
</li>
<li class="links ">
<a href="color-calibrate-scanner.html" title="Kako kalibrirati moj skener?">Kako kalibrirati moj skener?</a><span class="desc"> — Kalibriranje vašeg skenera je važno za hvatanje tačne boje.</span>
</li>
<li class="links ">
<a href="color-calibrationtargets.html" title="Koji odredišni tipovi su podržani?">Koji odredišni tipovi su podržani?</a><span class="desc"> — Kalibracijski objekti su potrebni za rad  profiliranja skenera i kamere.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
