<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Rozdiel medzi kalibráciou a charakterizáciou</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#calibration" title="Kalibrácia">Kalibrácia</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#calibration" title="Kalibrácia">Kalibrácia</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Rozdiel medzi kalibráciou a charakterizáciou</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Mnoho ľudí nevie, aký je rozdiel medzi kalibráciou a charakterizáciou. Kalibrácia je proces úpravy farebného správania zariadenia. Vykonáva sa zvyčajne dvoma spôsobmi:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Zmenou ovládania alebo vnútornými nastaveniami, ktoré zariadenie má</p></li>
<li class="list"><p class="p">Aplikovaním kriviek na jednotlivé farebné kanály</p></li>
</ul></div></div></div>
<p class="p">Myšlienka kalibrácie je, dostať zariadenie do definovaného stavu, pri ktorom vykazuje želané správanie pri reprodukcii farieb. Toto nastavenie je často potrebné vykonávať dennodenne aby sa želané správanie zachovalo. Kalibračné hodnoty sa ukladajú do formátov určených zariadením alebo systémami a obsahujú nastavenia zariadenia alebo kalibračné krivky pre každý kanál.</p>
<p class="p">Charakterizácia (alebo profilovanie) je <span class="em">zaznamenávanie</span> spôsobu, akým zariadenie reprodukuje alebo reaguje na farby. Výsledok tejto operácie je uložený do profilu ICC. Takýto profil sám o sebe farby žiadnym spôsobom nemení, no umožňuje systémom ako napríklad CMM (Color Management Module) alebo aplikáciám so správou farieb upraviť farbu, keď je kombinovaná s profilom iného zariadenia. Na základe znalosti charakteristík dvoch zariadení, sa urobí prevod reprezentácie farieb z jedného zariadenia do druhého.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">
      Note that a characterization (profile) will only be valid for a device
      if it's in the same state of calibration as it was when it was
      characterized.
    </p></div></div></div></div>
<p class="p">V prípade profilov pre displeje, je v tom trochu zmätok, pretože kalibračné údaje sú kvôli pohodliu súčasťou profilu. Podľa dohovoru sú uložené v značke vcgt. Aj napriek tomu, že sú v profile uložené, žiadny z nástrojov založených na ICC ich neberie do úvahy, ani s nimi nič nerobí. Podobne sa žiadny z nástrojov na kalibrovanie nezaoberá informáciami uloženými v profile ICC.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#calibration" title="Kalibrácia">Kalibrácia</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
