<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Skontrolovanie chýb na disku</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="disk.html" title="Disky a úložiská">Disky a úložiská</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Skontrolovanie chýb na disku</span></h1></div>
<div class="region">
<div class="contents"></div>
<div id="disk-status" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kontrola pevného disku</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Pevné disky majú vstavaný nástroj na kontrolu funkčnosti s názvom <span class="app">SMART</span> (Self-Monitoring, Analysis, and Reporting Technology - nástroj na sebakontrolu, analýzu a hlásenie), ktorý neustále sleduje možné problémy. SMART nás tiež varuje, ak hrozí zlyhanie disku, aby sa predišlo strate dôležitých údajov.</p>
<p class="p">Although SMART runs automatically, you can also check your disk's
 health by running the <span class="app">Disks</span> application:</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h3><span class="title">Check your disk's health using the Disks application</span></h3></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Open the <span class="app">Disks</span> application from the <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">Select the disk you want to check from the <span class="gui">Storage Devices</span> list.
  Information and status of the disk will appear under <span class="gui">Drive</span>.</p></li>
<li class="steps"><p class="p"><span class="gui">Stav SMART</span> by mal byť „Disk je v dobrom stave“.</p></li>
<li class="steps"><p class="p">Ak chceme vidieť viac informácií alebo chceme spustiť samokontrolu, klikneme na tlačidlo <span class="gui">Údaje SMART</span>.</p></li>
</ol></div>
</div></div>
</div></div>
</div></div>
<div id="disk-not-healthy" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Čo robiť keď disk nie je v dobrom stave</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Aj napriek tomu, že <span class="gui">Stav SMART</span> indikuje, že disk <span class="em">nie je</span> v dobrom stave, nemusíme sa plašiť. Bude však lepšie, a si vytvoríme <span class="link"><a href="backup-why.html" title="Zálohovanie dôležitých súborov">zálohu</a></span>, aby sme predišli strate dát.</p>
<p class="p">Ak je stav „Pre-fail“, disk je ešte stále funkčný, no vykazuje známky opotrebovania, ktoré v blízkej budúcnosti môžu viesť k zlyhaniu. Ak je disk (alebo počítač) niekoľko rokov starý, pri niektorých kontrolách stavu to pravdepodobne uvidíme. Mali by sme nastaviť <span class="link"><a href="backup-how.html" title="Ako zálohovať">pravidelnú zálohu dôležitých súborov</a></span> a pravidelne kontrolovať stav disku, aby sme videli, či sa to zhoršuje.</p>
<p class="p">Ak sa to zhoršuje, možno bude potrebné počítač alebo pevný disk, zveriť na opravu profesionálom.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Disky a úložiská">Disky a úložiská</a><span class="desc"> — 
    <span class="link"><a href="disk-capacity.html" title="Kontrola zostávajúceho voľného miesta">Disk space</a></span>,
    <span class="link"><a href="disk-benchmark.html" title="Testovanie výkonu pevného disku">performance</a></span>,
    <span class="link"><a href="disk-check.html" title="Skontrolovanie chýb na disku">problems</a></span>,
    <span class="link"><a href="disk-partitions.html" title="Správa zväzkov a oddielov">volumes and partitions</a></span>…
  </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
