<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Provjerite koliko je slobodnog prostora u diksu ostalo</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Provjerite koliko je slobodnog prostora u diksu ostalo</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Možete provjeriti koliko prostora na disku je slobodno koristeći  <span class="app">Analizer Zauzetosti Diska</span> ili <span class="app">Monitor Sistema</span>.</p></div>
<div id="disk-usage-analyzer" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite sa Analizatorom disk iskoristivosti</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Da biste provjerili slobodni prostor na disku i iskorištenost kapaciteta diska koristeći <span class="app"> Analizator iskoristivosti diska  </span>:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Open the <span class="app">Disk Usage Analyzer</span> application from the
 <span class="gui">Dash</span>. The window will display the <span class="gui">Total file system capacity</span>
  and <span class="gui">Total file system usage</span>.</p></li>
<li class="list"><p class="p">Kliknite na jednu od dugmadi na alatnoj traci odabrati da <span class="gui"> Skeniraj lični direktorij </span>, <span class="gui"> skeniranje datotečni sustav </span>, <span class="gui"> Skeniranje mape </span> ili <span class="gui"> Skeniranje udaljene mapu </span></p></li>
</ul></div></div></div>
<p class="p">Informacije se prikazuju prema <span class="gui">Folder</span>, <span class="gui">Upotreba</span>, <span class="gui">Veličina</span> i <span class="gui">Sadržaj</span>. Pogledajte više detalja na <span class="link"><a href="https://help.gnome.org/users/baobab/stable/" title="https://help.gnome.org/users/baobab/stable/"><span class="app">Analizer zauzetosti diska</span></a></span>.</p>
</div></div>
</div></div>
<div id="system-monitor" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite sa Nadzornikom sistema</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Da biste provjerili slobodni prostor na disku i kapacitet diska sa <span class="app"> Nadzornik sistema </span>:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite <span class="app"> Nadzornik sistema </span> aplikacije iz <span class="gui"> Dash (pristup svim programima) </span>.</p></li>
<li class="steps"><p class="p">Odaberite tab<span class="gui">Sistem Datoteka</span>da vidite particije sistema i iskorištenost prostora na disku. Informacije su prikazane prema <span class="gui">Ukupan prostor</span>,<span class="gui">Slobodan prostor</span>, <span class="gui">Slobodan prostor</span> i <span class="gui"> Iskorišten prostor</span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="disk-full" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Šta ako je disk previše pun?</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako je disk pun trebali bi da:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Izbrišite datoteke koje vam nisu važne ili koje nećete više koristiti.</p></li>
<li class="list"><p class="p">Napravite  <span class="link"><a href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka">sigurnosne kopije </a></span> od važnih datoteka koje vam neće trebati neko vrijeme te ih izbrišite ih s tvrdog diska.</p></li>
</ul></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a><span class="desc"> — <span class="link"><a href="disk-capacity.html" title="Provjerite koliko je slobodnog prostora u diksu ostalo">Kapacitet Diska</a></span>, <span class="link"><a href="disk-benchmark.html" title="Testirajte performanse vašeg tvrdog diska">performance</a></span>, <span class="link"><a href="disk-check.html" title="Provjerite vaš tvrdi disk na probleme">problemi</a></span>, <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama">količine i particije</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
