<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Disky a úložiská</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Disky a úložiská</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="disk-capacity.html" title="Kontrola zostávajúceho voľného miesta"><span class="title">Kontrola zostávajúceho voľného miesta</span><span class="linkdiv-dash"> — </span><span class="desc">Use <span class="gui">Disk Usage Analyzer</span> or <span class="gui">System Monitor</span> to
    check space and capacity.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="disk-check.html" title="Skontrolovanie chýb na disku"><span class="title">Skontrolovanie chýb na disku</span><span class="linkdiv-dash"> — </span><span class="desc">Test your hard disk for problems to make sure that it's healthy.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="disk-partitions.html" title="Správa zväzkov a oddielov"><span class="title">Správa zväzkov a oddielov</span><span class="linkdiv-dash"> — </span><span class="desc">Vysvetlenie toho, čo sú zväzky a oddiely a ako ich spravovať pomocou diskových nástrojov.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="disk-benchmark.html" title="Testovanie výkonu pevného disku"><span class="title">Testovanie výkonu pevného disku</span><span class="linkdiv-dash"> — </span><span class="desc">Run benchmarks on your hard disk to check how fast it is.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="disk-format.html" title="Vymazanie odpojiteľného disku"><span class="title">Vymazanie odpojiteľného disku</span><span class="linkdiv-dash"> — </span><span class="desc">Odstránenie všetkých súborov a priečinkov z externého pevného disku alebo USB kľúča formátovaním.</span></a></div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware.html" title="Hardvér a ovládače">Hardvér a ovládače</a><span class="desc"> — 
      <span class="link"><a href="hardware.html#problems" title="Časté problémy">Hardware problems</a></span>,
      <span class="link"><a href="printing.html" title="Tlačiť">printers</a></span>,
      <span class="link"><a href="power.html" title="Power &amp; battery">power settings</a></span>,
      <span class="link"><a href="color.html" title="Správa farieb">color management</a></span>,
      <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>,
      <span class="link"><a href="disk.html" title="Disky a úložiská">disks</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
