<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Postavite osvjetljenje ekrana</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="power.html#problems" title="Problemi">Problemi sa snagom</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Postavite osvjetljenje ekrana</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete promijeniti osvjetljenje vašeg ekrana da štedite energiju ili da učinite ekran čitljivijim na jakom svjetlu. Možete također postaviti da se ekran automatski zatamni kada je na bateriji i da se ugasi kada nije u upotrebi.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Postavite osvjetljenje</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Odaberite <span class="gui">Zaključavanje osvjetljenja</span>.</p></li>
<li class="steps"><p class="p">Podesite <span class="gui"> Osvjetljenje </span> klizač na udobnu vrijednost.</p></li>
</ol></div>
</div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Many laptop keyboards have special keys to adjust the brightness. These
    have a picture that looks like the sun and are located on the function
    keys at the top. Hold down the <span class="key"><kbd class="key-Fn">Fn</kbd></span> key to use these keys.</p></div></div></div></div>
<p class="p">Odaberite <span class="gui"> Zamaglite ekran za čuvanje energije </span> da se osvjetljenje automatski smanji kada ste na bateriji. Pozadinsko svjetlo ekrana može uzeti puno snage i znatno smanjiti koliko dugo će baterija trajati prije nego se bude trebala napuniti.</p>
<p class="p">Ekran će se automatski ugasiti kada se ne koristi određeno vrijeme. Ovo samo utiče na ekran, i neće se isključiti računar. Možete podesiti koliko dugo morate biti neaktivan da se <span class="gui"> isključi ekran </span> u postavkama.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a><span class="desc"> — <span class="link"><a href="look-background.html" title="Promijenite pozadinu">Pozadina</a></span>, <span class="link"><a href="look-resolution.html" title="Promijenite veličinu rotacije ekrana">veličina i rotacija</a></span>, <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">svjetlost</a></span>…</span>
</li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li>
<li class="links ">
<a href="power.html#problems" title="Problemi">Problemi sa snagom</a><span class="desc"> — Otklanjanje problema sa snagom i baterijama.</span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="display-lock.html" title="Automatski zaključajte vaš ekran">Automatski zaključajte vaš ekran</a><span class="desc"> — Spriječite druge osobe da koriste radnu površinu kada odete dalje od računara.</span>
</li>
<li class="links ">
<a href="a11y-contrast.html" title="Podesite kontrast">Podesite kontrast</a><span class="desc"> — Napravite prozore i tipke na ekranu više (ili manje) živopisne, tako da se lakše vide.</span>
</li>
<li class="links ">
<a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">Zašto se moj ekran zamagli nakon nekog vremena?</a><span class="desc"> — Ako vaš računar radi na bateriju, ekran će se zatamniti kada računar miruje kako bi uštedio snagu.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
