<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Triedenie súborov a priečinkov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Triedenie súborov a priečinkov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can sort files in different ways in a folder, for example by sorting them
in order of date or file size. See <span class="link"><a href="#ways" title="Spôsoby usporiadania súborov">Spôsoby usporiadania súborov</a></span> below for a list of
common ways to sort files. See <span class="link"><a href="nautilus-views.html" title="Views preferences in Files">Views preferences in <span class="app">Files</span></a></span> for information on
how to change the default sort order.</p>
<p class="p">The way that you can sort files depends on the <span class="em">folder view</span> that you
are using. You can change the current view using the list or icon buttons in the
toolbar.</p>
</div>
<div id="icon-view" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pohľad Ikony</span></h2></div>
<div class="region"><div class="contents">
<p class="p">To sort files in a different order, click the
 <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span> button in the
 toolbar and choose <span class="gui">By Name</span>, <span class="gui">By Size</span>, <span class="gui">By Type</span>
 or <span class="gui">By Modification Date</span>.</p>
<p class="p">As an example, if you select <span class="gui">By Name</span>, the files will be sorted by
 their names, in alphabetical order. See <span class="link"><a href="#ways" title="Spôsoby usporiadania súborov">Spôsoby usporiadania súborov</a></span> for other options.</p>
<p class="p">You can sort in the reverse order by selecting <span class="gui">Reversed Order</span>
 from the pull-down menu.</p>
</div></div>
</div></div>
<div id="list-view" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pohľad Zoznam</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Keď chceme súbory usporiadať rôznymi spôsobmi, klikneme na jednu z hlavičiek stĺpcov v správcovi súborov. Napríklad kliknutím na <span class="gui">Typ</span> usporiadame stĺpce podľa ich typu. Keď na hlavičku stĺpca klikneme znova, usporiada sa v opačnom poradí.</p>
<p class="p">In list view, you can show columns with more attributes and sort on those
 columns. Click the
 <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span> button in the
 toolbar, pick <span class="gui">Visible Columns</span> and select the columns that you want
 to be visible. You will then be able to sort by those columns. See
 <span class="link"><a href="nautilus-list.html" title="Nastavenia stĺpcov v zozname správcu súborov">Nastavenia stĺpcov v zozname správcu súborov</a></span> for descriptions of available columns.</p>
</div></div>
</div></div>
<div id="ways" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Spôsoby usporiadania súborov</span></h2></div>
<div class="region"><div class="contents"><div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">Podľa názvu</dt>
<dd class="terms"><p class="p">Usporiada súbory abecedne podľa ich názvu.</p></dd>
<dt class="terms">Podľa veľkosti</dt>
<dd class="terms"><p class="p">Usporiada súbory podľa ich veľkosti (podľa toho, koľko priestoru zaberajú na disku). Súbory budú usporiadané od najmenšieho po najväčší.</p></dd>
<dt class="terms">Podľa typu</dt>
<dd class="terms"><p class="p">Usporiada súbory abecedne podľa ich typu. Súbory rovnakého typu budú zoskupené a usporiadané podľa ich názvu.</p></dd>
<dt class="terms">Podľa dátumu zmeny</dt>
<dd class="terms"><p class="p">Usporiada súbory podľa dátumu a času poslednej zmeny. Súbory budú usporiadané od najstaršieho po najnovší.</p></dd>
</dl></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Vyhľadávanie súborov">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
