<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zápis súborov na CD a DVD</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zápis súborov na CD a DVD</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can put files onto a blank disc by using <span class="gui">CD/DVD Creator</span>. The
 option to create a CD or DVD will appear in the file manager as soon as you
 place the CD into your CD/DVD writer. The file manager lets you transfer files
 to other computers or perform <span class="link"><a href="backup-why.html" title="Zálohovanie dôležitých súborov">backups</a></span> by putting
 files onto a blank disc. To write files to a CD or DVD:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Umiestnime prázdny disk do zapisovacej mechaniky CD/DVD.</p></li>
<li class="steps">
<p class="p">In the <span class="gui">Blank CD/DVD-R Disc</span> window that appears,
     select <span class="gui">CD/DVD Creator</span> and click <span class="gui">OK</span>.
     The <span class="gui">CD/DVD Creator</span> folder window will open.</p>
<p class="p">(Môžeme tiež kliknúť na položku <span class="gui">Čistý disk CD/DVD-R</span> pod nápisom <span class="gui">Zariadenia</span> na bočnom paneli v správcovi súborov.)</p>
</li>
<li class="steps"><p class="p">Do poľa <span class="gui">Názov disku</span> zadáme názov pre nový disk.</p></li>
<li class="steps"><p class="p">Drag or copy the desired files into the window.</p></li>
<li class="steps"><p class="p">Click <span class="gui">Write to Disc</span>.</p></li>
<li class="steps">
<p class="p">V časti <span class="gui">Vyberte cieľový disk</span>, zvolíme čistý disk.</p>
<p class="p">(Môžeme namiesto toho zvoliť <span class="gui">Napáliť do súboru</span>. Týmto umiestnime súbor do tzv. <span class="em">obrazu disku</span>, ktorý sa uloží do nášho počítača. Neskôr tento obraz môžeme na čistý disk.)</p>
</li>
<li class="steps"><p class="p">Ak chceme zmeniť rýchlosť napaľovania, umiestnenie dočasný súborov a iné nastavenia, klikneme na <span class="gui">Vlastnosti</span>. Predvolené vlastnosti však vo väčšine prípadov vyhovujú.</p></li>
<li class="steps">
<p class="p">Klikneme na tlačidlo <span class="gui">Napáliť</span>.</p>
<p class="p">Ak zvolíme <span class="gui">Napáliť viacero kópií</span>, program nás vyzve, aby sme po skončení každého napaľovania vložili ďalší disk.</p>
</li>
<li class="steps"><p class="p">When the disc burning is complete, it will eject automatically. Choose
     <span class="gui">Make More Copies</span> or <span class="gui">Close</span> to exit.</p></li>
</ol></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents">
<p class="p">Ak chceme napáliť inú formu CD/DVD  (zvukový disk, film), môžeme skúsiť program Brasero.</p>
<p class="p">For help with using Brasero, read the <span class="link"><a href="https://help.gnome.org/users/brasero/stable/" title="https://help.gnome.org/users/brasero/stable/">user guide</a></span>.</p>
</div></div></div></div>
</div>
<div id="problem" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">If the disc wasn't burned properly</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Sometimes the computer doesn't record the data correctly, and you won't be
 able to see the files you put onto the disc when you insert it into a computer.</p>
<p class="p">In this case, try burning the disc again but use a lower burning speed, e.g.
 12x rather than 48x. Burning at slower speeds is more reliable. You can choose
 the speed by clicking the <span class="gui">Properties</span> button in the
 <span class="gui">CD/DVD Creator</span> window.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Vyhľadávanie súborov">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
