<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>šabloni  za najčešće korištne vrste dokumenata.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">šabloni  za najčešće korištne vrste dokumenata.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako često stvarate dokumente  temeljene na  istom sadržaju, možda ćete imati koristi od korištenja datoteke šablona. Datoteka šablona može biti dokument bilo koje vrste formatiranja ili sadržaja koji želite ponovno koristiti. Na primjer, možete stvoriti šablon dokumenta sa svojim zaglavljem.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Napravite novi šablon</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Napravite dokument koji ćete korsititi kao šablon. Na primjer, možete napraviti svoje zaglavlje u aplikacijama u obradi teksta.</p></li>
<li class="steps"><p class="p">Snimite datoteku koja sadrži šablon u  <span class="file">Šabloni</span> folderu u vašem <span class="file">Home</span> folderu. Ako <span class="file">Šabloni</span> folder ne postoji, prvo ćete ga morati kreirati.</p></li>
</ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Koritite šablone za izradu dokumenata.</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite mapu u koju želite da stavite novi dokument</p></li>
<li class="steps"><p class="p">Right-click anywhere in the empty space in the folder, then choose
    <span class="gui">New Document</span>. The names of available
    templates will be listed in the submenu.</p></li>
<li class="steps"><p class="p">Odaberite željeni šablon iz liste.</p></li>
<li class="steps"><p class="p">Unesite naziv datoteke za novostvoreni dokument.</p></li>
<li class="steps"><p class="p">Dvaput kliknite na datoteku da biste je otvorili i počeli uređivanje.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
