<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Otvorite aplikacije za uređaje ili diskove</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#videos" title="Video i video kamere">Video</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Otvorite aplikacije za uređaje ili diskove</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete postaviti da se aplikacija automatski pokrene kada spojite neki uređaj ili ubacite disk ili karticu. Na primjer, možda želite da se organizator slika automatski pokrene kada spojite digitalnu kameru. Ovu opciju također možete isključiti, tako da se ništa neće desiti kada nešto spojite.</p>
<p class="p">Da odlučite koje aplikacije se trebaju pokrenuti kada priključite razne uređaje:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Odaberite <span class="guiseq"><span class="gui">Detalji</span> ▸ <span class="gui">Uklonjivi Medij</span></span>.</p></li>
<li class="steps">
<p class="p">Find your desired device or media type, and then choose an application
    or action for that media type. See below for a description of the different
    types of devices and media.</p>
<p class="p">Instead of starting an application, you can also set it so that the device
    will be shown in the file manager. When that happens, you will be asked
    what to do, or nothing will happen automatically.</p>
</li>
<li class="steps"><p class="p"><span class="gui"> Softver </span> opcija je malo drugačija od drugih - ako računar otkrije da postoji softver na disku koji ste umetnuli, može pokušati automatski pokrenuti program ako želite. To je dobro ako imate program instaliran na CD-u i želite da se pokrene kada je disk umetnut (na primjer, slideshow).</p></li>
<li class="steps"><p class="p">Ako ne vidite uređaj ili vrstu medija koju želite promijeniti na popisu (kao što su Blu-ray diskova ili E-knjige čitatelji), kliknite <span class="gui"> drugim medijima </span> da vidite detaljniji popis uređaja. Odaberite vrstu uređaja ili medija iz <span class="gui"> Type </span> padajućem i program ili radnju iz <span class="gui"> akcije </span> padajući.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Ukoliko ne želite da se bilo koja aplikacija automatski otvori, bez obzira šta priključili, odaberite <span class="gui"> Nikada izazvati ili pokrenuti programe umetanjem medija </span> na dnu prozora Prijenosni medij.</p></div></div></div></div>
</div>
<div id="files-types-of-devices" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Types of devices and media</span></h2></div>
<div class="region"><div class="contents"><div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">Audio diskovi</dt>
<dd class="terms"><p class="p">Choose your favorite music application or CD audio extractor to handle
    audio CDs. If you use audio DVDs (DVD-A), select how to open them under
    <span class="gui">Other Media</span>. If you open an audio disc with the file manager,
    the tracks will appear as WAV files that you can play in any audio player
    application.</p></dd>
<dt class="terms">Video diskovi</dt>
<dd class="terms"><p class="p">Choose your favorite video application to handle video DVDs. Use the
    <span class="gui">Other Media</span> button to set an application for Blu-ray, HD DVD,
    video CD (VCD), and super video CD (SVCD). If DVDs or other video discs
    do not work correctly when you insert them, see <span class="link"><a href="video-dvd.html" title="Zašto DVD ne radi?">Zašto DVD ne radi?</a></span>.
    </p></dd>
<dt class="terms">Prazni diskovi</dt>
<dd class="terms"><p class="p">Use the <span class="gui">Other Media</span> button to select a disc-writing
    application for blank CDs, blank DVDs, blank Blu-ray discs, and blank HD
    DVDs.</p></dd>
<dt class="terms">Cameras and photos</dt>
<dd class="terms">
<p class="p">Use the <span class="gui">Photos</span> drop-down to choose a photo-management
    application to run when you plug in your digital camera, or when you insert
    a media card from a camera, such as a CF, SD, MMC, or MS card. You can also
    simply browse your photos using the file manager.</p>
<p class="p">Under <span class="gui">Other Media</span>, you can select an application to open Kodak
    picture CDs, such as those you might have made in a store. These are regular
    data CDs with JPEG images in a folder called <span class="file">PICTURES</span>.</p>
</dd>
<dt class="terms">Music players</dt>
<dd class="terms"><p class="p">Choose an application to manage the music library on your portable music
    player, or manage the files yourself using the file manager.</p></dd>
<dt class="terms">E-book readers</dt>
<dd class="terms"><p class="p">Use the <span class="gui">Other Media</span> button to choose an application to manage the
    books on your e-book reader, or manage the files yourself using the file manager.</p></dd>
<dt class="terms">Softver</dt>
<dd class="terms">
<p class="p">Some discs and removable media contain software that is supposed to be run
    automatically when the media is inserted. Use the <span class="gui">Software</span> option
    to control what to do when media with autorun software is inserted. You will
    always be prompted for a confirmation before software is run.</p>
<div class="note note-warning" title="Warning"><div class="inner"><div class="region"><div class="contents"><p class="p">Never run software from media you don't trust.</p></div></div></div></div>
</dd>
</dl></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a></li>
<li class="links "><a href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a></li>
<li class="links "><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a></li>
<li class="links "><a href="media.html#videos" title="Video i video kamere">Video</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
