<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Sakrij datoteku.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Sakrij datoteku.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">GNOME upravitelj datoteka pruža vam mogućnost da sakrijete i otkrijete datoteke po vašoj odluci. Kada je datoteka sakrivena, tada se ne prikazuje u upravitelju datoteka, ali je još uvijek u svom folderu.</p>
<p class="p">Da sakrijete datoteku, <span class="link"><a href="files-rename.html" title="Preimenujte datoteku ili folder">preimenujte te je </a></span> sa <span class="key"><kbd>.</kbd></span> na početku njenog imena. Na primjer, da sakrijete datoteku <span class="file"> primjer.txt</span>, trebate je preimenovati sa <span class="file">.primjer.txt</span>.</p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Možete sakriti folder na isti način kao i datoteke. Sakrijte folder stavljanjem <span class="key"><kbd>.</kbd></span> na početak imena foldera.</p></div></div></div></div>
</div>
<div id="show-hidden" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Prikaži sve skrivene datoteke.</span></h2></div>
<div class="region"><div class="contents">
<p class="p">If you want to see all hidden files in a folder, go to that folder and
  either click the <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span>
  button in the toolbar and pick <span class="gui">Show Hidden Files</span>, or press
  <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>H</kbd></span></span>. You will see all hidden files,
  along with regular files that are not hidden.</p>
<p class="p">To hide these files again, either click the
  <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span> button in the
  toolbar and pick <span class="gui">Show Hidden Files</span>, or press
  <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>H</kbd></span></span> again.</p>
</div></div>
</div></div>
<div id="unhide" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Otkrij datoteku</span></h2></div>
<div class="region"><div class="contents">
<p class="p">To unhide a file, go to the folder containing the hidden file and click
  the <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span> button in the
  toolbar and pick <span class="gui">Show Hidden Files</span>. Then, find the hidden file and
  rename it so that it doesn't have a <span class="key"><kbd>.</kbd></span> in front of its name. For
  example, to unhide a file called <span class="file">.example.txt</span>, you should rename
  it to <span class="file">example.txt</span>.</p>
<p class="p">Once you have renamed the file, you can either click the
  <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="down"></span></span> button
  in the toolbar and pick <span class="gui">Show Hidden Files</span>, or press
  <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>H</kbd></span></span> to hide any other hidden files
  again.</p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Prema zadanim postavkama, vidjet ćete samo sakrivene datoteke u upravitelju datoteka dok ne zatvorite upravitelj datoteka. Da promijenite ovu postavku da se u upravitelju datoteka uvijek prikazuju sakrivene datoteke, pogledajte <span class="link"><a href="nautilus-views.html" title="Views preferences in Files">Views preferences in <span class="app">Files</span></a></span>.</p></div></div></div></div>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Većina sakrivenih datoteka će imati <span class="key"><kbd>.</kbd></span> na početku imena, ali ostale umjesto toga mogu imati <span class="key"><kbd>~</kbd></span> na kraju imena. Ove datoteke su backup datoteke. Pogledajte <span class="link"><a href="files-tilde.html" title='Što je datoteka sa "~" na kraju svog imena?'>Što je datoteka sa "~" na kraju svog imena?</a></span> za više informacija.</p></div></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files-tilde.html" title='Što je datoteka sa "~" na kraju svog imena?'>Što je datoteka sa "~" na kraju svog imena?</a><span class="desc"> — To su sigurnosne kopije datoteka. One su skrivene po postavci.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
