<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Súbory, priečinky a vyhľadávanie</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Súbory, priečinky a vyhľadávanie</span></h1></div>
<div class="region">
<div class="contents">
<div class="media media-image floatend if-if if__not-target-mobile"><div class="inner"><img src="figures/nautilus.png" class="media media-block" alt="Nautilus - správca súborov"></div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h2><span class="title">Bežné úlohy</span></h2></div>
<div class="region"><ul>
<li class="links "><a class="bold" href="files-browse.html" title="Navigácia medzi priečinkami">Navigácia medzi priečinkami</a></li>
<li class="links "><a class="bold" href="files-copy.html" title="Kopírovanie alebo presúvanie súborov a priečinkov">Kopírovanie alebo presúvanie súborov a priečinkov</a></li>
<li class="links "><a class="bold" href="files-delete.html" title="Odstránenie súborov a prečinkov">Odstránenie súborov a prečinkov</a></li>
<li class="links "><a class="bold" href="files-rename.html" title="Premenovanie súborov a priečinkov">Premenovanie súborov a priečinkov</a></li>
<li class="links "><a class="bold" href="files-preview.html" title="Preview files and folders">Preview files and folders</a></li>
<li class="links "><a class="bold" href="files-sort.html" title="Triedenie súborov a priečinkov">Triedenie súborov a priečinkov</a></li>
<li class="links "><a class="bold" href="files-search.html" title="Vyhľadávanie súborov">Vyhľadávanie súborov</a></li>
</ul></div>
</div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h2><span class="title">Ďalšie témy</span></h2></div>
<div class="region"><ul>
<li class="links "><a class="bold" href="files-lost.html" title="Hľadanie strateného súboru">Hľadanie strateného súboru</a></li>
<li class="links "><a class="bold" href="nautilus-connect.html" title="Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku">Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku</a></li>
<li class="links "><a class="bold" href="files-open.html" title="Otvorenie aplikácie inou aplikáciou">Otvorenie aplikácie inou aplikáciou</a></li>
<li class="links "><a class="bold" href="files-recover.html" title="Recover a file from the Trash">Recover a file from the Trash</a></li>
<li class="links "><a class="bold" href="files-share.html" title="Spoločné používanie a prenos súborov">Spoločné používanie a prenos súborov</a></li>
<li class="links "><a class="bold" href="nautilus-file-properties-basic.html" title="Vlastnosti súboru">Vlastnosti súboru</a></li>
<li class="links "><a class="bold" href="files-disc-write.html" title="Zápis súborov na CD a DVD">Zápis súborov na CD a DVD</a></li>
<li class="links "><a class="bold" href="nautilus-prefs.html" title="Nastavenia správcu súborov">Nastavenia správcu súborov</a></li>
</ul></div>
</div></div>
</div>
<div id="removable" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Odpojiteľné jednotky a externé disky</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-removedrive.html" title="Bezpečné odobratie externého disku"><span class="title">Bezpečné odobratie externého disku</span><span class="linkdiv-dash"> — </span><span class="desc">Vysunutie alebo odpojenie USB kľúča, CD, DVD alebo iného zariadenia.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="files-autorun.html" title="Open applications for devices or discs"><span class="title">Open applications for devices or discs</span><span class="linkdiv-dash"> — </span><span class="desc">Automatické spustenie aplikácie pre CD a DVD disky, fotoaparáty, prehrávače zvuku a ďalšie zariadenia a nosiče.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="backup" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Zálohovanie</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="backup-frequency.html" title="Frekvencia zálohovania"><span class="title">Frekvencia zálohovania</span><span class="linkdiv-dash"> — </span><span class="desc">Learn how often you should backup your important files to make sure
    that they're safe.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-thinkabout.html" title="Miesta, ktoré je vhodné odzálohovať"><span class="title">Miesta, ktoré je vhodné odzálohovať</span><span class="linkdiv-dash"> — </span><span class="desc">Zoznam priečinkov, v ktorých sa nachádzajú dokumenty, súbory a nastavenia, ktoré je vhodné zálohovať.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-restore.html" title="Obnovenie zálohy"><span class="title">Obnovenie zálohy</span><span class="linkdiv-dash"> — </span><span class="desc">Získanie súborov zo zálohy.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="backup-check.html" title="Skontrolujte si vašu zálohu"><span class="title">Skontrolujte si vašu zálohu</span><span class="linkdiv-dash"> — </span><span class="desc">Skontrolovanie, či zálohovanie prebehlo úspešne.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="backup-why.html" title="Zálohovanie dôležitých súborov"><span class="title">Zálohovanie dôležitých súborov</span><span class="linkdiv-dash"> — </span><span class="desc">Why, what, where and how of backups.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="documents" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Documents</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="documents.html" title="Documents"><span class="title">Documents</span><span class="linkdiv-dash"> — </span><span class="desc">
      Organize the documents stored locally on your computer or created 
      online.
    </span></a></div></div>
<div class="links-twocolumn"></div>
</div></div></div></div></div>
</div></div>
<div id="faq" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Tipy a otázky</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="nautilus-file-properties-permissions.html" title="Nastavenie oprávnení k súborom"><span class="title">Nastavenie oprávnení k súborom</span><span class="linkdiv-dash"> — </span><span class="desc">Nastavenie práv určujúcich kto môže zobraziť a upravovať súbory a priečinky.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-hidden.html" title="Skrytie súboru"><span class="title">Skrytie súboru</span><span class="linkdiv-dash"> — </span><span class="desc">Nastavenie, aby súbor nebol viditeľný v správcovi súborov.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-select.html" title="Vybratie súborov podľa vzoru"><span class="title">Vybratie súborov podľa vzoru</span><span class="linkdiv-dash"> — </span><span class="desc">Vybratie viacerých súborov s podobným názvom pomocou kombinácie kláves <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>S</kbd></span></span>.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="nautilus-bookmarks-edit.html" title="Úprava záložiek na priečinky"><span class="title">Úprava záložiek na priečinky</span><span class="linkdiv-dash"> — </span><span class="desc">Pridávanie, odstraňovanie a premenovanie záložiek v správcovi súborov</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-tilde.html" title='Čo znamená súbor so znakom "~" na konci názvu?'><span class="title">Čo znamená súbor so znakom "~" na konci názvu?</span><span class="linkdiv-dash"> — </span><span class="desc">Záložné súbory, ktoré sú štandardne skryté.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="files-templates.html" title="Šablóny pre často používané typy dokumentov"><span class="title">Šablóny pre často používané typy dokumentov</span><span class="linkdiv-dash"> — </span><span class="desc">Rýchle vytvorenie nových dokumentov z prispôsobených šablón.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Príručka pre Ubuntu desktop">Príručka pre Ubuntu desktop</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
