<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Problémy s čítačkou kariet</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="media.html" title="Zvuk, video a obrázky">Zvuk, video a obrázky</a> › <a class="trail" href="media.html#photos" title="Fotografie a digitálne fotoaparáty">Fotografie</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Problémy s čítačkou kariet</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Mnoho počítačov obsahuje čítačku pre karty SD (Secure Digital), MMC (MultiMediaCard), SmartMedia, Memory Stick, CompactFlash a ďalšie karty. Tieto karty by mali byť automaticky rozpoznané a pripojené. Tu je niekoľko krokov, pre riešenie problémov, ak sa tak nestane:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p"> Make sure that the card is put in correctly. Many cards look as though they are
upside down when correctly inserted. Also make sure that the card is firmly seated
in the slot; some cards, especially CompactFlash, require a small amount of force to insert
correctly. (Be careful not to push too hard! If you come up against something solid,
do not force it.)</p></li>
<li class="steps"><p class="p"> Open <span class="app">Files</span> by using the <span class="gui">Dash</span>. Does the inserted
 card appear in the <span class="gui">Devices</span> list in the left sidebar? Sometimes the card appears in this list but is not mounted; click it once to mount. (If the sidebar is not visible, press <span class="key"><kbd>F9</kbd></span> or click
 <span class="guiseq"><span class="gui">View</span> ▸ <span class="gui"> Sidebar</span> ▸ <span class="gui"> Show Sidebar</span></span>.)
</p></li>
<li class="steps"><p class="p">Ak sa karta nezobrazuje na bočnej lište, z ponuky zvolíme <span class="guiseq"><span class="gui">Prejsť na</span> ▸ <span class="gui">Počítač</span></span>. Ak čítačka kariet nie je správne nastavená, čítačka bez vloženej karty sa zobrazuje ako mechanika, a po vložení karty sa zobrazuje ako karta samotná (viď obrázok nižšie).</p></li>
<li class="steps"><p class="p">Ak vidíme čítačku kariet, no nevidíme samotnú kartu, problém môže byť v karte. Skúsime do čítačky vložiť inú kartu, alebo skúsime danú kartu vložiť do inej čítačky.</p></li>
</ol></div></div></div>
<p class="p">Ak sa v priečinku <span class="gui">Počítač</span>, je možné, že čítačka kariet nefunguje v systémoch s jadrom Linux kvôli problémom s ovládačom. Ak je čítačka kariet interná (vo vnútri počítača) je to viac pravdepodobné. Najlepšie riešenie je pripojiť priamo zariadenie (fotoaparát, telefón, atď.) do USB konektora na počítači. Dostupné sú tiež externé USB čítačky kariet, ktoré sú lepšie podporované v systémoch s jadrom Linux.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="media.html#photos" title="Fotografie a digitálne fotoaparáty">Fotografie</a></li>
<li class="links "><a href="hardware.html#problems" title="Časté problémy">Hardvérové problémy</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
