<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Čo je to ovládač?</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Čo je to ovládač?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Zariadenia sú fyzickými súčasťami počítača. Môžu byť externé ako napríklad tlačiarne a monitor, alebo interné ako napríklad grafické a zvukové karty.</p>
<p class="p">Aby počítač mohol tieto zariadenia používať, potrebuje vedieť, akým spôsobom má s nimi komunikovať. Túto komunikáciu zabezpečuje malý program, ktorý nazývame ovládač.</p>
<p class="p">Keď pripojíme zariadenie k počítaču, musíme mať nainštalovaný správny ovládač, aby zariadenie pracovalo. Napríklad ak pripojíme tlačiareň ale nie je k nej dostupný správny ovládač, nebudeme ju môcť používať. Rôzne modely zariadení majú zvyčajne odlišné ovládače, takže pri zmene zariadenia za iné, musíme zmeniť aj ovládač.</p>
<p class="p">V systémoch s jadrom Linux, sú ovládače väčšiny zariadení už nainštalované priamo v jadre systému, takže zariadenie by malo fungovať ihneď po pripojení. Ovládače pre niektoré zariadenia však bude možno potrebné nainštalovať ručne a niektoré zariadenia ovládač nemusí byť dostupný.</p>
<p class="p">Okrem toho niektoré ovládače nemusia byť dokončené a nemusia pracovať správne. V takom prípade niektoré funkcie zariadenia nemusia fungovať. Napríklad tlačiareň nebude tlačiť obojstranne.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware.html" title="Hardvér a ovládače">Hardvér a ovládače</a><span class="desc"> — 
      <span class="link"><a href="hardware.html#problems" title="Časté problémy">Hardware problems</a></span>,
      <span class="link"><a href="printing.html" title="Tlačiť">printers</a></span>,
      <span class="link"><a href="power.html" title="Power &amp; battery">power settings</a></span>,
      <span class="link"><a href="color.html" title="Správa farieb">color management</a></span>,
      <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>,
      <span class="link"><a href="disk.html" title="Disky a úložiská">disks</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="bluetooth-problem-connecting.html" title="I can't connect my Bluetooth device">I can't connect my Bluetooth device</a><span class="desc"> — Adaptér môže byť vypnutý, nemusí mať ovládače alebo môže byť bluetooth zakázané alebo blokované.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
