<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Hardware i upravljački programi</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Hardware i upravljački programi</span></h1></div>
<div class="region">
<div class="contents">
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">Spojiti</a></span>, <span class="link"><a href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju"> slanje datoteka</a></span>, <span class="link"><a href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite"> uključivanje i isključivanje</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="disk.html" title="Diskovi i skladište">Diskovi i skladište</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="disk-capacity.html" title="Provjerite koliko je slobodnog prostora u diksu ostalo">Kapacitet Diska</a></span>, <span class="link"><a href="disk-benchmark.html" title="Testirajte performanse vašeg tvrdog diska">performance</a></span>, <span class="link"><a href="disk-check.html" title="Provjerite vaš tvrdi disk na probleme">problemi</a></span>, <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama">količine i particije</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="mouse.html" title="Miš">Miš</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="mouse-lefthanded.html" title="Miš za ljevoruke">Ljevak</a></span>, <span class="link"><a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">brzina i osjetljivost</a></span>, <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">dodirna površina, klik i listanje</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">screen dimming</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="keyboard.html" title="Tastatura">Tastatura</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">Input sources</a></span>,
      <span class="link"><a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">cursor blinking</a></span>,
      <span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>super key</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">keyboard accessibility</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="color.html" title="Upravljanje bojama">Upravljanje bojama</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="color-whyimportant.html" title="Zašto je upravljanje bojama važno?">Why is this important</a></span>,
      <span class="link"><a href="color.html#profiles" title="Profili boja">Color profiles</a></span>,
      <span class="link"><a href="color.html#calibration" title="Kalibracija">How to calibrate a device</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="printing.html" title="Štampanje">Štampanje</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="printing-setup.html" title="Postavite lokalni štampač">Lokalne postavke</a></span>, <span class="link"><a href="printing-order.html" title="Promijenite redoslijed štampanja stranica">redoslijed i slaganje</a></span>, <span class="link"><a href="printing-2sided.html" title="Štampajte dvostrano ili kao multi-stranice"> dvostrano i visestrano</a></span>…</span></div>
</div>
</div></div></div>
<div class="links topiclinks"><div class="inner">
<div class="title title-links"><h2><span class="title">Više tema.</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware-driver-proprietary.html" title="Šta su vlasnički upravljački programi?">Šta su vlasnički upravljački programi?</a><span class="desc"> — Stvarni upravljački programi nisu slobodno dostupni ili otvorenog izvornog koda.</span>
</li>
<li class="links ">
<a href="hardware-driver.html" title="Što je to upravljački program?">Što je to upravljački program?</a><span class="desc"> — Hardware / upravljački uređaj omogućuje vašem računaru da koristi uređaje koji su priključeni na njega.</span>
</li>
</ul></div>
</div></div>
</div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Uobičajeni problemi</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><ul>
<li class="links ">
<a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a><span class="desc"> — Identifikujte i riješite probleme sa bežičnim povezivanjima</span>
</li>
<li class="links "><a href="bluetooth.html#problems" title="Problemi">Bluetooth problemi.</a></li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li>
<li class="links ">
<a href="power.html#problems" title="Problemi">Problemi sa snagom</a><span class="desc"> — Otklanjanje problema sa snagom i baterijama.</span>
</li>
<li class="links ">
<a href="sound-broken.html" title="Problemi sa zvukom">Problemi sa zvukom</a><span class="desc"> — Uklonite probleme poput onih da nemate zvuka ili je kvalitet zvula loš.</span>
</li>
<li class="links ">
<a href="hardware-cardreader.html" title="Problemi sa čitačem kartica.">Problemi sa čitačem kartica.</a><span class="desc"> — Rješavanje problema s čitatčima medijskih kartica.</span>
</li>
<li class="links ">
<a href="printing.html#problems" title="Problemi sa štampačem">Problemi sa štampačem</a><span class="desc"> — Nepoznat stampac, zaglavljen papir, ispis izgleda krivo.</span>
</li>
</ul></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
