<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Problémy s obrazom</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Problémy s obrazom</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Väčšina problémov s obrazom je spôsobená problémami s grafickými ovládačmi alebo ich konfiguráciou. Ktorá z tém najlepšie vystihuje problém, ktorý máte?</p>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="look-resolution.html" title="Change the size or rotation of the screen"><span class="title">Change the size or rotation of the screen</span><span class="linkdiv-dash"> — </span><span class="desc">Zmena rozlíšenia obrazovky a jej orientácie (otočenia).</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="display-dimscreen.html" title="Nastavenie jasu obrazovky"><span class="title">Nastavenie jasu obrazovky</span><span class="linkdiv-dash"> — </span><span class="desc">Stmavenie obrazovky kvôli šetreniu energie a zvýšenie jasu kvôli lepšej čitateľnosti v jasnom svetle.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-whydim.html" title="Prečo mi obrazovka stmavne po nejakej dobe?"><span class="title">Prečo mi obrazovka stmavne po nejakej dobe?</span><span class="linkdiv-dash"> — </span><span class="desc">Keď je váš notebook napájaný z batérie alebo akonáhle je počítač nečinný tak sa displej stlmí z dôvodu úspory energie.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="look-display-fuzzy.html" title="Prečo sú veci na obrazovke neostré alebo štvorčekované?"><span class="title">Prečo sú veci na obrazovke neostré alebo štvorčekované?</span><span class="linkdiv-dash"> — </span><span class="desc">Rozlíšenie obrazovky nie je správne nastavené.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="session-screenlocks.html" title="The screen locks itself too quickly"><span class="title">The screen locks itself too quickly</span><span class="linkdiv-dash"> — </span><span class="desc">Change how long to wait before locking the screen in the
    <span class="gui">Brightness &amp; Lock</span> settings.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-suspendfail.html" title="Why won't my computer turn back on after I suspended it?"><span class="title">Why won't my computer turn back on after I suspended it?</span><span class="linkdiv-dash"> — </span><span class="desc">Some computer hardware causes problems with suspend or hibernate.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-willnotturnon.html" title="Počítač sa nezapne"><span class="title">Počítač sa nezapne</span><span class="linkdiv-dash"> — </span><span class="desc">Možné príčiny sú voľné káble alebo hardvérové ​​problémy.</span></a></div>
</div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="hardware.html#problems" title="Časté problémy">Hardvérové problémy</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
