<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Príručka pre Ubuntu desktop</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" class="media media-inline" alt="Logo Ubuntu"></span></span> Príručka pre Ubuntu desktop</span></h1></div>
<div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="mouseovers"><img src="figures/unity.png"></div>
<ul class="mouseovers">
<li class="links"><a class="bold" href="unity-introduction.html" title="Welcome to Ubuntu"><img src="figures/ubuntu-mascot-creature.jpg">Welcome to Ubuntu</a></li>
<li class="links"><a class="bold" href="whats-new.html" title="What's new in Ubuntu 14.04?">What's new in Ubuntu 14.04?</a></li>
<li class="links"><a class="bold" href="unity-launcher-intro.html" title="Použite spúšťač pre spustenie aplikácií"><img src="figures/unity-launcher-intro.png">Použite spúšťač pre spustenie aplikácií</a></li>
<li class="links"><a class="bold" href="unity-dash-intro.html" title="Find apps, files, music, and more with the Dash"><img src="figures/unity-dash-intro.png">Find apps, files, music, and more with the Dash</a></li>
<li class="links"><a class="bold" href="unity-menubar-intro.html" title="Manage apps &amp; settings with the menu bar"><img src="figures/unity-appmenu-intro.png">Manage apps &amp; settings with the menu bar</a></li>
<li class="links"><a class="bold" href="shell-exit.html" title="Odhlásenie, vypnutie, prepnutie používateľa"><img src="figures/unity-exit.png">Odhlásenie, vypnutie, prepnutie používateľa</a></li>
</ul>
<div class="clear"></div>
</div></div></div>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="shell-overview.html" title="Desktop, apps &amp; windows">Desktop, apps &amp; windows</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="unity-introduction.html" title="Welcome to Ubuntu">Introduction</a></span>,
      <span class="link"><a href="shell-keyboard-shortcuts.html" title="Useful keyboard shortcuts">keyboard shortcuts</a></span>,
      <span class="link"><a href="shell-windows.html" title="Okná a pracovné plochy">windows</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net.html" title="Networking, web, email &amp; chat">Networking, web, email &amp; chat</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="net-wireless.html" title="Bezdrôtové pripojenie k sieti">Wireless</a></span>,
      <span class="link"><a href="net-wired.html" title="Drôtové siete">wired</a></span>,
      <span class="link"><a href="net-problem.html" title="Problémy so sieťou">connection problems</a></span>,
      <span class="link"><a href="net-browser.html" title="Prehliadače">web browsing</a></span>,
      <span class="link"><a href="net-email.html" title="Email &amp; email software">email accounts</a></span>,
      <span class="link"><a href="net-chat.html" title="Chat &amp; Social Networking">instant messaging</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="media.html" title="Zvuk, video a obrázky">Zvuk, video a obrázky</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="media.html#photos" title="Fotografie a digitálne fotoaparáty">Digital cameras</a></span>,
      <span class="link"><a href="media.html#music" title="Hudba a prenosné prehrávače">iPods</a></span>,
      <span class="link"><a href="media.html#videos" title="Videá a videokamery">playing videos</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="files-search.html" title="Vyhľadávanie súborov">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="addremove.html" title="Pridávanie a odstraňovanie softvéru">Pridávanie a odstraňovanie softvéru</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="addremove-install.html" title="Inštalácia ďalšieho softvéru">Install</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Odstránenie aplikácie">remove</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Pridanie ďalších zdrojov softvéru">extra repositories</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs.html" title="Užívateľské a systémové nastavenia">Užívateľské a systémové nastavenia</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="keyboard.html" title="Klávesnica">Keyboard</a></span>,
      <span class="link"><a href="mouse.html" title="Myš">mouse</a></span>,
      <span class="link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">display</a></span>,
      <span class="link"><a href="prefs-language.html" title="Region &amp; Language">languages</a></span>,
      <span class="link"><a href="user-accounts.html" title="Užívateľský účet">user accounts</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="hardware.html" title="Hardvér a ovládače">Hardvér a ovládače</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="hardware.html#problems" title="Časté problémy">Hardware problems</a></span>,
      <span class="link"><a href="printing.html" title="Tlačiť">printers</a></span>,
      <span class="link"><a href="power.html" title="Power &amp; battery">power settings</a></span>,
      <span class="link"><a href="color.html" title="Správa farieb">color management</a></span>,
      <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>,
      <span class="link"><a href="disk.html" title="Disky a úložiská">disks</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="a11y.html" title="Bezbariérový prístup">Bezbariérový prístup</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="a11y.html#vision" title="Zrakové postihnutie">Seeing</a></span>,
      <span class="link"><a href="a11y.html#sound" title="Sluchové postihnutie">hearing</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Pohybové postihnutie">mobility</a></span>,
      <span class="link"><a href="a11y-braille.html" title="Prepis obrazovky do Braiilovho písma">braille</a></span>…
      
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="tips.html" title="Tips &amp; tricks">Tips &amp; tricks</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="tips-specialchars.html" title="Zadanie špeciálnych znakov">Special characters</a></span>, <span class="link"><a href="mouse-middleclick.html" title="Stredné tlačidlo myši">middle click shortcuts</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="more-help.html" title="Získať ďalšiu pomoc">Získať ďalšiu pomoc</a></div>
<div class="desc"><span class="desc">
        <span class="link"><a href="about-this-guide.html" title="O tejto príručke">Tips on using this guide</a></span>, 
        <span class="link"><a href="get-involved.html" title="Participate to improve this guide">help improve this guide</a></span>…</span></div>
</div>
</div></div></div>
</div></div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
