<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Upravljanje tastaturom</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="a11y.html" title="Opšti pristup">Opšti pristup</a> › <a class="trail" href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Upravljanje tastaturom</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ova tipkovnica stranica Detalji orijentacija za ljude koji se ne mogu koristiti miša ili neki drugi pokazivački uređaj ili koji žele koristiti tipkovnicu koliko je god moguće. Za tipkovne prečace koji su korisni za sve korisnike, pogledajte <span class="link"><a href="shell-keyboard-shortcuts.html" title="Korisne skraćenice na tastaturi">Korisne skraćenice na tastaturi</a></span> umjesto.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Ukoliko ne možete koristiti pokazivački uređaj kao što je miš, možete kontrolisati pokazivač miša koristeći tipke sa brojevima na tastaturi. Pogledajte <span class="link"><a href="mouse-mousekeys.html" title="Click and move mouse pointer using the keypad">Click and move mouse pointer using the keypad</a></span> za detalje.</p></div></div></div></div>
<div class="table"><div class="inner">
<div class="title title-table"><h2><span class="title">Kretanje korisničkim sučeljem</span></h2></div>
<div class="region"><table class="table" style="border-top-style: solid;border-bottom-style: solid;">
<tr>
<td><p class="p"><span class="key"><kbd>Tab</kbd></span> i<span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span></p></td>
<td>
<p class="p">Move keyboard focus between different controls. <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> moves between groups of controls, such as from a sidebar
      to the main content. <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> can also
      break out of a control that uses <span class="key"><kbd>Tab</kbd></span> itself, such as a text area.</p>
<p class="p">Držite <span class="key"><kbd> Shift </kbd></span> za pomicanje fokusa u obrnutom redoslijedu.</p>
</td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p">Tasteri strelica</p></td>
<td style="border-top-style: solid;">
<p class="p">Premještanje odabira između stavki u jednoj kontroli, ili među skupa povezanih kontrola. Koristite tipke sa strelicama da se usredotočite gumbiće u alatnoj traci, odaberite stavke na popisu ili ikona pogled, ili odaberite gumb iz skupine.</p>
<p class="p">U prikazu strukture, koristite tipke lijeva i desna strelica da biste skupili i proširili stavke sa podstavkama.</p>
</td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+strelice</span></p></td>
<td style="border-top-style: solid;"><p class="p">U pregledu listom ili ikonama, pomjerite fokus tastature na drugu stavku, bez mijenjanja koja je stavka označena.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Shift</kbd></span>+strelice</span></p></td>
<td style="border-top-style: solid;"><p class="p">U pregledu listom ili ikonama, odaberite sve stavke od trenutno označene stavke do nove fokusirane stavke.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="key"><kbd>Razmak</kbd></span></p></td>
<td style="border-top-style: solid;"><p class="p">Aktivirajte usmjerene stavke kao što je tipka, potvrdni okvir, ili stavka popisa.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Razmak</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">U popisu ili prikazu ikona, odaberite ili poništite usmjerene stavke bez uklanjanja oznaka drugih stavki.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="key"><kbd>Alt</kbd></span></p></td>
<td style="border-top-style: solid;"><p class="p">Držite <span class="key"><kbd>Alt</kbd></span> tipku da otkrijete <span class="em">akceleratore</span>: podvučena slova na stavkama izbornika, tipkama, i drugim kontrolama. Pritisnite <span class="key"><kbd>Alt</kbd></span> te podvučena slova da aktivirate kontrolu, baš kao da ste kliknuli na to.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="key"><kbd>Esc</kbd></span></p></td>
<td style="border-top-style: solid;"><p class="p">Izlaz iz izbornika, popup-a, switcher-a, ili dijaloškog prozora.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="key"><kbd>F10</kbd></span></p></td>
<td style="border-top-style: solid;"><p class="p">Open the first menu on the menu bar of a window. Use the arrow keys
    to navigate the menus.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Shift</kbd></span>+<span class="key"><kbd>F10</kbd></span></span> ili Meni taster</p></td>
<td style="border-top-style: solid;"><p class="p">Pop-up kontekstni izbornik za trenutni odabir, kao da ste imali pravo-klik.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>F10</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">U upravitelju datoteka, pop-up kontekstni izbornik za trenutne mape, kao da je bio desni klik na pozadinu, a ne na bilo koju stavku.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>PageUp</kbd></span></span> i <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>PageDown</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">U sučelju sa tabovima, prebacujte tabove sa lijeva na desno.</p></td>
</tr>
</table></div>
</div></div>
<div class="table"><div class="inner">
<div class="title title-table"><h2><span class="title">Kretanje kroz desktop</span></h2></div>
<div class="region"><table class="table" style="border-top-style: solid;border-bottom-style: solid;">
<tr>
<td><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span></p></td>
<td><p class="p"><span class="link"><a href="shell-windows-switching.html" title="Zamjena između prozora">Brzo prebacivanje između prozora.</a></span> Držite <span class="key"><kbd>Shift</kbd></span> za obrnuti poredak.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>`</kbd></span></span></p></td>
<td style="border-top-style: solid;">
<p class="p">Promjena izmedju prozora iste aplikacije ili promijena aplikacije <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span>.</p>
<p class="p">Ova kratica koristi  <span class="key"><kbd>`</kbd></span> na USA tastaturi gdje <span class="key"><kbd>`</kbd></span> je iznad <span class="key"><kbd>Tab</kbd></span>. na ostalim tastaturama kratica je <span class="key"><kbd>Alt</kbd></span> plus zioka iznad  <span class="key"><kbd>Tab</kbd></span>.</p>
</td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tipke sa strelicama</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p"><span class="link"><a href="shell-workspaces-switch.html" title="Sljedeća radna površina">Prebacujte se između radnih prostora.</a></span></p></td>
</tr>
</table></div>
</div></div>
<div class="table"><div class="inner">
<div class="title title-table"><h2><span class="title">Upravljajte prozorima</span></h2></div>
<div class="region"><table class="table" style="border-top-style: solid;border-bottom-style: solid;">
<tr>
<td><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F4</kbd></span></span></p></td>
<td><p class="p">Zatvori trenutni prozor</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><a href="windows-key.html" title='Šta je "Super" tipka?'><kbd>Super</kbd></a></span>+<span class="key"><kbd>↓</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Vrati maksimizirani prozor na početnu veličinu.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F7</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Pomjerajte trenutni prozor. Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F7</kbd></span></span>, zatim koristite tipke sa strelicama da pomjerate prozor. Pritisnite <span class="key"><kbd>Enter</kbd></span> da završite pomjeranje prozora, ili <span class="key"><kbd>Esc</kbd></span> da ga vratite na njegovo početno mjesto.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F8</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Promijenite veličinu prozora. Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F8</kbd></span></span>, a zatim korisite tipke sa strelicama za promijenu veličine prozora. Pritisnite<span class="key"><kbd>Enter</kbd></span> da završite sa mijenjanjem veličine prozora, ili <span class="key"><kbd>Esc</kbd></span> za povratak na orginalnu veličinu.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Shift</kbd></span>+<span class="key"><kbd>Tipke sa strelicama</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p"><span class="link"><a href="shell-workspaces-movewindow.html" title="Pomjerite prozor na drugu radnu površinu">Pomjerite trenutni prozor na drugu radnu površinu.</a></span></p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><a href="windows-key.html" title='Šta je "Super" tipka?'><kbd>Super</kbd></a></span>+<span class="key"><kbd>↑</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p"><span class="link"><a href="shell-windows-maximize.html" title="Maksimizirajte i smanjite prozor.">Maksimiziraj</a></span> prozor.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><a href="windows-key.html" title='Šta je "Super" tipka?'><kbd>Super</kbd></a></span>+<span class="key"><kbd>←</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Povećajte prozor okomito duž lijeve strane ekrana.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><a href="windows-key.html" title='Šta je "Super" tipka?'><kbd>Super</kbd></a></span>+<span class="key"><kbd>→</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Povećajte prozor okomito duž desne strane ekrana.</p></td>
</tr>
<tr>
<td style="border-top-style: solid;"><p class="p"><span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Razmak</kbd></span></span></p></td>
<td style="border-top-style: solid;"><p class="p">Pop-up izbornik prozora, kao da je desni klik na naslovnicu.</p></td>
</tr>
</table></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a></li>
<li class="links ">
<a href="keyboard.html" title="Tastatura">Tastatura</a><span class="desc"> — 
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">Input sources</a></span>,
      <span class="link"><a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">cursor blinking</a></span>,
      <span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>super key</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">keyboard accessibility</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="shell-keyboard-shortcuts.html" title="Korisne skraćenice na tastaturi">Korisne skraćenice na tastaturi</a><span class="desc"> — Upoznavanje desktopa koristeći tastaturu.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
