<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">To se može dogoditi jer rezolucija koju ste postavili nije odgovarajuća za vaš zaslon.</p>
<p class="p">To solve this, click the icon at the very right of the menu bar and go to <span class="gui">System Settings</span>. In the Hardware section, choose <span class="gui">Displays</span>. Try some of the <span class="gui">Resolution</span> options and set the one that makes the screen look better.</p>
</div>
<div id="multihead" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kada je više ekrana povezano</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako imate dva displeja spojena na racunar (npr monitor i projektor), displeji mozda imaju razlocitu rezoluciju. Graficka kartica moze samo jednu rezoluciju prikazivati tako da jedan od vasih displeja moze izgledati cudno.</p>
<p class="p">Mozete podesiti tako da dva displeja imaju razlicite rezolucije, ali necete moci biti u prilici da prikazujete isti sliku na oba displeja simultano. Imat cete dva neovisna ekrana spojena u isto vrijeme. Moci cete pomijerati prozore sa jednog ekrana na drugi ali necete moci prikazati isti prozor na oba ekrana odjednom.</p>
<p class="p">Da postavite ekrane tako da svaki ima vlastitu rezoluciju:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu sasvi desno na traci menija i odaberite  <span class="gui">Sistemska podešavanja</span>. Otvorite <span class="gui">Ekrani</span>.</p></li>
<li class="steps"><p class="p">Odznači <span class="gui">Ekrani u ogledalu</span>.</p></li>
<li class="steps"><p class="p">Odaberite svaki zaslon u prijelazu iz sive kutije na vrhu <span class="gui">Zasloni</span> prozora. Mijenjajte <span class="gui">Rezolucija</span> sve dok zaslon ne izgleda ispravno.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="look-resolution.html" title="Promijenite veličinu rotacije ekrana">Promijenite veličinu rotacije ekrana</a><span class="desc"> — Promijenite rezoluciju ekrana i njegovu orijentaciju (rotaciju).</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
