<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Promijenite veličinu rotacije ekrana</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Promijenite veličinu rotacije ekrana</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete promijeniti koliko velike (ili koliko detaljne) stvari će se pojavljivati na ekranu mijenjanjem <span class="em">rezolucije ekrana</span>. Možete promijeniti na koji način će se stvari pojavljivati (na primjer, ukoliko imate rotirajući zaslon) mijenjanjem <span class="em">rotacije</span>.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu koja je desno od trake izbornika i odaberite <span class="gui">Postavke Sistema</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Zasloni</span>.</p></li>
<li class="steps"><p class="p">If you have multiple displays and they are not mirrored, you can have
  different settings on each display. Select a display in the preview area.</p></li>
<li class="steps"><p class="p">Odaberite željenu rezoluciju i rotaciju.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui"> Primjeni</span>. Nove postavke će biti primjenjene 30 sekundi prije nego što se vrate stare. Na taj način, ukoliko ne možete ništa vidjeti sa novim postavkama, stare postavke će se automatski vratiti. Ukoliko ste zadovoljni sa novim postavkama, kliknite <span class="gui"> Zadrži Ovu Konfiguraciju </span>.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Kada koristite drugi ekran, kao što je projektor, trebao bi biti otkriven automatski pa možete promijeniti postavke na isti način kao u na običnom ekranu. Ukoliko se ovo ne desi, samo kliknite <span class="gui">Otkriti Zaslone</span>.</p></div></div></div></div>
</div>
<div id="resolution" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Rezolucija</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Rezolucija je broj piksela(tacaka na ekranu) u svakom smijeru u kojem moze biti prikazano. Svaka rezolucija ima <span class="em">aspect ratio</span>, odnos sirine i visine.Siroki ekrani koriste 16:9 dok tradicionalni ekrani koriste 4:3. Ako izaberete rezoluciju koja ne odgovara odnosu sirine i visine vaseg monitora , ekran ce biti smanjen da bi se izbjeglo razvlacenje slike</p>
<p class="p">You can choose the resolution you prefer from the <span class="gui">Resolution</span> drop-down
list. If you choose one that is not right for your screen it may
<span class="link"><a href="look-display-fuzzy.html" title="Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?">look fuzzy or pixelated</a></span>.</p>
</div></div>
</div></div>
<div id="rotation" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Rotacija</span></h2></div>
<div class="region"><div class="contents"><p class="p">On some laptops, you can physically rotate the screen in many directions.
It is useful to be able to change the display rotation. You can choose the rotation
you want for your display from the <span class="gui">Rotation</span> drop-down list.</p></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a><span class="desc"> — <span class="link"><a href="look-background.html" title="Promijenite pozadinu">Pozadina</a></span>, <span class="link"><a href="look-resolution.html" title="Promijenite veličinu rotacije ekrana">veličina i rotacija</a></span>, <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">svjetlost</a></span>…</span>
</li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="look-display-fuzzy.html" title="Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?">Zašto stvari izgledaju tako čupavo/tačkasto na mom ekranu?</a><span class="desc"> — Rezolucija zaslona može se postaviti na pogrešan način.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
