<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Click and move mouse pointer using the keypad</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="a11y.html" title="Opšti pristup">Opšti pristup</a> › <a class="trail" href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="mouse.html" title="Miš">Miš</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Click and move mouse pointer using the keypad</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako imate poteškoća pri korištenju miša ili drugih pokazivačkih uređaja, možete kontrolisati kursor miša koristeći numerički dio tastature. Ova osobina se zove zove <span class="em">tipke miša</span>.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Tap the <span class="key"><kbd><span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>Super</a></span></kbd></span> key to open the <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">Kucajte <span class="input">Univerzalni Pristup</span> i pritisnite <span class="key"><kbd>Enter</kbd></span> da otvorite postavke Univerzalnog Pristupa.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="key"><kbd>Tab</kbd></span> jednom i odaberite <span class="gui">Vidjeti</span> karticu.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="key"><kbd>←</kbd></span> jednom da se prebacite na <span class="gui">Pokazivači i Klik</span> karticu.</p></li>
<li class="steps"><p class="p">Press <span class="key"><kbd>↓</kbd></span> once to select the <span class="gui">Mouse Keys</span> switch then press <span class="key"><kbd>Enter</kbd></span> to switch it on.</p></li>
<li class="steps"><p class="p">Budite sigurn da je <span class="key"><kbd>Num Lock</kbd></span> isključen. Sada ste u mogućnosti da pomjerate pokazivač miša pomoću tastature.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Ove instrukcije vam obezbjeđuju najkraći put da uključite tipke miša samo pomoću tastature. Odaberite <span class="gui">Postavke Univerzalnog Pristupa</span> da vidite više mogućnosti pristupačnosti.</p></div></div></div></div>
<p class="p">Skup numeričkih tipki na tastaturi, obično poredanih u kvadrat. Ako imate tastaturu bez (kao tastatura laptopa),možda će te morati da držite funkcijsku tipku (<span class="key"><kbd class="key-Fn">Fn</kbd></span>) i da koristite druge tipke na tastaturi. Ako koristite ovo često možete kupiti eksternu USB tastaturu.</p>
<p class="p">Svaki broj odgovara smijeru. Na primjer pritiskom na <span class="key"><kbd>8</kbd></span> pomaći će se prema gore a pritiskom na <span class="key"><kbd>2</kbd></span> prema dole. Pritiskom na tipku <span class="key"><kbd>5</kbd></span> kao pritisak miša ili dva puta brzo kao dvostuku-klik.</p>
<p class="p">većina tastartura imaju posebnu tipku koja dozvoljava desni-klik; često je blizu razmaknice, kakogod ova tipka reaguje tamo gdje je kursor a ne tamo gdje je strelica od miša. pogledajte <span class="link"><a href="a11y-right-click.html" title="Simulacija klika desnom tipkom miša">Simulacija klika desnom tipkom miša</a></span>za informacije kako naprabiti desni klik držanjem tipke <span class="key"><kbd>5</kbd></span> ili lijevog dumeta miša.</p>
<p class="p">Ukoliko želite koristit tastaturu za unos brojeva dok je miš isključen, uključite <span class="key"><kbd>Num Lock</kbd></span>. Miš ne možete kontrolirati pomoću tastature kada je <span class="key"><kbd>Num Lock</kbd></span> uključen.</p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Normalne tipke brojeva, u liniji na vrhu tastature, ne mogu kontrolirati pokazivač miša. Samo se tipke sa brojevima mogu koristiti.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse.html" title="Miš">Miš</a><span class="desc"> — <span class="link"><a href="mouse-lefthanded.html" title="Miš za ljevoruke">Ljevak</a></span>, <span class="link"><a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">brzina i osjetljivost</a></span>, <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">dodirna površina, klik i listanje</a></span>…</span>
</li>
<li class="links "><a href="a11y.html#mobility" title="Oštećenje mobilnosti">Oštećenje mobilnosti</a></li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="mouse-disabletouchpad.html" title="Isključi dodirnu tablu dok kucam">Isključi dodirnu tablu dok kucam</a><span class="desc"> — Isključite dodirnu površinu dok kucate na tastaruri kako biste spriječili slučajne klikove.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
