<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Rýchlosť dvojitého kliknutia</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="a11y.html" title="Bezbariérový prístup">Bezbariérový prístup</a> › <a class="trail" href="a11y.html#mobility" title="Pohybové postihnutie">Pohybové postihnutie</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="mouse.html" title="Myš">Myš</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Rýchlosť dvojitého kliknutia</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Double-clicking only happens when you press the mouse button twice
quickly enough. If the second press is too long after the first, you'll
just get two separate clicks, not a double click. If you have difficulty
pressing the mouse button quickly, you should increase the timeout.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikneme na ikonu v tvare vypínača vpravo na <span class="gui">hornej lište</span> a zvolíme <span class="gui">Nastavenia systému</span>.</p></li>
<li class="steps"><p class="p">Open <span class="gui">Mouse &amp; Touchpad</span>.</p></li>
<li class="steps"><p class="p">Under <span class="gui">General</span>, adjust the <span class="gui">Double-click</span>
  slider to a value you find comfortable.</p></li>
<li class="steps"><p class="p">Click the <span class="gui">Test Your Settings</span> button to test. A single
  click in the window will highlight the outer circle. A double-click will
  highlight the inside circle.</p></li>
</ol></div></div></div>
<p class="p">Ak myš robí dvojité kliknutie, keď chceme urobiť len jednoduché kliknutie aj napriek tomu, že sme skrátili čakanie medzi kliknutiami, môže byť chybná myš. Skúsime k počítaču pripojiť inú myš, aby sme videli, či pracuje správne. Môžeme tiež skúsiť pripojiť myš k inému počítaču a vyskúšať, či nastane rovnaký problém.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">This setting will affect both your mouse and touchpad,
as well as any other pointing device.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="mouse.html" title="Myš">Myš</a><span class="desc"> — 
      <span class="link"><a href="mouse-lefthanded.html" title="Myš pre ľavákov">Left-handed</a></span>,
      <span class="link"><a href="mouse-sensitivity.html" title="Rýchlosť pohybu myši a touchpadu">speed and sensitivity</a></span>,
      <span class="link"><a href="mouse-touchpad-click.html" title="Click, drag, or scroll with the touchpad">touchpad clicking and scrolling</a></span>…
    </span>
</li>
<li class="links "><a href="a11y.html#mobility" title="Pohybové postihnutie">Pohybové postihnutie</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
