<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prečo systém nerozpozná prehrávač po pripojení?</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="media.html" title="Zvuk, video a obrázky">Zvuk, video a obrázky</a> › <a class="trail" href="media.html#music" title="Hudba a prenosné prehrávače">Hudba a prehrávače</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Prečo systém nerozpozná prehrávač po pripojení?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ak je prenosný prehrávač hudby (napr. MP3 prehrávač a podobne) pripojený k počítaču, ale systém ho nezobrazuje v aplikácii na prehrávanie hudby, môže byť problém to, že systém nerozpoznal, že ide o prehrávač hudby.</p>
<p class="p">Skúsime prehrávač odpojiť a potom znova pripojiť. Ak t o nepomôže, <span class="link"><a href="files-browse.html" title="Navigácia medzi priečinkami">otvoríme správcu súborov</a></span>. Prehrávač by sme mali vidieť na bočnom paneli v časti Zariadenia - kliknutím na zodpovedajúcu ikonu otvoríme priečinok prehrávača. Teraz z ponuky zvolíme <span class="guiseq"><span class="gui">Súbor</span> ▸ <span class="gui">Nový dokument</span> ▸ <span class="gui">Prázdny dokument</span></span>, napíšeme .is_audio_player a stlačíme kláves <span class="key"><kbd>Enter</kbd></span> (bodka a znaky podčiarknutia sú dôležité, rovnako ako veľkosť písmen). Tento súbor povie počítaču aby zariadenie rozpoznal ako prehrávač hudby.</p>
<p class="p">Teraz klikneme na prehrávač hudby na bočnom panely správcu súborov a vysunieme ho (klikneme pravým tlačidlom a zvolíme <span class="gui">Vysunúť</span>). Odpojíme ho a znova ho pripojíme. Tentoraz by ho aplikácia na prehrávanie hudby mala rozpoznať. Ak nie, skúsime aplikáciu zatvoriť a znova otvoriť.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">Tieto inštrukcie nefungujú pre iPody a niektoré ďalšie prenosné prehrávače. Mali by fungovať pri zariadeniach, ktoré sú označené ako <span class="em">veľkokapacitné pamäťové zariadenie (Mass Storage)</span>. Či je váš prehrávač takýmto druhom zariadenia sa dozviete z jeho návodu.</p></div></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">Ak sa znova pozrieme do priečinka prenosného prehrávača, súboru <span class="input">.is_audio_player</span>. Je to preto, lebo bodka na začiatku názvu súboru znamená, že súbor má byť skrytý. Môžeme si to overiť tak, že z ponuky zvolíme <span class="guiseq"><span class="gui">Zobraziť</span> ▸ <span class="gui">Zobraziť skryté súbory</span></span>.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#music" title="Hudba a prenosné prehrávače">Hudba a prehrávače</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="music-player-newipod.html" title="Nový iPod nefunguje">Nový iPod nefunguje</a><span class="desc"> — Novozakúpené iPody je potrebné pred použitím nastaviť pomocou softvéru iTunes.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
