<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zašto moj audio player ne prepoznaju kada ga spojim?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zašto moj audio player ne prepoznaju kada ga spojim?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako je vaš audio player (MP3 player itd.) spojen na računar ali ne vidite muzičku aplikaciju, vjerovatno nije ispravno prepoznat kao audio player.</p>
<p class="p">Try unplugging the player and then plugging it in again. If that doesn't help, <span class="link"><a href="files-browse.html" title="Pregledavanje datoteka i mapa.">open the file manager</a></span>. You should see the player listed under <span class="gui">Devices</span> in the sidebar - click it to open the folder for the audio player. Now, click <span class="guiseq"><span class="gui">File</span> ▸ <span class="gui">New Document</span> ▸ <span class="gui">Empty Document</span></span>, type <span class="input">.is_audio_player</span> and press <span class="key"><kbd>Enter</kbd></span> (the period and underscores are important, and it should be all lower-case). This file tells your computer to recognize the device as an audio player.</p>
<p class="p">Sada, naći audio playera u sidebar upravitelj datoteka i izbaciti (desnom tipkom miša i kliknite <span class="gui"> izbacivanje </span>). Isključite ga, a zatim ga priključite natrag u. Ovaj put to je trebao biti priznat kao audio playera svoj ​​glazbeni organizator. Ako ne, pokušajte zatvoriti glazbeni organizator, a zatim ponovno otvaranje .</p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Ove upute neće raditi za iPod i nekih drugih audio playera. Oni bi trebali raditi ako vaš igrač je misa <span class="em"> USB pohrana </span> uređaj, iako, to bi trebalo reći u svom priručniku ako je.</p></div></div></div></div>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Kada pogledate u audio player mape opet, nećete vidjeti <span class="input">. Is_audio_player </span> file. To je zato što je to razdoblje u spisu ime govori upravitelj datoteka za skrivanje datoteka. Možete provjeriti da je još uvijek tamo klikom <span class="guiseq"><span class="gui"> Pogled </span> ▸ <span class="gui"> Prikaži skrivene datoteke </span></span>.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="music-player-newipod.html" title="Moj noviiPod neće da radi">Moj noviiPod neće da radi</a><span class="desc"> — Posve novi iPod moraju biti postavljeni koristeći iTunes softver prije nego što možete ih koristiti.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
