<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Úprava záložiek na priečinky</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> › <a class="trail" href="files.html#faq" title="Tipy a otázky">Tipy a otázky</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Úprava záložiek na priečinky</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Your bookmarks are listed in the sidebar of the file manager.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Pridanie záložky:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvoríme priečinok (alebo miesto), ktoré chceme pridať medzi záložky.</p></li>
<li class="steps"><p class="p">Click the gear button in the toolbar and pick
    <span class="gui">Bookmark this Location</span>.</p></li>
</ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Odstránenie záložky:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Click on <span class="gui">Files</span> in the top bar and pick <span class="gui">Bookmarks</span>
   from the app menu. </p></li>
<li class="steps"><p class="p">In the <span class="gui">Bookmarks</span> window, select the bookmark you wish to
   delete and click the <span class="key"><kbd>-</kbd></span> button.</p></li>
</ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Rename a bookmark:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Click on <span class="gui">Files</span> in the top bar and pick <span class="gui">Bookmarks</span>
     from the app menu.</p></li>
<li class="steps"><p class="p">In the <span class="gui">Bookmarks</span> window, select the bookmark you wish to
    rename.</p></li>
<li class="steps">
<p class="p">Do textového poľa <span class="gui">Názov</span> zadáme nový názov záložky.</p>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">Premenovaním záložky sa nezmení názov priečinka. Ak máme záložky pre dva rozdielne priečinky na dvoch rozdielnych miestach, no s rovnakým názvom, záložka bude mať rovnaký názov, a my ich nebudeme vedieť rozlíšiť. V takomto prípade je vhodné priradiť záložke iný názov ako je názvo priečinka, na ktorý odkazuje.</p></div></div></div></div>
</li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Tipy a otázky">Tipy a otázky</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
