<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Postavke pregleda programa za upravljanje datotekama</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » <a class="trail" href="nautilus-prefs.html" title="Postavke programa za upravljanje datotekama">Postavke programa za upravljanje datotekama</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Postavke pregleda programa za upravljanje datotekama</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">The file manager creates thumbnails to preview image, video, and text
files. Thumbnail previews can be slow for large files or over networks, so
you can control when previews are made. Click <span class="gui">Files</span> in the menu bar,
pick <span class="gui">Preferences</span> and select the <span class="gui">Preview</span> tab.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Datoteke</span></dt>
<dd class="terms">
<p class="p">By default, all previews are done for <span class="gui">Local Files Only</span>, those
    on your computer or connected external drives. You can set this feature to
    <span class="gui">Always</span> or <span class="gui">Never</span>. The file manager can
    <span class="link"><a href="nautilus-connect.html" title="Pregled datoteka na serveru ili na mreži">browse files on other computers</a></span> over
    a local area network or the internet. If you often browse files over a local
    area network, and the network has high bandwidth, you may want to set the
    preview option to <span class="gui">Always</span>.</p>
<p class="p">In addition, you can use the <span class="gui">Only for files smaller than</span>
    setting to limit the size of files previewed.</p>
</dd>
<dt class="terms"><span class="gui">Direktoriji</span></dt>
<dd class="terms"><p class="p">Ako vam pokazati veličine datoteka u <span class="link"><a href="nautilus-list.html" title="Postavke listi kolona menadžera datoteka"> prikazu popisa stupaca </a></span> ili <span class="link"><a href="nautilus-display.html#icon-captions" title="Naslovi ikona"> ikona naslove </a></span>, mape će biti prikazan sBrojač koliko datoteke i mape koje sadrže. Računajući stavke u mapi može biti spor, a posebno za velike mape, ili preko mreže. Možete uključiti ovu značajku ili isključiti, ili ga uključiti samo za datoteke na vašem računalu i lokalne vanjske diskove.</p></dd>
</dl></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="nautilus-prefs.html" title="Postavke programa za upravljanje datotekama">Postavke programa za upravljanje datotekama</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files-preview.html" title="Preview files and folders">Preview files and folders</a><span class="desc"> — 
      Quickly show and hide previews for documents, images, videos, and 
      more.
    </span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
