<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Postavite dozvole za datoteku</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Postavite dozvole za datoteku</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete koristiti dozvolu datoteka za kontrolu ko može gledati i uređivati vaše datoteke. Za pregled i postavke dozvole za datoteke, desni klik i odaberite <span class="gui">Svojstva</span>, a zatim odaberite <span class="gui">Dozvole</span> tab.</p>
<p class="p">Vidi <span class="link"><a href="#files" title="Datoteke">Datoteke</a></span> i <span class="link"><a href="#folders" title="Direktoriji">Direktoriji</a></span> ispod za detalje o tipovima dozvola koje možete postaviti.</p>
</div>
<div id="files" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Datoteke</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete postaviti dozvole za datoteke vlasnika, grupe vlasnika, i svim ostalim korisnicima sustava. Za svoje datoteke, vi ste vlasnik, a možete dati sebi samo za čitanje ili čitanje-i-napisati dozvolu. Postavite datoteku samo za čitanje ako ne želite slučajno ga promijeniti.</p>
<p class="p">Svaki korisnik na vašem računalu pripada skupini. Na kućnim računalima, što je uobičajeno za svaki korisnik ima svoju skupinu, i grupa dozvole nisu često koristi. U korporativnim okruženjima, skupine se ponekad koriste za odjele ili projekte. Kao i da vlasnika, svaka datoteka pripada skupini. Možete postaviti datoteke grupu i kontrolu dozvole za sve korisnike u toj grupi. Možete samo postaviti datoteke grupu na skupinu spadate u.</p>
<p class="p">Takođe možete postaviti dozvole za druge korisnike osim vlasnika i one koji su u grupi datoteke.</p>
<p class="p">Ako je datoteka programa, kao što su pisma, morate odabrati <span class="gui"> Dopustite izvršavanju sliku kao program </span> da ga pokrenuti. Čak i uz ova opcija odabrana, menadžer datoteka još uvijek može otvoriti datoteku u programu ili vas pitati što učiniti. Vidi <span class="link"><a href="nautilus-behavior.html#executable" title="Izvršne tekstualne datoteke">Izvršne tekstualne datoteke</a></span> za više informacija.</p>
</div></div>
</div></div>
<div id="folders" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Direktoriji</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete postaviti dozvole za mapu za vlasnika, grupu, i druge korisnike. Pogledajte detalje o dozvolama za datoteke za objašnjenje o vlasnicima, grupama i drugim korisnicima.</p>
<p class="p">Dozvole koje možete postaviti za mapu su različite od onih koje možete postaviti za datoteku.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms"><span class="gui">Nijedan</span></dt>
<dd class="terms"><p class="p">Korisnik neće ni biti u mogućnosti da vidi koje datoteke su u folderu.</p></dd>
<dt class="terms"><span class="gui">Samo pregledanje datoteka</span></dt>
<dd class="terms"><p class="p">Korisnik će biti u mogućnosti da vidi datototeke koje se nalaze u folderu, ali ne i da ih otvara, kreira ili briše.</p></dd>
<dt class="terms"><span class="gui">Pristup datotekama</span></dt>
<dd class="terms"><p class="p">Korisnik će biti u mogućnosti da otvori datoteke iz mape (ako ima dozvolu za to za odgovarajuću datoteku), ali neće biti u mogućnosti da kreira novu datoteku ili da je izbriše.</p></dd>
<dt class="terms"><span class="gui">Kreiranje i brisanje datoteka</span></dt>
<dd class="terms"><p class="p">Korisnik će imati potpuni pristup folderu, uključujući otvaranje, kreiranje i brisanje datoteka.</p></dd>
</dl></div></div></div>
<p class="p">You can also quickly set the file permissions for all the files
    in the folder by clicking <span class="gui">Change Permissions for Enclosed Files</span>.
    Use the drop-down lists to adjust the permissions of contained files or
    folders, and click <span class="gui">Change</span>. Permissions are applied to files and
    folders in subfolders as well, to any depth.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="nautilus-file-properties-basic.html" title="Svojstva datoteke">Svojstva datoteke</a><span class="desc"> — Pogledajte osnovne informacije o datoteci, postavite dozvole, i izaberite zadani program.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
