<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Alat za otkrivanje poteškoća u vezi bežičnih mreža</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » <a class="trail" href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks">
<a class="nextlinks-prev" href="net-wireless-troubleshooting-initial-check.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Previous</a><a class="nextlinks-next" href="net-wireless-troubleshooting-hardware-check.html" title="Rješavanje problema bežične konekcije">Next</a>
</div>
<div class="hgroup">
<h1 class="title"><span class="title">Alat za otkrivanje poteškoća u vezi bežičnih mreža</span></h1>
<h2 class="subtitle"><span class="subtitle">Skupite informacije o vašem mrežnom hardveru</span></h2>
</div>
<div class="region">
<div class="contents">
<p class="p">U ovom koraku, vi cete skupiti informacije o vasem bezicnom adapteru. nacin na koji rijesavate probleme sa bezicnom konekcijom zavisi od modela i broja bezicnog adaptera, trbat cete znati ove detalje. Takodje moze biti koristno da imate neke dijelove koji su dosli uz vas racunar, kao npr diskovi sa drajverima, potrazite sledece, da li imate:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Pakovanje i instrukcije za vas bezicni uredjaj (posebno uputstvo za upotrebu vaseg rutera)</p></li>
<li class="list"><p class="p">Disk sadrži drajvere za vaš bežični adapter (čak i ako sadrži samo Windows drajvere).</p></li>
<li class="list"><p class="p">Proizvodjac i broj modela vaseg racunara, bezicnog adaptera i rutera. Ova informacija se cesto moze naci na donjoj strani uredjaja.</p></li>
<li class="list"><p class="p">Bilo koji verzija/revizija brojevi koji su printani na vasim bezicnim uredjajima ili njihovim pakovanjima. Mogu biti korisni zato obratite paznju.</p></li>
<li class="list"><p class="p">Bilo sta na disku sa drajverima sta identifikuje uredjaj, to je verzija hardvera ili komponenti (chipseta) koje koristi</p></li>
</ul></div></div></div>
<p class="p">Ako je moguce, pokusajte se spojiti na neku drugu internet konekciju da mozete skinuti softver i drajvere ako bude potrebe. (ukljucivanjem vaseg racunara direktno u ruter je jedan od nacina da se ovo ostvari, ali nije preporuceno)</p>
<p class="p">Kada imate što je moguće više stavki, kliknite <span class="gui">Dalje</span>.</p>
</div>
<div class="links nextlinks">
<a class="nextlinks-prev" href="net-wireless-troubleshooting-initial-check.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Previous</a><a class="nextlinks-next" href="net-wireless-troubleshooting-hardware-check.html" title="Rješavanje problema bežične konekcije">Next</a>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Alat za otkrivanje poteškoća u vezi bežičnih mreža</a><span class="desc"> — Identifikujte i riješite probleme sa bežičnim povezivanjima</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
