<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Napravite konekciju sa fiksiranom IP adesom</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Napravite konekciju sa fiksiranom IP adesom</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Većina mreža će automatski dodijeliti IP adresu <span class="link"><a href="net-what-is-ip-address.html" title="Šta je IP adresa?">Šta je IP adresa?</a></span> i ostale pojedinosti na vašem računalu kada ste spojeni na mrežu. Ovi podaci mogu periodično mijenjati, ali možda želite imati fiksnu IP adresu za računalo, tako da uvijek znate što njegova adresa je (na primjer, ako je file server).</p>
<p class="p">Da date Vašem računaru fiksiranu ( statičnu) IP adesu</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui"> izbornik mreže</span> na traci izbornika i odaberite <span class="gui">Uredi Veze</span></p></li>
<li class="steps"><p class="p">Select the <span class="gui">Wired connection</span> on the <span class="gui">Wired</span> tab or your WiFi network on the <span class="gui">Wireless</span> tab and click <span class="gui">Edit</span>.</p></li>
<li class="steps"><p class="p">Kliknite na <span class="gui">IPv4 postavke</span> kartici i promijenite <span class="gui">Metod</span>  u <span class="em">Ručno</span>.</p></li>
<li class="steps"><p class="p">Ako nema informacija o vezi u <span class="gui"> Adrese </span> popisu, ili ako želite postaviti novu vezu, kliknite  <span class="gui">Dodaj </span>.</p></li>
<li class="steps"><p class="p">Ukucajte <span class="em">IP Adresa</span>, <span class="em">Mrežna maska</span>, i  <span class="em">Izlaz</span> informaciju u odgovarajuća polja. Kako ćete ih izabrati zavisit će od Vaših mrežnih postavki;postoje posebna pravila koja uređuju IP adrese i netmaske koje vrijede za određenu mrežu.</p></li>
<li class="steps"><p class="p">Ako je potrebno, unesite  <span class="em">Naziv Servera </span> adresu u <span class="gui"> DNS serveri </span> okvir domene. To je IP adresa servera koji gleda do imena domena, a većina korporativnih mreža i internet provideri imaju povećane DNS servere</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Snimi</span>.Mrežna konekcija trebala bi sada imati stalnu IP adresu.</p></li>
</ol></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a><span class="desc"> — <span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">Žičana internet konekcija</a></span>, <span class="link"><a href="net-fixed-ip-address.html" title="Napravite konekciju sa fiksiranom IP adesom">Stalne IP adrese</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-findip.html" title="Nađite Vašu IP adresu">Nađite Vašu IP adresu</a><span class="desc"> — Poznavanje Vaše IP adrese Vam može pomoći pri rješavanju mrežnih problema</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
