<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Da li trebam skenirati svoje mailove od virusa?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-email.html" title="E-mail pošta i e-mail program">E-mail pošta i e-mail program</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Da li trebam skenirati svoje mailove od virusa?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Virusi su programi koji izazivaju probleme ako uspiju pronaći put do vašeg računara. Čest način da dođu na računar je putem email poruka.</p>
<p class="p">Virusi koji mogu djelovati na računare koji koriste Linux su rijetki, dakle vi ste <span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">nesigurni da dobijete virus preko emaila ili ne neki drugi način</a></span>.  Ako primite email sa virusom koji je sakriven, vjerovatno neće imati nikakvog efekta na računar. Dakle, vjerovatno ne morate da skenirate email za viruse.</p>
<p class="p">Kako god,Vi možete skenirati Vašu e-mail poštu u slučaju da se desi da proslijedite virus jedne osobe drugoj. Npr. ako jedan Vaš prijatelj ima Windows računar sa virusom i zaražen mail, i Vi taj mail proslijedite drugom rijatelju sa Windows računarom, onda taj drugi prijatelj može dobiti virus. Možete instalirati antivirusni program za skeniranje e-mail pošte kako biste spriječili ovo, ali malo je vjerovatno da ljudi koji koriste Windows ili Mac OS nemaju instaliran antivirusni program na svojim računarima.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-email.html" title="E-mail pošta i e-mail program">E-mail pošta i e-mail program</a><span class="desc"> — <span class="link"><a href="net-default-email.html" title="Promjena aplikacije za pisanje maila">Podrazumijevani programi elektronske pošte</a></span></span>
</li>
<li class="links ">
<a href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a><span class="desc"> — <span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Antivirus softver</a></span>, <span class="link"><a href="net-firewall-on-off.html" title="Omogućite ili blokirajte pristup protupožarnom zidu">osnovni protupožarni zidovi</a></span>…</span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Da li mi treba anti-virusni softver?</a><span class="desc"> — Ovdje je nekoliko Linux virusa, tako da vjerovatno ne trebate anti-virusni softver.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
