<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako mogu koristiti Skype na Ubuntu?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">Chat &amp; Drustveno Umrezavanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako mogu koristiti Skype na Ubuntu?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p"><span class="app">Skype</span> je vlasnički program koji dopusta da pravite pozive putem interneta koristeci računar</p>
<p class="p">Skype koristi decentraliziranu vršnjak-vršnjaku tehnologije,tako da Vaši pozivi ne idu kroz centralni server,ali idu kroz servise za distribuiranje i druge korisnike</p>
<p class="p">Skype program je besplatan za koristenje,ali nije slobodni program;izvorni kod je vlasnički i ne može se modifikovati</p>
<p class="p">Skype nije instaliiran automatski na Ubuntu.<span class="link"><a href="https://apps.ubuntu.com/cat/applications/skype" title="https://apps.ubuntu.com/cat/applications/skype">Instaliraj <span class="em">skype</span> paket</a></span> za korištenje</p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Vi trebate <span class="link"><a href="addremove-sources.html#canonical-partner" title="Aktivirajte Canonical Partner Spremište">aktivirati repozitorij partnera firme Canonical</a></span>  da biste instalirali <span class="app">Skype</span></p></div></div></div></div>
<div class="list"><div class="inner">
<div class="title title-list"><h2><span class="title">Dodatni izvori za pomoć sa <span class="app">Skype</span></span></h2></div>
<div class="region"><ul class="list">
<li class="list"><p class="p"><span class="link"><a href="https://help.ubuntu.com/community/SkypeRecordingHowto" title="https://help.ubuntu.com/community/SkypeRecordingHowto"> Kako snimiti Skype razgovore </a></span></p></li>
<li class="list"><p class="p"><span class="link"><a href="https://wiki.ubuntu.com/SkypeWebCams" title="https://wiki.ubuntu.com/SkypeWebCams"> Lista webkamera koje su kompatibilne sa Skype </a></span></p></li>
<li class="list"><p class="p"><span class="link"><a href="https://help.ubuntu.com/community/SkypeTroubleshooting" title="https://help.ubuntu.com/community/SkypeTroubleshooting"> Rješavanje problema Skype - za napredne korisnike</a></span></p></li>
</ul></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">Chat &amp; Drustveno Umrezavanje</a><span class="desc"> — <span class="link"><a href="net-chat-empathy.html" title="Instantno dopisivanje na Ubuntu">Chat na bilokojoj mrezi koristeci<span class="app">Empathy</span></a></span>, <span class="link"><a href="net-chat-video.html" title="Video pozivi">napravi video pozive</a></span>, <span class="link"><a href="net-chat-skype.html" title="Kako mogu koristiti Skype na Ubuntu?">instaliraj skype</a></span>, <span class="link"><a href="net-chat-social.html" title="Dršstveno umrežavanje sa radne površine">aplikacije drustvenog umrezavanja</a></span></span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-chat-video.html" title="Video pozivi">Video pozivi</a><span class="desc"> — Koje aplikacije mogu koristiti za pokretanje video poziva?</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
