<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ostati siguran na internetu</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ostati siguran na internetu</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">A possible reason for why you are using Ubuntu is the robust security that Linux based
systems are known for. One reason that Linux is relatively safe from malware and
viruses is due to the lower number of people who use it.
Viruses are targeted at popular operating systems like Windows, that have an extremely large
user base. Linux based systems are also very secure due to their open source nature, which allows
experts to modify and enhance the security features included with each distribution.</p>
<p class="p">Despite the measures taken to ensure that your installation of Ubuntu is secure, there
are always vulnerabilities. As an average user on the internet you can still be susceptible to:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Phishing prevare (web stranice i e-mailove koji pokušavaju dobiti osjetljive informacije kroz obmane)</p></li>
<li class="list"><p class="p"><span class="link"><a href="net-email-virus.html" title="Da li trebam skenirati svoje mailove od virusa?"> Prosljeđivanje zlonamjernih e-poruka </a></span></p></li>
<li class="list"><p class="p"><span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Zlonamjerni programi (virusi)</a></span></p></li>
<li class="list"><p class="p"><span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">Unauthorized remote/local network access</a></span></p></li>
</ul></div></div></div>
<p class="p">Da biste bili sigurni online, imajte na umu sljedeće savjete:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Budite oprezni sa e-mail-ovima, prilozima, ili poveznicama koje vam šalju nepoznati ljudi.</p></li>
<li class="list"><p class="p">Ako web stranica je ponuda je predobro da bi bilo istinito, ili pita za osjetljive informacije koje se čini nepotrebno, a zatim dvaput razmisliti o tome što informacije koje su poslali i potencijalne posljedice ako se ta informacija je ugrožena kradljivci identiteta ili drugih kriminalaca.</p></li>
<li class="list"><p class="p">Budite oprezni u pružanje bilo koje aplikacije <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?"> dozvole root level </a></span>, posebno one koje niste koristili prije ili aplikacije koje nisu poznati. Pružanje nikoga / ništa sa root level dozvolama stavlja računalo na visokim rizikom za eksploataciju.</p></li>
<li class="list"><p class="p">Provjerite jeste li samo pokrenuli potrebne za daljinski pristup uslugama. Nakon SSH ili VNC trčanje može biti korisno, ali također ostavlja vaše računalo otvoren za upad ako ne i osiguran pravilno. Razmislite o korištenju <span class="link"><a href="net-firewall-on-off.html" title="Omogućite ili blokirajte pristup protupožarnom zidu"> firewall </a></span> kako bi zaštitili svoje računalo od upada.</p></li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a><span class="desc"> — <span class="link"><a href="net-findip.html" title="Nađite Vašu IP adresu">Pronađite vašu IP adresu</a></span>, <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">WEP &amp; WPA sigurnost</a></span>, <span class="link"><a href="net-macaddress.html" title="Šta je MAC adresa?">MAC adrese</a></span>, <span class="link"><a href="net-proxy.html" title="Definišite postavke ovlaštenja">proxies</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
