<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Umrežavanje, web, elektronska pošta i ćaskanje</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Umrežavanje, web, elektronska pošta i ćaskanje</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to wifi</a></span>,
      <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>,
      <span class="link"><a href="net-wireless-edit-connection.html" title="Uredite bežičnu konekciju">Edit connection settings</a></span>,
      <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">Chat &amp; Drustveno Umrezavanje</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-chat-empathy.html" title="Instantno dopisivanje na Ubuntu">Chat na bilokojoj mrezi koristeci<span class="app">Empathy</span></a></span>, <span class="link"><a href="net-chat-video.html" title="Video pozivi">napravi video pozive</a></span>, <span class="link"><a href="net-chat-skype.html" title="Kako mogu koristiti Skype na Ubuntu?">instaliraj skype</a></span>, <span class="link"><a href="net-chat-social.html" title="Dršstveno umrežavanje sa radne površine">aplikacije drustvenog umrezavanja</a></span></span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="sharing.html" title="Dijeljenje">Dijeljenje</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="sharing-desktop.html" title="Dijelite vaš desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Share files</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-email.html" title="E-mail pošta i e-mail program">E-mail pošta i e-mail program</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-default-email.html" title="Promjena aplikacije za pisanje maila">Podrazumijevani programi elektronske pošte</a></span></span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="contacts.html" title="Kontakti">Kontakti</a></div>
<div class="desc"><span class="desc">Pristup vašim kontaktima.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Antivirus softver</a></span>, <span class="link"><a href="net-firewall-on-off.html" title="Omogućite ili blokirajte pristup protupožarnom zidu">osnovni protupožarni zidovi</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-wired.html" title="Ožičeno umrežavanje">Ožičeno umrežavanje</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-wired-connect.html" title="Povezivanje na žičanu (Ethernet) mreže">Žičana internet konekcija</a></span>, <span class="link"><a href="net-fixed-ip-address.html" title="Napravite konekciju sa fiksiranom IP adesom">Stalne IP adrese</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-mobile.html" title="Povezivanje na mobilni širokopojasni pristup.">Povezivanje na mobilni širokopojasni pristup.</a></div>
<div class="desc"><span class="desc">Konektujte se na interent koristeći mobilni širokopojasni pristup</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Troubleshooting wireless connections</a></span>,
      <span class="link"><a href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi.">finding your wifi network</a></span>…
        </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-findip.html" title="Nađite Vašu IP adresu">Pronađite vašu IP adresu</a></span>, <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">WEP &amp; WPA sigurnost</a></span>, <span class="link"><a href="net-macaddress.html" title="Šta je MAC adresa?">MAC adrese</a></span>, <span class="link"><a href="net-proxy.html" title="Definišite postavke ovlaštenja">proxies</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net-browser.html" title="Web pretraživači">Web pretraživači</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="net-default-browser.html" title="Promjenite u kojem web pretraživaču se otvaraju web stranice.">Change the default browser</a></span>,
      <span class="link"><a href="net-install-flash.html" title="Instalirajte Flash plug-in">install Flash</a></span>,
      <span class="link"><a href="net-install-java-plugin.html" title="Instalirajte Java pretraživač plug-in">install the java plugin</a></span>,
      <span class="link"><a href="net-install-moonlight.html" title="Instaliraj Silverlight dodatak">Silverlight support</a></span>…
    </span></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
