<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako vršim hibernaciju mog računara?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako vršim hibernaciju mog računara?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada racunar <span class="em">hibernira</span>, sve vase aplikacije i dokumenti su spaseni na racunar i racunar se gasi u potpunosti tako da ne koristi energu, ali aplikacije i dokumenti ce biti otvoreni kad upalite vas racunar ponovo.</p>
<p class="p">nazalost, hibernacija <span class="link"><a href="power-suspendfail.html" title="Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??"> ne radi </a></span> u mnogim slucajevima, koji mogu prouzrokovati da izgubite podatke ako ocekujete da se ovasi dokumenti i aplikacije otvore kada upalite racunar ponovo.  Zato je hibernacija iskljucena.</p>
</div>
<div id="test-hibernate" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Testirajte da li hibernacija radi</span></h2></div>
<div class="region"><div class="contents">
<div class="note note-important" title="Important"><div class="inner">
<div class="title title-note"><h3><span class="title">Uvijek snimite svoj rad prije hibernacije</span></h3></div>
<div class="region"><div class="contents"><p class="p">Trebali bi spasiti sav vas rad prije hiberniranja racunara, u slucaju da nesto krene naopako i vasi dokumenti i aplikacije ne mogu da se vrate kada pokrenete racunar ponovo.</p></div></div>
</div></div>
<p class="p">Možete koristiti komandnu liniju da testirate da li hibernacija radi na vašem računaru.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Open the <span class="app">Terminal</span> by pressing <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>t</kbd></span></span> or by searching for <span class="input">terminal</span>
        in the <span class="gui">Dash</span>.</p></li>
<li class="steps">
<p class="p">Ukucajte <span class="cmd">sudo pm-hibernate</span> u terminalu i pritisnite <span class="key"><kbd>Enter</kbd></span>.</p>
<p class="p">Unesite vašu šifru kada se to zatraži.</p>
</li>
<li class="steps">
<p class="p">Poslije gašenja vašeg računara, ponovo ga upalite. Da li su se vaši otvireni programi ponovo otvorili?</p>
<p class="p">Ako hibernacija ne radi, provjerite da li je vaša zamjenska particija velika bar kao dostupni RAM.</p>
</li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="enable-hibernate" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Omogućite hibernaciju</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako test hibernacije radi, možete nastaviti koristiti <span class="cmd">sudo pm-hibernate</span> komandu kada želite hibernirati.</p>
<p class="p">Mozete takodjer ukljiciti opciju hibernacije u meniju. Da to uradite koristite vas omiljeni tekst editor da kreirate  <span class="file">/etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla</span>. Dodajte sledece u fajl i spasite.</p>
<div class="code"><pre class="contents ">[Re-enable hibernate by default in upower]
Identity=unix-user:*
Action=org.freedesktop.upower.hibernate
ResultActive=yes

[Re-enable hibernate by default in logind]
Identity=unix-user:*
Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.hibernate-multiple-sessions
ResultActive=yes</pre></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a><span class="desc"> — 
      <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">screen dimming</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">Koristite manje snage i unaprijedite trajanje baterije</a><span class="desc"> — Tips to reduce the power consumption of your computer.</span>
</li>
<li class="links ">
<a href="shell-exit.html" title="Odjavti se, isključiti, zamijeniti korisnika">Odjavti se, isključiti, zamijeniti korisnika</a><span class="desc"> — Naučite kako da napustite svoj korisnički račun, bez odjavljivanja, mijenjanja korisnika, i tako dalje.</span>
</li>
<li class="links ">
<a href="power-suspendfail.html" title="Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??">Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??</a><span class="desc"> — Hardver nekih računara stvara problem sa obustavljanjem ili hibernacijom</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
