<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Koristite manje snage i unaprijedite trajanje baterije</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Koristite manje snage i unaprijedite trajanje baterije</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Racunari mogu koristiti dosta energije. Koristenjem obicnih strategija ustede energije, mozete smanjiti racn za struju i pomoci okolisu. Ako imate laptop, ovo ce poveceati vrijeme koristenja laptopa samo na napajanju baterijom.</p></div>
<div id="general" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Opći savjeti</span></h2></div>
<div class="region"><div class="contents"><div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p"><span class="link"><a href="shell-exit.html#suspend" title="Suspenduj">Obustavite vaš računar</a></span> kada ga ne koristite. Ovo značajno može smanjiti količinu energije koja se koristi, a može se probuditi veoma brzo.</p></li>
<li class="list"><p class="p"><span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">Turn off</a></span> the computer when you
    will not be using it for longer periods. Some people worry that turning off
    a computer regularly may cause it to wear out faster, but this is not the
    case.</p></li>
<li class="list"><p class="p">Koristite postavke <span class="gui">Napajanja</span> u <span class="app">Podešavanjima sistema</span> da izmijenite vaša podešavanja napajanja. Postoji veliki broj opcija koje će vam pomoći da sačuvate energiju: možete <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">samostalno da zatamnite</a></span> ekran nakon određenog vremena; <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">da umanjite osvetljenost ekrana</a></span> (za prenosive računare); ili da se računar <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">sam uspava</a></span> ako ga ne koristite izvesni vremenski period.</p></li>
<li class="list"><p class="p">Turn off any external devices (like printers and scanners) when you are
    not using them.</p></li>
</ul></div></div></div></div></div>
</div></div>
<div id="laptop" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Laptopi, notebook-ovi, i drugi uređaji sa baterijama</span></h2></div>
<div class="region"><div class="contents"><div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p"><span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">Smanjenje osvjetljenja ekrana</a></span>;  Napajanje ekrana cini veliki udio u potrosnji energije laptopa.</p>
<p class="p">Većina laptopa ima dugmad na tastaturi (ili kratice na tastaturi) koje možete koristii da smanjite svjetlost.</p>
</li>
<li class="list">
<p class="p">If you do not need an Internet connection for a little while, turn off
     the wireless/Bluetooth card. These devices work by broadcasting radio
     waves, which takes quite a bit of power.</p>
<p class="p">Pojedini računari imaju fizički prekidač koje se može upotrijebiti kako bi se računar ugasio, a drugi imaju prečicu na tastaturi koju također možete koristiti. Možete ga opet upaliti kada Vam bude trebao.</p>
</li>
</ul></div></div></div></div></div>
</div></div>
<div id="advanced" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Više naprednih savjeta</span></h2></div>
<div class="region"><div class="contents"><div class="list"><div class="inner"><div class="region"><ul class="list"><li class="list">
<p class="p">Smanjite broj zadataka koji se izvršavaju u pozadini. Računar koristi više energije kada ima više posla za obaviti.</p>
<p class="p">Većina vaših pokrenutih programa rade veoma malo kada ih aktivno ne koristite. Ipak, programi koji peiodično uzimaju podake sa interneta, reproduciraju muziku ili filmove mogu uticati na potrošnju energije.</p>
</li></ul></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a><span class="desc"> — 
      <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">screen dimming</a></span>…
    </span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">Isključiti ili restartovati</a></li>
<li class="links ">
<a href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?">Kako vršim hibernaciju mog računara?</a><span class="desc"> — Hibernacija je normalno onemogućena jer nije potpuno podržana.</span>
</li>
<li class="links ">
<a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Šta se dešava kada obustavim moj računar?</a><span class="desc"> — Suspendiranje salje vas racunar na spavanje ztako da koristi manje energije.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
