<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Snaga &amp; baterija</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Snaga &amp; baterija</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="power-batteryoptimal.html" title="Dobijte najviše od vaše laptop baterije"><span class="title">Dobijte najviše od vaše laptop baterije</span><span class="linkdiv-dash"> — </span><span class="desc">Tips such as "Do not let the battery charge get too low"</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?"><span class="title">Kako vršim hibernaciju mog računara?</span><span class="linkdiv-dash"> — </span><span class="desc">Hibernacija je normalno onemogućena jer nije potpuno podržana.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije"><span class="title">Koristite manje snage i unaprijedite trajanje baterije</span><span class="linkdiv-dash"> — </span><span class="desc">Tips to reduce the power consumption of your computer.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="shell-exit.html" title="Odjavti se, isključiti, zamijeniti korisnika"><span class="title">Odjavti se, isključiti, zamijeniti korisnika</span><span class="linkdiv-dash"> — </span><span class="desc">Naučite kako da napustite svoj korisnički račun, bez odjavljivanja, mijenjanja korisnika, i tako dalje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-closelid.html" title="Zašto se moj računar gasi kada zatvorim kapak?"><span class="title">Zašto se moj računar gasi kada zatvorim kapak?</span><span class="linkdiv-dash"> — </span><span class="desc">Laptopi "zaspe" kada ih poklopite, kako bi sačuvali snagu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?"><span class="title">Šta se dešava kada obustavim moj računar?</span><span class="linkdiv-dash"> — </span><span class="desc">Suspendiranje salje vas racunar na spavanje ztako da koristi manje energije.</span></a></div>
</div></div></div></div>
<div id="battery" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Podešavanja baterije</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="power-batteryestimate.html" title="Procjenjeno trajanje baterije je pogrešno"><span class="title">Procjenjeno trajanje baterije je pogrešno</span><span class="linkdiv-dash"> — </span><span class="desc">Trajanje baterije se prikazuje kada kliknete na <span class="gui">ikonu baterije</span> procjena.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-batteryslow.html" title="Why is my laptop slow when it is on battery?"><span class="title">Why is my laptop slow when it is on battery?</span><span class="linkdiv-dash"> — </span><span class="desc">Neki laptopi namjerno usporavaju kada rade na bateriji.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-batterywindows.html" title="Zašto imam manje baterije nego kada radim sa Windows/Mac OS?"><span class="title">Zašto imam manje baterije nego kada radim sa Windows/Mac OS?</span><span class="linkdiv-dash"> — </span><span class="desc">Ugadjanja od proizvodjaca i procjena zivota baterije mogu prouzrokovati ovaj problem.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?"><span class="title">Zašto se moj ekran zamagli nakon nekog vremena?</span><span class="linkdiv-dash"> — </span><span class="desc">Ako vaš računar radi na bateriju, ekran će se zatamniti kada računar miruje kako bi uštedio snagu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-lowpower.html" title="Zašto se moj računar gasi/obustavlja kada baterija dođe do 10%?"><span class="title">Zašto se moj računar gasi/obustavlja kada baterija dođe do 10%?</span><span class="linkdiv-dash"> — </span><span class="desc">Dopustiti bateriji da se potpuno ispazni je loše za nju</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problemi</span></h2></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><ul>
<li class="links "><a href="power-batterybroken.html" title="Greška javlja da moja baterija ima mali kapacitet">Greška javlja da moja baterija ima mali kapacitet</a></li>
<li class="links "><a href="power-othercountry.html" title="Hoće li moj računar raditi sa napajanjem u drugoj zemlji?">Hoće li moj računar raditi sa napajanjem u drugoj zemlji?</a></li>
<li class="links "><a href="power-nowireless.html" title="Ja nemam bežične mreže kada probudim moj računar">Ja nemam bežične mreže kada probudim moj računar</a></li>
<li class="links "><a href="power-willnotturnon.html" title="Moj računar ne moe da se upali">Moj računar ne moe da se upali</a></li>
<li class="links "><a href="power-hotcomputer.html" title="Moj računar se jako zagrijava">Moj računar se jako zagrijava</a></li>
<li class="links "><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">Postavite osvjetljenje ekrana</a></li>
<li class="links "><a href="power-constantfan.html" title="Ventilator od laptopa uvijek radi">Ventilator od laptopa uvijek radi</a></li>
<li class="links "><a href="power-suspendfail.html" title="Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??">Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??</a></li>
</ul></div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h3><span class="title">More Information</span></h3></div>
<div class="region"><ul><li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a><span class="desc"> — <span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span>
</li>
<li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Region &amp; Language">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
