<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Štampanje</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Štampanje</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region"><div class="linkdiv "><a class="linkdiv" href="printing-inklevel.html" title="Kako mogu provjeriti količinu tinte/tonera u mom štampaču?"><span class="title">Kako mogu provjeriti količinu tinte/tonera u mom štampaču?</span><span class="linkdiv-dash"> — </span><span class="desc">Provjerite količinu tinte ili tonera u spremnicima štampača.</span></a></div></div></div></div></div>
<div id="setup" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Postavite štampač</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="printing-setup.html" title="Postavite lokalni štampač"><span class="title">Postavite lokalni štampač</span><span class="linkdiv-dash"> — </span><span class="desc">Postavite štampač koji je povezan na vaš računar.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="printing-setup-default-printer.html" title="Postavite zadani štampač"><span class="title">Postavite zadani štampač</span><span class="linkdiv-dash"> — </span><span class="desc">Izaberite štampač koji često koristite.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="paper" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Različite veličine papira i izgledi</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="printing-select.html" title="Odštampajte samo određene stranice"><span class="title">Odštampajte samo određene stranice</span><span class="linkdiv-dash"> — </span><span class="desc">Odštampajte samo određene stranice, ili samo raspon stranica.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="printing-order.html" title="Promijenite redoslijed štampanja stranica"><span class="title">Promijenite redoslijed štampanja stranica</span><span class="linkdiv-dash"> — </span><span class="desc">Razvrstaj i okreni redoslijed ispisa.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="printing-differentsize.html" title="Promijenite veličinu papira kada štampate"><span class="title">Promijenite veličinu papira kada štampate</span><span class="linkdiv-dash"> — </span><span class="desc">Štampajte dokument na drugačijoj veličini ili orijentaciji papira.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="printing-2sided.html" title="Štampajte dvostrano ili kao multi-stranice"><span class="title">Štampajte dvostrano ili kao multi-stranice</span><span class="linkdiv-dash"> — </span><span class="desc">Štampanje na obje strane papira, ili više stranica po listu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="printing-envelopes.html" title="Štampanje omotnica i naljepnica"><span class="title">Štampanje omotnica i naljepnica</span><span class="linkdiv-dash"> — </span><span class="desc">Pobrinite se da imate kovertu/labelu okrenutu u pravom smjeru i da ste izabrali odgovarajucu velicinu papira.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problemi sa štampačem</span></h2></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="printing-cancel-job.html" title="Cancel, pause or release a print job"><span class="title">Cancel, pause or release a print job</span><span class="linkdiv-dash"> — </span><span class="desc">Odustanite od ispisa na čekanju i obrišite ga iz reda.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="printing-streaks.html" title="Zašto se nalaze pruge, linije ili pogrešne boje na mojim ispisima?"><span class="title">Zašto se nalaze pruge, linije ili pogrešne boje na mojim ispisima?</span><span class="linkdiv-dash"> — </span><span class="desc">Ako su ispisi prugasti, blijedi ili im fali boje, provjerite nivo tinte ili ocistite glavu printera.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="printing-paperjam.html" title="Čišćenje zastoja papira"><span class="title">Čišćenje zastoja papira</span><span class="linkdiv-dash"> — </span><span class="desc">Kako ćete očistiti zastoj papira zavisi od toga kako je napravljen i koji je model štampača koji imate.</span></a></div></div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h3><span class="title">More Information</span></h3></div>
<div class="region"><ul><li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li></ul></div>
</div></div></div>
</div>
</div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a><span class="desc"> — <span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
