<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Postavite lokalni štampač</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="printing.html" title="Štampanje">Štampanje</a> › <a class="trail" href="printing.html#setup" title="Postavite štampač">Postavke</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Postavite lokalni štampač</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Vaš sitem može prepoznati više tipova štampača automatski jednom kada su povezani. Većina štampača je povezano USB kablom koje se treba spojiti na Vaš računar.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">You do not need to select whether you want to install network or local
  printer now. They are listed in one window.</p></div></div></div></div>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Uvjerite se da je štampač uključen.</p></li>
<li class="steps"><p class="p">Spojite stampac za vas racunar preko odgovarajuceg kabla. Mozda ce te vidjeti aktivnost na monitoru dok sistem bude trazio drajvere, i mozete biti upitani za dozvolu da se instaliraju.</p></li>
<li class="steps"><p class="p">A message will appear when the system is finished installing the
 printer. Select <span class="gui">Print Test Page</span> to print a test page, or
 <span class="gui">Options</span> to make additional changes in the printer setup.</p></li>
</ol></div></div></div>
<p class="p">Ako vaš štampač nije postavljen automatski, možete ga dodati u postavkama štampača.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikom na ikonu na desnoj strani <span class="gui">menu trake</span> i odabirom <span class="gui">Sistemske Postavke</span>.</p></li>
<li class="steps"><p class="p">Otvorite <span class="gui">Štampači</span>.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Dodaj</span> i odaberite štampač iz prozora Uređaji.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Naprijed</span> i čekajte dok se traže drajveri.</p></li>
<li class="steps"><p class="p">Ako želite možete promijeniti ime štampača, opis i lokaciju. Kada završite, kliknite <span class="gui">Primijeni</span>.</p></li>
<li class="steps"><p class="p">Sada možete odštampati testnu stranicu ili kliknuti <span class="gui">Odustani</span> da preskočite ovaj korak.</p></li>
</ol></div></div></div>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako postoji vise drajvera bit ce te upitani da izaberete drajver. Da bi koristili preporuceni kliknite Naprijed da odabir marke i modela.</p></div></div></div></div>
<p class="p">Nakon št instalirate štampač, možda ćete željeti  <span class="link"><a href="printing-setup-default-printer.html" title="Postavite zadani štampač">promijeniti vaš zadani štampač</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="printing.html#setup" title="Postavite štampač">Postavite štampač</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
