<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako mogu provjeriti količinu tinte/tonera u mom štampaču?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="printing.html" title="Štampanje">Štampanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako mogu provjeriti količinu tinte/tonera u mom štampaču?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kako provjeravate koliko je tinte ili tonera ostalo u vašem štampaču zavisi od modela i proizvođača vašeg štampača, te drajvera i programa koi su instalirani na vašem računaru.</p>
<p class="p">Neki štampači imaju ugrađen ekran za prikaz količine tinte ili drugih informacija.</p>
<p class="p">Drajveri i ostali alati za vecinu HP printera su dostupni kroz HP Linux Imaging and Printing (HPLIP) projekt. Drugi proizvodjaci mozda imaju drajvere sa slicnim osobinama.</p>
<p class="p">Drugačije, možete da instalirate programčić za provjeru i praćenje nivoa mastila. <span class="app">Inkblot</span> prikazuje stanje mastila za mnoge HP, Epson i Kenon štampače. Pogledajte da li se vaš štampač nalazi na <span class="link"><a href="http://libinklevel.sourceforge.net./#supported" title="http://libinklevel.sourceforge.net./#supported">spisku podržanih modela</a></span>. Još jedno programče za nivoe mastila za Epsonove i neke druge štampače je <span class="app">mktink</span>.</p>
<p class="p">Neki štampači još uvijek nisu sasvim podržani na Linuxu, a drugi nisu dizajnirani da izvjeste o količini tinte.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="printing.html" title="Štampanje">Štampanje</a><span class="desc"> — <span class="link"><a href="printing-setup.html" title="Postavite lokalni štampač">Lokalne postavke</a></span>, <span class="link"><a href="printing-order.html" title="Promijenite redoslijed štampanja stranica">redoslijed i slaganje</a></span>, <span class="link"><a href="printing-2sided.html" title="Štampajte dvostrano ili kao multi-stranice"> dvostrano i visestrano</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
