<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Promjenite jezik koji koristite</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-language.html" title="Region &amp; Language">Region &amp; Language</a> › <a class="trail" href="prefs-language.html#langsupport" title="Language Support">Language Support</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Promjenite jezik koji koristite</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can use your desktop and applications in any of dozens of languages, provided
  you have the proper <span class="link"><a href="prefs-language-install.html" title="Install languages">language packs
  installed</a></span> on your computer.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu koja je desno od trake izbornika i odaberite <span class="gui">Postavke Sistema</span>.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Podrška za jezik</span>.</p></li>
<li class="steps"><p class="p">Odaberite željeni jezik u <span class="gui">Jezik</span> tabu. Povucite jezik na vrh liste.</p></li>
<li class="steps"><p class="p">You have to log out and back in for language changes to take
    effect. Click the icon at the very right of the menu bar and select <span class="gui">Log Out</span>
    to log out.</p></li>
</ol></div></div></div>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">Neki prevodi mogu biti nedovršeni, i određeni programi ne moraju podržavati vaš jezik upotpunosti.</p></div></div></div></div>
<p class="p">Postoje neki posebni direktoriji u vašem ličnom direktoriju u kojima programi mogu da uskladište stvari kao što su muzika, slike i dokumenti. Ovi direktoriji koriste standardne nazive u skladu sa vašim jezikom. Kada se ponovo prijavite, bićete upitani da li želite da preimenujete te direktorije na standardne nazive za izabrani jezik. Ako planirate da koristite novi jezik svo vreme, trebali biste da ažurirate nazive direktorija.</p>
</div>
<div id="system" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Promijenite sistemski jezik</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Kada promijenite vaš jezik, promjenili ste ga samo za vaš račun na kome ste prijavljeni. Možete takođe promijeniti <span class="em">sistemski jezik</span>, jezik koji se koristi na mjestima poput ekrana za prijavu.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Promijenite vaš jezik, kako je opisano iznad.</p></li>
<li class="steps"><p class="p">Kliknite  <span class="gui">Primijeni Ssitem-Široko</span>.</p></li>
<li class="steps"><p class="p">Potrebne su <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?">Privilegije administratora</a></span>. Unesite vašu šifru, ili šifru za traženi administratorski račun.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="prefs-language.html#langsupport" title="Language Support">Language Support</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="session-formats.html" title="Promjenite formate za datum i mjerenje">Promjenite formate za datum i mjerenje</a><span class="desc"> — Izaberite regiju koja se koristi za datum i vrijeme, brojeve, valutu i mjerenje.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
