<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zaslon se prebrzo sam zaključava</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zaslon se prebrzo sam zaključava</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako ostavite vas racunar nekoliko minuta, ekran ce se automatski zakljucati i morati cete unositi sifru da ga nastavite koristiti. Ovo je napravljeno iz sigurnosnih razloga ( da se niko ne moze igrati sa vasim radom ako ostavite racunar bez nadzora) ali moze biti naporno ako se ekran zakljucava cesto.</p>
<p class="p">Da se čeka duži period prije automatskog ključanja zaslona:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na ikonu na kraju desne strane <span class="gui">meni trake</span> i odaberite <span class="gui">postavke sustava</span>.</p></li>
<li class="steps"><p class="p">Kliknite <span class="gui">Osvjetljenost i zaključavanje</span>.</p></li>
<li class="steps"><p class="p">Promjenite vrijedost u <span class="gui">Zaključaj zaslon poslije</span> iz padajućeg menija.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako ne želite da se zaslon sam automatski zaključava, isključite <span class="gui">Zaključavanje</span>.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a><span class="desc"> — <span class="link"><a href="look-background.html" title="Promijenite pozadinu">Pozadina</a></span>, <span class="link"><a href="look-resolution.html" title="Promijenite veličinu rotacije ekrana">veličina i rotacija</a></span>, <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">svjetlost</a></span>…</span>
</li>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="display-lock.html" title="Automatski zaključajte vaš ekran">Automatski zaključajte vaš ekran</a><span class="desc"> — Spriječite druge osobe da koriste radnu površinu kada odete dalje od računara.</span>
</li>
<li class="links "><a href="shell-exit.html#lock-screen" title="Zaključaj ekran">Zaključaj ekran</a></li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
