<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ne čujem nikakav zvuk na računaru</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="media.html#sound" title="Osnovni zvuk">Zvuk</a> » <a class="trail" href="sound-broken.html" title="Problemi sa zvukom">Problemi sa zvukom</a> » </div>
<div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="sound-broken.html" title="Problemi sa zvukom">Problemi sa zvukom</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ne čujem nikakav zvuk na računaru</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Ako ne čujete nikakav zvuk na vašem računaru, na primjer kada pokušavate reproducirati muziku, pokušajte ove korake za rješavanje problema da vidite ad li možete riješiti vaš problem.</p></div>
<div id="mute" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Uvjerite se da zvuk nije isključen</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Kliknite <span class="gui">zvuk meni</span> na traci menija (izgleda kao zvučnik) i uvjerite se da zvuk nije isključen ili smanjen.</p>
<p class="p">Neki laptopi imaju prekidace ili tipke za ukidanje zvuka na njihovim tastaturama- probajte pritisnuti da vidite da li se stisao zvuk.</p>
<p class="p">You should also check that you haven't muted the application that you're
 using to play sound (e.g. your music player or movie player). The application
 may have a mute or volume button in its main window, so check that. Also, click
 the sound menu on the menu bar and choose <span class="gui">Sound Settings</span>. When the
 <span class="gui">Sound</span> window appears, go to the <span class="gui">Applications</span> tab and
 check that your application is not muted.</p>
</div></div>
</div></div>
<div id="speakers" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite jesu li zvučnici uključen i spojeni pravilno</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako vaš računar ima spoljne zvučnike, uvjerite se da su upaljeni i da je jačina zvuka pojačana. Uverite se da je kabal zvučnika bezbedno priključen u „izlaznu“ priključnicu zvuka na poleđini računara. Ova priključnica je obično svijetlo-zelene boje.</p>
<p class="p">Neke zvučne kartice imaju mogućnost da prebace priključnicu koju koriste za izlaz (na zvučnike) i ulaz (iz mikrofona, na primer). Izlazna priključnica može biti drugačija kada radi pod Linuksom nego kada radi pod Vindouzom ili Mek OS-om. Pokušajte na smenu da povežete kabal zvučnika na drugu zvučnu priključnicu na računaru da vidite da li će da radi.</p>
<p class="p">Konačno, provjerite da li je audio kabl čvrsto priključen na pozadini zvučnika. Takođe neki zvučnici imaju više od jednog ulaza.</p>
</div></div>
</div></div>
<div id="device" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite da li je odabran pravi zvučni uređaj</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Neki računari ima vištruke "zvučne uređaje" instalirane. Neki od njih su u mogućnosti da daju zvuk a neki nisu, trebate provjeriti da imate ispavan uređaj instaliran. Ovo može ulljučite neke pokušaje-i-greške da izaberete ispravan uređaj.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui">zvučni meni</span> u <span class="gui">meni bar</span> i kliknite <span class="gui">Postavke zvuka</span>.</p></li>
<li class="steps"><p class="p">U <span class="gui">Zvuk</span> prozoru koji se pojavio, pokušajte označiti druge izlaze iz liste <span class="gui">Reproduciraj zvuk kroz</span>.</p></li>
<li class="steps"><p class="p">Za izabrani uredjaj, pritisnite <span class="gui">Test Sound</span>. u iskacucem prozoru, kliknite dugme za svaki zvucnik. Svako dugme ce otkriti svoju poziciju samo kanalu tog zvucnika.</p></li>
<li class="steps"><p class="p">Ako to ne radi, možda želite pokušati uraditi isto za neki drugi uređaj koji je naveden.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="hardware-detected" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Provjerite da li je pravilno otkrivena zvučna kartica</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Vasa zvucna kartica nije detektovana ispravno. Ako se ovo desilo, vas racunar ce misliti da nije u mogucnosti reproducirati zvuk. Moguci razlog tome je da drajveri za tu zvucnu karticu nisu instalirani.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Go to the <span class="link"><a href="unity-dash-intro.html" title="Find apps, files, music, and more with the Dash">Dash</a></span> and open the Terminal.</p></li>
<li class="steps"><p class="p">Ukucajte <span class="cmd">aplay -l</span> i pritisnite <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps"><p class="p">Lista uređaja će biti prikazana. Ako nema <span class="gui">playback hardware devices</span>, Vaša zvučna karta nije detektovana.</p></li>
</ol></div></div></div>
<p class="p">Ako zvučna kartica nije pronađena, možda ćete morati ručno instalirati drajvere za nju. Kako ćete to uraditi, zavisi od kartice koju imate.</p>
<p class="p">You can see what sound card you have by using the <span class="cmd">lspci</span> command
 in the <span class="app">Terminal</span>. You can get more complete results if you run <span class="cmd">lspci</span> as
 <span class="link"><a href="user-admin-explain.html" title="Kako funkcionišu administrativne privilegije?">superuser</a></span>; enter <span class="cmd">sudo lspci</span>
 and type your password. See if an
 <span class="em">audio controller</span> or <span class="em">audio device</span> is listed—it should have the
 sound card's make and model number. <span class="cmd">sudo lspci -v</span> will show a list with
 more detailed information.</p>
<p class="p">You may be able to find and install drivers for your card by searching the Internet. Otherwise, you can <span class="link"><a href="report-ubuntu-bug.html" title="Prijavite problem u Ubuntu-u">file a bug</a></span>.</p>
<p class="p">Ako ne mozete naci drajvere za vasu zvucnu karticu, mozda ce te htjeti novu zvucnu karticu, Mozete nabaviti kartice koje se postavljaju unutar racunara ili eksterne USB zvucne kartice.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="sound-broken.html" title="Problemi sa zvukom">Problemi sa zvukom</a><span class="desc"> — Uklonite probleme poput onih da nemate zvuka ili je kvalitet zvula loš.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
