<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Koristite drugi mikrofon</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="media.html#sound" title="Osnovni zvuk">Zvuk</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Koristite drugi mikrofon</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Mozete koristiti eksterni mikrofon za razgovor sa vasim prijateljima, razgovor sa kolegama na poslu, snimanjem govornih poruka ili koristenje ostalih multimedijalnih aplikacija. Iako vas racunar ima ugradjeni mikrofon ili kameru sa mikrofonom, odvojeni mikrofon ce pruziti bolji kvalitet zvuka.</p>
<p class="p">Ako vaš mikrofon ima kružni priključak, samo ga priključite u odgovarajći prilagođivač na vašem računaru. Većina računara ima dva prilagođivača: jedan za mikrofone a drugi za zvučnike. Potražite sliku mikrofona pored prilagođivača. Mikrofoni priključeni na odgovarajući prilagođivač će obično biti korišćeni uobičajeno. Ako ne, pogledajte uputstva ispod za izbor osnovnog ulaznog uređaja.</p>
<p class="p">Ako imate USB mikrofon, ukljucite ga u bilo koji USB port na vasem racunaru. USB mikrofoni se ponasaju kao odvojeni audio uredjaji, tako da morate navesti koji mikrofon zelite koristiti-</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Odaberite zadani ulazni audio uređaj</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui">zvuk meni</span> na <span class="gui">traci menija</span> i odaberite <span class="gui">Podešavanja zvuka</span>.</p></li>
<li class="steps"><p class="p">Na <span class="gui">Input</span> tabulatoru, izaberite uređaj sa liste uređaja. Indikator ulazne razine bi trebao da reaguje kada pričate.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="media.html#sound" title="Osnovni zvuk">Osnovni zvuk</a><span class="desc"> — <span class="link"><a href="sound-volume.html" title="Promjenite jačinu zvuka">Jačina</a></span>, <span class="link"><a href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice.">zvučnici i slušaliceheadphones</a></span>, <span class="link"><a href="sound-usemic.html" title="Koristite drugi mikrofon">mikrofoni</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice.">Koristite različite zvučnike i slušalice.</a><span class="desc"> — Spojite zvučnike ili slušalice i odaberite zadani izlazni audio uređaj.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
