<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako funkcionišu administrativne privilegije?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#privileges" title="Korisničke privilegije.">Privilegije.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako funkcionišu administrativne privilegije?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kao i datoteke koje <span class="em">vi</span> napravite, vaš računar sadrži brojne datoteke koje su potrebne sistemu da bi ispravno radio. Ako su ove važne <span class="em">sistemske datoteke</span> izmenjene na neodgovarajući način mogle bi da izazovu loš rad mnogih stvari, tako da su u osnovi zaštićene od izmjena. Određeni programi takođe menjaju važne dijelove sistema, tako da su i od ovoga zaštićene.</p>
<p class="p">Način na koji su one zaštićene je taj sto dozvoljavalju samo korisnicima sa <span class="em">administrativnim privilegijama</span> da mijenjaju datoteke ili da koriste aplikacije. U svakodnevnoj upotrebi,Vi nećete imati potrebu da mijenjate sistemske datoteke ili da koristite ove aplikacije,pa po defaultu nemate administrativne privilegije.</p>
<p class="p">Ponekad ćete morati da koristite ove programe, tako da ćete moći privremeno da dobijete administratorska ovlašćenja koja će vam omogućiti da napravite izmene. Ako neki program zahteva administratorska ovlašćenja, od vas će zatražiti vašu lozinku. Na primer, ako želite da instalirate neke nove programe, program za instalaciju (upravnik paketa) će od vas zatražiti administratorsku lozinku kako bi sistemu mogao da doda nove programe. Kada bude završio, biće vam ponovo oduzeta administratorska ovlašćenja.</p>
<p class="p">Administratorske privilegije su povezane sa vašim korisničkim nalogom. Nekim korisnicima je dozvoljeno da imaju administratorska prava a nekima nije. Bez administratorskih ovlašćenja nećete biti u mogućnosti da instalirate programe. Neki korisnički nalozi (na primer, „administratorski“ nalog) imaju stalna administratorska ovlašćenja. Ne možete da koristite administratorska ovlašćenja čitavo vreme, zato što biste mogli slučajno da izmijenite nešto što niste nameravali (da obrišete potrebnu sistemsku datoteku, na primer).</p>
<p class="p">Ukratko, admin privilegije omogućavaju vam da mijenjate važne dijelove vašeg sistema kada je to potrebno, ali sprječavaju da to radite slučajno.</p>
<div class="note" title="Note"><div class="inner">
<div class="title title-note"><h2><span class="title">Šta znač super korisnik?</span></h2></div>
<div class="region"><div class="contents"><p class="p">Korisnik sa administrativnim privilegijama se naziva <span class="em">super korisnik</span>. Ovo je čisto iz razloga što ovakav korisnik ima više privilegija nego normalni korisnik. Mozete sresti ljude koji diskutuju od stvarima poput <span class="cmd">su</span> and <span class="cmd">sudo</span>; ovo su programi koji vam daju ''super korisničke''(administrativne) privilegije.</p></div></div>
</div></div>
</div>
<div id="advantages" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Za što su korisne administrativne privilegije?</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Od korisnika se zahtijeva da imaju administrativne privilegije prije nego što se naprave vazne sistemske izmjene sto je korisno da Vas spriječi da pokvarite Vas sistem,namjerno ili slučajno.</p>
<p class="p">Ako imate administratorske privilegije stalno.možete slučajno izmijeniti važnu datoteku,ili pokrenuti aplikaciju koja mijenja nesto vazno greskom. Samo dobijanje administratorskih privilegija privremeno, kada su Vam stvarno potrebne, smanjuje rizik mogućih grešaka.</p>
<p class="p">Samo određeni poverljivi korisnici bi trebali da imaju administratorska ovlašćenja. Ovo sprječava druge korisnike da nanesu štetu računaru i da uklone programe koji vam trebaju, da instaliraju programe koji vam ne trebaju, ili da izmene važne datoteke. Ovo je korisno sa bezbjednosne tačke gledišta.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#privileges" title="Korisničke privilegije.">Korisničke privilegije.</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="user-admin-change.html" title="Mijenjajte(promijenite) ko ima administrativne privilegije">Mijenjajte(promijenite) ko ima administrativne privilegije</a><span class="desc"> — Možete mijenjati koji korisnici mogu praviti promjene na vašem sistemu dajući administrativne privilegije.</span>
</li>
<li class="links ">
<a href="net-othersedit.html" title="Ostali korisnici ne mogu uređivati mrežne konekcije">Ostali korisnici ne mogu uređivati mrežne konekcije</a><span class="desc"> — Trebate isključiti <span class="gui">Dostupno svim korisnicima</span> mogućnost u podešavanjima mrežne oknekcje.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
