<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Odaberite sigurne šifre.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#passwords" title="Šifre">Šifre</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Odaberite sigurne šifre.</span></h1></div>
<div class="region">
<div class="contents">
<div class="note note-important" title="Important"><div class="inner"><div class="region"><div class="contents"><p class="p">Neka Vase šifre budu dovoljno lahke da ih zapamtite,ali veoma teške za druge (uključujući računarske programe) da pogode.</p></div></div></div></div>
<p class="p">Odabiranje dobrih šiifri ce Vam pomoći da Vas  računar bude siguran. Ako su vaše sifre lagane za pogoditi, neko je možze odgonetnuti i dobiti pristup Vašim ličnim informacijama.</p>
<p class="p">Ljudi mogu čak koristiti racunare da sistematski pokušaju odgonetnuti Vasu sifru, pa čak i ako je tečko za čovjeka da pogodi Vasu sifru,ipak za računarski program to može biti ekstremno lahko. Ovo su neki savjeti za odabir dobre šifre:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list">
<p class="p">
        Use a mixture of upper-case and lower-case letters, numbers, symbols, 
        and spaces in the password. This makes it more difficult to guess. There 
        are more symbols to choose from, so more possible passwords would have 
        to be checked by someone when trying to guess yours.
      </p>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">
          A good method for choosing a password is to take the first letter of 
          each word in a phrase that you can remember. The phrase could be the 
          name of a movie, a book, a song, or an album. For example, "Flatland: 
          A Romance of Many Dimensions" would become F:ARoMD or faromd or f: 
          aromd.
        </p></div></div></div></div>
</li>
<li class="list"><p class="p">Neka Vasa šifra bude sto je moguce duža. Sto više znakova posjeduje, potrebno je više vremena osobi ili računaru da je pogodi.</p></li>
<li class="list"><p class="p">Ne koristite nijednu riječ koja se nalazi u rečnicima ili u nekom jeziku. Lozinkolomci će prvo njih isprobati. Najčešća lozinka je „password“ —— ovakvu lozinku će svako za čas da pogodi!</p></li>
<li class="list"><p class="p">
        Do not use any personal information, such as a date, license plate 
        number, or any family member's name.
      </p></li>
<li class="list"><p class="p">Ne koristite imenice.</p></li>
<li class="list">
<p class="p">
        Choose a password that can be typed quickly, to reduce the chance of 
        someone being able to make out what you have typed if they happen to be 
        watching you.
      </p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">
          Never write your passwords down anywhere. They can be found!
        </p></div></div></div></div>
</li>
<li class="list"><p class="p">Koristite različite šifre za različite stvari.</p></li>
<li class="list">
<p class="p">Koristite različite šifre za različite korisničke naloge.</p>
<p class="p">Ako koristite iste šifre za sve vaše naloge, bili tko ko pogodi bit će u mogućnosti da pristupi svim Vašim nalozima.</p>
<p class="p">
        It can be difficult to remember lots of passwords. Though not as secure 
        as using a different passwords for everything, it may be easier to use 
        the same one for things that don't matter (like websites), and different 
        ones for important things (like your online banking account and your 
        email).
      </p>
</li>
<li class="list"><p class="p">Mijenjajte Vašu šifru redovno.</p></li>
</ul></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#passwords" title="Šifre">Šifre</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="user-changepassword.html" title="Promijenite(mijenjajte) Vašu šifru.">Promijenite(mijenjajte) Vašu šifru.</a><span class="desc"> — Čuvajte Vas racun sigurnim čestim mijenjanjem sifre u vašim računskim postavkama.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
