<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kako da omogućim ograničene kodeke da pokrenu DVD-ve?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<a href="../../14.04" class="trail">Ubuntu 14.04</a> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#videos" title="Video i video kamere">Video</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kako da omogućim ograničene kodeke da pokrenu DVD-ve?</span></h1></div>
<div class="region">
<div class="contents"><p class="p">DVD podrska ne može biti osigurana po defaultu u Ubuntuu zbog pravničkih i tehničkih zabrana. Većna komercijalni DVD-va su zaštićeni i zahtijevaju programe za dešifrovanje da biste ih pokrenuli.</p></div>
<div id="fluendo" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Koristite Fluendo da zakonski pokrenete DVD-ve.</span></h2></div>
<div class="region"><div class="contents"><p class="p">Možete kupiti komercijalni DVD dekoder koji moze riješiti zaštitu od kopiranja preko <span class="link"><a href="https://apps.ubuntu.com/cat/applications/fluendo-dvd" title="https://apps.ubuntu.com/cat/applications/fluendo-dvd">Fluendo</a></span>. On radi s Linuxom i trebao bi biti legalan za upotrebu u svim zemljama.</p></div></div>
</div></div>
<div id="restricted" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Koristite alternativne programe za dešifriranje.</span></h2></div>
<div class="region"><div class="contents">
<div class="note note-warning" title="Warning"><div class="inner"><div class="region"><div class="contents"><p class="p">U odredjenim zemljama, korištenje dole navedenih nelicenciranih programa za dešifrovanje nije dozvoljeno zakonom. Potvrdite da ste unutar svojih prava da ih koristite.</p></div></div></div></div>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Instalirajte <span class="link"><a href="https://apps.ubuntu.com/cat/applications/libdvdnav4" title="https://apps.ubuntu.com/cat/applications/libdvdnav4">libdvdnav4</a></span>, <span class="link"><a href="https://apps.ubuntu.com/cat/applications/libdvdread4" title="https://apps.ubuntu.com/cat/applications/libdvdread4">libdvdread4</a></span>, <span class="link"><a href="https://apps.ubuntu.com/cat/applications/gstreamer0.10-plugins-bad" title="https://apps.ubuntu.com/cat/applications/gstreamer0.10-plugins-bad">gstreamer0.10-plugins-bad</a></span>, and <span class="link"><a href="https://apps.ubuntu.com/cat/applications/gstreamer0.10-plugins-ugly" title="https://apps.ubuntu.com/cat/applications/gstreamer0.10-plugins-ugly">gstreamer0.10-plugins-ugly</a></span>.</p></li>
<li class="steps"><p class="p">Ako želite pokrenuti šifrirane DVD-ve (pogledajte pravnu zabilješku gore), otvorite Dash i pokrenite <span class="app">Terminal</span>.</p></li>
<li class="steps">
<p class="p">Ukucajte sljedeće u ekran koji se pojavio,zatim pritisnite <span class="key"><kbd>Enter</kbd></span>:</p>
<p class="p"><span class="code">sudo /usr/share/doc/libdvdread4/install-css.sh</span></p>
</li>
<li class="steps"><p class="p">Unesite Vašu šifru da biste dovršili instalaciju.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#videos" title="Video i video kamere">Video</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="video-dvd.html" title="Zašto DVD ne radi?">Zašto DVD ne radi?</a><span class="desc"> — Možda nemate instalirane odgovarajuće kodeke, ili je DVD iz pogrešnog regiona.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
