<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zapnutie lepkavých kláves</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="keyboard.html" title="Klávesnica">Klávesnica</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="a11y.html" title="Bezbariérový prístup">Bezbariérový prístup</a> › <a class="trail" href="a11y.html#mobility" title="Pohybové postihnutie">Pohybové postihnutie</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="keyboard.html" title="Klávesnica">Klávesnica</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zapnutie lepkavých kláves</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Funkcia <span class="em">Lepkavé klávesy</span> umožňuje zadávať klávesové skratky po jednom klávese namiesto toho aby sme držali všetky klávesy naraz. Napríklad klávesovú skratku <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>Tab</kbd></span></span> na prepínanie okien bez zapnutej funkcie lepivé klávesy musíme držať naraz, no so zapnutou funkciou najskôr stlačíme <span class="key"><kbd>Alt</kbd></span>, a potom <span class="key"><kbd>Tab</kbd></span>.</p>
<p class="p">Funkciu lepivé klávesy môžeme zapnúť, ak sa nám zdá ťažké držať niektoré klávesy naraz.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and
      select <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">Klikneme na <span class="gui">Bezbariérový prístup</span> a prepneme sa na kartu <span class="gui">Písanie</span>.</p></li>
<li class="steps"><p class="p">Zapneme <span class="gui">Lepkavé klávesy</span>.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner">
<div class="title title-note"><h2><span class="title">Rýchlo zapnúť alebo vypnúť lepkavé klávesy</span></h2></div>
<div class="region"><div class="contents"><p class="p">
      Under <span class="gui">Enable by Keyboard</span>, select <span class="gui">Turn on accessibility 
      features from the keyboard</span> to turn sticky keys on and off from the 
      keyboard. When this option is selected, you can press <span class="key"><kbd>Shift</kbd></span> 
      five times in a row to enable or disable sticky keys.
    </p></div></div>
</div></div>
<p class="p">
    If you press two keys at once, you can have sticky keys turn itself off 
    temporarily to let you enter a keyboard shortcut in the normal way.
  </p>
<p class="p">Ak napríklad máme zapnuté lepivé klávesy s touto funkciou a stlačíme naraz <span class="key"><kbd>Alt</kbd></span> a <span class="key"><kbd>Tab</kbd></span>, lepkavé klávesy nebudú čakať, kým stlačíme ďalší kláves. <span class="em">Budú</span> čakať iba ak stlačíme jeden kláves. Toto je užitočné, ak sme niektoré klávesové skratky schopní stlačiť naraz (napríklad klávesy, ktoré sú blízko pri sebe) a iné zasa nie.</p>
<p class="p">Ak to správanie chceme povoliť, zaškrtneme <span class="gui">Zakázať ak sú stlačené dva klávesy naraz</span>.</p>
<p class="p">Môžeme nastaviť, aby počítač „pípol“ keď začneme písať klávesovú skratku so zapnutými lepkavými klávesmi. Toto je užitočné ak chceme vedieť, že sa očakáva lepivý kláves, takže ďalšie stlačenie klávesu sa bude interpretovať ako súčasť klávesovej skratky. Toto správanie povolím zaškrtnutím voľby <span class="gui">Pípnuť pri stlačení modifikátora</span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard.html" title="Klávesnica">Klávesnica</a><span class="desc"> — 
      <span class="link"><a href="keyboard-layouts.html" title="Use alternative input sources">Input sources</a></span>,
      <span class="link"><a href="keyboard-cursor-blink.html" title="Blikanie kurzora klávesnice">cursor blinking</a></span>,
      <span class="link"><a href="windows-key.html" title='What is the "Super" key?'>super key</a></span>,
      <span class="link"><a href="a11y.html#mobility" title="Pohybové postihnutie">keyboard accessibility</a></span>…
    </span>
</li>
<li class="links "><a href="a11y.html#mobility" title="Pohybové postihnutie">Pohybové postihnutie</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
