<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>O tejto príručke</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="more-help.html" title="Získať ďalšiu pomoc">Získať ďalšiu pomoc</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">O tejto príručke</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Tento sprievodca vám poskytne prehliadku schopnosťami vášho pracovného prostredia, zodpovie vaše otázky týkajúce sa počítača a poskytne rady, ako používať váš počítač efektívnejšie.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">
        The guide is divided into small, task-oriented topics - not chapters. 
        This means that you don't need to skim through an entire manual to find 
        answers to your questions.
      </p></li>
<li class="list"><p class="p">
        Related items are linked together. "See Also" links at the bottom of 
        some pages direct you to related topics.
      </p></li>
<li class="list"><p class="p">
        The text input box at the top of this guide acts as a <span class="em">search 
        bar</span>, and relevant results will appear beneath it as soon as you 
        start typing. Left-click on any result to open its page.
      </p></li>
<li class="list"><p class="p">
        The guide is constantly being improved. Although we attempt to provide 
        you with a comprehensive collection of helpful information, we know we 
        won't answer all of your questions here. We will keep adding more 
        information to make things more helpful, though.
      </p></li>
</ul></div></div></div>
<p class="p">Ďakujeme, že ste si urobili čas na prečítanie <span class="em">príručky pre Ubuntu Desktop</span>.</p>
<p class="p">
    -- The Ubuntu Documentation team
  </p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="more-help.html" title="Získať ďalšiu pomoc">Získať ďalšiu pomoc</a><span class="desc"> — <span class="link"><a href="about-this-guide.html" title="O tejto príručke">Tipy o používaní tejto proručky</a></span>, <span class="link"><a href="get-involved.html" title="Podieľajte sa na zlepšení tejto príručky">pomôžte túto príručku zlepšiť</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="unity-introduction.html" title="Welcome to Ubuntu">Welcome to Ubuntu</a><span class="desc"> — Úvod do vizuálneho Unity desktopu.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
