<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Online računi</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Online računi</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete pristupiti vašim detaljima za prijavu na internet servise, kao što su Google i Facebook, preko aplikacije <span class="app">Online Accounts</span> aplikacije. Ovo vam omogućava pristup kalendaru, pošti, računima za dopisivanje i sličnim aplikacijama bez ponovnog unošenja vaših detalja za prijavu.</p>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="accounts-add.html" title="Dodaj korisnički nalog"><span class="title">Dodaj korisnički nalog</span><span class="linkdiv-dash"> — </span><span class="desc">Poveži se sa internet računima</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="accounts-disable-service.html" title="Isključi korisničke usluge"><span class="title">Isključi korisničke usluge</span><span class="linkdiv-dash"> — </span><span class="desc">Neki internet računi dozvoljavaju vam da koristite više servisa (kao kalendar i internet poštu). Koje servise želite koristiti možete podešavati preko lokalnih aplikacija.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="accounts-remove.html" title="Izbrišite račun"><span class="title">Izbrišite račun</span><span class="linkdiv-dash"> — </span><span class="desc">Uklonite usluge za online korisničke račune</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="accounts-which-application.html" title="Koje aplikacije koriste prednost internet računa?"><span class="title">Koje aplikacije koriste prednost internet računa?</span><span class="linkdiv-dash"> — </span><span class="desc">Aplikacije i servisi koje aplikacije koriste, mogu koristiti račune kreirane u  <span class="app">Internet Računi</span>.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="accounts-provider-not-available.html" title="Zašto moj tip korisničkog računa nije na spisku?"><span class="title">Zašto moj tip korisničkog računa nije na spisku?</span><span class="linkdiv-dash"> — </span><span class="desc">Zašto nisu provajderi servisa navedeni?</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="accounts-whyadd.html" title="Žašto bih trebao/la dodati račun?"><span class="title">Žašto bih trebao/la dodati račun?</span><span class="linkdiv-dash"> — </span><span class="desc">Zašto dodati svoj email ili račun društvenih medija na desktop?</span></a></div>
</div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
