<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Povežite vaš računar sa Bluetooth uređajem</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="bluetooth.html" title="Bluetooth">Bluetooth</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Povežite vaš računar sa Bluetooth uređajem</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Prije nego što možete korisiti Bluetooth uređaje kao što je miš ili slušalice, prvo morate spojiti računar na uređaj. Ovo se još zove uparivanje Bluetooth uređaja.</p>
<div class="note note-important" title="Važna"><div class="inner"><div class="region"><div class="contents"><p class="p">Prije nego što počnete, budite sigurni da je Bluetooth omogućen na vašem računaru. Vidi <span class="link"><a href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite">Uključite Bluetooth ili isključite</a></span>.</p></div></div></div></div>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite na Bluetooth ikonu na izborniku i odaberite  <span class="gui">Postavi novi uređaj</span>.</p></li>
<li class="steps"><p class="p">Učinite drugi Bluetooth uređaj <span class="link"><a href="bluetooth-visibility.html" title="Šta je vidljivost Bluetooth-a?">otkrivenim ili vidljivim</a></span>  i postavite ga u krugu od 10 metara (oko 33 stope) od vašeg računara. Kliknite <span class="gui"> Nastavi</span>. Vaš računar će početi da traži uređaje.</p></li>
<li class="steps"><p class="p">Ako ima mnogo navedenih uređaja, koristite  <span class="gui">Tip uređaja</span> padajući meni da prikažete samo po jednu vrstu uređaja u listi.</p></li>
<li class="steps">
<p class="p">Kliknite <span class="gui">PIN opcije</span> da postavite kako će PIN biti dostavljen drugim uređajima.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Automatsko postavljanje PIN-a će koristiti šest-znamenkasti numerički kod. Uređaj bez tipki ili zaslona, kao što su miš ili slušalice, mogu zahtijevati određeni PIN, kao što je 0000, ili nikakav PIN. Provjerite priručnik vašeg uređaj za pravilno postavljanje.</p></div></div></div></div>
<p class="p">Odaberite odgovarajuće PIN postavke za uređaj i onda kliknite <span class="gui">Zatvori</span>.</p>
</li>
<li class="steps"><p class="p">Kliknite  <span class="gui">Nastaviti</span> za nastavak. Ako niste odabrali unaprijed PIN, PIN će se prikazati na zaslonu.</p></li>
<li class="steps">
<p class="p">Ako je potrebno, potvrdite PIN na vašem drugom uređaju. Uređaj bi trebao prikazati PIN koji vidite na zaslonu računara, ili će možda tražiti da unesete PIN. Potvrdite PIN na uređaju, a zatim kliknite <span class="gui"> Upari</span>.</p>
<p class="p">Morate završiti svoj ulazak u roku od oko 20 sekundi na većini uređaja, ili veze neće biti dovršena. Ako se to dogodi, vratite se na popis uređaja i počnite ponovo.</p>
</li>
<li class="steps"><p class="p">Poruka se pojavljuje kada se veza uspješno završi. Kliknite zatvori.</p></li>
</ol></div></div></div>
<p class="p">Možete <span class="link"><a href="bluetooth-remove-connection.html" title="Uklonite vezu između Bluetooth uređaja"> ukloniti Bluetooth vezu  </a></span> kasnije, ako to želite.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Da biste kontrolisali pristup vašim podijeljenim fajlovima, pristupite  <span class="gui">Dijeljenje preko bluetooth</span> postavkama. Pogledajte <span class="link"><a href="sharing-bluetooth.html" title="Kontrola dijeljenja preko Bluetooth-a">Kontrola dijeljenja preko Bluetooth-a</a></span>.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="bluetooth.html" title="Bluetooth">Bluetooth</a><span class="desc"> — <span class="link"><a href="bluetooth-connect-device.html" title="Povežite vaš računar sa Bluetooth uređajem">Spojiti</a></span>, <span class="link"><a href="bluetooth-send-file.html" title="Pošalji datoteku Bluetooth uređaju"> slanje datoteka</a></span>, <span class="link"><a href="bluetooth-turn-on-off.html" title="Uključite Bluetooth ili isključite"> uključivanje i isključivanje</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="sharing-bluetooth.html" title="Kontrola dijeljenja preko Bluetooth-a">Kontrola dijeljenja preko Bluetooth-a</a><span class="desc"> — Opcije dijeljenja i primanja datoteka preko Bluetooth-a.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
