<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zašto moram kalibraciju uraditi ja sama?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#calibration" title="Kalibracija">Kalibracija</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#calibration" title="Kalibracija">Kalibracija</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zašto moram kalibraciju uraditi ja sama?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Generički profili su obično loši. Kada proizvođač stvara novi model, uzme samo nekoliko predmeta iz proizvodne linije te ih uprosječi zajedno:</p>
<div class="media media-image"><div class="inner"><img src="figures/color-average.png" class="media media-block" alt="Prosječni profili"></div></div>
<p class="p">Prikazne ploče se razlikuju dosta od jedinice do jedinice i promijene se bitno kako ekran stari. Također je teže za printere jer samo mijenjanje vrste ili težine papira može izgubiti karakterizaciju stanja i napraviti profil netačnim.</p>
<p class="p">Najbolji način da se osigura da je profil koji imate tačan, je da uradite kalibraciju sami, ili da dopustite da vas vanjske firme opskrbe s profilom temeljnim na vašoj tačnoj karakterizaciji stanja.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#calibration" title="Kalibracija">Kalibracija</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="color-gettingprofiles.html" title="Gdje mogu dobiti profile boja?">Gdje mogu dobiti profile boja?</a><span class="desc"> — Profili boja osiguravaju dobavljači od prodavača i možete ih generirati.</span>
</li>
<li class="links ">
<a href="color-assignprofiles.html" title="Kako dodijeliti profile na uređaje?">Kako dodijeliti profile na uređaje?</a><span class="desc"> — Pogledajte u <span class="guiseq"><span class="gui"> Postavke sistema </span> ▸ <span class="gui"> Boja </span></span> za mogućnost da se to promijeni.</span>
</li>
<li class="links ">
<a href="color-notifications.html" title="Mogu li biti obaviješten kada mi je profil za boje netačan?">Mogu li biti obaviješten kada mi je profil za boje netačan?</a><span class="desc"> — Možete biti obaviješteni ukoliko je vaš profil za boje star i netačan.</span>
</li>
<li class="links ">
<a href="color-virtualdevice.html" title="Što je virtuelni upravljan bojama uređaj?">Što je virtuelni upravljan bojama uređaj?</a><span class="desc"> — Virtuelni uređaj je uređaj upravljanja boja koji nije povezan sa računarom.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
