<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Správa farieb</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Správa farieb</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="color-whyimportant.html" title="Prečo je správa farieb dôležitá"><span class="title">Prečo je správa farieb dôležitá</span><span class="linkdiv-dash"> — </span><span class="desc">Správa farieb je dôležitá pre návrhárov, fotografov a umelcov.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-assignprofiles.html" title="Priradenie profilov k zariadeniam"><span class="title">Priradenie profilov k zariadeniam</span><span class="linkdiv-dash"> — </span><span class="desc">Zmena nastavení pomocou <span class="guiseq"><span class="gui">Nastavenia systému</span> ▸ <span class="gui">Farby</span></span>.</span></a></div>
</div></div></div></div>
<div id="profiles" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Profily farieb</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-howtoimport.html" title="Importovanie profilov farieb"><span class="title">Importovanie profilov farieb</span><span class="linkdiv-dash"> — </span><span class="desc">Color profiles can be imported by opening them.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-virtualdevice.html" title="Virtuálne zariadenie so správou farieb"><span class="title">Virtuálne zariadenie so správou farieb</span><span class="linkdiv-dash"> — </span><span class="desc">Virtuálne zariadenie je zariadenie so správou farieb, ktoré nie je pripojené k počítaču.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-gettingprofiles.html" title="Získanie farebných profilov"><span class="title">Získanie farebných profilov</span><span class="linkdiv-dash"> — </span><span class="desc">Profily farieb sú poskytované výrobcami a môžeme si ich vygenerovať i sami.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-whatisspace.html" title="Čo je farebný priestor"><span class="title">Čo je farebný priestor</span><span class="linkdiv-dash"> — </span><span class="desc">Priestor farieb je definovaný rozsah farieb.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-whatisprofile.html" title="Čo je profil farieb"><span class="title">Čo je profil farieb</span><span class="linkdiv-dash"> — </span><span class="desc">Profil farieb je súbor, ktorý definuje farebný priestor alebo farebnú odozvu.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="calibration" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kalibrácia</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-camera.html" title="Kalibrovanie fotoaparátu"><span class="title">Kalibrovanie fotoaparátu</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrácia fotoaparátu je dôležitá pre verné zobrazenie farieb.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-scanner.html" title="Kalibrovanie skenera"><span class="title">Kalibrovanie skenera</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrovanie skenera je dôležité kvôli vernému zachyteniu farieb.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-printer.html" title="Kalibrovanie tlačiarne"><span class="title">Kalibrovanie tlačiarne</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrácia tlačiarne je dôležitá pre vernú tlač farieb.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrate-screen.html" title="Kalibrozvanie obrazovky"><span class="title">Kalibrozvanie obrazovky</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrovanie obrazovky je dôležité kvôli vernému zobrazeniu farieb.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-canshareprofiles.html" title="Podelenie sa o profil farieb"><span class="title">Podelenie sa o profil farieb</span><span class="linkdiv-dash"> — </span><span class="desc">Sharing color profiles is never a good idea as hardware changes over time.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-calibrationdevices.html" title="Podporované meracie nástroje"><span class="title">Podporované meracie nástroje</span><span class="linkdiv-dash"> — </span><span class="desc">We support a large number of calibration devices.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrationtargets.html" title="Podporované typy cieľov"><span class="title">Podporované typy cieľov</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibračné ciele potrebné pre vytvorenie profilu skenera a fotoaparátu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-calibrationcharacterization.html" title="Rozdiel medzi kalibráciou a charakterizáciou"><span class="title">Rozdiel medzi kalibráciou a charakterizáciou</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrácia a charakterizácia sú dve rozličné veci.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-why-calibrate.html" title="Vlastnoručná kalibrácia"><span class="title">Vlastnoručná kalibrácia</span><span class="linkdiv-dash"> — </span><span class="desc">Kalibrovanie je dôležité ak nám záleží na vernom zobrazení alebo tlačení farieb.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="problems" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Problémy</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-notifications.html" title="Can I get notified when my color profile is inaccurate?"><span class="title">Can I get notified when my color profile is inaccurate?</span><span class="linkdiv-dash"> — </span><span class="desc">
      You can be notified if your color profile is old and inaccurate.
    </span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-missingvcgt.html" title="Chýbajúce informácie o celoobrazovej korekcii farieb"><span class="title">Chýbajúce informácie o celoobrazovej korekcii farieb</span><span class="linkdiv-dash"> — </span><span class="desc">Celoobrazová korekcia farieb upravuje farby na celej obrazovke vo všetkých oknách.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="color-testing.html" title="How do I test if color management is working correctly?"><span class="title">How do I test if color management is working correctly?</span><span class="linkdiv-dash"> — </span><span class="desc">
      Testing color management isn't hard, and we even supply some test 
      profiles.
    </span></a></div>
<div class="linkdiv "><a class="linkdiv" href="color-notspecifiededid.html" title="Why don't the default monitor profiles have a calibration expiry?"><span class="title">Why don't the default monitor profiles have a calibration expiry?</span><span class="linkdiv-dash"> — </span><span class="desc">
      Default monitor profiles do not have a calibration date.
    </span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware.html" title="Hardvér a ovládače">Hardvér a ovládače</a><span class="desc"> — 
      <span class="link"><a href="hardware.html#problems" title="Časté problémy">Hardware problems</a></span>,
      <span class="link"><a href="printing.html" title="Tlačiť">printers</a></span>,
      <span class="link"><a href="power.html" title="Power &amp; battery">power settings</a></span>,
      <span class="link"><a href="color.html" title="Správa farieb">color management</a></span>,
      <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>,
      <span class="link"><a href="disk.html" title="Disky a úložiská">disks</a></span>…
    </span>
</li>
<li class="links ">
<a href="prefs.html" title="Užívateľské a systémové nastavenia">Užívateľské a systémové nastavenia</a><span class="desc"> — 
      <span class="link"><a href="keyboard.html" title="Klávesnica">Keyboard</a></span>,
      <span class="link"><a href="mouse.html" title="Myš">mouse</a></span>,
      <span class="link"><a href="prefs-display.html" title="Vzhľad displeja; obrazovka">display</a></span>,
      <span class="link"><a href="prefs-language.html" title="Region &amp; Language">languages</a></span>,
      <span class="link"><a href="user-accounts.html" title="Užívateľský účet">user accounts</a></span>…
    </span>
</li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
