<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Čo je profil farieb</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#profiles" title="Profily farieb">Profily farieb</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#profiles" title="Profily farieb">Profily farieb</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Čo je profil farieb</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Profil farieb je sada údajov, ktoré charakterizujú buď zariadenie, ako je napríklad projektor alebo farebný priestor, ako je napríklad sRGB.</p>
<p class="p">Väčšina profilov farieb je vo forme profilov ICC, čo je malý súbor s príponou <span class="input">.ICC</span> alebo <span class="input">.ICM</span>.</p>
<p class="p">Profily farieb môžu byť zahrnuté v obrázkoch a určovať farebný rozsah údajov. Zaisťujú aby používatelia videli rovnaké farby na rôznych zariadeniach.</p>
<p class="p">Každé zariadenie, ktoré spracováva farby by malo mať svoj vlastný profil ICC, aby ho v prípade potreby mohlo poskytnúť na <span class="em">prevod z jedného zariadenia na druhé</span>. Pri takomto spôsobe správy farieb je zaistené aby sa údaje o farbe nestratili a neboli pozmenené.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#profiles" title="Profily farieb">Profily farieb</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="color-howtoimport.html" title="Importovanie profilov farieb">Importovanie profilov farieb</a><span class="desc"> — Color profiles can be imported by opening them.</span>
</li>
<li class="links ">
<a href="color-canshareprofiles.html" title="Podelenie sa o profil farieb">Podelenie sa o profil farieb</a><span class="desc"> — Sharing color profiles is never a good idea as hardware changes over time.</span>
</li>
<li class="links ">
<a href="color-assignprofiles.html" title="Priradenie profilov k zariadeniam">Priradenie profilov k zariadeniam</a><span class="desc"> — Zmena nastavení pomocou <span class="guiseq"><span class="gui">Nastavenia systému</span> ▸ <span class="gui">Farby</span></span>.</span>
</li>
<li class="links ">
<a href="color-gettingprofiles.html" title="Získanie farebných profilov">Získanie farebných profilov</a><span class="desc"> — Profily farieb sú poskytované výrobcami a môžeme si ich vygenerovať i sami.</span>
</li>
<li class="links ">
<a href="color-whatisspace.html" title="Čo je farebný priestor">Čo je farebný priestor</a><span class="desc"> — Priestor farieb je definovaný rozsah farieb.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
