<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Što je profil boja?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#profiles" title="Profili boja">Profili boja</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#profiles" title="Profili boja">Profili boja</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Što je profil boja?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Profil boja je skup podataka koji karakterizira ili uređaj, kao što je projektor ili prostor boja, kao što je sRGB.</p>
<p class="p">Većina profila boja su obliku ICC profila, što je mala datoteka s <span class="input">. ICC </span> ili <span class="input">. ICM </span> ekstenzija datoteke.</p>
<p class="p">Profila boja može biti ugrađen u slike kako bi se odredila skala raspona podataka. To osigurava da korisnici vide iste boje na različitim uređajima.</p>
<p class="p">Svaki uređaj koji obrađuje boju treba imati vlastiti ICC profil i kada se to postigne sistemu je rečeno da ima <span class="em"> end-to-end bojom upravljan proces rada </span>. Uz ovu vrstu procesa rada možete biti sigurni da boje nisu izgubljene ili modificirane.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#profiles" title="Profili boja">Profili boja</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="color-gettingprofiles.html" title="Gdje mogu dobiti profile boja?">Gdje mogu dobiti profile boja?</a><span class="desc"> — Profili boja osiguravaju dobavljači od prodavača i možete ih generirati.</span>
</li>
<li class="links ">
<a href="color-assignprofiles.html" title="Kako dodijeliti profile na uređaje?">Kako dodijeliti profile na uređaje?</a><span class="desc"> — Pogledajte u <span class="guiseq"><span class="gui"> Postavke sistema </span> ▸ <span class="gui"> Boja </span></span> za mogućnost da se to promijeni.</span>
</li>
<li class="links ">
<a href="color-howtoimport.html" title="Kako uvesti profile boja?">Kako uvesti profile boja?</a><span class="desc"> — Profili boja mogu biti uvezeni njihovim otvaranjem.</span>
</li>
<li class="links ">
<a href="color-canshareprofiles.html" title="Mogu li dijeliti moje profile boja?">Mogu li dijeliti moje profile boja?</a><span class="desc"> — Dijeljenje boje profila nikada nije dobra ideja kao promjene hardware-a vremenom.</span>
</li>
<li class="links ">
<a href="color-whatisspace.html" title="Šta je prostor boja?">Šta je prostor boja?</a><span class="desc"> — Prostor boja je definiran raspon boja.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
