<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Šta je prostor boja?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#profiles" title="Profili boja">Profili boja</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="color.html" title="Upravljanje bojama">Upravljanje bojama</a> › <a class="trail" href="color.html#profiles" title="Profili boja">Profili boja</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Šta je prostor boja?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Prostor boja definira raspon boja. Poznati prostori boja su spektri uključujući sRGB, AdobeRGB and ProPhotoRGB.</p>
<p class="p">Ljudski vizualni sustav nije jednostavan RGB senzor, ali možemo ostvariti kako oko reagira s CIE 1931 dijagram kromatičnosti koji pokazuje ljudsku vizualni odgovor kao potkove formi. Možete vidjeti da je u ljudskoj viziji postoji mnogo više nijanse zelene otkrivenih od plave ili crvene. Uz trobojan prostora boja kao što su RGB mi predstavljaju boje na računalu pomoću tri vrijednosti, što ograničava do enkodiranje <span class="em"> trokut </span> boja</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Koristeći modele poput CIE dijagram kromatičnosti 1931 je ogromna pojednostavljenje ljudskog vizualnog sustava, a pravi skale izražene su kao 3D trupa, nego 2D projekcije.2D projekcija 3D formi ponekad može zavarati, pa ako želite vidjeti 3D trup, instalirati <span class="code">gnome-color-manager </span> i onda pokrenuti <span class="code"> gcm-viewer </span>.</p></div></div></div></div>
<div class="figure"><div class="inner">
<a href="#" class="zoom" data-zoom-in-title="Slike u normalnoj veličini" data-zoom-out-title="Smanji slike"></a><div class="region">
<div class="contents"><div class="media media-image"><div class="inner"><img src="figures/color-space.png" class="media media-block" alt=""></div></div></div>
<div class="desc">sRGB, AdobeRGB i ProPhotoRGB predstavljeni su sa bijelim trouglima</div>
</div>
</div></div>
<p class="p">
    First, looking at sRGB, which is the smallest space and can encode
    the least number of colors.
    It is an approximation of a 10 year old CRT display, and so most
    modern monitors can display more colors than this.
    sRGB is a <span class="em">least-common-denominator</span> standard and is used
    in a large number of applications (including the Internet).
  </p>
<p class="p">AdobeRGB često se koristi kao prostor <span class="em"> uređivanje </span>. To može kodirati više boje nego sRGB, što znači da možete promijeniti boje u fotografiji, bez brige previše da najviše žive boje se šišati ili crnci slomiti.</p>
<p class="p">ProPhoto je najveći prostor dostupan te se često koristi za dokumenta arhivskoj. To može kodirati gotovo cijeli spektar boja otkrivenih od strane ljudskog oka, pa čak i kodiranje boja koje oko ne može otkriti!</p>
<p class="p">Sada, ako ProPhoto je jasno bolje, zašto ne bismo ga koristiti za sve?O dgovor je to učiniti s <span class="em"> kvantizacije </span>. Ako imate samo 8 bitova (256 razina) do kodiraju svaki kanal, zatim veći raspon će imati veće korake između svih vrijednosti.</p>
<p class="p">Veći koraci znače veću pogrešku između zarobljenih boja i pohranjenih boja, a za neke boje to je veliki problem. Ispada da ključne boje, kao što je boja kože su vrlo važni, pa čak i male pogreške, učinit će da i neiskusni gledatelji primijete da nešto u fotografiji izgleda krivo.</p>
<p class="p">Naravno, korištenje 16 bitne slike će ostaviti mnogo više koraka i puno manju grešku kvantizacije, ali to udvostručuje veličinu slike. Većina sadržaja koji postoji danas je 8bpp, odnosno 8 bita po pikselu.</p>
<p class="p">Upravljanje bojama je proces pretvaranja iz jednog prostora boja u drugi, gdje prostor boja može biti dobro poznat definiran prostor poput sRGB, ili prilagođen prostor kao što je monitor ili printer.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#profiles" title="Profili boja">Profili boja</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="color-whatisprofile.html" title="Što je profil boja?">Što je profil boja?</a><span class="desc"> — Profil boja je jednostavna datoteka koja izražava prostor boja ili  odgovor uređaja.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
