<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Získanie farebných profilov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#profiles" title="Profily farieb">Profily farieb</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="color.html" title="Správa farieb">Správa farieb</a> › <a class="trail" href="color.html#profiles" title="Profily farieb">Profily farieb</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Získanie farebných profilov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Najlepší spôsob, ako sa dajú získať profily, je ich svojpomocné vygenerovanie, aj napriek tomu, že si to vyžaduje určité počiatočné náklady.</p>
<p class="p">Mnoho výrobcov sa pokúša poskytovať profily pre zariadenia, ktoré niekedy dodáva spolu s ovládačmi pre iné operačné systémy. Tieto balíky ovládačov je potrebné najskôr rozbaliť a potom v nich profily farieb vyhľadať.</p>
<p class="p">Niektorý výrobcovia neposkytujú presné profily pre hardvér a je lepšie sa im vyhnúť. Vhodné je najskôr skontrolovať dátum vydania na stiahnutom profile, a ak je viac ako o rok starší ako dátum zakúpenia zariadenia, ide pravdepodobne o nepoužiteľný profil.</p>
<p class="p">
    See <span class="link"><a href="color-why-calibrate.html" title="Vlastnoručná kalibrácia">Vlastnoručná kalibrácia</a></span> for information on why vendor-supplied
    profiles are often worse than useless.
  </p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="color.html#profiles" title="Profily farieb">Profily farieb</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="color-missingvcgt.html" title="Chýbajúce informácie o celoobrazovej korekcii farieb">Chýbajúce informácie o celoobrazovej korekcii farieb</a><span class="desc"> — Celoobrazová korekcia farieb upravuje farby na celej obrazovke vo všetkých oknách.</span>
</li>
<li class="links ">
<a href="color-testing.html" title="How do I test if color management is working correctly?">How do I test if color management is working correctly?</a><span class="desc"> — 
      Testing color management isn't hard, and we even supply some test 
      profiles.
    </span>
</li>
<li class="links ">
<a href="color-why-calibrate.html" title="Vlastnoručná kalibrácia">Vlastnoručná kalibrácia</a><span class="desc"> — Kalibrovanie je dôležité ak nám záleží na vernom zobrazení alebo tlačení farieb.</span>
</li>
<li class="links ">
<a href="color-whatisprofile.html" title="Čo je profil farieb">Čo je profil farieb</a><span class="desc"> — Profil farieb je súbor, ktorý definuje farebný priestor alebo farebnú odozvu.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
