<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Správa zväzkov a oddielov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="disk.html" title="Disky a úložiská">Disky a úložiská</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Správa zväzkov a oddielov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Slovo <span class="em">zväzok</span> sa používa v súvislosti s úložnými zariadeniami, ako je napríklad pevný disk. Označuje sa ním jednu <span class="em">časť</span> úložného priestoru, ktorý môže tvoriť jedno alebo viacero fyzických zariadení. Počítač k úložnému priestoru pristupuje prostredníctvom súborového systému pomocou procesu, ktorý sa volá <span class="em">pripojenie</span>. Pripojené zväzky môžu byť na pevných diskoch, USB kľúčoch, DVD disku, SD karte a ďalších nosičoch. Ak je zväzok práve pripojený, môžeme z neho čítať (a možno aj naň zapisovať) súbory.</p>
<p class="p">Pripojený zväzok často voláme <span class="em">oddiel</span>, aj napriek tomu, že to nie je celkom to isté. Oddiel hovorí o <span class="em">fyzickej</span> oblasti, ktorá sa nachádza na jednom disku. Keď oddiel pripojíme, môžeme ho považovať za zväzok, pretože môžeme pristupovať k súborom, ktoré sú na ňom uložené. Zväzky teda môžeme považovať za označené výkladné skrine obchodov v podobe oddielov a diskov.</p>
</div>
<div id="manage" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">View and manage volumes and partitions</span></h2></div>
<div class="region"><div class="contents">
<p class="p">To view and manage your computer's volumes and partitions:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Open <span class="app">Disks</span> from the <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p"> In the left pane, you will find a list of hard disks,
  CD/DVD drives, other physical devices, and loop devices. Select the device that you want to
  inspect.</p></li>
<li class="steps">
<p class="p"> In the right pane, the area labeled <span class="gui">Volumes</span> provides a visual
  breakdown of the volumes and partitions (if any) present on the selected device. It
  also contains a variety of tools used to manage these volumes.</p>
<p class="p">Be careful: it is possible to completely erase the data on your disk with
  these tools.</p>
</li>
</ol></div></div></div>
<p class="p">Počítač bude mať pravdepodobne aspoň jeden <span class="em">primárny</span> oddiel a jeden <span class="em">odkladací priestor</span>. Odkladací priestor je oddiel, ktorý operačný systém používa na správu pamäte. Primárny oddiel obsahuje operačný systém, aplikácie, nastavenia a osobné súbory. Tieto súbory môžu byť, kvôli zabezpečeniu a pohodliu rozdelené do viacerých oddielov.</p>
<p class="p">One primary partition must contain information that your computer uses to
 start up, or <span class="em">boot</span>. For this reason it is sometimes called a boot
 partition, or boot volume. If a volume is bootable, the information displayed will say: "Partition Type ... (Bootable)".
 External media such as USB flash drives and CDs may also contain a bootable volume.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="disk.html" title="Disky a úložiská">Disky a úložiská</a><span class="desc"> — 
    <span class="link"><a href="disk-capacity.html" title="Kontrola zostávajúceho voľného miesta">Disk space</a></span>,
    <span class="link"><a href="disk-benchmark.html" title="Test the performance of a disk">performance</a></span>,
    <span class="link"><a href="disk-check.html" title="Skontrolovanie chýb na disku">problems</a></span>,
    <span class="link"><a href="disk-partitions.html" title="Správa zväzkov a oddielov">volumes and partitions</a></span>…
  </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
