<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dokumenti</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#documents" title="Dokumenti">Dokumenti</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dokumenti</span></h1></div>
<div class="region">
<div class="contents"><p class="p"><span class="app">Documents</span> je GNOME aplikacija koja vam omogućava da prikažete, organizujete i printate dokumente na vašem računaru ili kreirane izdaleka koristeći <span class="em">Google Docs</span> ili <span class="em">SkyDrive</span>.</p></div>
<div id="view" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pregledaj, Sortiraj i Pretraga</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="documents-formats.html" title="Podržani formati"><span class="title">Podržani formati</span><span class="linkdiv-dash"> — </span><span class="desc"><span class="app">Dokumenti</span> prikazuje brojne popularne tipove dokumenata.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="documents-view.html" title="Prikažite dokumente smještene na disku ili na internetu"><span class="title">Prikažite dokumente smještene na disku ili na internetu</span><span class="linkdiv-dash"> — </span><span class="desc">Pregledajte dokumente preko cijelog ekrana.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="documents-filter.html" title="Filtrirajte dokumente"><span class="title">Filtrirajte dokumente</span><span class="linkdiv-dash"> — </span><span class="desc">Odaberite koje dokumente prikazivati.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="documents-viewgrid.html" title="Prikažite fajlove u listi ili u tabeli"><span class="title">Prikažite fajlove u listi ili u tabeli</span><span class="linkdiv-dash"> — </span><span class="desc">Promijenite način na koji se dokumenti prikazuju.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="documents-search.html" title="Traži datoteke"><span class="title">Traži datoteke</span><span class="linkdiv-dash"> — </span><span class="desc">Nađite vaše dokumente prema nazivu ili prema autoru.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="documents-info.html" title="Nađite informacije o dokumentima"><span class="title">Nađite informacije o dokumentima</span><span class="linkdiv-dash"> — </span><span class="desc">Pogledajte ime dokumenta, lokaciju, datum izmjene ili tip.</span></a></div>
</div>
</div></div></div></div></div>
</div></div>
<div id="print" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Odaberi, Organizuj, Printaj</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="documents-collections.html" title="Napravite kolekcije dokumenata."><span class="title">Napravite kolekcije dokumenata.</span><span class="linkdiv-dash"> — </span><span class="desc">Dokumenti koji se odnose na grupe u kolekciji.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="documents-select.html" title="Odabir dokumenata"><span class="title">Odabir dokumenata</span><span class="linkdiv-dash"> — </span><span class="desc">Koristite opciju za selektovanje da odaberete više dokumenata ili kolekcija.</span></a></div>
</div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="documents-print.html" title="Štampanje dokumenta"><span class="title">Štampanje dokumenta</span><span class="linkdiv-dash"> — </span><span class="desc">Printajte dokumente koji su pohranjeni lokalno ili na internetu.</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div id="question" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Pitanja</span></h2></div>
<div class="region"><div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="documents-tracker.html" title="Moji dokumenti nisu prikazani"><span class="title">Moji dokumenti nisu prikazani</span><span class="linkdiv-dash"> — </span><span class="desc">Lokalni ili udaljeni dokumenti se ne prikazuju.</span></a></div></div>
<div class="links-twocolumn"><div class="linkdiv "><a class="linkdiv" href="documents-previews.html" title="Zašto neki fajlovi nemaju pokazni pregled?"><span class="title">Zašto neki fajlovi nemaju pokazni pregled?</span><span class="linkdiv-dash"> — </span><span class="desc">Možete pregledati jedino dokumente sa lokalne memorije</span></a></div></div>
</div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#documents" title="Dokumenti">Dokumenti</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
