<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Sigurno ukloniti vanjski disk</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Sigurno ukloniti vanjski disk</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada koristite vanjske uređaje za pohranu kao što su USB flash diskove, što sigurno treba njih ukloniti prije nego njih izvlačenjem. Ako samo isključite uređaj, što pokrenete rizik od isključivanjem dok primjena još uvijek ga koristi. To bi moglo dovesti do neke od vaših datoteka se izgubljene ili oštećene. Kada koristite optički disk kao CD ili DVD, možete koristiti iste korake kako bi izvaditi disk iz računala.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Za izbacivanje prenosnog uređaja:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p"><span class="link"><a href="files-browse.html" title="Pregledavanje datoteka i mapa.">Otvorite upravljač datotekom</a></span>.</p></li>
<li class="steps">
<p class="p">Pronađite uređaj u bočnoj traci. Trebao bi imati malu ikonu izbacivanja pored imena. Kliknite ikonu za izbacivanje da sigurno uklonite ili izbacite uređaj.</p>
<p class="p">Alternativno, možete desnim klikom kliknuti na ime uređaja na traci sa strane i odabrati <span class="gui">Izbaci</span>.</p>
</li>
</ol></div>
</div></div>
</div>
<div id="remove-busy-device" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Sigurno uklonite uređaj koji je u upotrebi</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako bilo koji od datoteka na uređaju su otvoreni i koriste aplikacije, nećete biti u mogućnosti sigurno ukloniti uređaj. Vi ćete biti zatraženo s prozora vam reći da je "obujam je zauzet", a popis svih otvorenih datoteka na uređaju. Nakon što zatvorite sve datoteke na uređaju, uređaj će automatski biti sigurno ukloniti. U tom trenutku možete isključiti ili ga izbaciti.</p>
<p class="p">Ako ne možete zatvoriti jednu od datoteka, na primjer, ako je aplikacija koja koristi datoteku zaključana, možete desnom tipkom miša kliknuti na datoteku u <span class="gui"> Volumen je zauzet </span> Prozor i odaberite <span class="gui"> Kraj procesa </span>. To će prisiliti cijelu zaključanu aplikaciju da se zatvori, što bi moglo zatvoriti druge datotekaekoje ste otvorili sa tom aplikacijom.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Takođe možete izabrati <span class="gui">Eject Anyway</span> da biste uklonili uređaj bez zatvaranja datoteka. Ovo bi moglo izazvati greške u aplikacijama kod kojih su te datoteke otvorene.</p></div></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
