<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Otvorite aplikacije za uređaje ili diskove</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#videos" title="Video i video kamere">Video</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Otvorite aplikacije za uređaje ili diskove</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete postaviti da se aplikacija automatski pokrene kada spojite neki uređaj ili ubacite disk ili karticu. Na primjer, možda želite da se organizator slika automatski pokrene kada spojite digitalnu kameru. Ovu opciju također možete isključiti, tako da se ništa neće desiti kada nešto spojite.</p>
<p class="p">Da odlučite koje aplikacije se trebaju pokrenuti kada priključite razne uređaje:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and
    select <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">Odaberite <span class="guiseq"><span class="gui">Detalji</span> ▸ <span class="gui">Uklonjivi Medij</span></span>.</p></li>
<li class="steps">
<p class="p">Pronađite vaš željeni uređaj ili tip medija i onda izaberite aplikaciju ili akciju za taj tip medija. Pogledajte ispod za opis svakog tipa uređaja ili medija.</p>
<p class="p">Umjesto da pokrećete aplikaciju, možete je podesit tako da uređaj bude prikazan u uređivaču fajlova. Kada se to desi, bit ćete pitani šta dalje, ili se ništa neće desiti.</p>
</li>
<li class="steps"><p class="p"><span class="gui"> Softver </span> opcija je malo drugačija od drugih - ako računar otkrije da postoji softver na disku koji ste umetnuli, može pokušati automatski pokrenuti program ako želite. To je dobro ako imate program instaliran na CD-u i želite da se pokrene kada je disk umetnut (na primjer, slideshow).</p></li>
<li class="steps"><p class="p">Ako ne vidite uređaj ili vrstu medija koju želite promijeniti na popisu (kao što su Blu-ray diskova ili E-knjige čitatelji), kliknite <span class="gui"> drugim medijima </span> da vidite detaljniji popis uređaja. Odaberite vrstu uređaja ili medija iz <span class="gui"> Type </span> padajućem i program ili radnju iz <span class="gui"> akcije </span> padajući.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ukoliko ne želite da se bilo koja aplikacija automatski otvori, bez obzira šta priključili, odaberite <span class="gui"> Nikada izazvati ili pokrenuti programe umetanjem medija </span> na dnu prozora Prijenosni medij.</p></div></div></div></div>
</div>
<div id="files-types-of-devices" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Tipovi uređaja i medija</span></h2></div>
<div class="region"><div class="contents"><div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">Audio diskovi</dt>
<dd class="terms"><p class="p">Choose your favorite music application or CD audio extractor to handle
    audio CDs. If you use audio DVDs (DVD-A), select how to open them under
    <span class="gui">Other Media</span>. If you open an audio disc with the file manager,
    the tracks will appear as WAV files that you can play in any audio player
    application.</p></dd>
<dt class="terms">Video diskovi</dt>
<dd class="terms"><p class="p">Odaberite omiljenu aplikaciju za rukovanje video DVD-ovima. Koristite <span class="gui">Other Media</span> dugme da postavite aplikaciju za Blu-ray, HD DVD, video CD(VCD, i super video CD(SVCD). Ako DVD-ovi ili neki drugi video diskovi ne rade ispravno kada ih umetnete, pogledajte <span class="link"><a href="video-dvd.html" title="Zašto DVD ne radi?">Zašto DVD ne radi?</a></span>.</p></dd>
<dt class="terms">Prazni diskovi</dt>
<dd class="terms"><p class="p">Koristite dugme <span class="gui">Drugi Mediji</span> da izaberete aplikaciju za pisanje diskova za prazne CD-ove, DVD-ove, Blu-ray diskove i prazne HD DVD-ove.</p></dd>
<dt class="terms">Aparati i fotografije</dt>
<dd class="terms">
<p class="p">Koristite  <span class="gui">Photos</span> padajući meni da biste izabrali aplikaciju za upravljanje slikama koju želite da koristite kada priključite vašu digitalnu kameru, ili kada ubacite media karticu iz kamere kao sto su CF, SD, MMC ili MS kartice. Ili možete korisiti file menadžera da jednostavno pregledate vaše slike.</p>
<p class="p">Ispod <span class="gui">Drugi mediji</span>, možete odabrati aplikaciju za otvaranje Kodakovih CD-ova, kao što su oni koji su možda napravljeni u radnji. Ovo su regularni CD-ovi podataka sa JPEG slikama u mapi <span class="file">SLIKE</span></p>
</dd>
<dt class="terms">Muzički plejeri</dt>
<dd class="terms"><p class="p">Izaberite aplikaciju koja će upravljati muzičkom bibliotekom na vašem prenosnom muzičkom plejeru, ili to možete raditi sami koristeći fajl menadžera.</p></dd>
<dt class="terms">Čitač e-knjiga</dt>
<dd class="terms"><p class="p">Koristite dugme <span class="gui">Drugi mediji</span> da odaberete aplikaciju za upravljanje knjigama na vašem čitaču e-knjiga, ili sami upravljajte datotekama pomoću upravljača datoteka.</p></dd>
<dt class="terms">Softver</dt>
<dd class="terms">
<p class="p">Neki diskovi i prijenosni mediji sadrže softver koji bi trebao da se pokrene automatski kada se uređaj priključi. Koristite <span class="gui">Software</span> opciju da biste odredili šta će se desiti kada se prikljući uređaj sa takvim softverom prikljući. Potvrda će uvijek biti potrebna za bi se pokrenuo softver.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Nikad ne pokrećite programe medija kojima ne vjerujete.</p></div></div></div></div>
</dd>
</dl></div></div></div></div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a></li>
<li class="links "><a href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a></li>
<li class="links "><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">Prijenosni diskovi i vanjski diskovi.</a></li>
<li class="links "><a href="media.html#videos" title="Video i video kamere">Video</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
