<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Kopirajte ili premjestite datoteke i foldere</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Kopirajte ili premjestite datoteke i foldere</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Datoteka ili folder se može kopirati ili premjestiti na novu lokaciju povlačenjem i ispuštanjem koriteći miš, koristeći copy i paste komande, ili korištenjem prečaca na tastaturi.</p>
<p class="p">Na primjer, možda želite kopirati prezentaciju na memory stick tako da ga možete nositi na posao. Ili možete napraviti backup kopiju dokumenta prije nego što napravite promjene (i zatim koristite staru kopiju ako vam se ne sviđaju promjene).</p>
<p class="p">Ove upute vrijede za datoteke i foldere. Možete kopirati i premjestiti datoteke i foldere na isti način.</p>
<div class="steps ui-expander">
<div class="yelp-data yelp-data-ui-expander" dir="ltr" data-yelp-expanded="false"></div>
<div class="inner">
<div class="title title-steps"><h2><span class="title">Kopirajte i umetnite datoteke</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Odaberite datoteku koju želite kopirati klikom na nju jednom.</p></li>
<li class="steps"><p class="p">Desnim klikom odaberite <span class="gui">Kopiraj</span>, ili pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>C</kbd></span></span>.</p></li>
<li class="steps"><p class="p">Dođite u drugi folder, gdje želite staviti kopiju datoteke.</p></li>
<li class="steps"><p class="p">Right-click and pick <span class="gui">Paste</span> to finish copying the
 file, or press <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>V</kbd></span></span>. There
 will now be a copy of the file in the original folder and the other
 folder.</p></li>
</ol></div>
</div>
</div>
<div class="steps ui-expander">
<div class="yelp-data yelp-data-ui-expander" dir="ltr" data-yelp-expanded="false"></div>
<div class="inner">
<div class="title title-steps"><h2><span class="title">Izrežite i zaljepite datoteke da ih premjestite</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Odaberite datoteku koju želite premjestiti jednim klikom na nju.</p></li>
<li class="steps"><p class="p">Desnim klikom odaberite <span class="gui">Izreži</span>, ili pritisnite  <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>X</kbd></span></span>.</p></li>
<li class="steps"><p class="p">Dođite u drugi folder, gdje želite premjestiti datoteku.</p></li>
<li class="steps"><p class="p">Right-click and pick <span class="gui">Paste</span> to
 finish moving the file, or press <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>V</kbd></span></span>.
 The file will be taken out of its original folder and moved to the other
 folder.</p></li>
</ol></div>
</div>
</div>
<div class="steps ui-expander">
<div class="yelp-data yelp-data-ui-expander" dir="ltr" data-yelp-expanded="false"></div>
<div class="inner">
<div class="title title-steps"><h2><span class="title">Povucite datoteke da kopirate ili premjestite</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite program za upravljanje datotekama i idite u folder koji sadrži datoteku koju želite kopirati.</p></li>
<li class="steps"><p class="p">Click <span class="gui">Files</span> in the top bar, select <span class="gui">New Window</span> (or
 press <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>N</kbd></span></span>) to open a second window. In
 the new window, navigate to the folder where you want to move or copy the file.
 </p></li>
<li class="steps">
<p class="p">Kliknite i povucite datoteku iz jednog prozora u drugi. Ovo će je <span class="em"> pomjeriti</span> ako je destinacija na <span class="em">istom</span> uređaju, ili će je <span class="em">kopirati</span> ako je destinacija na <span class="em">nekom drugom</span> uređaju.</p>
<p class="p">Na primjer, ako povučete datoteku sa USB memorije u vaš Home folder, biti će kopiran jer povlačite sa jednog uređaja na drugi.</p>
<p class="p">Možete prinuditi datoteku da se kopira držeći <span class="key"><kbd>Ctrl</kbd></span> tipku dok vućete, ili je prinuditi da se premjesti držeći <span class="key"><kbd>Shift</kbd></span> tipku dok vućete.</p>
</li>
</ol></div>
</div>
</div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Vi ne možete kopirati ili premjestiti datoteku u mapu koja je <span class="em"> samo za čitanje </span>. Neke mape su samo za čitanje kako bi spriječio promjene na njihov sadržaj. Možete promijeniti stvari od toga da bude samo za čitanje po <span class="link"><a href="nautilus-file-properties-permissions.html" title="Postavite dozvole za datoteku"> promjenom dozvole za datoteku </a></span></p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files-browse.html" title="Pregledavanje datoteka i mapa.">Pregledavanje datoteka i mapa.</a><span class="desc"> — Upravljanje i organiziranje datoteka programom ya  upravljanjem datotekama.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
