<!DOCTYPE html>
<html lang=kk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Search for files or folders</title>
<link rel="stylesheet" type="text/css" href="kk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Guide"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Help"></span></span> Ubuntu Desktop Guide</a> » <a class="trail" href="files.html" title="Files, folders &amp; search">Files</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Search for files or folders</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can search for:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">Files based on name or file type, and</p></li>
<li class="list"><p class="p">Folders based on name.</p></li>
</ul></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Search</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Open <span class="app">Files</span> from the <span class="gui">Dash</span>.</p></li>
<li class="steps"><p class="p">If you know the files or folders that you want are under a particular folder, navigate
    to that folder.</p></li>
<li class="steps"><p class="p">Click the magnifying glass
    <span class="media"><span class="media media-image"><img src="figures/system-search.png" class="media media-inline" alt="Magnifying glass icon"></span></span>
     in the toolbar, or press
    <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>F</kbd></span></span>.</p></li>
<li class="steps"><p class="p">In the search box type a word or words that you know appear in the name. For
    example, if you name all your invoices with the word "Invoice", type
    <span class="input">invoice</span>. Words are matched regardless of case.</p></li>
<li class="steps">
<p class="p">If you want to restrict your search to files of a particular type, click the
    <span class="media"><span class="media media-image"><img src="figures/go-down.png" class="media media-inline" alt="Down arrow icon"></span></span>
      button and select a file type from the <span class="gui">What</span>
      drop-down list. Click the <span class="key"><kbd>x</kbd></span> button to remove this restriction.</p>
<p class="p">You can open, copy, delete, or otherwise work with your files and folders from
    the search results, just as you would from any folder in the file manager.
    </p>
</li>
<li class="steps"><p class="p">Click the magnifying glass 
    <span class="media"><span class="media media-image"><img src="figures/system-search.png" class="media media-inline" alt="Magnifying glass icon"></span></span>
    in the toolbar again to exit the search
    and return to the folder.</p></li>
</ol></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Files, folders &amp; search">Files, folders &amp; search</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Delete files and folders">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Backing up">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Removable drives and external disks">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
