<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Pisanje datoteka na CD ili DVD.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Pisanje datoteka na CD ili DVD.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can put files onto a blank disc by using <span class="gui">CD/DVD Creator</span>. The
 option to create a CD or DVD will appear in the file manager as soon as you
 place the CD into your CD/DVD writer. The file manager lets you transfer files
 to other computers or perform <span class="link"><a href="backup-why.html" title="Napravite sigurnosne kopije važnih datoteka">backups</a></span> by putting
 files onto a blank disc. To write files to a CD or DVD:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Postavite prazan disk u CD / DVD u disk zapisivanja.</p></li>
<li class="steps">
<p class="p">U <span class="gui"> Prazan CD/DVD-R Disk</span> prozoru koji će se pojaviti, odaberite <span class="gui">CD/DVD Kreator</span>i kliknite <span class="gui">OK</span>. <span class="gui">CD/DVD Kreator</span> prozor mape će se otvoriti.</p>
<p class="p">(Također možete kliknuti na <span class="gui"> Prazan CD / DVD-R disk </span> pod <span class="gui"> Uređaji </span> u sidebaru file manageru).</p>
</li>
<li class="steps"><p class="p">U <span class="gui"> ime diska </span> polje, unesite naziv za disk.</p></li>
<li class="steps"><p class="p">Prevucite ili kopirajte željene datoteke u prozor.</p></li>
<li class="steps"><p class="p">Kliknite<span class="gui">Piši na disk</span>.</p></li>
<li class="steps">
<p class="p">Pod <span class="gui"> Odaberite disk za pisanje  </span>, odaberite prazan disk.</p>
<p class="p">(Možete odabrati <span class="gui">datoteku slike </span> umjesto toga. Ovo će staviti datoteke u <span class="em"> datoteku s preslikanim diskom</span>, koji će biti spremljen na vaš računar. Nakon toga možete snimiti taj disk za sliku na prazan disk na neki kasniji datum.)</p>
</li>
<li class="steps"><p class="p">Kliknite <span class="gui"> Svojstva </span> ako želite podesiti veću brzinu, mjesto privremene datoteke, i druge opcije. Zadane opcije bi trebale biti u redu.</p></li>
<li class="steps">
<p class="p">Kliknite <span class="gui"> Prženje </span>dugme za početak snimanja.</p>
<p class="p">Ako je <span class="gui"> Prženje nekoliko primjeraka </span>  odabran, od vas će se zatražiti za dodatne diskove.</p>
</li>
<li class="steps"><p class="p">Kada je snimanje diska završeno , ona će izbaciti automatski. Odaberite <span class="gui"> napraviti više kopija </span> ili <span class="gui"> Zatvori </span> za izlaz.</p></li>
</ol></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents">
<p class="p">For more advanced CD/DVD burning projects, try <span class="app">Brasero</span>. It's
    not installed by default, but you can <span class="link"><a href="https://apps.ubuntu.com/cat/applications/brasero" title="https://apps.ubuntu.com/cat/applications/brasero">install</a></span>
    it from the Ubuntu package archive.</p>
<p class="p">For help with using <span class="app">Brasero</span>, read the
    <span class="link"><a href="https://help.gnome.org/users/brasero/stable/" title="https://help.gnome.org/users/brasero/stable/">user guide</a></span>.</p>
</div></div></div></div>
</div>
<div id="problem" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Ako disk nije ispravno upisan</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ponekad računar ne bilježi podatke ispravno, i nećete vidjeti datoteke koje ste stavili na disk kada ga umetnete u računar.</p>
<p class="p">U tom slučaju, pokušajte snimiti disk ponovo ali koristeći manju brzinu snimanja, na primjer 12x umjesto 48x. Snimanje na manjoj brzini je pouzdanije. Možete odabrati brzinu klikom na <span class="gui"> Svojstva </span> tipku u <span class="gui">CD/DVD Kreator</span> prozoru.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
