<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Spoločné používanie a prenos súborov</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="net.html" title="Networking, web, email &amp; chat">Networking, web, email &amp; chat</a> » <a class="trail" href="sharing.html" title="Sharing">Sharing</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Spoločné používanie a prenos súborov</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can share files with your contacts or transfer them to external 
devices or <span class="link"><a href="nautilus-connect.html" title="Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku">network shares</a></span> directly 
from the file manager.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvoríme <span class="link"><a href="files-browse.html" title="Navigácia medzi priečinkami">správcu súborov</a></span>.</p></li>
<li class="steps"><p class="p">Nájdeme súbor, ktorý chceme preniesť.</p></li>
<li class="steps"><p class="p">Klikneme na súbor pravým tlačidlom myši a zvolíme <span class="gui">Odoslať kam</span>.</p></li>
<li class="steps"><p class="p">Zobrazí sa okno <span class="gui">Odoslať do</span>. Zvolíte kam chcete odoslať súbor a potom kliknete na <span class="gui">Odoslať</span>. Ďalšie informácie o možných cieľoch nájdete v nasledujúcom texte.</p></li>
</ol></div></div></div>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">You can send multiple files at once. Select multiple files by holding
  down <span class="key"><kbd>Ctrl</kbd></span>, then right-click any selected file. You can have
  the files automatically compressed into a zip or tar archive.</p></div></div></div></div>
<div class="list"><div class="inner">
<div class="title title-list"><h2><span class="title">Ciele</span></h2></div>
<div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">Keď chceme súbor poslať mailom, zvolíme <span class="gui">E-mail</span> a zadáme emailovú adresu príjemcu.</p></li>
<li class="list"><p class="p">Keď chceme odoslať súbor kontaktu cez internetový komunikátor, zvolíme <span class="gui">Okamžitá správa</span>, a potom vyberieme kontakt z rozbaľovacieho zoznamu. Aby to fungovalo, je potrebné aby bol internetový komunikátor spustený.</p></li>
<li class="list"><p class="p">Keď chceme súbor zapísať na CD alebo DVD, zvolíme <span class="gui">Tvorca CD/DVD</span>. Viac informácií sa nachádza v časti <span class="link"><a href="files-disc-write.html" title="Zápis súborov na CD a DVD">Zápis súborov na CD a DVD</a></span>.</p></li>
<li class="list"><p class="p">To transfer the file to a Bluetooth device, select
  <span class="gui">Bluetooth (OBEX Push)</span> and select the device to send the file 
  to.
  You will only see devices you have already paired with.
  See <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span> for more information.</p></li>
<li class="list"><p class="p">To copy a file to an external device like a USB flash drive,
  or to upload it to a server you've connected to, select <span class="gui">Removable
  disks and shares</span>, then select the device or server you want to
  copy the file to.</p></li>
</ul></div>
</div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="sharing.html" title="Sharing">Sharing</a><span class="desc"> — 
      <span class="link"><a href="sharing-desktop.html" title="Share your desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Spoločné používanie a prenos súborov">Share files</a></span>…
    </span>
</li>
<li class="links ">
<a href="files.html" title="Súbory, priečinky a vyhľadávanie">Súbory, priečinky a vyhľadávanie</a><span class="desc"> — 
      <span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>,
      <span class="link"><a href="files-delete.html" title="Odstránenie súborov a prečinkov">delete files</a></span>,
      <span class="link"><a href="files.html#backup" title="Zálohovanie">backups</a></span>,
      <span class="link"><a href="files.html#removable" title="Odpojiteľné jednotky a externé disky">removable drives</a></span>,
      <span class="link"><a href="files.html#documents" title="Documents">documents</a></span>…
    </span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="nautilus-connect.html" title="Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku">Navigácia medzi súbormi na serveri alebo spoločne používanom sieťovom disku</a><span class="desc"> — Zobrazenie a úprava súborov na inom počítači cez FTP, SSH, WebDAV alebo na sieťovom disku Windows.</span>
</li>
<li class="links ">
<a href="bluetooth-send-file.html" title="Send a file to a Bluetooth device">Send a file to a Bluetooth device</a><span class="desc"> — Share files to Bluetooth devices such as your phone.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
