<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Obrišite datoteke i  direktorije.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Obrišite datoteke i  direktorije.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako vipe ne želite da datoteku ili mapu, možete je izbrisati. Kada izbrišete stavku je preselio na <span class="gui"> smeće </span> mape, gdje je pohranjen dok ne ispraznite smeće. Možete <span class="link"><a href="files-recover.html" title="Obnova datoteke iz smeća."> vraćanja predmeta </a></span> u <span class="gui"> Otpad </span> mapu na svoje izvorno mjesto ako odlučite da ih trebate, ili ako se slučajno izbrisani.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Da pošaljete datoteku u smeće:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite jednom na nju da odaberete stavku koju želite staviti u smeće.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="key"><kbd> Delete </kbd></span> na vašoj tastaturi. Alternativno, povucite stavku u <span class="gui"> Smeće </span> u bočnoj traci.</p></li>
</ol></div>
</div></div>
<p class="p">Za brisanje datoteke trajno, a slobodan prostor na disku na vašem računalu, morate isprazniti smeće. Da biste ispraznili smeće, kliknite desnom tipkom <span class="gui"> Smeće </span> u bočnoj traci i odaberite <span class="gui"> Isprazni smeće </span>.</p>
</div>
<div id="permanent" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Trajno brisanje datoteka.</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Možete odmah izbrisati datoteku trajno, bez da je šaljete u smeće.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h3><span class="title">Da trajno obrišete datoteku:</span></h3></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Označite stavku koju želite da izbrišete.</p></li>
<li class="steps"><p class="p">Pritisnite i držite <span class="key"><kbd>Shift</kbd></span> tipku, zatim pritisnite <span class="key"><kbd>Delete</kbd></span> tipku na vašoj tastaturi.</p></li>
<li class="steps"><p class="p">Budući da ne možete poništiti, od vas će biti zatraženo  da potvrdite da želite izbrisati datoteku ili mapu</p></li>
</ol></div>
</div></div>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">If you frequently need to delete files without using the
  trash (for example, if you often work with sensitive data), you can add a
  <span class="gui">Delete</span> entry to the right-click menu for files and folders.
  Click <span class="gui">Files</span> in the menu bar, pick <span class="gui">Preferences</span> and select
  the <span class="gui">Behavior</span> tab. Select <span class="gui">Include a Delete command that
  bypasses Trash</span>.</p></div></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Izbrisane datoteke na <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">prenosivom uređaju</a></span>možda neće biti vidljive na drugim operativnim sistemima, kao što su Windows ili MAC OS. Datoteke su još uvijek tu, i biće dostupne kada ponovo uključite uređaj u računar.</p></div></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a><span class="desc"> — <span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="files-recover.html" title="Obnova datoteke iz smeća.">Obnova datoteke iz smeća.</a><span class="desc"> — Izbrisane datoteke obično se šalju u Smeće, ali mogu biti vraćene.</span>
</li>
<li class="links "><a href="nautilus-behavior.html#trash" title="Smeće">Postavke datoteke smeća</a></li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
