<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Šta su vlasnički upravljački programi?</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Šta su vlasnički upravljački programi?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Većina uređaja (hardware) priključenih na vaš računar treba ispravno funkcionirati u Ubuntu. Ovi uređaji  vjerojatno  će imati upravljački pogon otvorenog koda, što znači da se upravljački programi mogu mijenjati od strane Ubuntu razvijatelja i problemi s njima mogu biti riješeni.</p>
<p class="p">Neki hardver nema otvoreni izvor upravljačkog pogona, najčešće jer proizvođač hardvera nije objavio detalje svog hardvera koji bi mogao stvoriti takav upravljački program. Ovi uređaji mogu imati ograničenu funkcionalnost ili ne rade uopće.</p>
<p class="p">Ako je  vlasnički upravljački programdostupan za određene uređaje, možete ga instalirati kako bi se omogućilo  da vaš uređaj  radi ispravno, ili dodati nove osobine. Na primjer, instalacija  za vlasničke upravljačke programe za određene grafičke kartice mogu vam omogućiti da koristite naprednije vizualne efekte</p>
<p class="p">Mnogi kompjuteri  ne trebaju vlasničke upravljačkih programa uopšte, jer otvoreni izvorni  upravljački programi  u potpunosti podržavaju hardver.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Većina problemu s vlasničkim upravljačkim programima ne mogu popraviti Ubuntu razvijatelji.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a><span class="desc"> — <span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
