<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Problemi sa čitačem kartica.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Problemi sa čitačem kartica.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Mnogi kompjuteri sadrže čitače za SD (Secure Digital), MMC (MultiMediaCard), SmartMedia, Memory Stick, CompactFlash, i druge kartične medije za pohranu. To bi trebao biti automatski otkriveno i <span class="link"><a href="disk-partitions.html" title="Upravljanje volumenima i particijama"> montirano </a></span>. Ovdje su neki koraci za rješavanje problema ako nije:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Uvjerite se da je kartica stavljena ispravno. Mnoge kartice izgledaju kao da su naglavačke kada se pravilno umetnuta. Također budite sigurni da kartica sjedne u utor; neke kartice, a posebno CompactFlash, zahtijevaju malu količinu snagu za umetanje ispravno. (Budite oprezni da ne gurati previše teško! Ako navali na nešto čvrsto, nemojte ga prisiliti.)</p></li>
<li class="steps"><p class="p"> Open <span class="app">Files</span> by using the <span class="gui">Dash</span>. Does the inserted
 card appear in the <span class="gui">Devices</span> list in the left sidebar? Sometimes the card appears in this list but is not mounted; click it once to mount. (If the sidebar is not visible, press <span class="key"><kbd>F9</kbd></span> or click
 <span class="guiseq"><span class="gui">View</span> ▸ <span class="gui"> Sidebar</span> ▸ <span class="gui"> Show Sidebar</span></span>.)
</p></li>
<li class="steps"><p class="p">Ako se kartica ne prikazuje u bočnoj traci, kliknite <span class="guiseq"><span class="gui"> Kreni </span> ▸ <span class="gui"> računara</span></span>. Ako je Vaš čitač kartica ispravno konfiguriran, čitatelj bi trebao doći i do upravljačkog pogona i kada nema prisutnu karticu , a i do same kartice kada je kartica montirana (vidi sliku ispod).</p></li>
<li class="steps"><p class="p">Ako vidite čitač kartica, ali ne kartice, problem može biti sa samom karticom.  Pokušajte drugu karticu ili provjeritie karticu na različitim čitateljima, ako je moguće.</p></li>
</ol></div></div></div>
<p class="p">Ako nema kartice ili diskovi su dostupni u <span class="gui"> računaru </span> mape, moguće je da vaš čitač kartica ne radi sa Linux zbog problema s upravljačkim programima. Ako je Vaš čitač kartica unutrašnji (u unutrašnjosti računala umjesto da nalazi izvan), to je više vjerojatno. Najbolje rješenje je da se izravno spajanje uređaja (kamera, mobitela, itd.) na USB priključak na računaru USB vanjski čitači kartica su također dostupni, a daleko su bolje podržane od Linuxa.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links "><a href="media.html#photos" title="Slike i digitalni aparati">Fotografije</a></li>
<li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li>
</ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
