<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ubuntu Desktop Priručnik</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" class="media media-inline" alt="Ubuntu Logo"></span></span> Ubuntu Desktop Priručnik</span></h1></div>
<div class="title" style="margin-bottom: 1.5em"><span>Ubuntu 17.04</span></div><div class="region"><div class="contents">
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="mouseovers"><img src="figures/ubuntu-mascot-creature.png"></div>
<ul class="mouseovers">
<li class="links"><a class="bold" href="unity-introduction.html" title="Dobrodošli u Ubuntu"><img src="figures/unity.png">Dobrodošli u Ubuntu</a></li>
<li class="links"><a class="bold" href="unity-launcher-intro.html" title="Koristite Launcher da biste pokrenuli aplikacije"><img src="figures/unity-launcher-intro.png">Koristite Launcher da biste pokrenuli aplikacije</a></li>
<li class="links"><a class="bold" href="unity-dash-intro.html" title="Find applications, files, music, and more with the Dash"><img src="figures/unity-dash-intro.png">Find applications, files, music, and more with the Dash</a></li>
<li class="links"><a class="bold" href="unity-menubar-intro.html" title="Upravljajte aplikacijama i postavkama pomoću trake s menijem"><img src="figures/unity-appmenu-intro.png">Upravljajte aplikacijama i postavkama pomoću trake s menijem</a></li>
<li class="links"><a class="bold" href="shell-exit.html" title="Odjavti se, isključiti, zamijeniti korisnika"><img src="figures/unity-exit.png">Odjavti se, isključiti, zamijeniti korisnika</a></li>
</ul>
<div class="clear"></div>
</div></div></div>
<div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="shell-overview.html" title="Desktop, programi &amp; prozori">Desktop, programi &amp; prozori</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="unity-introduction.html" title="Dobrodošli u Ubuntu">Introduction</a></span>,
      <span class="link"><a href="shell-keyboard-shortcuts.html" title="Korisne skraćenice na tastaturi">keyboard shortcuts</a></span>,
      <span class="link"><a href="shell-windows.html" title="Prozori i radni prostori.">windows</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="net-wireless.html" title="Bežično Umrežavanje">Wireless</a></span>, <span class="link"><a href="net-wired.html" title="Ožičeno umrežavanje">žičani</a></span>, <span class="link"><a href="net-problem.html" title="Problemi sa mrežom"> problemi sa spajanjem</a></span>, <span class="link"><a href="net-browser.html" title="Web pretraživači">web pretraživač</a></span>, <span class="link"><a href="net-email.html" title="E-mail pošta i e-mail program">email računi</a></span>, <span class="link"><a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">ćaskanje</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="media.html#photos" title="Slike i digitalni aparati">Digitalne kamere</a></span>, <span class="link"><a href="media.html#music" title="Muzika i prenosivi plejeri">iPods</a></span>, <span class="link"><a href="media.html#videos" title="Video i video kamere">izvođenje video</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke, folderi &amp; pretraživanje</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="files-search.html" title="Search for files or folders">Searching</a></span>, <span class="link"><a href="files-delete.html" title="Obrišite datoteke i direktorije.">delete files</a></span>, <span class="link"><a href="files.html#backup" title="Rezervne kopije">backups</a></span>, <span class="link"><a href="files.html#removable" title="Prijenosni diskovi i vanjski diskovi.">removable drives</a></span>, <span class="link"><a href="files.html#documents" title="Dokumenti">documents</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="addremove.html" title="Install &amp; remove software">Install &amp; remove software</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="addremove-install.html" title="Install additional applications">Install applications</a></span>,
      <span class="link"><a href="addremove-remove.html" title="Uklonite aplikaciju">remove applications</a></span>,
      <span class="link"><a href="addremove-sources.html" title="Add software repositories">add repositories</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="hardware.html" title="Hardware i upravljački programi">Hardware i upravljački programi</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></span>, <span class="link"><a href="printing.html" title="Štampanje">štampači</a></span>, <span class="link"><a href="power.html" title="Snaga &amp; baterija">postavke napajanja</a></span>, <span class="link"><a href="color.html" title="Upravljanje bojama">upravljanje bojama</a></span>, <span class="link"><a href="bluetooth.html" title="Bluetooth">Bluetooth</a></span>, <span class="link"><a href="disk.html" title="Diskovi i skladište">diskovi</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="a11y.html" title="Opšti pristup">Opšti pristup</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="a11y.html#vision" title="Oštećenje vida">Vidjeti</a></span>, <span class="link"><a href="a11y.html#sound" title="Oštećenje sluha">Slušati</a></span>,  <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">Pokretljivost</a></span>, <span class="link"><a href="a11y-braille.html" title="Čitanje ekrana na Brajevom pismu.">Brejl( Braille)</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="tips.html" title="Savjeti &amp; trikovi">Savjeti &amp;  trikovi</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="tips-specialchars.html" title="Unesite posebne znakove">Specijalni znakovi</a></span>, <span class="link"><a href="mouse-middleclick.html" title="Srednji klik">kratice srednjim klikom</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="more-help.html" title="Još pomoći">Još pomoći</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="about-this-guide.html" title="O ovom vodiču">Savjeti za korištenje ovog priručnika</a></span>, <span class="link"><a href="get-involved.html" title="Učestvujte u poboljšanju ovog uputstva">pomozite da poboljšamo ovaj priručnik </a></span>…</span></div>
</div>
</div></div></div>
</div></div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
