<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Koristite alternativne izvore unosa</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="keyboard.html" title="Tastatura">Tastatura</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="prefs-language.html" title="Regija i jezik">Regija i jezik</a> › <a class="trail" href="prefs-language.html#textentry" title="Unos teksta">Unos teksta</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Koristite alternativne izvore unosa</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Tastature dolaze u stotine različitih izgleda za različite jezike. Čak i za jedan jezik, tu često ima više izgleda tastature, kao što je Dvorak raspored za engleski. Možete napraviti tastaturu da se ponaša kao tastature s različitim izgledom, bez obzira na slova i simbole ispisane na tipkama. To je korisno ako se često prebacujete između više jezika.</p>
<p class="p">Some languages, such as Chinese or Korean, require a more complex input
  method than just a simple key to character mapping. Consequently some of
  the input sources you can choose between enable such a method. More about
  that in the section <span class="link"><a href="#complex" title="Complex input methods">Complex input methods</a></span>.</p>
</div>
<div id="add" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Dodajte izvore unosa</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and
       select <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">U sekciji Osobno, kliknite <span class="gui">Text Entry</span>.</p></li>
<li class="steps"><p class="p">Kliknite na <span class="gui">+</span> taster, odaberite izvor unosa, i kliknite na <span class="gui">Dodaj</span></p></li>
</ol></div></div></div>
<p class="p">You can view an image of any source by selecting it in the list and clicking
    <span class="gui"><span class="media"><span class="media media-image"><img src="figures/input-keyboard-symbolic.svg" height="16" width="16" class="media media-inline" alt="view"></span></span></span>.</p>
<p class="p">Uobičajeni izvor je onaj koji je naveden na početku liste. Koristite tipke <span class="gui">↑</span> i <span class="gui">↓</span> da biste pomjerali izvore uz i niz listu.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><div class="list"><div class="inner"><div class="region"><ul class="list">
<li class="list"><p class="p">Ako odaberete izvor sa metodom unosa, možete kliknuti <span class="gui"><span class="media"><span class="media media-image"><img src="figures/input-preferences.png" height="18" width="18" class="media media-inline" alt="preferences"></span></span></span> da pristupite dialogu opcija te metode, ako on postoji.</p></li>
<li class="list">
<p class="p">Some rarely used keyboard layout variants are not included by default in the list of
          available input sources when you click the <span class="gui">+</span> button. To expand the list you
          can open a terminal window by pressing <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>T</kbd></span></span>
          and run this command:</p>
<p class="p"><span class="cmd">gsettings set org.gnome.desktop.input-sources show-all-sources true</span></p>
</li>
</ul></div></div></div></div></div></div></div>
</div></div>
</div></div>
<div id="indicator" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Indikator izvora unosa</span></h2></div>
<div class="region"><div class="contents"><p class="p">You can quickly switch between selected sources using the input source
    indicator in the menu bar. The menu will display a short identifier for the
    current source, such as <span class="gui">En</span> for the standard English layout or a
    symbol in case of a source that uses a special input method, e.g. Chinese
    (Chewing). Click the input source indicator and select from the menu the
    source you want to use.</p></div></div>
</div></div>
<div id="shortcuts" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Kratice za tastaturu</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Takođe možete koristiti prečace na tastaturi da brzo prebacite između odabranih izvora za unos. Po defaultu prečac za prebacivanje na sljedeći izvor je  <span class="keyseq"><span class="key"><a href="windows-key.html" title='Šta je "Super" tipka?'><kbd>Super</kbd></a></span>+<span class="key"><kbd>Space</kbd></span></span>, ali vi ga možete promijeniti:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and
       select <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">U sekciji Osobno, kliknite <span class="gui">Text Entry</span>.</p></li>
<li class="steps"><p class="p">Kliknite na trenutnu definiciju prečica pod oznakom <span class="gui">Prebaci se na slijedeći izvor pomoću</span>.</p></li>
<li class="steps"><p class="p">When the shortcut definition has changed to <span class="gui">New accelerator...</span>,
       press the keys you want to use as the new shortcut.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div id="windows" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Podesite izvor unosa za sve prozore ili za svaki pojedinačno</span></h2></div>
<div class="region"><div class="contents">
<p class="p">When you use multiple sources, you can choose to have all windows use the
    same source or to set a different source for each window. Using a different
    source for each window is useful, for example, if you're writing an article
    in another language in a word processor window. Your input source selection will
    be remembered for each window as you switch between windows.</p>
<p class="p">Po defaultu, novi prozori će imati defaultni izvor za unos. Umjesto toga možete odabrati da koriste izvor za unos kojeg je koristio posljednji prozor.</p>
</div></div>
</div></div>
<div id="complex" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Complex input methods</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Recommended frameworks for input methods are <span class="em">IBus</span> and
    <span class="em">Fcitx</span>. The latter is the default framework in Ubuntu for Chinese,
    Japanese, Korean and Vietnamese.</p>
<p class="p">Input source options with input methods are only available if respective
    input method (IM) engine is installed. When you install a language, a suitable
    IM engine is automatically installed if applicable.</p>
<p class="p">For example, to prepare for typing Korean (Hangul) on an English system,
    follow these steps:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p"><span class="link"><a href="prefs-language-install.html" title="Instalirajte jezike">Install</a></span> Korean. One of the
        installed packages is <span class="em">fcitx-hangul</span>, the Hangul IM engine for
        Fcitx.</p></li>
<li class="steps"><p class="p">Close <span class="gui">Language Support</span> and open it again.</p></li>
<li class="steps"><p class="p">Select <span class="em">fcitx</span> as the <span class="gui">Keyboard input method system</span>.</p></li>
<li class="steps"><p class="p">Log out and log in again.</p></li>
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and
       select <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">U sekciji Osobno, kliknite <span class="gui">Text Entry</span>.</p></li>
<li class="steps"><p class="p">Click the <span class="gui">+</span> button, select <span class="em">Hangul (Fcitx)</span>, and click
       <span class="gui">Add</span>.</p></li>
</ol></div></div></div>
<p class="p">This will make <span class="em">Hangul</span> available in the Fcitx input source indicator
    in the menu bar. (The design differs from the IBus equivalent.)</p>
<p class="p">If you prefer some other IM engine than the one which is installed
    automatically when you install a language, you can
    <span class="link"><a href="addremove-install.html" title="Install additional applications">install</a></span> the IBus or Fcitx IM engine of
    your choice separately.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard.html" title="Tastatura">Tastatura</a><span class="desc"> — <span class="link"><a href="keyboard-layouts.html" title="Koristite alternativne izvore unosa">Input sources</a></span>, <span class="link"><a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">treperenje kursora</a></span>, <span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>super key</a></span>, <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">pristupačnost tastature</a></span>…</span>
</li>
<li class="links "><a href="prefs-language.html#textentry" title="Unos teksta">Unos teksta</a></li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="keyboard-shortcuts-set.html" title="Postavi kratice tastature">Postavi kratice tastature</a><span class="desc"> — Odredite ili promijenite kratice na tastaturi u <span class="gui">Tastatura</span> podešavanjima.</span>
</li>
<li class="links ">
<a href="tips-specialchars.html" title="Unesite posebne znakove">Unesite posebne znakove</a><span class="desc"> — Ukucajte znakove koji nisu pronadjeni na vasoj tastaturi, ukljucujuci strani alfabet, matematicke simbole i slicno.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
