<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prečo sú veci na obrazovke neostré alebo štvorčekované?</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> › <a class="trail" href="hardware.html#problems" title="Časté problémy">Problémy</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Prečo sú veci na obrazovke neostré alebo štvorčekované?</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Toto sa môže by spôsobené tým, že rozlíšenie obrazovky, ktoré máme nastavené, nie je správne pre našu obrazovku.</p>
<p class="p">To solve this, click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span> and go to <span class="gui">System Settings</span>. In the Hardware section, choose <span class="gui">Displays</span>. Try some of the <span class="gui">Resolution</span> options and set the one that makes the screen look better.</p>
</div>
<div id="multihead" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Keď sú pripojené viaceré zobrazovacie zariadenia</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Keď máme k počítaču pripojené dve zobrazovacie zariadenia (napríklad monitor a projektor), jednotlivé zariadenia môžu mať rôzne rozlíšenia. Grafická karta však môže umožňovať zobrazovanie iba jedného rozlíšenia naraz, preto obraz na jednom zo zariadení môže byť chybný.</p>
<p class="p">Môžeme nastaviť, aby tieto dve zobrazovacie zariadenia mali rozdielne rozlíšenia, no potom možno neuvidíme ten istý obraz na oboch zariadeniach súčasne. V takomto prípade budeme mať dve nezávislé obrazovky a okná budeme môcť prenášať z jednej obrazovky na druhú, no nebudeme vedieť rovnaké okno zobrazovať naraz na oboch obrazovkách.</p>
<p class="p">Ak chceme nastaviť obrazovky tak, aby každá mala svoje vlastné rozlíšenie, bude postupovať takto:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Click the <span class="em">system menu</span> <span class="media"><span class="media media-image"><img src="figures/system-devices-panel.svg" class="media media-inline" alt="Power cog icon"></span></span>, select
   <span class="gui">System Settings</span>, and open <span class="gui">Displays</span>.</p></li>
<li class="steps"><p class="p">Zrušíme zaškrtnutie voľby <span class="gui">Zrkadliť monitory</span>.</p></li>
<li class="steps"><p class="p">Select each display in turn from the gray box at the top of the <span class="gui">Displays</span> window. Change the <span class="gui">Resolution</span> until that display looks right.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="hardware-problems-graphics.html" title="Problémy s obrazom">Problémy s obrazom</a><span class="desc"> — Riešenie problémov s obrazom a grafikou.</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Súvisiace časti</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="look-resolution.html" title="Change the size or rotation of the screen">Change the size or rotation of the screen</a><span class="desc"> — Zmena rozlíšenia obrazovky a jej orientácie (otočenia).</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
