<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zmena pozadia pracovnej plochy</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="prefs-display.html" title="Vzhľad displeja; obrazovka">Vzhľad displeja; obrazovka</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zmena pozadia pracovnej plochy</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can change the image used for your desktop background, or set
it to a simple color or gradient.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikneme pravým tlačidlom na prázdne miesto na pracovnej ploche a zvolíme <span class="gui">Zmeniť pozadie plochy</span>.</p></li>
<li class="steps"><p class="p">Select an image or color. The settings are applied immediately.</p></li>
</ol></div></div></div>
<p class="p">There are three choices in the drop-down list on the top right.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list">
<p class="p">Môžeme si ako <span class="gui">Tapetu</span> vybrať jedno z profesionálnych pozadí, ktoré sa dodávajú spolu so systémom Ubuntu. S výnimkou predvoleného pozadia a sady astronomických pozadí, sú všetky ostatné pozadia vybrané ako víťazné pozadia zo súťaže Community Wallpaper Contest.</p>
<p class="p">Some wallpapers are partially
  transparent and allow a background color to show through. For these
  wallpapers, there will be a color selector button in the bottom-right
  corner.</p>
</li>
<li class="list"><p class="p"><span class="gui">Priečinok s obrázkami</span> si zvolíme, ak chceme použiť ako pozadie jednu zo svojich fotografií z priečinka Obrázky. Väčšina aplikácií na správu fotografií ukladá fotografie do spomínaného priečinka.</p></li>
<li class="list"><p class="p">Select <span class="gui">Colors &amp; Gradients</span> to just
  use a flat color or a linear gradient. Color selector buttons will appear
  in the bottom right corner.</p></li>
</ul></div></div></div>
<p class="p">You can also browse for any picture on your computer by clicking
the <span class="gui">+</span> button. Any picture you add this way will show up
under <span class="gui">Pictures Folder</span>. You can remove it from the list
by selecting it and clicking the <span class="gui">-</span> button. Removing a
picture from the list will not delete the original file.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="prefs-display.html" title="Vzhľad displeja; obrazovka">Vzhľad displeja; obrazovka</a><span class="desc"> — 
      <span class="link"><a href="look-background.html" title="Zmena pozadia pracovnej plochy">Background</a></span>,
      <span class="link"><a href="look-resolution.html" title="Change the size or rotation of the screen">size and rotation</a></span>,
      <span class="link"><a href="display-dimscreen.html" title="Nastavenie jasu obrazovky">brightness</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
