<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Skladby zakúpené z internetového obchodu sa nedajú prehrať</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="media.html" title="Zvuk, video a obrázky">Zvuk, video a obrázky</a> › <a class="trail" href="media.html#music" title="Hudba a prenosné prehrávače">Hudba a prehrávače</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Skladby zakúpené z internetového obchodu sa nedajú prehrať</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">If you downloaded some music from an online store you may find that it won't play on your computer, especially if you bought it on a Windows or Mac OS X computer and then copied it over.</p>
<p class="p">Toto sa môže stať, pretože hudba je vo formáte, ktorý náš počítač nepozná. Aby bolo možné skladbu prehrať, je potrebné mať nainštalovanú podporu správnych formátov zvuku - napríklad ak chceme prehrávať MP3 súbory, je potrebné nainštalovať podporu pre MP3. Ak nemáme podporu daného zvukového formátu, pravdepodobne sa zobrazí správa, ktorá nás na túto skutočnosť upozorní. V správe by sa tiež mali nachádzať inštrukcie pre inštaláciu podpory formátu, ktorý chceme prehrať.</p>
<p class="p">Ak máme nainštalovanú podporu potrebného zvukového formátu, no stále sa skladba nedá prehrať, táto skladba môže byť <span class="em">chránená proti kopírovaniu</span> (tiež sa uvádza, že je <span class="em">obmedzená pomocou DRM</span>). DRM je spôsob ako obmedziť prehrávanie iba na to zariadenie, na ktorom bola skladba zakúpená. Spoločnosť, ktorá nám skladbu predala, takto chráni predávané skladby pred kopírovaním. Ak má súbor DRM obmedzenia, pravdepodobne ju nebudeme môcť prehrávať - na prehrávanie takýchto skladieb je potrebný špeciálny softvér, no tento softvér väčšinou nefunguje v systémoch s jadrom Linux.</p>
<p class="p">Viac informácií o DRM sa nachádza na stránke <span class="link"><a href="http://www.eff.org/issues/drm" title="http://www.eff.org/issues/drm">Electronic Frontier Foundation</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#music" title="Hudba a prenosné prehrávače">Hudba a prehrávače</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
