<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ne mogu slušati pjesmu koju sam kupio na online muzičkoj prodavnici</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="media.html" title="Zvuk, video &amp; slike">Zvuk, video &amp; slike</a> › <a class="trail" href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Ne mogu slušati pjesmu koju sam kupio na online muzičkoj prodavnici</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako ste skinuli neku muziku sa online prodavnice i otkrijete da ne svira na vasem racunaru, pogotovo ako ste je kupili na Windows ili Mac OS X i onda kopirali .</p>
<p class="p">Ovo se moze desiti ako je muzika u formatu koju ne prepoznaje vas racunar. Da bi bili u mogucnosti da pustite pjestmu morate imati instaliranu podrsku za odgovarajuci audio format. Npr ako zelite da reproducirate MP3 fajlove morate imati instaliranu podrsku za MP3. Ako nemate instaliranu podrsku za odgovarajuci format trebali bi vidjeti poruku koja ukazuje na to kada pokusate da pokrenete pjesmu. Poruka bi rakodje trebala sadrzavati informacije kako instalirati podrsku za taj format.</p>
<p class="p">Ako imate instaliranu podršku za zvučni format pjesme ali još uvek ne možete da ga puštate, pjesma može biti <span class="em">zaštićena od umnožavanja</span> (poznato da je <span class="em">DRM ograničena</span>). DRM je način ograničavanja ko može da pušta pesmu i na kom uređaju može da je pušta. Firma koja vam je prodala pesmu upravlja time, a ne vi. Ako datoteka muzike ima DRM ograničenje, verovatno nećete biti u mogućnosti da je pustite — uopšteno potreban vam je poseban softver od prodavca da biste puštali DRM ograničene datoteke, ali ovaj softver često nije podržan na Linuksu.</p>
<p class="p">Možete naučiti više o DRM iz <span class="link"><a href="http://www.eff.org/issues/drm" title="http://www.eff.org/issues/drm">Electronic Frontier Foundation</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="media.html#music" title="Muzika i prenosivi plejeri">Muzika i plejeri</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
