<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Uređujte oznake u folderu</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="files.html" title="Datoteke, folderi &amp; pretraživanje">Datoteke</a> › <a class="trail" href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Uređujte oznake u folderu</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">In the file manager you can add bookmarks in the sidebar in order to navigate quickly to a folder.
Click on a bookmark to navigate to the associated folder. You can add, remove, or rename bookmarks:</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Dodajte oznaku:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite folder (ili lokaciju) koju želite označiti.</p></li>
<li class="steps"><p class="p">Click the <span class="gui">window menu</span> <span class="media"><span class="media media-image"><img src="figures/window-menu.png" class="media media-inline" alt="Window menu icon"></span></span>
    and select <span class="gui">Bookmark this Location</span>.
    (If the option is greyed out then the location has already been bookmarked.) The bookmark is added in the sidebar.</p></li>
</ol></div>
</div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">You can also add a bookmark by dragging a folder over to the sidebar and dropping it on <span class="gui">New bookmark</span>.</p></div></div></div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Remove a bookmark:</span></h2></div>
<div class="region"><ol class="steps"><li class="steps"><p class="p">Right-click on the bookmark in the sidebar and select <span class="gui">Remove</span> from the menu.</p></li></ol></div>
</div></div>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Preimenuj zabilješku:</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Right-click on the bookmark in the sidebar and select <span class="gui">Rename...</span> from the menu.</p></li>
<li class="steps"><p class="p">In the <span class="gui">Name</span> text box, type the new name for the bookmark and click <span class="gui">Rename</span>.</p></li>
</ol></div>
</div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Preimenovanje zabilješkia ne preimenovati mapu. Ako imate oznake na dvije različite mape u dva različita mjesta, ali koji svaki imaju isti naziv, knjižne oznake će imati isti naziv, i nećete biti u mogućnosti da ih razlikovati. U tim slučajevima, to je korisno dati oznaku ime osim imena mapi to ukazuje na.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="files.html#faq" title="Savjeti i pitanja">Savjeti i pitanja</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
