<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bežično Umrežavanje</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Bežično Umrežavanje</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu."><span class="title">Povežite se na bežičnu mrežu.</span><span class="linkdiv-dash"> — </span><span class="desc">Uđite na internet-bežično.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža"><span class="title">Alat za otkrivanje poteškoća u vezi bežičnih mreža</span><span class="linkdiv-dash"> — </span><span class="desc">Identifikujte i riješite probleme sa bežičnim povezivanjima</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-edit-connection.html" title="Edit a Wi-Fi connection"><span class="title">Edit a Wi-Fi connection</span><span class="linkdiv-dash"> — </span><span class="desc">Learn about the Wi-Fi connection settings.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-airplane.html" title="Isključite bežično povezivanje ( avionski način)"><span class="title">Isključite bežično povezivanje ( avionski način)</span><span class="linkdiv-dash"> — </span><span class="desc">Click the network menu on the menu bar and uncheck Enable Wi-Fi.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-adhoc.html" title="Kreirajte pristupnu tačku wireless-a"><span class="title">Kreirajte pristupnu tačku wireless-a</span><span class="linkdiv-dash"> — </span><span class="desc">Koristite ad-hoc mreže kako bi se omogućilo drugim uređajima za povezivanje s računalom i njegovim mrežnim vezama.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi."><span class="title">Ne mogu da vidim svoju bežičnu mrežu u listi.</span><span class="linkdiv-dash"> — </span><span class="desc">Bežično umrežavanje može biti isključeno,jer je previše bežičnih mreža u blizini,ili ste izvan dometa.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-vpn-connect.html" title="Poveži se na VPN"><span class="title">Poveži se na VPN</span><span class="linkdiv-dash"> — </span><span class="desc">VPNs vam omogućava povezivanje na lokalnu mrežu preko interneta. Naučite kako da postavite VPN konekciju.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu"><span class="title">Poveži se na skrivenu bežičnu mrežu</span><span class="linkdiv-dash"> — </span><span class="desc">Click the network menu on the menu bar and select Connect to Hidden Wi-Fi Network.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-manual.html" title="Ručno postavljanje mrežnih postavki"><span class="title">Ručno postavljanje mrežnih postavki</span><span class="linkdiv-dash"> — </span><span class="desc">Ako se mrežne postavke ne dodjeljuju same, možda ćete ih morati unijeti sami.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-noconnection.html" title="Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati"><span class="title">Ukucao sam ispravnu šifru ali se ipak ne mogu konektovati</span><span class="linkdiv-dash"> — </span><span class="desc">Dobro provjerite lozinku, pokušajte koristiti brojčanu lozinku umjesto lozinke, isključite pa uključite bežičnu karticu...</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?"><span class="title">Zašto je moja bežična mreža odspojena?</span><span class="linkdiv-dash"> — </span><span class="desc">Možete imati slab signal,ili Vam mreža ne dozvoljava da se povežete ispravno.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?"><span class="title">Šta su WEP i WPA?</span><span class="linkdiv-dash"> — </span><span class="desc">WEP i WPA su načini šifriranje podataka o bežičnim mrežama.</span></a></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a><span class="desc"> — <span class="link"><a href="net-wireless.html" title="Bežično Umrežavanje">Wireless</a></span>, <span class="link"><a href="net-wired.html" title="Ožičeno umrežavanje">žičani</a></span>, <span class="link"><a href="net-problem.html" title="Problemi sa mrežom"> problemi sa spajanjem</a></span>, <span class="link"><a href="net-browser.html" title="Web pretraživači">web pretraživač</a></span>, <span class="link"><a href="net-email.html" title="E-mail pošta i e-mail program">email računi</a></span>, <span class="link"><a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">ćaskanje</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Troubleshooting wireless connections</a></span>,
      <span class="link"><a href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi.">finding your Wi-Fi network</a></span>…
        </span>
</li>
<li class="links ">
<a href="net-general.html" title="Uvjeti i savjeti umrežavanja">Uvjeti  i savjeti umrežavanja</a><span class="desc"> — <span class="link"><a href="net-findip.html" title="Nađite Vašu IP adresu">Pronađite vašu IP adresu</a></span>, <span class="link"><a href="net-wireless-wepwpa.html" title="Šta su WEP i WPA?">WEP &amp; WPA sigurnost</a></span>, <span class="link"><a href="net-macaddress.html" title="Šta je MAC adresa?">MAC adrese</a></span>, <span class="link"><a href="net-proxy.html" title="Definišite postavke ovlaštenja">proxies</a></span>…</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
