<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Uvjeti  i savjeti umrežavanja</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Uvjeti  i savjeti umrežavanja</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-proxy.html" title="Definišite postavke ovlaštenja"><span class="title">Definišite postavke ovlaštenja</span><span class="linkdiv-dash"> — </span><span class="desc">Proxy filteri web stranica koje gledate,obično za kotrolu ili sigurnosne svrhe</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-findip.html" title="Nađite Vašu IP adresu"><span class="title">Nađite Vašu IP adresu</span><span class="linkdiv-dash"> — </span><span class="desc">Poznavanje Vaše IP adrese Vam može pomoći pri rješavanju mrežnih problema</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-security-tips.html" title="Ostati siguran na internetu"><span class="title">Ostati siguran na internetu</span><span class="linkdiv-dash"> — </span><span class="desc">Opći savjeti koje trebate imati na umu prilikom korištenja interneta</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-what-is-ip-address.html" title="Šta je IP adresa?"><span class="title">Šta je IP adresa?</span><span class="linkdiv-dash"> — </span><span class="desc">IP adresa je kao telefonski broj za Vaš računar.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-macaddress.html" title="Šta je MAC adresa?"><span class="title">Šta je MAC adresa?</span><span class="linkdiv-dash"> — </span><span class="desc">Jedinstveni identifikator dodijeljen mrežnom hardveru.</span></a></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a><span class="desc"> — <span class="link"><a href="net-wireless.html" title="Bežično Umrežavanje">Wireless</a></span>, <span class="link"><a href="net-wired.html" title="Ožičeno umrežavanje">žičani</a></span>, <span class="link"><a href="net-problem.html" title="Problemi sa mrežom"> problemi sa spajanjem</a></span>, <span class="link"><a href="net-browser.html" title="Web pretraživači">web pretraživač</a></span>, <span class="link"><a href="net-email.html" title="E-mail pošta i e-mail program">email računi</a></span>, <span class="link"><a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">ćaskanje</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to Wi-Fi</a></span>,
      <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>,
      <span class="link"><a href="net-wireless-edit-connection.html" title="Edit a Wi-Fi connection">Edit connection settings</a></span>,
      <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…
    </span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
