<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Često korišteni mrežni portovi</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Često korišteni mrežni portovi</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ovo je popis mrežnih portova obično koriste aplikacije koje pružaju usluge mreže, kao što su dijeljenje datoteka ili Remote Desktop gledanja. Možete promijeniti svoj ​​sustav firewall <span class="link"><a href="net-firewall-on-off.html" title="Control network traffic in and out of your computer"> blokirati ili dopustiti pristup </a></span> za tih aplikacija. Postoje tisuće lukama u uporabi, tako da ova tablica nije potpuna.</p>
<div class="table"><div class="inner"><div class="region"><table class="table" style="border-top-style: solid;">
<thead><tr>
<td><p class="p">Port</p></td>
<td><p class="p">Naziv</p></td>
<td><p class="p">Opis</p></td>
</tr></thead>
<tbody>
<tr class="shade">
<td><p class="p">5353/udp</p></td>
<td><p class="p">mDNS, Avahi</p></td>
<td><p class="p">Dopušta da sistemi pronalaze jedni duruge ,i opisuje koje servise oni nude, pri tome ne morate specificirati detalje ručno</p></td>
</tr>
<tr>
<td><p class="p">631/udp</p></td>
<td><p class="p">Štampanje</p></td>
<td><p class="p">Omogućuje slanje ispisa na štamač preko mreže.</p></td>
</tr>
<tr class="shade">
<td><p class="p">631/tcp</p></td>
<td><p class="p">Štampanje</p></td>
<td><p class="p">Dopušta da dijelite svoj štampač sa drugim ljudima preko mreže</p></td>
</tr>
<tr>
<td><p class="p">5298/tcp</p></td>
<td><p class="p">Prisustvo</p></td>
<td><p class="p">Dopušta obavijesti druge ljude na mreži o Vašem trenutnom statusu dopisivanja,kao što su "na vezi" ili "zauzat/a"</p></td>
</tr>
<tr class="shade">
<td><p class="p">5900/tcp</p></td>
<td><p class="p">Udaljena radna površina</p></td>
<td><p class="p">Dopušta Vam da dijelite Vašu radnu površinu  tako da drugi ljudi mogu da gledaju ili osiguraju udaljenju pomoć</p></td>
</tr>
<tr>
<td><p class="p">3689/tcp</p></td>
<td><p class="p">Dijeljenje muzike (DAAP)</p></td>
<td><p class="p">Dopušta da dijelite Vašu muzičku biblioteku sa drugim ljudima na Vašoj mreži</p></td>
</tr>
</tbody>
</table></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-security.html" title="Ostati siguran na internetu.">Ostati siguran na internetu.</a><span class="desc"> — <span class="link"><a href="net-antivirus.html" title="Da li mi treba anti-virusni softver?">Antivirus softver</a></span>, <span class="link"><a href="net-firewall-on-off.html" title="Control network traffic in and out of your computer">osnovni protupožarni zidovi</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-firewall-on-off.html" title="Control network traffic in and out of your computer">Control network traffic in and out of your computer</a><span class="desc"> — You can control network traffic in and out of your computer. This helps to keep your computer secure.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
