<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Alat za otkrivanje poteškoća u vezi bežičnih mreža</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="links nextlinks"><a class="nextlinks-next" href="net-wireless-troubleshooting-initial-check.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Sljedeći</a></div>
<div class="hgroup"><h1 class="title"><span class="title">Alat za otkrivanje poteškoća u vezi bežičnih mreža</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ovo je rijesavanje problema korak po korak koje vam pomaze da identifikujete i rijesite bezicni problem. Ako se ne mozete spojiti na bezicnu mrezu iz nekog razloga, pokusajte pratiti instrukcije ovdje.</p>
<p class="p">Proći ćemo kroz nekoliko slijedećih koraka da bismo spojli vaš računar na internet.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Napravite početnu provjeru</p></li>
<li class="steps"><p class="p">Prikupljanje informacija o vašem hardveru</p></li>
<li class="steps"><p class="p">Provjera vašeg hardvera</p></li>
<li class="steps"><p class="p">Pokušavanje kreiranja veze sa vašim bežičnim ruterom</p></li>
<li class="steps"><p class="p">Napravite provjeru modema i rutera</p></li>
</ol></div></div></div>
<p class="p">Za početak, kliknite na <span class="em">Dalje</span> vezu na desnoj strani stranice. Ova veza, i ostale poput ove na sljedećim stranicama, provest će vas kroz svaki korak u uputstvu.</p>
<div class="note" title="Napomena"><div class="inner">
<div class="title title-note"><h2><span class="title">Korištenje komandne linije</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Neke instrukcije u ovom vidiču će tražiti od vas da unesete komande u  <span class="em">command line</span> (Terminal). Terminal aplikaciju možete pronaći u <span class="gui">Dash</span>.</p>
<p class="p">Ako niste spretni u korištenju komandne linije, ne brinite - ovo uputstvo će vam objasniti svaki korak. Sve što trebate zapamtiti je da su komande case-sensitive (tako da ih morate kucati <span class="em">tačno</span> onako kako se pojavljuju ovdje), te pritisnuti  <span class="key"><kbd>Enter</kbd></span> poslije svake ukucane komande da je pokrenete.</p>
</div></div>
</div></div>
</div>
<div class="links nextlinks"><a class="nextlinks-next" href="net-wireless-troubleshooting-initial-check.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Sljedeći</a></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to Wi-Fi</a></span>,
      <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>,
      <span class="link"><a href="net-wireless-edit-connection.html" title="Edit a Wi-Fi connection">Edit connection settings</a></span>,
      <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…
    </span>
</li>
<li class="links "><a href="hardware.html#problems" title="Uobičajeni problemi">Hardverski problemi</a></li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Povežite se na bežičnu mrežu.</a><span class="desc"> — Uđite na internet-bežično.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
