<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Moj računar se  povezuje na krivu mrežu.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Moj računar se  povezuje na krivu mrežu.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Kada uključite računalo ili premjestite ga na drugo mjesto, vaš računar će se automatski pokušati povezati s bežičnim mrežama na koje ste bili povezani u prošlosti. Ako se pokušava spojiti na krivu mrežu svaki put ( a ne onu na koju ga želite povezati), učinite sljedeće:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui"> izbornik mreže</span> na traci izbornika i odaberite <span class="gui">Uredi Veze</span></p></li>
<li class="steps"><p class="p">Idite na <span class="gui"> Bežično </span> karticu i pronađite mrežu na koju se <span class="em"> ne </span> želite povezati</p></li>
<li class="steps"><p class="p">Kliknite jedanput na mrežu da je odaberete i klknite  <span class="gui">Obriši</span>. Vaš računar neće pokušavati više da se poveže na ovu mrežu.</p></li>
</ol></div></div></div>
<p class="p">Ako zelite da se spojite na mrezu koju ste izbrisali,jednostavno je izaberite sa liste bezicnih mreza koja se pojavi kada kliknete izbor mreza u meniju- kao sto bi se i konektovali na drugu mrezu.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-problem.html" title="Problemi sa mrežom">Problemi sa mrežom</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-troubleshooting.html" title="Alat za otkrivanje poteškoća u vezi bežičnih mreža">Troubleshooting wireless connections</a></span>,
      <span class="link"><a href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi.">finding your Wi-Fi network</a></span>…
        </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
