<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Problemi sa mrežom</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Problemi sa mrežom</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-othersconnect.html" title="Drugi korisnici se ne mogu povezati na internet."><span class="title">Drugi korisnici se ne mogu povezati na internet.</span><span class="linkdiv-dash"> — </span><span class="desc">Možete spasiti postavke (poput lozinke) na spajanje na mrežu pa svi koji koriste računar će biti u mogućnosti da se spoje na mrežu.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-slow.html" title="Internet izgleda sporo."><span class="title">Internet izgleda sporo.</span><span class="linkdiv-dash"> — </span><span class="desc">Druga stvar može biti preuzimanje, vi možete imati lošu konekciju, ili zauzetu tokom nekog dijela dana.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="power-nowireless.html" title="Ja nemam bežične mreže kada probudim moj računar"><span class="title">Ja nemam bežične mreže kada probudim moj računar</span><span class="linkdiv-dash"> — </span><span class="desc">Neki bezžični uređaji imaju poteškoća kada je Vaš računar suspendovan i kada se ne povraća ispravno.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wrongnetwork.html" title="Moj računar se povezuje na krivu mrežu."><span class="title">Moj računar se  povezuje na krivu mrežu.</span><span class="linkdiv-dash"> — </span><span class="desc">Uredite svoje postavke veze, i uklonite neželjene povezujuće opcije.</span></a></div>
</div>
<div class="links-twocolumn">
<div class="linkdiv "><a class="linkdiv" href="net-wireless-find.html" title="Ne mogu da vidim svoju bežičnu mrežu u listi."><span class="title">Ne mogu da vidim svoju bežičnu mrežu u listi.</span><span class="linkdiv-dash"> — </span><span class="desc">Bežično umrežavanje može biti isključeno,jer je previše bežičnih mreža u blizini,ili ste izvan dometa.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-nonm.html" title="Nema mreža menija na traci menija"><span class="title">Nema mreža menija na traci menija</span><span class="linkdiv-dash"> — </span><span class="desc">Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F2</kbd></span></span>.Ukucajte <span class="input">nm-applet</span>.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-othersedit.html" title="Ostali korisnici ne mogu uređivati mrežne konekcije"><span class="title">Ostali korisnici ne mogu uređivati mrežne konekcije</span><span class="linkdiv-dash"> — </span><span class="desc">Trebate isključiti <span class="gui">Dostupno svim korisnicima</span> mogućnost u podešavanjima mrežne oknekcje.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?"><span class="title">Zašto je moja bežična mreža odspojena?</span><span class="linkdiv-dash"> — </span><span class="desc">Možete imati slab signal,ili Vam mreža ne dozvoljava da se povežete ispravno.</span></a></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a><span class="desc"> — <span class="link"><a href="net-wireless.html" title="Bežično Umrežavanje">Wireless</a></span>, <span class="link"><a href="net-wired.html" title="Ožičeno umrežavanje">žičani</a></span>, <span class="link"><a href="net-problem.html" title="Problemi sa mrežom"> problemi sa spajanjem</a></span>, <span class="link"><a href="net-browser.html" title="Web pretraživači">web pretraživač</a></span>, <span class="link"><a href="net-email.html" title="E-mail pošta i e-mail program">email računi</a></span>, <span class="link"><a href="net-chat.html" title="Chat &amp; Drustveno Umrezavanje">ćaskanje</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="net-wireless.html" title="Bežično Umrežavanje">Bežično Umrežavanje</a><span class="desc"> — 
      <span class="link"><a href="net-wireless-connect.html" title="Povežite se na bežičnu mrežu.">Connect to Wi-Fi</a></span>,
      <span class="link"><a href="net-wireless-hidden.html" title="Poveži se na skrivenu bežičnu mrežu">Hidden networks</a></span>,
      <span class="link"><a href="net-wireless-edit-connection.html" title="Edit a Wi-Fi connection">Edit connection settings</a></span>,
      <span class="link"><a href="net-wireless-disconnecting.html" title="Zašto je moja bežična mreža odspojena?">Disconnecting</a></span>…
    </span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
