<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation">
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a> » </div>
<div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="power.html#problems" title="Problemi">Problemi sa snagom</a> » </div>
</div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zasto moj racunar nece ponovo da se uklojuci nakon sto sam ga suspendirao??</span></h1></div>
<div class="region">
<div class="contents"><p class="p">Ako <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">suspend</a></span> ili <span class="link"><a href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?">hibernate</a></span> vas racunar, i ako onda probate da nastavite ili da ga upalite ponovo, mozete otkriti da to ne radi kako ste ocekivali. Ovo moze biti zato sto suspendovanje i hibernacije nisu podrzani za vas hardver.</p></div>
<div id="resume" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Moj racunar je suspednovan i ne nastavlja.</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako suspendujete vas racunar i onda pritisnete tipku ili mis, trebao bi se podici i na displeju zatraziti sifru. Ako se to ne desi. pokuasjte pritiskanjem dugmeta za paljenje( ne drzati, vec pritisnuti jednom).</p>
<p class="p">Ako ovo ne pomaže, uvjerite se da je vaš monitor uključen i pokušajte pritisnuti tipku na tastaturi ponovo.</p>
<p class="p">Kao zadnje , ugasite racunar drzanjem tipke za paljenje 5-10 sekundi, izgubit ce te sav nespaseni rad tako. tada cete moci upaliti vas racunar ponovo.</p>
<p class="p">Ako se ovo desi svaki puta kada obustavite vaš računar, možda mogućnost obustavljanja ne radi sa vašim hardverom.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako vaš računar izgubi snagu i nema nikakav alternativni izvor snage (kao što je baterija), on će se ugasiti.</p></div></div></div></div>
</div></div>
</div></div>
<div id="hibernate" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Ni jedan moj program/dokument nije otvoren kada ponovo upalim računar</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako ste zamrznuli vaš računar i ponovo ste ga uključili, ali se nije otvorio nijedan vaš dokument ili program, vjerovatno nije uspeo da zamrzne ispravno. Ponekad se ovo dogodi zbog manjeg problema, a računar će biti u mogućnosti da zamrzne ispravno sledeći put kada to uradite. Ovo takođe može da se desi zato što ste instalirali ažuriranje softvera koje je zahtevalo ponovno pokretanje računara; u tom slučaju, računar se ugasio umesto da se zamrzne.</p>
<p class="p">takodje je moguce da vas racunar nije u stanju da hibernira jer hardver to ne podrzava. Ovo moze biti problem sa Linux drajverima za vas hardver, npr. Ovo mozete testirati hiberniranjem ponovo ako drugi put radi. A ako ne problem je vjerovatno u drajverima</p>
</div></div>
</div></div>
<div id="hardware" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Moja bežična konekcija (ili drugi hardver) ne radi kada probudim moj računar</span></h2></div>
<div class="region"><div class="contents">
<p class="p">If you suspend or hibernate your computer and then resume it again, you
  may find that your internet connection, mouse, or some other device doesn't
  work properly. This could be because the device's driver doesn't
  properly support suspend or hibernate. This is a <span class="link"><a href="hardware-driver.html" title="Što je to upravljački program?">problem with the driver</a></span> and not the device
  itself.</p>
<p class="p">Ako uredjaj ima prekidac za gasenje, pokusajte ga ugasiti pa upaliti. U vecini slucajeva, uredjaj ce proraditi. Ako je spojen putem USB kalba ili slicno probajte ga odspojiti pa spojiti ponovo.</p>
<p class="p">Ako ne možete ugasiti/isključiti uređaj, ili ako ne radi, možda trebate restartovati vaš računar da uređaj počne raditi ponovo.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="hardware-problems-graphics.html" title="Problemi ekrana.">Problemi ekrana.</a><span class="desc"> — Rješavanje problema ekrana i grafički problemi.</span>
</li>
<li class="links ">
<a href="power.html#problems" title="Problemi">Problemi sa snagom</a><span class="desc"> — Otklanjanje problema sa snagom i baterijama.</span>
</li>
</ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul>
<li class="links ">
<a href="power-nowireless.html" title="Ja nemam bežične mreže kada probudim moj računar">Ja nemam bežične mreže kada probudim moj računar</a><span class="desc"> — Neki bezžični uređaji imaju poteškoća kada je Vaš računar suspendovan i kada se ne povraća ispravno.</span>
</li>
<li class="links ">
<a href="power-hibernate.html" title="Kako vršim hibernaciju mog računara?">Kako vršim hibernaciju mog računara?</a><span class="desc"> — Hibernacija je normalno onemogućena jer nije potpuno podržana.</span>
</li>
<li class="links ">
<a href="power-closelid.html" title="Zašto se moj računar gasi kada zatvorim kapak?">Zašto se moj računar gasi kada zatvorim kapak?</a><span class="desc"> — Laptopi "zaspe" kada ih poklopite, kako bi sačuvali snagu.</span>
</li>
</ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
