<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Moj računar se jako zagrijava</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="hardware.html" title="Hardware i upravljački programi">Hardver</a> › <a class="trail" href="hardware.html#problems" title="Uobičajeni problemi">Problemi</a> » <a class="trail" href="power.html#problems" title="Problemi">Problemi sa snagom</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Moj računar se jako zagrijava</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Vecina racunara se ugrije nakon odredjenog vremenea, a neki mogu postati pravo vruci. Ovo je normalno: to je jednostavno nacin na koji se hladi vas racunar, Kako god, ako se vas racunar puno ugrije to moze biti znak da se pregrijava, sto moze prouzrokovati stetu.</p>
<p class="p">Most laptops get reasonably warm once you have been using them for a while.
It's generally nothing to worry about - computers produce a lot of heat and
laptops are very compact, so they need to remove their heat rapidly and their
outer casing warms up as a result. Some laptops do get too hot, however, and
may be uncomfortable to use. This is normally the result of a poorly-designed
cooling system. You can sometimes get additional cooling accessories which fit
to the bottom of the laptop and provide more efficient cooling.</p>
<p class="p">If you have a desktop computer which feels hot to the touch, it may have
insufficient cooling. If this concerns you, you can buy extra cooling fans or
check that the cooling fans and vents are free from dust and other blockages.
You might want to consider putting the computer in a better-ventilated area too
- if kept in confined spaces (e.g. in a cupboard), the 
computer's cooling system may not be able to remove heat and circulate cool air fast enough.</p>
<p class="p">Neki ljudi se brinu o zdravstvenim rizicima korišćenja vrućih prenosnih računara. Postoje sugestije da dugotrajno korišćenje vrućeg prenosnog računara na krilu može vjerovatno da umanji (mušku) plodnost, a postoje i izveštaji o zadobijenim manjim opekotinama (u krajnjim slučajevima). Ako ste zabrinuti zbog ovih potencijalnih problema, možda ćete željeti da se posavetujete sa lekarom za savet. Naravno, možete jednostavno da izaberete da ne držite prenosni računar na krilu.</p>
<p class="p">Vecina modernih racunara ce se ugasiti ako se pregriju. da se spase od ostecenja. Ako se vas racunar gasi stalno, to moze biti razlog. Ako vam se racunar pregrijava, vjerovatno gd treba odnijeti na servis.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="power.html#problems" title="Problemi">Problemi sa snagom</a><span class="desc"> — Otklanjanje problema sa snagom i baterijama.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
