<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Korisničke &amp; sistemske postavke</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Korisničke &amp; sistemske postavke</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="links-grid ">
<div class="links-grid-link"><a href="startup-applications.html" title="Aplikacije pri pokretanju">Aplikacije pri pokretanju</a></div>
<div class="desc"><span class="desc">Odaberite koje aplikacije treba pokrenuti kada se prijavite.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="user-accounts.html" title="Korisnički nalozi">Korisnički nalozi</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="user-add.html" title="Dodaj novi korisnički račun.">Dodavanje korisnika</a></span> ili <span class="link"><a href="shell-guest-session.html" title="Pokrenite ograničenu gost sesiju">gost korisnik</a></span>, <span class="link"><a href="user-changepassword.html" title="Promijenite(mijenjajte) Vašu šifru.">izmjena lozinke</a></span>, <span class="link"><a href="user-admin-change.html" title="Mijenjajte(promijenite) ko ima administrativne privilegije">administratori</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="mouse.html" title="Miš">Miš</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="mouse-lefthanded.html" title="Miš za ljevoruke">Ljevak</a></span>, <span class="link"><a href="mouse-sensitivity.html" title="Promijenite brzinu miša ili dodirne površine">brzina i osjetljivost</a></span>, <span class="link"><a href="mouse-touchpad-click.html" title="Klikajte, povucite, ili skrolajte pomoću touchpad-a.">dodirna površina, klik i listanje</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="accounts.html" title="Online računi">Online računi</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="accounts-add.html" title="Dodaj korisnički nalog">Dodaj račune, </a></span> <span class="link"><a href="accounts-remove.html" title="Izbrišite račun">Ukloni račune, </a></span> <span class="link"><a href="accounts-disable-service.html" title="Isključi korisničke usluge">Isključi servise</a></span></span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs-display.html" title="Prikaži &amp; ekran">Prikaži &amp; ekran</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="look-background.html" title="Promijenite pozadinu">Pozadina</a></span>, <span class="link"><a href="look-resolution.html" title="Promijenite veličinu rotacije ekrana">veličina i rotacija</a></span>, <span class="link"><a href="display-dimscreen.html" title="Postavite osvjetljenje ekrana">svjetlost</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="prefs-language.html" title="Regija i jezik">Regija i jezik</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="prefs-language-install.html" title="Instalirajte jezike">Install languages</a></span>,
      <span class="link"><a href="session-language.html" title="Promjenite jezik koji koristite">change language</a></span>,
      <span class="link"><a href="session-formats.html" title="Promjenite formate za datum i mjerenje">region and formats</a></span>,
      <span class="link"><a href="keyboard-layouts.html" title="Koristite alternativne izvore unosa">input sources</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="security-settings.html" title="Security &amp; Privacy">Security &amp; Privacy</a></div>
<div class="desc"><span class="desc">Change some security and privacy settings.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="power.html" title="Snaga &amp; baterija">Snaga &amp; baterija</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="power-suspend.html" title="Šta se dešava kada obustavim moj računar?">Suspend</a></span>,
      <span class="link"><a href="power-batterylife.html" title="Koristite manje snage i unaprijedite trajanje baterije">energy savings</a></span>,
      <span class="link"><a href="shell-exit.html#shutdown" title="Isključiti ili restartovati">power off</a></span>,
      <span class="link"><a href="power-whydim.html" title="Zašto se moj ekran zamagli nakon nekog vremena?">screen dimming</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="keyboard.html" title="Tastatura">Tastatura</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="keyboard-layouts.html" title="Koristite alternativne izvore unosa">Input sources</a></span>, <span class="link"><a href="keyboard-cursor-blink.html" title="Napravite da kursor tastature treperi.">treperenje kursora</a></span>, <span class="link"><a href="windows-key.html" title='Šta je "Super" tipka?'>super key</a></span>, <span class="link"><a href="a11y.html#mobility" title="Oštećenje mobilnosti">pristupačnost tastature</a></span>…</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="color.html" title="Upravljanje bojama">Upravljanje bojama</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="color-whyimportant.html" title="Zašto je upravljanje bojama važno?">Why is this important</a></span>,
      <span class="link"><a href="color.html#profiles" title="Profili boja">Color profiles</a></span>,
      <span class="link"><a href="color.html#calibration" title="Kalibracija">How to calibrate a device</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="clock.html" title="Vrijeme &amp; datum">Vrijeme &amp; datum</a></div>
<div class="desc"><span class="desc">
      <span class="link"><a href="clock-set.html" title="Promijenite datum i vrijeme">Set time and date</a></span>,
      <span class="link"><a href="clock-timezone.html" title="Prikaži druge vremenske zone">timezone</a></span>,
      <span class="link"><a href="clock-calendar.html" title="Kalendarski sastanci">calendar and appointments</a></span>…
    </span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="wacom.html" title="Wacom grafički tablet">Wacom grafički tablet</a></div>
<div class="desc"><span class="desc">Prilagodite postavke vašeg Wacom tableta.</span></div>
</div>
<div class="links-grid ">
<div class="links-grid-link"><a href="media.html#sound" title="Osnovni zvuk">Zvuk</a></div>
<div class="desc"><span class="desc"><span class="link"><a href="sound-volume.html" title="Promjenite jačinu zvuka">Jačina</a></span>, <span class="link"><a href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice.">zvučnici i slušaliceheadphones</a></span>, <span class="link"><a href="sound-usemic.html" title="Koristite drugi mikrofon">mikrofoni</a></span>…</span></div>
</div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="index.html" title="Ubuntu Desktop Priručnik">Ubuntu Desktop Priručnik</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
