<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nastavenia tlačiarne</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="hardware.html" title="Hardvér a ovládače">Hardvér</a> » <a class="trail" href="printing.html" title="Tlačiť">Tlačiť</a> › <a class="trail" href="printing.html#setup" title="Nastavenia tlačiarne">Setup</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Nastavenia tlačiarne</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">You can set up a network printer or set up a printer using a USB cable.</p>
<p class="p">To set up a network printer:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">It's assumed that the printer is connected to your network.
    Click the icon at the far right of the <span class="gui">menu bar</span> and select
    <span class="gui">System Settings</span>.</p></li>
<li class="steps"><p class="p">Open <span class="gui">Printers</span>.</p></li>
<li class="steps"><p class="p">Click <span class="gui">Add</span>.</p></li>
<li class="steps"><p class="p">If your printer is listed in the <span class="gui">Devices</span> list, select it and goto step 7.</p></li>
<li class="steps"><p class="p">It's assumed that you know your printer's IP address. Select <span class="gui">Find Network Printer</span>,
    enter the IP address in the <span class="gui">Host</span> field, 
    and click <span class="gui">Find</span>.</p></li>
<li class="steps"><p class="p">The system should now have found your printer. 
    If the <span class="gui">Host</span> field does not display the IP address, enter it again.</p></li>
<li class="steps"><p class="p">Click <span class="gui">Forward</span> and wait while the system searches for drivers.</p></li>
<li class="steps"><p class="p">Choose a driver and install it.</p></li>
<li class="steps"><p class="p">You can customize the printer's name, description, and location if you like.
    When finished, click <span class="gui">Apply</span>.</p></li>
<li class="steps"><p class="p">You can now print a test page or click <span class="gui">Cancel</span> to skip that step.</p></li>
</ol></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">If you've set up a network printer and it won't print, check the <span class="gui">Device URI</span> field in the printer settings. It should display the printer's IP address. If it doesn't then correct it.</p></div></div></div></div>
<p class="p"> </p>
<p class="p">To set up a printer using a USB cable:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Uistite sa, že tlačiareň je zapnutá.</p></li>
<li class="steps"><p class="p">Connect the printer to your computer using the cable. You
 may see activity on the screen as the system searches for drivers, and you may
 be asked to authenticate to install them.</p></li>
<li class="steps"><p class="p">A message will appear when the system is finished setting up the
 printer. Select <span class="gui">Print Test Page</span> to print a test page, or
 <span class="gui">Options</span> to make additional changes in the printer setup.</p></li>
<li class="steps"><p class="p">If you wish to, you can share the printer on the network. To do this,
    if necessary open <span class="gui">Printers</span>, select <span class="gui">Server</span> ^ <span class="gui">Settings</span> from the menu bar and check
    <span class="gui">Publish shared printers connected to this system</span>.</p></li>
</ol></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">If multiple printer drivers are available, you may be
    asked to choose a driver. To use the recommended driver, just click <span class="gui">Forward</span>
    on the make and model screens.</p></div></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">If the system cannot find a driver,
    check the printer manufacturer's website for a driver.</p></div></div></div></div>
<p class="p"> </p>
<p class="p">After you set up the printer, you may wish to
 <span class="link"><a href="printing-setup-default-printer.html" title="Nastavte predvolenú tlačiareň">change your default printer</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="printing.html#setup" title="Nastavenia tlačiarne">Nastavenia tlačiarne</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
