<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Prijavite problem u Ubuntu-u</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="more-help.html" title="Još pomoći">Još pomoći</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Prijavite problem u Ubuntu-u</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Ako primjetite problem u Ubuntu-u, može te podnijeti <span class="em">izvještaj o greški</span>.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps">
<p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F2</kbd></span></span> i ukucajte <span class="input">ubuntu-greška imeprograma</span></p>
<p class="p">Ako imate hardverskih problema ili ne znate naziv programa koji je uticao, samo ukucajte <span class="input">ubuntu-greška</span></p>
</li>
<li class="steps"><p class="p">Nakon pokretanja neke od gore navedenih komandi Ubuntu ce skupiti informacije o problemu. Ovo moze potrajati par minuta. Pregledajte skupljene informacije ako zelite. pritisnite <span class="gui">Send</span> da nastavite.</p></li>
<li class="steps"><p class="p">A new web browser tab will open to continue processing the bug data. Ubuntu uses the 
website <span class="app">Launchpad</span> to manage its bug reports. If you do not
have a Launchpad account, you will need to register for one to file a bug and receive
email updates about its status. You can do this by clicking <span class="gui">Create a new account</span>.</p></li>
<li class="steps"><p class="p">Nakon logina u Lacunchpad, upišite opis problema u polje.</p></li>
<li class="steps"><p class="p">After clicking <span class="gui">Next</span> Launchpad will search for similar bugs in case the bug you
are reporting has already been reported. If the bug has already been reported, you can mark that bug as 
also affecting you. You can also subscribe to the bug report to receive updates about progress with
fixing it. If the bug has not already been reported, click <span class="gui">No, I need to report a new bug</span>.</p></li>
<li class="steps">
<p class="p">Popunite polje za opis sa što je moguće više informacija. Važno je da navedete tri stvari:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">Šta ste očekivali da se dogodi</p></li>
<li class="list"><p class="p">Šta se zapravo dogodilo</p></li>
<li class="list"><p class="p">Ako je moguće, najmanja serija koraka potrebnih da se to dogodi, gdje je prvi korak "pokretanje programa"</p></li>
</ul></div></div></div>
</li>
<li class="steps"><p class="p">Vašem izvještaju će biti dodijeljen ID broj, i njegov status će biti obnavljan kako se bude radilo s njim. Hvala što pomažet da Ubuntu bude bolji!</p></li>
</ol></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako dobijete "Ovo nije orginalni Ubuntu paket" gresko, znaci da softver za koji pokusavate prijaviti gresku nije oficijelan. U tom slucaju ne mozete koristiti Ubuntu ugradjeni alat za prijavu gresaka.</p></div></div></div></div>
<p class="p">Za više informacija kako izvjestiti o greškama u Ubuntu-u, molimo Vas pročitajte opsežnu  <span class="link"><a href="https://help.ubuntu.com/community/ReportingBugs" title="https://help.ubuntu.com/community/ReportingBugs">online dokumentaciju</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="more-help.html" title="Još pomoći">Još pomoći</a><span class="desc"> — <span class="link"><a href="about-this-guide.html" title="O ovom vodiču">Savjeti za korištenje ovog priručnika</a></span>, <span class="link"><a href="get-involved.html" title="Učestvujte u poboljšanju ovog uputstva">pomozite da poboljšamo ovaj priručnik </a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="get-involved.html" title="Učestvujte u poboljšanju ovog uputstva">Učestvujte u poboljšanju ovog uputstva</a><span class="desc"> — Kako i gdje prijaviti probleme s ovim temama pomoći.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
