<!DOCTYPE html>
<html lang=tl>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Report a problem in Ubuntu</title>
<link rel="stylesheet" type="text/css" href="tl.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Guide"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Help"></span></span> Ubuntu Desktop Guide</a> » <a class="trail" href="more-help.html" title="Get more help">Get more help</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Report a problem in Ubuntu</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">If you notice a problem in Ubuntu, you can file a <span class="em">bug report</span>.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps">
<p class="p">Type <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F2</kbd></span></span> and type
<span class="input">ubuntu-bug nameofprogram</span></p>
<p class="p">If you have a hardware issue or don't know the name of the program affected,
    just type <span class="input">ubuntu-bug</span></p>
</li>
<li class="steps"><p class="p">After running one of the above commands, Ubuntu will gather information about the bug. This may take a few minutes.
Review the collected information if you wish.
Click <span class="gui">Send</span> to continue.</p></li>
<li class="steps"><p class="p">A new web browser tab will open to continue processing the bug data. Ubuntu uses the 
website <span class="app">Launchpad</span> to manage its bug reports. If you do not
have a Launchpad account, you will need to register for one to file a bug and receive
email updates about its status. You can do this by clicking <span class="gui">Create a new account</span>.</p></li>
<li class="steps"><p class="p">After logging in to Launchpad, enter a description of the problem in the summary field.</p></li>
<li class="steps"><p class="p">After clicking <span class="gui">Next</span> Launchpad will search for similar bugs in case the bug you
are reporting has already been reported. If the bug has already been reported, you can mark that bug as 
also affecting you. You can also subscribe to the bug report to receive updates about progress with
fixing it. If the bug has not already been reported, click <span class="gui">No, I need to report a new bug</span>.</p></li>
<li class="steps">
<p class="p">Fill in the description field with as much information as you can. It's 
important that you specify three things:</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">What you expected to happen</p></li>
<li class="list"><p class="p">What actually happened</p></li>
<li class="list"><p class="p">If possible, a minimal series of steps necessary to make it happen, where step 1 is "start the
program"</p></li>
</ul></div></div></div>
</li>
<li class="steps"><p class="p">Your report will be given an ID number, and its status will be updated as it is being dealt with. Thanks for helping make Ubuntu better!</p></li>
</ol></div></div></div>
<div class="note" title="Note"><div class="inner"><div class="region"><div class="contents"><p class="p">If you get the "This is not a genuine Ubuntu package" error, it means that
the software you are trying to report a bug about is not from the official Ubuntu
repositories. In this case, you cannot use Ubuntu's built-in bug reporting tool.</p></div></div></div></div>
<p class="p">For more information about reporting bugs in Ubuntu, please read the extensive <span class="link"><a href="https://help.ubuntu.com/community/ReportingBugs" title="https://help.ubuntu.com/community/ReportingBugs">online documentation</a></span>.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">More Information</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="more-help.html" title="Get more help">Get more help</a><span class="desc"> — 
        <span class="link"><a href="about-this-guide.html" title="About this guide">Tips on using this guide</a></span>, 
        <span class="link"><a href="get-involved.html" title="Participate to improve this guide">help improve this guide</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">See Also</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="get-involved.html" title="Participate to improve this guide">Participate to improve this guide</a><span class="desc"> — How and where to report problems with these help topics.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
