<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Dijelite vaš desktop</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="net.html" title="Umrežavanje, web, elektronska pošta i ćaskanje">Umrežavanje, web, elektronska pošta i ćaskanje</a> » <a class="trail" href="sharing.html" title="Dijeljenje">Dijeljenje</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Dijelite vaš desktop</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete omogućiti drugim ljudima da vide i kontrolišu vaš desktop sa drugog računara sa programom za pregledanje desktopa. Podesite  <span class="app">Dijeljenje Desktopa</span> tako da dopušta pristup vašem desktopu i postavite sigurnosne postavke.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">In the <span class="gui">Dash</span>, open <span class="app">Desktop Sharing</span>.</p></li>
<li class="steps"><p class="p">Da omogućite drugima da vide vaš desktop, odaberite <span class="gui">Omogućite drugima da vide vaš desktop</span>. Ovo znači da će drugi moći pokušati da se povežu sa vašim računarom i vide šta je na vašem ekranu.</p></li>
<li class="steps"><p class="p">Da dopustitte drugima da koriste vas racunar izaberite <span class="gui">Allow other users to control your desktop</span>. Ovo moze dozvoliti drugima da pomjeraju misem, pokrecu aplikacije, i pretrazuju stvcari na vasem racunaru, ovisno od postavki koje trenutno koristite.</p></li>
</ol></div></div></div>
</div>
<div id="security" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Sigurnost</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Važno je da uzmete u obir u potpunosti značenje svake sigurnosne opcije prije nego što je promjenite.</p>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">Odobrite pristup vašoj mašini</dt>
<dd class="terms">
<p class="p">Ako zelite biti u mogucnosti da izaberete da li da dozvolite nekome da koristi vas racunar, izaberite <span class="gui">You must confirm each access to this machine</span>.Ako iskljucite ovu opciju, necete biti upitani dali zelite da dozvolite da se spoji na vas racunar.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ova mogućnost je zadano omogućena.</p></div></div></div></div>
</dd>
<dt class="terms">Omogućite šifru</dt>
<dd class="terms">
<p class="p">Da zahtjevate od drugih ljudi da koristte sifru kada se spajaju na vas racunar, izaberite <span class="gui">Require the user to enter this password</span>.  Ako ne koristite ovu opciju svako moze pokusati da vidi vas desktop.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ova mogućnost je zadano onemogućena, ali je trebate omogućiti i postaviti sigurnosnu šifru.</p></div></div></div></div>
</dd>
<dt class="terms">Dopustite pristup vašem desktopu preko Interneta</dt>
<dd class="terms">
<p class="p">Ako vas ruter podrzava UPnP Internet Gateway Device Protocol i ako je upaljen, mozete dozvoliti ostalim ljudima koji nisu u vasoj lokalnoj mrezi da vide vas desktop. Da dozvolite ovo izaberite <span class="gui">Automatically configure UPnP router to open and forward ports</span>. U drugom slucaju mozete konfigurisati ruter rucno.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ova mogućnost je zadano onemogućena</p></div></div></div></div>
</dd>
</dl></div></div></div>
</div></div>
</div></div>
<div id="notification-icon" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Prikaz ikone površine obavijesti</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Da bi bili u mogucnosti da odspojite nekoga ko gleda vas desktop, morate ukljuciti ovu opciju. Ako izaberete <span class="gui">Always</span>, ikona ce biti vidljiva bez obzira da li neko vidi vas desktop ili ne.</p>
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako je ova mogućnost isključena, moguće je da se neko poveže na vaš desktop bez vašeg znanja, zavisno od vaših postavki privatnosti.</p></div></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="sharing.html" title="Dijeljenje">Dijeljenje</a><span class="desc"> — 
      <span class="link"><a href="sharing-desktop.html" title="Dijelite vaš desktop">Desktop sharing</a></span>,
      <span class="link"><a href="files-share.html" title="Dijeli i prebaci datoteke">Share files</a></span>…
    </span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
