<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Sljedeća radna površina</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="shell-overview.html" title="Desktop, programi &amp; prozori">Radna površina</a> › <a class="trail" href="shell-overview.html#apps" title="Aplikacije i prozori">Aplikacije i prozori</a> » <a class="trail" href="shell-windows.html" title="Prozori i radni prostori.">Prozori i radni prostori.</a> › <a class="trail" href="shell-windows.html#working-with-workspaces" title="Rad sa radnim prostorima.">Radne površine</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Sljedeća radna površina</span></h1></div>
<div class="region">
<div class="contents">
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Pogledajte <span class="link"><a href="shell-workspaces.html" title="Šta je radna površina, i kako će mi pomoći?">Šta je radna površina, i kako će mi pomoći?</a></span> o omogućavanju radnih površina.</p></div></div></div></div>
<div class="terms"><div class="inner"><div class="region"><dl class="terms">
<dt class="terms">KOrištenje miša:</dt>
<dd class="terms"><p class="p">Open the <span class="link"><a href="unity-launcher-intro.html" title="Koristite Launcher da biste pokrenuli aplikacije">Launcher</a></span> and click the <span class="gui">workspace switcher</span> button near the bottom. Double-click on any window or workspace to switch to it, or press the workspace switcher button again to return to your previous workspace.</p></dd>
<dt class="terms">Korištenje tastature:</dt>
<dd class="terms"><div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>→</kbd></span></span> da se pomjerite na radnu površinu koja se nalazi desno od trenutne.</p></li>
<li class="list"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>←</kbd></span></span> da se pomjerite na radnu površinu koja se nalazi lijevo od trenutne.</p></li>
<li class="list"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>↓</kbd></span></span> da se pomjerite na radnu površinu koja se nalazi ispod trenutne.</p></li>
<li class="list"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>↑</kbd></span></span> da se pomjerite na radnu površinu koja se nalazi iznad trenutne.</p></li>
</ul></div></div></div></dd>
</dl></div></div></div>
<div class="media media-image"><div class="inner"><img src="figures/unity-windows.png" class="media media-block" alt=""></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="shell-windows.html#working-with-workspaces" title="Rad sa radnim prostorima.">Rad sa radnim prostorima.</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="shell-workspaces.html" title="Šta je radna površina, i kako će mi pomoći?">Šta je radna površina, i kako će mi pomoći?</a><span class="desc"> — Radne površne su način grupisanja prozora na vašem desktopu.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
