<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Koristite različite zvučnike i slušalice.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="media.html#sound" title="Osnovni zvuk">Zvuk</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Koristite različite zvučnike i slušalice.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Možete koristiti extrerne zvučnike ili slusaluče sa Vašim računatom. Zvučnici se obično povezuju kružnim TRS (<span class="em">tip, ring, sleeve</span>) priključkom preko USB-a.</p>
<p class="p">Ako vaši zvučnici ili slušalice imaju TRS priključak, samo ga priključite u odgovarajću priključnicu na vašem računaru. Većina računara ima dve priključnice: jednu za mikrofone a drugu za zvučnike. Potražite sliku slušalica pored priključnice. Zvučnici ili slušalice priključeni na TRS priključnicu će obično biti korišćeni po osnovi. Ako ne, pogledajte uputstva ispod za izbor osnovnog uređaja.</p>
<p class="p">Some computers support multi-channel output for surround sound. This usually
  uses multiple TRS jacks, which are often color-coded. If you are unsure which
  plugs go in which sockets, you can test the sound output in the sound settings.
  Click the <span class="gui">sound menu</span> on the <span class="gui">menu bar</span> then click
  <span class="gui">Sound Settings</span>. Select your speakers in the list
  of devices, then click <span class="gui">Test Sound</span>. In the pop-up window, click the
  button for each speaker. Each button will speak its position only to the channel
  corresponding to that speaker.</p>
<p class="p">Ako imate USB zvucnike ili slusalice, ili analogne slusalice spojene u USB zvucnu karticu, spojite ih na uSB port. USb zvucnici se ponasaju kao odvojeni audio uredjaj tako da cete morati izabrati koje zvucnike zelite koristiti.</p>
<div class="steps"><div class="inner">
<div class="title title-steps"><h2><span class="title">Odaberite zadani ulazni audio uređaj</span></h2></div>
<div class="region"><ol class="steps">
<li class="steps"><p class="p">Kliknite <span class="gui">zvuk meni</span> na <span class="gui">traci menija</span> i odaberite <span class="gui">Podešavanja zvuka</span>.</p></li>
<li class="steps"><p class="p">Na <span class="gui">Izlaz</span>  tabu, odaberite uređaj iz liste uređaja.</p></li>
</ol></div>
</div></div>
<p class="p">Ako ne vidite vas uredjaj na <span class="gui">Output</span> tabu. provjerite <span class="gui">Hardware</span> tab. Izaberite vas uredjaj i probajte drugcije profile.</p>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="media.html#sound" title="Osnovni zvuk">Osnovni zvuk</a><span class="desc"> — <span class="link"><a href="sound-volume.html" title="Promjenite jačinu zvuka">Jačina</a></span>, <span class="link"><a href="sound-usespeakers.html" title="Koristite različite zvučnike i slušalice.">zvučnici i slušaliceheadphones</a></span>, <span class="link"><a href="sound-usemic.html" title="Koristite drugi mikrofon">mikrofoni</a></span>…</span>
</li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="sound-usemic.html" title="Koristite drugi mikrofon">Koristite drugi mikrofon</a><span class="desc"> — Koristite analogni ili USB mikrofon i odaberite zadani ulazni uređaj.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
