<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Promijenite(mijenjajte) Vašu šifru.</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#passwords" title="Šifre">Šifre</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Promijenite(mijenjajte) Vašu šifru.</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Nije loša ideja da promijenite Vašu šifru s vremena na vrijeme,pogotovo ako mislite da je neko drugi zna.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikom na ikonu na desnoj strani <span class="gui">menu trake</span> i odabirom <span class="gui">Sistemske Postavke</span>.</p></li>
<li class="steps"><p class="p">Otvorite  <span class="gui">Korisnički račun</span>.</p></li>
<li class="steps">
<p class="p">Pritisnite oznaku do <span class="gui">Šifre</span>.</p>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Oznaka bi trebala izgledati kao serija tacaka ili kutijca ako već imate šifru.</p></div></div></div></div>
</li>
<li class="steps">
<p class="p">Unesite Vasu trenutnu šifru, zatim novu šifru. Ponovo unesite Vašu novu šifru u <span class="gui">Potvrdite šifru</span> polju.</p>
<p class="p">Takodje mozete kliknuti dugme sljedeće do <span class="gui">Nova šifra</span> polja da izaberete slucajno odabranu sigurnu šifru. Ove šifre su teške za druge da pogote,ali mogu biti teške i za zapamtiti, pa pripazite.</p>
</li>
<li class="steps"><p class="p">Kliknite<span class="gui">Promijeni</span>.</p></li>
</ol></div></div></div>
<p class="p">Pobrinete se da <span class="link"><a href="user-goodpassword.html" title="Odaberite sigurne šifre.">odaberete dobru šifru</a></span>. Ovo će Vam pomoći da Vam račun bude siguran.</p>
</div>
<div id="changepass" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Promijenite keyring šifru</span></h2></div>
<div class="region"><div class="contents">
<p class="p">Ako izmijenite vašu lozinku prijavljivanja, može postati neusaglašena sa <span class="em">lozinkom priveska</span>. Privezak vam omogućava da ne morate da pamtite veliki broj različitih lozinki tako što će vam tražiti jednu <span class="em">glavnu</span> lozinku da biste pristupili svim ostalim. Ako izmijenite vašu korisničku lozinku (pogledajte iznad), vaša lozinka priveska će ostati ista kao ona stara. Da izmenite lozinku priveska (da odgovara vašoj lozinki prijavljivanja):</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Otvorite aplikaciju <span class="app">Passwords and Keys</span> preko <span class="gui">Crtice</span>.</p></li>
<li class="steps"><p class="p">U imeniju <span class="gui">Pregled</span>, provjerite da li je izabrano <span class="gui">Prema privjesku</span>.</p></li>
<li class="steps"><p class="p">U bočnoj površi <span class="gui">Lozinke</span>, kliknite desnim tasterom miša na <span class="gui">Prsten ključeva za prijavu</span> i izaberite <span class="gui">Izmijeni lozinku</span>.</p></li>
<li class="steps"><p class="p">Unesite Vašu<span class="gui">Staru sšfru</span>, a zatim Vasu novu <span class="gui">Šifru</span>, i <span class="gui">Potvrdite</span> Vašu novu šifru ponovnim unosenjem iste.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="gui">U redu</span>.</p></li>
</ol></div></div></div>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents">
<div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#passwords" title="Šifre">Šifre</a></li></ul></div>
</div></div>
<div class="links seealsolinks"><div class="inner">
<div class="title"><h2><span class="title">Vidite i</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="user-goodpassword.html" title="Odaberite sigurne šifre.">Odaberite sigurne šifre.</a><span class="desc"> — Koristite duže, komplikovanije šifre.</span>
</li></ul></div>
</div></div>
</div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
