<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zaboravio sam šifru!</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="user-accounts.html" title="Korisnički nalozi">Korisnici</a> › <a class="trail" href="user-accounts.html#passwords" title="Šifre">Šifre</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zaboravio sam šifru!</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">Važno je da izaberete ne samo <span class="link"><a href="user-goodpassword.html" title="Odaberite sigurne šifre.">dobru i sigurnu šifru</a></span>,vec i onu koju ćete zapamtiti. Ako zaboravite vašu šifru kojom se prijavljujete na vas računarski nalog,pratite sljedeće korake da je resetujete.</p>
<div class="note note-important" title="Važna"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako imate kodiran home directory,nećete biti u mogućnosti da resetujete zaboravljenu sifru.</p></div></div></div></div>
<p class="p">Ako samo želite promijeniti Vasu sifru,pogledajte <span class="link"><a href="korisnicka-promjenasifre.html" title="korisnicka-promjenasifre">korisnicka-promjenasifre</a></span>.</p>
<div role="navigation" class="links sectionlinks"><div class="inner"><div class="region"><ul>
<li class="links "><a href="user-forgottenpassword.html#reset-password-grub2" title="Resetujte šifru koristeci Grub">Resetujte šifru koristeci Grub</a></li>
<li class="links "><a href="user-forgottenpassword.html#live-cd" title="Resetovanje sifre koristeci CD ili USB">Resetovanje sifre koristeci CD ili USB</a></li>
<li class="links "><a href="user-forgottenpassword.html#delete-keyring" title="Riješite se keyring-a">Riješite se keyring-a</a></li>
</ul></div></div></div>
</div>
<div id="reset-password-grub2" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Resetujte šifru koristeci Grub</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps">
<p class="p">Restartujte Vas racunar i držite <span class="key"><kbd>Shift</kbd></span> za vrijeme dizanja sistema da biste usli u Grub izbornik.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako imate dual-boot mašinu i prilikom paljenja računara birate koji operativni sistem želite da se pokren, Grub meni treba da se pojavi bez korištenja tipke <span class="key"><kbd>Shift</kbd></span>.</p></div></div></div></div>
<div class="note" title="Napomena"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako ne možete pristupiti Grub izborniku,i zbog toga ne mozete odabrati dizanje u recovery režimu,možete  <span class="link"><a href="user-forgottenpassword.html#live-cd" title="Resetovanje sifre koristeci CD ili USB">koristiti CD da resetujete Vasu šifru</a></span>.</p></div></div></div></div>
</li>
<li class="steps"><p class="p">Pritisnite strelicu dole na vasoj tastaturi da biste istaknuli liniju koja zavrsava sa rijecima 'recovery mode',zatim pritisnite <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps"><p class="p">Vas računar ce zatim poceti sa butanjem. Nakon par trenutaka, pojavit će se <span class="gui">Recovery Menu</span>. Koristite Vašu strelicu dole da biste istaknuli <span class="gui">korijen</span> i pritisnite<span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps">
<p class="p">Na <span class="cmd">#</span> simbolu, unesite:</p>
<p class="p"><span class="cmd">passwd <span class="var">korisničko ime</span></span>, gdje <span class="var">korisničko ime</span> je korisničko ime računa kojem mijenjate sifru.</p>
</li>
<li class="steps"><p class="p">Od Vas će se tražiti da unesete novu UNIX šifru,i da potvrdite novu šifru.</p></li>
<li class="steps">
<p class="p">Zatim ukucajte:</p>
<p class="p"># <span class="cmd">reboot</span></p>
</li>
</ol></div></div></div>
<p class="p">Nakon sto ste se uspjesno logovali,necete biti u mogucnosti da pristupite vasoj keyring sifri(posto se ne sjecate stare sifre). Ovo znaci da sve snimljene sifre za bezicne mreze,racune,itd. nece biti pristupacne. Morat cete <span class="link"><a href="#delete-keyring" title="Riješite se keyring-a">obrisati stari keyring</a></span> i startovati novi.</p>
</div></div>
</div></div>
<div id="live-cd" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Resetovanje sifre koristeci CD ili USB</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Pokreni CD ili USB</p></li>
<li class="steps"><p class="p">Pripremite Vaš uredjaj.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F2</kbd></span></span>da biste dobili<span class="gui">Pokreni aplikaciju</span> prozor.</p></li>
<li class="steps">
<p class="p">Ukucajte <span class="cmd">gksu nautilus</span> da pokrenete menadžer datoteka sa sirokim sistemskim privilegijama.</p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Unutar uređaja koji ste montirali,mozete provjeriti je li to ispravan uredjaj klikanjem na <span class="gui"> kuću</span>a zatim na vase korisnicko ime.</p></div></div></div></div>
</li>
<li class="steps">
<p class="p">Idite u gornji lijevi direktorij montiranog uredjaja. Zatim idite u <span class="gui">etc</span> direktorij.</p>
<p class="p">Locirajte 'shadow' datoteku i napravite rezervnu kopiju'.</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Desni klik na shadow datoteku i izaberite <span class="gui">kopiraj</span>.</p></li>
<li class="steps"><p class="p">Zatim desni klik na prazan prostor i izaberite <span class="gui">umetni</span>.</p></li>
<li class="steps"><p class="p"><span class="link"><a href="files-rename.html" title="Preimenujte datoteku ili folder">Promijenite ime</a></span>kopije "shadow.bak".</p></li>
</ol></div></div></div>
</li>
<li class="steps"><p class="p">Uredite originalnu shadow datoteku sa tekst uređivačom.</p></li>
<li class="steps">
<p class="p">Nadjite Vaš korisnicki račun za koji ste zaboravili čifru. Trebao bi izgledati nesto poput ovoga (znakovi nakon dvotačke će biti različiti):</p>
<p class="p">korisničko ime:$1$2abCd0E ili</p>
<p class="p">korisničko ime:$1$2abCd0E:13721a:0:99999:7:::</p>
</li>
<li class="steps">
<p class="p">Obrišite znakove prije prve dvotačke i poslije druge dvotačke. Ovo ce sklonuti šifru sa računa.</p>
<p class="p">Sačuvajte datoteku,izađite iz svega i ponovo pokrenite Vaš računar bez CD ili USB.</p>
</li>
<li class="steps"><p class="p">Kada se uključite u instalaciju, kliknite vaše ime u izborniku. Otvorite <span class="gui">Moj Račun</span> i resetujte vašu lozinku.</p></li>
<li class="steps"><p class="p">Za <span class="gui">Trenutnu šifru</span> ne unosite ništa,pošsto je vasa trenutna šifra prazna. Samo kliknite <span class="gui">Autentificiraj</span> i unesite Vašu novu šifru.</p></li>
</ol></div></div></div>
<p class="p">Nakon sto ste se uspjesno logovali,necete biti u mogucnosti da pristupite vasoj keyring sifri(posto se ne sjecate stare sifre). Ovo znaci da sve snimljene sifre za bezicne mreze,racune,itd. nece biti pristupacne. Morat cete <span class="link"><a href="#delete-keyring" title="Riješite se keyring-a">obrisati stari keyring</a></span> i startovati novi.</p>
</div></div>
</div></div>
<div id="delete-keyring" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Riješite se keyring-a</span></h2></div>
<div class="region"><div class="contents">
<div class="note note-warning" title="Upozoranje"><div class="inner"><div class="region"><div class="contents"><p class="p">Ovo će obrisati sve vase snimljene šifre za bežične mreze,instant chat naloge,i sl. Uradite ovo samo ako se ne možete sjetiti sifre koju ste koristili za Vas keyring.</p></div></div></div></div>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Idite u vašu Home fasciklu kucajući 'home' u <span class="gui">Crtica</span>.</p></li>
<li class="steps"><p class="p">Pritisnite <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>h</kbd></span></span> (ili kliknite <span class="guiseq"><span class="gui">Pogled</span> ▸ <span class="gui">Prikaži skrivene datoteke</span></span>.)</p></li>
<li class="steps"><p class="p">Dupli klik na folder  <span class="file">~/.local/share</span>.</p></li>
<li class="steps"><p class="p">Dupli klik na folder pod imenom keyrings.</p></li>
<li class="steps"><p class="p">Obrišite sve datoteke koje nađete u keyrings folderu.</p></li>
<li class="steps"><p class="p">Ponovo pokrenuti računar.</p></li>
</ol></div></div></div>
<p class="p">Nakon što ponovno pokrenete računar i logujete se bit ćete pitani da unesete vaše šifre za bežične mreže.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#passwords" title="Šifre">Šifre</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
