<!DOCTYPE html>
<html lang=sk>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Zabudol som heslo!</title>
<link rel="stylesheet" type="text/css" href="sk.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Príručka pre Ubuntu desktop"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomocník"></span></span> Príručka pre Ubuntu desktop</a> » <a class="trail" href="prefs.html" title="Užívateľské a systémové nastavenia">Settings</a> » <a class="trail" href="user-accounts.html" title="Užívateľský účet">Users</a> › <a class="trail" href="user-accounts.html#passwords" title="Heslá">Heslá</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Zabudol som heslo!</span></h1></div>
<div class="region">
<div class="contents">
<p class="p">
     It is important to choose not only <span class="link"><a href="user-goodpassword.html" title="Zvoľte si bezpečné heslo">a good
 and secure password</a></span>, but also one that you can remember. If you have
 forgotten the password to log in to your computer account, you can follow the
 following steps to reset it.
  </p>
<div class="note note-important" title="Dôležité"><div class="inner"><div class="region"><div class="contents"><p class="p">
     If you have an encrypted home directory, you will not be able to reset a
 forgotten password.
  </p></div></div></div></div>
<p class="p">
  If you simply want to change your password, see <span class="link"><a href="user-changepassword.html" title="Zmeniť heslo">Zmeniť heslo</a></span>.
  </p>
<div role="navigation" class="links sectionlinks"><div class="inner"><div class="region"><ul>
<li class="links "><a href="user-forgottenpassword.html#reset-password-grub2" title="Resetovanie hesla pomocou Grub">Resetovanie hesla pomocou Grub</a></li>
<li class="links "><a href="user-forgottenpassword.html#live-cd" title="Obnoviť heslo pomocou Live CD alebo USB">Obnoviť heslo pomocou Live CD alebo USB</a></li>
<li class="links "><a href="user-forgottenpassword.html#delete-keyring" title="Get rid of the keyring">Get rid of the keyring</a></li>
</ul></div></div></div>
</div>
<div id="reset-password-grub2" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Resetovanie hesla pomocou Grub</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps">
<p class="p">
           Restart your computer, and hold down <span class="key"><kbd>Shift</kbd></span> during bootup
 to get into the Grub menu.
           </p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">
           If you have a dual-boot machine and you choose at boot time which
 operating system to boot into, the Grub menu should appear without the need to
 hold down <span class="key"><kbd>Shift</kbd></span>.
           </p></div></div></div></div>
<div class="note" title="Poznámka"><div class="inner"><div class="region"><div class="contents"><p class="p">If you are unable to get into the Grub boot menu, and therefore cannot choose to boot into recovery mode, you can <span class="link"><a href="user-forgottenpassword.html#live-cd" title="Obnoviť heslo pomocou Live CD alebo USB">use a live CD to reset your user password</a></span>.
           </p></div></div></div></div>
</li>
<li class="steps"><p class="p">Stlačením šípky nadol na klávesnici zvýraznite riadok, ktorý končí slovom 'režim obnovenia', potom stlačte <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps"><p class="p">Váš počítač teraz spustí bootovanie. Po chvíli sa objaví <span class="gui">Ponuka obnovy</span>. Použitím šípky nadol zvýraznite <span class="gui">root</span> a stačte <span class="key"><kbd>Enter</kbd></span>.</p></li>
<li class="steps">
<p class="p">Na <span class="cmd">#</span> znak, typ:</p>
<p class="p"><span class="cmd">passwd <span class="var">užívateľské meno</span></span>, kde <span class="var">užívateľské meno </span> je užívateľské meno účtu kde ste zmenili heslo.</p>
</li>
<li class="steps"><p class="p">Budete vyzvaný na zadanie nového UNIX hesla a potvrdenie nového hesla.</p></li>
<li class="steps">
<p class="p">Typ:</p>
<p class="p">
           # <span class="cmd">reboot</span>
           </p>
</li>
</ol></div></div></div>
<p class="p">
       After you successfully log in, you will not be able to access your keyring
 (since you don't remember the old password).  This means that all your saved
 passwords for wireless networks, jabber accounts, etc. will no longer be
 accessible.  You will need to <span class="link"><a href="#delete-keyring" title="Get rid of the keyring">delete the old
 keyring</a></span> and start a new one.
     </p>
</div></div>
</div></div>
<div id="live-cd" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Obnoviť heslo pomocou Live CD alebo USB</span></h2></div>
<div class="region"><div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Bootovanie z Live CD alebo USB.</p></li>
<li class="steps"><p class="p">Pripojenie disku.</p></li>
<li class="steps"><p class="p">
           Press <span class="keyseq"><span class="key"><kbd>Alt</kbd></span>+<span class="key"><kbd>F2</kbd></span></span> to get the <span class="gui">Run
           Application</span> window.
           </p></li>
<li class="steps">
<p class="p">Typ <span class="cmd">gksu nautilus</span> spustenie správcu súborov s právami celého systému.</p>
<div class="note note-tip" title="Tip"><div class="inner"><div class="region"><div class="contents"><p class="p">Zariadenie stačí pripojiť, kliknutím <span class="gui"> domov </span> môžete skontrolovať že sa jedná o správne zariadenie a svoje užívateľské meno.</p></div></div></div></div>
</li>
<li class="steps">
<p class="p">Prejsť na najvyššiu úroveň adresára pripojenej jednotky.Potom prejdite do <span class="gui">atď</span> adresára.</p>
<p class="p">Prejdite 'tieňom' súbor a vytvorťe záložnú kópiu:</p>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Pravým tlačidlom kliknite na tieň súboru a vyberte <span class="gui">kopírovať</span>.</p></li>
<li class="steps"><p class="p">Potom kliknite pravým tlačidlom myši na prázdne miesto a vyberte <span class="gui">prilepiť</span>.</p></li>
<li class="steps"><p class="p"><span class="link"><a href="files-rename.html" title="Premenovanie súborov a priečinkov">Premenovať</a></span> zálohovanie "shadow.bak".</p></li>
</ol></div></div></div>
</li>
<li class="steps"><p class="p">Úpravy pôvodného "shadow" súboru pomocou textového editoru.</p></li>
<li class="steps">
<p class="p">Nájdite si užívateľské meno ktoré ste zabudli. Malo by vyzerať neako takto (znaky za dvojbodkou sa budú líšiť):</p>
<p class="p">vaše meno:$1$2abCd0E alebo</p>
<p class="p">vaše meno:$1$2abCd0E:13721a:0:99999:7:::</p>
</li>
<li class="steps">
<p class="p">Odstránte znaky po prvej dvojbodke a pred druhou dvojbodkou. Tým sa odstráni heslo k účtu.</p>
<p class="p">Uložte súbor, ukončite všetko a reštartujte váš počítač s live CD alebo USB.</p>
</li>
<li class="steps"><p class="p">
           When you boot back into your installation, click your name in the menu bar. Open <span class="gui">My Account</span> and reset your password.
           </p></li>
<li class="steps"><p class="p">Pre <span class="gui">Aktuálne heslo</span> nezadávajte nič, pretože vaše aktuálne heslo je prázdne. Stačí kliknúť <span class="gui">Overenie</span> a potvrdťe nové heslo.</p></li>
</ol></div></div></div>
<p class="p">
       After you successfully log in, you will not be able to access your keyring
 (since you don't remember the old password).  This means that all your saved
 passwords for wireless networks, jabber accounts, etc. will no longer be
 accessible.  You will need to <span class="link"><a href="#delete-keyring" title="Get rid of the keyring">delete the old
 keyring</a></span> and start a new one.
     </p>
</div></div>
</div></div>
<div id="delete-keyring" class="sect"><div class="inner">
<div class="hgroup"><h2 class="title"><span class="title">Get rid of the keyring</span></h2></div>
<div class="region"><div class="contents">
<div class="note note-warning" title="Upozornenie"><div class="inner"><div class="region"><div class="contents"><p class="p">Tým sa odstránia všetky uložené heslá pre bezdrôtové siete, okamžité zasielanie správ účtov, atď. Iba ak si nepamätáte heslo, ktoré ste používali pre vaše kľúče.</p></div></div></div></div>
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">
    Go to your Home folder by typing 'home' in the <span class="gui">Dash</span>.
   </p></li>
<li class="steps"><p class="p">Stačte <span class="keyseq"><span class="key"><kbd>Ctrl</kbd></span>+<span class="key"><kbd>h</kbd></span></span> (alebo kliknite <span class="guiseq"><span class="gui">Zobraziť</span> ▸ <span class="gui">Zobraziť skryté súbory</span></span>.)</p></li>
<li class="steps"><p class="p">
    Double click on the folder <span class="file">~/.local/share</span>.
   </p></li>
<li class="steps"><p class="p">Kliknite dvakrát na priečinok s názvom kľúčov.</p></li>
<li class="steps"><p class="p">Odstránťe všetky súbory ktoré nájdete v zložke kľúčov.</p></li>
<li class="steps"><p class="p">Reštartujte počítač.</p></li>
</ol></div></div></div>
<p class="p">Po reštartovaní a prihlásení budete vyzvaný zadať svoje heslo k bezdrôtovému pripojeniu.</p>
</div></div>
</div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Viac informácií</span></h2></div>
<div class="region"><ul><li class="links "><a href="user-accounts.html#passwords" title="Heslá">Heslá</a></li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
