<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Wacom grafički tablet</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Wacom grafički tablet</span></h1></div>
<div class="region">
<div class="contents"><div class="links topiclinks"><div class="inner"><div class="region">
<div class="linkdiv "><a class="linkdiv" href="wacom-multi-monitor.html" title="Izabrite monitor"><span class="title">Izabrite monitor</span><span class="linkdiv-dash"> — </span><span class="desc">Mapirajte Wacom tablet prema posebnom monitoru.</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="wacom-stylus.html" title="Konfigurisi olovku"><span class="title">Konfigurisi olovku</span><span class="linkdiv-dash"> — </span><span class="desc">Definišite funkciju dugmadi i pritisak Wacom olovke</span></a></div>
<div class="linkdiv "><a class="linkdiv" href="wacom-left-handed.html" title="Korištenje tableta lijevom rukom"><span class="title">Korištenje tableta lijevom rukom</span><span class="linkdiv-dash"> — </span><span class="desc">Podesi Wacom tablet na <span class="gui">Lijevoruku Orijentaciju</span></span></a></div>
<div class="linkdiv "><a class="linkdiv" href="wacom-mode.html" title="Podesite režim praćenja Wacom tablice"><span class="title">Podesite režim praćenja Wacom tablice</span><span class="linkdiv-dash"> — </span><span class="desc">Birajte na tabletu između tablet načina rada i miš načina rada</span></a></div>
</div></div></div></div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="prefs.html" title="Korisničke &amp; sistemske postavke">Korisničke &amp; sistemske postavke</a><span class="desc"> — <span class="link"><a href="keyboard.html" title="Tastatura">Tastatura</a></span>, <span class="link"><a href="mouse.html" title="Miš">miš</a></span>, <span class="link"><a href="prefs-display.html" title="Prikaži &amp; ekran">ekran</a></span>, <span class="link"><a href="prefs-language.html" title="Regija i jezik">jezici</a></span>, <span class="link"><a href="user-accounts.html" title="Korisnički nalozi">korisnički računi</a></span>…</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
