<!DOCTYPE html>
<html lang=bs>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Konfigurisi olovku</title>
<link rel="stylesheet" type="text/css" href="bs.css">
<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="jquery.syntax.js"></script><script type="text/javascript" src="yelp.js"></script>
</head>
<body id="home">
<script src="https://ssl.google-analytics.com/urchin.js" type="text/javascript"></script><script type="text/javascript">
        _uacct = "UA-1018242-8";
        urchinTracker();
      </script><div id="container">
<div id="container-inner">
<div id="mothership"><ul>
<li><a href="http://www.ubuntu.com/partners">Partners</a></li>
<li><a href="http://www.ubuntu.com/support">Support</a></li>
<li><a href="http://www.ubuntu.com/community">Community</a></li>
<li><a href="http://www.ubuntu.com">Ubuntu.com</a></li>
</ul></div>
<div id="header">
<h1 id="ubuntu-header"><a href="https://help.ubuntu.com/">Ubuntu Documentation</a></h1>
<ul id="main-menu">
<li><a class="main-menu-item current" href="../../">Official Documentation</a></li>
<li><a href="https://help.ubuntu.com/community/CommunityHelpWiki">Community Help Wiki</a></li>
<li><a href="http://community.ubuntu.com/contribute/documentation/">Contribute</a></li>
</ul>
</div>
<div id="menu-search"><div id="search-box">
<noscript><form action="https://www.google.com/cse" id="cse-search-box"><div>
<input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq"><input type="hidden" name="ie" value="UTF-8"><input type="text" name="q" size="21"><input type="submit" name="sa" value="Search">
</div></form></noscript>
<script>
                document.write('<form action="../../search.html" id="cse-search-box">');
                document.write('  <div>');
                document.write('    <input type="hidden" name="cof" value="FORID:9">');
                document.write('    <input type="hidden" name="cx" value="003883529982892832976:e2vwumte3fq">');
                document.write('    <input type="hidden" name="ie" value="UTF-8">');
                document.write('    <input type="text" name="q" size="21">');
                document.write('    <input type="submit" name="sa" value="Search">');
                document.write('  </div>');
                document.write('</form>');
              </script>
</div></div>
<div class="trails" role="navigation"><div class="trail">
<span style="color: #333">Ubuntu 17.04</span> » <a class="trail" href="index.html" title="Ubuntu Desktop Priručnik"><span class="media"><span class="media media-image"><img src="figures/ubuntu-logo.png" height="16" width="16" class="media media-inline" alt="Pomoć"></span></span> Ubuntu Desktop Priručnik</a> » <a class="trail" href="prefs.html" title="Korisničke &amp; sistemske postavke">Podešavanja</a> » <a class="trail" href="wacom.html" title="Wacom grafički tablet">Wacom grafički tablet</a> » </div></div>
<div id="cwt-content" class="clearfix content-area"><div id="page">
<div id="content">
<div class="hgroup"><h1 class="title"><span class="title">Konfigurisi olovku</span></h1></div>
<div class="region">
<div class="contents">
<div class="steps"><div class="inner"><div class="region"><ol class="steps">
<li class="steps"><p class="p">Klikom na ikonu na desnoj strani <span class="gui">menu trake</span> i odabirom <span class="gui">Sistemske Postavke</span>.</p></li>
<li class="steps">
<p class="p">Otvorite <span class="gui">Wacom Graphics Tablet</span></p>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">Ako nije pronađen tablet, pitat će vas <span class="gui">Molim Vas uključite i upalite Vaš Wacom tablet</span></p></div></div></div></div>
</li>
<li class="steps">
<p class="p">Donji dio panela sadrzi detalje i postavke specificne ta vasu olovku, ime uredjaja (klasu olovke) i dijagram lijevo. Ove postavke se mogu podesiti.</p>
<div class="list"><div class="inner"><div class="region"><ul class="list" style="list-style-type:disc">
<li class="list"><p class="p"><span class="gui">Osjećaj gumice::</span> koristi klizac da se podesi odjecaj (prevodi fizicki pritisak u brojnu vrijednost) izmedju <span class="gui">Meki</span> i <span class="gui">Firm</span>.</p></li>
<li class="list"><p class="p"><span class="gui">Dugme/Točkić</span> konfiguracija (ove postavke se odrazavaju na olovku). Pritisnite meni pored svake labele da izaberete neku od sledecih funkcija: Bez Akcije, Lijevi Klik Misem. Srednji Klik Misem, Desni Klik Misem, Skrolanje Gore, Skrolanje dole, Skrolanje Lijevo, Skrolanje Desno, Nazad, Naprijed</p></li>
<li class="list"><p class="p"><span class="gui">Osjećaj pritiska:</span> korisiti klizac da podesis "osjecaj" izmedju <span class="gui">Soft</span> i <span class="gui">Firm</span>.</p></li>
</ul></div></div></div>
</li>
</ol></div></div></div>
<div class="note note-tip" title="Savjet"><div class="inner"><div class="region"><div class="contents"><p class="p">If you have more than one stylus, when the additional
 stylus gets close to the tablet, a pager will be displayed next to the stylus
 device name. Use the pager to choose which stylus to configure.</p></div></div></div></div>
</div>
<div class="sect sect-links" role="navigation">
<div class="hgroup"></div>
<div class="contents"><div class="links guidelinks"><div class="inner">
<div class="title"><h2><span class="title">Više informacija</span></h2></div>
<div class="region"><ul><li class="links ">
<a href="wacom.html" title="Wacom grafički tablet">Wacom grafički tablet</a><span class="desc"> — Prilagodite postavke vašeg Wacom tableta.</span>
</li></ul></div>
</div></div></div>
</div>
</div>
<div class="clear"></div>
</div>
<div id="pagebottom"></div>
</div></div>
</div>
<div id="footer"><p>The material in this document is available under a free license, see <a href="../../legal.html">Legal</a> for details.<br>
          For information on contributing see the <a href="https://wiki.ubuntu.com/DocumentationTeam">Ubuntu Documentation Team wiki page</a>.
          To report errors in this documentation, <a href="https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs">file a bug</a>.</p></div>
</div>
</body>
</html>
